__mem.h
void * memcpy(void *dst, const void *src, size_t n)
Referenced by __copy_rom_section, __StringWrite, fread, fwrite, memmove, wmemcpy.
void * memset(void *dst, int val, size_t n)
References __fill_mem.
Referenced by __find_unopened_file, __init_bss_section.
void __fill_mem(void *dst, int val, unsigned long n)
References cpd, deref_auto_inc, lpd.
Referenced by memset.