__start_for_spuce.c
USE_FAR_ADDRESSING_TO_TEXT_SECTION
void main()
Referenced by __start.
asm void __start(void)
References __dest_os, __eppc_vxworks, __init_data, __init_registers, __init_user, exit, main, r1, r3, USE_FAR_ADDRESSING_TO_TEXT_SECTION.
void exit(int)
Referenced by __sformatter, __start, __wsformatter, abort, ANSI_Exit, raise, TRKSuppAccessFile.
static asm void __init_registers(void)
References r1, r2.
Referenced by __start.
static void __init_data(void)
References __copy_rom_section, __init_bss_section, __rom_copy_info::addr, __bss_init_info::addr, __rom_copy_info::rom, __rom_copy_info::size, __bss_init_info::size.
Referenced by __start.
static void __copy_rom_section(void *dst, const void *src, unsigned long size)
References memcpy, size.
Referenced by __init_data.
static void __init_bss_section(void *dst, unsigned long size)
References memset, size.
Referenced by __init_data.