UART.h
UARTBaudRate
typedef int UARTError
UARTError InitializeUART(UARTBaudRate baudRate)
Referenced by __init_uart_console.
UARTError InitializeIntDrivenUART(UARTBaudRate baudRate, unsigned char intDrivenInput, unsigned char intDrivenOutput, volatile unsigned char **inputPendingPtrRef)
UARTError TerminateUART(void)
UARTError ReadUARTPoll(char *c)
UARTError ReadUART1(char *c)
Referenced by __read_console.
UARTError ReadUARTN(void *bytes, unsigned long length)
Referenced by __read_console.
UARTError ReadUARTString(char *string, unsigned long limit, char terminateChar)
UARTError WriteUART1(char c)
UARTError WriteUARTN(const void *bytes, unsigned long length)
Referenced by __write_console.
UARTError WriteUARTString(const char *string)
void UARTInterruptHandler(void)