abort_exit.c
max_funcs
int __aborting
Referenced by _libc_exit_, abort.
void(* atexit_funcs[max_funcs])(void)[max_funcs])(void)
Referenced by _CleanUpMSL, _libc_exit_, atexit.
long atexit_curr_func
Referenced by _CleanUpMSL, _libc_exit_, atexit.
void(* __atexit_funcs[max_funcs])(void)[max_funcs])(void)
Referenced by __atexit, __exit.
long __atexit_curr_func
Referenced by __atexit, __exit.
void(* __stdio_exit) (void)=0)(void)=0
Referenced by __stdio_atexit, _CleanUpMSL, _libc_exit_.
void(* __console_exit) (void)=0)(void)=0
Referenced by __exit, _CleanUpMSL.
void(* __atexit_hook) (void))(void)
Referenced by __setup_exit.
void(* ___atexit_hook) (void))(void)
Referenced by __setup_exit.
short exitSetup
Referenced by __setup_exit.
void __destroy_global_chain(void)
References __global_destructor_chain, DestructorChain::destructor, DTORCALL_COMPLETE, DestructorChain::next, DestructorChain::object.
Referenced by _CleanUpMSL, _libc_exit_.
void ___teardown_be(int)
Referenced by __exit.
static void ANSI_Exit(void)
References exit.
Referenced by __setup_exit.
static void ANSI__Exit(void)
References __exit.
Referenced by __setup_exit.
void __setup_exit(void)
References ___atexit_hook, __atexit_hook, ANSI__Exit, ANSI_Exit, exitSetup.
Referenced by __atexit, __stdio_atexit, atexit.
void abort(void)
References __aborting, exit, raise.
Referenced by __assertion_failed.
int atexit(void(*func)(void))
References __begin_critical_region, __end_critical_region, __setup_exit, atexit_curr_func, atexit_funcs, atexit_funcs_access, max_funcs.
int __atexit(void(*func)(void))
References __atexit_curr_func, __atexit_funcs, __begin_critical_region, __end_critical_region, __setup_exit, atexit_funcs_access, max_funcs.
void _libc_exit_(int status)
References __aborting, __begin_critical_region, __destroy_global_chain, __end_critical_region, __exit, __stdio_exit, atexit_curr_func, atexit_funcs, atexit_funcs_access.
void __exit(int status)
References ___teardown_be, __atexit_curr_func, __atexit_funcs, __begin_critical_region, __console_exit, __end_critical_region, __kill_critical_regions, _ExitProcess, atexit_funcs_access.
Referenced by _libc_exit_, ANSI__Exit.
void _CleanUpMSL()
References __begin_critical_region, __console_exit, __destroy_global_chain, __end_critical_region, __kill_critical_regions, __pool_free_all, __stdio_exit, atexit_curr_func, atexit_funcs, atexit_funcs_access.