abort_exit.h
void(* __stdio_exit) (void))(void)
Referenced by __stdio_atexit, _CleanUpMSL, _libc_exit_.
void(* __console_exit) (void))(void)
Referenced by __exit, _CleanUpMSL.
int __aborting
Referenced by _libc_exit_, abort.
int __atexit(void(*func)(void))
References __atexit_curr_func, __atexit_funcs, __begin_critical_region, __end_critical_region, __setup_exit, atexit_funcs_access, max_funcs.
void __exit(int status)
References ___teardown_be, __atexit_curr_func, __atexit_funcs, __begin_critical_region, __console_exit, __end_critical_region, __kill_critical_regions, _ExitProcess, atexit_funcs_access.
Referenced by _libc_exit_, ANSI__Exit.
void __setup_exit(void)
References ___atexit_hook, __atexit_hook, ANSI__Exit, ANSI_Exit, exitSetup.
Referenced by __atexit, __stdio_atexit, atexit.
void _CleanUpMSL()
References __begin_critical_region, __console_exit, __destroy_global_chain, __end_critical_region, __kill_critical_regions, __pool_free_all, __stdio_exit, atexit_curr_func, atexit_funcs, atexit_funcs_access.
void _ExitProcess(void)
Referenced by __exit.