ansi_files.h
set_eof
set_error
__std(FILE) *__find_unopened_file(void)
void __init_file(__std(FILE) *file, __std(__file_modes) mode, char *buff, __std(size_t) size)
Referenced by __handle_reopen, __open_string_file, freopen, tmpfile.
void __close_all(void)
References __begin_critical_region, __end_critical_region, __files, fclose, files_access, NULL.
Referenced by __stdio_atexit.
int __flush_all(void)
References __files, EOF, fflush, NULL.
Referenced by fflush.
int __flush_line_buffered_output_files(void)
References __files, EOF, fflush, NULL.
Referenced by fread.