ansi_files.c
console_buff_mode
console_buff_size
typedef unsigned char console_buff[console_buff_size][console_buff_size]
console_buff stdin_buff
console_buff stdout_buff
console_buff stderr_buff
FILE __files[_STATIC_FILES][_STATIC_FILES]
Referenced by __close_all, __find_unopened_file, __flush_all, __flush_line_buffered_output_files.
FILE * __find_unopened_file(void)
References __files, memset, NULL.
Referenced by __handle_open, fopen, tmpfile.
void __init_file(FILE *file, __file_modes mode, char *buff, size_t size)
References __close_file, __close_string, __position_file, __read_file, __read_string, __write_file, __write_string, setvbuf, size.
void __close_all(void)
References __begin_critical_region, __end_critical_region, __files, fclose, files_access, NULL.
Referenced by __stdio_atexit.
int __flush_all(void)
References __files, EOF, fflush, NULL.
Referenced by fflush.
int __flush_line_buffered_output_files(void)
References __files, EOF, fflush, NULL.
Referenced by fread.