arith.c
int() abs(int n)
long() labs(long n)
Referenced by __dec2num.
div_t div(int numerator, int denominator)
References div_t::quot, div_t::rem.
Referenced by fmodf, leap_days, leap_days.
ldiv_t ldiv(long numerator, long denominator)
References ldiv_t::quot, ldiv_t::rem.
int __add(int *x, int y)
Referenced by adjust, adjust.
int __ladd(long *x, long y)
Referenced by __tm2time, __tm2time.
int __mul(int *x, int y)
int __lmul(long *x, long y)
Referenced by __tm2time, __tm2time.
div_t __div(int x, int y)
References div_t::quot, div_t::rem.
Referenced by adjust, adjust, leap_days, leap_days.
ldiv_t __ldiv(long x, long y)
References ldiv_t::quot, ldiv_t::rem.
int __mod(int x, int y)
Referenced by __leap_year, leap_year, week_num, week_num.
long __lmod(long x, long y)