buffer_io.c
alignment_mask
void __convert_from_newlines(unsigned char *buf, size_t *n)
Referenced by __flush_buffer.
void __convert_to_newlines(unsigned char *buf, size_t *n)
Referenced by __load_buffer.
void __prep_buffer(FILE *file)
Referenced by __flush_buffer, __load_buffer.
int __load_buffer(FILE *file, size_t *bytes_loaded, int alignment)
References __convert_to_newlines, __dont_align_buffer, __prep_buffer.
int __flush_buffer(FILE *file, size_t *bytes_flushed)
References __convert_from_newlines, __prep_buffer.
int setvbuf(FILE *file, char *buff, int mode, size_t size)
References alignment_mask, fflush, size.
Referenced by __init_file, setbuf.
void setbuf(FILE *file, char *buff)
References setvbuf.