buffer_io.h
void __convert_from_newlines(unsigned char *p, __std(size_t) *n)
void __convert_to_newlines(unsigned char *p, __std(size_t) *n)
void __prep_buffer(__std(FILE) *file)
Referenced by __open_string_file, __put_char, fread, fwrite.
int __load_buffer(__std(FILE) *file, __std(size_t) *bytes_loaded, int alignment)
Referenced by __get_char, fread.
int __flush_buffer(__std(FILE) *file, __std(size_t) *bytes_flushed)
Referenced by __put_char, _fseek, fflush, fwrite.