char_io.c
int __get_char(FILE *file)
References __align_buffer, __load_buffer, EOF, NULL, set_eof, set_error.
int fgetc(FILE *file)
References getc.
Referenced by __FileRead.
int() getc(FILE *file)
References getc.
Referenced by fgetc, fgets, getc, gets.
int() getchar(void)
References getchar.
Referenced by getchar.
char * fgets(char *s, int n, FILE *file)
References EOF, getc, NULL.
char * gets(char *s)
References EOF, getc, NULL.
int ungetc(int c, FILE *file)
References EOF, fwide.
Referenced by __FileRead.
int __ungotten(FILE *file)
References EOF.
int __put_char(int c, FILE *file)
References __flush_buffer, __prep_buffer, __stdio_atexit, EOF, fseek, NULL, set_error.
int fputc(int c, FILE *file)
References putc.
int() putc(int c, FILE *file)
References putc.
Referenced by fputc, fputs, putc, puts.
int() putchar(int c)
References putchar.
Referenced by putchar.
int fputs(const char *s, FILE *file)
References EOF, putc.
int puts(const char *s)
References EOF, putc.