hash_table
typedef size_t hash_table::size_type
typedef Key hash_table::key_type
typedef Value hash_table::value_type
typedef HashFunction hash_table::hash_function
typedef ptrdiff_t hash_table::difference_type
typedef value_type& hash_table::reference
typedef const value_type& hash_table::const_reference
typedef value_type* hash_table::pointer
typedef const value_type* hash_table::const_pointer
typedef pair<iterator, bool> hash_table::pair_iterator_bool
typedef pair<iterator, iterator> hash_table::pair_iterator_iterator
typedef pair<const_iterator, const_iterator> hash_table::pair_citerator_citerator
typedef hash_node_allocator_type::pointer hash_table::link_type
friend class iterator
friend class const_iterator
HashFunction hash_table::hash
Referenced by bkt_num_key, hash_funct, operator=, swap.
KeyEqual hash_table::equals
Referenced by count, equal_range, equal_range, find, find, key_comp, lower_bound, lower_bound, operator=, swap, upper_bound, upper_bound.
size_type hash_table::num_elements
Referenced by clear, copy_from, erase_bucket, erase_bucket, insert_equal, insert_equal, insert_equal, insert_equal, insert_unique, insert_unique, insert_unique, insert_unique, size, swap.
KeyOfValue hash_table::get_key
Referenced by bkt_num, bkt_num, count, equal_range, equal_range, find, find, lower_bound, lower_bound, operator=, swap, upper_bound, upper_bound.
link_type hash_table::free_list
Referenced by clear, get_node, put_node, swap.
hash_node_allocator_type hash_table::hash_node_allocator
Referenced by clear, delete_node, get_node, new_node.
value_allocator_type hash_table::value_allocator
Referenced by delete_node, new_node, put_node.
vector<link_type, allocator_link_type> hash_table::buckets
Referenced by begin, begin, bkt_num_key, bucket_count, clear, copy_from, count, elems_in_bucket, equal_range, equal_range, erase_bucket, erase_bucket, find, find, lower_bound, lower_bound, hash_table::iterator::operator++, hash_table::const_iterator::operator++, operator=, operator==, swap, upper_bound, upper_bound.
typedef hash_table::ALLOC_BIND(hash_node) hash_node_allocator_type
typedef hash_table::ALLOC_BIND(value_type) value_allocator_type
typedef hash_table::ALLOC_BIND(link_type) allocator_link_type
hash_table::hash_table(size_type initSize, const HashFunction &hf=HashFunction(), const KeyEqual &equal=KeyEqual(), const KeyOfValue &ext=KeyOfValue())
hash_table::hash_table(const value_type *first, const value_type *last, size_type initSize, const HashFunction &hf=HashFunction(), const KeyEqual &equal=KeyEqual(), const KeyOfValue &ext=KeyOfValue())
References insert_equal.
hash_table::hash_table(const HT_TYPE &ht)
References copy_from.
HT_TYPE & hash_table::operator=(const HT_TYPE &ht)
References buckets, clear, copy_from, equals, get_key, hash, WRITE_LOCK.
void hash_table::swap(HT_TYPE &ht)
References buckets, equals, free_list, get_key, hash, num_elements, WRITE_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::swap, hash_multimap< Key, T, HashFunction, KeyEqual >::swap, hash_multiset< Key, HashFunction, KeyEqual >::swap, hash_set< Key, HashFunction, KeyEqual >::swap.
bool hash_table::operator==(const HT_TYPE &ht)
References buckets, READ_LOCK.
bool hash_table::operator!=(const HT_TYPE &ht)
hash_table::~hash_table()
References clear.
size_type hash_table::size() const
References num_elements, READ_LOCK.
Referenced by empty, hash_map< Key, T, HashFunction, KeyEqual >::size, hash_multimap< Key, T, HashFunction, KeyEqual >::size, hash_multiset< Key, HashFunction, KeyEqual >::size, hash_set< Key, HashFunction, KeyEqual >::size.
size_type hash_table::max_size() const
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::max_size, hash_multimap< Key, T, HashFunction, KeyEqual >::max_size, hash_multiset< Key, HashFunction, KeyEqual >::max_size, hash_set< Key, HashFunction, KeyEqual >::max_size.
bool hash_table::empty() const
References READ_LOCK, size.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::empty, hash_multimap< Key, T, HashFunction, KeyEqual >::empty, hash_multiset< Key, HashFunction, KeyEqual >::empty, hash_set< Key, HashFunction, KeyEqual >::empty.
KeyEqual hash_table::key_comp() const
References equals, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::key_comp, hash_multimap< Key, T, HashFunction, KeyEqual >::key_comp, hash_multiset< Key, HashFunction, KeyEqual >::key_comp, hash_set< Key, HashFunction, KeyEqual >::key_comp, hash_multimap< Key, T, HashFunction, KeyEqual >::value_comp, hash_multiset< Key, HashFunction, KeyEqual >::value_comp, hash_set< Key, HashFunction, KeyEqual >::value_comp.
hash_function hash_table::hash_funct() const
References hash, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::hash_funct, hash_multimap< Key, T, HashFunction, KeyEqual >::hash_funct, hash_multiset< Key, HashFunction, KeyEqual >::hash_funct, hash_set< Key, HashFunction, KeyEqual >::hash_funct.
size_type hash_table::bucket_count() const
References buckets.
iterator hash_table::begin()
References buckets, end, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::begin, hash_multimap< Key, T, HashFunction, KeyEqual >::begin, hash_multiset< Key, HashFunction, KeyEqual >::begin, hash_set< Key, HashFunction, KeyEqual >::begin, hash_map< Key, T, HashFunction, KeyEqual >::begin, hash_multimap< Key, T, HashFunction, KeyEqual >::begin, hash_multiset< Key, HashFunction, KeyEqual >::begin, hash_set< Key, HashFunction, KeyEqual >::begin.
iterator hash_table::end()
References READ_LOCK.
Referenced by begin, begin, hash_map< Key, T, HashFunction, KeyEqual >::end, hash_multimap< Key, T, HashFunction, KeyEqual >::end, hash_multiset< Key, HashFunction, KeyEqual >::end, hash_set< Key, HashFunction, KeyEqual >::end, hash_map< Key, T, HashFunction, KeyEqual >::end, hash_multimap< Key, T, HashFunction, KeyEqual >::end, hash_multiset< Key, HashFunction, KeyEqual >::end, hash_set< Key, HashFunction, KeyEqual >::end, equal_range, equal_range.
const_iterator hash_table::begin() const
References buckets, end, READ_LOCK.
const_iterator hash_table::end() const
References READ_LOCK.
size_type hash_table::max_bucket_count() const
size_type hash_table::elems_in_bucket(size_type bucket) const
References buckets, READ_LOCK.
pair_iterator_bool hash_table::insert_unique(const value_type &obj)
References insert_unique_noresize, num_elements, resize.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::insert, hash_set< Key, HashFunction, KeyEqual >::insert, hash_map< Key, T, HashFunction, KeyEqual >::insert, hash_set< Key, HashFunction, KeyEqual >::insert, hash_map< Key, T, HashFunction, KeyEqual >::insert, hash_set< Key, HashFunction, KeyEqual >::insert.
iterator hash_table::insert_equal(const value_type &obj)
References insert_equal_noresize, num_elements, resize.
Referenced by hash_table, hash_multimap< Key, T, HashFunction, KeyEqual >::insert, hash_multiset< Key, HashFunction, KeyEqual >::insert, hash_multimap< Key, T, HashFunction, KeyEqual >::insert, hash_multiset< Key, HashFunction, KeyEqual >::insert, hash_multimap< Key, T, HashFunction, KeyEqual >::insert, hash_multiset< Key, HashFunction, KeyEqual >::insert.
reference hash_table::find_or_insert(const value_type &obj)
iterator hash_table::find(const key_type &key)
References bkt_num_key, buckets, equals, get_key, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::find, hash_multimap< Key, T, HashFunction, KeyEqual >::find, hash_multiset< Key, HashFunction, KeyEqual >::find, hash_set< Key, HashFunction, KeyEqual >::find, hash_map< Key, T, HashFunction, KeyEqual >::find, hash_multimap< Key, T, HashFunction, KeyEqual >::find, hash_multiset< Key, HashFunction, KeyEqual >::find, hash_set< Key, HashFunction, KeyEqual >::find.
const_iterator hash_table::find(const key_type &key) const
References bkt_num_key, buckets, equals, get_key, READ_LOCK.
size_type hash_table::count(const key_type &key) const
References bkt_num_key, buckets, equals, get_key, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::count, hash_multimap< Key, T, HashFunction, KeyEqual >::count, hash_multiset< Key, HashFunction, KeyEqual >::count, hash_set< Key, HashFunction, KeyEqual >::count.
size_type hash_table::erase(const key_type &key)
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::erase, hash_multimap< Key, T, HashFunction, KeyEqual >::erase, hash_multiset< Key, HashFunction, KeyEqual >::erase, hash_set< Key, HashFunction, KeyEqual >::erase, hash_map< Key, T, HashFunction, KeyEqual >::erase, hash_multimap< Key, T, HashFunction, KeyEqual >::erase, hash_multiset< Key, HashFunction, KeyEqual >::erase, hash_set< Key, HashFunction, KeyEqual >::erase, hash_map< Key, T, HashFunction, KeyEqual >::erase, hash_multimap< Key, T, HashFunction, KeyEqual >::erase, hash_multiset< Key, HashFunction, KeyEqual >::erase, hash_set< Key, HashFunction, KeyEqual >::erase.
void hash_table::erase(const iterator &it)
void hash_table::erase(iterator first, iterator last)
void hash_table::erase(const const_iterator &it)
void hash_table::erase(const_iterator first, const_iterator last)
void hash_table::resize(size_type num_elements_hint)
Referenced by insert_equal, insert_equal, insert_equal, insert_equal, insert_unique, insert_unique, insert_unique, insert_unique.
pair< iterator, bool > hash_table::insert_unique_noresize(const value_type &obj)
Referenced by insert_unique, insert_unique, insert_unique, insert_unique.
iterator hash_table::insert_equal_noresize(const value_type &obj)
Referenced by insert_equal, insert_equal, insert_equal, insert_equal.
void hash_table::insert_unique(const value_type *f, const value_type *l)
References insert_unique_noresize, num_elements, resize.
void hash_table::insert_equal(const value_type *f, const value_type *l)
References insert_equal_noresize, num_elements, resize.
void hash_table::insert_unique(const_iterator f, const_iterator l)
References insert_unique_noresize, num_elements, resize.
void hash_table::insert_equal(const_iterator f, const_iterator l)
References insert_equal_noresize, num_elements, resize.
void hash_table::insert_unique(iterator f, iterator l)
References insert_unique_noresize, num_elements, resize.
void hash_table::insert_equal(iterator f, iterator l)
References insert_equal_noresize, num_elements, resize.
iterator hash_table::lower_bound(const key_type &key)
References bkt_num_key, buckets, equals, get_key, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::lower_bound, hash_multimap< Key, T, HashFunction, KeyEqual >::lower_bound, hash_multiset< Key, HashFunction, KeyEqual >::lower_bound, hash_set< Key, HashFunction, KeyEqual >::lower_bound, hash_map< Key, T, HashFunction, KeyEqual >::lower_bound, hash_multimap< Key, T, HashFunction, KeyEqual >::lower_bound, hash_multiset< Key, HashFunction, KeyEqual >::lower_bound, hash_set< Key, HashFunction, KeyEqual >::lower_bound.
const_iterator hash_table::lower_bound(const key_type &key) const
References bkt_num_key, buckets, equals, get_key, READ_LOCK.
iterator hash_table::upper_bound(const key_type &key)
References bkt_num_key, buckets, equals, get_key, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::upper_bound, hash_multimap< Key, T, HashFunction, KeyEqual >::upper_bound, hash_multiset< Key, HashFunction, KeyEqual >::upper_bound, hash_set< Key, HashFunction, KeyEqual >::upper_bound, hash_multiset< Key, HashFunction, KeyEqual >::upper_bound, hash_set< Key, HashFunction, KeyEqual >::upper_bound.
const_iterator hash_table::upper_bound(const key_type &key) const
References bkt_num_key, buckets, equals, get_key, READ_LOCK.
pair_iterator_iterator hash_table::equal_range(const key_type &key)
References bkt_num_key, buckets, end, equals, get_key, READ_LOCK.
Referenced by hash_map< Key, T, HashFunction, KeyEqual >::equal_range, hash_multimap< Key, T, HashFunction, KeyEqual >::equal_range, hash_multiset< Key, HashFunction, KeyEqual >::equal_range, hash_set< Key, HashFunction, KeyEqual >::equal_range, hash_map< Key, T, HashFunction, KeyEqual >::equal_range, hash_multimap< Key, T, HashFunction, KeyEqual >::equal_range, hash_multiset< Key, HashFunction, KeyEqual >::equal_range, hash_set< Key, HashFunction, KeyEqual >::equal_range.
pair_citerator_citerator hash_table::equal_range(const key_type &key) const
References bkt_num_key, buckets, end, equals, get_key, READ_LOCK.
unsigned long hash_table::__stl_next_prime(unsigned long n) const
References _MN_.
Referenced by next_size.
void hash_table::copy_from(const HT_TYPE &ht)
References buckets, clear, MSIPL_CATCH, MSIPL_TRY, new_node, next, NULL, num_elements, WRITE_LOCK.
Referenced by hash_table, operator=.
void hash_table::erase_bucket(const size_type n, link_type first, link_type last)
References buckets, erase_bucket, next, num_elements, put_node, WRITE_LOCK.
Referenced by erase_bucket.
void hash_table::erase_bucket(const size_type n, link_type last)
References buckets, next, num_elements, put_node, WRITE_LOCK.
link_type hash_table::get_node()
References free_list, hash_node_allocator, WRITE_LOCK.
Referenced by new_node.
link_type hash_table::new_node(const value_type &obj)
References get_node, hash_node_allocator, MSIPL_CATCH, MSIPL_TRY, value_allocator.
Referenced by copy_from.
void hash_table::delete_node(link_type n)
References hash_node_allocator, value_allocator.
Referenced by clear.
void hash_table::put_node(link_type n)
References free_list, value_allocator.
Referenced by clear, erase_bucket, erase_bucket.
void hash_table::clear(bool delete_it=false)
References buckets, delete_node, free_list, hash_node_allocator, next, num_elements, put_node.
Referenced by copy_from, operator=, ~hash_table.
size_type hash_table::next_size(size_type n) const
References __stl_next_prime.
size_type hash_table::bkt_num_key(const key_type &key) const
References bkt_num_key, buckets.
Referenced by bkt_num, bkt_num, bkt_num_key, count, equal_range, equal_range, find, find, lower_bound, lower_bound, upper_bound, upper_bound.
size_type hash_table::bkt_num(const value_type &obj) const
References bkt_num_key, get_key.
size_type hash_table::bkt_num_key(const key_type &key, size_t n) const
References hash.
size_type hash_table::bkt_num(const value_type &obj, size_t n) const
References bkt_num_key, get_key.