ctype.c
ctrl
motn
spac
punc
digi
hexd
lowc
uppc
dhex
uhex
lhex
const unsigned char __ctype_map[256][256]
const unsigned char __lower_map[256][256]
const unsigned char __upper_map[256][256]
int() isalnum(int c)
int() isalpha(int c)
Referenced by __strtoul.
int() iscntrl(int c)
int() isdigit(int c)
Referenced by __strtold, __strtoul, parse_format, parse_format.
int() isgraph(int c)
int() islower(int c)
int() isprint(int c)
int() ispunct(int c)
int() isspace(int c)
Referenced by __sformatter, __strtold, __strtoul.
int() isupper(int c)
int() isxdigit(int c)
int tolower(int c)
int toupper(int c)
Referenced by __strtoul, __wcstoul.