direct_io.c
size_t fread(void *ptr, size_t memb_size, size_t num_memb, FILE *file)
References __align_buffer, __dont_align_buffer, __flush_line_buffered_output_files, __load_buffer, __prep_buffer, fwide, memcpy, NULL, set_eof, set_error.
Referenced by getwc, getwchar.
size_t fwrite(const void *ptr, size_t memb_size, size_t num_memb, FILE *file)
References __flush_buffer, __memrchr, __prep_buffer, __stdio_atexit, fseek, fwide, memcpy, NULL, set_error.
Referenced by __FileWrite, __wFileWrite, putwc, putwchar.