dolphin_trk.h
DSError TRKInitializeTarget()
References DS_NoError, gTRKState, TRKState::isStopped, lc_base, TRKState::msr.
Referenced by TRKInitializeNub.
void EnableMetroTRKInterrupts()
u32 TRKTargetTranslate(u32 param_0)
References Extended1_PPC_6xx_7xx::DBAT3U, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, lc_base.
Referenced by __TRK_copy_vectors, TRK_copy_vector.
void TRK__read_aram(register int c, register u32 p2, void *p3)
void TRK__write_aram(register int c, register u32 p2, void *p3)
void __TRK_copy_vectors(void)
References TRK_copy_vector, TRK_ISR_OFFSETS, TRKTargetTranslate.
Referenced by __declspec.