dolphin_trk.c
EXCEPTIONMASK_ADDR
u32 lc_base
Referenced by TRKInitializeTarget, TRKTargetTranslate.
u32 TRK_ISR_OFFSETS[15][15]
Referenced by __TRK_copy_vectors.
u8 gTRKInterruptVectorTable[][]
Referenced by TRK_copy_vector.
__declspec(section ".init")
References __TRK_copy_vectors.
asm void InitMetroTRK()
References Default_PPC::CR, ProcessorState_PPC_6xx_7xx::Default, Default_PPC::GPR, gTRKCPUState, InitMetroTRKCommTable, Default_PPC::LR, Default_PPC::PC, r1, r3, r4, r5, TRKSaveExtended1Block.
void EnableMetroTRKInterrupts(void)
References EnableEXI2Interrupts.
u32 TRKTargetTranslate(u32 param_0)
References Extended1_PPC_6xx_7xx::DBAT3U, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, lc_base.
Referenced by __TRK_copy_vectors, TRK_copy_vector.
void TRK_copy_vector(u32 offset)
References gTRKInterruptVectorTable, TRK_flush_cache, TRK_memcpy, TRKTargetTranslate.
Referenced by __TRK_copy_vectors.
void __TRK_copy_vectors(void)
References TRK_copy_vector, TRK_ISR_OFFSETS, TRKTargetTranslate.
Referenced by __declspec.
DSError TRKInitializeTarget()
References DS_NoError, gTRKState, TRKState::isStopped, lc_base, TRKState::msr.
Referenced by TRKInitializeNub.