dolphin_trk_glue.h
typedef void(* DBCommFunc) (void))(void)
typedef u32(* DBPollFunc) (void))(void)
typedef void(* DBCommInitFunc) (volatile u8 **, __OSInterruptHandler))(volatile u8 **, __OSInterruptHandler)
typedef int(* DBCommReadFunc) (void *, size_t))(void *, size_t)
typedef int(* DBCommWriteFunc) (const void *, size_t))(const void *, size_t)
typedef struct DBCommTable DBCommTable
DSError TRKInitializeIntDrivenUART(u32 param_0, u32 param_1, u32 param_2, volatile u8 **param_3)
References DS_NoError, gDBCommTable, DBCommTable::initialize_func, TRKEXICallBack.
Referenced by TRKInitializeNub.
void UnreserveEXI2Port(void)
References DBCommTable::close_func, gDBCommTable.
Referenced by TRKTargetContinue.
void ReserveEXI2Port(void)
References gDBCommTable, DBCommTable::open_func.
Referenced by TRKTargetContinue.
int TRKPollUART(void)
References gDBCommTable, DBCommTable::peek_func.
Referenced by TRKTestForPacket.
UARTError TRKReadUARTN(void *bytes, u32 length)
References gDBCommTable, DBCommTable::read_func.
Referenced by TRKTestForPacket.
UARTError TRKWriteUARTN(const void *bytes, u32 length)
References gDBCommTable, DBCommTable::write_func.
Referenced by TRKMessageSend.
void TRKLoadContext(OSContext *ctx, u32 r4)
References r1, r2, r3, r4, r5, r6, TRKInterruptHandler.
Referenced by TRKEXICallBack.
int InitMetroTRKCommTable(int hwId)
References DBCommTable::close_func, gDBCommTable, HARDWARE_GDEV, DBCommTable::init_interrupts_func, DBCommTable::initialize_func, DBCommTable::open_func, DBCommTable::peek_func, DBCommTable::read_func, DBCommTable::write_func.
Referenced by InitMetroTRK.
void EnableEXI2Interrupts(void)
References gDBCommTable, DBCommTable::init_interrupts_func.
Referenced by EnableMetroTRKInterrupts.
void TRK_board_display(char *str)
Referenced by TRKNubWelcome.