dolphin_trk_glue.c
DBCommTable gDBCommTable
Referenced by EnableEXI2Interrupts, InitMetroTRKCommTable, ReserveEXI2Port, TRKInitializeIntDrivenUART, TRKPollUART, TRKReadUARTN, TRKWriteUARTN, UnreserveEXI2Port.
asm void TRKLoadContext(OSContext *ctx, u32)
References r1, r2, r3, r4, r5, r6, TRKInterruptHandler.
Referenced by TRKEXICallBack.
void TRKEXICallBack(__OSInterrupt param_0, OSContext *ctx)
References TRKLoadContext.
Referenced by TRKInitializeIntDrivenUART.
int InitMetroTRKCommTable(int hwId)
References DBCommTable::close_func, gDBCommTable, HARDWARE_GDEV, DBCommTable::init_interrupts_func, DBCommTable::initialize_func, DBCommTable::open_func, DBCommTable::peek_func, DBCommTable::read_func, DBCommTable::write_func.
Referenced by InitMetroTRK.
void TRKUARTInterruptHandler()
Referenced by TRKInterruptHandler.
DSError TRKInitializeIntDrivenUART(u32 param_0, u32 param_1, u32 param_2, volatile u8 **param_3)
References DS_NoError, gDBCommTable, DBCommTable::initialize_func, TRKEXICallBack.
Referenced by TRKInitializeNub.
void EnableEXI2Interrupts(void)
References gDBCommTable, DBCommTable::init_interrupts_func.
Referenced by EnableMetroTRKInterrupts.
int TRKPollUART(void)
References gDBCommTable, DBCommTable::peek_func.
Referenced by TRKTestForPacket.
UARTError TRKReadUARTN(void *bytes, u32 length)
References gDBCommTable, DBCommTable::read_func.
Referenced by TRKTestForPacket.
UARTError TRKWriteUARTN(const void *bytes, u32 length)
References gDBCommTable, DBCommTable::write_func.
Referenced by TRKMessageSend.
void ReserveEXI2Port(void)
References gDBCommTable, DBCommTable::open_func.
Referenced by TRKTargetContinue.
void UnreserveEXI2Port(void)
References DBCommTable::close_func, gDBCommTable.
Referenced by TRKTargetContinue.
void TRK_board_display(char *str)
Referenced by TRKNubWelcome.