e_exp.c
double one
Referenced by __ieee754_exp.
double halF[2][2]
Referenced by __ieee754_exp.
double big
Referenced by __ieee754_exp.
double twom1000
Referenced by __ieee754_exp.
double o_threshold
Referenced by __ieee754_exp.
double u_threshold
Referenced by __ieee754_exp.
double ln2HI[2][2]
Referenced by __ieee754_exp.
double ln2LO[2][2]
Referenced by __ieee754_exp.
double invln2
Referenced by __ieee754_exp.
double P1
Referenced by __ieee754_exp.
double P2
Referenced by __ieee754_exp.
double P3
Referenced by __ieee754_exp.
double P4
Referenced by __ieee754_exp.
double P5
Referenced by __ieee754_exp.
double __ieee754_exp(double x)
References __HI, __LO, big, halF, invln2, ln2HI, ln2LO, o_threshold, one, P1, P2, P3, P4, P5, twom1000, u_threshold.
Referenced by __ieee754_cosh, __ieee754_sinh, erf, erfc, exp.