e_log.c
double ln2_hi
Referenced by __ieee754_log.
double ln2_lo
Referenced by __ieee754_log.
double two54
Referenced by __ieee754_log.
double Lg1
Referenced by __ieee754_log.
double Lg2
Referenced by __ieee754_log.
double Lg3
Referenced by __ieee754_log.
double Lg4
Referenced by __ieee754_log.
double Lg5
Referenced by __ieee754_log.
double Lg6
Referenced by __ieee754_log.
double Lg7
Referenced by __ieee754_log.
double zero
Referenced by __ieee754_log.
double __ieee754_log(double x)
References __HI, __LO, errno, Lg1, Lg2, Lg3, Lg4, Lg5, Lg6, Lg7, ln2_hi, ln2_lo, t1, t2, two54, zero.
Referenced by __ieee754_acosh, __ieee754_lgamma_r, __ieee754_log10, asinh, log.