e_rem_pio2.c
int two_over_pi[][]
Referenced by __ieee754_rem_pio2.
int npio2_hw[][]
Referenced by __ieee754_rem_pio2.
double zero
Referenced by __ieee754_rem_pio2.
double half
Referenced by __ieee754_rem_pio2.
double two24
Referenced by __ieee754_rem_pio2.
double invpio2
Referenced by __ieee754_rem_pio2.
double pio2_1
Referenced by __ieee754_rem_pio2.
double pio2_1t
Referenced by __ieee754_rem_pio2.
double pio2_2
Referenced by __ieee754_rem_pio2.
double pio2_2t
Referenced by __ieee754_rem_pio2.
double pio2_3
Referenced by __ieee754_rem_pio2.
double pio2_3t
Referenced by __ieee754_rem_pio2.
int __ieee754_rem_pio2(double x, y)
References __HI, __kernel_rem_pio2, __LO, fabs, half, invpio2, npio2_hw, pio2_1, pio2_1t, pio2_2, pio2_2t, pio2_3, pio2_3t, two24, two_over_pi, zero.
Referenced by cos, sin, tan.