file_io.stub.c
temp_file_info temp_info[FOPEN_MAX][FOPEN_MAX]
Referenced by find_temp_info.
static temp_file_info * find_temp_info(short refnum)
References temp_file_info::refnum, temp_info.
Referenced by __open_temp_file.
int __open_file(const char *name, __file_modes mode, __file_handle *handle)
Referenced by __open_temp_file.
int __open_temp_file(__file_handle *handle)
References __open_file, __temp_file_mode, __temp_file_name, find_temp_info, temp_file_info::refnum, temp_file_info::spec.
int __read_file(__file_handle handle, unsigned char *buffer, size_t *count, __idle_proc idle_proc)
int __write_file(__file_handle handle, unsigned char *buffer, size_t *count, __idle_proc idle_proc)
int __position_file(__file_handle handle, fpos_t *position, int mode, __idle_proc idle_proc)
int __close_file(__file_handle handle)
void __temp_file_name(char *name_str, void *filespec)
Referenced by __open_temp_file, tmpnam.
int __delete_file(const char *name)
Referenced by remove.
int __rename_file(const char *old_name, const char *new_name)