file_io.c
__file_modes __temp_file_mode
Referenced by __open_temp_file, tmpfile.
int remove(const char *name)
References __delete_file.
char * tmpnam(char *name)
References __temp_file_name, __tls, NULL.
FILE * tmpfile(void)
References __begin_critical_region, __end_critical_region, __find_unopened_file, __init_file, __open_temp_file, __stdio_atexit, __temp_file_mode, files_access, NULL.
int fclose(FILE *file)
References EOF, fflush, NULL.
Referenced by __close_all, __handle_reopen, freopen.
int fflush(FILE *file)
References __flush_all, __flush_buffer, EOF, ftell, NULL, set_error.
Referenced by __flush_all, __flush_line_buffered_output_files, __kernel_standard, fclose, setvbuf.
FILE * fopen(const char *name, const char *mode)
References __begin_critical_region, __end_critical_region, __find_unopened_file, files_access, freopen.
FILE * freopen(const char *name, const char *mode, FILE *file)
References __get_file_modes, __init_file, __open_file, __stdio_atexit, clearerr, fclose, fseek, NULL.
Referenced by fopen.
FILE * __handle_open(__file_handle handle, const char *mode)
References __begin_critical_region, __end_critical_region, __find_unopened_file, __handle_reopen, files_access.
FILE * __handle_reopen(__file_handle handle, const char *mode, FILE *file)
References __get_file_modes, __init_file, __stdio_atexit, clearerr, fclose, NULL.
Referenced by __handle_open.
int __get_file_modes(const char *mode, __file_modes *modes)
Referenced by __handle_reopen, freopen.
void __set_idle_proc(FILE *file, __idle_proc idle_proc)