file_io.h
_MSL_DLLDATA __std(__file_modes) __temp_file_mode
int __open_file(const char *name, __std(__file_modes) mode, __std(__file_handle) *handle)
Referenced by freopen.
int __open_temp_file(__std(__file_handle) *handle)
Referenced by tmpfile.
int __read_file(__std(__file_handle) handle, unsigned char *buffer, __std(size_t) *count, __std(__idle_proc) idle_proc)
Referenced by __init_file.
int __write_file(__std(__file_handle) handle, unsigned char *buffer, __std(size_t) *count, __std(__idle_proc) idle_proc)
Referenced by __init_file.
int __position_file(__std(__file_handle) handle, __std(fpos_t) *position, int mode, __std(__idle_proc) idle_proc)
Referenced by __init_file.
int __close_file(__std(__file_handle) handle)
Referenced by __init_file.
void __temp_file_name(char *name_str, void *)
Referenced by __open_temp_file, tmpnam.
int __delete_file(const char *name)
Referenced by remove.
int __rename_file(const char *old_name, const char *new_name)
int __get_file_modes(const char *mode, __std(__file_modes) *modes)
int __flush_line_buffered_output_files(void)