file_pos.c
fpos_t _ftell(FILE *file)
References errno.
Referenced by _fseek, fgetpos, ftell.
long ftell(FILE *file)
References _ftell.
Referenced by fflush.
int fgetpos(FILE *file, fpos_t *pos)
References _ftell.
int _fseek(FILE *file, fpos_t offset, int mode)
References __flush_buffer, _ftell, errno, NULL, set_error.
Referenced by fseek, fsetpos.
int fseek(FILE *file, long offset, int mode)
References _fseek.
Referenced by __put_char, freopen, fwrite, rewind.
int fsetpos(FILE *file, const fpos_t *pos)
References _fseek.
void rewind(FILE *file)
References fseek.