flush_cache.h
void TRK_flush_cache(void *param_1, int param_2)
Referenced by TRK_copy_vector, TRKPPCAccessSpecialReg, TRKTargetFlushCache, TRKTargetSupportRequest.