hyperbolicsf.c
float sinhf(float arg)
References fabsf.
Referenced by sinh.
float coshf(float arg)
Referenced by cosh.
float tanhf(float arg)
References fabsf.
Referenced by tanh.