inverse_trig.c
__PI_O2
__PI
float _inv_sqrtf(float x)
References __frsqrte.
Referenced by acosf, asinf, sqrtf.
float atan2f(float y, float x)
References __HI, __PI, __PI_O2, atanf.
Referenced by atan2.
float acosf(float x)
References __PI_O2, _inv_sqrtf, atan.
Referenced by acos.
float asinf(float x)
References _inv_sqrtf, atan.
Referenced by asin.
float atanf(float x)
References __HI, __PI_O2.
Referenced by atan, atan2f.