k_cos.c
double one
Referenced by __kernel_cos.
double C1
Referenced by __kernel_cos.
double C2
Referenced by __kernel_cos.
double C3
Referenced by __kernel_cos.
double C4
Referenced by __kernel_cos.
double C5
Referenced by __kernel_cos.
double C6
Referenced by __kernel_cos.
double __kernel_cos(double x, double y)
References __HI, __LO, C1, C2, C3, C4, C5, C6, one.
Referenced by cos, sin, sin_pi.