k_standard.c
WRITE2
HUGE_VAL
double zero
Referenced by __kernel_standard.
double __kernel_standard(double x, double y, int type)
References __HI, _IEEE_, _LIB_VERSION, _POSIX_, _SVID_, exception::arg1, exception::arg2, DOMAIN, errno, fflush, HUGE, HUGE_VAL, matherr, exception::name, OVERFLOW, exception::retval, rint, SING, TLOSS, exception::type, UNDERFLOW, WRITE2, zero.
Referenced by acos, acosh, asin, atan2, atanh, cosh, exp, fmod, gamma, hypot, lgamma, log, log10, pow, remainder, sinh, sqrt.