k_sin.c
double half
Referenced by __kernel_sin.
double S1
Referenced by __kernel_sin.
double S2
Referenced by __kernel_sin.
double S3
Referenced by __kernel_sin.
double S4
Referenced by __kernel_sin.
double S5
Referenced by __kernel_sin.
double S6
Referenced by __kernel_sin.
double __kernel_sin(double x, double y, int iy)
References __HI, half, S1, S2, S3, S4, S5, S6.
Referenced by cos, sin, sin_pi.