mainloop.c
void TRKHandleRequestEvent(TRKEvent *event)
References TRKEvent::msgBufID, TRKDispatchMessage, TRKGetBuffer.
Referenced by TRKNubMainLoop.
void TRKHandleSupportEvent(TRKEvent *event)
References TRKTargetSupportRequest.
Referenced by TRKNubMainLoop.
void TRKIdle()
References TRKTargetContinue, TRKTargetStopped.
Referenced by TRKNubMainLoop.
void TRKNubMainLoop(void)
References TRKEvent::eventType, gTRKInputPendingPtr, NUBEVENT_Breakpoint, NUBEVENT_Exception, NUBEVENT_Null, NUBEVENT_Request, NUBEVENT_Shutdown, NUBEVENT_Support, TRKDestructEvent, TRKGetInput, TRKGetNextEvent, TRKHandleRequestEvent, TRKHandleSupportEvent, TRKIdle, TRKTargetInterrupt.
Referenced by TRK_main.