math_ppc.h
float sqrtf(float x)
References __frsqrte.
float _inv_sqrtf(float x)
References __frsqrte, inv_sqrt_guess, inv_sqrt_guess2.
Referenced by acosf, asinf.
double sqrt(double x)
References __frsqrte.
double fabs(double x)
float fabsf(float x)
Referenced by cosf, fabs, fmodf, fmodf, sinf, sinhf, tanhf.
float fmodf(register float x, register float y)
References fabsf.