mbstring.c
int mblen(const char *s, size_t n)
References mbtowc.
int mbtowc(wchar_t *pwc, const char *s, size_t n)
Referenced by __sformatter, __wpformatter, mblen.
int wctomb(char *s, wchar_t wchar)
Referenced by __wsformatter.
size_t mbstowcs(wchar_t *pwcs, const char *s, size_t n)
Referenced by __wpformatter.
size_t wcstombs(char *s, const wchar_t *pwcs, size_t n)
Referenced by __pformatter.