mem.c
void *() memmove(void *dst, const void *src, size_t n)
References __copy_longs_aligned, __copy_longs_rev_aligned, __copy_longs_rev_unaligned, __copy_longs_unaligned, __min_bytes_for_long_copy, memcpy.
Referenced by wmemmove.
void * memset(void *dst, int val, size_t n)
References __fill_mem.
Referenced by __find_unopened_file, __init_bss_section.
void * memchr(const void *src, int val, size_t n)
References NULL.
Referenced by __pformatter, __wpformatter.
void * __memrchr(const void *src, int val, size_t n)
References NULL.
Referenced by fwrite.
int memcmp(const void *src1, const void *src2, size_t n)