mem_TRK.h
void * TRK_memset(void *dst, int val, size_t n)
Referenced by TRKResetBuffer.
void * TRK_memcpy(void *dst, const void *src, size_t n)
Referenced by TRK_copy_vector, TRKAppendBuffer, TRKCopyEvent, TRKReadBuffer.