mem_funcs.h
__min_bytes_for_long_copy
void __copy_mem(void *dst, const void *src, unsigned long n)
References __copy_longs_aligned, __copy_longs_unaligned, __min_bytes_for_long_copy.
void __move_mem(void *dst, const void *src, unsigned long n)
References __copy_longs_aligned, __copy_longs_rev_aligned, __copy_longs_rev_unaligned, __copy_longs_unaligned, __min_bytes_for_long_copy.
void __copy_longs_aligned(void *dst, const void *src, unsigned long n)
References cpd, cps, deref_auto_inc, lpd, lps.
Referenced by __copy_mem, __move_mem, memmove.
void __copy_longs_rev_aligned(void *dst, const void *src, unsigned long n)
References cpd, cps, lpd, lps.
Referenced by __move_mem, memmove.
void __copy_longs_unaligned(void *dst, const void *src, unsigned long n)
References cpd, cps, deref_auto_inc, lpd, lps, v1, v2.
Referenced by __copy_mem, __move_mem, memmove.
void __copy_longs_rev_unaligned(void *dst, const void *src, unsigned long n)
References cpd, cps, lpd, lps, v1, v2.
Referenced by __move_mem, memmove.
void __fill_mem(void *dst, int val, unsigned long n)
References cpd, deref_auto_inc, lpd.
Referenced by memset.