misc_io.c
void clearerr(FILE *file)
Referenced by __handle_reopen, freopen.
int() feof(FILE *file)
References feof.
Referenced by __FileRead, __wFileRead, feof.
int() ferror(FILE *file)
References ferror.
Referenced by __FileRead, __wFileRead, ferror.
void perror(const char *s)
References __strerror, errno, fprintf.
void __stdio_atexit(void)
References __close_all, __setup_exit, __stdio_exit.
Referenced by __handle_reopen, __put_char, freopen, fwrite, tmpfile.