misc_io.h
void __stdio_atexit(void)
References __close_all, __setup_exit, __stdio_exit.
Referenced by __handle_reopen, __put_char, freopen, fwrite, tmpfile.