mpc_7xx_603e.c
u8 gTRKRestoreFlags[9+3][9+3]
Referenced by TRKRestoreExtended1Block.
asm void TRKSaveExtended1Block()
References gTRKCPUState, r2.
Referenced by InitMetroTRK, TRKInterruptHandler.
asm void TRKRestoreExtended1Block()
References gTRKCPUState, gTRKRestoreFlags, r2, r3, r5, r6.
Referenced by TRKSwapAndGo.
u32 TRKTargetCPUMinorType(void)
Referenced by TRKTargetCPUType.