msg.h
typedef struct _TRK_Msg TRK_Msg
DSError TRKMessageSend(TRK_Msg *msg)
References DS_NoError, _TRK_Msg::m_msg, _TRK_Msg::m_msgLength, TRKWriteUARTN.
Referenced by TRKRequestSend, TRKSendACK, TRKSuppAccessFile.