msgbuf.h
DSError TRKInitializeMessageBuffers(void)
References DS_NoError, gTRKMsgBufs, TRKAcquireMutex, TRKInitializeMutex, TRKReleaseMutex, TRKSetBufferUsed.
Referenced by TRKInitializeNub.
DSError TRKSetBufferPosition(TRKBuffer *msg, u32 pos)
References DS_MessageBufferOverflow, DS_NoError, TRKBuffer::length, TRKBuffer::position.
Referenced by TRKDispatchMessage, TRKDoFlushCache, TRKDoReadMemory, TRKDoReadRegisters, TRKDoStep, TRKDoWriteMemory, TRKDoWriteRegisters, TRKGetInput, TRKRequestSend, TRKSuppAccessFile.
void * TRKGetBuffer(int)
References gTRKMsgBufs, NULL.
Referenced by TRKGetFreeBuffer, TRKGetInput, TRKHandleRequestEvent, TRKRequestSend, TRKSuppAccessFile.
void TRKResetBuffer(TRKBuffer *msg, BOOL keepData)
References TRKBuffer::data, TRKBuffer::length, TRKBuffer::position, TRK_memset, TRKMSGBUF_SIZE.
Referenced by TRKGetFreeBuffer, TRKMessageIntoReply.
void TRKReleaseBuffer(int idx)
References gTRKMsgBufs, TRKAcquireMutex, TRKReleaseMutex, TRKSetBufferUsed.
Referenced by TRKDestructEvent, TRKDoNotifyStopped, TRKGetInput, TRKRequestSend, TRKSuppAccessFile, TRKTestForPacket.
DSError TRKGetFreeBuffer(int *msgID, TRKBuffer **outMsg)
References DS_NoError, DS_NoMessageBufferAvailable, TRKBuffer::isInUse, NULL, TRKAcquireMutex, TRKGetBuffer, TRKReleaseMutex, TRKResetBuffer, TRKSetBufferUsed.
Referenced by TRKDoNotifyStopped, TRKSuppAccessFile, TRKTestForPacket.
DSError TRKAppendBuffer(TRKBuffer *msg, const void *data, size_t length)
References TRKBuffer::data, DS_MessageBufferOverflow, DS_NoError, TRKBuffer::length, TRKBuffer::position, TRK_memcpy.
Referenced by TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32, TRKAppendBuffer1_ui64, TRKDoReadMemory, TRKDoSupportMask.
DSError TRKAppendBuffer1_ui8(TRKBuffer *buffer, const u8 data)
References TRKBuffer::data, DS_MessageBufferOverflow, DS_NoError, TRKBuffer::length, TRKBuffer::position, TRKMSGBUF_SIZE.
Referenced by TRKAppendBuffer_ui8, TRKDoCPUType, TRKDoSupportMask, TRKDoVersions, TRKMessageIntoReply, TRKSuppAccessFile.
DSError TRKAppendBuffer1_ui16(TRKBuffer *buffer, const u16 data)
References gTRKBigEndian, TRKAppendBuffer.
Referenced by TRKDoReadMemory, TRKDoWriteMemory, TRKSuppAccessFile, TRKTargetAddExceptionInfo, TRKTargetAddStopInfo.
DSError TRKAppendBuffer1_ui32(TRKBuffer *buffer, const u32 data)
References gTRKBigEndian, TRKAppendBuffer.
Referenced by TRKAppendBuffer_ui32, TRKSuppAccessFile, TRKTargetAddExceptionInfo, TRKTargetAddStopInfo.
DSError TRKAppendBuffer1_ui64(TRKBuffer *buffer, const u64 data)
References gTRKBigEndian, TRKAppendBuffer.
DSError TRKAppendBuffer_ui8(TRKBuffer *buffer, const u8 *data, int count)
References count, DS_NoError, TRKAppendBuffer1_ui8.
Referenced by TRKSuppAccessFile.
DSError TRKAppendBuffer_ui32(TRKBuffer *buffer, const u32 *data, int count)
References count, DS_NoError, TRKAppendBuffer1_ui32.
DSError TRKReadBuffer1_ui8(TRKBuffer *buffer, u8 *data)
References TRKReadBuffer.
Referenced by TRKDispatchMessage, TRKDoFlushCache, TRKDoReadMemory, TRKDoReadRegisters, TRKDoStep, TRKDoWriteMemory, TRKDoWriteRegisters, TRKGetInput, TRKReadBuffer_ui8, TRKRequestSend, TRKSuppAccessFile.
DSError TRKReadBuffer1_ui16(TRKBuffer *buffer, u16 *data)
References DS_NoError, gTRKBigEndian, TRKReadBuffer.
Referenced by TRKDoReadMemory, TRKDoReadRegisters, TRKDoWriteMemory, TRKDoWriteRegisters, TRKSuppAccessFile.
DSError TRKReadBuffer1_ui32(TRKBuffer *buffer, u32 *data)
References DS_NoError, gTRKBigEndian, TRKReadBuffer.
Referenced by TRKDoFlushCache, TRKDoReadMemory, TRKDoStep, TRKDoWriteMemory, TRKReadBuffer_ui32.
DSError TRKReadBuffer1_ui64(TRKBuffer *buffer, u64 *data)
References gTRKBigEndian, TRKReadBuffer.
DSError TRKReadBuffer_ui8(TRKBuffer *buffer, u8 *data, int count)
References count, DS_NoError, TRKReadBuffer1_ui8.
Referenced by TRKSuppAccessFile.
DSError TRKReadBuffer_ui32(TRKBuffer *buffer, u32 *data, int count)
References count, DS_NoError, TRKReadBuffer1_ui32.
DSError TRKReadBuffer(TRKBuffer *msg, void *data, size_t length)
References TRKBuffer::data, DS_MessageBufferReadError, DS_NoError, TRKBuffer::length, TRKBuffer::position, TRK_memcpy.
Referenced by TRKDoWriteMemory, TRKReadBuffer1_ui16, TRKReadBuffer1_ui32, TRKReadBuffer1_ui64, TRKReadBuffer1_ui8.