msghndlr.c
static void TRKMessageIntoReply(TRKBuffer *buffer, u8 ackCmd, DSReplyError errSentInAck)
References TRKAppendBuffer1_ui8, TRKResetBuffer.
Referenced by TRKDoCPUType, TRKDoFlushCache, TRKDoReadMemory, TRKDoReadRegisters, TRKDoSupportMask, TRKDoVersions, TRKDoWriteMemory, TRKDoWriteRegisters, TRKStandardACK.
DSError TRKSendACK(TRKBuffer *buffer)
References DS_NoError, TRKMessageSend.
Referenced by TRKDoCPUType, TRKDoFlushCache, TRKDoReadMemory, TRKDoReadRegisters, TRKDoSupportMask, TRKDoVersions, TRKDoWriteMemory, TRKDoWriteRegisters, TRKStandardACK.
DSError TRKStandardACK(TRKBuffer *buffer, MessageCommandID commandID, DSReplyError replyError)
References DS_NoError, TRKMessageIntoReply, TRKSendACK.
Referenced by TRKDoConnect, TRKDoContinue, TRKDoCPUType, TRKDoDisconnect, TRKDoFlushCache, TRKDoReadMemory, TRKDoReadRegisters, TRKDoReset, TRKDoStep, TRKDoStop, TRKDoSupportMask, TRKDoUnsupported, TRKDoVersions, TRKDoWriteMemory, TRKDoWriteRegisters, TRKTestForPacket.
DSError TRKDoUnsupported(TRKBuffer *buffer)
References DSMSG_ReplyACK, DSREPLY_UnsupportedCommandError, TRKStandardACK.
DSError TRKDoConnect(TRKBuffer *buffer)
References DSMSG_ReplyACK, DSREPLY_NoError, TRKStandardACK.
DSError TRKDoDisconnect(TRKBuffer *buffer)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, TRKConstructEvent, TRKPostEvent, TRKStandardACK.
DSError TRKDoReset(TRKBuffer *buffer)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, TRKStandardACK.
DSError TRKDoVersions(TRKBuffer *buffer)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_NoError, DSREPLY_PacketSizeError, DSVersions::kernelMajor, DSVersions::kernelMinor, TRKBuffer::length, DSVersions::protocolMajor, DSVersions::protocolMinor, TRKAppendBuffer1_ui8, TRKMessageIntoReply, TRKSendACK, TRKStandardACK, TRKTargetVersions.
DSError TRKDoSupportMask(TRKBuffer *buffer)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_NoError, DSREPLY_PacketSizeError, TRKBuffer::length, TRKAppendBuffer, TRKAppendBuffer1_ui8, TRKMessageIntoReply, TRKSendACK, TRKStandardACK, TRKTargetSupportMask.
DSError TRKDoCPUType(TRKBuffer *buffer)
References DSCPUType::bigEndian, DSCPUType::cpuMajor, DSCPUType::cpuMinor, DSCPUType::defaultTypeSize, DS_NoError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_NoError, DSREPLY_PacketSizeError, DSCPUType::extended1TypeSize, DSCPUType::extended2TypeSize, DSCPUType::fpTypeSize, TRKBuffer::length, TRKAppendBuffer1_ui8, TRKMessageIntoReply, TRKSendACK, TRKStandardACK, TRKTargetCPUType.
DSError TRKDoReadMemory(TRKBuffer *buffer)
References DS_CWDSException, DS_InvalidMemory, DS_InvalidProcessID, DS_InvalidThreadID, DS_NoError, DS_OSError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidMemoryRange, DSREPLY_InvalidProcessID, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_ParameterError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, MEMACCESS_DebuggerMemory, MEMACCESS_UserMemory, TRKAppendBuffer, TRKAppendBuffer1_ui16, TRKMessageIntoReply, TRKReadBuffer1_ui16, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessMemory.
DSError TRKDoWriteMemory(TRKBuffer *buffer)
References DS_CWDSException, DS_InvalidMemory, DS_InvalidProcessID, DS_InvalidThreadID, DS_NoError, DS_OSError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidMemoryRange, DSREPLY_InvalidProcessID, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_ParameterError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, MEMACCESS_DebuggerMemory, MEMACCESS_UserMemory, TRKAppendBuffer1_ui16, TRKMessageIntoReply, TRKReadBuffer, TRKReadBuffer1_ui16, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessMemory.
DSError TRKDoReadRegisters(TRKBuffer *buffer)
References DS_CWDSException, DS_InvalidProcessID, DS_InvalidRegister, DS_InvalidThreadID, DS_NoError, DS_OSError, DS_UnsupportedError, DSMSG_ReplyACK, DSREG_Default, DSREG_Extended1, DSREG_Extended2, DSREG_FP, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidProcessID, DSREPLY_InvalidRegisterRange, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, TRKMessageIntoReply, TRKReadBuffer1_ui16, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessDefault, TRKTargetAccessExtended1, TRKTargetAccessExtended2, TRKTargetAccessFP.
DSError TRKDoWriteRegisters(TRKBuffer *buffer)
References DS_CWDSException, DS_InvalidProcessID, DS_InvalidRegister, DS_InvalidThreadID, DS_MessageBufferReadError, DS_NoError, DS_OSError, DS_UnsupportedError, DSMSG_ReplyACK, DSREG_Default, DSREG_Extended1, DSREG_Extended2, DSREG_FP, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidProcessID, DSREPLY_InvalidRegisterRange, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, TRKMessageIntoReply, TRKReadBuffer1_ui16, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessDefault, TRKTargetAccessExtended1, TRKTargetAccessExtended2, TRKTargetAccessFP.
DSError TRKDoFlushCache(TRKBuffer *buffer)
References DS_NoError, DS_UnsupportedError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_InvalidMemoryRange, DSREPLY_NoError, DSREPLY_PacketSizeError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, TRKMessageIntoReply, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetFlushCache.
DSError TRKDoContinue(TRKBuffer *buffer)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, DSREPLY_NotStopped, TRKStandardACK, TRKTargetContinue, TRKTargetStopped.
DSError TRKDoStep(TRKBuffer *buffer)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, DSREPLY_NotStopped, DSREPLY_PacketSizeError, DSREPLY_ParameterError, DSREPLY_UnsupportedOptionError, DSSTEP_IntoCount, DSSTEP_IntoRange, DSSTEP_OverCount, DSSTEP_OverRange, TRKBuffer::length, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSetBufferPosition, TRKStandardACK, TRKTargetGetPC, TRKTargetSingleStep, TRKTargetStepOutOfRange, TRKTargetStopped.
DSError TRKDoStop(TRKBuffer *b)
References DS_InvalidProcessID, DS_InvalidThreadID, DS_NoError, DS_OSError, DSMSG_ReplyACK, DSREPLY_Error, DSREPLY_InvalidProcessID, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, TRKStandardACK, TRKTargetStop.