msghndlr.h
void SetTRKConnected(BOOL)
BOOL GetTRKConnected(void)
DSError TRKDoUnsupported(TRKBuffer *)
References DSMSG_ReplyACK, DSREPLY_UnsupportedCommandError, TRKStandardACK.
DSError TRKDoSetOption(TRKBuffer *)
DSError TRKDoStop(TRKBuffer *)
References DS_InvalidProcessID, DS_InvalidThreadID, DS_NoError, DS_OSError, DSMSG_ReplyACK, DSREPLY_Error, DSREPLY_InvalidProcessID, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, TRKStandardACK, TRKTargetStop.
DSError TRKDoStep(TRKBuffer *)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, DSREPLY_NotStopped, DSREPLY_PacketSizeError, DSREPLY_ParameterError, DSREPLY_UnsupportedOptionError, DSSTEP_IntoCount, DSSTEP_IntoRange, DSSTEP_OverCount, DSSTEP_OverRange, TRKBuffer::length, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSetBufferPosition, TRKStandardACK, TRKTargetGetPC, TRKTargetSingleStep, TRKTargetStepOutOfRange, TRKTargetStopped.
DSError TRKDoContinue(TRKBuffer *)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, DSREPLY_NotStopped, TRKStandardACK, TRKTargetContinue, TRKTargetStopped.
DSError TRKDoWriteRegisters(TRKBuffer *)
References DS_CWDSException, DS_InvalidProcessID, DS_InvalidRegister, DS_InvalidThreadID, DS_MessageBufferReadError, DS_NoError, DS_OSError, DS_UnsupportedError, DSMSG_ReplyACK, DSREG_Default, DSREG_Extended1, DSREG_Extended2, DSREG_FP, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidProcessID, DSREPLY_InvalidRegisterRange, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, TRKMessageIntoReply, TRKReadBuffer1_ui16, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessDefault, TRKTargetAccessExtended1, TRKTargetAccessExtended2, TRKTargetAccessFP.
DSError TRKDoReadRegisters(TRKBuffer *)
References DS_CWDSException, DS_InvalidProcessID, DS_InvalidRegister, DS_InvalidThreadID, DS_NoError, DS_OSError, DS_UnsupportedError, DSMSG_ReplyACK, DSREG_Default, DSREG_Extended1, DSREG_Extended2, DSREG_FP, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidProcessID, DSREPLY_InvalidRegisterRange, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, TRKMessageIntoReply, TRKReadBuffer1_ui16, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessDefault, TRKTargetAccessExtended1, TRKTargetAccessExtended2, TRKTargetAccessFP.
DSError TRKDoFlushCache(TRKBuffer *)
References DS_NoError, DS_UnsupportedError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_InvalidMemoryRange, DSREPLY_NoError, DSREPLY_PacketSizeError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, TRKMessageIntoReply, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetFlushCache.
DSError TRKDoWriteMemory(TRKBuffer *)
References DS_CWDSException, DS_InvalidMemory, DS_InvalidProcessID, DS_InvalidThreadID, DS_NoError, DS_OSError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidMemoryRange, DSREPLY_InvalidProcessID, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_ParameterError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, MEMACCESS_DebuggerMemory, MEMACCESS_UserMemory, TRKAppendBuffer1_ui16, TRKMessageIntoReply, TRKReadBuffer, TRKReadBuffer1_ui16, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessMemory.
DSError TRKDoReadMemory(TRKBuffer *)
References DS_CWDSException, DS_InvalidMemory, DS_InvalidProcessID, DS_InvalidThreadID, DS_NoError, DS_OSError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_CWDSException, DSREPLY_InvalidMemoryRange, DSREPLY_InvalidProcessID, DSREPLY_InvalidThreadID, DSREPLY_NoError, DSREPLY_OSError, DSREPLY_PacketSizeError, DSREPLY_ParameterError, DSREPLY_UnsupportedOptionError, TRKBuffer::length, MEMACCESS_DebuggerMemory, MEMACCESS_UserMemory, TRKAppendBuffer, TRKAppendBuffer1_ui16, TRKMessageIntoReply, TRKReadBuffer1_ui16, TRKReadBuffer1_ui32, TRKReadBuffer1_ui8, TRKSendACK, TRKSetBufferPosition, TRKStandardACK, TRKTargetAccessMemory.
DSError TRKDoSupportMask(TRKBuffer *)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_NoError, DSREPLY_PacketSizeError, TRKBuffer::length, TRKAppendBuffer, TRKAppendBuffer1_ui8, TRKMessageIntoReply, TRKSendACK, TRKStandardACK, TRKTargetSupportMask.
DSError TRKDoVersions(TRKBuffer *)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_NoError, DSREPLY_PacketSizeError, DSVersions::kernelMajor, DSVersions::kernelMinor, TRKBuffer::length, DSVersions::protocolMajor, DSVersions::protocolMinor, TRKAppendBuffer1_ui8, TRKMessageIntoReply, TRKSendACK, TRKStandardACK, TRKTargetVersions.
DSError TRKDoCPUType(TRKBuffer *)
References DSCPUType::bigEndian, DSCPUType::cpuMajor, DSCPUType::cpuMinor, DSCPUType::defaultTypeSize, DS_NoError, DSMSG_ReplyACK, DSREPLY_CWDSError, DSREPLY_NoError, DSREPLY_PacketSizeError, DSCPUType::extended1TypeSize, DSCPUType::extended2TypeSize, DSCPUType::fpTypeSize, TRKBuffer::length, TRKAppendBuffer1_ui8, TRKMessageIntoReply, TRKSendACK, TRKStandardACK, TRKTargetCPUType.
DSError TRKDoOverride(TRKBuffer *)
DSError TRKDoReset(TRKBuffer *)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, TRKStandardACK.
DSError TRKDoDisconnect(TRKBuffer *)
References DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, TRKConstructEvent, TRKPostEvent, TRKStandardACK.
DSError TRKDoConnect(TRKBuffer *)
References DSMSG_ReplyACK, DSREPLY_NoError, TRKStandardACK.
DSError TRKStandardACK(TRKBuffer *buffer, MessageCommandID commandID, DSReplyError replyError)
References DS_NoError, TRKMessageIntoReply, TRKSendACK.
Referenced by TRKDoConnect, TRKDoContinue, TRKDoCPUType, TRKDoDisconnect, TRKDoFlushCache, TRKDoReadMemory, TRKDoReadRegisters, TRKDoReset, TRKDoStep, TRKDoStop, TRKDoSupportMask, TRKDoUnsupported, TRKDoVersions, TRKDoWriteMemory, TRKDoWriteRegisters, TRKTestForPacket.
void OutputData(void *data, int length)