mutex_TRK.h
DSError TRKInitializeMutex(void *)
References DS_NoError.
Referenced by TRKInitializeEventQueue, TRKInitializeMessageBuffers.
DSError TRKAcquireMutex(void *)
References DS_NoError.
Referenced by TRKGetFreeBuffer, TRKGetNextEvent, TRKInitializeEventQueue, TRKInitializeMessageBuffers, TRKPostEvent, TRKReleaseBuffer.
DSError TRKReleaseMutex(void *)
References DS_NoError.
Referenced by TRKGetFreeBuffer, TRKGetNextEvent, TRKInitializeEventQueue, TRKInitializeMessageBuffers, TRKPostEvent, TRKReleaseBuffer.