nubevent.h
typedef u32 NubEventID
typedef struct TRKEvent TRKEvent
typedef struct TRKEventQueue TRKEventQueue
TRKEventQueue gTRKEventQueue
Referenced by TRKGetNextEvent, TRKInitializeEventQueue, TRKPostEvent.
BOOL TRKGetNextEvent(TRKEvent *event)
References TRKEventQueue::count, TRKEventQueue::events, gTRKEventQueue, TRKEventQueue::next, TRKAcquireMutex, TRKCopyEvent, TRKReleaseMutex.
Referenced by TRKNubMainLoop.
void TRKDestructEvent(TRKEvent *)
References TRKEvent::msgBufID, TRKReleaseBuffer.
Referenced by TRKNubMainLoop.
void TRKConstructEvent(TRKEvent *, NubEventType)
Referenced by TRKDoDisconnect, TRKPostInterruptEvent, TRKProcessInput, TRKTargetSupportRequest.
DSError TRKPostEvent(TRKEvent *)
References TRKEventQueue::count, DS_EventQueueFull, DS_NoError, TRKEvent::eventID, TRKEventQueue::eventID, TRKEventQueue::events, gTRKEventQueue, TRKEventQueue::next, TRKAcquireMutex, TRKCopyEvent, TRKReleaseMutex.
Referenced by TRKDoDisconnect, TRKPostInterruptEvent, TRKProcessInput, TRKTargetSupportRequest.
DSError TRKInitializeEventQueue()
References TRKEventQueue::count, DS_NoError, TRKEventQueue::eventID, gTRKEventQueue, TRKEventQueue::next, TRKAcquireMutex, TRKInitializeMutex, TRKReleaseMutex.
Referenced by TRKInitializeNub.