nubevent.c
TRKEventQueue gTRKEventQueue
Referenced by TRKGetNextEvent, TRKInitializeEventQueue, TRKPostEvent.
DSError TRKInitializeEventQueue()
References TRKEventQueue::count, DS_NoError, TRKEventQueue::eventID, gTRKEventQueue, TRKEventQueue::next, TRKAcquireMutex, TRKInitializeMutex, TRKReleaseMutex.
Referenced by TRKInitializeNub.
void TRKCopyEvent(TRKEvent *dstEvent, const TRKEvent *srcEvent)
References TRK_memcpy.
Referenced by TRKGetNextEvent, TRKPostEvent.
BOOL TRKGetNextEvent(TRKEvent *event)
References TRKEventQueue::count, TRKEventQueue::events, gTRKEventQueue, TRKEventQueue::next, TRKAcquireMutex, TRKCopyEvent, TRKReleaseMutex.
Referenced by TRKNubMainLoop.
DSError TRKPostEvent(TRKEvent *event)
References TRKEventQueue::count, DS_EventQueueFull, DS_NoError, TRKEvent::eventID, TRKEventQueue::eventID, TRKEventQueue::events, gTRKEventQueue, TRKEventQueue::next, TRKAcquireMutex, TRKCopyEvent, TRKReleaseMutex.
Referenced by TRKDoDisconnect, TRKPostInterruptEvent, TRKProcessInput, TRKTargetSupportRequest.
void TRKConstructEvent(TRKEvent *event, NubEventType eventType)
Referenced by TRKDoDisconnect, TRKPostInterruptEvent, TRKProcessInput, TRKTargetSupportRequest.
void TRKDestructEvent(TRKEvent *event)
References TRKEvent::msgBufID, TRKReleaseBuffer.
Referenced by TRKNubMainLoop.