nubinit.c
BOOL gTRKBigEndian
Referenced by TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32, TRKAppendBuffer1_ui64, TRKInitializeEndian, TRKReadBuffer1_ui16, TRKReadBuffer1_ui32, TRKReadBuffer1_ui64, TRKTargetCPUType.
BOOL TRKInitializeEndian(void)
References gTRKBigEndian.
Referenced by TRKInitializeNub.
DSError TRKInitializeNub(void)
References DS_NoError, gTRKInputPendingPtr, TRKInitializeDispatcher, TRKInitializeEndian, TRKInitializeEventQueue, TRKInitializeIntDrivenUART, TRKInitializeMessageBuffers, TRKInitializeSerialHandler, TRKInitializeTarget, TRKTargetSetInputPendingPtr, usr_put_initialize.
Referenced by TRK_main.
DSError TRKTerminateNub(void)
References DS_NoError, TRKTerminateSerialHandler.
Referenced by TRK_main.
void TRKNubWelcome(void)
References TRK_board_display.
Referenced by TRK_main.