nubinit.h
BOOL gTRKBigEndian
Referenced by TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32, TRKAppendBuffer1_ui64, TRKReadBuffer1_ui16, TRKReadBuffer1_ui32, TRKReadBuffer1_ui64.
void TRKNubWelcome(void)
References TRK_board_display.
Referenced by TRK_main.
void TRKNubMainLoop(void)
DSError TRKTerminateNub(void)
References DS_NoError, TRKTerminateSerialHandler.
Referenced by TRK_main.
DSError TRKInitializeNub(void)
References DS_NoError, gTRKInputPendingPtr, TRKInitializeDispatcher, TRKInitializeEndian, TRKInitializeEventQueue, TRKInitializeIntDrivenUART, TRKInitializeMessageBuffers, TRKInitializeSerialHandler, TRKInitializeTarget, TRKTargetSetInputPendingPtr, usr_put_initialize.
Referenced by TRK_main.