printf.c
conversion_buff_size
conversion_max
bad_conversion
MAX_SIG_DIG
justification_options
sign_options
argument_options
static const char * parse_format(const char *format_string, va_list *arg, print_format *format)
References print_format::alternate_form, print_format::argument_options, bad_conversion, char_argument, print_format::conversion_char, conversion_max, print_format::field_width, isdigit, print_format::justification_options, left_justification, long_argument, long_double_argument, long_long_argument, normal_argument, only_minus, print_format::precision, print_format::precision_specified, right_justification, short_argument, sign_always, print_format::sign_options, space_holder, strlen, wchar_argument, zero_fill.
Referenced by __pformatter.
static char * long2str(long num, char *buff, print_format *format)
References print_format::alternate_form, print_format::conversion_char, conversion_max, print_format::field_width, print_format::justification_options, NULL, only_minus, print_format::precision, sign_always, print_format::sign_options, space_holder, zero_fill.
Referenced by __pformatter.
static void round_decimal(decimal *dec, int new_length)
References decimal::exp, decimal::length, decimal::sgn, decimal::sig, decimal::text.
Referenced by float2str.
static char * float2str(va_list arg, char *buff, print_format *format, int vecIndex)
References __num2dec, print_format::alternate_form, print_format::argument_options, print_format::conversion_char, conversion_max, decform::digits, decimal::exp, FLOATDECIMAL, decimal::length, long_double_argument, MAX_SIG_DIG, NULL, print_format::precision, round_decimal, decimal::sgn, decimal::sig, sign_always, print_format::sign_options, space_holder, strcpy, decform::style, decimal::text.
Referenced by __pformatter.
static int __pformatter(void *(*WriteProc)(void *, const char *, size_t), void *WriteProcArg, const char *format_str, va_list arg)
References print_format::alternate_form, print_format::argument_options, bad_conversion, char_argument, conversion_buff_size, print_format::conversion_char, print_format::field_width, float2str, format_str, print_format::justification_options, left_justification, long2str, long_argument, long_long_argument, memchr, normal_argument, NULL, parse_format, print_format::precision, print_format::precision_specified, short_argument, strlen, wchar_argument, wcstombs, zero_fill.
Referenced by fprintf, vfprintf, vprintf, vsnprintf.
void * __FileWrite(void *File, const char *Buffer, size_t NumChars)
References fwrite.
Referenced by fprintf, vfprintf, vprintf.
void * __StringWrite(void *osc, const char *Buffer, size_t NumChars)
References memcpy.
Referenced by vsnprintf.
int fprintf(FILE *file, const char *format,...)
References __FileWrite, __pformatter, fwide.
Referenced by __assertion_failed, parse_format, perror.
int vprintf(const char *format, va_list arg)
References __FileWrite, __pformatter, fwide.
int vfprintf(FILE *file, const char *format, va_list arg)
References __FileWrite, __pformatter, fwide.
int vsnprintf(char *s, size_t n, const char *format, va_list arg)
References __pformatter, __StringWrite.
Referenced by snprintf, vsprintf.
int vsprintf(char *s, const char *format, va_list arg)
References vsnprintf.
Referenced by emit.
int snprintf(char *s, size_t n, const char *format,...)
References vsnprintf.