s_log1p.c
double ln2_hi
Referenced by log1p.
double ln2_lo
Referenced by log1p.
double two54
Referenced by log1p.
double Lp1
Referenced by log1p.
double Lp2
Referenced by log1p.
double Lp3
Referenced by log1p.
double Lp4
Referenced by log1p.
double Lp5
Referenced by log1p.
double Lp6
Referenced by log1p.
double Lp7
Referenced by log1p.
double zero
Referenced by log1p.
double log1p(double x)
References __HI, ln2_hi, ln2_lo, Lp1, Lp2, Lp3, Lp4, Lp5, Lp6, Lp7, two54, zero.
Referenced by __ieee754_acosh, __ieee754_atanh, asinh.