scanf.c
conversion_buff_size
conversion_max
bad_conversion
set_char_map
tst_char_map
argument_options
typedef unsigned char char_map[32][32]
static const char * parse_format(const char *format_string, scan_format *format)
References scan_format::argument_options, bad_conversion, char_argument, scan_format::char_set, scan_format::conversion_char, double_argument, scan_format::field_width, scan_format::field_width_specified, fprintf, isdigit, long_argument, long_double_argument, long_long_argument, normal_argument, set_char_map, short_argument, strlen, scan_format::suppress_assignment, wchar_argument.
Referenced by __sformatter.
static int __sformatter(int(*ReadProc)(void *, int, int), void *ReadProcArg, const char *format_str, va_list arg)
References __strtold, __strtoul, scan_format::argument_options, bad_conversion, char_argument, scan_format::char_set, scan_format::conversion_char, double_argument, EOF, exit, scan_format::field_width, scan_format::field_width_specified, format_str, isspace, long_argument, long_double_argument, long_long_argument, mbtowc, normal_argument, parse_format, short_argument, scan_format::suppress_assignment, tst_char_map, wchar_argument.
Referenced by __vsscanf, fscanf, scanf.
int __FileRead(void *File, int ch, int Action)
References feof, ferror, fgetc, ungetc.
Referenced by fscanf, scanf.
int __StringRead(void *isc, int ch, int Action)
References EOF.
Referenced by __vsscanf, strtod, strtol, strtoul.
int fscanf(FILE *file, const char *format,...)
References __FileRead, __sformatter, EOF, fwide, NULL.
int scanf(const char *format,...)
References __FileRead, __sformatter, EOF, fwide.
int __vsscanf(const char *s, const char *format, va_list arg)
References __sformatter, __StringRead, EOF, NULL.
Referenced by sscanf.
int sscanf(const char *s, const char *format,...)
References __vsscanf.