serpoll.c
TRKFramingState gTRKFramingState
Referenced by TRKInitializeSerialHandler, TRKProcessInput.
void* gTRKInputPendingPtr
Referenced by TRKInitializeNub, TRKNubMainLoop.
MessageBufferID TRKTestForPacket()
References TRKBuffer::data, TRKBuffer::length, TRKGetFreeBuffer, TRKMSGBUF_SIZE, TRKPollUART, TRKReadUARTN, TRKReleaseBuffer, TRKStandardACK.
Referenced by TRKGetInput, TRKRequestSend.
void TRKGetInput(void)
References DSMSG_ReplyACK, TRKGetBuffer, TRKProcessInput, TRKReadBuffer1_ui8, TRKReleaseBuffer, TRKSetBufferPosition, TRKTestForPacket.
Referenced by TRKNubMainLoop.
void TRKProcessInput(int bufferIdx)
References gTRKFramingState, TRKFramingState::msgBufID, NUBEVENT_Request, TRKConstructEvent, TRKPostEvent.
Referenced by TRKGetInput, TRKRequestSend.
DSError TRKInitializeSerialHandler(void)
References DS_NoError, DSRECV_Wait, gTRKFramingState, TRKFramingState::isEscape, TRKFramingState::msgBufID, TRKFramingState::receiveState.
Referenced by TRKInitializeNub.
DSError TRKTerminateSerialHandler(void)
References DS_NoError.
Referenced by TRKTerminateNub.