signal.c
__signal_func_ptr signal_funcs[__signal_max][__signal_max]
Referenced by raise, signal.
__signal_func_ptr signal(int signal, __signal_func_ptr signal_func)
References __begin_critical_region, __end_critical_region, errno, signal, signal_funcs, signal_funcs_access.
Referenced by raise, signal.
int raise(int signal)
References __begin_critical_region, __end_critical_region, exit, signal, signal_funcs, signal_funcs_access.
Referenced by abort.