sqrtf.c
_INT32 inv_sqrt_guess[][]
Referenced by _inv_sqrtf.
_INT32 inv_sqrt_guess2[][]
Referenced by _inv_sqrtf.
float _inv_sqrtf(float x)
Referenced by sqrtf.
float sqrtf(float x)
References _inv_sqrtf.
Referenced by sqrt.
double __frsqrte(double)
Referenced by _inv_sqrtf, sqrt, sqrtf.