string.c
set_char_map
tst_char_map
typedef unsigned char char_map[32][32]
int K1
Referenced by strcmp, strcpy.
int K2
Referenced by strcmp, strcpy.
char *() strcpy(char *dst, const char *src)
References adjust, K1, K2.
Referenced by __strerror, std::_MSLstring::_MSLstring, std::_MSLstring::_MSLstring, float2str.
char * strncpy(char *dst, const char *src, size_t n)
References zero.
Referenced by strxfrm.
char * strcat(char *dst, const char *src)
char * strncat(char *dst, const char *src, size_t n)
int strcmp(const char *str1, const char *str2)
References adjust, K1, K2, r1.
Referenced by setlocale, strcoll, wctrans.
int strncmp(const char *str1, const char *str2, size_t n)
int strcoll(const char *str1, const char *str2)
References strcmp.
size_t strxfrm(char *str1, const char *str2, size_t n)
References strlen, strncpy.
char * strrchr(const char *str, int chr)
char * strpbrk(const char *str, const char *set)
References NULL, set_char_map, tst_char_map.
size_t strspn(const char *str, const char *set)
References set_char_map, tst_char_map.
size_t strcspn(const char *str, const char *set)
References set_char_map, tst_char_map.
char * strtok(char *str, const char *set)
References NULL, set_char_map, tst_char_map.
char * strstr(const char *str, const char *pat)
References NULL, s1, s2.
char * strerror(int errnum)
References __strerror.
char * __strerror(int errnum, char *str)
References strcpy.
Referenced by perror, strerror.