string_io.h
int __open_string_file(__std(FILE) *file, char *str, __std(size_t) n, int io_state)
int __read_string(__std(__file_handle) handle, unsigned char *buffer, __std(size_t) *count, __std(__idle_proc) idle_proc)
Referenced by __init_file.
int __write_string(__std(__file_handle) handle, unsigned char *buffer, __std(size_t) *count, __std(__idle_proc) idle_proc)
Referenced by __init_file.
int __close_string(__std(__file_handle) handle)
Referenced by __init_file.