strtoul.h
unsigned long __strtoul(int base, int max_width, int(*ReadProc)(void *, int, int), void *ReadProcArg, int *chars_scanned, int *negative, int *overflow)
References check_for_zero, count, digit_loop, EOF, failure, fetch, final_state, finished, isalpha, isdigit, isspace, leading_zero, need_digit, start, success, toupper, unfetch.
Referenced by __sformatter, strtol, strtoul.