strtoul.c
final_state
success
fetch
unfetch
scan_states
unsigned long __strtoul(int base, int max_width, int(*ReadProc)(void *, int, int), void *ReadProcArg, int *chars_scanned, int *negative, int *overflow)
References check_for_zero, count, digit_loop, EOF, failure, fetch, final_state, finished, isalpha, isdigit, isspace, leading_zero, need_digit, start, success, toupper, unfetch.
Referenced by __sformatter, strtol, strtoul.
unsigned long strtoul(const char *str, char **end, int base)
References __StringRead, __strtoul, count, errno.
Referenced by strtoumax.
long strtol(const char *str, char **end, int base)
References __StringRead, __strtoul, count, errno.
Referenced by atoi, atol, strtoimax.
int atoi(const char *str)
References NULL, strtol.
long atol(const char *str)
References NULL, strtol.
intmax_t() strtoimax(const char *nptr, char **endptr, int base)
References strtol.
uintmax_t() strtoumax(const char *nptr, char **endptr, int base)
References strtoul.