support.h
DSError TRKSuppAccessFile(u32 file_handle, u8 *data, size_t *count, DSIOResult *io_result, BOOL need_reply, BOOL read)
References count, DS_IONoError, DS_NoError, DS_ParameterError, DSMSG_ReadFile, DSMSG_WriteFile, exit, TRKBuffer::length, NULL, TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32, TRKAppendBuffer1_ui8, TRKAppendBuffer_ui8, TRKGetBuffer, TRKGetFreeBuffer, TRKMessageSend, TRKReadBuffer1_ui16, TRKReadBuffer1_ui8, TRKReadBuffer_ui8, TRKReleaseBuffer, TRKRequestSend, TRKSetBufferPosition.
Referenced by TRKTargetSupportRequest.
DSError TRKRequestSend(TRKBuffer *msgBuf, int *bufferId, u32 p1, u32 p2, int p3)
References DS_Error800, DS_NoError, DSMSG_ReplyACK, DSREPLY_NoError, TRKBuffer::length, TRKGetBuffer, TRKMessageSend, TRKProcessInput, TRKReadBuffer1_ui8, TRKReleaseBuffer, TRKSetBufferPosition, TRKTestForPacket.
Referenced by TRKDoNotifyStopped, TRKSuppAccessFile.
DSError HandleOpenFileSupportRequest(const char *path, u8 replyError, u32 *param_3, DSIOResult *ioResult)
DSError HandleCloseFileSupportRequest(int replyError, DSIOResult *ioResult)
DSError HandlePositionFileSupportRequest(DSReplyError replyErr, u32 *param_2, u8 param_3, DSIOResult *ioResult)