targimpl.c
INSTR_NOP
INSTR_BLR
INSTR_PSQ_ST
INSTR_PSQ_L
INSTR_STW
INSTR_LWZ
INSTR_STFD
INSTR_LFD
INSTR_MFSPR
INSTR_MTSPR
DSFetch_u32
DSFetch_u64
msr
byte
count
DEBUG_VECTORREG_ACCESS
typedef struct memRange memRange
typedef struct StopInfo_PPC StopInfo_PPC
typedef struct TRKExceptionStatus TRKExceptionStatus
typedef struct TRKStepStatus TRKStepStatus
typedef unsigned char u128[16][16]
const memRange gTRKMemMap[1][1]
ProcessorRestoreFlags_PPC gTRKRestoreFlags
Referenced by TRKRestoreExtended1Block.
TRKExceptionStatus gTRKExceptionStatus
Referenced by TRKExceptionHandler, TRKInterruptHandler, TRKSwapAndGo, TRKTargetAddExceptionInfo.
TRKStepStatus gTRKStepStatus
Referenced by TRKTargetCheckStep, TRKTargetDoStep, TRKTargetSingleStep, TRKTargetStepDone, TRKTargetStepOutOfRange.
u16 TRK_saved_exceptionID
Referenced by TRKInterruptHandler.
ProcessorState_PPC gTRKCPUState
Referenced by InitMetroTRK, TRKInterruptHandler, TRKPostInterruptEvent, TRKRestoreExtended1Block, TRKSaveExtended1Block, TRKSwapAndGo, TRKTargetAddStopInfo, TRKTargetEnableTrace, TRKTargetGetPC, TRKTargetStepDone, TRKTargetSupportRequest, TRKTargetTranslate.
TRKState gTRKState
Referenced by TRKInitializeTarget, TRKInterruptHandler, TRKInterruptHandlerEnableInterrupts, TRKPostInterruptEvent, TRKSwapAndGo, TRKTargetSetInputPendingPtr, TRKTargetSetStopped, TRKTargetStopped.
u128 TRKvalue128_temp
Referenced by TRKPPCAccessSpecialReg.
Default_PPC gTRKSaveState
Referenced by TRKInterruptHandler.
psr<< 21) | (rDest << 16) | (w << 15) | (gqr << 12) ﾂ･ | offset)#define INSTR_PSQ_L(psr, offset, rSrc, w, gqr) (0xE0000000 | (psr << 21) | (rSrc << 16) | (w << 15) | (gqr << 12) | offset)#define INSTR_STW(rSrc, offset, rDest) (0x90000000 | (rSrc << 21) | (rDest << 16) | offset)#define INSTR_LWZ(rDest, offset, rSrc) (0x80000000 | (rDest << 21) | (rSrc << 16) | offset)#define INSTR_STFD(fprSrc, offset, rDest) (0xD8000000 | (fprSrc << 21) | (rDest << 16) | offset)#define INSTR_LFD(fprDest, offset, rSrc) (0xC8000000 | (fprDest << 21) | (rSrc << 16) | offset)#define INSTR_MFSPR(rDest, spr) (0x7C000000 | (rDest << 21) | ((spr & 0xFE0) << 6) | ((spr & 0x1F) << 16) ﾂ･ | 0x2A6)#define INSTR_MTSPR(spr, rSrc) (0x7C000000 | (rSrc << 21) | ((spr & 0xFE0) << 6) | ((spr & 0x1F) << 16) ﾂ･ | 0x3A6)#define DSFetch_u32(_p_) #define DSFetch_u64(_p_) DSError TRKPPCAccessSPR(void* value, u32 spr_register_num, BOOL read);DSError TRKPPCAccessPairedSingleRegister(void* srcDestPtr, u32 psr, BOOL read);DSError TRKPPCAccessFPRegister(void* srcDestPtr, u32 fpr, BOOL read);DSError TRKPPCAccessSpecialReg(void* value, u32* access_func, BOOL read);static void TRKExceptionHandler(u16);void TRKInterruptHandlerEnableInterrupts(void);void WriteFPSCR(register f64*);void ReadFPSCR(register f64*);void __TRK_set_MSR(u32 msr);u32 __TRK_get_MSR();static void TRK_ppc_memcpy(register void* dest, register const void* src, register int n, register u32 param_4, register u32 param_5);void TRKRestoreExtended1Block();void TRKUARTInterruptHandler();static BOOL TRKTargetCheckStep();asm u32 __TRK_get_MSR(){ nofralloc mfmsr r3 blr}asm void __TRK_set_MSR(register u32 msr) { nofralloc mtmsr msr blr}DSError TRKValidMemory32(const void* addr, size_t length, ValidMemoryOptions readWriteable){ DSError err = DS_InvalidMemory; const u8* start; const u8* end; s32 i; start = (const u8*)addr; end = ((const u8*)addr + (length - 1)); if (end < start) return DS_InvalidMemory; for (i = 0; (i < (s32)(sizeof(gTRKMemMap) / sizeof(memRange))); i++) { if ((start <= (const u8*)gTRKMemMap[i].end) && (end >= (const u8*)gTRKMemMap[i].start)) { if (((readWriteable == VALIDMEM_Readable) && !gTRKMemMap[i].readable) || ((readWriteable == VALIDMEM_Writeable) && !gTRKMemMap[i].writeable)) { err = DS_InvalidMemory; } else { err = DS_NoError; if (start < (const u8*)gTRKMemMap[i].start) err = TRKValidMemory32( start, (u32)((const u8*)gTRKMemMap[i].start - start), readWriteable); if ((err == DS_NoError) && (end >(const u8*)gTRKMemMap[i].end)) err = TRKValidMemory32( (const u8*)gTRKMemMap[i].end, (u32)(end - (const u8*)gTRKMemMap[i].end), readWriteable); } break; } } return err;}static asm void TRK_ppc_memcpy(register void* dest, register const void* src, register int n, register u32 param_4, register u32 param_5) {#define msr #define byte #define count nofralloc mfmsr msr li count, 0top_loop: cmpw count, n beq out_loop mtmsr param_5 sync lbzx byte, count, src mtmsr param_4 sync stbx byte, count, dest addi count, count, 1 b top_loopout_loop: mtmsr msr sync blr}DSError TRKTargetAccessMemory(void* data, u32 start, size_t* length, MemoryAccessOptions accessOptions, BOOL read){ DSError error; u32 target_msr; void* addr; u32 trk_msr; TRKExceptionStatus tempExceptionStatus = gTRKExceptionStatus; gTRKExceptionStatus.exceptionDetected = FALSE; addr = (void*)TRKTargetTranslate(start); error = TRKValidMemory32(addr, *length, read ? VALIDMEM_Readable : VALIDMEM_Writeable); if (error != DS_NoError) { *length = 0; } else { target_msr = __TRK_get_MSR(); trk_msr = target_msr | gTRKCPUState.Extended1.MSR & 0x10; if (read) { TRK_ppc_memcpy(data, addr, *length, target_msr, trk_msr); } else { TRK_ppc_memcpy(addr, data, *length, trk_msr, target_msr); TRK_flush_cache(addr, *length); if ((void*)start != addr) { TRK_flush_cache((void*)start, *length); } } } if (gTRKExceptionStatus.exceptionDetected) { *length = 0; error = DS_CWDSException; } gTRKExceptionStatus = tempExceptionStatus; return error;}DSError TRKTargetReadInstruction(void* data, u32 start){ DSError error; size_t registersLength = 4; error = TRKTargetAccessMemory(data, start, &registersLength, MEMACCESS_UserMemory, TRUE); if (error == DS_NoError && registersLength != 4) { error = DS_InvalidMemory; } return error;}DSError TRKTargetAccessDefault(u32 firstRegister, u32 lastRegister, TRKBuffer* b, size_t* registersLengthPtr, BOOL read){ DSError error; u32 count; u32* data; TRKExceptionStatus tempExceptionStatus; if (lastRegister > 0x24) { return DS_InvalidRegister; } tempExceptionStatus = gTRKExceptionStatus; data = gTRKCPUState.Default.GPR + firstRegister; count = (lastRegister - firstRegister) + 1; gTRKExceptionStatus.exceptionDetected = FALSE; *registersLengthPtr = count * sizeof(u32); if (read) { error = TRKAppendBuffer_ui32(b, data, count); } else { error = TRKReadBuffer_ui32(b, data, count); } if (gTRKExceptionStatus.exceptionDetected) { *registersLengthPtr = 0; error = DS_CWDSException; } gTRKExceptionStatus = tempExceptionStatus; return error;}DSError TRKTargetAccessFP(u32 firstRegister, u32 lastRegister, TRKBuffer* b, size_t* registersLengthPtr, BOOL read){ u64 temp; DSError error; TRKExceptionStatus tempExceptionStatus; u32 current; if (lastRegister > 0x21) { return DS_InvalidRegister; } tempExceptionStatus = gTRKExceptionStatus; gTRKExceptionStatus.exceptionDetected = FALSE; __TRK_set_MSR(__TRK_get_MSR() | 0x2000); *registersLengthPtr = 0; error = DS_NoError; for (current = firstRegister; (current <= lastRegister) && (error == DS_NoError); current++, *registersLengthPtr += sizeof(f64)) { if (read) { TRKPPCAccessFPRegister(&temp, current, read); error = TRKAppendBuffer1_ui64(b, temp); } else { TRKReadBuffer1_ui64(b, &temp); error = TRKPPCAccessFPRegister(&temp, current, read); } } if (gTRKExceptionStatus.exceptionDetected) { *registersLengthPtr = 0; error = DS_CWDSException; } gTRKExceptionStatus = tempExceptionStatus; return error;}DSError TRKTargetAccessExtended1(u32 firstRegister, u32 lastRegister, TRKBuffer* b, size_t* registersLengthPtr, BOOL read){ TRKExceptionStatus tempExceptionStatus; int error; u32* data; int count; if (lastRegister > 0x60) { return DS_InvalidRegister; } tempExceptionStatus = gTRKExceptionStatus; gTRKExceptionStatus.exceptionDetected = FALSE; *registersLengthPtr = 0; if (firstRegister <= lastRegister) { data = (u32*)&gTRKCPUState.Extended1 + firstRegister; count = lastRegister - firstRegister + 1; *registersLengthPtr += count * sizeof(u32); if (read) { error = TRKAppendBuffer_ui32(b, data, count); } else { if (data <= &gTRKCPUState.Extended1.TBU && (data + count - 1) >= &gTRKCPUState.Extended1.TBL) { gTRKRestoreFlags.TBR = 1; } if (data <= &gTRKCPUState.Extended1.DEC && (data + count - 1) >= &gTRKCPUState.Extended1.DEC) { gTRKRestoreFlags.DEC = 1; } error = TRKReadBuffer_ui32(b, data, count); } } if (gTRKExceptionStatus.exceptionDetected) { *registersLengthPtr = 0; error = DS_CWDSException; } gTRKExceptionStatus = tempExceptionStatus; return error;}DSError TRKTargetAccessExtended2(u32 firstRegister, u32 lastRegister, TRKBuffer* b, size_t* registerStorageSize, BOOL read){ TRKExceptionStatus savedException; u32 i; u32 value_buf0[1]; u32 value_buf[2]; DSError err; u32 access_func[10]; if (lastRegister > 0x1f) return DS_InvalidRegister; savedException = gTRKExceptionStatus; gTRKExceptionStatus.exceptionDetected = FALSE; TRKPPCAccessSPR(value_buf0, SPR_HID2, TRUE); value_buf0[0] |= 0xA0000000; TRKPPCAccessSPR(value_buf0, SPR_HID2, FALSE); value_buf0[0] = 0; TRKPPCAccessSPR(value_buf0, SPR_GQR0, FALSE); *registerStorageSize = 0; err = DS_NoError; for (i = firstRegister; (i <= lastRegister) && (err == DS_NoError); i++) { if (read) { err = TRKPPCAccessPairedSingleRegister((u64*)value_buf, i, read); err = TRKAppendBuffer1_ui64(b, *(u64*)value_buf); } else { err = TRKReadBuffer1_ui64(b, (u64*)value_buf); err = TRKPPCAccessPairedSingleRegister((u64*)value_buf, i, read); } *registerStorageSize += sizeof(u64); } if (gTRKExceptionStatus.exceptionDetected) { *registerStorageSize = 0; err = DS_CWDSException; } gTRKExceptionStatus = savedException; return err;}DSError TRKTargetVersions(DSVersions* versions){ versions-> kernelMajor
versions kernelMinor
versions protocolMajor
versions protocolMinor
return DS_NoError
Referenced by TRKPPCAccessFPRegister, TRKPPCAccessSpecialReg, TRKTargetCPUType, TRKTargetDoStep, TRKTargetEnableTrace, TRKTargetFlushCache, TRKTargetInterrupt, TRKTargetSingleStep, TRKTargetStepOutOfRange, TRKTargetSupportMask, TRKTargetSupportRequest.
BOOL gTRKBigEndian
Referenced by TRKInitializeEndian, TRKTargetCPUType.
DSError TRKTargetSupportMask(u8 mask[32])
References DS_NoError.
Referenced by TRKDoSupportMask.
DSError TRKTargetCPUType(DSCPUType *cpuType)
References DSCPUType::bigEndian, DSCPUType::cpuMajor, DSCPUType::cpuMinor, DSCPUType::defaultTypeSize, DS_NoError, DSCPUType::extended1TypeSize, DSCPUType::extended2TypeSize, DSCPUType::fpTypeSize, gTRKBigEndian, TRKTargetCPUMinorType.
Referenced by TRKDoCPUType.
asm void TRKInterruptHandler()
References Default_PPC::CR, TRKState_PPC::CTR, TRKState_PPC::DAR, ProcessorState_PPC_6xx_7xx::Default, TRKState_PPC::DSISR, Extended1_PPC_6xx_7xx::exceptionID, ProcessorState_PPC_6xx_7xx::Extended1, Default_PPC::GPR, TRKState_PPC::GPR, gTRKCPUState, gTRKExceptionStatus, gTRKSaveState, gTRKState, TRKState_PPC::inputActivated, TRKState_PPC::inputPendingPtr, TRKExceptionStatus::inTRK, TRKState_PPC::LR, TRKState_PPC::MSR, Default_PPC::PC, r1, r2, r3, r4, ProcessorState_PPC_6xx_7xx::transport_handler_saved_ra, TRK_saved_exceptionID, TRKExceptionHandler, TRKPostInterruptEvent, TRKSaveExtended1Block, TRKUARTInterruptHandler, TRKState_PPC::XER.
Referenced by TRKLoadContext.
static asm void TRKExceptionHandler(u16)
References TRKExceptionStatus::exceptionDetected, StopInfo_PPC::exceptionID, TRKExceptionStatus::exceptionInfo, gTRKExceptionStatus, StopInfo_PPC::PC, r2, r3.
Referenced by TRKInterruptHandler.
void TRKPostInterruptEvent(void)
References ProcessorState_PPC_6xx_7xx::Default, Extended1_PPC_6xx_7xx::exceptionID, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, gTRKState, TRKState::inputActivated, NUBEVENT_Breakpoint, NUBEVENT_Exception, NUBEVENT_Support, Default_PPC::PC, TRKConstructEvent, TRKPostEvent.
Referenced by TRKInterruptHandler, TRKInterruptHandlerEnableInterrupts.
asm void TRKSwapAndGo()
References TRKState_PPC::CTR, TRKState_PPC::DAR, ProcessorState_PPC_6xx_7xx::Default, TRKState_PPC::DSISR, Default_PPC::GPR, TRKState_PPC::GPR, gTRKCPUState, gTRKExceptionStatus, gTRKState, TRKState_PPC::inputActivated, TRKState_PPC::inputPendingPtr, TRKState_PPC::LR, TRKState_PPC::MSR, Default_PPC::PC, r1, r2, r3, TRKInterruptHandlerEnableInterrupts, TRKRestoreExtended1Block, TRKState_PPC::XER.
Referenced by TRKTargetContinue.
asm void TRKInterruptHandlerEnableInterrupts(void)
References TRKState_PPC::CTR, TRKState_PPC::DAR, TRKState_PPC::DSISR, TRKState_PPC::GPR, gTRKState, TRKState_PPC::LR, TRKState_PPC::MSR, r1, r2, r3, TRKPostInterruptEvent, TRKState_PPC::XER.
Referenced by TRKSwapAndGo.
DSError TRKTargetInterrupt(TRKEvent *event)
References DS_NoError, DSMSG_NotifyStopped, TRKEvent::eventType, NUBEVENT_Breakpoint, NUBEVENT_Exception, TRKDoNotifyStopped, TRKTargetCheckStep, TRKTargetSetStopped.
Referenced by TRKNubMainLoop.
DSError TRKTargetAddStopInfo(TRKBuffer *buffer)
References ProcessorState_PPC_6xx_7xx::Default, Extended1_PPC_6xx_7xx::exceptionID, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, Default_PPC::PC, TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32.
Referenced by TRKDoNotifyStopped.
DSError TRKTargetAddExceptionInfo(TRKBuffer *buffer)
References StopInfo_PPC::exceptionID, TRKExceptionStatus::exceptionInfo, gTRKExceptionStatus, StopInfo_PPC::PC, TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32.
Referenced by TRKDoNotifyStopped.
static DSError TRKTargetEnableTrace(BOOL val)
References DS_NoError, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, Extended1_PPC_6xx_7xx::MSR.
Referenced by TRKTargetCheckStep, TRKTargetDoStep.
static BOOL TRKTargetStepDone()
References TRKStepStatus::active, TRKStepStatus::count, ProcessorState_PPC_6xx_7xx::Default, DSSTEP_IntoCount, DSSTEP_IntoRange, Extended1_PPC_6xx_7xx::exceptionID, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, gTRKStepStatus, Default_PPC::PC, PPC_Trace, TRKStepStatus::rangeEnd, TRKStepStatus::rangeStart, TRKStepStatus::type.
Referenced by TRKTargetCheckStep.
static DSError TRKTargetDoStep()
References TRKStepStatus::active, TRKStepStatus::count, DS_NoError, DSSTEP_IntoCount, DSSTEP_OverCount, gTRKStepStatus, TRKTargetEnableTrace, TRKTargetSetStopped, TRKStepStatus::type.
Referenced by TRKTargetCheckStep, TRKTargetSingleStep, TRKTargetStepOutOfRange.
static BOOL TRKTargetCheckStep()
References TRKStepStatus::active, gTRKStepStatus, TRKTargetDoStep, TRKTargetEnableTrace, TRKTargetStepDone.
Referenced by TRKTargetInterrupt.
DSError TRKTargetSingleStep(u32 count, BOOL stepOver)
References TRKStepStatus::count, count, DS_NoError, DS_UnsupportedError, DSSTEP_IntoCount, gTRKStepStatus, TRKTargetDoStep, TRKStepStatus::type.
Referenced by TRKDoStep.
DSError TRKTargetStepOutOfRange(u32 rangeStart, u32 rangeEnd, BOOL stepOver)
References DS_NoError, DS_UnsupportedError, DSSTEP_IntoRange, gTRKStepStatus, TRKStepStatus::rangeEnd, TRKStepStatus::rangeStart, TRKTargetDoStep, TRKStepStatus::type.
Referenced by TRKDoStep.
u32 TRKTargetGetPC()
References ProcessorState_PPC_6xx_7xx::Default, gTRKCPUState, Default_PPC::PC.
Referenced by TRKDoStep.
DSError TRKTargetSupportRequest()
References ProcessorState_PPC_6xx_7xx::Default, DS_IOError, DS_IONoError, DS_NoError, DSMSG_ReadFile, DSMSG_WriteFile, Default_PPC::GPR, gTRKCPUState, Default_PPC::PC, TRK_flush_cache, TRKConstructEvent, TRKPostEvent, TRKSuppAccessFile.
Referenced by TRKHandleSupportEvent.
DSError TRKTargetFlushCache(u8, void *start, void *end)
References DS_InvalidMemory, DS_NoError, start, TRK_flush_cache.
Referenced by TRKDoFlushCache.
BOOL TRKTargetStopped()
References gTRKState, TRKState::isStopped.
Referenced by TRKDoContinue, TRKDoStep, TRKIdle.
void TRKTargetSetStopped(unsigned int stopped)
References gTRKState, TRKState::isStopped.
Referenced by TRKTargetContinue, TRKTargetDoStep, TRKTargetInterrupt, TRKTargetStop.
u32 TRKTargetStop()
References TRKTargetSetStopped.
Referenced by TRKDoStop.
DSError TRKPPCAccessSPR(void *value, u32 spr_register_num, BOOL read)
References INSTR_LWZ, INSTR_MFSPR, INSTR_MTSPR, INSTR_NOP, INSTR_STW, TRKPPCAccessSpecialReg.
Referenced by TRKPPCAccessFPRegister.
DSError TRKPPCAccessPairedSingleRegister(void *srcDestPtr, u32 psr, BOOL read)
References INSTR_NOP, INSTR_PSQ_L, INSTR_PSQ_ST, TRKPPCAccessSpecialReg.
DSError TRKPPCAccessFPRegister(void *srcDestPtr, u32 fpr, BOOL read)
References DS_NoError, DSFetch_u32, DSFetch_u64, INSTR_LFD, INSTR_NOP, INSTR_STFD, SPR_FPECR, TRKPPCAccessSpecialReg, TRKPPCAccessSPR.
DSError TRKPPCAccessSpecialReg(void *value, u32 *access_func, BOOL read)
References DS_NoError, INSTR_BLR, TRK_flush_cache, TRKvalue128_temp.
Referenced by TRKPPCAccessFPRegister, TRKPPCAccessPairedSingleRegister, TRKPPCAccessSPR.
void TRKTargetSetInputPendingPtr(void *ptr)
References gTRKState, TRKState::inputPendingPtr.
Referenced by TRKInitializeNub.