targimpl.h
typedef struct DSVersions DSVersions
typedef struct DSCPUType DSCPUType
typedef struct Default_PPC Default_PPC
typedef struct Float_PPC Float_PPC
typedef struct Extended1_PPC_6xx_7xx Extended1_PPC_6xx_7xx
typedef struct Extended2_PPC_6xx_7xx Extended2_PPC_6xx_7xx
typedef struct ProcessorState_PPC_6xx_7xx ProcessorState_PPC_6xx_7xx
typedef ProcessorState_PPC_6xx_7xx ProcessorState_PPC
typedef struct TRKState TRKState
ProcessorState_PPC gTRKCPUState
Referenced by InitMetroTRK, TRKInterruptHandler, TRKPostInterruptEvent, TRKRestoreExtended1Block, TRKSaveExtended1Block, TRKSwapAndGo, TRKTargetAddStopInfo, TRKTargetEnableTrace, TRKTargetGetPC, TRKTargetStepDone, TRKTargetSupportRequest, TRKTargetTranslate.
TRKState gTRKState
Referenced by TRKInitializeTarget, TRKInterruptHandler, TRKInterruptHandlerEnableInterrupts, TRKPostInterruptEvent, TRKSwapAndGo, TRKTargetSetInputPendingPtr, TRKTargetSetStopped, TRKTargetStopped.
void TRKTargetSetInputPendingPtr(void *ptr)
References gTRKState, TRKState::inputPendingPtr.
Referenced by TRKInitializeNub.
void TRKSwapAndGo()
References TRKState_PPC::CTR, TRKState_PPC::DAR, ProcessorState_PPC_6xx_7xx::Default, TRKState_PPC::DSISR, Default_PPC::GPR, TRKState_PPC::GPR, gTRKCPUState, gTRKExceptionStatus, gTRKState, TRKState_PPC::inputActivated, TRKState_PPC::inputPendingPtr, TRKState_PPC::LR, TRKState_PPC::MSR, Default_PPC::PC, r1, r2, r3, TRKInterruptHandlerEnableInterrupts, TRKRestoreExtended1Block, TRKState_PPC::XER.
Referenced by TRKTargetContinue.
void TRKTargetSetStopped(unsigned int)
References gTRKState, TRKState::isStopped.
Referenced by TRKTargetContinue, TRKTargetDoStep, TRKTargetInterrupt, TRKTargetStop.
DSError TRKTargetInterrupt(TRKEvent *)
References DS_NoError, DSMSG_NotifyStopped, TRKEvent::eventType, NUBEVENT_Breakpoint, NUBEVENT_Exception, TRKDoNotifyStopped, TRKTargetCheckStep, TRKTargetSetStopped.
Referenced by TRKNubMainLoop.
DSError TRKTargetSupportRequest()
References ProcessorState_PPC_6xx_7xx::Default, DS_IOError, DS_IONoError, DS_NoError, DSMSG_ReadFile, DSMSG_WriteFile, Default_PPC::GPR, gTRKCPUState, Default_PPC::PC, TRK_flush_cache, TRKConstructEvent, TRKPostEvent, TRKSuppAccessFile.
Referenced by TRKHandleSupportEvent.
void TRKDestructEvent(TRKEvent *)
DSError TRKTargetFlushCache(u8, void *start, void *end)
References DS_InvalidMemory, DS_NoError, start, TRK_flush_cache.
Referenced by TRKDoFlushCache.
BOOL TRKTargetStopped(void)
References gTRKState, TRKState::isStopped.
Referenced by TRKDoContinue, TRKDoStep, TRKIdle.
DSError TRKTargetAddStopInfo(TRKBuffer *b)
References ProcessorState_PPC_6xx_7xx::Default, Extended1_PPC_6xx_7xx::exceptionID, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, Default_PPC::PC, TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32.
Referenced by TRKDoNotifyStopped.
DSError TRKTargetAddExceptionInfo(TRKBuffer *b)
References StopInfo_PPC::exceptionID, TRKExceptionStatus::exceptionInfo, gTRKExceptionStatus, StopInfo_PPC::PC, TRKAppendBuffer1_ui16, TRKAppendBuffer1_ui32.
Referenced by TRKDoNotifyStopped.
DSError TRKTargetAccessARAM(u32 p1, u32 p2, u32 *p3, BOOL read)
DSError TRKTargetAccessMemory(void *data, u32 start, size_t *length, MemoryAccessOptions accessOptions, BOOL read)
Referenced by TRKDoReadMemory, TRKDoWriteMemory.
DSError TRKTargetAccessDefault(u32 firstRegister, u32 lastRegister, TRKBuffer *b, size_t *registersLengthPtr, BOOL read)
Referenced by TRKDoReadRegisters, TRKDoWriteRegisters.
DSError TRKTargetAccessFP(u32 firstRegister, u32 lastRegister, TRKBuffer *b, size_t *registersLengthPtr, BOOL read)
Referenced by TRKDoReadRegisters, TRKDoWriteRegisters.
DSError TRKTargetAccessExtended1(u32 firstRegister, u32 lastRegister, TRKBuffer *b, size_t *registersLengthPtr, BOOL read)
Referenced by TRKDoReadRegisters, TRKDoWriteRegisters.
DSError TRKTargetAccessExtended2(u32 firstRegister, u32 lastRegister, TRKBuffer *b, size_t *registerStorageSize, BOOL read)
Referenced by TRKDoReadRegisters, TRKDoWriteRegisters.
u32 TRKTargetGetPC()
References ProcessorState_PPC_6xx_7xx::Default, gTRKCPUState, Default_PPC::PC.
Referenced by TRKDoStep.
DSError TRKTargetSingleStep(u32 count, BOOL stepOver)
References TRKStepStatus::count, count, DS_NoError, DS_UnsupportedError, DSSTEP_IntoCount, gTRKStepStatus, TRKTargetDoStep, TRKStepStatus::type.
Referenced by TRKDoStep.
DSError TRKTargetStepOutOfRange(u32 rangeStart, u32 rangeEnd, BOOL stepOver)
References DS_NoError, DS_UnsupportedError, DSSTEP_IntoRange, gTRKStepStatus, TRKStepStatus::rangeEnd, TRKStepStatus::rangeStart, TRKTargetDoStep, TRKStepStatus::type.
Referenced by TRKDoStep.
u32 TRKTargetStop()
References TRKTargetSetStopped.
Referenced by TRKDoStop.
void TRKInterruptHandler()
References Default_PPC::CR, TRKState_PPC::CTR, TRKState_PPC::DAR, ProcessorState_PPC_6xx_7xx::Default, TRKState_PPC::DSISR, Extended1_PPC_6xx_7xx::exceptionID, ProcessorState_PPC_6xx_7xx::Extended1, Default_PPC::GPR, TRKState_PPC::GPR, gTRKCPUState, gTRKExceptionStatus, gTRKSaveState, gTRKState, TRKState_PPC::inputActivated, TRKState_PPC::inputPendingPtr, TRKExceptionStatus::inTRK, TRKState_PPC::LR, TRKState_PPC::MSR, Default_PPC::PC, r1, r2, r3, r4, ProcessorState_PPC_6xx_7xx::transport_handler_saved_ra, TRK_saved_exceptionID, TRKExceptionHandler, TRKPostInterruptEvent, TRKSaveExtended1Block, TRKUARTInterruptHandler, TRKState_PPC::XER.
Referenced by TRKLoadContext.
void TRKPostInterruptEvent(void)
References ProcessorState_PPC_6xx_7xx::Default, Extended1_PPC_6xx_7xx::exceptionID, ProcessorState_PPC_6xx_7xx::Extended1, gTRKCPUState, gTRKState, TRKState::inputActivated, NUBEVENT_Breakpoint, NUBEVENT_Exception, NUBEVENT_Support, Default_PPC::PC, TRKConstructEvent, TRKPostEvent.
Referenced by TRKInterruptHandler, TRKInterruptHandlerEnableInterrupts.
DSError TRKTargetVersions(DSVersions *versions)
Referenced by TRKDoVersions.
DSError TRKTargetSupportMask(u8 mask[32])
References DS_NoError.
Referenced by TRKDoSupportMask.
DSError TRKTargetCPUType(DSCPUType *cpuType)
References DSCPUType::bigEndian, DSCPUType::cpuMajor, DSCPUType::cpuMinor, DSCPUType::defaultTypeSize, DS_NoError, DSCPUType::extended1TypeSize, DSCPUType::extended2TypeSize, DSCPUType::fpTypeSize, gTRKBigEndian, TRKTargetCPUMinorType.
Referenced by TRKDoCPUType.