tgmath.h
float exp(float x)
Referenced by __dec2num, exp, frexp, frexp, frexp, frexpf, ldexp, ldexp, log10f.
float log(float x)
Referenced by log.
float log10(float x)
References log10f.
Referenced by log10.
float pow(float x, float y)
Referenced by __dec2num, pow.
float sqrt(float x)
References sqrtf.
Referenced by __ieee754_acos, __ieee754_acosh, __ieee754_asin, __ieee754_hypot, __ieee754_pow, asinh, sqrt.
float fabs(float x)
References fabsf.
Referenced by __ieee754_asin, __ieee754_atan2, __ieee754_cosh, __ieee754_lgamma_r, __ieee754_pow, __ieee754_rem_pio2, __ieee754_remainder, __ieee754_sinh, __kernel_tan, acos, asin, asinh, atan, atanh, cosh, erf, erfc, fabs, logb, strtod, tanh, wcstod.
float ceil(float x)
float floor(float x)
Referenced by __kernel_rem_pio2, gamma, lgamma, sin_pi.
float ldexp(float x, _INT32 n)
Referenced by ldexp.
float frexp(float x, int *exp)
References exp.
Referenced by __num2dec, frexp.
float tan(float x)
References tanf.
Referenced by tan.
float acos(float x)
References acosf.
Referenced by acos.
float asin(float x)
References asinf.
Referenced by asin.
float atan2(float x, float y)
References atan2f.
Referenced by atan2.
float atan(float x)
References atanf.
Referenced by __ieee754_atan2, acosf, asinf, atan.
float sin(float x)
References sinf.
Referenced by sin, tanf.
float cos(float x)
References cosf.
Referenced by cos, tanf.
float cosh(float x)
References coshf.
Referenced by cosh.
float sinh(float x)
References sinhf.
Referenced by sinh.
float tanh(float x)
References tanhf.
Referenced by tanh.
float fmod(float x, float y)
References fmodf.
Referenced by fmod.
long double acos(long double x)
long double asin(long double x)
long double atan(long double x)
long double atan2(long double y, long double x)
long double cos(long double x)
long double sin(long double x)
long double tan(long double x)
long double cosh(long double x)
long double sinh(long double x)
long double tanh(long double x)
long double fmod(long double x, long double y)
long double ceil(long double x)
long double floor(long double x)
long double exp(long double x)
long double frexp(long double x, int *exp)
References exp.
long double ldexp(long double x, int exp)
References exp.
long double log(long double x)
long double log10(long double x)
long double fabs(long double x)
long double pow(long double x, long double y)
long double sqrt(long double x)
double fmod(const T &x, const U &y)
References fmod.
double ldexp(const T &x, int exp)
References exp, ldexp.
double ceil(const T &x)
double floor(const T &x)
double acos(const T &x)
References acos.
double asin(const T &x)
References asin.
double atan(const T &x)
References atan.
double atan2(const T &y, const U &x)
References atan2.
double cos(const T &x)
References cos.
double sin(const T &x)
References sin.
double tan(const T &x)
References tan.
double cosh(const T &x)
References cosh.
double sinh(const T &x)
References sinh.
double tanh(const T &x)
References tanh.
double exp(const T &x)
References exp.
double frexp(const T &x, int *exp)
References exp, frexp.
double log(const T &x)
References log.
double log10(const T &x)
References log10.
double fabs(const T &x)
References fabs.
double pow(const T &x, const U &y)
References pow.
double sqrt(const T &x)
References sqrt.