time.c
seconds_per_minute
seconds_per_hour
seconds_per_day
const short __month_to_days[2][13][2][13]
Referenced by __time2tm, __tm2time.
const char* day_name[][]
Referenced by asciitime.
const char* month_name[][]
Referenced by asciitime.
int __leap_year(int year)
References __mod.
Referenced by __time2tm, leap_days.
static int leap_days(int year, int mon)
References __div, __leap_year, div, div_t::quot.
Referenced by __tm2time.
static int adjust(int *x, int y, int *z)
References __add, __div, div_t::quot, div_t::rem.
Referenced by __tm2time, strcmp, strcpy.
static void __time2tm(time_t inTime, struct tm *tm)
References __leap_year, __month_to_days, seconds_per_day, seconds_per_hour, seconds_per_minute, time.
Referenced by __tm2time.
static int __tm2time(struct tm *tm, time_t *time)
References __ladd, __lmul, __month_to_days, __time2tm, adjust, leap_days, seconds_per_day, seconds_per_hour, seconds_per_minute, time.
static void asciitime(struct tm tm, char *str)
References day_name, month_name.
static void clear_tm(struct tm *tm)
clock_t clock(void)
References __get_clock.
time_t time(time_t *timer)
References __get_time, time.
Referenced by __time2tm, __time2tm, __tm2time, __tm2time, time.
static int emit(char *str, size_t size, size_t *max_size, const char *format_str,...)
References format_str, size, vsprintf.
static int week_num(const struct tm *tm, int starting_day)
References __mod.