trigf.c
__PIO2__
__PI
__two_over_pi
__four_over_pi
__SQRT_FLT_EPSILON__
__sqrt2_m1
__ln2
__FAST_MATH_MODE__
__FAST_MATH_MODE__
const float __sincos_poly[][]
Referenced by cosf, sinf.
const float __sincos_on_quadrant[][]
Referenced by cosf, sinf.
const int tmp_float[4][4]
const float __four_over_pi_m1[][]
Referenced by cosf, sinf.
float sinf(float x)
References __four_over_pi_m1, __HI, __sincos_on_quadrant, __sincos_poly, __SQRT_FLT_EPSILON__, __two_over_pi, fabsf.
Referenced by sin.
float cosf(float x)
References __four_over_pi_m1, __HI, __sincos_on_quadrant, __sincos_poly, __SQRT_FLT_EPSILON__, __two_over_pi, fabsf.
Referenced by cos.
float tanf(float x)
References cos, sin.
Referenced by tan.