wchar_io.c
wchar_t putwc(wchar_t c, FILE *file)
References fwide, fwrite.
Referenced by fputwc, fputws.
wchar_t putwchar(wchar_t c)
References fwide, fwrite.
wchar_t fputwc(wchar_t c, FILE *file)
References putwc.
wchar_t getwc(FILE *file)
References fread, fwide.
Referenced by fgetwc, fgetws.
wchar_t getwchar(void)
References fread, fwide.
wchar_t fgetwc(FILE *file)
References getwc.
Referenced by __wFileRead.
wchar_t ungetwc(wchar_t c, FILE *file)
References fwide.
Referenced by __wFileRead.
int fputws(const wchar_t *s, FILE *file)
References errno, fwide, putwc.
wchar_t * fgetws(wchar_t *s, int n, FILE *file)
References fwide, getwc, NULL.
int fwide(FILE *stream, int mode)
Referenced by fgetws, fprintf, fputws, fread, fscanf, fwprintf, fwrite, fwscanf, getwc, getwchar, putwc, putwchar, scanf, ungetc, ungetwc, vfprintf, vfwprintf, vprintf, vwprintf, wprintf, wscanf.