wcstoul.h
unsigned long __wcstoul(int base, int max_width, __std(wint_t)(*ReadProc)(void *, __std(wint_t), int), void *ReadProcArg, int *chars_scanned, int *negative, int *overflow)
Referenced by __wsformatter.
unsigned long wcstoul(const wchar_t *str, wchar_t **end, int base)
References __wcstoul, __wStringRead, count, errno.
Referenced by wcstoumax.
long wcstol(const wchar_t *str, wchar_t **end, int base)
References __wcstoul, __wStringRead, count, errno.
Referenced by watoi, watol, wcstoimax.
int watoi(const wchar_t *str)
References NULL, wcstol.
long watol(const wchar_t *str)
References NULL, wcstol.