wprintf.c
conversion_buff_size
conversion_max
bad_conversion
MAX_SIG_DIG
justification_options
sign_options
argument_options
static const wchar_t * parse_format(const wchar_t *format_string, va_list *arg, print_format *format)
References print_format::alternate_form, print_format::argument_options, bad_conversion, print_format::conversion_char, conversion_max, print_format::field_width, print_format::justification_options, left_justification, long_argument, long_double_argument, long_long_argument, normal_argument, only_minus, print_format::precision, print_format::precision_specified, right_justification, short_argument, sign_always, print_format::sign_options, space_holder, wchar_argument, zero_fill.
Referenced by __wpformatter.
static wchar_t * long2str(long num, wchar_t *buff, print_format format)
References print_format::alternate_form, print_format::conversion_char, conversion_max, print_format::field_width, print_format::justification_options, NULL, only_minus, print_format::precision, sign_always, print_format::sign_options, space_holder, zero_fill.
Referenced by __wpformatter.
static void round_decimal(decimal *dec, int new_length)
References decimal::exp, decimal::length, decimal::sgn, decimal::sig, decimal::text.
Referenced by float2str.
static wchar_t * float2str(long double num, wchar_t *wbuff, print_format format)
References __num2dec, print_format::alternate_form, conversion_buff_size, print_format::conversion_char, conversion_max, decform::digits, decimal::exp, FLOATDECIMAL, decimal::length, MAX_SIG_DIG, NULL, print_format::precision, round_decimal, decimal::sgn, decimal::sig, sign_always, print_format::sign_options, space_holder, strlen, decform::style, decimal::text, wcscpy.
Referenced by __wpformatter.
static int __wpformatter(void *(*wWriteProc)(void *, const wchar_t *, size_t), void *WriteProcArg, const wchar_t *format_str, va_list arg)
References print_format::alternate_form, print_format::argument_options, bad_conversion, conversion_buff_size, print_format::conversion_char, print_format::field_width, float2str, format_str, print_format::justification_options, left_justification, long2str, long_argument, long_double_argument, long_long_argument, mbstowcs, mbtowc, memchr, normal_argument, NULL, parse_format, print_format::precision, print_format::precision_specified, short_argument, strlen, wchar_argument, wcschr, wcslen, wmemchr, zero_fill.
Referenced by fwprintf, vfwprintf, vswprintf, vwprintf, wprintf.
void * __wFileWrite(void *File, const wchar_t *Buffer, size_t NumChars)
References fwrite.
Referenced by fwprintf, vfwprintf, vwprintf, wprintf.
void * __wStringWrite(void *wosc, const wchar_t *Buffer, size_t NumChars)
References wmemcpy.
Referenced by vswprintf.
int wprintf(const wchar_t *format,...)
References __wFileWrite, __wpformatter, fwide.
int fwprintf(FILE *file, const wchar_t *format,...)
References __wFileWrite, __wpformatter, fwide.
int vwprintf(const wchar_t *format, va_list arg)
References __wFileWrite, __wpformatter, fwide.
int vfwprintf(FILE *file, const wchar_t *format, va_list arg)
References __wFileWrite, __wpformatter, fwide.
int swprintf(wchar_t *s, size_t n, const wchar_t *format,...)
References vswprintf.
Referenced by wasciitime.
int vswprintf(wchar_t *s, size_t n, const wchar_t *format, va_list arg)
References __wpformatter, __wStringWrite, count.
Referenced by swprintf, wemit.