wprintf.h
int fwprintf(FILE *file, const wchar_t *format,...)
References __wFileWrite, __wpformatter, fwide.
int wprintf(const wchar_t *format,...)
References __wFileWrite, __wpformatter, fwide.
int swprintf(wchar_t *s, size_t n, const wchar_t *format,...)
References vswprintf.
Referenced by wasciitime.
int vfwprintf(FILE *file, const wchar_t *format_str, va_list arg)
References __wFileWrite, __wpformatter, fwide.
int vswprintf(wchar_t *s, size_t n, const wchar_t *format, va_list arg)
References __wpformatter, __wStringWrite, count.
Referenced by swprintf, wemit.
int vwprintf(const wchar_t *format, va_list arg)
References __wFileWrite, __wpformatter, fwide.