wscanf.h
int fwscanf(FILE *file, const wchar_t *format,...)
References __vfwscanf, __wFileRead, __wsformatter, EOF, fwide.
int wscanf(const wchar_t *format,...)
References __vfwscanf, __wFileRead, __wsformatter, EOF, fwide.
int swscanf(const wchar_t *s, const wchar_t *format,...)
References __vswscanf.
int __vswscanf(const wchar_t *s, const wchar_t *format, va_list arg)
References __wsformatter, __wStringRead.
Referenced by swscanf.
int __vfwscanf(FILE *file, const wchar_t *format_str, va_list arg)
Referenced by fwscanf, wscanf.
int vwscanf(const wchar_t *format, va_list arg)
References __wFileRead, __wsformatter.