wscanf.c
conversion_buff_size
conversion_max
bad_conversion
set_char_map
tst_char_map
argument_options
typedef wchar_t char_map[32][32]
static const wchar_t * parse_format(const wchar_t *format_string, scan_format *format)
References scan_format::argument_options, bad_conversion, scan_format::char_set, scan_format::conversion_char, double_argument, scan_format::field_width, scan_format::field_width_specified, long_argument, long_double_argument, long_long_argument, normal_argument, set_char_map, short_argument, scan_format::suppress_assignment, wchar_argument.
Referenced by __wsformatter.
static int __wsformatter(wint_t(*wReadProc)(void *, wint_t, int), void *wReadProcArg, const wchar_t *format_str, va_list arg)
References __wcstold, __wcstoul, scan_format::argument_options, bad_conversion, scan_format::char_set, scan_format::conversion_char, double_argument, exit, scan_format::field_width, scan_format::field_width_specified, format_str, long_argument, long_double_argument, long_long_argument, normal_argument, parse_format, short_argument, scan_format::suppress_assignment, tst_char_map, wchar_argument, wctomb.
Referenced by __vswscanf, fwscanf, vwscanf, wscanf.
wint_t __wFileRead(void *File, wint_t ch, int Action)
References feof, ferror, fgetwc, ungetwc.
Referenced by fwscanf, vwscanf, wscanf.
wint_t __wStringRead(void *isc, wint_t ch, int Action)
References NULL.
Referenced by __vswscanf, wcstod, wcstol, wcstoul.
int fwscanf(FILE *file, const wchar_t *format,...)
References __vfwscanf, __wFileRead, __wsformatter, EOF, fwide.
int wscanf(const wchar_t *format,...)
References __vfwscanf, __wFileRead, __wsformatter, EOF, fwide.
int vwscanf(const wchar_t *format, va_list arg)
References __wFileRead, __wsformatter.
int __vswscanf(const wchar_t *s, const wchar_t *format, va_list arg)
References __wsformatter, __wStringRead.
Referenced by swscanf.
int swscanf(const wchar_t *s, const wchar_t *format,...)
References __vswscanf.