wstdio.h
wchar_t putwc(wchar_t c, FILE *file)
References fwide, fwrite.
Referenced by fputwc, fputws.
wchar_t fputwc(wchar_t c, FILE *file)
References putwc.
wchar_t getwc(FILE *file)
References fread, fwide.
Referenced by fgetwc, fgetws.
wchar_t fgetwc(FILE *file)
References getwc.
Referenced by __wFileRead.
int fputws(const wchar_t *s, FILE *file)
References errno, fwide, putwc.
wchar_t * fgetws(wchar_t *s, int n, FILE *file)
References fwide, getwc, NULL.
wchar_t putwchar(wchar_t c)
References fwide, fwrite.
wchar_t getwchar(void)