wstring.c
set_wchar_map
tst_wchar_map
typedef wchar_t wchar_map[32][32]
size_t() wcslen(const wchar_t *str)
Referenced by __wpformatter, wasciitime, wcsxfrm.
wchar_t *() wcscpy(wchar_t *dst, const wchar_t *src)
Referenced by float2str.
wchar_t * wcsncpy(wchar_t *dst, const wchar_t *src, size_t n)
References zero.
Referenced by wcsxfrm.
wchar_t * wcscat(wchar_t *dst, const wchar_t *src)
wchar_t * wcsncat(wchar_t *dst, const wchar_t *src, size_t n)
int wcscmp(const wchar_t *str1, const wchar_t *str2)
Referenced by wcscoll.
int wcsncmp(const wchar_t *str1, const wchar_t *str2, size_t n)
wchar_t * wcschr(const wchar_t *str, const wchar_t chr)
Referenced by __wpformatter.
int wcscoll(const wchar_t *str1, const wchar_t *str2)
References wcscmp.
size_t wcsxfrm(wchar_t *str1, const wchar_t *str2, size_t n)
References wcslen, wcsncpy.
wchar_t * wcsrchr(const wchar_t *str, wchar_t chr)
wchar_t * wcspbrk(const wchar_t *str, const wchar_t *set)
References NULL, set_wchar_map, tst_wchar_map.
size_t wcsspn(const wchar_t *str, const wchar_t *set)
References set_wchar_map, tst_wchar_map.
size_t wcscspn(const wchar_t *str, const wchar_t *set)
References set_wchar_map, tst_wchar_map.
wchar_t * wcstok(wchar_t *str, const wchar_t *set)
References NULL, set_wchar_map, tst_wchar_map.
wchar_t * wcsstr(const wchar_t *str, const wchar_t *pat)
References NULL, s1, s2.