wtime.c
seconds_per_minute
seconds_per_hour
seconds_per_day
const short month_to_days[2][13][2][13]
Referenced by __time2tm, __tm2time.
const wchar_t* day_name[][]
Referenced by wasciitime.
const wchar_t* month_name[][]
Referenced by wasciitime.
static int leap_year(int year)
References __mod.
Referenced by __time2tm, leap_days.
static int leap_days(int year, int mon)
References __div, div, leap_year, div_t::quot.
Referenced by __tm2time.
static int adjust(int *x, int y, int *z)
References __add, __div, div_t::quot, div_t::rem.
Referenced by __tm2time.
static void __time2tm(time_t inTime, struct tm *tm)
References leap_year, month_to_days, seconds_per_day, seconds_per_hour, seconds_per_minute, time.
Referenced by __tm2time.
static int __tm2time(struct tm *tm, time_t *time)
References __ladd, __lmul, __time2tm, adjust, leap_days, month_to_days, seconds_per_day, seconds_per_hour, seconds_per_minute, time.
static void wasciitime(struct tm tm, wchar_t *str)
References day_name, month_name, swprintf, wcslen.
static void clear_tm(struct tm *tm)
static int wemit(wchar_t *str, size_t size, size_t *max_size, const wchar_t *format_str,...)
References format_str, size, vswprintf.
static int week_num(const struct tm *tm, int starting_day)
References __mod.