__start.c
EXCEPTIONMASK_ADDR
BOOTINFO2_ADDR
OS_BI2_DEBUGFLAG_OFFSET
ARENAHI_ADDR
DEBUGFLAG_ADDR
DVD_DEVICECODE_ADDR
typedef struct __rom_copy_info __rom_copy_info
typedef struct __bss_init_info __bss_init_info
SEC_INIT s8 _stack_addr[][]
Referenced by __init_registers.
SEC_INIT s8 _SDA_BASE_[][]
Referenced by __init_registers.
SEC_INIT s8 _SDA2_BASE_[][]
Referenced by __init_registers.
SEC_INIT __rom_copy_info _rom_copy_info[][]
Referenced by __init_data.
SEC_INIT __bss_init_info _bss_init_info[][]
Referenced by __init_data.
int main(int argc, char *argv[])
Referenced by __start.
void exit(int)
References __fini_cpp, _ExitProcess.
Referenced by __start, FIOFclose, FIOFerror, FIOFflush, FIOFindFirst, FIOFindNext, FIOFopen, FIOFprintf, FIOFread, FIOFreadAsync, FIOFseek, FIOFstat, FIOFwrite, FIOFwriteAsync, FIOInit, fioPacketReceiveResult, fioPacketResultRead, fioPacketResultWrite, FIOQuery, IsChannelOpened, MCCClose, MCCLock, MCCOpen, MCCRead, MCCStreamWrite, MCCUnlock, MCCWrite, NotifyCompulsorily, PSMTXROMultS16VecArray, PSMTXROMultVecArray.
SEC_INIT void __init_hardware(void)
Referenced by __start.
SEC_INIT void __flush_cache(void *address, u32 size)
Referenced by __copy_rom_section.
asm void __init_registers(void)
References _SDA2_BASE_, _SDA_BASE_, _stack_addr, CARD_MAX_MOUNT_STEP.
Referenced by __start.
void __init_data(void)
References __copy_rom_section, __init_bss_section, _bss_init_info, _rom_copy_info, CARD_MAX_MOUNT_STEP, TRUE.
Referenced by __start.
SEC_INIT void __start(void)
References __init_data, __init_hardware, __init_registers, __init_user, ARENAHI_ADDR, BOOTINFO2_ADDR, CARD_MAX_MOUNT_STEP, DBInit, EXCEPTIONMASK_ADDR, exit, main, OS_BI2_DEBUGFLAG_OFFSET, OSInit.
void __copy_rom_section(void *dst, const void *src, u32 size)
References __flush_cache, CARD_MAX_MOUNT_STEP.
Referenced by __init_data.
void __init_bss_section(void *dst, u32 size)
References CARD_MAX_MOUNT_STEP.
Referenced by __init_data.