__ppc_eabi_init.cpp
DECL_SECT(".ctors") extern void(*_ctors[])()
DECL_SECT(".dtors") extern void(*_dtors[])()
asm void __init_hardware(void)
References __OSCacheInit, __OSPSInit, CARD_MAX_MOUNT_STEP, MSR_FP.
Referenced by __start.
asm void __flush_cache(void *address, u32 size)
References CARD_MAX_MOUNT_STEP.
Referenced by __copy_rom_section.
void __init_user(void)
References __init_cpp.
Referenced by __start.
void __init_cpp(void)
References CARD_MAX_MOUNT_STEP.
Referenced by __init_user.
void __fini_cpp(void)
References CARD_MAX_MOUNT_STEP.
Referenced by exit.
WEAKFUNC void abort(void)
References _ExitProcess.
Referenced by __BypassDoneRender.
WEAKFUNC void exit(int status)
References __fini_cpp, _ExitProcess.
Referenced by __start, FIOFclose, FIOFerror, FIOFflush, FIOFindFirst, FIOFindNext, FIOFopen, FIOFprintf, FIOFread, FIOFreadAsync, FIOFseek, FIOFstat, FIOFwrite, FIOFwriteAsync, FIOInit, fioPacketReceiveResult, fioPacketResultRead, fioPacketResultWrite, FIOQuery, IsChannelOpened, MCCClose, MCCLock, MCCOpen, MCCRead, MCCStreamWrite, MCCUnlock, MCCWrite, NotifyCompulsorily, PSMTXROMultS16VecArray, PSMTXROMultVecArray.
void _ExitProcess(void)
References PPCHalt.
Referenced by abort, exit.