AXAux.c
void(* __AXCallbackAuxA) (void *, void *))(void *, void *)
Referenced by __AXAuxInit, __AXAuxQuit, __AXProcessAux, AXRegisterAuxACallback.
void(* __AXCallbackAuxB) (void *, void *))(void *, void *)
Referenced by __AXAuxInit, __AXAuxQuit, __AXProcessAux, AXRegisterAuxBCallback.
void* __AXContextAuxA
Referenced by __AXAuxInit, __AXProcessAux, AXRegisterAuxACallback.
void* __AXContextAuxB
Referenced by __AXAuxInit, __AXProcessAux, AXRegisterAuxBCallback.
s32* __AXAuxADspWrite
Referenced by __AXProcessAux.
s32* __AXAuxADspRead
Referenced by __AXProcessAux.
s32* __AXAuxBDspWrite
Referenced by __AXProcessAux.
s32* __AXAuxBDspRead
Referenced by __AXProcessAux.
u32 __AXAuxDspWritePosition
Referenced by __AXAuxInit, __AXGetAuxAInput, __AXGetAuxBInput, __AXProcessAux.
u32 __AXAuxDspReadPosition
Referenced by __AXAuxInit, __AXGetAuxAOutput, __AXGetAuxBOutput, __AXProcessAux.
u32 __AXAuxCpuReadWritePosition
Referenced by __AXAuxInit, __AXProcessAux.
static s32 __AXBufferAuxA[3][480] ALIGN(32)
void __AXAuxInit(void)
References __AXAuxCpuReadWritePosition, __AXAuxDspReadPosition, __AXAuxDspWritePosition, __AXCallbackAuxA, __AXCallbackAuxB, __AXContextAuxA, __AXContextAuxB, NULL, OSReport.
Referenced by AXInit.
void __AXAuxQuit(void)
References __AXCallbackAuxA, __AXCallbackAuxB, NULL, OSReport.
Referenced by AXQuit.
void __AXGetAuxAInput(u32 *p)
References __AXAuxDspWritePosition.
Referenced by __AXNextFrame.
void __AXGetAuxAOutput(u32 *p)
References __AXAuxDspReadPosition.
Referenced by __AXNextFrame.
void __AXGetAuxBInput(u32 *p)
References __AXAuxDspWritePosition.
Referenced by __AXNextFrame.
void __AXGetAuxBOutput(u32 *p)
References __AXAuxDspReadPosition.
Referenced by __AXNextFrame.
void __AXProcessAux(void)
References __AXAuxADspRead, __AXAuxADspWrite, __AXAuxBDspRead, __AXAuxBDspWrite, __AXAuxCpuReadWritePosition, __AXAuxDspReadPosition, __AXAuxDspWritePosition, __AXCallbackAuxA, __AXCallbackAuxB, __AXClMode, __AXContextAuxA, __AXContextAuxB, DCFlushRangeNoSync, DCInvalidateRange, AX_AUX_DATA::l, AX_AUX_DATA::r, AX_AUX_DATA::s.
Referenced by __AXOutNewFrame.
void AXRegisterAuxACallback(void(*callback)(void *, void *), void *context)
References __AXCallbackAuxA, __AXContextAuxA.
void AXRegisterAuxBCallback(void(*callback)(void *, void *), void *context)
References __AXCallbackAuxB, __AXContextAuxB.