AXCL.c
u16 __AXHRTFHistory[128][128]
Referenced by __AXNextFrame, AXSetMode.
u16 __AXCommandList[2][384][2][384]
Referenced by __AXClInit, __AXGetCommandListAddress.
u32 __AXCommandListPosition
Referenced by __AXClInit, __AXGetCommandListAddress.
u16* __AXClWrite
Referenced by __AXClInit, __AXGetCommandListAddress, __AXNextFrame, __AXWriteToCommandList.
u32 __AXCommandListCycles
Referenced by __AXGetCommandListCycles, __AXNextFrame.
u32 __AXClMode
Referenced by __AXClInit, __AXNextFrame, __AXProcessAux, AXGetMode, AXSetMode, AXSetVoiceMix.
u32 __AXGetCommandListCycles(void)
References __AXCommandListCycles.
Referenced by __AXSyncPBs.
u32 __AXGetCommandListAddress(void)
References __AXClWrite, __AXCommandList, __AXCommandListPosition.
Referenced by __AXOutNewFrame.
void __AXWriteToCommandList(u16 data)
References __AXClWrite.
Referenced by __AXNextFrame.
void __AXNextFrame(void *sbuffer, void *buffer)
References __AXClMode, __AXClWrite, __AXCommandListCycles, __AXGetAuxAInput, __AXGetAuxAOutput, __AXGetAuxBInput, __AXGetAuxBOutput, __AXGetPBs, __AXGetStudio, __AXHRTFHistory, __AXWriteToCommandList, buffer, DCFlushRange.
Referenced by __AXOutInit, __AXOutNewFrame.
void __AXClInit(void)
References __AXClMode, __AXClWrite, __AXCommandList, __AXCommandListPosition, OSReport.
Referenced by AXInit.
void __AXClQuit(void)
References OSReport.
Referenced by AXQuit.
void AXSetMode(u32 mode)
References __AXClMode, __AXHRTFHistory.
u32 AXGetMode(void)
References __AXClMode.