AXSPB.c
s32 __AXSpbAL
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbAR
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbAS
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbAAL
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbAAR
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbAAS
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbABL
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbABR
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
s32 __AXSpbABS
Referenced by __AXDepopVoice, __AXPrintStudio, __AXSPBInit.
static struct _AXSPB __AXStudio ALIGN(32)
u32 __AXGetStudio(void)
Referenced by __AXNextFrame.
void __AXDepopFade(s32 *hostSum, long *dspVolume, s16 *dspDelta)
Referenced by __AXPrintStudio.
void __AXPrintStudio(void)
References __AXDepopFade, __AXSpbAAL, __AXSpbAAR, __AXSpbAAS, __AXSpbABL, __AXSpbABR, __AXSpbABS, __AXSpbAL, __AXSpbAR, __AXSpbAS, DCFlushRange.
Referenced by __AXOutNewFrame.
void __AXSPBInit(void)
References __AXSpbAAL, __AXSpbAAR, __AXSpbAAS, __AXSpbABL, __AXSpbABR, __AXSpbABS, __AXSpbAL, __AXSpbAR, __AXSpbAS, OSReport.
Referenced by AXInit.
void __AXSPBQuit(void)
References OSReport.
Referenced by AXQuit.
void __AXDepopVoice(AXPB *p)
References __AXSpbAAL, __AXSpbAAR, __AXSpbAAS, __AXSpbABL, __AXSpbABR, __AXSpbABS, __AXSpbAL, __AXSpbAR, __AXSpbAS, _AXPBDPOP::aAuxAL, _AXPBDPOP::aAuxAR, _AXPBDPOP::aAuxAS, _AXPBDPOP::aAuxBL, _AXPBDPOP::aAuxBR, _AXPBDPOP::aAuxBS, _AXPBDPOP::aL, _AXPBDPOP::aR, _AXPBDPOP::aS, _AXPB::dpop.
Referenced by __AXDumpVPB, __AXSyncPBs.