AXVPB.c
u32 __AXSrcCycles[5][5]
Referenced by __AXSyncPBs.
u32 __AXMixCycles[32][32]
Referenced by __AXSyncPBs.
AXVPB __AXVPB[AX_MAX_VOICES][AX_MAX_VOICES]
Referenced by __AXVPBInit.
u32 __AXMaxDspCycles
Referenced by __AXSyncPBs, __AXVPBInit, AXGetMaxDspCycles, AXSetMaxDspCycles.
u32 __AXRecDspCycles
Referenced by __AXSyncPBs, __AXVPBInit, AXGetDspCycles.
u32 __AXNumVoices
Referenced by __AXGetNumVoices, __AXServiceVPB, __AXSyncPBs.
static AXPB __AXPB[AX_MAX_VOICES] ALIGN(32)
u32 __AXGetNumVoices(void)
References __AXNumVoices.
Referenced by __AXOutNewFrame.
void __AXServiceVPB(AXVPB *pvpb)
References __AXNumVoices, _AXPB::addr, _AXPB::adpcm, _AXPB::adpcmLoop, AX_MAX_VOICES, AX_SYNC_FLAG_COPYADDR, AX_SYNC_FLAG_COPYADPCM, AX_SYNC_FLAG_COPYADPCMLOOP, AX_SYNC_FLAG_COPYALL, AX_SYNC_FLAG_COPYAXPBMIX, AX_SYNC_FLAG_COPYCURADDR, AX_SYNC_FLAG_COPYDPOP, AX_SYNC_FLAG_COPYENDADDR, AX_SYNC_FLAG_COPYFIR, AX_SYNC_FLAG_COPYITD, AX_SYNC_FLAG_COPYLOOP, AX_SYNC_FLAG_COPYLOOPADDR, AX_SYNC_FLAG_COPYMXRCTRL, AX_SYNC_FLAG_COPYRATIO, AX_SYNC_FLAG_COPYSELECT, AX_SYNC_FLAG_COPYSRC, AX_SYNC_FLAG_COPYSTATE, AX_SYNC_FLAG_COPYTSHIFT, AX_SYNC_FLAG_COPYTYPE, AX_SYNC_FLAG_COPYUPDATE, AX_SYNC_FLAG_COPYVOL, AX_SYNC_FLAG_SWAPVOL, _AXPB::coefSelect, _AXPBADDR::currentAddressHi, _AXPBADDR::currentAddressLo, _AXPBVE::currentDelta, _AXPBVE::currentVolume, _AXPB::dpop, _AXPBADDR::endAddressHi, _AXPB::fir, _AXVPB::index, _AXPB::itd, _AXVPB::itdBuffer, _AXPBADDR::loopAddressHi, _AXPBADDR::loopFlag, _AXPB::mix, _AXPB::mixerCtrl, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPBSRC::ratioLo, _AXPB::src, src, _AXPB::srcSelect, _AXPB::state, _AXVPB::sync, sync, _AXPBITD::targetShiftL, _AXPBITD::targetShiftR, _AXPB::type, _AXPB::update, _AXVPB::updateCounter, _AXVPB::updateData, _AXPB::ve.
Referenced by __AXSyncPBs.
void __AXDumpVPB(AXVPB *pvpb)
References __AXDepopVoice, __AXPushCallbackStack, _AXVPB::index, _AXVPB::pb, _AXPB::state, _AXPB::update, _AXPBUPDATE::updNum.
Referenced by __AXSyncPBs.
void __AXSyncPBs(u32 lessDspCycles)
References __AXDepopVoice, __AXDumpVPB, __AXGetCommandListCycles, __AXGetStackHead, __AXMaxDspCycles, __AXMixCycles, __AXNumVoices, __AXRecDspCycles, __AXServiceVPB, __AXSrcCycles, DCFlushRange, DCInvalidateRange, _AXVPB::depop, _AXVPB::index, _AXPB::mixerCtrl, _AXVPB::next, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPB::src, _AXPB::state, _AXVPB::sync, _AXVPB::updateCounter, _AXVPB::updateData, _AXVPB::updateMS, _AXVPB::updateWrite.
Referenced by __AXOutNewFrame.
AXPB * __AXGetPBs(void)
Referenced by __AXNextFrame.
void __AXSetPBDefault(AXVPB *p)
References _AXPBITD::flag, _AXPB::itd, _AXVPB::pb, _AXPB::state, _AXVPB::sync, _AXPB::update, _AXVPB::updateCounter, _AXVPB::updateData, _AXVPB::updateMS, _AXVPB::updateWrite, _AXPBUPDATE::updNum.
Referenced by __AXVPBInit, AXAcquireVoice, AXFreeVoice.
void __AXVPBInit(void)
References __AXMaxDspCycles, __AXPushFreeStack, __AXRecDspCycles, __AXSetPBDefault, __AXVPB, AX_MAX_VOICES, _AXPBITD::bufferHi, _AXPBITD::bufferLo, _AXPB::currHi, _AXPB::currLo, _AXPBUPDATE::dataHi, _AXPBUPDATE::dataLo, DCFlushRange, _AXVPB::index, _AXPB::itd, _AXVPB::itdBuffer, _AXPB::nextHi, _AXPB::nextLo, OS_BUS_CLOCK, OSReport, _AXVPB::pb, _AXPB::update, _AXVPB::updateData, _AXVPB::updateWrite.
Referenced by AXInit.
void __AXVPBQuit(void)
References OSReport.
Referenced by AXQuit.
void AXSetVoiceSrcType(AXVPB *p, u32 type)
References AX_SRC_TYPE_4TAP_12K, AX_SRC_TYPE_4TAP_16K, AX_SRC_TYPE_4TAP_8K, AX_SRC_TYPE_LINEAR, AX_SRC_TYPE_NONE, AX_SYNC_FLAG_COPYSELECT, _AXPB::coefSelect, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::srcSelect, _AXVPB::sync.
void AXSetVoiceState(AXVPB *p, u16 state)
References AX_SYNC_FLAG_COPYSTATE, _AXVPB::depop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::state, _AXVPB::sync.
void AXSetVoiceType(AXVPB *p, u16 type)
References AX_SYNC_FLAG_COPYTYPE, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPB::type.
void AXSetVoiceMix(AXVPB *p, AXPBMIX *mix)
References __AXClMode, AX_SYNC_FLAG_COPYAXPBMIX, AX_SYNC_FLAG_COPYMXRCTRL, _AXPB::mix, _AXPB::mixerCtrl, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync, _AXPBMIX::vAuxAL, _AXPBMIX::vAuxAR, _AXPBMIX::vAuxAS, _AXPBMIX::vAuxBL, _AXPBMIX::vAuxBR, _AXPBMIX::vAuxBS, _AXPBMIX::vDeltaAuxAL, _AXPBMIX::vDeltaAuxAR, _AXPBMIX::vDeltaAuxAS, _AXPBMIX::vDeltaAuxBL, _AXPBMIX::vDeltaAuxBR, _AXPBMIX::vDeltaAuxBS, _AXPBMIX::vDeltaL, _AXPBMIX::vDeltaR, _AXPBMIX::vDeltaS, _AXPBMIX::vS.
void AXSetVoiceItdOn(AXVPB *p)
References AX_SYNC_FLAG_COPYITD, AX_SYNC_FLAG_COPYTSHIFT, _AXPBITD::flag, _AXPB::itd, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPBITD::shiftL, _AXPBITD::shiftR, _AXVPB::sync, _AXPBITD::targetShiftL, _AXPBITD::targetShiftR.
void AXSetVoiceItdTarget(AXVPB *p, u16 lShift, u16 rShift)
References AX_SYNC_FLAG_COPYTSHIFT, _AXPB::itd, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPBITD::targetShiftL, _AXPBITD::targetShiftR.
void AXSetVoiceUpdateIncrement(AXVPB *p)
References AX_SYNC_FLAG_COPYUPDATE, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::sync, _AXVPB::updateMS.
void AXSetVoiceUpdateWrite(AXVPB *p, u16 param, u16 data)
References AX_SYNC_FLAG_COPYUPDATE, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::sync, _AXVPB::updateCounter, _AXVPB::updateWrite.
void AXSetVoiceDpop(AXVPB *p, AXPBDPOP *dpop)
References AX_SYNC_FLAG_COPYDPOP, _AXPB::dpop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetVoiceVe(AXVPB *p, AXPBVE *ve)
References AX_SYNC_FLAG_COPYVOL, _AXPBVE::currentDelta, _AXPBVE::currentVolume, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPB::ve.
void AXSetVoiceVeDelta(AXVPB *p, s16 delta)
References AX_SYNC_FLAG_SWAPVOL, _AXPBVE::currentDelta, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPB::ve.
void AXSetVoiceFir(AXVPB *p, AXPBFIR *fir)
References AX_SYNC_FLAG_COPYFIR, _AXPBFIR::coefsHi, _AXPBFIR::coefsLo, _AXPB::fir, _AXPBFIR::numCoefs, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceAddr(AXVPB *p, AXPBADDR *addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYADDR, AX_SYNC_FLAG_COPYADPCM, AX_SYNC_FLAG_COPYCURADDR, AX_SYNC_FLAG_COPYENDADDR, AX_SYNC_FLAG_COPYLOOP, AX_SYNC_FLAG_COPYLOOPADDR, _AXPBADDR::currentAddressLo, _AXPBADDR::endAddressLo, _AXPBADDR::format, _AXPBADDR::loopAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetVoiceLoop(AXVPB *p, u16 loop)
References _AXPB::addr, AX_SYNC_FLAG_COPYLOOP, _AXPBADDR::loopFlag, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceLoopAddr(AXVPB *p, u32 addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYLOOPADDR, _AXPBADDR::loopAddressHi, _AXPBADDR::loopAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceEndAddr(AXVPB *p, u32 addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYENDADDR, _AXPBADDR::endAddressHi, _AXPBADDR::endAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceCurrentAddr(AXVPB *p, u32 addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYCURADDR, _AXPBADDR::currentAddressHi, _AXPBADDR::currentAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceAdpcm(AXVPB *p, AXPBADPCM *adpcm)
References _AXPB::adpcm, AX_SYNC_FLAG_COPYADPCM, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetVoiceSrc(AXVPB *p, AXPBSRC *src_)
References AX_SYNC_FLAG_COPYRATIO, AX_SYNC_FLAG_COPYSRC, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::src, src, _AXVPB::sync.
void AXSetVoiceSrcRatio(AXVPB *p, float ratio)
References AX_SYNC_FLAG_COPYRATIO, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPBSRC::ratioLo, _AXPB::src, _AXVPB::sync.
void AXSetVoiceAdpcmLoop(AXVPB *p, AXPBADPCMLOOP *adpcmloop)
References _AXPB::adpcmLoop, AX_SYNC_FLAG_COPYADPCMLOOP, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetMaxDspCycles(u32 cycles)
References __AXMaxDspCycles.
u32 AXGetMaxDspCycles(void)
References __AXMaxDspCycles.
u32 AXGetDspCycles(void)
References __AXRecDspCycles.