AXPrivate.h
u32 __AXClMode
Referenced by __AXClInit, __AXNextFrame, __AXProcessAux, AXGetMode, AXSetMode, AXSetVoiceMix.
AXVPB * __AXGetStackHead(u32 priority)
References __AXStackHead, AX_PRIORITY_STACKS.
Referenced by __AXSyncPBs.
void __AXServiceCallbackStack(void)
References __AXPopCallbackStack, __AXPushFreeStack, __AXRemoveFromStack, _AXVPB::callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __AXOutNewFrame.
void __AXInitVoiceStacks(void)
References __AXCallbackStack, __AXStackHead, __AXStackTail, AX_PRIORITY_STACKS, NULL.
Referenced by __AXAllocInit, __AXAllocQuit.
void __AXAllocInit(void)
References __AXInitVoiceStacks, OSReport.
Referenced by AXInit.
void __AXAllocQuit(void)
References __AXInitVoiceStacks, OSReport.
Referenced by AXQuit.
void __AXPushFreeStack(AXVPB *p)
References __AXStackHead, _AXVPB::next.
Referenced by __AXServiceCallbackStack, __AXVPBInit, AXFreeVoice.
AXVPB * __AXPopFreeStack(void)
References __AXStackHead, _AXVPB::next.
Referenced by AXAcquireVoice.
void __AXPushCallbackStack(AXVPB *p)
References __AXCallbackStack, _AXVPB::next1.
Referenced by __AXDumpVPB.
AXVPB * __AXPopCallbackStack(void)
References __AXCallbackStack, _AXVPB::next1.
Referenced by __AXServiceCallbackStack.
void __AXRemoveFromStack(AXVPB *p)
References __AXStackHead, __AXStackTail, _AXVPB::next, _AXVPB::prev, _AXVPB::priority.
Referenced by __AXServiceCallbackStack, AXFreeVoice, AXSetVoicePriority.
void __AXPushStackHead(AXVPB *p, u32 priority)
References __AXStackHead, __AXStackTail, AX_PRIORITY_STACKS, _AXVPB::next, _AXVPB::prev, _AXVPB::priority.
Referenced by AXAcquireVoice, AXSetVoicePriority.
AXVPB * __AXPopStackFromBottom(u32 priority)
References __AXStackHead, __AXStackTail, AX_PRIORITY_STACKS, _AXVPB::next, NULL, _AXVPB::prev.
Referenced by AXAcquireVoice.
void __AXAuxInit(void)
References __AXAuxCpuReadWritePosition, __AXAuxDspReadPosition, __AXAuxDspWritePosition, __AXCallbackAuxA, __AXCallbackAuxB, __AXContextAuxA, __AXContextAuxB, NULL, OSReport.
Referenced by AXInit.
void __AXAuxQuit(void)
References __AXCallbackAuxA, __AXCallbackAuxB, NULL, OSReport.
Referenced by AXQuit.
void __AXGetAuxAInput(u32 *p)
References __AXAuxDspWritePosition.
Referenced by __AXNextFrame.
void __AXGetAuxAOutput(u32 *p)
References __AXAuxDspReadPosition.
Referenced by __AXNextFrame.
void __AXGetAuxBInput(u32 *p)
References __AXAuxDspWritePosition.
Referenced by __AXNextFrame.
void __AXGetAuxBOutput(u32 *p)
References __AXAuxDspReadPosition.
Referenced by __AXNextFrame.
void __AXProcessAux(void)
References __AXAuxADspRead, __AXAuxADspWrite, __AXAuxBDspRead, __AXAuxBDspWrite, __AXAuxCpuReadWritePosition, __AXAuxDspReadPosition, __AXAuxDspWritePosition, __AXCallbackAuxA, __AXCallbackAuxB, __AXClMode, __AXContextAuxA, __AXContextAuxB, DCFlushRangeNoSync, DCInvalidateRange, AX_AUX_DATA::l, AX_AUX_DATA::r, AX_AUX_DATA::s.
Referenced by __AXOutNewFrame.
u32 __AXGetCommandListCycles(void)
References __AXCommandListCycles.
Referenced by __AXSyncPBs.
u32 __AXGetCommandListAddress(void)
References __AXClWrite, __AXCommandList, __AXCommandListPosition.
Referenced by __AXOutNewFrame.
void __AXWriteToCommandList(u16 data)
References __AXClWrite.
Referenced by __AXNextFrame.
void __AXNextFrame(void *sbuffer, void *buffer)
References __AXClMode, __AXClWrite, __AXCommandListCycles, __AXGetAuxAInput, __AXGetAuxAOutput, __AXGetAuxBInput, __AXGetAuxBOutput, __AXGetPBs, __AXGetStudio, __AXHRTFHistory, __AXWriteToCommandList, buffer, DCFlushRange.
Referenced by __AXOutInit, __AXOutNewFrame.
void __AXClInit(void)
References __AXClMode, __AXClWrite, __AXCommandList, __AXCommandListPosition, OSReport.
Referenced by AXInit.
void __AXClQuit(void)
References OSReport.
Referenced by AXQuit.
void __AXOutNewFrame(u32 lessDspCycles)
References __AXGetCommandListAddress, __AXGetCurrentProfile, __AXGetNumVoices, __AXLocalProfile, __AXNextFrame, __AXOutBuffer, __AXOutFrame, __AXOutSBuffer, __AXPrintStudio, __AXProcessAux, __AXServiceCallbackStack, __AXSyncPBs, __AXUserFrameCallback, AIInitDMA, _AXPROFILE::auxProcessingEnd, _AXPROFILE::auxProcessingStart, _AXPROFILE::axFrameEnd, _AXPROFILE::axFrameStart, _AXPROFILE::axNumVoices, DSPCheckMailToDSP, DSPSendMailToDSP, OSEnableInterrupts, OSGetTime, OSRestoreInterrupts, profile, _AXPROFILE::userCallbackEnd, _AXPROFILE::userCallbackStart.
Referenced by __AXDSPResumeCallback, __AXOutAiCallback.
void __AXOutAiCallback(void)
References __AXOsTime, __AXOutDspReady, __AXOutNewFrame, DSPAssertTask, OSGetTime, task.
Referenced by __AXOutInit.
void __AXOutInitDSP(void)
References __AXDSPDoneCallback, __AXDSPDoneFlag, __AXDSPInitCallback, __AXDSPInitFlag, __AXDSPResumeCallback, ax_dram_image, axDspSlave, axDspSlaveLength, STRUCT_DSP_TASK::done_cb, STRUCT_DSP_TASK::dram_addr, STRUCT_DSP_TASK::dram_length, STRUCT_DSP_TASK::dram_mmem_addr, STRUCT_DSP_TASK::dsp_init_vector, STRUCT_DSP_TASK::dsp_resume_vector, DSPAddTask, DSPCheckInit, DSPInit, STRUCT_DSP_TASK::init_cb, STRUCT_DSP_TASK::iram_addr, STRUCT_DSP_TASK::iram_length, STRUCT_DSP_TASK::iram_mmem_addr, NULL, STRUCT_DSP_TASK::priority, STRUCT_DSP_TASK::req_cb, STRUCT_DSP_TASK::res_cb, task.
Referenced by __AXOutInit.
void __AXOutInit(void)
References __AXNextFrame, __AXOutAiCallback, __AXOutBuffer, __AXOutDspReady, __AXOutFrame, __AXOutInitDSP, __AXOutSBuffer, __AXUserFrameCallback, AIInitDMA, AIRegisterDMACallback, AIStartDMA, DCFlushRange, NULL, OSReport.
Referenced by AXInit.
void __AXOutQuit(void)
References __AXUserFrameCallback, AIStopDMA, DSPGetDMAStatus, DSPHalt, DSPReset, NULL, OSDisableInterrupts, OSReport, OSRestoreInterrupts.
Referenced by AXQuit.
AXPROFILE * __AXGetCurrentProfile(void)
References __AXCurrentProfile, __AXMaxProfiles, __AXProfile, __AXProfileInitialized, profile.
Referenced by __AXOutNewFrame.
u32 __AXGetStudio(void)
Referenced by __AXNextFrame.
void __AXDepopFade(s32 *hostSum, long *dspVolume, s16 *dspDelta)
Referenced by __AXPrintStudio.
void __AXPrintStudio(void)
References __AXDepopFade, __AXSpbAAL, __AXSpbAAR, __AXSpbAAS, __AXSpbABL, __AXSpbABR, __AXSpbABS, __AXSpbAL, __AXSpbAR, __AXSpbAS, DCFlushRange.
Referenced by __AXOutNewFrame.
void __AXSPBInit(void)
References __AXSpbAAL, __AXSpbAAR, __AXSpbAAS, __AXSpbABL, __AXSpbABR, __AXSpbABS, __AXSpbAL, __AXSpbAR, __AXSpbAS, OSReport.
Referenced by AXInit.
void __AXSPBQuit(void)
References OSReport.
Referenced by AXQuit.
void __AXDepopVoice(AXPB *p)
References __AXSpbAAL, __AXSpbAAR, __AXSpbAAS, __AXSpbABL, __AXSpbABR, __AXSpbABS, __AXSpbAL, __AXSpbAR, __AXSpbAS, _AXPBDPOP::aAuxAL, _AXPBDPOP::aAuxAR, _AXPBDPOP::aAuxAS, _AXPBDPOP::aAuxBL, _AXPBDPOP::aAuxBR, _AXPBDPOP::aAuxBS, _AXPBDPOP::aL, _AXPBDPOP::aR, _AXPBDPOP::aS, _AXPB::dpop.
Referenced by __AXDumpVPB, __AXSyncPBs.
u32 __AXGetNumVoices(void)
References __AXNumVoices.
Referenced by __AXOutNewFrame.
void __AXServiceVPB(AXVPB *pvpb)
References __AXNumVoices, _AXPB::addr, _AXPB::adpcm, _AXPB::adpcmLoop, AX_MAX_VOICES, AX_SYNC_FLAG_COPYADDR, AX_SYNC_FLAG_COPYADPCM, AX_SYNC_FLAG_COPYADPCMLOOP, AX_SYNC_FLAG_COPYALL, AX_SYNC_FLAG_COPYAXPBMIX, AX_SYNC_FLAG_COPYCURADDR, AX_SYNC_FLAG_COPYDPOP, AX_SYNC_FLAG_COPYENDADDR, AX_SYNC_FLAG_COPYFIR, AX_SYNC_FLAG_COPYITD, AX_SYNC_FLAG_COPYLOOP, AX_SYNC_FLAG_COPYLOOPADDR, AX_SYNC_FLAG_COPYMXRCTRL, AX_SYNC_FLAG_COPYRATIO, AX_SYNC_FLAG_COPYSELECT, AX_SYNC_FLAG_COPYSRC, AX_SYNC_FLAG_COPYSTATE, AX_SYNC_FLAG_COPYTSHIFT, AX_SYNC_FLAG_COPYTYPE, AX_SYNC_FLAG_COPYUPDATE, AX_SYNC_FLAG_COPYVOL, AX_SYNC_FLAG_SWAPVOL, _AXPB::coefSelect, _AXPBADDR::currentAddressHi, _AXPBADDR::currentAddressLo, _AXPBVE::currentDelta, _AXPBVE::currentVolume, _AXPB::dpop, _AXPBADDR::endAddressHi, _AXPB::fir, _AXVPB::index, _AXPB::itd, _AXVPB::itdBuffer, _AXPBADDR::loopAddressHi, _AXPBADDR::loopFlag, _AXPB::mix, _AXPB::mixerCtrl, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPBSRC::ratioLo, _AXPB::src, src, _AXPB::srcSelect, _AXPB::state, _AXVPB::sync, sync, _AXPBITD::targetShiftL, _AXPBITD::targetShiftR, _AXPB::type, _AXPB::update, _AXVPB::updateCounter, _AXVPB::updateData, _AXPB::ve.
Referenced by __AXSyncPBs.
void __AXDumpVPB(AXVPB *pvpb)
References __AXDepopVoice, __AXPushCallbackStack, _AXVPB::index, _AXVPB::pb, _AXPB::state, _AXPB::update, _AXPBUPDATE::updNum.
Referenced by __AXSyncPBs.
void __AXSyncPBs(u32 lessDspCycles)
References __AXDepopVoice, __AXDumpVPB, __AXGetCommandListCycles, __AXGetStackHead, __AXMaxDspCycles, __AXMixCycles, __AXNumVoices, __AXRecDspCycles, __AXServiceVPB, __AXSrcCycles, DCFlushRange, DCInvalidateRange, _AXVPB::depop, _AXVPB::index, _AXPB::mixerCtrl, _AXVPB::next, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPB::src, _AXPB::state, _AXVPB::sync, _AXVPB::updateCounter, _AXVPB::updateData, _AXVPB::updateMS, _AXVPB::updateWrite.
Referenced by __AXOutNewFrame.
AXPB * __AXGetPBs(void)
Referenced by __AXNextFrame.
void __AXSetPBDefault(AXVPB *p)
References _AXPBITD::flag, _AXPB::itd, _AXVPB::pb, _AXPB::state, _AXVPB::sync, _AXPB::update, _AXVPB::updateCounter, _AXVPB::updateData, _AXVPB::updateMS, _AXVPB::updateWrite, _AXPBUPDATE::updNum.
Referenced by __AXVPBInit, AXAcquireVoice, AXFreeVoice.
void __AXVPBInit(void)
References __AXMaxDspCycles, __AXPushFreeStack, __AXRecDspCycles, __AXSetPBDefault, __AXVPB, AX_MAX_VOICES, _AXPBITD::bufferHi, _AXPBITD::bufferLo, _AXPB::currHi, _AXPB::currLo, _AXPBUPDATE::dataHi, _AXPBUPDATE::dataLo, DCFlushRange, _AXVPB::index, _AXPB::itd, _AXVPB::itdBuffer, _AXPB::nextHi, _AXPB::nextLo, OS_BUS_CLOCK, OSReport, _AXVPB::pb, _AXPB::update, _AXVPB::updateData, _AXVPB::updateWrite.
Referenced by AXInit.
void __AXVPBQuit(void)
References OSReport.
Referenced by AXQuit.