AXAlloc.c
AXVPB* __AXStackHead[AX_PRIORITY_STACKS][AX_PRIORITY_STACKS]
Referenced by __AXGetStackHead, __AXInitVoiceStacks, __AXPopFreeStack, __AXPopStackFromBottom, __AXPushFreeStack, __AXPushStackHead, __AXRemoveFromStack.
AXVPB* __AXStackTail[AX_PRIORITY_STACKS][AX_PRIORITY_STACKS]
Referenced by __AXInitVoiceStacks, __AXPopStackFromBottom, __AXPushStackHead, __AXRemoveFromStack.
AXVPB* __AXCallbackStack
Referenced by __AXInitVoiceStacks, __AXPopCallbackStack, __AXPushCallbackStack.
AXVPB * __AXGetStackHead(u32 priority)
References __AXStackHead, AX_PRIORITY_STACKS.
Referenced by __AXSyncPBs.
void __AXServiceCallbackStack(void)
References __AXPopCallbackStack, __AXPushFreeStack, __AXRemoveFromStack, _AXVPB::callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __AXOutNewFrame.
void __AXInitVoiceStacks(void)
References __AXCallbackStack, __AXStackHead, __AXStackTail, AX_PRIORITY_STACKS, NULL.
Referenced by __AXAllocInit, __AXAllocQuit.
void __AXAllocInit(void)
References __AXInitVoiceStacks, OSReport.
Referenced by AXInit.
void __AXAllocQuit(void)
References __AXInitVoiceStacks, OSReport.
Referenced by AXQuit.
void __AXPushFreeStack(AXVPB *p)
References __AXStackHead, _AXVPB::next.
Referenced by __AXServiceCallbackStack, __AXVPBInit, AXFreeVoice.
AXVPB * __AXPopFreeStack(void)
References __AXStackHead, _AXVPB::next.
Referenced by AXAcquireVoice.
void __AXPushCallbackStack(AXVPB *p)
References __AXCallbackStack, _AXVPB::next1.
Referenced by __AXDumpVPB.
AXVPB * __AXPopCallbackStack(void)
References __AXCallbackStack, _AXVPB::next1.
Referenced by __AXServiceCallbackStack.
void __AXRemoveFromStack(AXVPB *p)
References __AXStackHead, __AXStackTail, _AXVPB::next, _AXVPB::prev, _AXVPB::priority.
Referenced by __AXServiceCallbackStack, AXFreeVoice, AXSetVoicePriority.
void __AXPushStackHead(AXVPB *p, u32 priority)
References __AXStackHead, __AXStackTail, AX_PRIORITY_STACKS, _AXVPB::next, _AXVPB::prev, _AXVPB::priority.
Referenced by AXAcquireVoice, AXSetVoicePriority.
AXVPB * __AXPopStackFromBottom(u32 priority)
References __AXStackHead, __AXStackTail, AX_PRIORITY_STACKS, _AXVPB::next, NULL, _AXVPB::prev.
Referenced by AXAcquireVoice.
void AXFreeVoice(AXVPB *p)
References __AXPushFreeStack, __AXRemoveFromStack, __AXSetPBDefault, _AXVPB::depop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::state.
Referenced by __SYNNoteOn, __SYNServiceVoice, SYNQuitSynth.
AXVPB * AXAcquireVoice(u32 priority, void(*callback)(void *), u32 userContext)
References __AXPopFreeStack, __AXPopStackFromBottom, __AXPushStackHead, __AXSetPBDefault, AX_PRIORITY_STACKS, _AXVPB::callback, _AXVPB::depop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::state, _AXVPB::userContext.
Referenced by __SYNNoteOn.
void AXSetVoicePriority(AXVPB *p, u32 priority)
References __AXPushStackHead, __AXRemoveFromStack, AX_PRIORITY_STACKS, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __SYNNoteOn, __SYNSetVoiceToRelease.