AXOut.c
s16 __AXOutBuffer[2][320][2][320]
Referenced by __AXOutInit, __AXOutNewFrame.
s32 __AXOutSBuffer[160][160]
Referenced by __AXOutInit, __AXOutNewFrame.
AXPROFILE __AXLocalProfile
Referenced by __AXOutNewFrame.
DSPTaskInfo task
Referenced by __ARQPushTempQueue, __AXOutAiCallback, __AXOutInitDSP, __CARDUnlock, __DSP_add_task, __DSP_boot_task, __DSP_insert_task, __DSP_remove_task, DoneCallback, DSPAddTask, DSPAssertTask, DSPCancelTask, InitCallback.
u16 ax_dram_image[8192][8192]
Referenced by __AXOutInitDSP.
volatile u32 __AXOutFrame
Referenced by __AXOutInit, __AXOutNewFrame.
volatile u32 __AXOutDspReady
Referenced by __AXDSPResumeCallback, __AXOutAiCallback, __AXOutInit.
volatile s64 __AXOsTime
Referenced by __AXDSPResumeCallback, __AXOutAiCallback.
void(* __AXUserFrameCallback) ())()
Referenced by __AXOutInit, __AXOutNewFrame, __AXOutQuit, AXRegisterCallback.
volatile int __AXDSPInitFlag
Referenced by __AXDSPInitCallback, __AXOutInitDSP.
int __AXDSPDoneFlag
Referenced by __AXDSPDoneCallback, __AXOutInitDSP.
static void __AXDSPInitCallback(void *task)
References __AXDSPInitFlag.
Referenced by __AXOutInitDSP.
static void __AXDSPResumeCallback(void *task)
References __AXOsTime, __AXOutDspReady, __AXOutNewFrame, OSGetTime.
Referenced by __AXOutInitDSP.
static void __AXDSPDoneCallback(void *task)
References __AXDSPDoneFlag.
Referenced by __AXOutInitDSP.
void __AXOutNewFrame(u32 lessDspCycles)
References __AXGetCommandListAddress, __AXGetCurrentProfile, __AXGetNumVoices, __AXLocalProfile, __AXNextFrame, __AXOutBuffer, __AXOutFrame, __AXOutSBuffer, __AXPrintStudio, __AXProcessAux, __AXServiceCallbackStack, __AXSyncPBs, __AXUserFrameCallback, AIInitDMA, _AXPROFILE::auxProcessingEnd, _AXPROFILE::auxProcessingStart, _AXPROFILE::axFrameEnd, _AXPROFILE::axFrameStart, _AXPROFILE::axNumVoices, DSPCheckMailToDSP, DSPSendMailToDSP, OSEnableInterrupts, OSGetTime, OSRestoreInterrupts, profile, _AXPROFILE::userCallbackEnd, _AXPROFILE::userCallbackStart.
Referenced by __AXDSPResumeCallback, __AXOutAiCallback.
void __AXOutAiCallback(void)
References __AXOsTime, __AXOutDspReady, __AXOutNewFrame, DSPAssertTask, OSGetTime, task.
Referenced by __AXOutInit.
void __AXOutInitDSP(void)
References __AXDSPDoneCallback, __AXDSPDoneFlag, __AXDSPInitCallback, __AXDSPInitFlag, __AXDSPResumeCallback, ax_dram_image, axDspSlave, axDspSlaveLength, STRUCT_DSP_TASK::done_cb, STRUCT_DSP_TASK::dram_addr, STRUCT_DSP_TASK::dram_length, STRUCT_DSP_TASK::dram_mmem_addr, STRUCT_DSP_TASK::dsp_init_vector, STRUCT_DSP_TASK::dsp_resume_vector, DSPAddTask, DSPCheckInit, DSPInit, STRUCT_DSP_TASK::init_cb, STRUCT_DSP_TASK::iram_addr, STRUCT_DSP_TASK::iram_length, STRUCT_DSP_TASK::iram_mmem_addr, NULL, STRUCT_DSP_TASK::priority, STRUCT_DSP_TASK::req_cb, STRUCT_DSP_TASK::res_cb, task.
Referenced by __AXOutInit.
void __AXOutInit(void)
References __AXNextFrame, __AXOutAiCallback, __AXOutBuffer, __AXOutDspReady, __AXOutFrame, __AXOutInitDSP, __AXOutSBuffer, __AXUserFrameCallback, AIInitDMA, AIRegisterDMACallback, AIStartDMA, DCFlushRange, NULL, OSReport.
Referenced by AXInit.
void __AXOutQuit(void)
References __AXUserFrameCallback, AIStopDMA, DSPGetDMAStatus, DSPHalt, DSPReset, NULL, OSDisableInterrupts, OSReport, OSRestoreInterrupts.
Referenced by AXQuit.
void AXRegisterCallback(void(*callback)())
References __AXUserFrameCallback.