CARDOpen.c
BOOL __CARDCompareFileName(CARDDir *ent, const char *fileName)
References CARD_FILENAME_MAX, CARD_MAX_MOUNT_STEP, FALSE, TRUE.
Referenced by __CARDGetFileNo, CARDCreateAsync, CARDRenameAsync.
s32 __CARDAccess(CARDDir *ent)
References __CARDDiskID, __CARDDiskNone, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOFILE, CARD_RESULT_NOPERM, CARD_RESULT_READY, DVDDiskID::company, DVDDiskID::gameName.
Referenced by __CARDGetFileNo, __CARDGetStatusEx, __CARDSetStatusExAsync, CARDFastDeleteAsync, CARDFastOpen, CARDGetStatus, CARDReadAsync, CARDRenameAsync, CARDSetStatusAsync, CARDWriteAsync.
s32 __CARDIsPublic(CARDDir *ent)
References CARD_ATTR_PUBLIC, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOFILE, CARD_RESULT_NOPERM.
Referenced by __CARDGetStatusEx, CARDFastOpen, CARDGetStatus, CARDReadAsync.
s32 __CARDGetFileNo(CARDControl *card, const char *fileName, s32 *pfileNo)
References __CARDAccess, __CARDCompareFileName, __CARDGetDirBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_NOFILE, CARD_RESULT_READY.
Referenced by CARDDeleteAsync, CARDOpen.
s32 CARDFastOpen(s32 chan, s32 fileNo, CARDFileInfo *fileInfo)
References __CARDAccess, __CARDGetControlBlock, __CARDGetDirBlock, __CARDIsPublic, __CARDPutControlBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOPERM, CARDIsValidBlockNo, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::offset.
s32 CARDOpen(s32 chan, char *fileName, CARDFileInfo *fileInfo)
References __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFileNo, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARDIsValidBlockNo, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::offset.
s32 CARDClose(CARDFileInfo *fileInfo)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_READY, CARDFileInfo::chan, CARDFileInfo::fileNo.
BOOL __CARDIsOpened(CARDControl *card, s32 fileNo)
References FALSE.
Referenced by CARDDeleteAsync, CARDFastDeleteAsync.