CARDWrite.c
OFFSET
static void WriteCallback(s32 chan, long result)
References __CARDBlock, __CARDEraseSector, __CARDGetDirBlock, __CARDGetFatBlock, __CARDPutControlBlock, __CARDUpdateDir, __OSBusClock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_CANCELED, CARDFileInfo::chan, EraseCallback, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::length, NULL, CARDFileInfo::offset, OSGetTime.
Referenced by EraseCallback.
static void EraseCallback(s32 chan, long result)
References __CARDBlock, __CARDPutControlBlock, __CARDWrite, CARD_MAX_MOUNT_STEP, CARDFileInfo::chan, CARDFileInfo::iBlock, NULL, CARDFileInfo::offset, OFFSET, WriteCallback.
Referenced by CARDWriteAsync, WriteCallback.
s32 CARDWriteAsync(struct CARDFileInfo *fileInfo, void *buf, s32 length, long offset, void(*callback)(long, long))
References __CARDAccess, __CARDDefaultApiCallback, __CARDEraseSector, __CARDGetDirBlock, __CARDPutControlBlock, __CARDSeek, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARDFileInfo::chan, DCStoreRange, EraseCallback, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDDir::length, OFFSET, CARDControl::result.
Referenced by CARDWrite.
s32 CARDWrite(struct CARDFileInfo *fileInfo, void *buf, s32 length, long offset)
References __CARDSync, __CARDSyncCallback, CARD_MAX_MOUNT_STEP, CARDWriteAsync, CARDFileInfo::chan, CARDDir::length.