CARDCheck.c
static s32 VerifyID(CARDControl *card)
References __CARDBlock, __CARDCheckSum, __OSLockSramEx, __OSUnlockSramEx, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_ENCODING, CARD_RESULT_READY, CARDID::checkSum, CARDID::checkSumInv, CARDID::deviceID, CARDID::encode, FALSE, OSGetFontEncode, CARDID::serial, CARDID::size.
Referenced by __CARDVerify, CARDCheckExAsync.
static s32 VerifyDir(CARDControl *card, int *outCurrent)
References __CARDCheckSum, CARD_MAX_MOUNT_STEP, CARD_SYSTEM_BLOCK_SIZE, CARDGetDirCheck.
Referenced by __CARDVerify, CARDCheckExAsync.
static s32 VerifyFAT(CARDControl *card, int *outCurrent)
References __CARDCheckSum, CARD_FAT_AVAIL, CARD_FAT_CHECKCODE, CARD_FAT_CHECKSUM, CARD_FAT_CHECKSUMINV, CARD_FAT_FREEBLOCKS, CARD_MAX_MOUNT_STEP, CARD_NUM_SYSTEM_BLOCK, CARD_SYSTEM_BLOCK_SIZE.
Referenced by __CARDVerify, CARDCheckExAsync.
void __CARDCheckSum(void *ptr, int length, u16 *checksum, u16 *checksumInv)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDUpdateDir, __CARDUpdateFatBlock, CARDCheckExAsync, CARDFormatAsync, VerifyDir, VerifyFAT, VerifyID.
s32 __CARDVerify(CARDControl *card)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_READY, NULL, VerifyDir, VerifyFAT, VerifyID.
Referenced by __CARDMountCallback.
s32 CARDCheckExAsync(s32 chan, s32 *xferBytes, CARDCallback callback)
References __CARDCheckSum, __CARDGetControlBlock, __CARDPutControlBlock, __CARDUpdateDir, __CARDUpdateFatBlock, CARD_FAT_AVAIL, CARD_FAT_CHECKCODE, CARD_FAT_CHECKSUM, CARD_FAT_CHECKSUMINV, CARD_FAT_FREEBLOCKS, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_NUM_SYSTEM_BLOCK, CARD_RESULT_BROKEN, CARD_RESULT_READY, CARD_SYSTEM_BLOCK_SIZE, CARDIsValidBlockNo, FALSE, OSDisableInterrupts, OSRestoreInterrupts, TRUE, VerifyDir, VerifyFAT, VerifyID.
Referenced by CARDCheckAsync, CARDCheckEx.
s32 CARDCheckAsync(s32 chan, CARDCallback callback)
References CARD_MAX_MOUNT_STEP, CARDCheckExAsync.
s32 CARDCheckEx(s32 chan, s32 *xferBytes)
References __CARDSync, __CARDSyncCallback, CARD_MAX_MOUNT_STEP, CARDCheckExAsync.
Referenced by CARDCheck.
s32 CARDCheck(s32 chan)
References CARD_MAX_MOUNT_STEP, CARDCheckEx.