CARDUnlock.c
SEC_AD1
SEC_AD2
SEC_AD3
SEC_BA
static u8 CardData[352] ALIGN(32)
static u32 exnor_1st(u32 data, u32 rshift)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDUnlock.
static u32 exnor(u32 data, u32 lshift)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDUnlock, DoneCallback.
static u32 bitrev(u32 data)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDUnlock.
static s32 ReadArrayUnlock(s32 chan, u32 data, void *rbuf, s32 rlen, s32 mode)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImmEx, EXISelect, FALSE, SEC_AD1, SEC_AD2, SEC_AD3, SEC_BA.
Referenced by __CARDUnlock, DoneCallback.
static u32 GetInitVal(void)
References CARD_MAX_MOUNT_STEP, OSGetTick, tmp.
Referenced by __CARDUnlock.
static s32 DummyLen(void)
References CARD_MAX_MOUNT_STEP, OSGetTick, tmp.
Referenced by __CARDUnlock, DoneCallback.
static void InitCallback(void *_task)
References __CARDBlock, CARD_MAX_MOUNT_STEP, DSPCheckMailToDSP, DSPSendMailToDSP, task.
Referenced by __CARDUnlock.
static void DoneCallback(void *_task)
References __CARDBlock, __CARDMountCallback, __CARDReadStatus, CARD_MAX_MOUNT_STEP, CARD_RESULT_IOERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, DummyLen, EXIProbe, EXIUnlock, exnor, OSRoundUp32B, ReadArrayUnlock, task.
Referenced by __CARDUnlock.
s32 __CARDUnlock(s32 chan, u8 flashID[12])
References __CARDBlock, bitrev, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, DCFlushRange, DCInvalidateRange, STRUCT_DSP_TASK::done_cb, DoneCallback, STRUCT_DSP_TASK::dsp_init_vector, DSPAddTask, DummyLen, exnor, exnor_1st, GetInitVal, STRUCT_DSP_TASK::init_cb, InitCallback, STRUCT_DSP_TASK::iram_addr, STRUCT_DSP_TASK::iram_length, STRUCT_DSP_TASK::iram_mmem_addr, NULL, OSCachedToPhysical, OSRoundUp32B, STRUCT_DSP_TASK::priority, ReadArrayUnlock, STRUCT_DSP_TASK::req_cb, STRUCT_DSP_TASK::res_cb, task.
Referenced by DoMount.