CARDDelete.c
static void DeleteCallback(s32 chan, s32 result)
References __CARDBlock, __CARDFreeBlock, __CARDPutControlBlock, CARDControl::apiCallback, CARD_MAX_MOUNT_STEP, NULL.
Referenced by CARDDeleteAsync, CARDFastDeleteAsync.
s32 CARDFastDeleteAsync(s32 chan, s32 fileNo, CARDCallback callback)
References __CARDAccess, __CARDDefaultApiCallback, __CARDGetControlBlock, __CARDGetDirBlock, __CARDIsOpened, __CARDPutControlBlock, __CARDUpdateDir, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, DeleteCallback.
Referenced by CARDFastDelete.
s32 CARDFastDelete(s32 chan, long fileNo)
References __CARDSync, __CARDSyncCallback, CARDFastDeleteAsync.
s32 CARDDeleteAsync(s32 chan, char *fileName, CARDCallback callback)
References __CARDDefaultApiCallback, __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFileNo, __CARDIsOpened, __CARDPutControlBlock, __CARDUpdateDir, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, DeleteCallback.
Referenced by CARDDelete.
s32 CARDDelete(s32 chan, char *fileName)
References __CARDSync, __CARDSyncCallback, CARDDeleteAsync.