CARDPrivate.h
CARD_PAGE_SIZE
CARD_SEG_SIZE
CARD_MAX_SIZE
CARD_NUM_SYSTEM_BLOCK
CARD_SYSTEM_BLOCK_SIZE
CARD_MAX_MOUNT_STEP
CARD_CUSTOM_ID
CARD_CUSTOM_ID_MASK
CARD_ID_SIZE
CARD_ID_CHIPS
CARD_ID_LATENCY
CARD_ID_LATENCY_SHIFT
CARD_ID_SECTOR
CARD_ID_SECTOR_SHIFT
CARD_CMD_CUSTOM_ID
CARD_CMD_INT_ENABLE
CARD_CMD_INT_DISABLE
CARD_CMD_CLEAR_STATUS
CARD_CMD_READ_STATUS
CARD_CMD_VENDOR_ID
CARD_CMD_READ
CARD_CMD_WRITE
CARD_CMD_ERASE
CARD_CMD_ERASE_SECTOR
CARD_CMD_WAKEUP
CARD_CMD_SLEEP
CARD_STS_COMPLETE
CARD_STS_SECURITY_PASS
CARD_STS_SLEEPING
CARD_STS_ERASE_FAIL
CARD_STS_PROGRAM_FAIL
CARD_STS_NA_FAIL
CARD_STS_INT_ENABLE
CARD_STS_READY
CARD_FAT_AVAIL
CARD_FAT_VOID
CARD_FAT_EOF
CARD_FAT_CHECKSUM
CARD_FAT_CHECKSUMINV
CARD_FAT_CHECKCODE
CARD_FAT_FREEBLOCKS
CARD_FAT_LASTSLOT
CARD_VENDOR_SAMSUNG
CARDIsValidBlockNo
CARDGetDirCheck
typedef struct CARDID CARDID
typedef struct CARDDir CARDDir
typedef struct CARDControl CARDControl
typedef struct CARDDecParam CARDDecParam
typedef struct CARDDirCheck CARDDirCheck
struct CARDControl __CARDBlock[2][2]
Referenced by __CARDAllocBlock, __CARDErase, __CARDEraseSector, __CARDExiHandler, __CARDExtHandler, __CARDFreeBlock, __CARDGetControlBlock, __CARDMountCallback, __CARDRead, __CARDReadSegment, __CARDStart, __CARDSync, __CARDSyncCallback, __CARDTxHandler, __CARDUnlock, __CARDUnlockedHandler, __CARDUpdateDir, __CARDUpdateFatBlock, __CARDWrite, __CARDWritePage, BlockReadCallback, BlockWriteCallback, CARDCancel, CARDGetResultCode, CARDGetXferredBytes, CARDInit, CARDMountAsync, CARDProbeEx, CreateCallbackFat, DeleteCallback, DoMount, DoneCallback, DoUnmount, EraseCallback, EraseCallback, EraseCallback, FormatCallback, InitCallback, ReadArrayUnlock, ReadCallback, Retry, TimeoutHandler, UnlockedCallback, VerifyID, WriteCallback, WriteCallback, WriteCallback.
DVDDiskID* __CARDDiskID
Referenced by __CARDAccess, __CARDGetControlBlock, __CARDSetDiskID, CARDCreateAsync, CARDInit, CARDRenameAsync, CreateCallbackFat.
DVDDiskID __CARDDiskNone
Referenced by __CARDAccess, __CARDSetDiskID.
s32 __CARDGetStatusEx(long chan, long fileNo, struct CARDDir *dirent)
s32 __CARDSetStatusExAsync(long chan, long fileNo, struct CARDDir *dirent, void(*callback)(long, long))
s32 __CARDSetStatusEx(long chan, long fileNo, struct CARDDir *dirent)
s32 __CARDUnlock(s32 chan, u8 flashID[12])
References __CARDBlock, bitrev, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, DCFlushRange, DCInvalidateRange, STRUCT_DSP_TASK::done_cb, DoneCallback, STRUCT_DSP_TASK::dsp_init_vector, DSPAddTask, DummyLen, exnor, exnor_1st, GetInitVal, STRUCT_DSP_TASK::init_cb, InitCallback, STRUCT_DSP_TASK::iram_addr, STRUCT_DSP_TASK::iram_length, STRUCT_DSP_TASK::iram_mmem_addr, NULL, OSCachedToPhysical, OSRoundUp32B, STRUCT_DSP_TASK::priority, ReadArrayUnlock, STRUCT_DSP_TASK::req_cb, STRUCT_DSP_TASK::res_cb, task.
Referenced by DoMount.
s32 __CARDSeek(CARDFileInfo *fileInfo, s32 length, s32 offset, CARDControl **pcard)
References __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFatBlock, __CARDPutControlBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_FATAL_ERROR, CARD_RESULT_LIMIT, CARD_RESULT_READY, CARDIsValidBlockNo, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::length, CARDFileInfo::offset, TRUNC.
Referenced by CARDReadAsync, CARDWriteAsync.
s32 __CARDRead(long chan, u32 addr, long length, void *dst, void(*callback)(long, long))
Referenced by __CARDRawReadAsync, CARDReadAsync, DoMount, ReadCallback.
s32 __CARDWrite(long chan, u32 addr, long length, void *dst, void(*callback)(long, long))
Referenced by EraseCallback, EraseCallback, EraseCallback, FormatCallback.
s32 __CARDRawReadAsync(long chan, void *buf, long length, long offset, void(*callback)(long, long))
s32 __CARDRawRead(long chan, void *buf, long length, long offset)
BOOL __CARDCompareFileName(CARDDir *ent, const char *fileName)
References CARD_FILENAME_MAX, CARD_MAX_MOUNT_STEP, FALSE, TRUE.
Referenced by __CARDGetFileNo, CARDCreateAsync, CARDRenameAsync.
s32 __CARDAccess(CARDDir *ent)
References __CARDDiskID, __CARDDiskNone, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOFILE, CARD_RESULT_NOPERM, CARD_RESULT_READY, DVDDiskID::company, DVDDiskID::gameName.
Referenced by __CARDGetFileNo, __CARDGetStatusEx, __CARDSetStatusExAsync, CARDFastDeleteAsync, CARDFastOpen, CARDGetStatus, CARDReadAsync, CARDRenameAsync, CARDSetStatusAsync, CARDWriteAsync.
s32 __CARDIsPublic(CARDDir *ent)
References CARD_ATTR_PUBLIC, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOFILE, CARD_RESULT_NOPERM.
Referenced by __CARDGetStatusEx, CARDFastOpen, CARDGetStatus, CARDReadAsync.
s32 __CARDGetFileNo(CARDControl *card, const char *fileName, s32 *pfileNo)
References __CARDAccess, __CARDCompareFileName, __CARDGetDirBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_NOFILE, CARD_RESULT_READY.
Referenced by CARDDeleteAsync, CARDOpen.
BOOL __CARDIsOpened(CARDControl *card, s32 fileNo)
References FALSE.
Referenced by CARDDeleteAsync, CARDFastDeleteAsync.
void __CARDMountCallback(s32 chan, s32 result)
References __CARDBlock, __CARDPutControlBlock, __CARDVerify, CARD_MAX_MOUNT_STEP, CARD_RESULT_IOERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_UNLOCKED, DoMount, DoUnmount, NULL.
Referenced by CARDMountAsync, DoMount, DoneCallback.
s32 CARDFormatAsync(s32 chan, CARDCallback callback)
Referenced by CARDFormat.
CARDDir * __CARDGetDirBlock(CARDControl *card)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDGetFileNo, __CARDGetStatusEx, __CARDSeek, __CARDSetStatusExAsync, __CARDUpdateDir, CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFastOpen, CARDFreeBlocks, CARDGetStatus, CARDOpen, CARDReadAsync, CARDRenameAsync, CARDSetStatusAsync, CARDWriteAsync, CreateCallbackFat, EraseCallback, WriteCallback.
s32 __CARDUpdateDir(s32 chan, CARDCallback callback)
References __CARDBlock, __CARDCheckSum, __CARDEraseSector, __CARDGetDirBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARDGetDirCheck, DCStoreRange, EraseCallback.
Referenced by __CARDSetStatusExAsync, CARDCheckExAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDRenameAsync, CARDSetStatusAsync, CreateCallbackFat, WriteCallback.
void __CARDCheckSum(void *ptr, int length, u16 *checksum, u16 *checksumInv)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDUpdateDir, __CARDUpdateFatBlock, CARDCheckExAsync, CARDFormatAsync, VerifyDir, VerifyFAT, VerifyID.
s32 __CARDVerify(CARDControl *card)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_READY, NULL, VerifyDir, VerifyFAT, VerifyID.
Referenced by __CARDMountCallback.
void * __CARDGetFatBlock(CARDControl *card)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDAllocBlock, __CARDFreeBlock, __CARDSeek, CARDCreateAsync, CARDFreeBlocks, EraseCallback, ReadCallback, WriteCallback.
s32 __CARDAllocBlock(s32 chan, u32 cBlock, CARDCallback callback)
References __CARDBlock, __CARDGetFatBlock, __CARDUpdateFatBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_INSSPACE, CARD_RESULT_NOCARD, CARDIsValidBlockNo.
Referenced by CARDCreateAsync.
s32 __CARDFreeBlock(s32 chan, u16 nBlock, CARDCallback callback)
References __CARDBlock, __CARDGetFatBlock, __CARDUpdateFatBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_NOCARD, CARDIsValidBlockNo.
Referenced by DeleteCallback.
s32 __CARDUpdateFatBlock(s32 chan, u16 *fat, CARDCallback callback)
References __CARDBlock, __CARDCheckSum, __CARDEraseSector, CARD_MAX_MOUNT_STEP, DCStoreRange, EraseCallback.
Referenced by __CARDAllocBlock, __CARDFreeBlock, CARDCheckExAsync.
void __CARDDefaultApiCallback(s32 chan, s32 result)
Referenced by CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFormatAsync, CARDMountAsync, CARDReadAsync, CARDWriteAsync.
void __CARDSyncCallback(s32 chan, s32 result)
References __CARDBlock, OSWakeupThread, CARDControl::threadQueue.
Referenced by __CARDRawRead, __CARDSetStatusEx, CARDCheckEx, CARDCreate, CARDDelete, CARDFastDelete, CARDFormat, CARDMount, CARDRead, CARDRename, CARDSetStatus, CARDWrite.
void __CARDExtHandler(s32 chan, OSContext *context)
References __CARDBlock, CARDControl::alarm, CARDControl::attached, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARDControl::exiCallback, EXISetExiCallback, CARDControl::extCallback, FALSE, OSCancelAlarm, CARDControl::result, CARDControl::txCallback.
Referenced by CARDMountAsync.
void __CARDExiHandler(s32 chan, OSContext *context)
References __CARDBlock, __CARDClearStatus, __CARDReadStatus, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_RESULT_IOERROR, CARD_RESULT_READY, EXILock, EXIUnlock, OSCancelAlarm, Retry, status.
Referenced by DoMount.
void __CARDTxHandler(s32 chan, OSContext *context)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIProbe, EXIUnlock, NULL.
Referenced by __CARDReadSegment, __CARDWritePage, Retry.
void __CARDUnlockedHandler(s32 chan, OSContext *context)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_UNLOCKED, EXIProbe, CARDControl::unlockCallback.
Referenced by __CARDStart, CARDMountAsync, UnlockedCallback.
int __CARDReadNintendoID(s32 chan, u32 *id)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_WRONGDEVICE, EXIDeselect, EXIImm, EXISelect, EXISync.
Referenced by DoMount.
s32 __CARDEnableInterrupt(s32 chan, BOOL enable)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync, FALSE, NULL.
Referenced by DoMount.
s32 __CARDReadStatus(s32 chan, u8 *status)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync, FALSE, NULL, status.
Referenced by __CARDExiHandler, DoMount, DoneCallback.
s32 __CARDClearStatus(s32 chan)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync, FALSE.
Referenced by __CARDExiHandler, DoMount.
s32 __CARDSleep(long chan)
s32 __CARDWakeup(long chan)
s32 __CARDReadSegment(s32 chan, CARDCallback callback)
References __CARDBlock, __CARDStart, __CARDTxHandler, AD1, AD2, AD3, BA, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_SEG_SIZE, EXIDeselect, EXIDma, EXIImmEx, EXIUnlock, NULL.
Referenced by __CARDRead, BlockReadCallback.
s32 __CARDWritePage(s32 chan, CARDCallback callback)
References __CARDBlock, __CARDStart, __CARDTxHandler, AD1, AD2, AD3, BA, CARD_MAX_MOUNT_STEP, CARD_PAGE_SIZE, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIDma, EXIImmEx, EXIUnlock.
Referenced by __CARDWrite, BlockWriteCallback.
s32 __CARDErase(long chan, void(*callback)(long, long))
s32 __CARDEraseSector(s32 chan, u32 addr, CARDCallback callback)
References __CARDBlock, __CARDStart, AD1, AD2, CARDControl::addr, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImmEx, EXIUnlock, NULL, CARDControl::result.
Referenced by __CARDUpdateDir, __CARDUpdateFatBlock, CARDFormatAsync, CARDWriteAsync, FormatCallback, WriteCallback.
void __CARDSetDiskID(DVDDiskID *id)
References __CARDDiskID, __CARDDiskNone, CARDControl::id.
Referenced by CARDInit.
s32 __CARDGetControlBlock(s32 chan, CARDControl **pcard)
References __CARDBlock, __CARDDiskID, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, NULL, OSDisableInterrupts, OSRestoreInterrupts, CARDControl::result.
Referenced by __CARDGetStatusEx, __CARDRawReadAsync, __CARDSeek, __CARDSetStatusExAsync, CARDCheckExAsync, CARDClose, CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFastOpen, CARDFormatAsync, CARDFreeBlocks, CARDGetEncoding, CARDGetMemSize, CARDGetSectorSize, CARDGetStatus, CARDOpen, CARDRenameAsync, CARDSetStatusAsync, CARDUnmount.
s32 __CARDPutControlBlock(CARDControl *card, s32 result)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, OSDisableInterrupts, OSRestoreInterrupts, CARDControl::result.
Referenced by __CARDGetStatusEx, __CARDMountCallback, __CARDRawReadAsync, __CARDSeek, __CARDSetStatusExAsync, BlockReadCallback, BlockWriteCallback, CARDCheckExAsync, CARDClose, CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFastOpen, CARDFormatAsync, CARDFreeBlocks, CARDGetEncoding, CARDGetMemSize, CARDGetSectorSize, CARDGetStatus, CARDOpen, CARDReadAsync, CARDRenameAsync, CARDSetStatusAsync, CARDWriteAsync, CreateCallbackFat, DeleteCallback, DoMount, EraseCallback, EraseCallback, EraseCallback, FormatCallback, ReadCallback, WriteCallback, WriteCallback, WriteCallback.
s32 __CARDSync(s32 chan)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARDGetResultCode, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, CARDControl::result.
Referenced by __CARDRawRead, __CARDSetStatusEx, CARDCheckEx, CARDCreate, CARDDelete, CARDFastDelete, CARDFormat, CARDMount, CARDRead, CARDRename, CARDSetStatus, CARDWrite.