CARDDir.c
static void WriteCallback(s32 chan, s32 result)
References __CARDBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, NULL.
Referenced by EraseCallback.
static void EraseCallback(s32 chan, s32 result)
References __CARDBlock, __CARDGetDirBlock, __CARDPutControlBlock, __CARDWrite, CARD_MAX_MOUNT_STEP, NULL, WriteCallback.
Referenced by __CARDUpdateDir.
CARDDir * __CARDGetDirBlock(CARDControl *card)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDGetFileNo, __CARDGetStatusEx, __CARDSeek, __CARDSetStatusExAsync, __CARDUpdateDir, CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFastOpen, CARDFreeBlocks, CARDGetStatus, CARDOpen, CARDReadAsync, CARDRenameAsync, CARDSetStatusAsync, CARDWriteAsync, CreateCallbackFat, EraseCallback, WriteCallback.
s32 __CARDUpdateDir(s32 chan, CARDCallback callback)
References __CARDBlock, __CARDCheckSum, __CARDEraseSector, __CARDGetDirBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARDGetDirCheck, DCStoreRange, EraseCallback.
Referenced by __CARDSetStatusExAsync, CARDCheckExAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDRenameAsync, CARDSetStatusAsync, CreateCallbackFat, WriteCallback.