CARDFormat.c
formatStep
static void FormatCallback(s32 chan, s32 result)
References __CARDBlock, __CARDEraseSector, __CARDPutControlBlock, __CARDWrite, CARD_MAX_MOUNT_STEP, CARD_NUM_SYSTEM_BLOCK, CARD_SYSTEM_BLOCK_SIZE, FormatCallback, CARDControl::formatStep, NULL.
Referenced by CARDFormatAsync, FormatCallback.
s32 CARDFormatAsync(s32 chan, CARDCallback callback)
References __CARDCheckSum, __CARDDefaultApiCallback, __CARDEraseSector, __CARDGetControlBlock, __CARDPutControlBlock, __OSLockSram, __OSLockSramEx, __OSUnlockSram, __OSUnlockSramEx, CARD_FAT_CHECKCODE, CARD_FAT_CHECKSUM, CARD_FAT_CHECKSUMINV, CARD_FAT_FREEBLOCKS, CARD_FAT_LASTSLOT, CARD_MAX_MOUNT_STEP, CARD_NUM_SYSTEM_BLOCK, CARD_SYSTEM_BLOCK_SIZE, CARD_WORKAREA_SIZE, CARDGetDirCheck, CARDID::checkSum, CARDID::checkSumInv, OSSram::counterBias, DCStoreRange, FALSE, FormatCallback, OSSram::language, OSGetFontEncode, OSGetTime, CARDID::serial.
Referenced by CARDFormat.
s32 CARDFormat(s32 chan)
References __CARDSync, __CARDSyncCallback, CARDFormatAsync.