CARDRdwr.c
static void BlockReadCallback(s32 chan, long result)
References __CARDBlock, __CARDPutControlBlock, __CARDReadSegment, BlockReadCallback, CARD_MAX_MOUNT_STEP, NULL, CARDControl::result, CARDControl::xferred.
Referenced by __CARDRead, BlockReadCallback.
static void BlockWriteCallback(s32 chan, long result)
References __CARDBlock, __CARDPutControlBlock, __CARDWritePage, BlockWriteCallback, CARD_MAX_MOUNT_STEP, NULL, CARDControl::result, CARDControl::xferred.
Referenced by __CARDWrite, BlockWriteCallback.
s32 __CARDRead(s32 chan, u32 addr, long length, void *dst, void(*callback)(long, long))
References __CARDBlock, __CARDReadSegment, CARDControl::addr, BlockReadCallback, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_SEG_SIZE, CARDControl::xferCallback.
s32 __CARDWrite(s32 chan, u32 addr, long length, void *dst, void(*callback)(long, long))
References __CARDBlock, __CARDWritePage, CARDControl::addr, BlockWriteCallback, CARD_MAX_MOUNT_STEP, CARD_PAGE_SIZE, CARD_RESULT_NOCARD, CARDControl::xferCallback.
s32 CARDGetXferredBytes(s32 chan)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARDControl::xferred.