CARDRead.c
TRUNC
static void ReadCallback(s32 chan, s32 result)
References __CARDBlock, __CARDGetFatBlock, __CARDPutControlBlock, __CARDRead, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_CANCELED, CARD_SEG_SIZE, CARDIsValidBlockNo, CARDFileInfo::iBlock, CARDFileInfo::length, NULL, CARDFileInfo::offset, OFFSET, ReadCallback, TRUNC.
Referenced by CARDReadAsync, ReadCallback.
s32 __CARDSeek(CARDFileInfo *fileInfo, s32 length, s32 offset, CARDControl **pcard)
References __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFatBlock, __CARDPutControlBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_FATAL_ERROR, CARD_RESULT_LIMIT, CARD_RESULT_READY, CARDIsValidBlockNo, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::length, CARDFileInfo::offset, TRUNC.
Referenced by CARDReadAsync, CARDWriteAsync.
s32 CARDReadAsync(CARDFileInfo *fileInfo, void *buf, s32 length, s32 offset, CARDCallback callback)
References __CARDAccess, __CARDDefaultApiCallback, __CARDGetDirBlock, __CARDIsPublic, __CARDPutControlBlock, __CARDRead, __CARDSeek, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOPERM, CARD_SEG_SIZE, CARDFileInfo::chan, DCInvalidateRange, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::offset, OFFSET, ReadCallback.
Referenced by CARDRead.
s32 CARDRead(struct CARDFileInfo *fileInfo, void *buf, s32 length, long offset)
References __CARDSync, __CARDSyncCallback, CARD_MAX_MOUNT_STEP, CARDReadAsync, CARDFileInfo::chan.
s32 CARDCancel(CARDFileInfo *fileInfo)
References __CARDBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_CANCELED, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::length, OSDisableInterrupts, OSRestoreInterrupts.