CARDMount.c
u32 SectorSizeTable[8][8]
Referenced by CARDProbeEx, DoMount.
u32 LatencyTable[8][8]
Referenced by DoMount.
static s32 DoMount(s32 chan)
References __CARDBlock, __CARDClearStatus, __CARDEnableInterrupt, __CARDExiHandler, __CARDMountCallback, __CARDPutControlBlock, __CARDRead, __CARDReadNintendoID, __CARDReadStatus, __CARDUnlock, __OSLockSramEx, __OSUnlockSramEx, CARD_MAX_MOUNT_STEP, CARD_RESULT_IOERROR, CARD_RESULT_NOCARD, CARD_SYSTEM_BLOCK_SIZE, CARD_WORKAREA_SIZE, DCInvalidateRange, DoUnmount, EXIProbe, EXISetExiCallback, EXIUnlock, FALSE, OSSramEx::flashID, OSSramEx::flashIDCheckSum, LatencyTable, SectorSizeTable, status, TRUE.
Referenced by __CARDMountCallback, CARDMountAsync.
static void DoUnmount(s32 chan, s32 v)
References __CARDBlock, CARD_MAX_MOUNT_STEP, EXIDetach, EXISetExiCallback, FALSE, OSCancelAlarm, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __CARDMountCallback, CARDUnmount, DoMount.
BOOL CARDProbe(s32 chan)
References EXIProbe.
s32 CARDProbeEx(s32 chan, s32 *memSize, s32 *sectorSize)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_WRONGDEVICE, EXIGetID, EXIGetState, EXIProbeEx, OSDisableInterrupts, OSRestoreInterrupts, SectorSizeTable.
void __CARDMountCallback(s32 chan, s32 result)
References __CARDBlock, __CARDPutControlBlock, __CARDVerify, CARD_MAX_MOUNT_STEP, CARD_RESULT_IOERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_UNLOCKED, DoMount, DoUnmount, NULL.
Referenced by CARDMountAsync, DoMount, DoneCallback.
s32 CARDMountAsync(s32 chan, void *workArea, CARDCallback detachCallback, CARDCallback attachCallback)
References __CARDBlock, __CARDDefaultApiCallback, __CARDExtHandler, __CARDMountCallback, __CARDUnlockedHandler, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_WRONGDEVICE, DoMount, EXIAttach, EXIGetState, EXILock, EXISetExiCallback, OSCancelAlarm, OSDisableInterrupts, OSRestoreInterrupts, TRUE.
Referenced by CARDMount.
s32 CARDMount(s32 chan, void *workArea, CARDCallback detachCallback)
References __CARDSync, __CARDSyncCallback, CARD_MAX_MOUNT_STEP, CARDMountAsync.
s32 CARDUnmount(s32 chan)
References __CARDGetControlBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, DoUnmount.
Referenced by OnReset.