CARDBios.c
AD1
AD1EX
AD2
AD3
BA
CARDControl __CARDBlock[2][2]
Referenced by __CARDAllocBlock, __CARDErase, __CARDEraseSector, __CARDExiHandler, __CARDExtHandler, __CARDFreeBlock, __CARDGetControlBlock, __CARDMountCallback, __CARDRead, __CARDReadSegment, __CARDStart, __CARDSync, __CARDSyncCallback, __CARDTxHandler, __CARDUnlock, __CARDUnlockedHandler, __CARDUpdateDir, __CARDUpdateFatBlock, __CARDWrite, __CARDWritePage, BlockReadCallback, BlockWriteCallback, CARDCancel, CARDGetResultCode, CARDGetXferredBytes, CARDInit, CARDMountAsync, CARDProbeEx, CreateCallbackFat, DeleteCallback, DoMount, DoneCallback, DoUnmount, EraseCallback, EraseCallback, EraseCallback, FormatCallback, InitCallback, ReadArrayUnlock, ReadCallback, Retry, TimeoutHandler, UnlockedCallback, VerifyID, WriteCallback, WriteCallback, WriteCallback.
DVDDiskID* __CARDDiskID
Referenced by __CARDAccess, __CARDGetControlBlock, __CARDSetDiskID, CARDCreateAsync, CARDInit, CARDRenameAsync, CreateCallbackFat.
DVDDiskID __CARDDiskNone
Referenced by __CARDAccess, __CARDSetDiskID.
OSResetFunctionInfo ResetFunctionInfo
Referenced by CARDInit.
static void TimeoutHandler(OSAlarm *alarm, OSContext *context)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_IOERROR, EXISetExiCallback, NULL.
Referenced by SetupTimeoutAlarm.
static void SetupTimeoutAlarm(CARDControl *card)
References CARD_MAX_MOUNT_STEP, OSCancelAlarm, OSMillisecondsToTicks, OSSecondsToTicks, OSSetAlarm, TimeoutHandler.
Referenced by __CARDStart, Retry.
static s32 Retry(s32 chan)
References __CARDBlock, __CARDTxHandler, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIDma, EXIImmEx, EXISelect, EXIUnlock, SetupTimeoutAlarm.
Referenced by __CARDExiHandler, UnlockedCallback.
static void UnlockedCallback(s32 chan, s32 result)
References __CARDBlock, __CARDUnlockedHandler, CARD_MAX_MOUNT_STEP, CARD_RESULT_READY, EXILock, NULL, Retry, CARDControl::unlockCallback, UnlockedCallback.
Referenced by __CARDStart, UnlockedCallback.
static BOOL OnReset(BOOL f)
References CARD_RESULT_BUSY, CARDUnmount, FALSE, TRUE.
void __CARDDefaultApiCallback(s32 chan, s32 result)
Referenced by CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFormatAsync, CARDMountAsync, CARDReadAsync, CARDWriteAsync.
void __CARDSyncCallback(s32 chan, s32 result)
References __CARDBlock, OSWakeupThread, CARDControl::threadQueue.
Referenced by __CARDRawRead, __CARDSetStatusEx, CARDCheckEx, CARDCreate, CARDDelete, CARDFastDelete, CARDFormat, CARDMount, CARDRead, CARDRename, CARDSetStatus, CARDWrite.
void __CARDExtHandler(s32 chan, OSContext *context)
References __CARDBlock, CARDControl::alarm, CARDControl::attached, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARDControl::exiCallback, EXISetExiCallback, CARDControl::extCallback, FALSE, OSCancelAlarm, CARDControl::result, CARDControl::txCallback.
Referenced by CARDMountAsync.
void __CARDExiHandler(s32 chan, OSContext *context)
References __CARDBlock, __CARDClearStatus, __CARDReadStatus, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_RESULT_IOERROR, CARD_RESULT_READY, EXILock, EXIUnlock, OSCancelAlarm, Retry, status.
Referenced by DoMount.
void __CARDTxHandler(s32 chan, OSContext *context)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIProbe, EXIUnlock, NULL.
Referenced by __CARDReadSegment, __CARDWritePage, Retry.
void __CARDUnlockedHandler(s32 chan, OSContext *context)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_UNLOCKED, EXIProbe, CARDControl::unlockCallback.
Referenced by __CARDStart, CARDMountAsync, UnlockedCallback.
int __CARDReadNintendoID(s32 chan, u32 *id)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_WRONGDEVICE, EXIDeselect, EXIImm, EXISelect, EXISync.
Referenced by DoMount.
s32 __CARDEnableInterrupt(s32 chan, BOOL enable)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync, FALSE, NULL.
Referenced by DoMount.
s32 __CARDReadStatus(s32 chan, u8 *status)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync, FALSE, NULL, status.
Referenced by __CARDExiHandler, DoMount, DoneCallback.
s32 __CARDClearStatus(s32 chan)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync, FALSE.
Referenced by __CARDExiHandler, DoMount.
s32 __CARDSleep(s32 chan)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync.
s32 __CARDWakeup(s32 chan)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImm, EXISelect, EXISync.
static s32 __CARDStart(s32 chan, CARDCallback txCallback, CARDCallback exiCallback)
References __CARDBlock, __CARDUnlockedHandler, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXILock, EXISelect, EXIUnlock, SetupTimeoutAlarm, CARDControl::txCallback, UnlockedCallback.
Referenced by __CARDErase, __CARDEraseSector, __CARDReadSegment, __CARDWritePage.
s32 __CARDReadSegment(s32 chan, CARDCallback callback)
References __CARDBlock, __CARDStart, __CARDTxHandler, AD1, AD2, AD3, BA, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_SEG_SIZE, EXIDeselect, EXIDma, EXIImmEx, EXIUnlock, NULL.
Referenced by __CARDRead, BlockReadCallback.
s32 __CARDWritePage(s32 chan, CARDCallback callback)
References __CARDBlock, __CARDStart, __CARDTxHandler, AD1, AD2, AD3, BA, CARD_MAX_MOUNT_STEP, CARD_PAGE_SIZE, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIDma, EXIImmEx, EXIUnlock.
Referenced by __CARDWrite, BlockWriteCallback.
s32 __CARDErase(s32 chan, void(*callback)(long, long))
References __CARDBlock, __CARDStart, CARD_MAX_MOUNT_STEP, CARDControl::cmd, EXIDeselect, EXIImmEx, EXIUnlock, CARDControl::result.
s32 __CARDEraseSector(s32 chan, u32 addr, CARDCallback callback)
References __CARDBlock, __CARDStart, AD1, AD2, CARDControl::addr, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, CARD_RESULT_READY, EXIDeselect, EXIImmEx, EXIUnlock, NULL, CARDControl::result.
Referenced by __CARDUpdateDir, __CARDUpdateFatBlock, CARDFormatAsync, CARDWriteAsync, FormatCallback, WriteCallback.
void CARDInit(void)
References __CARDBlock, __CARDDiskID, __CARDSetDiskID, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, DSPInit, OSCreateAlarm, OSInitAlarm, OSInitThreadQueue, OSPhysicalToCached, OSRegisterResetFunction, ResetFunctionInfo, CARDControl::result.
void __CARDSetDiskID(DVDDiskID *id)
References __CARDDiskID, __CARDDiskNone, CARDControl::id.
Referenced by CARDInit.
s32 __CARDGetControlBlock(s32 chan, CARDControl **pcard)
References __CARDBlock, __CARDDiskID, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, NULL, OSDisableInterrupts, OSRestoreInterrupts, CARDControl::result.
Referenced by __CARDGetStatusEx, __CARDRawReadAsync, __CARDSeek, __CARDSetStatusExAsync, CARDCheckExAsync, CARDClose, CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFastOpen, CARDFormatAsync, CARDFreeBlocks, CARDGetEncoding, CARDGetMemSize, CARDGetSectorSize, CARDGetStatus, CARDOpen, CARDRenameAsync, CARDSetStatusAsync, CARDUnmount.
s32 __CARDPutControlBlock(CARDControl *card, s32 result)
References CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_NOCARD, OSDisableInterrupts, OSRestoreInterrupts, CARDControl::result.
Referenced by __CARDGetStatusEx, __CARDMountCallback, __CARDRawReadAsync, __CARDSeek, __CARDSetStatusExAsync, BlockReadCallback, BlockWriteCallback, CARDCheckExAsync, CARDClose, CARDCreateAsync, CARDDeleteAsync, CARDFastDeleteAsync, CARDFastOpen, CARDFormatAsync, CARDFreeBlocks, CARDGetEncoding, CARDGetMemSize, CARDGetSectorSize, CARDGetStatus, CARDOpen, CARDReadAsync, CARDRenameAsync, CARDSetStatusAsync, CARDWriteAsync, CreateCallbackFat, DeleteCallback, DoMount, EraseCallback, EraseCallback, EraseCallback, FormatCallback, ReadCallback, WriteCallback, WriteCallback, WriteCallback.
s32 CARDGetResultCode(s32 chan)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARDControl::result.
Referenced by __CARDSync.
s32 CARDFreeBlocks(s32 chan, s32 *byteNotUsed, s32 *filesNotUsed)
References __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFatBlock, __CARDPutControlBlock, CARD_FAT_FREEBLOCKS, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_READY, CARDControl::result.
s32 CARDGetEncoding(s32 chan, u16 *encode)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARDID::encode.
s32 CARDGetMemSize(s32 chan, u16 *size)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARDControl::result, size.
s32 CARDGetSectorSize(s32 chan, u32 *size)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARDControl::result, size.
s32 __CARDSync(s32 chan)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARDGetResultCode, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, CARDControl::result.
Referenced by __CARDRawRead, __CARDSetStatusEx, CARDCheckEx, CARDCreate, CARDDelete, CARDFastDelete, CARDFormat, CARDMount, CARDRead, CARDRename, CARDSetStatus, CARDWrite.