CARDBlock.c
static void WriteCallback(s32 chan, s32 result)
References __CARDBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, NULL.
Referenced by EraseCallback.
static void EraseCallback(s32 chan, s32 result)
References __CARDBlock, __CARDGetFatBlock, __CARDPutControlBlock, __CARDWrite, CARD_MAX_MOUNT_STEP, CARD_SYSTEM_BLOCK_SIZE, NULL, WriteCallback.
Referenced by __CARDUpdateFatBlock.
void * __CARDGetFatBlock(CARDControl *card)
References CARD_MAX_MOUNT_STEP.
Referenced by __CARDAllocBlock, __CARDFreeBlock, __CARDSeek, CARDCreateAsync, CARDFreeBlocks, EraseCallback, ReadCallback, WriteCallback.
s32 __CARDAllocBlock(s32 chan, u32 cBlock, CARDCallback callback)
References __CARDBlock, __CARDGetFatBlock, __CARDUpdateFatBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_INSSPACE, CARD_RESULT_NOCARD, CARDIsValidBlockNo.
Referenced by CARDCreateAsync.
s32 __CARDFreeBlock(s32 chan, u16 nBlock, CARDCallback callback)
References __CARDBlock, __CARDGetFatBlock, __CARDUpdateFatBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_NOCARD, CARDIsValidBlockNo.
Referenced by DeleteCallback.
s32 __CARDUpdateFatBlock(s32 chan, u16 *fat, CARDCallback callback)
References __CARDBlock, __CARDCheckSum, __CARDEraseSector, CARD_MAX_MOUNT_STEP, DCStoreRange, EraseCallback.
Referenced by __CARDAllocBlock, __CARDFreeBlock, CARDCheckExAsync.