CARDStat.c
static void UpdateIconOffsets(CARDDir *ent, CARDStat *stat)
References CARDStat::bannerFormat, CARD_BANNER_HEIGHT, CARD_BANNER_WIDTH, CARD_ICON_HEIGHT, CARD_ICON_MAX, CARD_ICON_WIDTH, CARD_MAX_MOUNT_STEP, CARD_STAT_BANNER_C8, CARD_STAT_BANNER_RGB5A3, CARD_STAT_ICON_C8, CARD_STAT_ICON_RGB5A3, CARDGetBannerFormat, CARDGetIconFormat, FALSE, CARDStat::iconFormat, CARDStat::iconSpeed, CARDStat::offsetBanner, CARDStat::offsetBannerTlut, CARDStat::offsetData, CARDStat::offsetIcon, CARDStat::offsetIconTlut, TRUE.
Referenced by CARDGetStatus, CARDSetStatusAsync.
s32 CARDGetStatus(s32 chan, s32 fileNo, CARDStat *stat)
References __CARDAccess, __CARDGetControlBlock, __CARDGetDirBlock, __CARDIsPublic, __CARDPutControlBlock, CARDStat::bannerFormat, CARD_FILENAME_MAX, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOPERM, CARDStat::commentAddr, CARDStat::company, CARDStat::fileName, CARDStat::gameName, CARDStat::iconAddr, CARDStat::iconFormat, CARDStat::iconSpeed, CARDStat::length, CARDStat::time, UpdateIconOffsets.
s32 CARDSetStatusAsync(s32 chan, s32 fileNo, CARDStat *stat, CARDCallback callback)
References __CARDAccess, __CARDGetControlBlock, __CARDGetDirBlock, __CARDPutControlBlock, __CARDUpdateDir, CARDStat::bannerFormat, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_STAT_SPEED_FAST, CARDSetIconSpeed, CARDStat::commentAddr, CARDStat::iconAddr, CARDStat::iconFormat, CARDStat::iconSpeed, OSGetTime, OSTicksToSeconds, UpdateIconOffsets.
Referenced by CARDSetStatus.
s32 CARDSetStatus(s32 chan, long fileNo, struct CARDStat *stat)
References __CARDSync, __CARDSyncCallback, CARDSetStatusAsync.