DBInterface.h
typedef void(* MTRCallbackType) (s32))(s32)
typedef struct DBInterface DBInterface
DBInterface* __DBInterface
Referenced by __DBIsExceptionMarked, __DBMarkException, __DBSetPresent, DBInit, DBIsDebuggerPresent.
void DBInit(void)
References __DBExceptionDestination, __DBInterface, DBVerbose, DBInterface::ExceptionDestination, OSCachedToPhysical, OSPhysicalToCached, TRUE.
void DBInitComm(u8 **inputFlagPtr, MTRCallbackType mtrCallback)
References CARD_MAX_MOUNT_STEP, DBGEXIInit, EXIInputFlag, MTRCallback, OSDisableInterrupts, OSRestoreInterrupts, pEXIInputFlag.
void __DBExceptionDestination(void)
References __DBExceptionDestinationAux, CARD_MAX_MOUNT_STEP, r3.
Referenced by DBInit.
void __DBExceptionDestinationAux(void)
References CARD_MAX_MOUNT_STEP, OSDumpContext, OSPhysicalToCached, OSReport, PPCHalt.
Referenced by __DBExceptionDestination.
BOOL __DBIsExceptionMarked(__OSException exception)
References __DBInterface, CARD_MAX_MOUNT_STEP, DBInterface::exceptionMask.
Referenced by OSExceptionInit.
void __DBMarkException(__OSException exception, BOOL value)
References __DBInterface, CARD_MAX_MOUNT_STEP, DBInterface::exceptionMask.
void __DBSetPresent(u32 value)
References __DBInterface, DBInterface::bPresent, CARD_MAX_MOUNT_STEP.