DEMOInit.h
void* DemoFrameBuffer1
Referenced by __DEMOInitMem, __DEMOInitVI, DEMOSwapBuffers.
void* DemoFrameBuffer2
Referenced by __DEMOInitMem, __DEMOInitVI, DEMOSwapBuffers.
void* DemoCurrentBuffer
Referenced by __BypassDoneRender, __DEMOInitGX, __DEMOInitMem, __DEMOInitVI, DEMODoneRender, DEMOGetCurrentBuffer, DEMOSwapBuffers.
void DEMOInit(struct _GXRenderModeObj *mode)
References __DEMOInitGX, __DEMOInitMem, __DEMOInitRenderMode, __DEMOInitVI, __OSCurrHeap, DefaultFifo, DefaultFifoObj, DEMOPadInit, DVDInit, GXInit, OSAllocFromHeap, OSInit, rmode, VIConfigure, VIInit.
void DEMOBeforeRender()
References BypassWorkaround, _GXRenderModeObj::fbWidth, _GXRenderModeObj::field_rendering, GXInvalidateTexAll, GXInvalidateVtxCache, GXSetDrawSync, GXSetViewport, GXSetViewportJitter, rmode, VIGetNextField, _GXRenderModeObj::xfbHeight.
Referenced by DEMOWinMenuChild.
void DEMODoneRender()
References __BypassDoneRender, BypassWorkaround, DemoCurrentBuffer, DEMOPrintStats, DemoStatEnable, DEMOSwapBuffers, DEMOUpdateStats, GXCopyDisp, GXDrawDone, GXSetColorUpdate, GXSetZMode.
Referenced by DEMOWinMenuChild.
void DEMOSwapBuffers()
References DemoCurrentBuffer, DemoFirstFrame, DemoFrameBuffer1, DemoFrameBuffer2, VIFlush, VISetBlack, VISetNextFrameBuffer, VIWaitForRetrace.
Referenced by __BypassDoneRender, DEMODoneRender.
void DEMOSetTevColorIn(enum _GXTevStageID stage, enum _GXTevColorArg a, enum _GXTevColorArg b, enum _GXTevColorArg c, enum _GXTevColorArg d)
References CARD_MAX_MOUNT_STEP, GX_CC_TEXC, GX_CC_TEXRRR, GXSetTevColorIn, GXSetTevSwapMode.
Referenced by DEMOSetTevOp.
void DEMOSetTevOp(enum _GXTevStageID id, enum _GXTevMode mode)
References CARD_MAX_MOUNT_STEP, DEMOSetTevColorIn, FALSE, GX_CC_RASC, GX_TEVSTAGE5, GXSetTevAlphaIn, GXSetTevAlphaOp, GXSetTevColorIn, GXSetTevColorOp.
struct _GXRenderModeObj * DEMOGetRenderModeObj()
u32 DEMOGetCurrentBuffer(void)
References DemoCurrentBuffer.
void DEMOEnableBypassWorkaround(u32 timeoutFrames)
References __BypassRetraceCallback, BypassWorkaround, CARD_MAX_MOUNT_STEP, FrameMissThreshold, VISetPreRetraceCallback.
void DEMOReInit(struct _GXRenderModeObj *mode)
References __DEMOInitGX, __DEMOInitRenderMode, __DEMOInitVI, __OSCurrHeap, CARD_MAX_MOUNT_STEP, DefaultFifoObj, GXAbortFrame, GXGetCPUFifo, GXGetFifoBase, GXGetFifoSize, GXInit, GXInitFifoBase, GXSetCPUFifo, GXSetGPFifo, OSAllocFromHeap, OSFreeToHeap, rmode, VIConfigure.
Referenced by __BypassDoneRender.