DEMOPuts.c
u32 DEMOFontBitmap[][]
Referenced by DEMOLoadFont.
struct _GXTexObj fontTexObj
Referenced by DEMOLoadFont.
s32 fontShift
Referenced by DEMOLoadFont, DEMOPuts.
struct OSFontHeader* FontData
Referenced by DEMODumpROMFont, DEMOGetRFTextWidth, DEMOInitROMFont, DEMORFPuts, DEMORFPutsEx, DrawFontChar, LoadSheet.
void* LastSheet
Referenced by DEMORFPuts, DEMORFPutsEx, LoadSheet.
s16 FontSize
Referenced by DEMOGetRFTextWidth, DEMOInitROMFont, DEMORFPuts, DEMORFPutsEx, DEMOSetROMFontSize, DrawFontChar.
s16 FontSpace
Referenced by DEMOGetRFTextWidth, DEMOInitROMFont, DEMORFPuts, DEMORFPutsEx, DEMOSetROMFontSize.
static void DrawFontChar(int x, int y, int z, int xChar, int yChar)
References CARD_MAX_MOUNT_STEP, OSFontHeader::cellHeight, OSFontHeader::cellWidth, FontData, FontSize, GXBegin, GXEnd.
Referenced by DEMORFPuts, DEMORFPutsEx.
static void LoadSheet(void *image, enum _GXTexMapID texMapID)
References CARD_MAX_MOUNT_STEP, FontData, GXInitTexObj, GXInitTexObjLOD, GXLoadTexMtxImm, GXLoadTexObj, GXSetNumTexGens, GXSetTexCoordGen, LastSheet, MTXScale, OSFontHeader::sheetFormat, OSFontHeader::sheetHeight, OSFontHeader::sheetWidth.
Referenced by DEMORFPuts, DEMORFPutsEx.
void DEMOSetFontType(DMFontType attr)
References DM_FT_OPQ, DM_FT_RVS, DM_FT_XLU, GXSetBlendMode.
Referenced by DEMOInitCaption.
void DEMOLoadFont(enum _GXTexMapID texMap, enum _GXTexMtx texMtx, DMTexFlt texFlt)
References CARD_MAX_MOUNT_STEP, DEMOFontBitmap, fontShift, fontTexObj, GXInitTexObj, GXInitTexObjLOD, GXLoadTexMtxImm, GXLoadTexObj, GXSetNumTexGens, GXSetTexCoordGen, MTXScale, OSFontHeader::width.
Referenced by DEMOInitCaption.
void DEMOSetupScrnSpc(s32 width, long height, float depth)
References CARD_MAX_MOUNT_STEP, GXLoadPosMtxImm, GXSetCurrentMtx, GXSetProjection, MTXIdentity, MTXOrtho, OSFontHeader::width.
Referenced by DEMOInitCaption.
void DEMOInitCaption(s32 font_type, long width, long height)
References CARD_MAX_MOUNT_STEP, DEMOLoadFont, DEMOSetFontType, DEMOSetupScrnSpc, GXSetNumChans, GXSetNumTevStages, GXSetTevOp, GXSetTevOrder, GXSetZMode, OSFontHeader::width.
Referenced by DEMOPrintStats, DEMOWinRefresh.
void DEMOPuts(s16 x, s16 y, s16 z, char *string)
References CARD_MAX_MOUNT_STEP, fontShift, GXBegin, GXClearVtxDesc, GXEnd, GXSetVtxAttrFmt, GXSetVtxDesc.
Referenced by DEMOPrintf.
void DEMOPrintf(s16 x, s16 y, s16 z, char *fmt,...)
References CARD_MAX_MOUNT_STEP, DEMOPuts.
Referenced by DEMOPrintStats, DEMOWinRefresh.
struct OSFontHeader * DEMOInitROMFont()
References __OSCurrHeap, CARD_MAX_MOUNT_STEP, OSFontHeader::cellWidth, FontData, FontSize, FontSpace, OSAllocFromHeap, OSGetFontEncode, OSInitFont, OSPanic.
void DEMOSetROMFontSize(s16 size, s16 space)
References CARD_MAX_MOUNT_STEP, FontSize, FontSpace, size.
int DEMORFPuts(s16 x, s16 y, s16 z, char *string)
References CARD_MAX_MOUNT_STEP, OSFontHeader::cellWidth, DrawFontChar, FontData, FontSize, FontSpace, GXClearVtxDesc, GXSetVtxAttrFmt, GXSetVtxDesc, LastSheet, OSFontHeader::leading, LoadSheet, NULL, OSGetFontTexture.
Referenced by DEMORFPrintf.
int DEMORFPutsEx(s16 x, s16 y, s16 z, char *string, s16 maxWidth, int length)
References CARD_MAX_MOUNT_STEP, OSFontHeader::cellWidth, DrawFontChar, FontData, FontSize, FontSpace, GXClearVtxDesc, GXSetVtxAttrFmt, GXSetVtxDesc, LastSheet, OSFontHeader::leading, LoadSheet, NULL, OSGetFontTexture.
int DEMORFPrintf(s16 x, s16 y, s16 z, char *fmt,...)
References CARD_MAX_MOUNT_STEP, DEMORFPuts.
char * DEMODumpROMFont(char *string)
References CARD_MAX_MOUNT_STEP, FontData, OSGetFontEncode, OSGetFontTexel, OSInitFont, OSLoadFont, OSReport.
int DEMOGetRFTextWidth(char *string)
References CARD_MAX_MOUNT_STEP, OSFontHeader::cellWidth, FontData, FontSize, FontSpace, OSGetFontWidth.