DEMOInit.c
u16 DemoStatEnable
Referenced by DEMODoneRender, DEMOSetStats.
struct _GXRenderModeObj rmodeobj
Referenced by __DEMOInitRenderMode.
u16 DemoFirstFrame
Referenced by DEMOSwapBuffers.
void* DefaultFifo
Referenced by DEMOInit.
GXFifoObj* DefaultFifoObj
Referenced by DEMOInit, DEMOReInit.
struct _GXRenderModeObj* rmode
Referenced by __BypassDoneRender, __DEMOInitGX, __DEMOInitMem, __DEMOInitRenderMode, __DEMOInitVI, DEMOBeforeRender, DEMOGetRenderModeObj, DEMOInit, DEMOPrintStats, DEMOReInit, GXInit.
int BypassWorkaround
Referenced by DEMOBeforeRender, DEMODoneRender, DEMOEnableBypassWorkaround.
u32 FrameCount
Referenced by __BypassDoneRender, __BypassRetraceCallback.
u32 FrameMissThreshold
Referenced by __BypassDoneRender, DEMOEnableBypassWorkaround.
void* DemoFrameBuffer1
Referenced by __DEMOInitMem, __DEMOInitVI, DEMOSwapBuffers.
void* DemoFrameBuffer2
Referenced by __DEMOInitMem, __DEMOInitVI, DEMOSwapBuffers.
void* DemoCurrentBuffer
Referenced by __BypassDoneRender, __DEMOInitGX, __DEMOInitMem, __DEMOInitVI, DEMODoneRender, DEMOGetCurrentBuffer, DEMOSwapBuffers.
static void __DEMOInitRenderMode(struct _GXRenderModeObj *mode)
References CARD_MAX_MOUNT_STEP, GXAdjustForOverscan, GXMpal480IntDf, GXNtsc480IntDf, GXPal528IntDf, NULL, OSPanic, rmode, rmodeobj, VI_MPAL, VI_NTSC, VI_PAL, VIGetTvFormat.
Referenced by DEMOInit, DEMOReInit.
static void __DEMOInitMem()
References CARD_MAX_MOUNT_STEP, DemoCurrentBuffer, DemoFrameBuffer1, DemoFrameBuffer2, _GXRenderModeObj::fbWidth, LoadMemInfo, OSCreateHeap, OSGetArenaHi, OSGetArenaLo, OSGetConsoleSimulatedMemSize, OSGetConsoleType, OSGetPhysicalMemSize, OSInitAlloc, OSSetArenaLo, OSSetCurrentHeap, rmode, _GXRenderModeObj::xfbHeight.
Referenced by DEMOInit.
static void __DEMOInitGX()
References _GXRenderModeObj::aa, DemoCurrentBuffer, _GXRenderModeObj::efbHeight, _GXRenderModeObj::fbWidth, GXCopyDisp, GXSetCopyFilter, GXSetDispCopyDst, GXSetDispCopyGamma, GXSetDispCopySrc, GXSetDispCopyYScale, GXSetPixelFmt, GXSetScissor, GXSetVerifyLevel, GXSetViewport, rmode, _GXRenderModeObj::sample_pattern, _GXRenderModeObj::vfilter, _GXRenderModeObj::xfbHeight.
Referenced by DEMOInit, DEMOReInit.
static void __DEMOInitVI()
References CARD_MAX_MOUNT_STEP, DemoCurrentBuffer, DemoFrameBuffer1, DemoFrameBuffer2, rmode, VIFlush, VISetNextFrameBuffer, _GXRenderModeObj::viTVmode, VIWaitForRetrace.
Referenced by DEMOInit, DEMOReInit.
static void __DEMOInitForEmu()
static void __BypassRetraceCallback()
References FrameCount.
Referenced by DEMOEnableBypassWorkaround.
static void __BypassDoneRender()
References abort, CARD_MAX_MOUNT_STEP, DemoCurrentBuffer, DEMOReInit, DEMOSwapBuffers, FrameCount, FrameMissThreshold, GXCopyDisp, GXReadDrawSync, GXSetDrawSync, OSReport, rmode.
Referenced by DEMODoneRender.
static void LoadMemInfo()
References __OSCurrHeap, CARD_MAX_MOUNT_STEP, DVDClose, DVDOpen, DVDReadPrio, DVDFileInfo::length, OSAllocFixed, OSCreateHeap, OSDumpHeap, OSGetArenaHi, OSGetArenaLo, OSGetConsoleSimulatedMemSize, OSGetPhysicalMemSize, OSInitAlloc, OSPanic, OSPhysicalToCached, OSReport, OSSetArenaHi, OSSetArenaLo, OSSetCurrentHeap.
Referenced by __DEMOInitMem.
void DEMOInit(struct _GXRenderModeObj *mode)
References __DEMOInitGX, __DEMOInitMem, __DEMOInitRenderMode, __DEMOInitVI, __OSCurrHeap, DefaultFifo, DefaultFifoObj, DEMOPadInit, DVDInit, GXInit, OSAllocFromHeap, OSInit, rmode, VIConfigure, VIInit.
void DEMOBeforeRender()
References BypassWorkaround, _GXRenderModeObj::fbWidth, _GXRenderModeObj::field_rendering, GXInvalidateTexAll, GXInvalidateVtxCache, GXSetDrawSync, GXSetViewport, GXSetViewportJitter, rmode, VIGetNextField, _GXRenderModeObj::xfbHeight.
Referenced by DEMOWinMenuChild.
void DEMODoneRender()
References __BypassDoneRender, BypassWorkaround, DemoCurrentBuffer, DEMOPrintStats, DemoStatEnable, DEMOSwapBuffers, DEMOUpdateStats, GXCopyDisp, GXDrawDone, GXSetColorUpdate, GXSetZMode.
Referenced by DEMOWinMenuChild.
void DEMOSwapBuffers()
References DemoCurrentBuffer, DemoFirstFrame, DemoFrameBuffer1, DemoFrameBuffer2, VIFlush, VISetBlack, VISetNextFrameBuffer, VIWaitForRetrace.
Referenced by __BypassDoneRender, DEMODoneRender.
void DEMOSetTevColorIn(enum _GXTevStageID stage, enum _GXTevColorArg a, enum _GXTevColorArg b, enum _GXTevColorArg c, enum _GXTevColorArg d)
References CARD_MAX_MOUNT_STEP, GX_CC_TEXC, GX_CC_TEXRRR, GXSetTevColorIn, GXSetTevSwapMode.
Referenced by DEMOSetTevOp.
void DEMOSetTevOp(enum _GXTevStageID id, enum _GXTevMode mode)
References CARD_MAX_MOUNT_STEP, DEMOSetTevColorIn, FALSE, GX_CC_RASC, GX_TEVSTAGE5, GXSetTevAlphaIn, GXSetTevAlphaOp, GXSetTevColorIn, GXSetTevColorOp.
struct _GXRenderModeObj * DEMOGetRenderModeObj()
References rmode.
Referenced by DEMOPrintStats, DEMOWinInit.
u32 DEMOGetCurrentBuffer(void)
References DemoCurrentBuffer.
void DEMOEnableBypassWorkaround(u32 timeoutFrames)
References __BypassRetraceCallback, BypassWorkaround, CARD_MAX_MOUNT_STEP, FrameMissThreshold, VISetPreRetraceCallback.
void DEMOReInit(struct _GXRenderModeObj *mode)
References __DEMOInitGX, __DEMOInitRenderMode, __DEMOInitVI, __OSCurrHeap, CARD_MAX_MOUNT_STEP, DefaultFifoObj, GXAbortFrame, GXGetCPUFifo, GXGetFifoBase, GXGetFifoSize, GXInit, GXInitFifoBase, GXSetCPUFifo, GXSetGPFifo, OSAllocFromHeap, OSFreeToHeap, rmode, VIConfigure.
Referenced by __BypassDoneRender.