DEMOStats.c
u16 DemoStatEnable
Referenced by DEMODoneRender, DEMOSetStats.
DemoStatData* DemoStat
Referenced by DEMOPrintStats, DEMOSetStats, DEMOWriteStats.
u32 DemoStatIndx
Referenced by DEMOSetStats, DEMOUpdateStats, DEMOWriteStats.
u32 DemoStatMaxIndx
Referenced by DEMOPrintStats, DEMOSetStats, DEMOUpdateStats.
u32 DemoStatClocks
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 DemoStatDisp
Referenced by DEMOPrintStats, DEMOSetStats.
u32 DemoStatStrLen
Referenced by DEMOSetStats.
u32 topPixIn
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 topPixOut
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 botPixIn
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 botPixOut
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 clrPixIn
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 copyClks
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 vcCheck
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 vcMiss
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 vcStall
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 cpReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 tcReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 cpuRdReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 cpuWrReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 dspReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 ioReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 viReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 peReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 rfReq
Referenced by DEMOPrintStats, DEMOWriteStats.
u32 fiReq
Referenced by DEMOPrintStats, DEMOWriteStats.
static void DEMOWriteStats(u16 update)
References botPixIn, botPixOut, CARD_MAX_MOUNT_STEP, clrPixIn, copyClks, DemoStatData::count, cpReq, cpuRdReq, cpuWrReq, DEMO_STAT_FR, DEMO_STAT_GP0, DEMO_STAT_GP1, DEMO_STAT_MEM, DEMO_STAT_MYC, DEMO_STAT_MYR, DEMO_STAT_PIX, DEMO_STAT_TBP, DEMO_STAT_TBW, DEMO_STAT_VC, DemoStat, DemoStatClocks, DemoStatIndx, dspReq, fiReq, GXClearGPMetric, GXClearMemMetric, GXClearPixMetric, GXClearVCacheMetric, GXReadGP0Metric, GXReadGP1Metric, GXReadMemMetric, GXReadPixMetric, GXReadVCacheMetric, GXSetGPMetric, GXSetVCacheMetric, ioReq, OSPanic, peReq, rfReq, tcReq, topPixIn, topPixOut, vcCheck, vcMiss, vcStall, viReq.
Referenced by DEMOUpdateStats.
void DEMOSetStats(DemoStatData *stat, u32 nstats, DEMO_STAT_DISP disp)
References CARD_MAX_MOUNT_STEP, DemoStat, DemoStatDisp, DemoStatEnable, DemoStatIndx, DemoStatMaxIndx, DemoStatStrLen, FALSE, DemoStatData::text, TRUE.
void DEMOUpdateStats(u16 inc)
References CARD_MAX_MOUNT_STEP, DemoStatIndx, DemoStatMaxIndx, DEMOWriteStats.
Referenced by DEMODoneRender.
void DEMOPrintStats(void)
References botPixIn, botPixOut, CARD_MAX_MOUNT_STEP, clrPixIn, copyClks, cpReq, cpuRdReq, cpuWrReq, DEMO_STAT_BL, DEMO_STAT_BLD, DEMO_STAT_FR, DEMO_STAT_GP0, DEMO_STAT_GP1, DEMO_STAT_IO, DEMO_STAT_MEM, DEMO_STAT_MYC, DEMO_STAT_MYR, DEMO_STAT_PIX, DEMO_STAT_TBP, DEMO_STAT_TBW, DEMO_STAT_TL, DEMO_STAT_TLD, DEMO_STAT_VC, DEMOGetRenderModeObj, DEMOInitCaption, DEMOPrintf, DemoStat, DemoStatClocks, DemoStatDisp, DemoStatMaxIndx, dspReq, _GXRenderModeObj::fbWidth, fiReq, ioReq, OSReport, peReq, rfReq, rmode, DemoStatData::stat, tcReq, topPixIn, topPixOut, vcCheck, vcMiss, vcStall, viReq, _GXRenderModeObj::xfbHeight.
Referenced by DEMODoneRender.