DEMOWin.c
u32 __DEMOWIN_PAD_repeat_threshold
Referenced by DEMOWinPadRead, DEMOWinResetRepeat, DEMOWinSetRepeat.
u32 __DEMOWIN_PAD_repeat_rate
Referenced by DEMOWinPadRead, DEMOWinResetRepeat, DEMOWinSetRepeat.
struct STRUCT_DEMOWIN* __first_node
Referenced by __DEMOWin_add_node, __DEMOWin_delete_node, DEMOWinBringToFront, DEMOWinInit, DEMOWinRefresh.
struct STRUCT_DEMOWIN* __last_node
Referenced by __DEMOWin_add_node, __DEMOWin_delete_node, DEMOWinInit.
struct STRUCT_DEMOWIN* __curr_node
Referenced by __DEMOWin_add_node, DEMOWinInit.
struct _GXRenderModeObj* __rmp
Referenced by DEMOWinInit, DEMOWinRefresh.
s32 fontShift
Referenced by __DEMOWin_puts_n.
static void __DEMOWin_add_node(struct STRUCT_DEMOWIN *handle)
References __curr_node, __first_node, __last_node, CARD_MAX_MOUNT_STEP, DEMOWIN_FLAGS_INIT, STRUCT_DEMOWIN::flags, STRUCT_DEMOWIN::next, NULL, STRUCT_DEMOWIN::prev.
Referenced by DEMOWinCreateWindow.
static void __DEMOWin_delete_node(struct STRUCT_DEMOWIN *handle)
References __first_node, __last_node, CARD_MAX_MOUNT_STEP, DEMOWIN_FLAGS_INIT, STRUCT_DEMOWIN::flags, STRUCT_DEMOWIN::next, NULL, STRUCT_DEMOWIN::prev.
Referenced by DEMOWinDestroyWindow.
static void __DEMOWin_puts_n(s16 x, s16 y, s16 z, u16 n, char *string)
Referenced by DEMOWinRefresh.
static void __DEMOWinMenu_refesh_menu(struct STRUCT_DEMOWIN *w)
References CARD_MAX_MOUNT_STEP, DEMOWinClearWindow, DEMOWinPrintfXY, NULL, STRUCT_DEMOWIN::parent.
Referenced by DEMOWinCreateMenuWindow.
static u16 __DEMOWinMenu_get_user_input(DEMOWinPadInfo *p)
References CARD_MAX_MOUNT_STEP, DEMOWinPadRead.
Referenced by DEMOWinMenuChild.
static void __DEMOWinList_refresh_list(struct STRUCT_DEMOWIN *w)
References CARD_MAX_MOUNT_STEP, STRUCT_LISTBOX::curr_pos, STRUCT_DEMOWIN::cursor_line, STRUCT_LISTBOX::cursor_state, DEMOWinClearWindow, DEMOWinPrintfXY, STRUCT_LISTBOX::display_pos, STRUCT_LISTBOX_ITEM::flags, STRUCT_LISTBOX::items, STRUCT_LISTBOX_ITEM::name, STRUCT_LISTBOX::num_display_items, STRUCT_LISTBOX::num_items, STRUCT_DEMOWIN::parent.
Referenced by DEMOWinCreateListWindow.
void DEMOWinInit()
References __curr_node, __first_node, __last_node, __rmp, DEMOGetRenderModeObj, GXSetCopyClear, NULL.
struct STRUCT_DEMOWIN * DEMOWinCreateWindow(s32 x1, s32 y1, s32 x2, s32 y2, char *caption, u16 scroll, void *func)
References __DEMOWin_add_node, __OSCurrHeap, STRUCT_DEMOWIN::buffer, STRUCT_DEMOWIN::caption, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::char_height, STRUCT_DEMOWIN::char_width, STRUCT_DEMOWIN::curr_output_col, STRUCT_DEMOWIN::curr_output_line, STRUCT_DEMOWIN::curr_view_line, STRUCT_DEMOWIN::cursor_line, DEMOWinSetWindowColor, STRUCT_DEMOWIN::flags, STRUCT_DEMOWIN::num_scroll_lines, OSAllocFromHeap, STRUCT_DEMOWIN::parent, STRUCT_DEMOWIN::pixel_height, STRUCT_DEMOWIN::pixel_width, STRUCT_DEMOWIN::priority, STRUCT_DEMOWIN::refresh, STRUCT_DEMOWIN::total_lines, STRUCT_DEMOWIN::x1, STRUCT_DEMOWIN::x2, STRUCT_DEMOWIN::x_cal, STRUCT_DEMOWIN::y1, STRUCT_DEMOWIN::y2, STRUCT_DEMOWIN::y_cal.
Referenced by DEMOWinCreateListWindow, DEMOWinCreateMenuWindow.
void DEMOWinDestroyWindow(struct STRUCT_DEMOWIN *handle)
References __DEMOWin_delete_node, __OSCurrHeap, STRUCT_DEMOWIN::buffer, CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSFreeToHeap, OSRestoreInterrupts.
Referenced by DEMOWinDestroyListWindow, DEMOWinDestroyMenuWindow.
void DEMOWinOpenWindow(struct STRUCT_DEMOWIN *handle)
References CARD_MAX_MOUNT_STEP, DEMOWIN_FLAGS_OPENED, STRUCT_DEMOWIN::flags.
Referenced by DEMOWinMenuChild.
void DEMOWinCloseWindow(struct STRUCT_DEMOWIN *handle)
References CARD_MAX_MOUNT_STEP, DEMOWIN_FLAGS_OPENED, STRUCT_DEMOWIN::flags.
Referenced by DEMOWinDestroyListWindow, DEMOWinDestroyMenuWindow, DEMOWinMenuChild.
void DEMOWinSetWindowColor(struct STRUCT_DEMOWIN *handle, enum DEMOWinItem item, u8 r, u8 g, u8 b, u8 a)
References _GXColor::a, _GXColor::b, STRUCT_DEMOWIN::bkgnd, STRUCT_DEMOWIN::border, STRUCT_DEMOWIN::cap, CARD_MAX_MOUNT_STEP, DEMOWIN_ITEM_BKGND, DEMOWIN_ITEM_BORDER, DEMOWIN_ITEM_CAP, DEMOWIN_ITEM_DEFAULT, FALSE, _GXColor::g, _GXColor::r.
Referenced by DEMOWinCreateWindow.
void DEMOWinLogPrintf(struct STRUCT_DEMOWIN *handle, char *fmt,...)
References STRUCT_DEMOWIN::buffer, buffer, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::char_width, STRUCT_DEMOWIN::curr_output_col, STRUCT_DEMOWIN::curr_output_line, STRUCT_DEMOWIN::curr_view_line, index, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DEMOWIN::total_lines.
void DEMOWinPrintfXY(struct STRUCT_DEMOWIN *handle, u16 col, u16 row, char *fmt,...)
References STRUCT_DEMOWIN::buffer, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::char_height, STRUCT_DEMOWIN::char_width, STRUCT_DEMOWIN::curr_view_line, index, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DEMOWIN::total_lines.
Referenced by __DEMOWinList_refresh_list, __DEMOWinMenu_refesh_menu.
void DEMOWinScrollWindow(struct STRUCT_DEMOWIN *handle, u32 dir)
References CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::char_height, STRUCT_DEMOWIN::curr_output_line, STRUCT_DEMOWIN::curr_view_line, FALSE, STRUCT_DEMOWIN::num_scroll_lines, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DEMOWIN::total_lines.
void DEMOWinBringToFront(struct STRUCT_DEMOWIN *handle)
References __first_node, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::next, STRUCT_DEMOWIN::priority.
Referenced by DEMOWinMenuChild.
void DEMOWinSendToBack(struct STRUCT_DEMOWIN *handle)
References CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::priority.
void DEMOWinClearRow(struct STRUCT_DEMOWIN *handle, u16 row)
References STRUCT_DEMOWIN::buffer, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::char_height, STRUCT_DEMOWIN::char_width, STRUCT_DEMOWIN::curr_view_line, index, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DEMOWIN::total_lines.
void DEMOWinClearWindow(struct STRUCT_DEMOWIN *handle)
References STRUCT_DEMOWIN::buffer, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::char_height, STRUCT_DEMOWIN::char_width, STRUCT_DEMOWIN::curr_view_line, index, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DEMOWIN::total_lines.
Referenced by __DEMOWinList_refresh_list, __DEMOWinMenu_refesh_menu.
void DEMOWinClearBuffer(struct STRUCT_DEMOWIN *handle)
References STRUCT_DEMOWIN::buffer, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::char_width, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DEMOWIN::total_lines.
void DEMOWinRefresh()
References __DEMOWin_puts_n, __first_node, __rmp, CARD_MAX_MOUNT_STEP, DEMOInitCaption, DEMOPrintf, DEMOWIN_FLAGS_OPENED, _GXRenderModeObj::efbHeight, _GXRenderModeObj::fbWidth, GXBegin, GXClearVtxDesc, GXEnd, GXSetBlendMode, GXSetChanCtrl, GXSetLineWidth, GXSetNumChans, GXSetNumTevStages, GXSetNumTexGens, GXSetTevOp, GXSetTevOrder, GXSetVtxAttrFmt, GXSetVtxDesc, GXSetZMode, index, STRUCT_DEMOWIN::next, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by DEMOWinMenuChild.
static void __DEMOWin_puts_n(s16 x, signed s16 y, signed short z, u16 n, char *string)
References CARD_MAX_MOUNT_STEP, fontShift, GXBegin, GXClearVtxDesc, GXEnd, GXSetVtxAttrFmt, GXSetVtxDesc.
struct STRUCT_MENU * DEMOWinCreateMenuWindow(struct STRUCT_MENU *menu, u16 x, u16 y)
References __DEMOWinMenu_refesh_menu, CARD_MAX_MOUNT_STEP, DEMOWinCreateWindow, NULL.
Referenced by DEMOWinMenuChild.
void DEMOWinDestroyMenuWindow(struct STRUCT_MENU *menu)
References CARD_MAX_MOUNT_STEP, DEMOWinCloseWindow, DEMOWinDestroyWindow.
Referenced by DEMOWinMenuChild.
u32 DEMOWinMenuChild(struct STRUCT_MENU *menu, int child_flag)
References __DEMOWinMenu_get_user_input, CARD_MAX_MOUNT_STEP, STRUCT_DEMOWIN::cursor_line, DEMOBeforeRender, DEMODoneRender, DEMOWinBringToFront, DEMOWinCloseWindow, DEMOWinCreateMenuWindow, DEMOWinDestroyMenuWindow, DEMOWinMenuChild, DEMOWinOpenWindow, DEMOWinPadInit, DEMOWinPadRead, DEMOWinRefresh, VIWaitForRetrace, STRUCT_DEMOWIN::x1, STRUCT_DEMOWIN::y1.
Referenced by DEMOWinMenuChild.
void DEMOWinPadInit(DEMOWinPadInfo *p)
References CARD_MAX_MOUNT_STEP.
Referenced by DEMOWinMenuChild.
void DEMOWinPadRead(DEMOWinPadInfo *p)
References __DEMOWIN_PAD_repeat_rate, __DEMOWIN_PAD_repeat_threshold, PADStatus::button, CARD_MAX_MOUNT_STEP, index, PADRead, PADStatus::stickX, PADStatus::stickY, PADStatus::substickX, PADStatus::substickY, PADStatus::triggerLeft, PADStatus::triggerRight.
Referenced by __DEMOWinMenu_get_user_input, DEMOWinMenuChild.
void DEMOWinSetRepeat(u32 threshold, u32 rate)
References __DEMOWIN_PAD_repeat_rate, __DEMOWIN_PAD_repeat_threshold, CARD_MAX_MOUNT_STEP.
void DEMOWinResetRepeat()
References __DEMOWIN_PAD_repeat_rate, __DEMOWIN_PAD_repeat_threshold.
struct STRUCT_LISTBOX * DEMOWinCreateListWindow(struct STRUCT_LISTBOX *list, u16 x, u16 y)
References __DEMOWinList_refresh_list, CARD_MAX_MOUNT_STEP, DEMOWinCreateWindow, NULL.
void DEMOWinDestroyListWindow(struct STRUCT_LISTBOX *list)
References CARD_MAX_MOUNT_STEP, DEMOWinCloseWindow, DEMOWinDestroyWindow.
void DEMOWinListSetCursor(struct STRUCT_LISTBOX *list, int x)
References CARD_MAX_MOUNT_STEP.
s32 DEMOWinListScrollList(struct STRUCT_LISTBOX *list, u32 dir)
References CARD_MAX_MOUNT_STEP, FALSE.
s32 DEMOWinListMoveCursor(struct STRUCT_LISTBOX *list, u32 dir)
References CARD_MAX_MOUNT_STEP, FALSE.