DebuggerDriver.c
DB_NO_ERROR
DB_STAT_SEND
DB_STAT_RECIEVE
ODEMU_NO_ERROR
ODEMU_ERROR
ODEMU_ADDR_RECV
ODEMU_OFFSET_RECV
ODEMU_MAIL_MAGIC
ODEMU_MAIL_MASK
ODEMU_ERROR
typedef void(* DBGCallbackType) (u32, OSContext *))(u32, OSContext *)
u8 EXIInputFlag
Referenced by CheckMailBox, DBInitComm, DBQueryData, DBRead, MWCallback.
u8* pEXIInputFlag
Referenced by DBInitComm.
s32 RecvDataLeng
Referenced by CheckMailBox, DBQueryData, DBRead.
u32 SendMailData
Referenced by CheckMailBox, DBRead.
DBGCallbackType DBGCallback
Referenced by DBGHandler, DBInitInterrupts.
MTRCallbackType MTRCallback
Referenced by DBInitComm, MWCallback.
void DBGEXIClearInterrupts(void)
References CARD_MAX_MOUNT_STEP, SI_EXILK.
Referenced by DBGEXIInit.
void DBGEXIInit(void)
References __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, DBGEXIClearInterrupts, EXI_C2_SR, OS_INTERRUPTMASK_EXI_2.
Referenced by DBInitComm.
BOOL DBGEXISelect(u32 v)
References CARD_MAX_MOUNT_STEP, EXI_C2_SR, ODEMU_NO_ERROR, regs.
Referenced by DBGRead, DBGReadMailbox, DBGReadStatus, DBGWrite, DBGWriteMailbox.
BOOL DBGEXIDeselect(void)
References CARD_MAX_MOUNT_STEP, EXI_C2_SR, ODEMU_NO_ERROR.
Referenced by DBGRead, DBGReadMailbox, DBGReadStatus, DBGWrite, DBGWriteMailbox.
BOOL DBGEXISync(void)
References CARD_MAX_MOUNT_STEP, EXI_C2_CR, ODEMU_NO_ERROR.
Referenced by DBGEXIImm, DBGRead, DBGReadMailbox, DBGReadStatus, DBGWrite, DBGWriteMailbox.
BOOL DBGEXIImm(const void *data, s32 size, u32 mode)
References CARD_MAX_MOUNT_STEP, DBGEXISync, ODEMU_NO_ERROR, size.
Referenced by DBGRead, DBGReadMailbox, DBGReadStatus, DBGWrite, DBGWriteMailbox.
BOOL DBGWriteMailbox(u32 v)
References CARD_MAX_MOUNT_STEP, DBGEXIDeselect, DBGEXIImm, DBGEXISelect, DBGEXISync, FALSE, ODEMU_ERROR.
Referenced by DBWrite.
BOOL DBGReadMailbox(u32 *v)
References CARD_MAX_MOUNT_STEP, DBGEXIDeselect, DBGEXIImm, DBGEXISelect, DBGEXISync, FALSE, ODEMU_ERROR.
Referenced by CheckMailBox.
BOOL DBGRead(u32 addr, const u32 *data, s32 byte_size)
References CARD_MAX_MOUNT_STEP, DBGEXIDeselect, DBGEXIImm, DBGEXISelect, DBGEXISync, FALSE, ODEMU_ERROR.
Referenced by DBRead.
BOOL DBGWrite(u32 addr, const void *data, s32 size)
References CARD_MAX_MOUNT_STEP, DBGEXIDeselect, DBGEXIImm, DBGEXISelect, DBGEXISync, FALSE, ODEMU_ERROR, size.
Referenced by DBWrite.
BOOL DBGReadStatus(u32 *status)
References DBGEXIDeselect, DBGEXIImm, DBGEXISelect, DBGEXISync, FALSE, ODEMU_ERROR, status.
Referenced by CheckMailBox, DBWrite.
void MWCallback(u32 a, OSContext *b)
References EXIInputFlag, MTRCallback, NULL, TRUE.
Referenced by DBInitInterrupts.
void DBGHandler(s16 a, OSContext *b)
References CARD_MAX_MOUNT_STEP, DBGCallback, NULL, PI_INTSR.
Referenced by DBInitInterrupts.
void DBInitComm(u8 **a, MTRCallbackType b)
References CARD_MAX_MOUNT_STEP, DBGEXIInit, EXIInputFlag, MTRCallback, OSDisableInterrupts, OSRestoreInterrupts, pEXIInputFlag.
void DBInitInterrupts(void)
References __OS_INTERRUPT_PI_DEBUG, __OSMaskInterrupts, __OSSetInterruptHandler, __OSUnmaskInterrupts, DBGCallback, DBGHandler, MWCallback, OS_INTERRUPTMASK_EXI_2, OS_INTERRUPTMASK_PI_DEBUG.
void CheckMailBox(void)
References DBGReadMailbox, DBGReadStatus, EXIInputFlag, ODEMU_MAIL_MAGIC, ODEMU_MAIL_MASK, RecvDataLeng, SendMailData.
Referenced by DBQueryData.
s32 DBQueryData()
References CARD_MAX_MOUNT_STEP, CheckMailBox, EXIInputFlag, FALSE, OSDisableInterrupts, OSRestoreInterrupts, RecvDataLeng.
BOOL DBRead(const u32 *data, s32 size)
References CARD_MAX_MOUNT_STEP, DB_NO_ERROR, DBGRead, EXIInputFlag, ODEMU_ADDR_RECV, ODEMU_OFFSET_RECV, OSDisableInterrupts, OSRestoreInterrupts, RecvDataLeng, SendMailData, size.
BOOL DBWrite(const s32 *data, u32 size)
References CARD_MAX_MOUNT_STEP, DB_NO_ERROR, DB_STAT_RECIEVE, DBGReadStatus, DBGWrite, DBGWriteMailbox, ODEMU_MAIL_MAGIC, OSDisableInterrupts, OSRestoreInterrupts, size.
void DBOpen(void)
void DBClose(void)