GXTev.h
void GXSetTevOp(GXTevStageID id, GXTevMode mode)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_BLEND, GX_CA_APREV, GX_CA_RASA, GX_CA_TEXA, GX_CA_ZERO, GX_CC_CPREV, GX_CC_ONE, GX_CC_RASC, GX_CC_TEXA, GX_CC_TEXC, GX_CC_ZERO, GX_CS_SCALE_1, GX_DECAL, GX_MODULATE, GX_PASSCLR, GX_REPLACE, GX_TB_ZERO, GX_TEV_ADD, GX_TEVPREV, GX_TEVSTAGE0, GX_TRUE, GXSetTevAlphaIn, GXSetTevAlphaOp, GXSetTevColorIn, GXSetTevColorOp.
Referenced by DEMOInitCaption, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GXInit, PERFPreDraw.
void GXSetTevColorIn(GXTevStageID stage, GXTevColorArg a, GXTevColorArg b, GXTevColorArg c, GXTevColorArg d)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::tevc.
Referenced by DEMOSetTevColorIn, DEMOSetTevOp, GXSetTevOp.
void GXSetTevAlphaIn(GXTevStageID stage, GXTevAlphaArg a, GXTevAlphaArg b, GXTevAlphaArg c, GXTevAlphaArg d)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::teva.
Referenced by DEMOSetTevOp, GXSetTevOp.
void GXSetTevColorOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp, GXTevRegID out_reg)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::tevc.
Referenced by DEMOSetTevOp, GXSetTevOp.
void GXSetTevAlphaOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp, GXTevRegID out_reg)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::teva.
Referenced by DEMOSetTevOp, GXSetTevOp.
void GXSetTevColor(GXTevRegID id, GXColor color)
References __GXData, _GXColor::a, _GXColor::b, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, _GXColor::g, GX_WRITE_RAS_REG, _GXColor::r, SET_REG_FIELD.
void GXSetTevColorS10(GXTevRegID id, GXColorS10 color)
References __GXData, _GXColorS10::a, _GXColorS10::b, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, _GXColorS10::g, GX_WRITE_RAS_REG, _GXColorS10::r, SET_REG_FIELD.
void GXSetTevKColor(GXTevKColorID id, GXColor color)
References __GXData, _GXColor::a, _GXColor::b, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, _GXColor::g, GX_WRITE_RAS_REG, _GXColor::r, SET_REG_FIELD.
void GXSetTevKColorSel(GXTevStageID stage, GXTevKColorSel sel)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::tevKsel.
Referenced by GXInit.
void GXSetTevKAlphaSel(GXTevStageID stage, GXTevKAlphaSel sel)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::tevKsel.
Referenced by GXInit.
void GXSetTevSwapMode(GXTevStageID stage, GXTevSwapSel ras_sel, GXTevSwapSel tex_sel)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::teva.
Referenced by DEMOSetTevColorIn, GXInit.
void GXSetTevSwapModeTable(GXTevSwapSel table, GXTevColorChan red, GXTevColorChan green, GXTevColorChan blue, GXTevColorChan alpha)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::tevKsel.
Referenced by GXInit.
void GXSetTevClampMode(void)
References CARD_MAX_MOUNT_STEP.
void GXSetAlphaCompare(GXCompare comp0, u8 ref0, GXAlphaOp op, GXCompare comp1, u8 ref1)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXSetZTexture(GXZTexOp op, GXTexFmt fmt, u32 bias)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_TF_Z16, GX_TF_Z24X8, GX_TF_Z8, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXSetTevOrder(GXTevStageID stage, GXTexCoordID coord, GXTexMapID map, GXChannelID color)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, GX_COLOR_NULL, GX_MAX_TEXCOORD, GX_MAX_TEXMAP, GX_TEXCOORD0, GX_TEXMAP0, GX_TEXMAP_NULL, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::texmapId, __GXData_struct::tref.
Referenced by DEMOInitCaption, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GXInit, PERFPreDraw.
void GXSetNumTevStages(u8 nStages)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::genMode, SET_REG_FIELD.
Referenced by DEMOInitCaption, DEMOWinRefresh, GXInit, PERFPreDraw.