GXDraw.c
GXVtxDescList vcd[27][27]
Referenced by GetVertState, GXGetVtxDescv, RestoreVertState.
GXVtxAttrFmtList vat[27][27]
Referenced by GetVertState, GXGetVtxAttrFmtv, RestoreVertState.
u32 polygons[12][5][12][5]
Referenced by GXDrawDodeca.
f32 verts[20][3][20][3]
Referenced by GXDrawDodeca.
f32 odata[6][3][6][3]
Referenced by GXDrawOctahedron, GXGenNormalTable.
u8 ondex[8][3][8][3]
Referenced by GXDrawOctahedron, GXGenNormalTable.
f32 idata[12][3][12][3]
Referenced by GXDrawIcosahedron, GXDrawSphere1.
u8 index[20][3][20][3]
Referenced by DEMOWinClearRow, DEMOWinClearWindow, DEMOWinLogPrintf, DEMOWinPadRead, DEMOWinPrintfXY, DEMOWinRefresh, DSHTableHead, GXDrawIcosahedron, GXDrawSphere1, SearchFreeBlocks.
u32 nrm_cnt
Referenced by AddNormal, GXGenNormalTable.
f32* nrm_tab
Referenced by AddNormal, GXGenNormalTable.
static void GetVertState(void)
References GX_DIRECT, GX_F32, GX_NRM_XYZ, GX_POS_XYZ, GX_VA_NRM, GX_VA_POS, GX_VTXFMT3, GXClearVtxDesc, GXGetVtxAttrFmtv, GXGetVtxDescv, GXSetVtxAttrFmt, GXSetVtxDesc, vat, vcd.
Referenced by GXDrawCube, GXDrawCylinder, GXDrawDodeca, GXDrawIcosahedron, GXDrawOctahedron, GXDrawSphere, GXDrawSphere1, GXDrawTorus.
static void RestoreVertState(void)
References GX_VTXFMT3, GXSetVtxAttrFmtv, GXSetVtxDescv, vat, vcd.
Referenced by GXDrawCube, GXDrawCylinder, GXDrawDodeca, GXDrawIcosahedron, GXDrawOctahedron, GXDrawSphere, GXDrawSphere1, GXDrawTorus.
static void vsub(f32 p1[3], f32 p2[3], f32 u[3])
References CARD_MAX_MOUNT_STEP.
Referenced by GXDrawDodeca.
static void vcross(f32 u[3], f32 v[3], f32 n[3])
References CARD_MAX_MOUNT_STEP.
Referenced by GXDrawDodeca.
static void normalize(f32 v[3])
References CARD_MAX_MOUNT_STEP.
Referenced by GXDrawDodeca, GXSetTexCoordGen2, Subdivide, SubdivideNrm.
static void myvertex(f32 v[3], f32 n[3])
References CARD_MAX_MOUNT_STEP.
Referenced by DumpTriangle, GXDrawDodeca.
static void DumpTriangle(f32 v0[3], f32 v1[3], f32 v2[3])
References CARD_MAX_MOUNT_STEP, GX_TRIANGLES, GX_VTXFMT3, GXBegin, GXEnd, myvertex.
Referenced by Subdivide.
static void Subdivide(u8 depth, f32 v0[3], f32 v1[3], f32 v2[3])
References CARD_MAX_MOUNT_STEP, DumpTriangle, normalize, Subdivide.
Referenced by Subdivide, SubDivTriangle.
static void SubDivTriangle(u8 depth, u8 i, f32(*data)[3], u8(*ndx)[3])
References CARD_MAX_MOUNT_STEP, Subdivide.
Referenced by GXDrawIcosahedron, GXDrawOctahedron, GXDrawSphere1.
void GXDrawCylinder(u8 numEdges)
References CARD_MAX_MOUNT_STEP, cosf, GetVertState, GX_TRIANGLEFAN, GX_TRIANGLESTRIP, GX_VTXFMT3, GXBegin, GXEnd, RestoreVertState, sinf.
void GXDrawTorus(f32 rc, u8 numc, u8 numt)
References CARD_MAX_MOUNT_STEP, cosf, GetVertState, GX_DIRECT, GX_F32, GX_NONE, GX_TEX_ST, GX_TRIANGLESTRIP, GX_VA_TEX0, GX_VTXFMT3, GXBegin, GXEnd, GXGetVtxDesc, GXSetVtxAttrFmt, GXSetVtxDesc, RestoreVertState, sinf.
void GXDrawSphere(u8 numMajor, u8 numMinor)
References CARD_MAX_MOUNT_STEP, cosf, GetVertState, GX_DIRECT, GX_NONE, GX_RGBA6, GX_TEX_ST, GX_TRIANGLESTRIP, GX_VA_TEX0, GX_VTXFMT3, GXBegin, GXEnd, GXGetVtxDesc, GXSetVtxAttrFmt, GXSetVtxDesc, RestoreVertState, sinf.
static void GXDrawCubeFace(f32 nx, f32 ny, f32 nz, f32 tx, f32 ty, f32 tz, f32 bx, f32 by, f32 bz, GXAttrType binormal, GXAttrType texture)
References CARD_MAX_MOUNT_STEP, GX_NONE.
Referenced by GXDrawCube.
void GXDrawCube(void)
References CARD_MAX_MOUNT_STEP, GetVertState, GX_DIRECT, GX_NONE, GX_QUADS, GX_RGB8, GX_RGBA6, GX_TEX_ST, GX_VA_NBT, GX_VA_TEX0, GX_VTXFMT3, GXBegin, GXDrawCubeFace, GXEnd, GXGetVtxDesc, GXSetVtxAttrFmt, GXSetVtxDesc, RestoreVertState.
void GXDrawDodeca(void)
References CARD_MAX_MOUNT_STEP, GetVertState, GX_TRIANGLEFAN, GX_VTXFMT3, GXBegin, GXEnd, myvertex, normalize, polygons, RestoreVertState, vcross, verts, vsub.
void GXDrawOctahedron(void)
References CARD_MAX_MOUNT_STEP, GetVertState, odata, ondex, RestoreVertState, SubDivTriangle.
void GXDrawIcosahedron(void)
References CARD_MAX_MOUNT_STEP, GetVertState, idata, index, RestoreVertState, SubDivTriangle.
void GXDrawSphere1(u8 depth)
References CARD_MAX_MOUNT_STEP, GetVertState, idata, index, RestoreVertState, SubDivTriangle.
static u32 CmpNormal32(f32 n1[3], f32 n2[3])
References CARD_MAX_MOUNT_STEP, FALSE, TRUE.
Referenced by AddNormal.
static void AddNormal(f32 n[3])
References CARD_MAX_MOUNT_STEP, CmpNormal32, nrm_cnt, nrm_tab.
Referenced by SubdivideNrm.
static void SubdivideNrm(u8 depth, f32 v0[3], f32 v1[3], f32 v2[3])
References AddNormal, CARD_MAX_MOUNT_STEP, normalize, SubdivideNrm.
Referenced by SubdivideNrm, SubDivNrm.
static void SubDivNrm(u8 depth, u8 i, f32(*data)[3], u8(*ndx)[3])
References CARD_MAX_MOUNT_STEP, SubdivideNrm.
Referenced by GXGenNormalTable.
u32 GXGenNormalTable(u8 depth, f32 *table)
References CARD_MAX_MOUNT_STEP, nrm_cnt, nrm_tab, odata, ondex, SubDivNrm.