GXTransform.c
qr0
GX_WRITE_MTX_ELEM
SET_REG_FIELD_
void GXProject(f32 x, f32 y, f32 z, f32 mtx[3][4], f32 *pm, f32 *vp, f32 *sx, f32 *sy, f32 *sz)
References CARD_MAX_MOUNT_STEP.
void GXSetProjection(f32 mtx[4][4], GXProjectionType type)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_ORTHOGRAPHIC, GX_WRITE_U32, GX_WRITE_U8, GX_WRITE_XF_REG_2, GX_WRITE_XF_REG_F, __GXData_struct::projMtx, __GXData_struct::projType.
Referenced by DEMOSetupScrnSpc, G2DInitWorld, PERFPostDraw, PERFPreDraw.
void GXSetProjectionv(f32 *ptr)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_U32, GX_WRITE_U8, GX_WRITE_XF_REG_2, GX_WRITE_XF_REG_F, __GXData_struct::projMtx, __GXData_struct::projType.
void GXGetProjectionv(f32 *ptr)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::projMtx, __GXData_struct::projType.
Referenced by PERFPreDraw.
static asm void WriteMTXPS4x3(register f32 mtx[3][4], register volatile f32 *dest)
References CARD_MAX_MOUNT_STEP, qr0.
Referenced by GXLoadPosMtxImm, GXLoadTexMtxImm.
static asm void WriteMTXPS3x3from3x4(register f32 mtx[3][4], register volatile f32 *dest)
References CARD_MAX_MOUNT_STEP, qr0.
Referenced by GXLoadNrmMtxImm.
static asm void WriteMTXPS3x3(register f32 mtx[3][3], register volatile f32 *dest)
References CARD_MAX_MOUNT_STEP, qr0.
Referenced by GXLoadNrmMtxImm3x3.
static asm void WriteMTXPS4x2(register f32 mtx[2][4], register volatile f32 *dest)
References CARD_MAX_MOUNT_STEP, qr0.
Referenced by GXLoadTexMtxImm.
void GXLoadPosMtxImm(f32 mtx[3][4], u32 id)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, uPPCWGPipe::f32, GX_WRITE_MTX_ELEM, GX_WRITE_U32, GX_WRITE_U8, GXWGFifo, WriteMTXPS4x3.
Referenced by DEMOSetupScrnSpc, G2DSetCamera, GXInit, PERFDumpScreen.
void GXLoadPosMtxIndx(u16 mtx_indx, u32 id)
References __GXShadowIndexState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_U32, GX_WRITE_U8, SET_REG_FIELD, SET_REG_FIELD_.
void GXLoadNrmMtxImm(f32 mtx[3][4], u32 id)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, uPPCWGPipe::f32, GX_WRITE_MTX_ELEM, GX_WRITE_U32, GX_WRITE_U8, GXWGFifo, WriteMTXPS3x3from3x4.
Referenced by GXInit.
void GXLoadNrmMtxImm3x3(f32 mtx[3][3], u32 id)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, uPPCWGPipe::f32, GX_WRITE_MTX_ELEM, GX_WRITE_U32, GX_WRITE_U8, GXWGFifo, WriteMTXPS3x3.
void GXLoadNrmMtxIndx3x3(u16 mtx_indx, u32 id)
References __GXShadowIndexState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_U32, GX_WRITE_U8, SET_REG_FIELD, SET_REG_FIELD_.
void GXSetCurrentMtx(u32 id)
References __GXData, __GXSetMatrixIndex, CHECK_GXBEGIN, GX_VA_PNMTXIDX, __GXData_struct::matIdxA, SET_REG_FIELD.
Referenced by DEMOSetupScrnSpc, GXInit.
void GXLoadTexMtxImm(f32 mtx[][4], u32 id, GXTexMtxType type)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, uPPCWGPipe::f32, GX_MTX2x4, GX_MTX3x4, GX_PTTEXMTX0, GX_WRITE_MTX_ELEM, GX_WRITE_U32, GX_WRITE_U8, GXWGFifo, WriteMTXPS4x2, WriteMTXPS4x3.
Referenced by DEMOLoadFont, GXInit, LoadSheet.
void GXLoadTexMtxIndx(u16 mtx_indx, u32 id, GXTexMtxType type)
References __GXShadowIndexState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_MTX2x4, GX_MTX3x4, GX_PTTEXMTX0, GX_WRITE_U32, GX_WRITE_U8, SET_REG_FIELD, SET_REG_FIELD_.
void GXSetViewportJitter(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz, u32 field)
References __GXData, __GXSetRange, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::fgRange, __GXData_struct::fgSideX, GX_WRITE_U32, GX_WRITE_U8, GX_WRITE_XF_REG_F, __GXData_struct::vpFarz, __GXData_struct::vpHt, __GXData_struct::vpLeft, __GXData_struct::vpNearz, __GXData_struct::vpTop, __GXData_struct::vpWd.
Referenced by DEMOBeforeRender, GXSetViewport.
void GXSetViewport(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz)
References CARD_MAX_MOUNT_STEP, GXSetViewportJitter.
Referenced by __DEMOInitGX, DEMOBeforeRender, GXInit.
void GXGetViewportv(f32 *vp)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::vpFarz, __GXData_struct::vpHt, __GXData_struct::vpLeft, __GXData_struct::vpNearz, __GXData_struct::vpTop, __GXData_struct::vpWd.
void GXSetScissor(u32 left, u32 top, u32 wd, u32 ht)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GXSetScissor.
Referenced by __DEMOInitGX, G2DSetViewport, GXInit, GXSetScissor.
void GXGetScissor(u32 *left, u32 *top, u32 *wd, u32 *ht)
void GXSetScissorBoxOffset(s32 x_off, s32 y_off)
Referenced by GXInit.
void GXSetClipMode(GXClipMode mode)
Referenced by GXInit.
void __GXSetMatrixIndex(GXAttr matIdxAttr)
Referenced by GXSetCurrentMtx, GXSetTexCoordGen2.