GXFifo.c
SOME_MACRO1
SOME_MACRO2
SET_REG_FIELD2
OSThread* __GXCurrentThread
Referenced by __GXFifoInit, GXGetCurrentGXThread, GXOverflowHandler, GXSetCurrentGXThread, GXUnderflowHandler.
GXBool CPGPLinked
Referenced by __GXSaveCPUFifoAux, GXRedirectWriteGatherPipe, GXSetCPUFifo, GXSetGPFifo.
BOOL GXOverflowSuspendInProgress
Referenced by __GXFifoInit, GXOverflowHandler, GXSetCurrentGXThread, GXUnderflowHandler.
GXBreakPtCallback BreakPointCB
Referenced by GXBreakPointHandler, GXSetBreakPtCallback.
u32 __GXOverflowCount
Referenced by GXGetOverflowCount, GXOverflowHandler, GXResetOverflowCount.
__GXFifoObj* CPUFifo
Referenced by GXBeginDisplayList, GXGetCPUFifo, GXGetFifoPtrs, GXGetFifoStatus, GXInitFifoBase, GXInitFifoPtrs, GXRedirectWriteGatherPipe, GXSaveCPUFifo, GXSetCPUFifo, GXSetGPFifo.
__GXFifoObj* GPFifo
Referenced by __GXInsaneWatermark, GXEnableBreakPt, GXGetFifoPtrs, GXGetFifoStatus, GXGetGPFifo, GXInitFifoBase, GXInitFifoLimits, GXInitFifoPtrs, GXSaveGPFifo, GXSetCPUFifo, GXSetGPFifo.
void * __GXCurrentBP
Referenced by GXDisableBreakPt, GXEnableBreakPt.
static void __GXFifoReadEnable(void)
References __GXData, __GXData_struct::cpEnable, GX_SET_CP_REG, SET_REG_FIELD.
Referenced by GXEnableBreakPt, GXSetGPFifo.
static void __GXFifoReadDisable(void)
References __GXData, __GXData_struct::cpEnable, GX_SET_CP_REG, SET_REG_FIELD.
Referenced by GXEnableBreakPt, GXSetGPFifo.
static void __GXFifoLink(u8 arg0)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::cpEnable, GX_SET_CP_REG, SET_REG_FIELD.
Referenced by GXRedirectWriteGatherPipe, GXSetCPUFifo, GXSetGPFifo.
static void __GXWriteFifoIntEnable(u8 arg0, u8 arg1)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::cpEnable, GX_SET_CP_REG, SET_REG_FIELD.
Referenced by GXOverflowHandler, GXRedirectWriteGatherPipe, GXSetCPUFifo, GXSetGPFifo, GXUnderflowHandler.
static void __GXWriteFifoIntReset(u8 arg0, u8 arg1)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::cpClr, GX_SET_CP_REG, SET_REG_FIELD.
Referenced by GXOverflowHandler, GXSetCPUFifo, GXSetGPFifo, GXUnderflowHandler.
static void GXOverflowHandler(s16 interrupt, OSContext *context)
References __GXCurrentThread, __GXOverflowCount, __gxVerif, __GXWriteFifoIntEnable, __GXWriteFifoIntReset, CARD_MAX_MOUNT_STEP, GXOverflowSuspendInProgress, OSReport, OSSuspendThread, TRUE, __GXVerifyData::verifyLevel.
Referenced by GXCPInterruptHandler.
static void GXUnderflowHandler(s16 interrupt, OSContext *context)
References __GXCurrentThread, __gxVerif, __GXWriteFifoIntEnable, __GXWriteFifoIntReset, CARD_MAX_MOUNT_STEP, FALSE, GXOverflowSuspendInProgress, OSReport, OSResumeThread, __GXVerifyData::verifyLevel.
Referenced by GXCPInterruptHandler.
static void GXBreakPointHandler(s16 interrupt, OSContext *context)
References __GXData, BreakPointCB, CARD_MAX_MOUNT_STEP, __GXData_struct::cpEnable, GX_SET_CP_REG, NULL, OSClearContext, OSSetCurrentContext.
Referenced by GXCPInterruptHandler.
static void GXCPInterruptHandler(s16 interrupt, OSContext *context)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::cpEnable, __GXData_struct::cpStatus, GET_REG_FIELD, GX_GET_CP_REG, GXBreakPointHandler, GXOverflowHandler, GXUnderflowHandler.
Referenced by __GXFifoInit.
void GXInitFifoBase(GXFifoObj *fifo, void *base, u32 size)
References CARD_MAX_MOUNT_STEP, CPUFifo, GPFifo, GXInitFifoLimits, GXInitFifoPtrs, NULL, size.
Referenced by DEMOReInit, GXInit.
void GXInitFifoPtrs(GXFifoObj *fifo, void *readPtr, void *writePtr)
References CARD_MAX_MOUNT_STEP, CPUFifo, GPFifo, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __GXCleanGPFifo, GXInitFifoBase.
void GXInitFifoLimits(GXFifoObj *fifo, u32 hiWatermark, u32 loWatermark)
References CARD_MAX_MOUNT_STEP, GPFifo, __GXFifoObj::hiWatermark, __GXFifoObj::loWatermark, __GXFifoObj::top.
Referenced by GXInitFifoBase.
void GXSetCPUFifo(GXFifoObj *fifo)
References __GXFifoLink, __GXWriteFifoIntEnable, __GXWriteFifoIntReset, CARD_MAX_MOUNT_STEP, CPGPLinked, CPUFifo, GPFifo, GX_FALSE, GX_SET_PI_REG, GX_TRUE, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by __GXCleanGPFifo, DEMOReInit, GXBeginDisplayList, GXEndDisplayList, GXInit.
void GXSetGPFifo(GXFifoObj *fifo)
References __GXFifoLink, __GXFifoReadDisable, __GXFifoReadEnable, __GXWriteFifoIntEnable, __GXWriteFifoIntReset, CARD_MAX_MOUNT_STEP, CPGPLinked, CPUFifo, GPFifo, GX_FALSE, GX_SET_CP_REG, GX_TRUE, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __GXCleanGPFifo, DEMOReInit, GXInit.
void GXSaveCPUFifo(GXFifoObj *fifo)
References __GXSaveCPUFifoAux, CARD_MAX_MOUNT_STEP, CPUFifo.
Referenced by GXBeginDisplayList.
void __GXSaveCPUFifoAux(__GXFifoObj *realFifo)
References CARD_MAX_MOUNT_STEP, CPGPLinked, GX_GET_PI_REG, GXFlush, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, SOME_MACRO1, SOME_MACRO2.
Referenced by GXEndDisplayList, GXGetFifoStatus, GXSaveCPUFifo.
void GXSaveGPFifo(GXFifoObj *fifo)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GPFifo, GX_GET_CP_REG, SOME_MACRO1, SOME_MACRO2.
void GXGetGPStatus(GXBool *overhi, GXBool *underlow, GXBool *readIdle, GXBool *cmdIdle, GXBool *brkpt)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::cpStatus, GET_REG_FIELD, GX_GET_CP_REG.
void GXGetFifoStatus(GXFifoObj *fifo, GXBool *overhi, GXBool *underflow, u32 *fifoCount, GXBool *cpuWrite, GXBool *gpRead, GXBool *fifowrap)
References __GXSaveCPUFifoAux, CARD_MAX_MOUNT_STEP, CPUFifo, GET_REG_FIELD, GPFifo, GX_FALSE, GX_GET_PI_REG, SOME_MACRO1, SOME_MACRO2.
void GXGetFifoPtrs(GXFifoObj *fifo, void **readPtr, void **writePtr)
References CARD_MAX_MOUNT_STEP, CPUFifo, GPFifo, GX_GET_PI_REG, OSPhysicalToCached, SOME_MACRO1, SOME_MACRO2.
void * GXGetFifoBase(GXFifoObj *fifo)
References __GXFifoObj::base, CARD_MAX_MOUNT_STEP.
Referenced by __GXCleanGPFifo, DEMOReInit.
u32 GXGetFifoSize(GXFifoObj *fifo)
References CARD_MAX_MOUNT_STEP, __GXFifoObj::size.
Referenced by DEMOReInit.
void GXGetFifoLimits(GXFifoObj *fifo, u32 *hi, u32 *lo)
References CARD_MAX_MOUNT_STEP, __GXFifoObj::hiWatermark.
GXBreakPtCallback GXSetBreakPtCallback(GXBreakPtCallback cb)
References BreakPointCB, CARD_MAX_MOUNT_STEP, cb, OSDisableInterrupts, OSRestoreInterrupts.
void GXEnableBreakPt(void *break_pt)
References __GXCurrentBP, __GXData, __GXFifoReadDisable, __GXFifoReadEnable, __GXFifoObj::base, CARD_MAX_MOUNT_STEP, __GXData_struct::cpEnable, GPFifo, GX_SET_CP_REG, OSDisableInterrupts, OSRestoreInterrupts, __GXFifoObj::top.
void GXDisableBreakPt(void)
References __GXCurrentBP, __GXData, __GXData_struct::cpEnable, GX_SET_CP_REG, NULL, OSDisableInterrupts, OSRestoreInterrupts.
void __GXFifoInit(void)
References __GXCurrentThread, __OSSetInterruptHandler, __OSUnmaskInterrupts, FALSE, GXCPInterruptHandler, GXOverflowSuspendInProgress, OSGetCurrentThread.
Referenced by GXInit.
void __GXInsaneWatermark(void)
References CARD_MAX_MOUNT_STEP, GPFifo, GX_SET_CP_REG, __GXFifoObj::hiWatermark.
void __GXCleanGPFifo(void)
References __GXFifoObj::base, CARD_MAX_MOUNT_STEP, GXGetCPUFifo, GXGetFifoBase, GXGetGPFifo, GXInitFifoPtrs, GXSetCPUFifo, GXSetGPFifo.
Referenced by GXAbortFrame.
OSThread * GXSetCurrentGXThread(void)
References __GXCurrentThread, CARD_MAX_MOUNT_STEP, GXOverflowSuspendInProgress, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, prev.
OSThread * GXGetCurrentGXThread(void)
References __GXCurrentThread.
GXFifoObj * GXGetCPUFifo(void)
References CPUFifo.
Referenced by __GXCleanGPFifo, DEMOReInit, GXBeginDisplayList.
GXFifoObj * GXGetGPFifo(void)
References GPFifo.
Referenced by __GXCleanGPFifo.
u32 GXGetOverflowCount(void)
References __GXOverflowCount.
u32 GXResetOverflowCount(void)
References __GXOverflowCount, CARD_MAX_MOUNT_STEP.
volatile void * GXRedirectWriteGatherPipe(void *ptr)
References __GXFifoLink, __GXWriteFifoIntEnable, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, CPGPLinked, CPUFifo, GX_GET_PI_REG, GX_SET_PI_REG, GXFIFO_ADDR, GXFlush, OFFSET, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, OSUncachedToPhysical, PPCMfwpar, PPCMtwpar, SET_REG_FIELD, TRUE, __GXFifoObj::wrPtr.