GXCpu2Efb.h
void GXPokeAlphaMode(GXCompare func, u8 threshold)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, PE_PI_ALPHA_THRESHOLD_ID.
Referenced by GXInit.
void GXPokeAlphaRead(GXAlphaReadMode mode)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeAlphaUpdate(GXBool update_enable)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeBlendMode(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor, GXLogicOp op)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_BM_BLEND, GX_BM_LOGIC, GX_BM_SUBTRACT, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeColorUpdate(GXBool update_enable)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeDstAlpha(GXBool enable, u8 alpha)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeDither(GXBool dither)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeZMode(GXBool compare_enable, GXCompare func, GXBool update_enable)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPeekARGB(u16 x, u16 y, u32 *color)
References OSPhysicalToUncached, SET_REG_FIELD.
void GXPokeARGB(u16 x, u16 y, u32 color)
References OSPhysicalToUncached, SET_REG_FIELD.
void GXPeekZ(u16 x, u16 y, u32 *z)
References OSPhysicalToUncached, SET_REG_FIELD.
void GXPokeZ(u16 x, u16 y, u32 z)
References OSPhysicalToUncached, SET_REG_FIELD.
u32 GXCompressZ16(u32 z24, GXZFmt16 zfmt)
References CARD_MAX_MOUNT_STEP, GX_ZC_FAR, GX_ZC_LINEAR, GX_ZC_MID, GX_ZC_NEAR, OSPanic.
u32 GXDecompressZ16(u32 z16, GXZFmt16 zfmt)
References CARD_MAX_MOUNT_STEP, GX_ZC_FAR, GX_ZC_LINEAR, GX_ZC_MID, GX_ZC_NEAR, OSPanic.