GXGeometry.c
void __GXSetDirtyState(void)
References __GXData, __GXSetGenMode, __GXSetSUTexRegs, __GXSetVAT, __GXSetVCD, __GXUpdateBPMask, __GXData_struct::dirtyState.
Referenced by GXBegin, GXBeginDisplayList, GXCallDisplayList, GXEndDisplayList, GXFlush.
void GXBegin(GXPrimitive type, GXVtxFmt vtxfmt, u16 nverts)
References __GXData, __GXSendFlushPrim, __GXSetDirtyState, __GXVerifyState, CARD_MAX_MOUNT_STEP, __GXData_struct::dirtyState, GX_WRITE_U16, GX_WRITE_U8, __GXData_struct::inDispList, __GXData_struct::vNum.
Referenced by __DEMOWin_puts_n, DEMOPuts, DEMOWinRefresh, DrawFontChar, DumpTriangle, G2DDrawLayer, G2DDrawSprite, GXDrawCube, GXDrawCylinder, GXDrawDodeca, GXDrawSphere, GXDrawTorus, PERFDumpScreen.
void __GXSendFlushPrim(void)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, GX_WRITE_U16, GX_WRITE_U32, GX_WRITE_U8, __GXData_struct::vLim, __GXData_struct::vNum.
Referenced by GXBegin, GXCallDisplayList.
void GXSetLineWidth(u8 width, GXTexOffset texOffsets)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, __GXData_struct::lpSize, SET_REG_FIELD.
Referenced by DEMOWinRefresh, GXInit, PERFDumpScreen.
void GXGetLineWidth(u8 *width, GXTexOffset *texOffsets)
References __GXData, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, __GXData_struct::lpSize, NULL.
void GXSetPointSize(u8 pointSize, GXTexOffset texOffsets)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, __GXData_struct::lpSize, SET_REG_FIELD.
Referenced by GXInit.
void GXGetPointSize(u8 *pointSize, GXTexOffset *texOffsets)
References __GXData, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, __GXData_struct::lpSize, NULL.
void GXEnableTexOffsets(GXTexCoordID coord, u8 line_enable, u8 point_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0.
Referenced by GXInit.
void GXSetCullMode(GXCullMode mode)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::genMode, GX_CULL_BACK, GX_CULL_FRONT, SET_REG_FIELD.
Referenced by GXInit.
void GXGetCullMode(GXCullMode *mode)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::genMode, GET_REG_FIELD, GX_CULL_BACK, GX_CULL_FRONT.
void GXSetCoPlanar(GXBool enable)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::genMode, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.
void __GXSetGenMode(void)
References __GXData, __GXData_struct::bpSent, __GXData_struct::genMode, GX_WRITE_RAS_REG.
Referenced by __GXSetDirtyState.