GXPixel.h
void GXSetFog(GXFogType type, f32 startz, f32 endz, f32 nearz, f32 farz, GXColor color)
References __GXData, _GXColor::b, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, _GXColor::g, GX_WRITE_RAS_REG, _GXColor::r, SET_REG_FIELD.
Referenced by GXInit.
void GXInitFogAdjTable(GXFogAdjTable *table, u16 width, f32 projmtx[4][4])
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXSetFogRangeAdj(GXBool enable, u16 center, GXFogAdjTable *table)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, NULL, SET_REG_FIELD.
Referenced by GXInit.
void GXSetBlendMode(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor, GXLogicOp op)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode0, GX_BM_BLEND, GX_BM_LOGIC, GX_BM_SUBTRACT, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by DEMOSetFontType, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GXInit, PERFPreDraw.
void GXSetColorUpdate(GXBool update_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode0, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by DEMODoneRender, GXInit.
void GXSetAlphaUpdate(GXBool update_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode0, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXSetZMode(GXBool compare_enable, GXCompare func, GXBool update_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::zmode.
Referenced by DEMODoneRender, DEMOInitCaption, DEMOWinRefresh, G2DInitWorld, GXInit, PERFPreDraw.
void GXSetZCompLoc(GXBool before_tex)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, __GXData_struct::peCtrl, SET_REG_FIELD.
Referenced by GXInit, PERFPreDraw.
void GXSetPixelFmt(GXPixelFmt pix_fmt, GXZFmt16 z_fmt)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode1, __GXData_struct::dirtyState, __GXData_struct::genMode, GX_PF_RGB565_Z16, GX_WRITE_RAS_REG, __GXData_struct::peCtrl, SET_REG_FIELD.
Referenced by __DEMOInitGX, GXInit.
void GXSetDither(GXBool dither)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode0, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXSetDstAlpha(GXBool enable, u8 alpha)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode1, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXSetFieldMask(GXBool odd_mask, GXBool even_mask)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXSetFieldMode(GXBool field_mode, GXBool half_aspect_ratio)
References __GXData, __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, __GXData_struct::lpSize, SET_REG_FIELD.
Referenced by GXInit.