GXBump.c
GX_WRITE_SOME_REG5
void GXSetTevIndirect(GXTevStageID tev_stage, GXIndTexStageID ind_stage, GXIndTexFormat format, GXIndTexBiasSel bias_sel, GXIndTexMtxID matrix_sel, GXIndTexWrap wrap_s, GXIndTexWrap wrap_t, GXBool add_prev, GXBool utc_lod, GXIndTexAlphaSel alpha_sel)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_SOME_REG5, SET_REG_FIELD.
Referenced by GXSetTevDirect, GXSetTevIndBumpST, GXSetTevIndBumpXYZ, GXSetTevIndRepeat, GXSetTevIndTile, GXSetTevIndWarp.
void GXSetIndTexMtx(GXIndTexMtxID mtx_id, f32 offset[2][3], s8 scale_exp)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_ITM_0, GX_ITM_1, GX_ITM_2, GX_ITM_S0, GX_ITM_S1, GX_ITM_S2, GX_ITM_T0, GX_ITM_T1, GX_ITM_T2, GX_WRITE_SOME_REG5, SET_REG_FIELD.
Referenced by GXSetTevIndTile.
void GXSetIndTexCoordScale(GXIndTexStageID ind_state, GXIndTexScale scale_s, GXIndTexScale scale_t)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_INDTEXSTAGE0, GX_INDTEXSTAGE1, GX_INDTEXSTAGE2, GX_INDTEXSTAGE3, GX_WRITE_SOME_REG5, __GXData_struct::IndTexScale0, __GXData_struct::IndTexScale1, SET_REG_FIELD.
Referenced by GXInit.
void GXSetIndTexOrder(GXIndTexStageID ind_stage, GXTexCoordID tex_coord, GXTexMapID tex_map)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, GX_INDTEXSTAGE0, GX_INDTEXSTAGE1, GX_INDTEXSTAGE2, GX_INDTEXSTAGE3, GX_WRITE_SOME_REG5, __GXData_struct::iref, SET_REG_FIELD.
void GXSetNumIndStages(u8 nIndStages)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::genMode, SET_REG_FIELD.
Referenced by GXInit.
void GXSetTevDirect(GXTevStageID tev_stage)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_FALSE, GX_INDTEXSTAGE0, GX_ITB_NONE, GX_ITBA_OFF, GX_ITF_8, GX_ITM_OFF, GX_ITW_OFF, GXSetTevIndirect.
Referenced by GXInit.
void GXSetTevIndWarp(GXTevStageID tev_stage, GXIndTexStageID ind_stage, u8 signed_offset, u8 replace_mode, GXIndTexMtxID matrix_sel)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_FALSE, GX_ITB_NONE, GX_ITB_STU, GX_ITBA_OFF, GX_ITF_8, GX_ITW_0, GX_ITW_OFF, GXSetTevIndirect.
void GXSetTevIndTile(GXTevStageID tev_stage, GXIndTexStageID ind_stage, u16 tilesize_s, u16 tilesize_t, u16 tilespacing_s, u16 tilespacing_t, GXIndTexFormat format, GXIndTexMtxID matrix_sel, GXIndTexBiasSel bias_sel, GXIndTexAlphaSel alpha_sel)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_ITW_128, GX_ITW_16, GX_ITW_256, GX_ITW_32, GX_ITW_64, GX_ITW_OFF, GXSetIndTexMtx, GXSetTevIndirect.
void GXSetTevIndBumpST(GXTevStageID tev_stage, GXIndTexStageID ind_stage, GXIndTexMtxID matrix_sel)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_FALSE, GX_ITB_NONE, GX_ITB_ST, GX_ITBA_OFF, GX_ITF_8, GX_ITM_0, GX_ITM_1, GX_ITM_2, GX_ITM_OFF, GX_ITM_S0, GX_ITM_S1, GX_ITM_S2, GX_ITM_T0, GX_ITM_T1, GX_ITM_T2, GX_ITW_0, GX_ITW_OFF, GX_TRUE, GXSetTevIndirect.
void GXSetTevIndBumpXYZ(GXTevStageID tev_stage, GXIndTexStageID ind_stage, GXIndTexMtxID matrix_sel)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_FALSE, GX_ITB_STU, GX_ITBA_OFF, GX_ITF_8, GX_ITW_OFF, GXSetTevIndirect.
void GXSetTevIndRepeat(GXTevStageID tev_stage)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_FALSE, GX_INDTEXSTAGE0, GX_ITB_NONE, GX_ITBA_OFF, GX_ITF_8, GX_ITM_OFF, GX_ITW_0, GX_TRUE, GXSetTevIndirect.
void __GXUpdateBPMask(void)
References __GXData, __GXData_struct::bpMask, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, __GXData_struct::genMode, GET_REG_FIELD, GX_WRITE_SOME_REG5, __GXData_struct::iref, SET_REG_FIELD, __GXData_struct::texmapId.
Referenced by __GXSetDirtyState.
void __GXFlushTextureState(void)
References __GXData, __GXData_struct::bpMask, __GXData_struct::bpSent, GX_WRITE_SOME_REG5.
Referenced by GXInit, GXInvalidateTexAll, GXInvalidateTexRegion, GXLoadTlut, GXPreLoadEntireTexture, GXSetFieldMode.