GXAttr.c
CHECK_ATTRPTR
CHECK_ATTRNAME
CHECK_ATTRNAME2
CHECK_ATTRNAME3
CHECK_ATTRTYPE
CHECK_VTXFMT
CHECK_FRAC
CHECK_LISTPTR
static void __GXXfVtxSpecs(void)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_WRITE_XF_REG, __GXData_struct::hasBiNrms, __GXData_struct::hasNrms, __GXData_struct::vcdHi, __GXData_struct::vcdLo.
Referenced by __GXSetVCD.
static void SETVCDATTR(GXAttr Attr, GXAttrType Type)
References __GXData, CARD_MAX_MOUNT_STEP, GX_NONE, GX_VA_CLR0, GX_VA_CLR1, GX_VA_NBT, GX_VA_NRM, GX_VA_PNMTXIDX, GX_VA_POS, GX_VA_TEX0, GX_VA_TEX0MTXIDX, GX_VA_TEX1, GX_VA_TEX1MTXIDX, GX_VA_TEX2, GX_VA_TEX2MTXIDX, GX_VA_TEX3, GX_VA_TEX3MTXIDX, GX_VA_TEX4, GX_VA_TEX4MTXIDX, GX_VA_TEX5, GX_VA_TEX5MTXIDX, GX_VA_TEX6, GX_VA_TEX6MTXIDX, GX_VA_TEX7, GX_VA_TEX7MTXIDX, __GXData_struct::hasBiNrms, __GXData_struct::hasNrms, __GXData_struct::nrmType, SET_REG_FIELD, Type, __GXData_struct::vcdHi, __GXData_struct::vcdLo.
Referenced by GXSetVtxDesc, GXSetVtxDescv.
void GXSetVtxDesc(GXAttr attr, GXAttrType type)
References __GXData, CHECK_ATTRNAME, CHECK_ATTRTYPE, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::hasBiNrms, __GXData_struct::hasNrms, __GXData_struct::nrmType, SET_REG_FIELD, SETVCDATTR, __GXData_struct::vcdLo.
Referenced by __DEMOWin_puts_n, DEMOPuts, DEMORFPuts, DEMORFPutsEx, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GetVertState, GXDrawCube, GXDrawSphere, GXDrawTorus, PERFPreDraw.
void GXSetVtxDescv(const GXVtxDescList *attrPtr)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_ATTRNAME, CHECK_ATTRPTR, CHECK_ATTRTYPE, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::hasBiNrms, __GXData_struct::hasNrms, __GXData_struct::nrmType, SET_REG_FIELD, SETVCDATTR, __GXData_struct::vcdLo.
Referenced by RestoreVertState.
void __GXSetVCD(void)
References __GXData, __GXXfVtxSpecs, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_WRITE_SOME_REG4, __GXData_struct::hasBiNrms, __GXData_struct::vcdHi, __GXData_struct::vcdLo, __GXData_struct::vLim, __GXData_struct::vNum.
Referenced by __GXSetDirtyState.
void GXGetVtxDesc(GXAttr attr, GXAttrType *type)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_ATTRNAME, CHECK_GXBEGIN, GET_REG_FIELD, GX_VA_CLR0, GX_VA_CLR1, GX_VA_NBT, GX_VA_NRM, GX_VA_PNMTXIDX, GX_VA_POS, GX_VA_TEX0, GX_VA_TEX0MTXIDX, GX_VA_TEX1, GX_VA_TEX1MTXIDX, GX_VA_TEX2, GX_VA_TEX2MTXIDX, GX_VA_TEX3, GX_VA_TEX3MTXIDX, GX_VA_TEX4, GX_VA_TEX4MTXIDX, GX_VA_TEX5, GX_VA_TEX5MTXIDX, GX_VA_TEX6, GX_VA_TEX6MTXIDX, GX_VA_TEX7, GX_VA_TEX7MTXIDX, __GXData_struct::hasBiNrms, __GXData_struct::hasNrms, __GXData_struct::vcdHi, __GXData_struct::vcdLo.
Referenced by GXDrawCube, GXDrawSphere, GXDrawTorus, GXGetVtxDescv.
void GXGetVtxDescv(GXVtxDescList *vcd)
References _GXVtxDescList::attr, CHECK_ATTRPTR, CHECK_GXBEGIN, GX_VA_MAX_ATTR, GX_VA_NULL, GX_VA_PNMTXIDX, GXGetVtxDesc, vcd.
Referenced by GetVertState.
void GXClearVtxDesc(void)
References __GXData, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::hasBiNrms, __GXData_struct::hasNrms, SET_REG_FIELD, __GXData_struct::vcdHi, __GXData_struct::vcdLo.
Referenced by __DEMOWin_puts_n, DEMOPuts, DEMORFPuts, DEMORFPutsEx, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GetVertState, GXInit, PERFPreDraw.
static void SETVAT(u32 *va, u32 *vb, u32 *vc, GXAttr attr, GXCompCnt cnt, GXCompType type, u8 shft)
References CARD_MAX_MOUNT_STEP, GX_NRM_NBT3, GX_VA_CLR0, GX_VA_CLR1, GX_VA_NBT, GX_VA_NRM, GX_VA_POS, GX_VA_TEX0, GX_VA_TEX1, GX_VA_TEX2, GX_VA_TEX3, GX_VA_TEX4, GX_VA_TEX5, GX_VA_TEX6, GX_VA_TEX7, SET_REG_FIELD.
Referenced by GXSetVtxAttrFmt, GXSetVtxAttrFmtv.
void GXSetVtxAttrFmt(GXVtxFmt vtxfmt, GXAttr attr, GXCompCnt cnt, GXCompType type, u8 frac)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_ATTRNAME2, CHECK_FRAC, CHECK_GXBEGIN, CHECK_VTXFMT, __GXData_struct::dirtyState, __GXData_struct::dirtyVAT, SETVAT, __GXData_struct::vatA, __GXData_struct::vatB, __GXData_struct::vatC.
Referenced by __DEMOWin_puts_n, DEMOPuts, DEMORFPuts, DEMORFPutsEx, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GetVertState, GXDrawCube, GXDrawSphere, GXDrawTorus, PERFPreDraw.
void GXSetVtxAttrFmtv(GXVtxFmt vtxfmt, const GXVtxAttrFmtList *list)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_ATTRNAME2, CHECK_FRAC, CHECK_GXBEGIN, CHECK_LISTPTR, CHECK_VTXFMT, __GXData_struct::dirtyState, __GXData_struct::dirtyVAT, GX_VA_NULL, SETVAT, __GXData_struct::vatA, __GXData_struct::vatB, __GXData_struct::vatC.
Referenced by RestoreVertState.
void __GXSetVAT(void)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::dirtyVAT, GX_WRITE_SOME_REG4, __GXData_struct::vatA, __GXData_struct::vatB, __GXData_struct::vatC.
Referenced by __GXSetDirtyState.
void GXGetVtxAttrFmt(GXVtxFmt fmt, GXAttr attr, GXCompCnt *cnt, GXCompType *type, u8 *frac)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, CHECK_VTXFMT, GET_REG_FIELD, GX_NRM_NBT3, GX_RGB565, GX_TEX_ST, GX_VA_CLR0, GX_VA_CLR1, GX_VA_NBT, GX_VA_NRM, GX_VA_POS, GX_VA_TEX0, GX_VA_TEX1, GX_VA_TEX2, GX_VA_TEX3, GX_VA_TEX4, GX_VA_TEX5, GX_VA_TEX6, GX_VA_TEX7, __GXData_struct::vatA, __GXData_struct::vatB, __GXData_struct::vatC.
Referenced by GXGetVtxAttrFmtv.
void GXGetVtxAttrFmtv(GXVtxFmt fmt, GXVtxAttrFmtList *vat)
References _GXVtxAttrFmtList::attr, CHECK_GXBEGIN, CHECK_LISTPTR, CHECK_VTXFMT, _GXVtxAttrFmtList::cnt, _GXVtxAttrFmtList::frac, GX_VA_MAX_ATTR, GX_VA_NULL, GX_VA_POS, GXGetVtxAttrFmt, _GXVtxAttrFmtList::type, vat.
Referenced by GetVertState.
void GXSetArray(GXAttr attr, const void *base_ptr, u8 stride)
References CARD_MAX_MOUNT_STEP, CHECK_ATTRNAME3, CHECK_IN_BEGIN, GX_VA_NBT, GX_VA_NRM, GX_VA_POS, GX_WRITE_SOME_REG2, GX_WRITE_SOME_REG3, GXSetArray.
Referenced by G2DDrawLayer, GXSetArray.
void GXInvalidateVtxCache(void)
References CHECK_GXBEGIN, GX_WRITE_U8.
Referenced by DEMOBeforeRender, GXInit, PERFPreDraw.
void GXSetTexCoordGen2(GXTexCoordID dst_coord, GXTexGenType func, GXTexGenSrc src_param, u32 mtx, GXBool normalize, u32 pt_texmtx)
References __GXData, __GXSetMatrixIndex, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_TEXCOORD0, GX_TEXCOORD1, GX_TEXCOORD2, GX_TEXCOORD3, GX_TEXCOORD4, GX_TEXCOORD5, GX_TEXCOORD6, GX_TG_BINRM, GX_TG_COLOR0, GX_TG_COLOR1, GX_TG_MTX2x4, GX_TG_MTX3x4, GX_TG_NRM, GX_TG_POS, GX_TG_SRTG, GX_TG_TANGENT, GX_TG_TEX0, GX_TG_TEX1, GX_TG_TEX2, GX_TG_TEX3, GX_TG_TEX4, GX_TG_TEX5, GX_TG_TEX6, GX_TG_TEX7, GX_TG_TEXCOORD0, GX_TG_TEXCOORD1, GX_TG_TEXCOORD2, GX_TG_TEXCOORD3, GX_TG_TEXCOORD4, GX_TG_TEXCOORD5, GX_TG_TEXCOORD6, GX_WRITE_XF_REG, __GXData_struct::matIdxA, __GXData_struct::matIdxB, normalize, SET_REG_FIELD.
Referenced by GXSetTexCoordGen.
void GXSetNumTexGens(u8 nTexGens)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::genMode, GX_WRITE_XF_REG, SET_REG_FIELD.
Referenced by DEMOLoadFont, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GXInit, LoadSheet, PERFPreDraw.