GXPrivate.h
VERIF_XF_REG
VERIF_XF_REG_alt
VERIF_RAS_REG
GX_WRITE_XF_REG
GX_WRITE_XF_REG_2
GX_WRITE_XF_REG_F
GX_WRITE_RAS_REG
GX_WRITE_SOME_REG2
GX_WRITE_SOME_REG3
GX_WRITE_SOME_REG4
GET_REG_FIELD
SET_REG_FIELD
CHECK_GXBEGIN
CHECK_IN_BEGIN
GX_GET_MEM_REG
GX_GET_CP_REG
GX_GET_PE_REG
GX_GET_PI_REG
GX_SET_MEM_REG
GX_SET_CP_REG
GX_SET_PE_REG
GX_SET_PI_REG
__GX_WARN
__GX_WARNF
__GX_WARN2
__GX_WARN2F
GXWarnID
typedef struct __GXFifoObj __GXFifoObj
typedef struct __GXData_struct GXData
typedef struct __GXVerifyData __GXVerifyData
GXData* __GXData
Referenced by __GXDefaultTexRegionCallback, __GXDefaultTlutRegionCallback, __GXFifoLink, __GXFifoReadDisable, __GXFifoReadEnable, __GXFlushTextureState, __GXGetSUTexSize, __GXSendFlushPrim, __GXSetDirtyState, __GXSetGenMode, __GXSetSUTexRegs, __GXSetVAT, __GXSetVCD, __GXUpdateBPMask, __GXWriteFifoIntEnable, __GXWriteFifoIntReset, __GXXfVtxSpecs, __SetSURegs, GXBegin, GXBeginDisplayList, GXBreakPointHandler, GXCallDisplayList, GXClearBoundingBox, GXClearGPMetric, GXClearMemMetric, GXClearPixMetric, GXClearVtxDesc, GXCopyDisp, GXCopyTex, GXCPInterruptHandler, GXDisableBreakPt, GXEnableBreakPt, GXEnableTexOffsets, GXEndDisplayList, GXFlush, GXGetCullMode, GXGetGPStatus, GXGetLineWidth, GXGetPointSize, GXGetProjectionv, GXGetViewportv, GXGetVtxAttrFmt, GXGetVtxDesc, GXInit, GXInitXfRasMetric, GXLoadLightObjImm, GXLoadLightObjIndx, GXLoadTexObj, GXLoadTexObjPreLoaded, GXLoadTlut, GXPixModeSync, GXReadGPMetric, GXReadMemMetric, GXReadPixMetric, GXSetAlphaCompare, GXSetAlphaUpdate, GXSetBlendMode, GXSetChanAmbColor, GXSetChanMatColor, GXSetColorUpdate, GXSetCoPlanar, GXSetCopyClamp, GXSetCopyClear, GXSetCopyFilter, GXSetCullMode, GXSetCurrentMtx, GXSetDispCopyDst, GXSetDispCopyFrame2Field, GXSetDispCopyGamma, GXSetDispCopySrc, GXSetDispCopyYScale, GXSetDither, GXSetDrawSync, GXSetDstAlpha, GXSetFieldMask, GXSetFieldMode, GXSetFog, GXSetFogRangeAdj, GXSetGPMetric, GXSetIndTexCoordScale, GXSetIndTexMtx, GXSetIndTexOrder, GXSetLineWidth, GXSetMisc, GXSetNumIndStages, GXSetNumTevStages, GXSetNumTexGens, GXSetPixelFmt, GXSetPointSize, GXSetProjection, GXSetProjectionv, GXSetTevAlphaIn, GXSetTevAlphaOp, GXSetTevColor, GXSetTevColorIn, GXSetTevColorOp, GXSetTevColorS10, GXSetTevIndirect, GXSetTevKAlphaSel, GXSetTevKColor, GXSetTevKColorSel, GXSetTevOrder, GXSetTevSwapMode, GXSetTevSwapModeTable, GXSetTexCoordBias, GXSetTexCoordCylWrap, GXSetTexCoordGen2, GXSetTexCoordScaleManually, GXSetTexCopyDst, GXSetTexCopySrc, GXSetTexRegionCallback, GXSetTlutRegionCallback, GXSetVCacheMetric, GXSetViewportJitter, GXSetVtxAttrFmt, GXSetVtxAttrFmtv, GXSetVtxDesc, GXSetVtxDescv, GXSetZCompLoc, GXSetZMode, GXSetZTexture, GXTexModeSync, SETVCDATTR.
void* __memReg
Referenced by GXInit, PERFGetAllMemMetrics, PERFResetAllMemMetrics.
void* __peReg
Referenced by GXInit.
void* __cpReg
Referenced by GXInit.
void* __piReg
Referenced by GXInit.
__GXVerifyData* __gxVerif
Referenced by GXInit, GXOverflowHandler, GXUnderflowHandler.
char* __gxvWarnings[125][125]
s8 __gxvDummyStr[256][256]
GXWarningLevel __gxvWarnLev[][]
void __GXSetVCD(void)
References __GXData, __GXXfVtxSpecs, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_WRITE_SOME_REG4, __GXData_struct::hasBiNrms, __GXData_struct::vcdHi, __GXData_struct::vcdLo, __GXData_struct::vLim, __GXData_struct::vNum.
Referenced by __GXSetDirtyState.
void __GXSetVAT(void)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::dirtyVAT, GX_WRITE_SOME_REG4, __GXData_struct::vatA, __GXData_struct::vatB, __GXData_struct::vatC.
Referenced by __GXSetDirtyState.
void __GXUpdateBPMask(void)
References __GXData, __GXData_struct::bpMask, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, __GXData_struct::genMode, GET_REG_FIELD, GX_WRITE_SOME_REG5, __GXData_struct::iref, SET_REG_FIELD, __GXData_struct::texmapId.
Referenced by __GXSetDirtyState.
void __GXFlushTextureState(void)
References __GXData, __GXData_struct::bpMask, __GXData_struct::bpSent, GX_WRITE_SOME_REG5.
Referenced by GXInit, GXInvalidateTexAll, GXInvalidateTexRegion, GXLoadTlut, GXPreLoadEntireTexture, GXSetFieldMode.
void __GXSaveCPUFifoAux(__GXFifoObj *realFifo)
References CARD_MAX_MOUNT_STEP, CPGPLinked, GX_GET_PI_REG, GXFlush, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, SOME_MACRO1, SOME_MACRO2.
Referenced by GXEndDisplayList, GXGetFifoStatus, GXSaveCPUFifo.
void __GXFifoInit(void)
References __GXCurrentThread, __OSSetInterruptHandler, __OSUnmaskInterrupts, FALSE, GXCPInterruptHandler, GXOverflowSuspendInProgress, OSGetCurrentThread.
Referenced by GXInit.
void __GXInsaneWatermark(void)
References CARD_MAX_MOUNT_STEP, GPFifo, GX_SET_CP_REG, __GXFifoObj::hiWatermark.
void __GXCleanGPFifo(void)
References __GXFifoObj::base, CARD_MAX_MOUNT_STEP, GXGetCPUFifo, GXGetFifoBase, GXGetGPFifo, GXInitFifoPtrs, GXSetCPUFifo, GXSetGPFifo.
Referenced by GXAbortFrame.
void __GXSetDirtyState(void)
References __GXData, __GXSetGenMode, __GXSetSUTexRegs, __GXSetVAT, __GXSetVCD, __GXUpdateBPMask, __GXData_struct::dirtyState.
Referenced by GXBegin, GXBeginDisplayList, GXCallDisplayList, GXEndDisplayList, GXFlush.
void __GXSendFlushPrim(void)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, GX_WRITE_U16, GX_WRITE_U32, GX_WRITE_U8, __GXData_struct::vLim, __GXData_struct::vNum.
Referenced by GXBegin, GXCallDisplayList.
void __GXSetGenMode(void)
References __GXData, __GXData_struct::bpSent, __GXData_struct::genMode, GX_WRITE_RAS_REG.
Referenced by __GXSetDirtyState.
void __GXBypass(u32 reg)
u16 __GXReadPEReg(u32 reg)
void __GXPEInit(void)
References __OSSetInterruptHandler, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, FinishQueue, GX_GET_PE_REG, GX_SET_PE_REG, GXFinishInterruptHandler, GXTokenInterruptHandler, OSInitThreadQueue, SET_REG_FIELD.
Referenced by GXInit.
void __GXAbort()
void __GXSetBWDials(u16 cpDial, u16 tcDial, u16 peDial, u16 cpuRdDial, u16 cpuWrDial)
static u32 __GXReadCPCounterU32(u32 regAddrL, u32 regAddrH)
References CARD_MAX_MOUNT_STEP, GX_GET_CP_REG.
static u32 __GXReadMEMCounterU32(u32 regAddrL, u32 regAddrH)
References CARD_MAX_MOUNT_STEP, GX_GET_MEM_REG.
static u32 __GXReadPECounterU32(u32 regAddrL, u32 regAddrH)
References CARD_MAX_MOUNT_STEP, GX_GET_PE_REG.
void __GXShadowDispList(void *list, u32 nbytes)
Referenced by GXCallDisplayList.
void __GXShadowIndexState(u32 idx_reg, u32 reg_data)
Referenced by GXLoadLightObjIndx, GXLoadNrmMtxIndx3x3, GXLoadPosMtxIndx, GXLoadTexMtxIndx.
void __GXPrintShadowState(void)
void __GXSetRange(f32 nearz, f32 fgSideX)
Referenced by GXSetViewportJitter.
void __GetImageTileCount(GXTexFmt fmt, u16 wd, u16 ht, u32 *rowTiles, u32 *colTiles, u32 *cmpTiles)
Referenced by GXSetTexCopyDst.
void __GXSetSUTexRegs(void)
References __GXData, __SetSURegs, CARD_MAX_MOUNT_STEP, __GXData_struct::genMode, GET_REG_FIELD, __GXData_struct::iref, __GXData_struct::tcsManEnab, __GXData_struct::texmapId, __GXData_struct::tref.
Referenced by __GXSetDirtyState.
void __GXGetSUTexSize(GXTexCoordID coord, u16 *width, u16 *height)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::suTs0, __GXData_struct::suTs1.
void __GXSetTmemConfig(u32 config)
void __GXSetMatrixIndex(GXAttr matIdxAttr)
Referenced by GXSetCurrentMtx, GXSetTexCoordGen2.
void __GXSetProjection(void)
void __GXSetViewport()
void __GXVerifySU(void)
void __GXVerifyBUMP(void)
void __GXVerifyTEX(void)
void __GXVerifyTEV(void)
void __GXVerifyPE(void)
void __GXVerifyGlobal(void)
void __GXVerifyCP(GXVtxFmt fmt)
void __GXVerifyState(GXVtxFmt vtxfmt)
Referenced by GXBegin.
void __GXVerifyXF(void)