GXTexture.c
typedef struct __GXTexObjInt_struct __GXTexObjInt
typedef struct __GXTexRegionInt_struct __GXTexRegionInt
typedef struct __GXTlutObjInt_struct __GXTlutObjInt
typedef struct __GXTlutRegionInt_struct __GXTlutRegionInt
u8 GXTexMode0Ids[8][8]
Referenced by GXLoadTexObjPreLoaded.
u8 GXTexMode1Ids[8][8]
Referenced by GXLoadTexObjPreLoaded.
u8 GXTexImage0Ids[8][8]
Referenced by GXLoadTexObjPreLoaded.
u8 GXTexImage1Ids[8][8]
Referenced by GXLoadTexObjPreLoaded.
u8 GXTexImage2Ids[8][8]
Referenced by GXLoadTexObjPreLoaded.
u8 GXTexImage3Ids[8][8]
Referenced by GXLoadTexObjPreLoaded.
u8 GXTexTlutIds[8][8]
Referenced by GXLoadTexObjPreLoaded.
u8 GX2HWFiltConv[6][6]
Referenced by GXInitTexObjLOD.
u8 HW2GXFiltConv[8][8]
Referenced by GXGetTexObjLODAll, GXGetTexObjMinFilt.
static void __GXGetTexTileShift(GXTexFmt fmt, u32 *rowTileS, u32 *colTileS)
References CARD_MAX_MOUNT_STEP, GX_CTF_B8, GX_CTF_G8, GX_CTF_GB8, GX_CTF_R4, GX_CTF_R8, GX_CTF_RA4, GX_CTF_RA8, GX_CTF_RG8, GX_CTF_Z16L, GX_CTF_Z4, GX_CTF_Z8L, GX_CTF_Z8M, GX_TF_A8, GX_TF_C14X2, GX_TF_C4, GX_TF_C8, GX_TF_CMPR, GX_TF_I4, GX_TF_I8, GX_TF_IA4, GX_TF_IA8, GX_TF_RGB565, GX_TF_RGB5A3, GX_TF_RGBA8, GX_TF_Z16, GX_TF_Z24X8, GX_TF_Z8.
Referenced by __GetImageTileCount, GXGetTexBufferSize.
u32 GXGetTexBufferSize(u16 width, u16 height, u32 format, u8 mipmap, u8 max_lod)
References __GXGetTexTileShift, CARD_MAX_MOUNT_STEP, GX_TF_RGBA8, GX_TF_Z24X8.
void __GetImageTileCount(enum _GXTexFmt fmt, u16 wd, u16 ht, u32 *rowTiles, u32 *colTiles, u32 *cmpTiles)
References __GXGetTexTileShift, CARD_MAX_MOUNT_STEP, GX_TF_RGBA8, GX_TF_Z24X8.
Referenced by GXPreLoadEntireTexture.
void GXInitTexObj(GXTexObj *obj, void *image_ptr, u16 width, u16 height, GXTexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_CLAMP, SET_REG_FIELD.
Referenced by DEMOLoadFont, GXInitTexObjCI, LoadSheet, TEXGetGXTexObjFromPalette.
void GXInitTexObjCI(GXTexObj *obj, void *image_ptr, u16 width, u16 height, GXCITexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap, u32 tlut_name)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GXInitTexObj.
Referenced by TEXGetGXTexObjFromPaletteCI.
void GXInitTexObjLOD(GXTexObj *obj, GXTexFilter min_filt, GXTexFilter mag_filt, f32 min_lod, f32 max_lod, f32 lod_bias, u8 bias_clamp, u8 do_edge_lod, GXAnisotropy max_aniso)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX2HWFiltConv, GX_LINEAR, SET_REG_FIELD.
Referenced by DEMOLoadFont, LoadSheet, TEXGetGXTexObjFromPalette, TEXGetGXTexObjFromPaletteCI.
void GXInitTexObjData(GXTexObj *obj, void *image_ptr)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
void GXInitTexObjWrapMode(GXTexObj *obj, GXTexWrapMode sm, GXTexWrapMode tm)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
void GXInitTexObjTlut(GXTexObj *obj, u32 tlut_name)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN.
void GXInitTexObjUserData(GXTexObj *obj, void *user_data)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN.
void * GXGetTexObjUserData(const GXTexObj *obj)
References CARD_MAX_MOUNT_STEP.
void GXGetTexObjAll(const GXTexObj *obj, void **image_ptr, u16 *width, u16 *height, GXTexFmt *format, GXTexWrapMode *wrap_s, GXTexWrapMode *wrap_t, u8 *mipmap)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void * GXGetTexObjData(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
u16 GXGetTexObjWidth(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
Referenced by G2DDrawLayer, G2DInitSprite.
u16 GXGetTexObjHeight(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
Referenced by G2DDrawLayer, G2DInitSprite.
GXTexFmt GXGetTexObjFmt(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP.
Referenced by __GXDefaultTexRegionCallback.
GXTexWrapMode GXGetTexObjWrapS(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
GXTexWrapMode GXGetTexObjWrapT(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
GXBool GXGetTexObjMipMap(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP.
void GXGetTexObjLODAll(const GXTexObj *tex_obj, GXTexFilter *min_filt, GXTexFilter *mag_filt, f32 *min_lod, f32 *max_lod, f32 *lod_bias, u8 *bias_clamp, u8 *do_edge_lod, GXAnisotropy *max_aniso)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_FALSE, HW2GXFiltConv, tmp.
GXTexFilter GXGetTexObjMinFilt(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, HW2GXFiltConv.
GXTexFilter GXGetTexObjMagFilt(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
f32 GXGetTexObjMinLOD(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
f32 GXGetTexObjMaxLOD(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
f32 GXGetTexObjLODBias(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, tmp.
GXBool GXGetTexObjBiasClamp(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_TRUE.
GXBool GXGetTexObjEdgeLOD(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_FALSE.
GXAnisotropy GXGetTexObjMaxAniso(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
u32 GXGetTexObjTlut(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP.
void GXLoadTexObjPreLoaded(GXTexObj *obj, GXTexRegion *region, GXTexMapID id)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, GX_WRITE_RAS_REG, GXTexImage0Ids, GXTexImage1Ids, GXTexImage2Ids, GXTexImage3Ids, GXTexMode0Ids, GXTexMode1Ids, GXTexTlutIds, __GXTexRegionInt_struct::image1, __GXTexRegionInt_struct::image2, SET_REG_FIELD, __GXData_struct::tImage0, __GXData_struct::tlutRegionCallback, __GXData_struct::tMode0.
Referenced by GXLoadTexObj.
void GXLoadTexObj(GXTexObj *obj, GXTexMapID id)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GXLoadTexObjPreLoaded, __GXData_struct::texRegionCallback.
Referenced by DEMOLoadFont, G2DDrawLayer, G2DDrawSprite, LoadSheet.
void GXInitTlutObj(GXTlutObj *tlut_obj, void *lut, GXTlutFmt fmt, u16 n_entries)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
Referenced by TEXGetGXTexObjFromPaletteCI.
void GXGetTlutObjAll(const GXTlutObj *tlut_obj, void **data, GXTlutFmt *format, u16 *numEntries)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void * GXGetTlutObjData(const GXTlutObj *tlut_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
GXTlutFmt GXGetTlutObjFmt(const GXTlutObj *tlut_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
u16 GXGetTlutObjNumEntries(const GXTlutObj *tlut_obj)
References CARD_MAX_MOUNT_STEP.
void GXLoadTlut(GXTlutObj *tlut_obj, u32 tlut_name)
References __GXData, __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, __GXTlutRegionInt_struct::loadTlut1, SET_REG_FIELD, __GXTlutRegionInt_struct::tlutObj, __GXData_struct::tlutRegionCallback.
void GXInitTexCacheRegion(GXTexRegion *region, u8 is_32b_mipmap, u32 tmem_even, GXTexCacheSize size_even, u32 tmem_odd, GXTexCacheSize size_odd)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_TEXCACHE_128K, GX_TEXCACHE_32K, GX_TEXCACHE_512K, GX_TEXCACHE_NONE, SET_REG_FIELD.
Referenced by GXInit.
void GXInitTexPreLoadRegion(GXTexRegion *region, u32 tmem_even, u32 size_even, u32 tmem_odd, u32 size_odd)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
void GXGetTexRegionAll(const GXTexRegion *region, u8 *is_cached, u8 *is_32b_mipmap, u32 *tmem_even, u32 *size_even, u32 *tmem_odd, u32 *size_odd)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void GXInitTlutRegion(GXTlutRegion *region, u32 tmem_addr, GXTlutSize tlut_size)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
Referenced by GXInit.
void GXGetTlutRegionAll(const GXTlutRegion *region, u32 *tmem_addr, GXTlutSize *tlut_size)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void GXInvalidateTexRegion(GXTexRegion *region)
References __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GET_REG_FIELD, GX_WRITE_RAS_REG, __GXTexRegionInt_struct::image1, __GXTexRegionInt_struct::image2, __GXTexRegionInt_struct::is32bMipmap, SET_REG_FIELD.
void GXInvalidateTexAll(void)
References __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG.
Referenced by DEMOBeforeRender, GXInit.
GXTexRegionCallback GXSetTexRegionCallback(GXTexRegionCallback f)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::texRegionCallback.
Referenced by GXInit.
GXTlutRegionCallback GXSetTlutRegionCallback(GXTlutRegionCallback f)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::tlutRegionCallback.
Referenced by GXInit.
void GXPreLoadEntireTexture(GXTexObj *tex_obj, GXTexRegion *region)
References __GetImageTileCount, __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GET_REG_FIELD, GX_WRITE_RAS_REG, __GXTexRegionInt_struct::image1, __GXTexRegionInt_struct::image2, SET_REG_FIELD, __GXTexRegionInt_struct::sizeEven, __GXTexRegionInt_struct::sizeOdd.
void GXSetTexCoordScaleManually(GXTexCoordID coord, u8 enable, u16 ss, u16 ts)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tcsManEnab.
void GXSetTexCoordCylWrap(GXTexCoordID coord, u8 s_enable, u8 t_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tcsManEnab.
void GXSetTexCoordBias(GXTexCoordID coord, u8 s_enable, u8 t_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tcsManEnab.
static void __SetSURegs(u32 tmap, u32 tcoord)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tImage0, __GXData_struct::tMode0.
Referenced by __GXSetSUTexRegs.
void __GXSetSUTexRegs(void)
References __GXData, __SetSURegs, CARD_MAX_MOUNT_STEP, __GXData_struct::genMode, GET_REG_FIELD, __GXData_struct::iref, __GXData_struct::tcsManEnab, __GXData_struct::texmapId, __GXData_struct::tref.
Referenced by __GXSetDirtyState.
void __GXGetSUTexSize(GXTexCoordID coord, u16 *width, u16 *height)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::suTs0, __GXData_struct::suTs1.