GXLight.c
WRITE_SOME_LIGHT_REG1
WRITE_SOME_LIGHT_REG2
void GXInitLightAttn(GXLightObj *lt_obj, f32 a0, f32 a1, f32 a2, f32 k0, f32 k1, f32 k2)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXInitLightAttnA(GXLightObj *lt_obj, f32 a0, f32 a1, f32 a2)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXGetLightAttnA(GXLightObj *lt_obj, f32 *a0, f32 *a1, f32 *a2)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXInitLightAttnK(GXLightObj *lt_obj, f32 k0, f32 k1, f32 k2)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXGetLightAttnK(GXLightObj *lt_obj, f32 *k0, f32 *k1, f32 *k2)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXInitLightSpot(GXLightObj *lt_obj, f32 cutoff, GXSpotFn spot_func)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, cosf, GX_SP_COS, GX_SP_COS2, GX_SP_FLAT, GX_SP_OFF, GX_SP_RING1, GX_SP_RING2, GX_SP_SHARP, NULL.
void GXInitLightDistAttn(GXLightObj *lt_obj, f32 ref_dist, f32 ref_br, GXDistAttnFn dist_func)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_DA_GENTLE, GX_DA_MEDIUM, GX_DA_OFF, GX_DA_STEEP, NULL.
void GXInitLightPos(GXLightObj *lt_obj, f32 x, f32 y, f32 z)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXGetLightPos(GXLightObj *lt_obj, f32 *x, f32 *y, f32 *z)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXInitLightDir(GXLightObj *lt_obj, f32 nx, f32 ny, f32 nz)
References CARD_MAX_MOUNT_STEP, NULL.
void GXGetLightDir(GXLightObj *lt_obj, f32 *nx, f32 *ny, f32 *nz)
References CARD_MAX_MOUNT_STEP, NULL.
void GXInitSpecularDir(GXLightObj *lt_obj, f32 nx, f32 ny, f32 nz)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXInitSpecularDirHA(GXLightObj *lt_obj, f32 nx, f32 ny, f32 nz, f32 hx, f32 hy, f32 hz)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXInitLightColor(GXLightObj *lt_obj, GXColor color)
References _GXColor::a, _GXColor::b, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, _GXColor::g, NULL, _GXColor::r.
void GXGetLightColor(GXLightObj *lt_obj, GXColor *color)
References _GXColor::a, _GXColor::b, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, _GXColor::g, NULL, _GXColor::r.
void GXLoadLightObjImm(GXLightObj *lt_obj, GXLightID light)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_LIGHT0, GX_LIGHT1, GX_LIGHT2, GX_LIGHT3, GX_LIGHT4, GX_LIGHT5, GX_LIGHT6, GX_LIGHT7, GX_WRITE_U32, GX_WRITE_U8, NULL, WRITE_SOME_LIGHT_REG1, WRITE_SOME_LIGHT_REG2.
void GXLoadLightObjIndx(u32 lt_obj_indx, GXLightID light)
References __GXData, __GXShadowIndexState, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_LIGHT0, GX_LIGHT1, GX_LIGHT2, GX_LIGHT3, GX_LIGHT4, GX_LIGHT5, GX_LIGHT6, GX_LIGHT7, GX_WRITE_U32, GX_WRITE_U8, SET_REG_FIELD.
void GXSetChanAmbColor(GXChannelID chan, GXColor amb_color)
References __GXData, __GXData_struct::ambColor, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_ALPHA0, GX_ALPHA1, GX_COLOR0, GX_COLOR0A0, GX_COLOR1, GX_COLOR1A1, GX_WRITE_XF_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXSetChanMatColor(GXChannelID chan, GXColor mat_color)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_ALPHA0, GX_ALPHA1, GX_COLOR0, GX_COLOR0A0, GX_COLOR1, GX_COLOR1A1, GX_WRITE_XF_REG, __GXData_struct::matColor, SET_REG_FIELD.
Referenced by G2DDrawLayer, GXInit, PERFDumpScreen.
void GXSetNumChans(u8 nChans)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN.
Referenced by DEMOInitCaption, DEMOWinRefresh, G2DDrawLayer, G2DDrawSprite, GXInit, PERFPreDraw.
void GXSetChanCtrl(GXChannelID chan, GXBool enable, GXColorSrc amb_src, GXColorSrc mat_src, u32 light_mask, GXDiffuseFn diff_fn, GXAttnFn attn_fn)
Referenced by DEMOWinRefresh, G2DDrawLayer, GXInit, PERFPreDraw.