GXCull.h
void GXSetScissor(u32 left, u32 top, u32 wd, u32 ht)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GXSetScissor.
Referenced by __DEMOInitGX, G2DSetViewport, GXInit, GXSetScissor.
void GXSetCullMode(GXCullMode mode)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, __GXData_struct::genMode, GX_CULL_BACK, GX_CULL_FRONT, SET_REG_FIELD.
Referenced by GXInit.
void GXSetCoPlanar(GXBool enable)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::genMode, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by GXInit.