GXGet.h
void GXGetVtxDesc(GXAttr attr, GXAttrType *type)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_ATTRNAME, CHECK_GXBEGIN, GET_REG_FIELD, GX_VA_CLR0, GX_VA_CLR1, GX_VA_NBT, GX_VA_NRM, GX_VA_PNMTXIDX, GX_VA_POS, GX_VA_TEX0, GX_VA_TEX0MTXIDX, GX_VA_TEX1, GX_VA_TEX1MTXIDX, GX_VA_TEX2, GX_VA_TEX2MTXIDX, GX_VA_TEX3, GX_VA_TEX3MTXIDX, GX_VA_TEX4, GX_VA_TEX4MTXIDX, GX_VA_TEX5, GX_VA_TEX5MTXIDX, GX_VA_TEX6, GX_VA_TEX6MTXIDX, GX_VA_TEX7, GX_VA_TEX7MTXIDX, __GXData_struct::hasBiNrms, __GXData_struct::hasNrms, __GXData_struct::vcdHi, __GXData_struct::vcdLo.
Referenced by GXDrawCube, GXDrawSphere, GXDrawTorus, GXGetVtxDescv.
void GXGetVtxDescv(GXVtxDescList *vcd)
References _GXVtxDescList::attr, CHECK_ATTRPTR, CHECK_GXBEGIN, GX_VA_MAX_ATTR, GX_VA_NULL, GX_VA_PNMTXIDX, GXGetVtxDesc, vcd.
Referenced by GetVertState.
void GXGetVtxAttrFmt(GXVtxFmt fmt, GXAttr attr, GXCompCnt *cnt, GXCompType *type, u8 *frac)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, CHECK_VTXFMT, GET_REG_FIELD, GX_NRM_NBT3, GX_RGB565, GX_TEX_ST, GX_VA_CLR0, GX_VA_CLR1, GX_VA_NBT, GX_VA_NRM, GX_VA_POS, GX_VA_TEX0, GX_VA_TEX1, GX_VA_TEX2, GX_VA_TEX3, GX_VA_TEX4, GX_VA_TEX5, GX_VA_TEX6, GX_VA_TEX7, __GXData_struct::vatA, __GXData_struct::vatB, __GXData_struct::vatC.
Referenced by GXGetVtxAttrFmtv.
void GXGetVtxAttrFmtv(GXVtxFmt fmt, GXVtxAttrFmtList *vat)
References _GXVtxAttrFmtList::attr, CHECK_GXBEGIN, CHECK_LISTPTR, CHECK_VTXFMT, _GXVtxAttrFmtList::cnt, _GXVtxAttrFmtList::frac, GX_VA_MAX_ATTR, GX_VA_NULL, GX_VA_POS, GXGetVtxAttrFmt, _GXVtxAttrFmtList::type, vat.
Referenced by GetVertState.
void GXGetLineWidth(u8 *width, GXTexOffset *texOffsets)
References __GXData, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, __GXData_struct::lpSize, NULL.
void GXGetPointSize(u8 *pointSize, GXTexOffset *texOffsets)
References __GXData, CARD_MAX_MOUNT_STEP, GET_REG_FIELD, __GXData_struct::lpSize, NULL.
void GXGetCullMode(GXCullMode *mode)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::genMode, GET_REG_FIELD, GX_CULL_BACK, GX_CULL_FRONT.
void GXGetLightAttnA(GXLightObj *lt_obj, f32 *a0, f32 *a1, f32 *a2)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXGetLightAttnK(GXLightObj *lt_obj, f32 *k0, f32 *k1, f32 *k2)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXGetLightPos(GXLightObj *lt_obj, f32 *x, f32 *y, f32 *z)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, NULL.
void GXGetLightDir(GXLightObj *lt_obj, f32 *nx, f32 *ny, f32 *nz)
References CARD_MAX_MOUNT_STEP, NULL.
void GXGetLightColor(GXLightObj *lt_obj, GXColor *color)
References _GXColor::a, _GXColor::b, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, _GXColor::g, NULL, _GXColor::r.
GXBool GXGetTexObjMipMap(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP.
GXTexFmt GXGetTexObjFmt(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP.
Referenced by __GXDefaultTexRegionCallback.
u16 GXGetTexObjWidth(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
Referenced by G2DDrawLayer, G2DInitSprite.
u16 GXGetTexObjHeight(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
Referenced by G2DDrawLayer, G2DInitSprite.
GXTexWrapMode GXGetTexObjWrapS(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
GXTexWrapMode GXGetTexObjWrapT(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void * GXGetTexObjData(const GXTexObj *to)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void GXGetTexObjAll(const GXTexObj *obj, void **image_ptr, u16 *width, u16 *height, GXTexFmt *format, GXTexWrapMode *wrap_s, GXTexWrapMode *wrap_t, u8 *mipmap)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void GXGetTexObjLODAll(const GXTexObj *tex_obj, GXTexFilter *min_filt, GXTexFilter *mag_filt, f32 *min_lod, f32 *max_lod, f32 *lod_bias, u8 *bias_clamp, u8 *do_edge_lod, GXAnisotropy *max_aniso)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_FALSE, HW2GXFiltConv, tmp.
GXTexFilter GXGetTexObjMinFilt(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, HW2GXFiltConv.
GXTexFilter GXGetTexObjMagFilt(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
f32 GXGetTexObjMinLOD(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
f32 GXGetTexObjMaxLOD(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
f32 GXGetTexObjLODBias(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, tmp.
GXBool GXGetTexObjBiasClamp(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_TRUE.
GXBool GXGetTexObjEdgeLOD(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD, GX_FALSE.
GXAnisotropy GXGetTexObjMaxAniso(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
u32 GXGetTexObjTlut(const GXTexObj *tex_obj)
References CARD_MAX_MOUNT_STEP.
void GXGetTlutObjAll(const GXTlutObj *tlut_obj, void **data, GXTlutFmt *format, u16 *numEntries)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void * GXGetTlutObjData(const GXTlutObj *tlut_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
GXTlutFmt GXGetTlutObjFmt(const GXTlutObj *tlut_obj)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
u16 GXGetTlutObjNumEntries(const GXTlutObj *tlut_obj)
References CARD_MAX_MOUNT_STEP.
void GXGetTexRegionAll(const GXTexRegion *region, u8 *is_cached, u8 *is_32b_mipmap, u32 *tmem_even, u32 *size_even, u32 *tmem_odd, u32 *size_odd)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void GXGetTlutRegionAll(const GXTlutRegion *region, u32 *tmem_addr, GXTlutSize *tlut_size)
References CARD_MAX_MOUNT_STEP, GET_REG_FIELD.
void GXGetProjectionv(f32 *ptr)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::projMtx, __GXData_struct::projType.
Referenced by PERFPreDraw.
void GXGetViewportv(f32 *vp)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::vpFarz, __GXData_struct::vpHt, __GXData_struct::vpLeft, __GXData_struct::vpNearz, __GXData_struct::vpTop, __GXData_struct::vpWd.
void GXGetScissor(u32 *left, u32 *top, u32 *wd, u32 *ht)