GXMisc.c
GXDrawSyncCallback TokenCB
Referenced by GXSetDrawSyncCallback, GXTokenInterruptHandler.
GXDrawDoneCallback DrawDoneCB
Referenced by GXFinishInterruptHandler, GXSetDrawDoneCallback.
u8 DrawDone
Referenced by GXFinishInterruptHandler, GXSetDrawDone, GXWaitDrawDone.
OSThreadQueue FinishQueue
Referenced by __GXPEInit, GXFinishInterruptHandler, GXWaitDrawDone.
void GXSetMisc(GXMiscToken token, u32 val)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::dirtyState, __GXData_struct::dlSaveContext, GX_MT_DL_SAVE_CONTEXT, GX_MT_NULL, GX_MT_XF_FLUSH, __GXData_struct::inDispList, OSReport, __GXData_struct::vNum.
void GXFlush(void)
References __GXData, __GXSetDirtyState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, GX_WRITE_U8, PPCSync.
Referenced by __GXSaveCPUFifoAux, GXRedirectWriteGatherPipe, GXSetDrawDone, GXSetDrawSync.
void GXResetWriteGatherPipe(void)
References GXFIFO_ADDR, OSUncachedToPhysical, PPCMfwpar, PPCMtwpar.
static void __GXAbortWait(u32 clocks)
References CARD_MAX_MOUNT_STEP, OSGetTime.
Referenced by GXAbortFrame.
void GXAbortFrame(void)
References __GXAbortWait, __GXCleanGPFifo, GX_SET_PI_REG.
Referenced by DEMOReInit.
void GXSetDrawSync(u16 token)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, GXFlush, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by __BypassDoneRender, DEMOBeforeRender, PERFEventEnd, PERFEventStart.
u16 GXReadDrawSync(void)
References CARD_MAX_MOUNT_STEP, GX_GET_PE_REG.
Referenced by __BypassDoneRender.
void GXSetDrawDone(void)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, DrawDone, GX_WRITE_RAS_REG, GXFlush, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by GXDrawDone.
void GXWaitDrawDone(void)
References CHECK_GXBEGIN, DrawDone, FinishQueue, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread.
Referenced by GXDrawDone.
void GXDrawDone(void)
References CHECK_GXBEGIN, GXSetDrawDone, GXWaitDrawDone.
Referenced by DEMODoneRender, GXReadClksPerVtx.
void GXPixModeSync(void)
References __GXData, __GXData_struct::bpSent, CHECK_GXBEGIN, GX_WRITE_RAS_REG, __GXData_struct::peCtrl.
void GXTexModeSync(void)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG.
void GXPokeAlphaMode(GXCompare func, u8 threshold)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, PE_PI_ALPHA_THRESHOLD_ID.
Referenced by GXInit.
void GXPokeAlphaRead(GXAlphaReadMode mode)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeAlphaUpdate(GXBool update_enable)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeBlendMode(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor, GXLogicOp op)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_BM_BLEND, GX_BM_LOGIC, GX_BM_SUBTRACT, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeColorUpdate(GXBool update_enable)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeDstAlpha(GXBool enable, u8 alpha)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeDither(GXBool dither)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_GET_PE_REG, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPokeZMode(GXBool compare_enable, GXCompare func, GXBool update_enable)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_SET_PE_REG, SET_REG_FIELD.
Referenced by GXInit.
void GXPeekARGB(u16 x, u16 y, u32 *color)
References OSPhysicalToUncached, SET_REG_FIELD.
void GXPokeARGB(u16 x, u16 y, u32 color)
References OSPhysicalToUncached, SET_REG_FIELD.
void GXPeekZ(u16 x, u16 y, u32 *z)
References OSPhysicalToUncached, SET_REG_FIELD.
void GXPokeZ(u16 x, u16 y, u32 z)
References OSPhysicalToUncached, SET_REG_FIELD.
GXDrawSyncCallback GXSetDrawSyncCallback(GXDrawSyncCallback cb)
References CARD_MAX_MOUNT_STEP, cb, OSDisableInterrupts, OSRestoreInterrupts, TokenCB.
static void GXTokenInterruptHandler(__OSInterrupt interrupt, OSContext *context)
References CARD_MAX_MOUNT_STEP, GX_GET_PE_REG, GX_SET_PE_REG, NULL, OSClearContext, OSSetCurrentContext, SET_REG_FIELD, TokenCB.
Referenced by __GXPEInit.
GXDrawDoneCallback GXSetDrawDoneCallback(GXDrawDoneCallback cb)
References CARD_MAX_MOUNT_STEP, cb, DrawDoneCB, OSDisableInterrupts, OSRestoreInterrupts.
static void GXFinishInterruptHandler(__OSInterrupt interrupt, OSContext *context)
References CARD_MAX_MOUNT_STEP, DrawDone, DrawDoneCB, FinishQueue, GX_GET_PE_REG, GX_SET_PE_REG, NULL, OSClearContext, OSSetCurrentContext, OSWakeupThread, SET_REG_FIELD.
Referenced by __GXPEInit.
void __GXPEInit(void)
References __OSSetInterruptHandler, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, FinishQueue, GX_GET_PE_REG, GX_SET_PE_REG, GXFinishInterruptHandler, GXTokenInterruptHandler, OSInitThreadQueue, SET_REG_FIELD.
Referenced by GXInit.
u32 GXCompressZ16(u32 z24, GXZFmt16 zfmt)
References CARD_MAX_MOUNT_STEP, GX_ZC_FAR, GX_ZC_LINEAR, GX_ZC_MID, GX_ZC_NEAR, OSPanic.
u32 GXDecompressZ16(u32 z16, GXZFmt16 zfmt)
References CARD_MAX_MOUNT_STEP, GX_ZC_FAR, GX_ZC_LINEAR, GX_ZC_MID, GX_ZC_NEAR, OSPanic.