GXTexture.h
typedef GXTexRegion *(* GXTexRegionCallback) (GXTexObj *t_obj, GXTexMapID id))(GXTexObj *t_obj, GXTexMapID id)
typedef GXTlutRegion *(* GXTlutRegionCallback) (u32 idx))(u32 idx)
u32 GXGetTexBufferSize(u16 width, u16 height, u32 format, u8 mipmap, u8 max_lod)
References __GXGetTexTileShift, CARD_MAX_MOUNT_STEP, GX_TF_RGBA8, GX_TF_Z24X8.
void GXInitTexObj(GXTexObj *obj, void *image_ptr, u16 width, u16 height, GXTexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_CLAMP, SET_REG_FIELD.
Referenced by DEMOLoadFont, GXInitTexObjCI, LoadSheet, TEXGetGXTexObjFromPalette.
void GXInitTexObjCI(GXTexObj *obj, void *image_ptr, u16 width, u16 height, GXCITexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap, u32 tlut_name)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GXInitTexObj.
Referenced by TEXGetGXTexObjFromPaletteCI.
void GXInitTexObjLOD(GXTexObj *obj, GXTexFilter min_filt, GXTexFilter mag_filt, f32 min_lod, f32 max_lod, f32 lod_bias, GXBool bias_clamp, GXBool do_edge_lod, GXAnisotropy max_aniso)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX2HWFiltConv, GX_LINEAR, SET_REG_FIELD.
Referenced by DEMOLoadFont, LoadSheet, TEXGetGXTexObjFromPalette, TEXGetGXTexObjFromPaletteCI.
void GXInitTexObjData(GXTexObj *obj, void *image_ptr)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
void GXInitTexObjWrapMode(GXTexObj *obj, GXTexWrapMode s, GXTexWrapMode t)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
void GXInitTexObjTlut(GXTexObj *obj, u32 tlut_name)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN.
void GXInitTexObjUserData(GXTexObj *obj, void *user_data)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN.
void * GXGetTexObjUserData(const GXTexObj *obj)
References CARD_MAX_MOUNT_STEP.
void GXLoadTexObjPreLoaded(GXTexObj *obj, GXTexRegion *region, GXTexMapID id)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::dirtyState, GX_WRITE_RAS_REG, GXTexImage0Ids, GXTexImage1Ids, GXTexImage2Ids, GXTexImage3Ids, GXTexMode0Ids, GXTexMode1Ids, GXTexTlutIds, __GXTexRegionInt_struct::image1, __GXTexRegionInt_struct::image2, SET_REG_FIELD, __GXData_struct::tImage0, __GXData_struct::tlutRegionCallback, __GXData_struct::tMode0.
Referenced by GXLoadTexObj.
void GXLoadTexObj(GXTexObj *obj, GXTexMapID id)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GXLoadTexObjPreLoaded, __GXData_struct::texRegionCallback.
Referenced by DEMOLoadFont, G2DDrawLayer, G2DDrawSprite, LoadSheet.
void GXInitTlutObj(GXTlutObj *tlut_obj, void *lut, GXTlutFmt fmt, u16 n_entries)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
Referenced by TEXGetGXTexObjFromPaletteCI.
void GXLoadTlut(GXTlutObj *tlut_obj, u32 tlut_name)
References __GXData, __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, __GXTlutRegionInt_struct::loadTlut1, SET_REG_FIELD, __GXTlutRegionInt_struct::tlutObj, __GXData_struct::tlutRegionCallback.
void GXInitTexCacheRegion(GXTexRegion *region, u8 is_32b_mipmap, u32 tmem_even, GXTexCacheSize size_even, u32 tmem_odd, GXTexCacheSize size_odd)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_TEXCACHE_128K, GX_TEXCACHE_32K, GX_TEXCACHE_512K, GX_TEXCACHE_NONE, SET_REG_FIELD.
Referenced by GXInit.
void GXInitTexPreLoadRegion(GXTexRegion *region, u32 tmem_even, u32 size_even, u32 tmem_odd, u32 size_odd)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
void GXInitTlutRegion(GXTlutRegion *region, u32 tmem_addr, GXTlutSize tlut_size)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, SET_REG_FIELD.
Referenced by GXInit.
void GXInvalidateTexRegion(GXTexRegion *region)
References __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GET_REG_FIELD, GX_WRITE_RAS_REG, __GXTexRegionInt_struct::image1, __GXTexRegionInt_struct::image2, __GXTexRegionInt_struct::is32bMipmap, SET_REG_FIELD.
void GXInvalidateTexAll(void)
References __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG.
Referenced by DEMOBeforeRender, GXInit.
GXTexRegionCallback GXSetTexRegionCallback(GXTexRegionCallback f)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::texRegionCallback.
Referenced by GXInit.
GXTlutRegionCallback GXSetTlutRegionCallback(GXTlutRegionCallback f)
References __GXData, CARD_MAX_MOUNT_STEP, __GXData_struct::tlutRegionCallback.
Referenced by GXInit.
void GXPreLoadEntireTexture(GXTexObj *tex_obj, GXTexRegion *region)
References __GetImageTileCount, __GXFlushTextureState, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GET_REG_FIELD, GX_WRITE_RAS_REG, __GXTexRegionInt_struct::image1, __GXTexRegionInt_struct::image2, SET_REG_FIELD, __GXTexRegionInt_struct::sizeEven, __GXTexRegionInt_struct::sizeOdd.
void GXSetTexCoordScaleManually(GXTexCoordID coord, u8 enable, u16 ss, u16 ts)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tcsManEnab.
void GXSetTexCoordCylWrap(GXTexCoordID coord, u8 s_enable, u8 t_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tcsManEnab.
void GXSetTexCoordBias(GXTexCoordID coord, u8 s_enable, u8 t_enable)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tcsManEnab.