GXPerf.c
void GXSetGPMetric(GXPerf0 perf0, GXPerf1 perf1)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_PERF0_AVG_QUAD_CNT, GX_PERF0_CLIP_CLKS, GX_PERF0_CLIP_RATIO, GX_PERF0_CLIP_VTX, GX_PERF0_CLOCKS, GX_PERF0_NONE, GX_PERF0_QUAD_0CVG, GX_PERF0_QUAD_1CVG, GX_PERF0_QUAD_2CVG, GX_PERF0_QUAD_3CVG, GX_PERF0_QUAD_4CVG, GX_PERF0_QUAD_NON0CVG, GX_PERF0_TRIANGLES, GX_PERF0_TRIANGLES_0CLR, GX_PERF0_TRIANGLES_0TEX, GX_PERF0_TRIANGLES_1CLR, GX_PERF0_TRIANGLES_1TEX, GX_PERF0_TRIANGLES_2CLR, GX_PERF0_TRIANGLES_2TEX, GX_PERF0_TRIANGLES_3TEX, GX_PERF0_TRIANGLES_4TEX, GX_PERF0_TRIANGLES_5TEX, GX_PERF0_TRIANGLES_6TEX, GX_PERF0_TRIANGLES_7TEX, GX_PERF0_TRIANGLES_8TEX, GX_PERF0_TRIANGLES_CULLED, GX_PERF0_TRIANGLES_PASSED, GX_PERF0_TRIANGLES_SCISSORED, GX_PERF0_VERTICES, GX_PERF0_XF_BOT_CLKS, GX_PERF0_XF_LIT_CLKS, GX_PERF0_XF_REGLD_CLKS, GX_PERF0_XF_REGRD_CLKS, GX_PERF0_XF_WAIT_IN, GX_PERF0_XF_WAIT_OUT, GX_PERF0_XF_XFRM_CLKS, GX_PERF1_CALL_REQ, GX_PERF1_CLOCKS, GX_PERF1_CP_ALL_REQ, GX_PERF1_FIFO_REQ, GX_PERF1_NONE, GX_PERF1_TC_CHECK1_2, GX_PERF1_TC_CHECK3_4, GX_PERF1_TC_CHECK5_6, GX_PERF1_TC_CHECK7_8, GX_PERF1_TC_MISS, GX_PERF1_TEXELS, GX_PERF1_TX_IDLE, GX_PERF1_TX_MEMSTALL, GX_PERF1_TX_REGS, GX_PERF1_VC_ALL_STALLS, GX_PERF1_VC_ELEMQ_FULL, GX_PERF1_VC_MEMREQ_FULL, GX_PERF1_VC_MISS_REQ, GX_PERF1_VC_MISSQ_FULL, GX_PERF1_VC_MISSREP_FULL, GX_PERF1_VC_STATUS7, GX_PERF1_VC_STREAMBUF_LOW, GX_PERF1_VERTICES, GX_SET_CP_REG, GX_WRITE_RAS_REG, GX_WRITE_SOME_REG4, GX_WRITE_XF_REG, __GXData_struct::perf0, __GXData_struct::perf1, __GXData_struct::perfSel, SET_REG_FIELD.
Referenced by DEMOWriteStats.
void GXReadGPMetric(u32 *cnt0, u32 *cnt1)
References __GXData, CARD_MAX_MOUNT_STEP, GX_GET_CP_REG, GX_PERF0_AVG_QUAD_CNT, GX_PERF0_CLIP_CLKS, GX_PERF0_CLIP_RATIO, GX_PERF0_CLIP_VTX, GX_PERF0_CLOCKS, GX_PERF0_NONE, GX_PERF0_QUAD_0CVG, GX_PERF0_QUAD_1CVG, GX_PERF0_QUAD_2CVG, GX_PERF0_QUAD_3CVG, GX_PERF0_QUAD_4CVG, GX_PERF0_QUAD_NON0CVG, GX_PERF0_TRIANGLES, GX_PERF0_TRIANGLES_0CLR, GX_PERF0_TRIANGLES_0TEX, GX_PERF0_TRIANGLES_1CLR, GX_PERF0_TRIANGLES_1TEX, GX_PERF0_TRIANGLES_2CLR, GX_PERF0_TRIANGLES_2TEX, GX_PERF0_TRIANGLES_3TEX, GX_PERF0_TRIANGLES_4TEX, GX_PERF0_TRIANGLES_5TEX, GX_PERF0_TRIANGLES_6TEX, GX_PERF0_TRIANGLES_7TEX, GX_PERF0_TRIANGLES_8TEX, GX_PERF0_TRIANGLES_CULLED, GX_PERF0_TRIANGLES_PASSED, GX_PERF0_TRIANGLES_SCISSORED, GX_PERF0_VERTICES, GX_PERF0_XF_BOT_CLKS, GX_PERF0_XF_LIT_CLKS, GX_PERF0_XF_REGLD_CLKS, GX_PERF0_XF_REGRD_CLKS, GX_PERF0_XF_WAIT_IN, GX_PERF0_XF_WAIT_OUT, GX_PERF0_XF_XFRM_CLKS, GX_PERF1_CALL_REQ, GX_PERF1_CLOCKS, GX_PERF1_CP_ALL_REQ, GX_PERF1_FIFO_REQ, GX_PERF1_NONE, GX_PERF1_TC_CHECK1_2, GX_PERF1_TC_CHECK3_4, GX_PERF1_TC_CHECK5_6, GX_PERF1_TC_CHECK7_8, GX_PERF1_TC_MISS, GX_PERF1_TEXELS, GX_PERF1_TX_IDLE, GX_PERF1_TX_MEMSTALL, GX_PERF1_TX_REGS, GX_PERF1_VC_ALL_STALLS, GX_PERF1_VC_ELEMQ_FULL, GX_PERF1_VC_MEMREQ_FULL, GX_PERF1_VC_MISS_REQ, GX_PERF1_VC_MISSQ_FULL, GX_PERF1_VC_MISSREP_FULL, GX_PERF1_VC_STATUS7, GX_PERF1_VC_STREAMBUF_LOW, GX_PERF1_VERTICES, __GXData_struct::inDispList, __GXData_struct::perf0, __GXData_struct::perf1.
Referenced by GXReadGP0Metric, GXReadGP1Metric.
void GXClearGPMetric(void)
References __GXData, CARD_MAX_MOUNT_STEP, GX_SET_CP_REG, __GXData_struct::inDispList.
Referenced by DEMOWriteStats, PERFStartFrame.
u32 GXReadGP0Metric(void)
References CARD_MAX_MOUNT_STEP, GXReadGPMetric.
Referenced by DEMOWriteStats.
u32 GXReadGP1Metric(void)
References CARD_MAX_MOUNT_STEP, GXReadGPMetric.
Referenced by DEMOWriteStats.
void GXReadMemMetric(u32 *cp_req, u32 *tc_req, u32 *cpu_rd_req, u32 *cpu_wr_req, u32 *dsp_req, u32 *io_req, u32 *vi_req, u32 *pe_req, u32 *rf_req, u32 *fi_req)
References __GXData, CARD_MAX_MOUNT_STEP, GX_GET_MEM_REG, __GXData_struct::inDispList.
Referenced by DEMOWriteStats.
void GXClearMemMetric(void)
References __GXData, CARD_MAX_MOUNT_STEP, GX_SET_MEM_REG, __GXData_struct::inDispList.
Referenced by DEMOWriteStats.
void GXReadPixMetric(u32 *top_pixels_in, u32 *top_pixels_out, u32 *bot_pixels_in, u32 *bot_pixels_out, u32 *clr_pixels_in, u32 *copy_clks)
References __GXData, CARD_MAX_MOUNT_STEP, GX_GET_PE_REG, __GXData_struct::inDispList.
Referenced by DEMOWriteStats.
void GXClearPixMetric(void)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG.
Referenced by DEMOWriteStats.
void GXSetVCacheMetric(GXVCachePerf attr)
References __GXData, CARD_MAX_MOUNT_STEP, GX_WRITE_SOME_REG4, __GXData_struct::perfSel, SET_REG_FIELD.
Referenced by DEMOWriteStats.
void GXReadVCacheMetric(u32 *check, u32 *miss, u32 *stall)
References CARD_MAX_MOUNT_STEP, GX_GET_CP_REG.
Referenced by DEMOWriteStats.
void GXClearVCacheMetric(void)
References GX_WRITE_SOME_REG4.
Referenced by DEMOWriteStats.
void GXInitXfRasMetric(void)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, GX_WRITE_XF_REG.
Referenced by PERFInit.
void GXReadXfRasMetric(u32 *xf_wait_in, u32 *xf_wait_out, u32 *ras_busy, u32 *clocks)
References CARD_MAX_MOUNT_STEP, GX_GET_CP_REG.
Referenced by PERFGetAllMemMetrics.
u32 GXReadClksPerVtx(void)
References CARD_MAX_MOUNT_STEP, GX_GET_CP_REG, GX_SET_CP_REG, GXDrawDone.