GXInit.c
struct __GXData_struct gxData
struct __GXData_struct* __GXData
Referenced by __GXDefaultTexRegionCallback, __GXDefaultTlutRegionCallback, __GXFifoLink, __GXFifoReadDisable, __GXFifoReadEnable, __GXFlushTextureState, __GXGetSUTexSize, __GXSendFlushPrim, __GXSetDirtyState, __GXSetGenMode, __GXSetSUTexRegs, __GXSetVAT, __GXSetVCD, __GXUpdateBPMask, __GXWriteFifoIntEnable, __GXWriteFifoIntReset, __GXXfVtxSpecs, __SetSURegs, GXBegin, GXBeginDisplayList, GXBreakPointHandler, GXCallDisplayList, GXClearBoundingBox, GXClearGPMetric, GXClearMemMetric, GXClearPixMetric, GXClearVtxDesc, GXCopyDisp, GXCopyTex, GXCPInterruptHandler, GXDisableBreakPt, GXEnableBreakPt, GXEnableTexOffsets, GXEndDisplayList, GXFlush, GXGetCullMode, GXGetGPStatus, GXGetLineWidth, GXGetPointSize, GXGetProjectionv, GXGetViewportv, GXGetVtxAttrFmt, GXGetVtxDesc, GXInit, GXInitXfRasMetric, GXLoadLightObjImm, GXLoadLightObjIndx, GXLoadTexObj, GXLoadTexObjPreLoaded, GXLoadTlut, GXPixModeSync, GXReadGPMetric, GXReadMemMetric, GXReadPixMetric, GXSetAlphaCompare, GXSetAlphaUpdate, GXSetBlendMode, GXSetChanAmbColor, GXSetChanMatColor, GXSetColorUpdate, GXSetCoPlanar, GXSetCopyClamp, GXSetCopyClear, GXSetCopyFilter, GXSetCullMode, GXSetCurrentMtx, GXSetDispCopyDst, GXSetDispCopyFrame2Field, GXSetDispCopyGamma, GXSetDispCopySrc, GXSetDispCopyYScale, GXSetDither, GXSetDrawSync, GXSetDstAlpha, GXSetFieldMask, GXSetFieldMode, GXSetFog, GXSetFogRangeAdj, GXSetGPMetric, GXSetIndTexCoordScale, GXSetIndTexMtx, GXSetIndTexOrder, GXSetLineWidth, GXSetMisc, GXSetNumIndStages, GXSetNumTevStages, GXSetNumTexGens, GXSetPixelFmt, GXSetPointSize, GXSetProjection, GXSetProjectionv, GXSetTevAlphaIn, GXSetTevAlphaOp, GXSetTevColor, GXSetTevColorIn, GXSetTevColorOp, GXSetTevColorS10, GXSetTevIndirect, GXSetTevKAlphaSel, GXSetTevKColor, GXSetTevKColorSel, GXSetTevOrder, GXSetTevSwapMode, GXSetTevSwapModeTable, GXSetTexCoordBias, GXSetTexCoordCylWrap, GXSetTexCoordGen2, GXSetTexCoordScaleManually, GXSetTexCopyDst, GXSetTexCopySrc, GXSetTexRegionCallback, GXSetTlutRegionCallback, GXSetVCacheMetric, GXSetViewportJitter, GXSetVtxAttrFmt, GXSetVtxAttrFmtv, GXSetVtxDesc, GXSetVtxDescv, GXSetZCompLoc, GXSetZMode, GXSetZTexture, GXTexModeSync, SETVCDATTR.
void* __memReg
Referenced by GXInit, PERFGetAllMemMetrics, PERFResetAllMemMetrics.
void* __peReg
Referenced by GXInit.
void* __cpReg
Referenced by GXInit.
void* __piReg
Referenced by GXInit.
GXFifoObj FifoObj
Referenced by GXInit.
asm BOOL IsWriteGatherBufferEmpty(void)
References CARD_MAX_MOUNT_STEP, FALSE, r3, sync, WPAR.
static void EnableWriteGatherPipe(void)
References CARD_MAX_MOUNT_STEP, GXFIFO_ADDR, OSUncachedToPhysical, PPCMfhid2, PPCMthid2, PPCMtwpar.
Referenced by GXInit.
static void DisableWriteGatherPipe(void)
References CARD_MAX_MOUNT_STEP, PPCMfhid2, PPCMthid2.
static GXTexRegion * __GXDefaultTexRegionCallback(GXTexObj *t_obj, GXTexMapID unused)
References __GXData, CARD_MAX_MOUNT_STEP, GX_TF_C14X2, GX_TF_C4, GX_TF_C8, GXGetTexObjFmt, __GXData_struct::nextTexRgn, __GXData_struct::nextTexRgnCI, __GXData_struct::TexRegions, __GXData_struct::TexRegionsCI.
Referenced by GXInit.
static GXTlutRegion * __GXDefaultTlutRegionCallback(u32 idx)
References __GXData, CARD_MAX_MOUNT_STEP, NULL, __GXData_struct::TlutRegions.
Referenced by GXInit.
GXFifoObj * GXInit(void *base, u32 size)
References __cpReg, __GXData, __GXDefaultTexRegionCallback, __GXDefaultTlutRegionCallback, __GXFifoInit, __GXFlushTextureState, __GXPEInit, __gxVerif, __memReg, __OSBusClock, __peReg, __piReg, _GXRenderModeObj::aa, __GXData_struct::bpMask, CARD_MAX_MOUNT_STEP, __GXData_struct::cmode0, __GXData_struct::cmode1, __GXData_struct::cpTex, __GXData_struct::dirtyState, __GXData_struct::dirtyVAT, __GXData_struct::dlSaveContext, _GXRenderModeObj::efbHeight, EnableWriteGatherPipe, FALSE, _GXRenderModeObj::fbWidth, _GXRenderModeObj::field_rendering, FifoObj, __GXData_struct::genMode, GX_AF_NONE, GX_ALWAYS, GX_AOP_AND, GX_BL_INVSRCALPHA, GX_BL_ONE, GX_BL_SRCALPHA, GX_BL_ZERO, GX_BM_NONE, GX_CH_ALPHA, GX_CH_BLUE, GX_CH_GREEN, GX_CH_RED, GX_CLAMP_BOTTOM, GX_CLAMP_TOP, GX_CLIP_ENABLE, GX_COLOR0A0, GX_COLOR1A1, GX_COLOR_NULL, GX_COPY_PROGRESSIVE, GX_CULL_BACK, GX_DF_NONE, GX_DISABLE, GX_ENABLE, GX_FALSE, GX_FOG_NONE, GX_GM_1_0, GX_IDENTITY, GX_INDTEXSTAGE0, GX_INDTEXSTAGE1, GX_INDTEXSTAGE2, GX_INDTEXSTAGE3, GX_ITS_1, GX_LEQUAL, GX_LIGHT_NULL, GX_LO_CLEAR, GX_LO_SET, GX_MAX_TEVSTAGE, GX_MAX_VTXFMT, GX_MTX3x4, GX_PF_RGB8_Z24, GX_PNMTX0, GX_PTIDENTITY, GX_READ_FF, GX_REPLACE, GX_SRC_REG, GX_SRC_VTX, GX_TEV_KASEL_1, GX_TEV_KCSEL_1_4, GX_TEV_SWAP0, GX_TEV_SWAP1, GX_TEV_SWAP2, GX_TEV_SWAP3, GX_TEVSTAGE0, GX_TEVSTAGE1, GX_TEVSTAGE10, GX_TEVSTAGE11, GX_TEVSTAGE12, GX_TEVSTAGE13, GX_TEVSTAGE14, GX_TEVSTAGE15, GX_TEVSTAGE2, GX_TEVSTAGE3, GX_TEVSTAGE4, GX_TEVSTAGE5, GX_TEVSTAGE6, GX_TEVSTAGE7, GX_TEVSTAGE8, GX_TEVSTAGE9, GX_TEXCACHE_32K, GX_TEXCOORD0, GX_TEXCOORD1, GX_TEXCOORD2, GX_TEXCOORD3, GX_TEXCOORD4, GX_TEXCOORD5, GX_TEXCOORD6, GX_TEXCOORD7, GX_TEXCOORD_NULL, GX_TEXMAP0, GX_TEXMAP1, GX_TEXMAP2, GX_TEXMAP3, GX_TEXMAP4, GX_TEXMAP5, GX_TEXMAP6, GX_TEXMAP7, GX_TEXMAP_NULL, GX_TF_Z8, GX_TG_MTX2x4, GX_TG_TEX0, GX_TG_TEX1, GX_TG_TEX2, GX_TG_TEX3, GX_TG_TEX4, GX_TG_TEX5, GX_TG_TEX6, GX_TG_TEX7, GX_TLUT_1K, GX_TLUT_256, GX_TO_ZERO, GX_TRUE, GX_VTXFMT0, GX_WARN_ALL, GX_WRITE_RAS_REG, GX_WRITE_U32, GX_WRITE_U8, GX_WRITE_XF_REG, GX_ZC_LINEAR, GX_ZT_DISABLE, GXClearBoundingBox, GXClearVtxDesc, GXEnableTexOffsets, GXInitFifoBase, GXInitTexCacheRegion, GXInitTlutRegion, GXInvalidateTexAll, GXInvalidateVtxCache, GXLoadNrmMtxImm, GXLoadPosMtxImm, GXLoadTexMtxImm, GXMpal480IntDf, GXNtsc480IntDf, GXPal528IntDf, GXPokeAlphaMode, GXPokeAlphaRead, GXPokeAlphaUpdate, GXPokeBlendMode, GXPokeColorUpdate, GXPokeDither, GXPokeDstAlpha, GXPokeZMode, GXSetAlphaCompare, GXSetAlphaUpdate, GXSetBlendMode, GXSetChanAmbColor, GXSetChanCtrl, GXSetChanMatColor, GXSetClipMode, GXSetColorUpdate, GXSetCoPlanar, GXSetCopyClamp, GXSetCopyClear, GXSetCopyFilter, GXSetCPUFifo, GXSetCullMode, GXSetCurrentMtx, GXSetDispCopyDst, GXSetDispCopyFrame2Field, GXSetDispCopyGamma, GXSetDispCopySrc, GXSetDispCopyYScale, GXSetDither, GXSetDstAlpha, GXSetFieldMask, GXSetFieldMode, GXSetFog, GXSetFogRangeAdj, GXSetGPFifo, GXSetIndTexCoordScale, GXSetLineWidth, GXSetNumChans, GXSetNumIndStages, GXSetNumTevStages, GXSetNumTexGens, GXSetPixelFmt, GXSetPointSize, GXSetScissor, GXSetScissorBoxOffset, GXSetTevDirect, GXSetTevKAlphaSel, GXSetTevKColorSel, GXSetTevOp, GXSetTevOrder, GXSetTevSwapMode, GXSetTevSwapModeTable, GXSetTexCoordGen, GXSetTexRegionCallback, GXSetTlutRegionCallback, GXSetVerifyCallback, GXSetViewport, GXSetZCompLoc, GXSetZMode, GXSetZTexture, __GXData_struct::inDispList, __GXData_struct::iref, __GXData_struct::lpSize, __GXData_struct::nextTexRgn, __GXData_struct::nextTexRgnCI, OSPhysicalToUncached, __GXData_struct::peCtrl, __GXVerifyData::rasRegs, rmode, _GXRenderModeObj::sample_pattern, SET_REG_FIELD, size, __GXData_struct::suScis0, __GXData_struct::suScis1, __GXData_struct::suTs0, __GXData_struct::suTs1, __GXData_struct::tcsManEnab, __GXData_struct::teva, __GXData_struct::tevc, __GXData_struct::tevKsel, __GXData_struct::texmapId, __GXData_struct::TexRegions, __GXData_struct::TexRegionsCI, __GXData_struct::TlutRegions, __GXData_struct::tref, TRUE, __GXData_struct::vatA, __GXData_struct::vatB, __GXVerifyData::verifyLevel, _GXRenderModeObj::vfilter, VI_MPAL, VI_NTSC, VI_PAL, VIGetTvFormat, _GXRenderModeObj::viHeight, __GXData_struct::vNum, _GXRenderModeObj::xfbHeight, __GXVerifyData::xfLightDirty, __GXVerifyData::xfMtxDirty, __GXVerifyData::xfNrmDirty, __GXVerifyData::xfRegsDirty, __GXData_struct::zmode.
Referenced by DEMOInit, DEMOReInit.