GXFrameBuf.c
GXRenderModeObj GXNtsc240Ds
GXRenderModeObj GXNtsc240DsAa
GXRenderModeObj GXNtsc240Int
GXRenderModeObj GXNtsc240IntAa
GXRenderModeObj GXNtsc480IntDf
Referenced by __DEMOInitRenderMode, GXInit.
GXRenderModeObj GXNtsc480Int
GXRenderModeObj GXNtsc480IntAa
GXRenderModeObj GXNtsc480Prog
GXRenderModeObj GXNtsc480ProgAa
GXRenderModeObj GXMpal240Ds
GXRenderModeObj GXMpal240DsAa
GXRenderModeObj GXMpal240Int
GXRenderModeObj GXMpal240IntAa
GXRenderModeObj GXMpal480IntDf
Referenced by __DEMOInitRenderMode, GXInit.
GXRenderModeObj GXMpal480Int
GXRenderModeObj GXMpal480IntAa
GXRenderModeObj GXPal264Ds
GXRenderModeObj GXPal264DsAa
GXRenderModeObj GXPal264Int
GXRenderModeObj GXPal264IntAa
GXRenderModeObj GXPal528IntDf
Referenced by __DEMOInitRenderMode, GXInit.
GXRenderModeObj GXPal528Int
GXRenderModeObj GXPal524IntAa
GXRenderModeObj GXRmHW
void GXAdjustForOverscan(GXRenderModeObj *rmin, GXRenderModeObj *rmout, u16 hor, u16 ver)
References CARD_MAX_MOUNT_STEP, _GXRenderModeObj::fbWidth, VI_XFB_MODE_SF.
Referenced by __DEMOInitRenderMode.
void GXSetDispCopySrc(u16 left, u16 top, u16 wd, u16 ht)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cpDispSize, __GXData_struct::cpDispSrc, SET_REG_FIELD.
Referenced by __DEMOInitGX, GXInit.
void GXSetTexCopySrc(u16 left, u16 top, u16 wd, u16 ht)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cpTexSize, __GXData_struct::cpTexSrc, SET_REG_FIELD.
void GXSetDispCopyDst(u16 wd, u16 ht)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cpDispStride, SET_REG_FIELD.
Referenced by __DEMOInitGX, GXInit.
void GXSetTexCopyDst(u16 wd, u16 ht, GXTexFmt fmt, GXBool mipmap)
References __GetImageTileCount, __GXData, _GX_TF_ZTF, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cpTex, __GXData_struct::cpTexStride, __GXData_struct::cpTexZ, GX_CTF_YUVA8, GX_TF_I4, GX_TF_I8, GX_TF_IA4, GX_TF_IA8, GX_TF_Z16, SET_REG_FIELD.
void GXSetDispCopyFrame2Field(GXCopyMode mode)
References __GXData, CHECK_GXBEGIN, __GXData_struct::cpDisp, __GXData_struct::cpTex, SET_REG_FIELD.
Referenced by GXInit.
void GXSetCopyClamp(GXFBClamp clamp)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cpDisp, __GXData_struct::cpTex, SET_REG_FIELD.
Referenced by GXInit.
u32 GXSetDispCopyYScale(f32 vscale)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cpDisp, __GXData_struct::cpDispSize, GET_REG_FIELD, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by __DEMOInitGX, GXInit.
void GXSetCopyClear(GXColor clear_clr, u32 clear_z)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by DEMOWinInit, GXInit.
void GXSetCopyFilter(GXBool aa, const u8 sample_pattern[12][2], GXBool vf, const u8 vfilter[7])
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, SET_REG_FIELD.
Referenced by __DEMOInitGX, GXInit.
void GXSetDispCopyGamma(GXGamma gamma)
References __GXData, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cpDisp, SET_REG_FIELD.
Referenced by __DEMOInitGX, GXInit.
void GXCopyDisp(void *dest, GXBool clear)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode0, __GXData_struct::cpDisp, __GXData_struct::cpDispSize, __GXData_struct::cpDispSrc, __GXData_struct::cpDispStride, FALSE, GET_REG_FIELD, GX_WRITE_RAS_REG, __GXData_struct::peCtrl, SET_REG_FIELD, TRUE, __GXData_struct::zmode.
Referenced by __BypassDoneRender, __DEMOInitGX, DEMODoneRender.
void GXCopyTex(void *dest, GXBool clear)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, __GXData_struct::cmode0, __GXData_struct::cpTex, __GXData_struct::cpTexSize, __GXData_struct::cpTexSrc, __GXData_struct::cpTexStride, __GXData_struct::cpTexZ, GX_WRITE_RAS_REG, __GXData_struct::peCtrl, SET_REG_FIELD, __GXData_struct::zmode.
void GXClearBoundingBox(void)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG.
Referenced by GXInit.
void GXReadBoundingBox(u16 *left, u16 *top, u16 *right, u16 *bottom)
References CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, PE_PI_XBOUND0_ID, PE_PI_XBOUND1_ID, PE_PI_YBOUND0_ID, PE_PI_YBOUND1_ID.