List.c
void DSInitList(DSListPtr list, Ptr obj, DSLinkPtr link)
References CARD_MAX_MOUNT_STEP, NULL.
Referenced by DSInitCache, DSInitHTable.
void DSInsertListObject(DSListPtr list, Ptr cursor, Ptr obj)
References CARD_MAX_MOUNT_STEP, NULL.
Referenced by DSAddCacheNode, DSInsertHTableObj.
void DSRemoveListObject(DSListPtr list, Ptr obj)
References CARD_MAX_MOUNT_STEP, NULL, Prev.
Referenced by DSEmptyCache, DSPurgeCache, DSReleaseCacheObj.
void DSAttachList(DSListPtr baseList, DSListPtr attachList)
References CARD_MAX_MOUNT_STEP.
Referenced by DSHTableToList.
void * DSNextListObj(DSListPtr list, Ptr obj)
References CARD_MAX_MOUNT_STEP, NULL.
Referenced by DSHTableHead, DSNextHTableObj.