OSInterrupt.c
__OSInterruptHandler* InterruptHandlerTable
Referenced by __OSGetInterruptHandler, __OSInterruptInit, __OSSetInterruptHandler.
OSInterruptMask InterruptPrioTable[][]
Referenced by __OSDispatchInterrupt.
static asm void ExternalInterruptHandler(register __OSException exception, register OSContext *context)
References __OSDispatchInterrupt, CARD_MAX_MOUNT_STEP, OS_EXCEPTION_SAVE_GPRS.
Referenced by __OSInterruptInit.
void __RAS_OSDisableInterrupts_begin(void)
Referenced by OSDisableInterrupts.
void __RAS_OSDisableInterrupts_end(void)
Referenced by OSDisableInterrupts.
asm BOOL OSDisableInterrupts(void)
References __RAS_OSDisableInterrupts_begin, __RAS_OSDisableInterrupts_end, blr, CARD_MAX_MOUNT_STEP, FALSE, r3, r4.
Referenced by __AI_set_stream_sample_rate, __AXOutQuit, __AXServiceCallbackStack, __CARDGetControlBlock, __CARDPutControlBlock, __CARDSync, __DTKBackward, __DTKForward, __DVDCheckWaitingQueue, __DVDDequeueWaitingQueue, __DVDLowSetWAType, __DVDPopWaitingQueue, __DVDPrepareResetAsync, __DVDPushWaitingQueue, __GXSaveCPUFifoAux, __OSDoHotReset, __OSGetSystemTime, __OSMaskInterrupts, __OSReboot, __OSSetTime, __OSUnmaskInterrupts, __SEQPushSequenceList, __SEQRemoveSequenceFromList, __SITransfer, __SYNAddSynthToList, __SYNRemoveSynthFromList, __VIGetAdjustingValues, __VISetAdjustingValues, AIInitDMA, AIRegisterDMACallback, AIRegisterStreamCallback, AISetDSPSampleRate, AISetStreamPlayState, ARAlloc, ARFree, ARGetDMAStatus, ARInit, ARQFlushQueue, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest, ARRegisterDMACallback, ARStartDMA, AXAcquireVoice, AXFreeVoice, AXFXChorusInit, AXFXChorusSettings, AXFXChorusShutdown, AXFXDelayInit, AXFXDelaySettings, AXFXDelayShutdown, AXFXReverbHiInit, AXFXReverbHiSettings, AXFXReverbHiShutdown, AXFXReverbStdInit, AXFXReverbStdSettings, AXFXReverbStdShutdown, AXGetProfile, AXSetVoiceAddr, AXSetVoiceAdpcm, AXSetVoiceAdpcmLoop, AXSetVoiceCurrentAddr, AXSetVoiceDpop, AXSetVoiceEndAddr, AXSetVoiceFir, AXSetVoiceItdOn, AXSetVoiceItdTarget, AXSetVoiceLoop, AXSetVoiceLoopAddr, AXSetVoiceMix, AXSetVoicePriority, AXSetVoiceSrc, AXSetVoiceSrcRatio, AXSetVoiceSrcType, AXSetVoiceState, AXSetVoiceType, AXSetVoiceUpdateIncrement, AXSetVoiceUpdateWrite, AXSetVoiceVe, AXSetVoiceVeDelta, CARDCancel, CARDCheckExAsync, CARDMountAsync, CARDProbeEx, DBInitComm, DBQueryData, DBRead, DBWrite, DEMOWinClearBuffer, DEMOWinClearRow, DEMOWinClearWindow, DEMOWinDestroyWindow, DEMOWinLogPrintf, DEMOWinPrintfXY, DEMOWinRefresh, DEMOWinScrollWindow, DoUnmount, DSPAddTask, DSPAssertInt, DSPAssertTask, DSPCancelTask, DSPHalt, DSPInit, DSPReset, DSPUnhalt, DTKQueueTrack, DTKRemoveTrack, DVDCancel, DVDCancelAll, DVDCancelAllAsync, DVDCancelAsync, DVDCancelStream, DVDChangeDisk, DVDCheckDisk, DVDGetCommandBlockStatus, DVDGetDriveStatus, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInquiry, DVDLowSetResetCoverCallback, DVDPause, DVDPrepareStream, DVDReadPrio, DVDResume, DVDSeekPrio, DVDStopStreamAtEnd, EXIAttach, EXIDeselect, EXIDetach, EXIDma, EXIImm, EXILock, EXIProbe, EXISelect, EXISetExiCallback, EXISync, EXIUnlock, GXDisableBreakPt, GXEnableBreakPt, GXEndDisplayList, GXInitFifoPtrs, GXRedirectWriteGatherPipe, GXSetBreakPtCallback, GXSetCPUFifo, GXSetCurrentGXThread, GXSetDrawDone, GXSetDrawDoneCallback, GXSetDrawSync, GXSetDrawSyncCallback, GXSetGPFifo, GXWaitDrawDone, issueCommand, LCEnable, LockSram, MIXInitChannel, OSCancelAlarm, OSCancelThread, OSCheckActiveThreads, OSCreateThread, OSDetachThread, OSDisableScheduler, OSDumpContext, OSEnableScheduler, OSExitThread, OSGetResetSwitchState, OSInit, OSJamMessage, OSJoinThread, OSLockMutex, OSPanic, OSReceiveMessage, OSResetSystem, OSResumeThread, OSSendMessage, OSSetAbsAlarm, OSSetAlarm, OSSetInterruptMask, OSSetPeriodicAlarm, OSSetResetCallback, OSSetThreadPriority, OSSleepThread, OSStartTimer, OSStopTimer, OSSuspendThread, OSTryLockMutex, OSUnlockMutex, OSWaitCond, OSWakeupThread, OSYieldThread, PADControlAllMotors, PADControlMotor, PADDisable, PADRead, PADRecalibrate, PADReset, PADSetAnalogMode, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartFrame, PERFStopAutoSampling, PopWaitingQueuePrio, Run, SelectThread, SEQSetState, SIDisablePolling, SIEnablePolling, SISetXY, SISync, SITransfer, SYNQuitSynth, VIConfigure, VIConfigurePan, VIFlush, VIGetCurrentLine, VIGetDTVStatus, VIGetNextField, VISet3D, VISetBlack, VISetNextFrameBuffer, VISetNextRightFrameBuffer, VISetPostRetraceCallback, VISetPreRetraceCallback, VIWaitForRetrace.
asm BOOL OSEnableInterrupts(void)
References blr, CARD_MAX_MOUNT_STEP, FALSE, r3, r4.
Referenced by __AXOutNewFrame, __OSReboot, OSInit, SelectThread.
asm BOOL OSRestoreInterrupts(register BOOL level)
References blr, CARD_MAX_MOUNT_STEP, FALSE, r4, r5.
Referenced by __OSMaskInterrupts, __OSUnmaskInterrupts, OSSetInterruptMask.
__OSInterruptHandler __OSSetInterruptHandler(__OSInterrupt interrupt, __OSInterruptHandler handler)
References CARD_MAX_MOUNT_STEP, InterruptHandlerTable.
Referenced by __GXFifoInit, __GXPEInit, AIInit, ARInit, DBInitInterrupts, DSPInit, DVDInit, EXIInit, HIOInit, OSInit, SIInit, VIInit.
__OSInterruptHandler __OSGetInterruptHandler(__OSInterrupt interrupt)
References CARD_MAX_MOUNT_STEP, InterruptHandlerTable.
Referenced by __OSDispatchInterrupt, SetExiInterruptMask.
void __OSInterruptInit(void)
References __OS_INTERRUPT_MAX, __OSMaskInterrupts, __OSSetExceptionHandler, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, ExternalInterruptHandler, InterruptHandlerTable, OS_INTERRUPTMASK_AI, OS_INTERRUPTMASK_DSP, OS_INTERRUPTMASK_EXI, OS_INTERRUPTMASK_MEM, OS_INTERRUPTMASK_PI, OSPhysicalToCached.
Referenced by OSInit.
static u32 SetInterruptMask(OSInterruptMask mask, OSInterruptMask current)
References __OS_INTERRUPT_AI_AI, __OS_INTERRUPT_DSP_AI, __OS_INTERRUPT_DSP_ARAM, __OS_INTERRUPT_DSP_DSP, __OS_INTERRUPT_EXI_0_EXI, __OS_INTERRUPT_EXI_0_EXT, __OS_INTERRUPT_EXI_0_TC, __OS_INTERRUPT_EXI_1_EXI, __OS_INTERRUPT_EXI_1_EXT, __OS_INTERRUPT_EXI_1_TC, __OS_INTERRUPT_EXI_2_EXI, __OS_INTERRUPT_EXI_2_TC, __OS_INTERRUPT_MEM_0, __OS_INTERRUPT_MEM_1, __OS_INTERRUPT_MEM_2, __OS_INTERRUPT_MEM_3, __OS_INTERRUPT_PI_CP, __OS_INTERRUPT_PI_DEBUG, __OS_INTERRUPT_PI_DI, __OS_INTERRUPT_PI_ERROR, __OS_INTERRUPT_PI_HSP, __OS_INTERRUPT_PI_PE_FINISH, __OS_INTERRUPT_PI_PE_TOKEN, __OS_INTERRUPT_PI_RSW, __OS_INTERRUPT_PI_SI, __OS_INTERRUPT_PI_VI, CARD_MAX_MOUNT_STEP, OS_INTERRUPTMASK_AI_AI, OS_INTERRUPTMASK_DSP_AI, OS_INTERRUPTMASK_DSP_ARAM, OS_INTERRUPTMASK_DSP_DSP, OS_INTERRUPTMASK_EXI_0_EXI, OS_INTERRUPTMASK_EXI_0_EXT, OS_INTERRUPTMASK_EXI_0_TC, OS_INTERRUPTMASK_EXI_1_EXI, OS_INTERRUPTMASK_EXI_1_EXT, OS_INTERRUPTMASK_EXI_1_TC, OS_INTERRUPTMASK_EXI_2_EXI, OS_INTERRUPTMASK_EXI_2_TC, OS_INTERRUPTMASK_MEM_0, OS_INTERRUPTMASK_MEM_1, OS_INTERRUPTMASK_MEM_2, OS_INTERRUPTMASK_MEM_3, OS_INTERRUPTMASK_MEM_ADDRESS, OS_INTERRUPTMASK_PI_CP, OS_INTERRUPTMASK_PI_DEBUG, OS_INTERRUPTMASK_PI_DI, OS_INTERRUPTMASK_PI_ERROR, OS_INTERRUPTMASK_PI_HSP, OS_INTERRUPTMASK_PI_PE_FINISH, OS_INTERRUPTMASK_PI_PE_TOKEN, OS_INTERRUPTMASK_PI_RSW, OS_INTERRUPTMASK_PI_SI, OS_INTERRUPTMASK_PI_VI.
Referenced by __OSMaskInterrupts, __OSUnmaskInterrupts, OSSetInterruptMask.
OSInterruptMask OSGetInterruptMask(void)
References OSPhysicalToCached.
OSInterruptMask OSSetInterruptMask(OSInterruptMask local)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, prev, SetInterruptMask.
OSInterruptMask __OSMaskInterrupts(OSInterruptMask global)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, prev, SetInterruptMask.
Referenced by __OSInterruptInit, __OSReboot, __OSResetSWInterruptHandler, AlarmHandlerForTimeout, DBGEXIInit, DBInitInterrupts, EXIDetach, EXIInit, EXISelect, EXTIntrruptHandler, OSSetResetCallback, SetExiInterruptMask, TCIntrruptHandler.
OSInterruptMask __OSUnmaskInterrupts(OSInterruptMask global)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, prev, SetInterruptMask.
Referenced by __GXFifoInit, __GXPEInit, __OSInterruptInit, __OSReboot, AIInit, ARInit, DBInitInterrupts, DSPInit, DVDInit, EXIAttach, EXIDeselect, EXIDma, EXIImm, HIOInit, OSSetResetCallback, SetExiInterruptMask, SIInit, VIInit.
void __OSDispatchInterrupt(__OSException exception, OSContext *context)
References __OSGetInterruptHandler, __OSInterruptNames, __OSPIErrors, __OSReschedule, __OSSpuriousInterrupts, CARD_MAX_MOUNT_STEP, InterruptPrioTable, OS_INTERRUPTMASK_AI_AI, OS_INTERRUPTMASK_DSP_AI, OS_INTERRUPTMASK_DSP_ARAM, OS_INTERRUPTMASK_DSP_DSP, OS_INTERRUPTMASK_EXI_0_EXI, OS_INTERRUPTMASK_EXI_0_EXT, OS_INTERRUPTMASK_EXI_0_TC, OS_INTERRUPTMASK_EXI_1_EXI, OS_INTERRUPTMASK_EXI_1_EXT, OS_INTERRUPTMASK_EXI_1_TC, OS_INTERRUPTMASK_EXI_2_EXI, OS_INTERRUPTMASK_EXI_2_TC, OS_INTERRUPTMASK_MEM_0, OS_INTERRUPTMASK_MEM_1, OS_INTERRUPTMASK_MEM_2, OS_INTERRUPTMASK_MEM_3, OS_INTERRUPTMASK_MEM_ADDRESS, OS_INTERRUPTMASK_PI_CP, OS_INTERRUPTMASK_PI_DEBUG, OS_INTERRUPTMASK_PI_DI, OS_INTERRUPTMASK_PI_ERROR, OS_INTERRUPTMASK_PI_HSP, OS_INTERRUPTMASK_PI_PE_FINISH, OS_INTERRUPTMASK_PI_PE_TOKEN, OS_INTERRUPTMASK_PI_RSW, OS_INTERRUPTMASK_PI_SI, OS_INTERRUPTMASK_PI_VI, OSDisableScheduler, OSDumpContext, OSEnableScheduler, OSLoadContext, OSPhysicalToCached, OSReport.
Referenced by ExternalInterruptHandler.