OSReboot.c
typedef struct _ApploaderHeader ApploaderHeader
volatile BOOL Prepared
Referenced by Callback, ReadApploader.
void* __OSSavedRegionStart
void* __OSSavedRegionEnd
void *BOOT_REGION_START AT_ADDRESS(0x812FDFF0)
void *BOOT_REGION_END AT_ADDRESS(0x812FDFEC)
u32 OS_RESET_CODE AT_ADDRESS(0x800030F0)
u8 OS_REBOOT_BOOL AT_ADDRESS(0x800030E2)
u32 OS_UNK_CODE AT_ADDRESS(0x817FFFF8)
u32 OS_HOT_RESET_CODE AT_ADDRESS(0x817FFFFC)
static ApploaderHeader Header ALIGN(32)
static asm void Run(register u32 addr)
References blr, CARD_MAX_MOUNT_STEP, ICFlashInvalidate, isync, OSDisableInterrupts, sync.
Referenced by __OSReboot.
static void ReadApploader(DVDCommandBlock *dvdCmd, void *addr, u32 offset, u32 numBytes)
References __OSDoHotReset, CARD_MAX_MOUNT_STEP, DVDReadAbsAsyncForBS, FALSE, NULL, Prepared, TRUE.
Referenced by __OSReboot.
static void Callback(s32 result, DVDCommandBlock *block)
References Prepared, TRUE.
void __OSReboot(u32 resetCode, BOOL forceMenu)
References __DVDPrepareResetAsync, __OSDoHotReset, __OSMaskInterrupts, __OSUnmaskInterrupts, Callback, CARD_MAX_MOUNT_STEP, DVDCheckDisk, DVDInit, ICInvalidateRange, OS_BOOTROM_ADDR, OSClearContext, OSDisableInterrupts, OSEnableInterrupts, OSRoundUp32B, OSSetCurrentContext, ReadApploader, Run, TRUE.
Referenced by OSResetSystem.