OSAlarm.h
typedef struct OSAlarm OSAlarm
typedef void(* OSAlarmHandler) (OSAlarm *alarm, OSContext *context))(OSAlarm *alarm, OSContext *context)
void OSInitAlarm(void)
References __OSGetExceptionHandler, __OSSetExceptionHandler, AlarmQueue, DecrementerExceptionHandler, OSAlarmQueue::head, NULL, OSAlarmQueue::tail.
Referenced by __DVDInitWA, CARDInit, DVDInit, PERFInit.
void OSSetAlarm(OSAlarm *alarm, OSTime tick, OSAlarmHandler handler)
References CARD_MAX_MOUNT_STEP, InsertAlarm, OSCheckAlarmQueue, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts, OSAlarm::period.
Referenced by SetBreakAlarm, SetTimeoutAlarm, SetupTimeoutAlarm, stateCoverClosed, WaitBeforeRead.
void OSSetAbsAlarm(OSAlarm *alarm, OSTime time, OSAlarmHandler handler)
Referenced by SITransfer.
void OSSetPeriodicAlarm(OSAlarm *alarm, OSTime start, OSTime period, OSAlarmHandler handler)
References CARD_MAX_MOUNT_STEP, InsertAlarm, OSCheckAlarmQueue, OSDisableInterrupts, OSRestoreInterrupts, OSAlarm::period, OSAlarm::start.
Referenced by PERFStartAutoSampling.
void OSCreateAlarm(OSAlarm *alarm)
References OSAlarm::handler.
Referenced by CARDInit, SetBreakAlarm, SetTimeoutAlarm, stateCoverClosed, WaitBeforeRead.
void OSCancelAlarm(OSAlarm *alarm)
References AlarmQueue, CARD_MAX_MOUNT_STEP, OSAlarm::handler, OSAlarmQueue::head, OSAlarm::next, next, OSCheckAlarmQueue, OSDisableInterrupts, OSRestoreInterrupts, DVDCommandBlock::prev, OSAlarm::prev, SetTimer, OSAlarmQueue::tail.
Referenced by __CARDExiHandler, __CARDExtHandler, __DVDInterruptHandler, CARDMountAsync, DoUnmount, PERFStopAutoSampling, SetupTimeoutAlarm, SITransferNext.
BOOL OSCheckAlarmQueue(void)
References AlarmQueue, ASSERTREPORT, OSAlarmQueue::head, OSAlarm::next, NULL, OSAlarm::prev, OSAlarmQueue::tail, TRUE.
Referenced by DecrementerExceptionCallback, OSCancelAlarm, OSSetAbsAlarm, OSSetAlarm, OSSetPeriodicAlarm.