OSPrivate.h
SEC_INIT
char* __OSExceptionNames[15][15]
Referenced by __OSUnhandledException.
volatile BOOL __OSCurrHeap
Referenced by OSDestroyHeap, OSInitAlloc, OSSetCurrentHeap.
u64 __OSSpuriousInterrupts
Referenced by __OSDispatchInterrupt.
char* __OSInterruptNames[33][33]
Referenced by __OSDispatchInterrupt.
char* __OSPIErrors[8][8]
Referenced by __OSDispatchInterrupt.
OSTime __OSStartTime
void* BOOT_REGION_START
void* BOOT_REGION_END
u32 __OSIsDebuggerPresent(void)
References OSPhysicalToCached.
void __OSPSInit(void)
void __OSInitAudioSystem(void)
References __DSPWorkBuffer, CARD_MAX_MOUNT_STEP, DCFlushRange, DSPInitCode, OSGetTick.
Referenced by OSInit.
void __OSStopAudioSystem(void)
References CARD_MAX_MOUNT_STEP, OSGetTick, waitUntil.
Referenced by OSResetSystem.
void __OSCacheInit(void)
void __OSContextInit(void)
References __OS_EXCEPTION_FLOATING_POINT, __OSFPUContext, __OSSetExceptionHandler, DBPrintf, NULL, OSSwitchFPUContext.
Referenced by OSInit.
void __OSUnhandledException(u8 exception, OSContext *context, u32 dsisr, u32 dar)
void __RAS_OSDisableInterrupts_begin(void)
void __RAS_OSDisableInterrupts_end(void)
__OSInterruptHandler __OSSetInterruptHandler(__OSInterrupt BOOLerrupt, __OSInterruptHandler handler)
__OSInterruptHandler __OSGetInterruptHandler(__OSInterrupt BOOLerrupt)
Referenced by __OSDispatchInterrupt.
void __OSInterruptInit(void)
References __OS_INTERRUPT_MAX, __OSMaskInterrupts, __OSSetExceptionHandler, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, ExternalInterruptHandler, InterruptHandlerTable, OS_INTERRUPTMASK_AI, OS_INTERRUPTMASK_DSP, OS_INTERRUPTMASK_EXI, OS_INTERRUPTMASK_MEM, OS_INTERRUPTMASK_PI, OSPhysicalToCached.
Referenced by OSInit.
OSInterruptMask __OSMaskInterrupts(OSInterruptMask global)
Referenced by __OSInterruptInit.
OSInterruptMask __OSUnmaskInterrupts(OSInterruptMask global)
Referenced by __OSInterruptInit.
void __OSDispatchInterrupt(__OSException exception, OSContext *context)
Referenced by ExternalInterruptHandler.
void __OSModuleInit(void)
References CARD_MAX_MOUNT_STEP.
Referenced by OSInit.
void __OSUnlockAllMutex(OSThread *thread)
References CARD_MAX_MOUNT_STEP, OSMutex::count, DEQUEUE_HEAD, OSMutexQueue::head, OSWakeupThread, OSMutex::queue, OSThread::queueMutex, OSMutex::thread.
Referenced by OSCancelThread, OSExitThread.
BOOL __OSCheckDeadLock(OSThread *thread)
References FALSE, OSThread::mutex, OSMutex::thread, TRUE.
Referenced by OSCheckActiveThreads, OSLockMutex.
BOOL __OSCheckMutexes(OSThread *thread)
References __OSCheckMutex, FALSE, OSMutexQueue::head, OSMutex::link, OSMutexLink::next, OSThread::queueMutex, OSMutex::thread, TRUE.
Referenced by OSCheckActiveThreads.
void __OSDoHotReset(s32 code)
References CARD_MAX_MOUNT_STEP, ICFlashInvalidate, OSDisableInterrupts, Reset, VI_DISP_CONFIG.
Referenced by __OSReboot, OSResetSystem, ReadApploader.
void __OSResetSWInterruptHandler(s16 exception, OSContext *context)
References __OSGetSystemTime, __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, Down, HoldDown, LastState, NULL, OS_INTERRUPTMASK_PI_RSW, OSMicrosecondsToTicks, PI_INTSR, ResetCallback, TRUE.
Referenced by OSInit.
BOOL __OSGetRTC(u32 *rtc)
References CARD_MAX_MOUNT_STEP, FALSE, GetRTC, t0, t1, TRUE.
BOOL __OSSetRTC(u32 rtc)
References CARD_MAX_MOUNT_STEP, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL.
void __OSInitSram()
References CARD_MAX_MOUNT_STEP, ReadSram, RTC_SRAM_SIZE.
Referenced by OSInit.
OSSram * __OSLockSram(void)
References LockSram.
Referenced by __OSGetBootMode, __OSSetBootMode, CARDFormatAsync, ImportAdjustingValues, OSGetLanguage, OSGetProgressiveMode, OSGetSoundMode, OSGetVideoMode, OSResetSystem, OSSetLanguage, OSSetProgressiveMode, OSSetSoundMode, OSSetVideoMode.
OSSramEx * __OSLockSramEx(void)
References LockSram.
Referenced by __DVDStoreErrorCode, CARDFormatAsync, DoMount, GetWirelessID, SetWirelessID, VerifyID.
BOOL __OSUnlockSram(BOOL commit)
References CARD_MAX_MOUNT_STEP, UnlockSram.
Referenced by __OSGetBootMode, __OSSetBootMode, CARDFormatAsync, ImportAdjustingValues, OSGetLanguage, OSGetProgressiveMode, OSGetSoundMode, OSGetVideoMode, OSResetSystem, OSSetLanguage, OSSetProgressiveMode, OSSetSoundMode, OSSetVideoMode.
BOOL __OSUnlockSramEx(BOOL commit)
References CARD_MAX_MOUNT_STEP, UnlockSram.
Referenced by __DVDStoreErrorCode, CARDFormatAsync, DoMount, GetWirelessID, SetWirelessID, VerifyID.
BOOL __OSSyncSram(void)
References CARD_MAX_MOUNT_STEP.
Referenced by CallResetFunctions, OSResetSystem.
BOOL __OSCheckSram(void)
References CARD_MAX_MOUNT_STEP, OSSram::checkSum, OSSram::checkSumInv, OSSram::counterBias.
BOOL __OSReadROM(void *buffer, s32 length, long offset)
References buffer, CARD_MAX_MOUNT_STEP, DCInvalidateRange, EXIDeselect, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL.
Referenced by ReadROM.
BOOL __OSReadROMAsync(void *buffer, s32 length, long offset, void(*callback)())
References __OSReadROMCallback, buffer, CARD_MAX_MOUNT_STEP, DCInvalidateRange, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL.
u16 __OSGetBootMode(void)
References __OSLockSram, __OSUnlockSram, OSSram::ntd.
void __OSSetBootMode(u16 ntd)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, OSSram::ntd.
void __OSSystemCallVectorStart()
void __OSSystemCallVectorEnd()
void __OSInitSystemCall(void)
References __OSSystemCallVectorEnd, __OSSystemCallVectorStart, CARD_MAX_MOUNT_STEP, DCFlushRangeNoSync, ICInvalidateRange, OSPhysicalToCached.
Referenced by OSInit.
void __OSThreadInit(void)
References __OSActiveThreadQueue, __OSCurrentThread, __OSFPUContext, _stack_addr, _stack_end, OSThread::attr, OSThread::base, CARD_MAX_MOUNT_STEP, OSThread::context, DefaultThread, ENQUEUE_THREAD, OSMutexQueue::head, IdleContext, MSR_FP, OSThread::mutex, OSClearContext, OSInitThreadQueue, OSSetCurrentContext, PPCMfmsr, OSThread::priority, OSThread::queueJoin, OSThread::queueMutex, Reschedule, RunQueue, RunQueueBits, RunQueueHint, OSThread::stackBase, OSThread::stackEnd, OSThread::state, OSThread::suspend, OSMutexQueue::tail, OSThread::val.
Referenced by OSInit.
s32 __OSGetEffectivePriority(OSThread *thread)
References OSThread::base, CARD_MAX_MOUNT_STEP, OSThreadQueue::head, OSMutexQueue::head, OSMutex::link, OSMutexLink::next, OSThread::priority, OSMutex::queue, OSThread::queueMutex.
Referenced by OSCheckActiveThreads, OSResumeThread, OSUnlockMutex, OSWaitCond, UpdatePriority.
void __OSPromoteThread(OSThread *thread, s32 priority)
References OSThread::priority, SetEffectivePriority, OSThread::suspend.
Referenced by OSLockMutex.
void __OSReschedule(void)
References RunQueueHint, SelectThread.
Referenced by __OSDispatchInterrupt, DecrementerExceptionCallback, OSCancelThread, OSExitThread, OSResumeThread, OSSetThreadPriority, OSSleepThread, OSSuspendThread, OSWakeupThread.
void __OSSetTime(s64 time)
References __SetTime, CARD_MAX_MOUNT_STEP, EXIProbeReset, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts.
s64 __OSGetSystemTime()
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts.
Referenced by __DVDInterruptHandler, __OSResetSWInterruptHandler, DVDLowGetCoverStatus, DVDLowRead, DVDLowReset, OSGetResetSwitchState, Read.
void __OSSetTick(register u32 newTicks)
References CARD_MAX_MOUNT_STEP.
void __OSReboot(u32 resetCode, BOOL forceMenu)
References __DVDPrepareResetAsync, __OSDoHotReset, __OSMaskInterrupts, __OSUnmaskInterrupts, Callback, CARD_MAX_MOUNT_STEP, DVDCheckDisk, DVDInit, ICInvalidateRange, OS_BOOTROM_ADDR, OSClearContext, OSDisableInterrupts, OSEnableInterrupts, OSRoundUp32B, OSSetCurrentContext, ReadApploader, Run, TRUE.
Referenced by OSResetSystem.
SEC_INIT ASM void __init_hardware(void)
References __OSCacheInit, __OSPSInit, CARD_MAX_MOUNT_STEP, MSR_FP.
SEC_INIT ASM void __flush_cache(void *address, u32 size)
References CARD_MAX_MOUNT_STEP.
void __init_user(void)
References __init_cpp.
Referenced by __start.
void __init_cpp(void)
References CARD_MAX_MOUNT_STEP.
Referenced by __init_user.
void __fini_cpp(void)
References CARD_MAX_MOUNT_STEP.
Referenced by exit.
void _ExitProcess(void)
References PPCHalt.
Referenced by abort, exit.
void __start(void)
References __init_data, __init_hardware, __init_registers, __init_user, ARENAHI_ADDR, BOOTINFO2_ADDR, CARD_MAX_MOUNT_STEP, DBInit, EXCEPTIONMASK_ADDR, exit, main, OS_BI2_DEBUGFLAG_OFFSET, OSInit.
SEC_INIT void __copy_rom_section(void *dst, const void *src, u32 size)
References __flush_cache, CARD_MAX_MOUNT_STEP.
Referenced by __init_data.
SEC_INIT void __init_bss_section(void *dst, u32 size)
References CARD_MAX_MOUNT_STEP.
Referenced by __init_data.
SEC_INIT void __init_registers(void)
References _SDA2_BASE_, _SDA_BASE_, _stack_addr, CARD_MAX_MOUNT_STEP.
Referenced by __start.
SEC_INIT void __init_data(void)
References __copy_rom_section, __init_bss_section, _bss_init_info, _rom_copy_info, CARD_MAX_MOUNT_STEP, TRUE.
Referenced by __start.
s64 __get_clock(void)
u32 __get_time(void)
References OSGetTime, OSTicksToSeconds.
int __to_gm_time(void)