OSAlloc.c
ALIGNMENT
InRange
HEADERSIZE
MINOBJSIZE
ASSERTREPORT
typedef struct HeapDesc HeapDesc
typedef struct Cell Cell
volatile OSHeapHandle __OSCurrHeap
Referenced by AXFXChorusInit, AXFXChorusShutdown, AXFXDelaySettings, AXFXDelayShutdown, DEMOInit, DEMOInitROMFont, DEMOReInit, DEMOWinCreateWindow, DEMOWinDestroyWindow, DLcreate, DLcreate, DLdelete, DLdelete, LoadMemInfo, OSDestroyHeap, OSInitAlloc, OSSetCurrentHeap, ReverbHICreate, ReverbHIFree, ReverbHIModify, ReverbSTDCreate, ReverbSTDFree, ReverbSTDModify.
HeapDesc* HeapArray
Referenced by OSAddToHeap, OSAllocFixed, OSAllocFromHeap, OSCheckHeap, OSCreateHeap, OSDestroyHeap, OSDumpHeap, OSFreeToHeap, OSInitAlloc, OSReferentSize, OSSetCurrentHeap, OSVisitAllocated.
int NumHeaps
Referenced by OSAddToHeap, OSAllocFixed, OSAllocFromHeap, OSCheckHeap, OSCreateHeap, OSDestroyHeap, OSDumpHeap, OSInitAlloc, OSReferentSize, OSSetCurrentHeap, OSVisitAllocated.
void* ArenaStart
Referenced by OSAddToHeap, OSAllocFixed, OSCheckHeap, OSCreateHeap, OSFreeToHeap, OSInitAlloc, OSReferentSize.
void* ArenaEnd
Referenced by OSAddToHeap, OSAllocFixed, OSCheckHeap, OSCreateHeap, OSFreeToHeap, OSInitAlloc, OSReferentSize.
static Cell * DLAddFront(Cell *list, Cell *cell)
References CARD_MAX_MOUNT_STEP, Cell::next, Cell::prev.
Referenced by OSAllocFromHeap.
static Cell * DLLookup(Cell *list, Cell *cell)
References CARD_MAX_MOUNT_STEP, NULL.
Referenced by OSFreeToHeap, OSReferentSize.
static Cell * DLExtract(Cell *list, Cell *cell)
References CARD_MAX_MOUNT_STEP, Cell::next, NULL, Cell::prev.
Referenced by OSAllocFixed, OSAllocFromHeap, OSFreeToHeap.
static Cell * DLInsert(Cell *list, Cell *cell)
References CARD_MAX_MOUNT_STEP, DVDCommandBlock::next, next, NULL, DVDCommandBlock::prev, prev.
Referenced by OSAddToHeap, OSFreeToHeap.
static BOOL DLOverlap(Cell *list, void *start, void *end)
References CARD_MAX_MOUNT_STEP, FALSE, Cell::next, TRUE.
Referenced by OSAddToHeap, OSAllocFixed, OSCreateHeap.
static s32 DLSize(Cell *list)
References CARD_MAX_MOUNT_STEP, size, Cell::size.
Referenced by OSDestroyHeap.
void * OSAllocFromHeap(int heap, u32 size)
References CARD_MAX_MOUNT_STEP, DLAddFront, DLExtract, HeapArray, NULL, NumHeaps, OSReport, size.
Referenced by AXFXChorusInit, AXFXDelaySettings, DEMOInit, DEMOInitROMFont, DEMOReInit, DEMOWinCreateWindow, DLcreate, DLcreate, ReverbHICreate, ReverbSTDCreate.
void * OSAllocFixed(void *rstart, void *rend)
References ALIGNMENT, ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLExtract, DLOverlap, HeapDesc::free, HeapArray, MINOBJSIZE, NULL, NumHeaps, OFFSET, OSReport.
Referenced by LoadMemInfo.
void OSFreeToHeap(int heap, void *ptr)
References ALIGNMENT, ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLExtract, DLInsert, DLLookup, HeapArray, OFFSET, size.
Referenced by AXFXChorusShutdown, AXFXDelayShutdown, DEMOReInit, DEMOWinDestroyWindow, DLdelete, DLdelete, ReverbHIFree, ReverbHIModify, ReverbSTDFree, ReverbSTDModify.
int OSSetCurrentHeap(int heap)
References __OSCurrHeap, CARD_MAX_MOUNT_STEP, HeapArray, NumHeaps, prev, size.
Referenced by __DEMOInitMem, LoadMemInfo.
void * OSInitAlloc(void *arenaStart, void *arenaEnd, int maxHeaps)
References __OSCurrHeap, ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, HeapArray, NumHeaps, HeapDesc::size.
Referenced by __DEMOInitMem, LoadMemInfo.
int OSCreateHeap(void *start, void *end)
References ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLOverlap, HeapArray, NumHeaps, OSReport, size, HeapDesc::size.
Referenced by __DEMOInitMem, LoadMemInfo.
void OSDestroyHeap(int heap)
References __OSCurrHeap, CARD_MAX_MOUNT_STEP, DLSize, HeapArray, NumHeaps, OSReport, size.
void OSAddToHeap(int heap, void *start, void *end)
References ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLInsert, DLOverlap, HeapArray, NumHeaps, size.
s32 OSCheckHeap(int heap)
References ALIGNMENT, ArenaEnd, ArenaStart, ASSERTREPORT, CARD_MAX_MOUNT_STEP, HEADERSIZE, HeapArray, InRange, NULL, NumHeaps, OFFSET, size.
Referenced by OSDumpHeap.
u32 OSReferentSize(void *ptr)
References ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLLookup, HEADERSIZE, HeapArray, InRange, NumHeaps, OFFSET.
void OSDumpHeap(int heap)
References CARD_MAX_MOUNT_STEP, HeapArray, NULL, NumHeaps, OSCheckHeap, OSReport.
Referenced by LoadMemInfo.
void OSVisitAllocated(void(*visitor)(void *, u32))
References CARD_MAX_MOUNT_STEP, HEADERSIZE, HeapArray, NumHeaps, size.