OSExi.c
MAX_CHAN
STATE_IDLE
STATE_DMA
STATE_IMM
STATE_BUSY
STATE_SELECTED
STATE_ATTACHED
STATE_LOCKED
MAX_IMM
MAX_TYPE
MAX_DEV
MAX_FREQ
EXI_0LENGTH_EXILENGTH_MASK
EXI_READ
EXI_WRITE
EXI_RDWR
typedef void(* EXICallback) (s32, OSContext *))(s32, OSContext *)
typedef struct EXIControl EXIControl
unsigned int __gUnknown800030C0[2][2]
Referenced by EXIProbe, EXIProbeEx, EXIProbeReset.
EXIControl Ecb[3][3]
Referenced by CompleteTransfer, EXIAttach, EXIDeselect, EXIDetach, EXIDma, EXIGetState, EXIImm, EXIIntrruptHandler, EXILock, EXIProbe, EXISelect, EXISetExiCallback, EXISync, EXIUnlock, EXTIntrruptHandler, SetExiInterruptMask, TCIntrruptHandler.
static void SetExiInterruptMask(s32 chan, EXIControl *exi)
References __OSGetInterruptHandler, __OSMaskInterrupts, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, STATE_LOCKED.
Referenced by EXILock, EXISetExiCallback, EXIUnlock.
static void CompleteTransfer(s32 chan)
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN, STATE_BUSY, STATE_IMM.
int EXIImm(s32 chan, void *buf, long len, u32 type, EXICallback callback)
References __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIClearInterrupts, MAX_CHAN, MAX_IMM, MAX_TYPE, OSDisableInterrupts, OSRestoreInterrupts, STATE_BUSY, STATE_IMM, STATE_SELECTED.
Referenced by EXIGetID, EXIImmEx.
int EXIImmEx(s32 chan, void *buf, long len, u32 mode)
References CARD_MAX_MOUNT_STEP, EXIImm, EXISync.
int EXIDma(s32 chan, void *buf, long len, u32 type, EXICallback callback)
References __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXI_0LENGTH_EXILENGTH_MASK, EXI_READ, EXI_WRITE, EXIClearInterrupts, OFFSET, OSDisableInterrupts, OSRestoreInterrupts, STATE_BUSY, STATE_DMA, STATE_SELECTED.
int EXISync(s32 chan)
References __OSGetDIConfig, CARD_MAX_MOUNT_STEP, CompleteTransfer, Ecb, FALSE, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, STATE_BUSY, STATE_SELECTED, TRUE.
Referenced by __CARDClearStatus, __CARDEnableInterrupt, __CARDReadNintendoID, __CARDReadStatus, __CARDSleep, __CARDWakeup, __OSReadROM, __OSReadROMAsync, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, EXIGetID, EXIImmEx, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, QueueLength, ReadSram, WriteSram, WriteUARTN.
u32 EXIClearInterrupts(s32 chan, int exi, int tc, int ext)
References CARD_MAX_MOUNT_STEP, MAX_CHAN, prev.
Referenced by EXIAttach, EXIDma, EXIImm, EXIIntrruptHandler, EXIProbe, TCIntrruptHandler.
EXICallback EXISetExiCallback(s32 chan, EXICallback exiCallback)
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, prev, SetExiInterruptMask.
Referenced by __CARDExtHandler, CARDMountAsync, DoMount, DoUnmount, HIOInit, TimeoutHandler.
void EXIProbeReset()
References __gUnknown800030C0, EXIProbe.
Referenced by __OSSetTime, EXIInit.
int EXIProbe(s32 chan)
References __gUnknown800030C0, CARD_MAX_MOUNT_STEP, Ecb, EXIClearInterrupts, MAX_CHAN, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts, OSTicksToMilliseconds, STATE_ATTACHED.
Referenced by __CARDTxHandler, __CARDUnlockedHandler, CARDProbe, DoMount, DoneCallback, EXIAttach, EXIDeselect, EXIProbeEx, EXIProbeReset, EXISelect.
int EXIProbeEx(s32 chan)
References __gUnknown800030C0, EXIProbe.
Referenced by CARDProbeEx, HIOEnumDevices, HIOInit.
int EXIAttach(s32 chan, EXICallback extCallback)
References __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIClearInterrupts, EXIProbe, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED.
Referenced by CARDMountAsync, EXIGetID, HIOEnumDevices, HIOInit.
int EXIDetach(s32 chan)
References __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED, STATE_LOCKED.
Referenced by DoUnmount, EXIGetID, HIOEnumDevices, HIOInit.
int EXISelect(s32 chan, u32 dev, u32 freq)
References __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIProbe, MAX_CHAN, MAX_DEV, MAX_FREQ, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED, STATE_LOCKED, STATE_SELECTED.
Referenced by __CARDClearStatus, __CARDEnableInterrupt, __CARDReadNintendoID, __CARDReadStatus, __CARDSleep, __CARDStart, __CARDWakeup, __OSReadROM, __OSReadROMAsync, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, EXIGetID, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, QueueLength, ReadArrayUnlock, ReadSram, Retry, WriteSram, WriteUARTN.
int EXIDeselect(s32 chan)
References __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIProbe, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED, STATE_SELECTED.
Referenced by __CARDClearStatus, __CARDEnableInterrupt, __CARDErase, __CARDEraseSector, __CARDReadNintendoID, __CARDReadSegment, __CARDReadStatus, __CARDSleep, __CARDTxHandler, __CARDWakeup, __CARDWritePage, __OSReadROM, __OSReadROMCallback, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, EXIGetID, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteMailbox, QueueLength, ReadArrayUnlock, ReadSram, Retry, RxHandler, TxHandler, WriteSram, WriteUARTN.
static void EXIIntrruptHandler(s16 interrupt, OSContext *context)
References CARD_MAX_MOUNT_STEP, Ecb, EXIClearInterrupts, MAX_CHAN.
Referenced by EXIInit.
static void TCIntrruptHandler(s16 interrupt, OSContext *context)
References __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, CompleteTransfer, Ecb, EXIClearInterrupts, MAX_CHAN, NULL.
Referenced by EXIInit.
static void EXTIntrruptHandler(s16 interrupt, OSContext *context)
References __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIControl::extCallback.
Referenced by EXIInit.
void EXIInit()
References __OSMaskInterrupts, __OSSetInterruptHandler, CARD_MAX_MOUNT_STEP, EXIIntrruptHandler, EXIProbeReset, EXTIntrruptHandler, OSGetConsoleType, TCIntrruptHandler.
Referenced by OSInit.
int EXILock(s32 chan, u32 dev, void(*unlockedCallback)(long, OSContext *))
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN, MAX_DEV, OSDisableInterrupts, OSRestoreInterrupts, SetExiInterruptMask, STATE_LOCKED.
Referenced by EXIGetID.
int EXIUnlock(s32 chan)
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, SetExiInterruptMask, STATE_LOCKED.
Referenced by __CARDErase, __CARDEraseSector, __CARDExiHandler, __CARDReadSegment, __CARDStart, __CARDTxHandler, __CARDWritePage, __OSReadROM, __OSReadROMAsync, __OSReadROMCallback, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, DoMount, DoneCallback, EXIGetID, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, ReadSram, Retry, RxHandler, TxHandler, WriteSram, WriteUARTN.
u32 EXIGetState(s32 chan)
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN.
Referenced by CARDMountAsync, CARDProbeEx.
int EXIGetID(s32 chan, u32 dev, u32 *id)
References CARD_MAX_MOUNT_STEP, EXIAttach, EXIDeselect, EXIDetach, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, MAX_CHAN.
Referenced by CARDProbeEx.
u32 __OSGetDIConfig(void)
Referenced by EXISync.