OSRtc.c
RTC_SRAM_SIZE
static struct SramControl Scb ALIGN(32)
static BOOL GetRTC(u32 *rtc)
References CARD_MAX_MOUNT_STEP, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL.
Referenced by __OSGetRTC.
static BOOL ReadSram(void *buffer)
References buffer, DCInvalidateRange, EXIDeselect, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL, RTC_SRAM_SIZE.
Referenced by __OSInitSram.
static void WriteSramCallback()
References CARD_MAX_MOUNT_STEP, RTC_SRAM_SIZE, WriteSram.
Referenced by WriteSram.
static BOOL WriteSram(void *buffer, u32 offset, u32 size)
References buffer, EXIDeselect, EXIImm, EXIImmEx, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, SramControl::offset, size, WriteSramCallback.
Referenced by UnlockSram, WriteSramCallback.
static void * LockSram(u32 offset)
References CARD_MAX_MOUNT_STEP, SramControl::enabled, NULL, SramControl::offset, OSDisableInterrupts, OSRestoreInterrupts, TRUE.
Referenced by __OSLockSram, __OSLockSramEx.
static BOOL UnlockSram(BOOL commit, u32 offset)
References CARD_MAX_MOUNT_STEP, OSSram::checkSum, OSSram::checkSumInv, OSSram::counterBias, FALSE, OSSram::flags, SramControl::offset, OSRestoreInterrupts, RTC_SRAM_SIZE, SramControl::sram, WriteSram.
Referenced by __OSUnlockSram, __OSUnlockSramEx.
static void __OSReadROMCallback(s32 chan)
References CARD_MAX_MOUNT_STEP, EXIDeselect, EXIUnlock, NULL.
Referenced by __OSReadROMAsync.
BOOL __OSGetRTC(u32 *rtc)
References CARD_MAX_MOUNT_STEP, FALSE, GetRTC, t0, t1, TRUE.
BOOL __OSSetRTC(u32 rtc)
References CARD_MAX_MOUNT_STEP, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL.
void __OSInitSram()
References CARD_MAX_MOUNT_STEP, ReadSram, RTC_SRAM_SIZE.
Referenced by OSInit.
OSSram * __OSLockSram()
References LockSram.
Referenced by __OSGetBootMode, __OSSetBootMode, CARDFormatAsync, ImportAdjustingValues, OSGetLanguage, OSGetProgressiveMode, OSGetSoundMode, OSGetVideoMode, OSResetSystem, OSSetLanguage, OSSetProgressiveMode, OSSetSoundMode, OSSetVideoMode.
OSSramEx * __OSLockSramEx(void)
References LockSram.
Referenced by __DVDStoreErrorCode, CARDFormatAsync, DoMount, GetWirelessID, SetWirelessID, VerifyID.
BOOL __OSUnlockSram(BOOL commit)
References CARD_MAX_MOUNT_STEP, UnlockSram.
Referenced by __OSGetBootMode, __OSSetBootMode, CARDFormatAsync, ImportAdjustingValues, OSGetLanguage, OSGetProgressiveMode, OSGetSoundMode, OSGetVideoMode, OSResetSystem, OSSetLanguage, OSSetProgressiveMode, OSSetSoundMode, OSSetVideoMode.
BOOL __OSUnlockSramEx(BOOL commit)
References CARD_MAX_MOUNT_STEP, UnlockSram.
Referenced by __DVDStoreErrorCode, CARDFormatAsync, DoMount, GetWirelessID, SetWirelessID, VerifyID.
BOOL __OSSyncSram()
References CARD_MAX_MOUNT_STEP.
Referenced by CallResetFunctions, OSResetSystem.
BOOL __OSCheckSram()
References CARD_MAX_MOUNT_STEP, OSSram::checkSum, OSSram::checkSumInv, OSSram::counterBias.
BOOL __OSReadROM(void *buffer, s32 length, long offset)
References buffer, CARD_MAX_MOUNT_STEP, DCInvalidateRange, EXIDeselect, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL.
Referenced by ReadROM.
BOOL __OSReadROMAsync(void *buffer, s32 length, long offset, void(*callback)())
References __OSReadROMCallback, buffer, CARD_MAX_MOUNT_STEP, DCInvalidateRange, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, FALSE, NULL.
u32 OSGetSoundMode()
References __OSLockSram, __OSUnlockSram, FALSE, OSSram::flags.
void OSSetSoundMode(u32 mode)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, FALSE, OSSram::flags, OS_SOUND_MODE_MONO, OS_SOUND_MODE_STEREO, TRUE.
u32 OSGetProgressiveMode()
References __OSLockSram, __OSUnlockSram, FALSE, OSSram::flags, TRUE.
void OSSetProgressiveMode(u32 mode)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, FALSE, OSSram::flags, TRUE.
u32 OSGetVideoMode()
References __OSLockSram, __OSUnlockSram, FALSE, OSSram::flags.
void OSSetVideoMode(u32 mode)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, FALSE, OSSram::flags, OS_VIDEO_MODE_MPAL, OS_VIDEO_MODE_NTSC, TRUE.
u16 OSGetLanguage()
References __OSLockSram, __OSUnlockSram, FALSE, OSSram::language.
void OSSetLanguage(u16 language)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, FALSE, OSSram::language, TRUE.
u16 __OSGetBootMode()
References __OSLockSram, __OSUnlockSram, FALSE, OSSram::ntd.
void __OSSetBootMode(u16 ntd)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, FALSE, OSSram::ntd, TRUE.