OSError.c
OSErrorHandler OSErrorTable[15][15]
Referenced by __OSUnhandledException, OSSetErrorHandler.
void OSReport(char *msg,...)
References CARD_MAX_MOUNT_STEP.
Referenced by __ARChecksize, __AXAllocInit, __AXAllocQuit, __AXAuxInit, __AXAuxQuit, __AXClInit, __AXClQuit, __AXOutInit, __AXOutQuit, __AXSPBInit, __AXSPBQuit, __AXVPBInit, __AXVPBQuit, __BypassDoneRender, __DBExceptionDestinationAux, __fstLoad, __OSDispatchInterrupt, __OSUnhandledException, __VIRetraceHandler, AIInit, AISetStreamSampleRate, ARInit, ARSetSize, AXInit, AXQuit, DEMODumpROMFont, DEMOPrintStats, DMAErrorHandler, DVDDumpWaitingQueue, DVDInit, DVDOpen, fioErrorReport, fioPacketResultRead, fioPacketResultWrite, GXOverflowHandler, GXSetMisc, GXUnderflowHandler, LoadMemInfo, MPDWaiting, OSAllocFixed, OSAllocFromHeap, OSCheckActiveThreads, OSCreateHeap, OSDestroyHeap, OSDumpContext, OSDumpHeap, OSDumpStopwatch, OSInit, OSInitTimer, OSPanic, PERFEventEnd, PERFEventStart, PERFTimerCallback, Relocate, ShowChannelInfo, ShowChannelInfo, Undo.
void OSPanic(char *file, int line, char *msg,...)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSGetStackPointer, OSReport, PPCHalt.
Referenced by __DEMOInitRenderMode, DEMOInitROMFont, DEMOWriteStats, DVDConvertPathToEntrynum, DVDPrepareStream, DVDPrepareStreamAsync, DVDReadAsyncPrio, DVDReadPrio, DVDSeekAsyncPrio, GXCompressZ16, GXDecompressZ16, GXEnd, LoadMemInfo, OSCheckActiveThreads, OSInitTimer, OSStartTimer, OSStopTimer, PADSetSamplingRate, UnpackTexPalette.
OSErrorHandler OSSetErrorHandler(OSError error, OSErrorHandler handler)
References __OS_EXCEPTION_MAX, CARD_MAX_MOUNT_STEP, OSErrorTable.
Referenced by __OSCacheInit.
void __OSUnhandledException(u8 exception, OSContext *context, u32 dsisr, u32 dar)
References __OS_EXCEPTION_ALIGNMENT, __OS_EXCEPTION_DECREMENTER, __OS_EXCEPTION_DSI, __OS_EXCEPTION_ISI, __OS_EXCEPTION_PROGRAM, __OSExceptionNames, CARD_MAX_MOUNT_STEP, MSR_RI, OSDumpContext, OSErrorTable, OSLoadContext, OSReport, PPCHalt, OSContext::srr0, OSContext::srr1.
Referenced by OSDefaultExceptionHandler.