OSAlloc.h
OSAlloc
OSFree
typedef int OSHeapHandle
volatile OSHeapHandle __OSCurrHeap
Referenced by AXFXChorusInit, AXFXChorusShutdown, AXFXDelaySettings, AXFXDelayShutdown, DEMOInit, DEMOInitROMFont, DEMOReInit, DEMOWinCreateWindow, DEMOWinDestroyWindow, DLcreate, DLcreate, DLdelete, DLdelete, LoadMemInfo, ReverbHICreate, ReverbHIFree, ReverbHIModify, ReverbSTDCreate, ReverbSTDFree, ReverbSTDModify.
void * OSAllocFromHeap(int heap, u32 size)
References CARD_MAX_MOUNT_STEP, DLAddFront, DLExtract, HeapArray, NULL, NumHeaps, OSReport, size.
Referenced by AXFXChorusInit, AXFXDelaySettings, DEMOInit, DEMOInitROMFont, DEMOReInit, DEMOWinCreateWindow, DLcreate, DLcreate, ReverbHICreate, ReverbSTDCreate.
void * OSAllocFixed(void *rstart, void *rend)
References ALIGNMENT, ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLExtract, DLOverlap, HeapDesc::free, HeapArray, MINOBJSIZE, NULL, NumHeaps, OFFSET, OSReport.
Referenced by LoadMemInfo.
void OSFreeToHeap(int heap, void *ptr)
References ALIGNMENT, ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLExtract, DLInsert, DLLookup, HeapArray, OFFSET, size.
Referenced by AXFXChorusShutdown, AXFXDelayShutdown, DEMOReInit, DEMOWinDestroyWindow, DLdelete, DLdelete, ReverbHIFree, ReverbHIModify, ReverbSTDFree, ReverbSTDModify.
int OSSetCurrentHeap(int heap)
References __OSCurrHeap, CARD_MAX_MOUNT_STEP, HeapArray, NumHeaps, prev, size.
Referenced by __DEMOInitMem, LoadMemInfo.
void * OSInitAlloc(void *arenaStart, void *arenaEnd, int maxHeaps)
References __OSCurrHeap, ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, HeapArray, NumHeaps, HeapDesc::size.
Referenced by __DEMOInitMem, LoadMemInfo.
int OSCreateHeap(void *start, void *end)
References ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLOverlap, HeapArray, NumHeaps, OSReport, size, HeapDesc::size.
Referenced by __DEMOInitMem, LoadMemInfo.
void OSDestroyHeap(int heap)
References __OSCurrHeap, CARD_MAX_MOUNT_STEP, DLSize, HeapArray, NumHeaps, OSReport, size.
void OSAddToHeap(int heap, void *start, void *end)
References ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLInsert, DLOverlap, HeapArray, NumHeaps, size.
s32 OSCheckHeap(int heap)
References ALIGNMENT, ArenaEnd, ArenaStart, ASSERTREPORT, CARD_MAX_MOUNT_STEP, HEADERSIZE, HeapArray, InRange, NULL, NumHeaps, OFFSET, size.
Referenced by OSDumpHeap.
u32 OSReferentSize(void *ptr)
References ArenaEnd, ArenaStart, CARD_MAX_MOUNT_STEP, DLLookup, HEADERSIZE, HeapArray, InRange, NumHeaps, OFFSET.
void OSDumpHeap(int heap)
References CARD_MAX_MOUNT_STEP, HeapArray, NULL, NumHeaps, OSCheckHeap, OSReport.
Referenced by LoadMemInfo.
void OSVisitAllocated(void(*visitor)(void *, u32))
References CARD_MAX_MOUNT_STEP, HEADERSIZE, HeapArray, NumHeaps, size.