OSContext.h
__OS_CONTEXT_FRAME
OS_CONTEXT_R0
OS_CONTEXT_R1
OS_CONTEXT_R2
OS_CONTEXT_R3
OS_CONTEXT_R4
OS_CONTEXT_R5
OS_CONTEXT_R6
OS_CONTEXT_R7
OS_CONTEXT_R8
OS_CONTEXT_R9
OS_CONTEXT_R10
OS_CONTEXT_R11
OS_CONTEXT_R12
OS_CONTEXT_R13
OS_CONTEXT_R14
OS_CONTEXT_R15
OS_CONTEXT_R16
OS_CONTEXT_R17
OS_CONTEXT_R18
OS_CONTEXT_R19
OS_CONTEXT_R20
OS_CONTEXT_R21
OS_CONTEXT_R22
OS_CONTEXT_R23
OS_CONTEXT_R24
OS_CONTEXT_R25
OS_CONTEXT_R26
OS_CONTEXT_R27
OS_CONTEXT_R28
OS_CONTEXT_R29
OS_CONTEXT_R30
OS_CONTEXT_R31
OS_CONTEXT_CR
OS_CONTEXT_LR
OS_CONTEXT_CTR
OS_CONTEXT_XER
OS_CONTEXT_FPR0
OS_CONTEXT_FPR1
OS_CONTEXT_FPR2
OS_CONTEXT_FPR3
OS_CONTEXT_FPR4
OS_CONTEXT_FPR5
OS_CONTEXT_FPR6
OS_CONTEXT_FPR7
OS_CONTEXT_FPR8
OS_CONTEXT_FPR9
OS_CONTEXT_FPR10
OS_CONTEXT_FPR11
OS_CONTEXT_FPR12
OS_CONTEXT_FPR13
OS_CONTEXT_FPR14
OS_CONTEXT_FPR15
OS_CONTEXT_FPR16
OS_CONTEXT_FPR17
OS_CONTEXT_FPR18
OS_CONTEXT_FPR19
OS_CONTEXT_FPR20
OS_CONTEXT_FPR21
OS_CONTEXT_FPR22
OS_CONTEXT_FPR23
OS_CONTEXT_FPR24
OS_CONTEXT_FPR25
OS_CONTEXT_FPR26
OS_CONTEXT_FPR27
OS_CONTEXT_FPR28
OS_CONTEXT_FPR29
OS_CONTEXT_FPR30
OS_CONTEXT_FPR31
OS_CONTEXT_FPSCR
OS_CONTEXT_SRR0
OS_CONTEXT_SRR1
OS_CONTEXT_MODE
OS_CONTEXT_STATE
OS_CONTEXT_GQR0
OS_CONTEXT_GQR1
OS_CONTEXT_GQR2
OS_CONTEXT_GQR3
OS_CONTEXT_GQR4
OS_CONTEXT_GQR5
OS_CONTEXT_GQR6
OS_CONTEXT_GQR7
__OSCONTEXT_PADDING
OS_CONTEXT_PSF0
OS_CONTEXT_PSF1
OS_CONTEXT_PSF2
OS_CONTEXT_PSF3
OS_CONTEXT_PSF4
OS_CONTEXT_PSF5
OS_CONTEXT_PSF6
OS_CONTEXT_PSF7
OS_CONTEXT_PSF8
OS_CONTEXT_PSF9
OS_CONTEXT_PSF10
OS_CONTEXT_PSF11
OS_CONTEXT_PSF12
OS_CONTEXT_PSF13
OS_CONTEXT_PSF14
OS_CONTEXT_PSF15
OS_CONTEXT_PSF16
OS_CONTEXT_PSF17
OS_CONTEXT_PSF18
OS_CONTEXT_PSF19
OS_CONTEXT_PSF20
OS_CONTEXT_PSF21
OS_CONTEXT_PSF22
OS_CONTEXT_PSF23
OS_CONTEXT_PSF24
OS_CONTEXT_PSF25
OS_CONTEXT_PSF26
OS_CONTEXT_PSF27
OS_CONTEXT_PSF28
OS_CONTEXT_PSF29
OS_CONTEXT_PSF30
OS_CONTEXT_PSF31
OS_CONTEXT_STATE_EXC
OS_CONTEXT_STATE_FPSAVED
typedef struct OSContext OSContext
u32 OSGetStackPointer(void)
References blr, CARD_MAX_MOUNT_STEP, r3.
Referenced by OSPanic.
void OSDumpContext(OSContext *context)
References CARD_MAX_MOUNT_STEP, OSContext::cr, OSContext::fpr, OSContext::gpr, OSContext::gqr, OSContext::lr, OS_CONTEXT_STATE_FPSAVED, OSClearContext, OSDisableInterrupts, OSGetCurrentContext, OSReport, OSRestoreInterrupts, OSSetCurrentContext, OSContext::psf, OSContext::srr0, OSContext::srr1, OSContext::state.
Referenced by __DBExceptionDestinationAux, __OSDispatchInterrupt, __OSUnhandledException, DMAErrorHandler.
void OSLoadContext(OSContext *context)
Referenced by __OSDispatchInterrupt, __OSSwitchThread, __OSUnhandledException, DecrementerExceptionCallback, DecrementerExceptionCallback.
u32 OSSaveContext(OSContext *context)
Referenced by SelectThread.
void OSClearContext(OSContext *context)
Referenced by __AIDHandler, __AISHandler, __ARHandler, __DSPHandler, __DVDInterruptHandler, __OSReboot, __OSThreadInit, __VIRetraceHandler, AlarmHandlerForTimeout, DecrementerExceptionCallback, GXBreakPointHandler, GXFinishInterruptHandler, GXTokenInterruptHandler, OSCancelThread, OSExitThread, SelectThread.
OSContext * OSGetCurrentContext(void)
References CARD_MAX_MOUNT_STEP.
Referenced by OSDumpContext, SelectThread.
void OSSetCurrentContext(OSContext *context)
Referenced by __AIDHandler, __AISHandler, __ARHandler, __DSPHandler, __DVDInterruptHandler, __OSReboot, __OSSwitchThread, __OSThreadInit, __VIRetraceHandler, AlarmHandlerForTimeout, DecrementerExceptionCallback, GXBreakPointHandler, GXFinishInterruptHandler, GXTokenInterruptHandler, SelectThread.
void OSLoadFPUContext(OSContext *fpuContext)
void OSSaveFPUContext(OSContext *fpuContext)
u32 OSSwitchStack(u32 newsp)
int OSSwitchFiber(u32 pc, u32 newsp)
void OSInitContext(OSContext *context, u32 pc, u32 newsp)
Referenced by OSCreateThread.
void OSFillFPUContext(OSContext *context)