OSMemory.c
u32 __OSPhysicalMemSize AT_ADDRESS(OS_BASE_CACHED|0x0028)
u32 OSGetPhysicalMemSize(void)
References BootInfo, CARD_MAX_MOUNT_STEP, OSBootInfo_s::memorySize, OSPhysicalToCached.
Referenced by __DEMOInitMem, LoadMemInfo.
u32 OSGetConsoleSimulatedMemSize(void)
References CARD_MAX_MOUNT_STEP, OSPhysicalToCached.
Referenced by __DEMOInitMem, LoadMemInfo.