OSContext.c
HID2
u32 __OSSimulatedMemSize AT_ADDRESS(OS_BASE_CACHED|0x00D4)
static asm void __OSLoadFPUContext(register u32 p0, register OSContext *fpuContext)
References blr, CARD_MAX_MOUNT_STEP, HID2, OS_CONTEXT_FPSCR, OS_CONTEXT_PSF0, OS_CONTEXT_PSF1, OS_CONTEXT_PSF10, OS_CONTEXT_PSF11, OS_CONTEXT_PSF12, OS_CONTEXT_PSF13, OS_CONTEXT_PSF14, OS_CONTEXT_PSF15, OS_CONTEXT_PSF16, OS_CONTEXT_PSF17, OS_CONTEXT_PSF18, OS_CONTEXT_PSF19, OS_CONTEXT_PSF2, OS_CONTEXT_PSF20, OS_CONTEXT_PSF21, OS_CONTEXT_PSF22, OS_CONTEXT_PSF23, OS_CONTEXT_PSF24, OS_CONTEXT_PSF25, OS_CONTEXT_PSF26, OS_CONTEXT_PSF27, OS_CONTEXT_PSF28, OS_CONTEXT_PSF29, OS_CONTEXT_PSF3, OS_CONTEXT_PSF30, OS_CONTEXT_PSF31, OS_CONTEXT_PSF4, OS_CONTEXT_PSF5, OS_CONTEXT_PSF6, OS_CONTEXT_PSF7, OS_CONTEXT_PSF8, OS_CONTEXT_PSF9, r5.
Referenced by OSLoadFPUContext, OSSwitchFPUContext.
static asm void __OSSaveFPUContext(register u32 p0, register u32 p1, register OSContext *fpuContext)
References blr, CARD_MAX_MOUNT_STEP, HID2, OS_CONTEXT_FPSCR, OS_CONTEXT_PSF0, OS_CONTEXT_PSF1, OS_CONTEXT_PSF10, OS_CONTEXT_PSF11, OS_CONTEXT_PSF12, OS_CONTEXT_PSF13, OS_CONTEXT_PSF14, OS_CONTEXT_PSF15, OS_CONTEXT_PSF16, OS_CONTEXT_PSF17, OS_CONTEXT_PSF18, OS_CONTEXT_PSF19, OS_CONTEXT_PSF2, OS_CONTEXT_PSF20, OS_CONTEXT_PSF21, OS_CONTEXT_PSF22, OS_CONTEXT_PSF23, OS_CONTEXT_PSF24, OS_CONTEXT_PSF25, OS_CONTEXT_PSF26, OS_CONTEXT_PSF27, OS_CONTEXT_PSF28, OS_CONTEXT_PSF29, OS_CONTEXT_PSF3, OS_CONTEXT_PSF30, OS_CONTEXT_PSF31, OS_CONTEXT_PSF4, OS_CONTEXT_PSF5, OS_CONTEXT_PSF6, OS_CONTEXT_PSF7, OS_CONTEXT_PSF8, OS_CONTEXT_PSF9, r3.
Referenced by OSSaveFPUContext, OSSwitchFPUContext.
asm void OSLoadFPUContext(register OSContext *fpuContext)
References __OSLoadFPUContext, CARD_MAX_MOUNT_STEP, r4.
asm void OSSaveFPUContext(register OSContext *fpuContext)
References __OSSaveFPUContext, CARD_MAX_MOUNT_STEP, r5.
asm void OSSetCurrentContext(register OSContext *context)
References blr, CARD_MAX_MOUNT_STEP, isync, OS_CACHED_REGION_PREFIX, r4, r5, OSContext::srr1.
Referenced by OSDumpContext.
OSContext * OSGetCurrentContext(void)
References CARD_MAX_MOUNT_STEP.
Referenced by OSDumpContext, SelectThread.
asm u32 OSSaveContext(register OSContext *context)
References blr, CARD_MAX_MOUNT_STEP, OSContext::cr, OSContext::ctr, OSContext::gpr, OSContext::gqr, GQR1, GQR2, GQR3, GQR4, GQR5, GQR6, GQR7, OSContext::lr, r3, OSContext::srr0, OSContext::srr1, OSContext::xer.
void __RAS_OSDisableInterrupts_begin()
Referenced by OSLoadContext.
void __RAS_OSDisableInterrupts_end()
Referenced by OSLoadContext.
asm void OSLoadContext(register OSContext *context)
References __RAS_OSDisableInterrupts_begin, __RAS_OSDisableInterrupts_end, CARD_MAX_MOUNT_STEP, OSContext::cr, OSContext::ctr, OSContext::gpr, OSContext::gqr, GQR1, GQR2, GQR3, GQR4, GQR5, GQR6, GQR7, OSContext::lr, r3, r4, r5, OSContext::srr0, OSContext::srr1, OSContext::state, OSContext::xer.
asm u32 OSGetStackPointer()
References blr, CARD_MAX_MOUNT_STEP, r3.
Referenced by OSPanic.
asm u32 OSSwitchStack(register u32 newsp)
References blr, CARD_MAX_MOUNT_STEP, r3, r5.
asm int OSSwitchFiber(register u32 pc, register u32 newsp)
References blr, CARD_MAX_MOUNT_STEP, r5.
void OSClearContext(register OSContext *context)
References __OSFPUContext, OSContext::mode, NULL, OSContext::state.
Referenced by OSDumpContext, OSInitContext.
asm void OSInitContext(register OSContext *context, register u32 pc, register u32 newsp)
References CARD_MAX_MOUNT_STEP, OS_CONTEXT_CR, OS_CONTEXT_GQR0, OS_CONTEXT_GQR1, OS_CONTEXT_GQR2, OS_CONTEXT_GQR3, OS_CONTEXT_GQR4, OS_CONTEXT_GQR5, OS_CONTEXT_GQR6, OS_CONTEXT_GQR7, OS_CONTEXT_R1, OS_CONTEXT_R10, OS_CONTEXT_R11, OS_CONTEXT_R12, OS_CONTEXT_R13, OS_CONTEXT_R14, OS_CONTEXT_R15, OS_CONTEXT_R16, OS_CONTEXT_R17, OS_CONTEXT_R18, OS_CONTEXT_R19, OS_CONTEXT_R2, OS_CONTEXT_R20, OS_CONTEXT_R21, OS_CONTEXT_R22, OS_CONTEXT_R23, OS_CONTEXT_R24, OS_CONTEXT_R25, OS_CONTEXT_R26, OS_CONTEXT_R27, OS_CONTEXT_R28, OS_CONTEXT_R29, OS_CONTEXT_R3, OS_CONTEXT_R30, OS_CONTEXT_R31, OS_CONTEXT_R4, OS_CONTEXT_R5, OS_CONTEXT_R6, OS_CONTEXT_R7, OS_CONTEXT_R8, OS_CONTEXT_R9, OS_CONTEXT_SRR0, OS_CONTEXT_SRR1, OS_CONTEXT_XER, OSClearContext.
void OSDumpContext(OSContext *context)
References CARD_MAX_MOUNT_STEP, OSContext::cr, OSContext::fpr, OSContext::gpr, OSContext::gqr, OSContext::lr, OS_CONTEXT_STATE_FPSAVED, OSClearContext, OSDisableInterrupts, OSGetCurrentContext, OSReport, OSRestoreInterrupts, OSSetCurrentContext, OSContext::psf, OSContext::srr0, OSContext::srr1, OSContext::state.
Referenced by __DBExceptionDestinationAux, __OSDispatchInterrupt, __OSUnhandledException, DMAErrorHandler.
static asm void OSSwitchFPUContext(register __OSException exception, register OSContext *context)
References __OSLoadFPUContext, __OSSaveFPUContext, CARD_MAX_MOUNT_STEP, isync, OS_CACHED_REGION_PREFIX, OS_CONTEXT_CR, OS_CONTEXT_CTR, OS_CONTEXT_LR, OS_CONTEXT_R3, OS_CONTEXT_R4, OS_CONTEXT_R5, OS_CONTEXT_SRR0, OS_CONTEXT_SRR1, OS_CONTEXT_XER, r3, r4, r5, OSContext::state.
Referenced by __OSContextInit.
void DBPrintf(char *,...)
Referenced by __OSContextInit.
void __OSContextInit(void)
References __OS_EXCEPTION_FLOATING_POINT, __OSFPUContext, __OSSetExceptionHandler, DBPrintf, NULL, OSSwitchFPUContext.
Referenced by OSInit.
asm void OSFillFPUContext(register OSContext *context)
References blr, CARD_MAX_MOUNT_STEP, OSContext::fpr, HID2, isync, OS_CONTEXT_FPSCR, OS_CONTEXT_PSF0, OS_CONTEXT_PSF1, OS_CONTEXT_PSF10, OS_CONTEXT_PSF11, OS_CONTEXT_PSF12, OS_CONTEXT_PSF13, OS_CONTEXT_PSF14, OS_CONTEXT_PSF15, OS_CONTEXT_PSF16, OS_CONTEXT_PSF17, OS_CONTEXT_PSF18, OS_CONTEXT_PSF19, OS_CONTEXT_PSF2, OS_CONTEXT_PSF20, OS_CONTEXT_PSF21, OS_CONTEXT_PSF22, OS_CONTEXT_PSF23, OS_CONTEXT_PSF24, OS_CONTEXT_PSF25, OS_CONTEXT_PSF26, OS_CONTEXT_PSF27, OS_CONTEXT_PSF28, OS_CONTEXT_PSF29, OS_CONTEXT_PSF3, OS_CONTEXT_PSF30, OS_CONTEXT_PSF31, OS_CONTEXT_PSF4, OS_CONTEXT_PSF5, OS_CONTEXT_PSF6, OS_CONTEXT_PSF7, OS_CONTEXT_PSF8, OS_CONTEXT_PSF9, r5.