OSFont.h
OS_FONT_ENCODE_ANSI
OS_FONT_ENCODE_SJIS
OS_FONT_SIZE_ANSI
OS_FONT_SIZE_SJIS
OS_FONT_ROM_SIZE_ANSI
OS_FONT_ROM_SIZE_SJIS
typedef struct OSFontHeader OSFontHeader
u16 OSGetFontEncode(void)
References CARD_MAX_MOUNT_STEP, OS_FONT_ENCODE_ANSI, OS_FONT_ENCODE_SJIS, OSPhysicalToCached, VI_DEBUG, VI_DEBUG_PAL, VI_DTV_STAT, VI_EURGB60, VI_MPAL, VI_NTSC, VI_PAL.
Referenced by CARDFormatAsync, DEMODumpROMFont, DEMOInitROMFont, GetFontCode, OSGetFontTexel, OSGetFontTexture, OSGetFontWidth, OSInitFont, ReadFont, VerifyID.
BOOL OSInitFont(OSFontHeader *fontData)
References CARD_MAX_MOUNT_STEP, ExpandFontSheet, FontData, OS_FONT_ENCODE_SJIS, OSGetFontEncode, OSLoadFont, OSFontHeader::sheetImage, SheetImage, size.
Referenced by DEMODumpROMFont, DEMOInitROMFont.
u32 OSLoadFont(OSFontHeader *fontData, void *temp)
References CARD_MAX_MOUNT_STEP, CharsInSheet, Decode, FontData, NULL, ReadFont, OSFontHeader::sheetColumn, SheetImage, OSFontHeader::sheetRow, size, OSFontHeader::widthTable, WidthTable.
Referenced by DEMODumpROMFont, OSInitFont.
char * OSGetFontTexture(char *string, void **image, s32 *x, s32 *y, s32 *width)
Referenced by DEMORFPuts, DEMORFPutsEx.
char * OSGetFontWidth(char *string, s32 *width)
References CARD_MAX_MOUNT_STEP, GetFontCode, OS_FONT_ENCODE_SJIS, OSGetFontEncode, WidthTable.
Referenced by DEMOGetRFTextWidth.
char * OSGetFontTexel(char *string, void *image, s32 pos, s32 stride, s32 *width)
Referenced by DEMODumpROMFont.