OSReset.c
ENQUEUE_INFO
DEQUEUE_INFO
ENQUEUE_INFO_PRIO
struct OSResetFunctionQueue ResetFunctionQueue
Referenced by CallResetFunctions, OSRegisterResetFunction, OSUnregisterResetFunction.
OSThreadQueue __OSActiveThreadQueue
Referenced by KillThreads.
static int CallResetFunctions(int final)
References __OSSyncSram, OSResetFunctionInfo::func, OSResetFunctionQueue::head, OSResetFunctionInfo::next, ResetFunctionQueue.
Referenced by OSResetSystem.
static asm void Reset(u32 resetCode)
References CARD_MAX_MOUNT_STEP, HID0, isync, r3, r4, r5, sync.
Referenced by __OSDoHotReset.
void OSRegisterResetFunction(OSResetFunctionInfo *info)
References CARD_MAX_MOUNT_STEP, ENQUEUE_INFO_PRIO, OSResetFunctionInfo::func, ResetFunctionQueue.
Referenced by CARDInit, PADInit.
void OSUnregisterResetFunction(OSResetFunctionInfo *info)
References DEQUEUE_INFO, ResetFunctionQueue.
static void KillThreads(void)
References __OSActiveThreadQueue, OSThreadQueue::head, OSThread::linkActive, OSThreadLink::next, next, OSCancelThread, OSThread::state.
Referenced by OSResetSystem.
void __OSDoHotReset(s32 code)
References CARD_MAX_MOUNT_STEP, ICFlashInvalidate, OSDisableInterrupts, Reset, VI_DISP_CONFIG.
Referenced by __OSReboot, OSResetSystem, ReadApploader.
void OSResetSystem(int reset, u32 resetCode, BOOL forceMenu)
References __OSDoHotReset, __OSLockSram, __OSReboot, __OSStopAudioSystem, __OSSyncSram, __OSUnlockSram, CallResetFunctions, CARD_MAX_MOUNT_STEP, FALSE, OSSram::flags, KillThreads, OS_RESET_HOTRESET, OSDisableInterrupts, OSDisableScheduler, OSEnableScheduler, OSRestoreInterrupts, TRUE.
u32 OSGetResetCode()
References CARD_MAX_MOUNT_STEP, PI_RESET_CODE.