OSAlarm.c
ASSERTREPORT
typedef struct OSAlarmQueue OSAlarmQueue
OSAlarmQueue AlarmQueue
Referenced by DecrementerExceptionCallback, InsertAlarm, OSCancelAlarm, OSCheckAlarmQueue, OSInitAlarm.
static void SetTimer(OSAlarm *alarm)
References CARD_MAX_MOUNT_STEP, OSAlarm::fire, OSGetTime, PPCMtdec.
Referenced by DecrementerExceptionCallback, InsertAlarm, OSCancelAlarm.
static void InsertAlarm(OSAlarm *alarm, OSTime fire, OSAlarmHandler handler)
References AlarmQueue, CARD_MAX_MOUNT_STEP, OSAlarm::fire, OSAlarm::handler, OSAlarmQueue::head, DVDCommandBlock::next, OSAlarm::next, next, OSGetTime, OSAlarm::period, DVDCommandBlock::prev, OSAlarm::prev, prev, SetTimer, OSAlarm::start, OSAlarmQueue::tail.
Referenced by DecrementerExceptionCallback, OSSetAbsAlarm, OSSetAlarm, OSSetPeriodicAlarm.
static void DecrementerExceptionCallback(register __OSException exception, register OSContext *context)
References __OSReschedule, AlarmQueue, CARD_MAX_MOUNT_STEP, OSAlarm::handler, OSAlarmQueue::head, InsertAlarm, OSAlarm::next, next, OSCheckAlarmQueue, OSDisableScheduler, OSEnableScheduler, OSGetTime, OSLoadContext, OSAlarm::period, DVDCommandBlock::prev, SetTimer, OSAlarmQueue::tail.
Referenced by DecrementerExceptionHandler.
static void DecrementerExceptionHandler(__OSException exception, OSContext *context)
Referenced by OSInitAlarm.
BOOL OSCheckAlarmQueue(void)
References AlarmQueue, ASSERTREPORT, OSAlarmQueue::head, OSAlarm::next, NULL, OSAlarm::prev, OSAlarmQueue::tail, TRUE.
Referenced by DecrementerExceptionCallback, OSCancelAlarm, OSSetAbsAlarm, OSSetAlarm, OSSetPeriodicAlarm.
void OSInitAlarm(void)
References __OSGetExceptionHandler, __OSSetExceptionHandler, AlarmQueue, DecrementerExceptionHandler, OSAlarmQueue::head, NULL, OSAlarmQueue::tail.
Referenced by __DVDInitWA, CARDInit, DVDInit, PERFInit.
void OSCreateAlarm(OSAlarm *alarm)
References OSAlarm::handler.
Referenced by CARDInit, SetBreakAlarm, SetTimeoutAlarm, stateCoverClosed, WaitBeforeRead.
void OSSetAlarm(OSAlarm *alarm, OSTime tick, OSAlarmHandler handler)
References CARD_MAX_MOUNT_STEP, InsertAlarm, OSCheckAlarmQueue, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts, OSAlarm::period.
Referenced by SetBreakAlarm, SetTimeoutAlarm, SetupTimeoutAlarm, stateCoverClosed, WaitBeforeRead.
void OSSetAbsAlarm(OSAlarm *alarm, s64 time, void(*handler)(OSAlarm *, OSContext *))
References CARD_MAX_MOUNT_STEP, InsertAlarm, OSCheckAlarmQueue, OSDisableInterrupts, OSRestoreInterrupts, OSAlarm::period.
void OSSetPeriodicAlarm(OSAlarm *alarm, OSTime start, OSTime period, OSAlarmHandler handler)
References CARD_MAX_MOUNT_STEP, InsertAlarm, OSCheckAlarmQueue, OSDisableInterrupts, OSRestoreInterrupts, OSAlarm::period, OSAlarm::start.
Referenced by PERFStartAutoSampling.
void OSCancelAlarm(OSAlarm *alarm)
References AlarmQueue, CARD_MAX_MOUNT_STEP, OSAlarm::handler, OSAlarmQueue::head, OSAlarm::next, next, OSCheckAlarmQueue, OSDisableInterrupts, OSRestoreInterrupts, DVDCommandBlock::prev, OSAlarm::prev, SetTimer, OSAlarmQueue::tail.
Referenced by __CARDExiHandler, __CARDExtHandler, __DVDInterruptHandler, CARDMountAsync, DoUnmount, PERFStopAutoSampling, SetupTimeoutAlarm, SITransferNext.
static asm void DecrementerExceptionHandler(register __OSException exception, register OSContext *context)
References CARD_MAX_MOUNT_STEP, DecrementerExceptionCallback, OS_EXCEPTION_SAVE_GPRS.