OSException.h
__OS_EXCEPTION_SYSTEM_RESET
__OS_EXCEPTION_MACHINE_CHECK
__OS_EXCEPTION_DSI
__OS_EXCEPTION_ISI
__OS_EXCEPTION_EXTERNAL_INTERRUPT
__OS_EXCEPTION_ALIGNMENT
__OS_EXCEPTION_PROGRAM
__OS_EXCEPTION_FLOATING_POINT
__OS_EXCEPTION_DECREMENTER
__OS_EXCEPTION_SYSTEM_CALL
__OS_EXCEPTION_TRACE
__OS_EXCEPTION_PERFORMACE_MONITOR
__OS_EXCEPTION_BREAKPOINT
__OS_EXCEPTION_SYSTEM_INTERRUPT
__OS_EXCEPTION_THERMAL_INTERRUPT
__OS_EXCEPTION_MAX
OS_EXCEPTION_SAVE_GPRS
typedef u8 __OSException
typedef void(* __OSExceptionHandler) (__OSException exception, OSContext *context))(__OSException exception, OSContext *context)
__OSExceptionHandler __OSSetExceptionHandler(__OSException exception, __OSExceptionHandler handler)
References __OS_EXCEPTION_MAX, CARD_MAX_MOUNT_STEP, OSExceptionTable.
Referenced by __OSContextInit, __OSInterruptInit, OSExceptionInit, OSInitAlarm, OSInitTimer.
__OSExceptionHandler __OSGetExceptionHandler(__OSException exception)
References __OS_EXCEPTION_MAX, CARD_MAX_MOUNT_STEP, OSExceptionTable.
Referenced by OSInitAlarm.