OSSerial.h
BOOL SIBusy()
References SIControl::chan, Si.
Referenced by PADSync.
void SIInit()
References __OSSetInterruptHandler, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, SIPacket::chan, Packet, SI_COMCSR_IDX, SI_COMCSR_TCINT_MASK, SI_COMCSR_TSTART_MASK, SIIntrruptHandler.
Referenced by OSInit.
u32 SISync()
References CARD_MAX_MOUNT_STEP, CompleteTransfer, OSDisableInterrupts, OSRestoreInterrupts, SI_COMCSR_IDX, SI_COMCSR_TSTART_MASK, SITransferNext.
u32 SIGetStatus()
References CARD_MAX_MOUNT_STEP, SI_STATUS_IDX.
Referenced by PADRead.
void SISetCommand(s32 chan, u32 command)
References CARD_MAX_MOUNT_STEP, SIPacket::chan.
Referenced by PADControlAllMotors, PADControlMotor, PADEnable, ProbeWireless.
u32 SIGetCommand(s32 chan)
References CARD_MAX_MOUNT_STEP, SIPacket::chan.
void SITransferCommands()
References CARD_MAX_MOUNT_STEP, SI_COMCSR_TCINT_MASK, SI_STATUS_IDX.
Referenced by PADControlAllMotors, PADControlMotor.
u32 SISetXY(u32 x, u32 y)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, SIControl::poll, Si.
Referenced by PADSetSamplingRate.
u32 SIEnablePolling(u32 poll)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, SIControl::poll, Si.
Referenced by PADEnable, PADSetSamplingRate, ProbeWireless.
u32 SIDisablePolling(u32 poll)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, SIControl::poll, Si.
Referenced by PADDisable, PADRecalibrate, PADReset, PADSetAnalogMode.
void SIGetResponse(s32 chan, void *data)
References CARD_MAX_MOUNT_STEP, SIPacket::chan.
Referenced by PADEnable, PADRead, ProbeWireless.
BOOL SITransfer(s32 chan, void *output, u32 outputBytes, void *input, u32 inputBytes, void(*callback)(s32, u32, OSContext *), s64 time)
References __SITransfer, Alarm, AlarmHandler, SIPacket::callback, CARD_MAX_MOUNT_STEP, SIPacket::chan, FALSE, SIPacket::input, SIPacket::inputBytes, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts, OSSetAbsAlarm, SIPacket::output, SIPacket::outputBytes, Packet, SIPacket::time, TRUE.
Referenced by DoReset, PADFixCallback, PADRead, PADReceiveCheckCallback, PADResetCallback.