OS.c
OS_BI2_DEBUG_ADDRESS
DEBUGFLAG_ADDR
OS_DEBUG_ADDRESS_2
OS_CURRENTCONTEXT_PADDR
OS_EXCEPTIONTABLE_ADDR
OS_DBJUMPPOINT_ADDR
OS_CACHED_REGION_PREFIX
OS_BI2_DEBUG_ADDRESS
OS_BI2_DEBUGFLAG_OFFSET
PAD3_BUTTON_ADDR
OS_DVD_DEVICECODE
DEBUGFLAG_ADDR
OS_DEBUG_ADDRESS_2
DB_EXCEPTIONRET_OFFSET
DB_EXCEPTIONDEST_OFFSET
NOP
u32 __DVDLongFileNameFlag
Referenced by DVDConvertPathToEntrynum, OSInit.
u32 __PADSpec
Referenced by OSInit, PADInit, PADSetSpec.
u16 __ArenaLo[][]
Referenced by OSInit.
s8 _stack_addr[][]
Referenced by __init_registers, OSInit.
u16 __ArenaHi[][]
Referenced by OSInit.
struct OSBootInfo_s* BootInfo
Referenced by OSGetConsoleType, OSInit.
u32* BI2DebugFlag
Referenced by OSExceptionInit, OSInit.
double ZeroF
Referenced by __OSInitFPRs.
int AreWeInitialized
Referenced by OSInit.
void(** OSExceptionTable) (u8, OSContext *))(u8, OSContext *)
Referenced by __OSGetExceptionHandler, __OSSetExceptionHandler, OSExceptionInit.
u32 __OSExceptionLocations[][]
Referenced by OSExceptionInit.
void __OSEVStart(void)
Referenced by OSExceptionInit, OSExceptionVector.
void __OSEVEnd(void)
Referenced by OSExceptionInit, OSExceptionVector.
void __OSEVSetNumber(void)
Referenced by OSExceptionInit, OSExceptionVector.
void __OSExceptionVector(void)
void __DBVECTOR(void)
Referenced by OSExceptionInit, OSExceptionVector.
void __OSDBINTSTART(void)
Referenced by __OSDBIntegrator, OSExceptionInit.
void __OSDBINTEND(void)
Referenced by __OSDBIntegrator, OSExceptionInit.
void __OSDBJUMPSTART(void)
Referenced by __OSDBJump, OSExceptionInit.
void __OSDBJUMPEND(void)
Referenced by __OSDBJump, OSExceptionInit.
static asm void __OSInitFPRs(void)
References blr, CARD_MAX_MOUNT_STEP, ZeroF.
static void OSExceptionInit(void)
References __DBIsExceptionMarked, __DBVECTOR, __OS_EXCEPTION_MAX, __OSDBINTEND, __OSDBINTSTART, __OSDBJUMPEND, __OSDBJUMPSTART, __OSEVEnd, __OSEVSetNumber, __OSEVStart, __OSExceptionLocations, __OSSetExceptionHandler, BI2DebugFlag, CARD_MAX_MOUNT_STEP, cb, DBPrintf, DCFlushRangeNoSync, ICInvalidateRange, NOP, OS_DBJUMPPOINT_ADDR, OS_EXCEPTIONTABLE_ADDR, OSDefaultExceptionHandler, OSExceptionTable, OSPhysicalToCached.
Referenced by OSInit.
static void OSDefaultExceptionHandler(u8 exception, OSContext *context)
Referenced by OSExceptionInit, OSExceptionVector.
unsigned long __OSIsDebuggerPresent()
References OSPhysicalToCached.
u32 OSGetConsoleType()
References BootInfo, OSBootInfo_s::consoleType, OS_CONSOLE_ARTHUR.
Referenced by __DEMOInitMem, EXIInit, InitializeUART, OSInit.
void OSInit()
References __ArenaHi, __ArenaLo, __DVDLongFileNameFlag, __OSCacheInit, __OSContextInit, __OSInitAudioSystem, __OSInitSram, __OSInitSystemCall, __OSInterruptInit, __OSModuleInit, __OSResetSWInterruptHandler, __OSSetInterruptHandler, __OSThreadInit, __PADSpec, _stack_addr, OSBootInfo_s::arenaHi, OSBootInfo_s::arenaLo, AreWeInitialized, BI2DebugFlag, BootInfo, CARD_MAX_MOUNT_STEP, OSBootInfo_s::consoleType, EXIInit, OSBootInfo_s::memorySize, NULL, OS_CONSOLE_ARTHUR, OS_CONSOLE_DEVELOPMENT, OS_CONSOLE_DEVHW1, OS_CONSOLE_EMULATOR, OS_CONSOLE_MINNOW, OS_CONSOLE_PC_EMULATOR, OS_CONSOLE_RETAIL, OS_CONSOLE_RETAIL1, OSDisableInterrupts, OSEnableInterrupts, OSExceptionInit, OSGetArenaHi, OSGetArenaLo, OSGetConsoleType, OSPhysicalToCached, OSReport, OSSetArenaHi, OSSetArenaLo, SIInit.
Referenced by DEMOInit.
static asm void __OSDBIntegrator(void)
References __OSDBINTEND, __OSDBINTSTART, blr, CARD_MAX_MOUNT_STEP, DB_EXCEPTIONDEST_OFFSET, DB_EXCEPTIONRET_OFFSET, OS_CACHED_REGION_PREFIX, OS_DBINTERFACE_ADDR, r3, r5.
static asm void __OSDBJump(void)
References __OSDBJUMPEND, __OSDBJUMPSTART, CARD_MAX_MOUNT_STEP, OS_DBJUMPPOINT_ADDR.
__OSExceptionHandler __OSSetExceptionHandler(__OSException exception, __OSExceptionHandler handler)
References __OS_EXCEPTION_MAX, CARD_MAX_MOUNT_STEP, OSExceptionTable.
Referenced by __OSContextInit, __OSInterruptInit, OSExceptionInit, OSInitAlarm, OSInitTimer.
__OSExceptionHandler __OSGetExceptionHandler(__OSException exception)
References __OS_EXCEPTION_MAX, CARD_MAX_MOUNT_STEP, OSExceptionTable.
Referenced by OSInitAlarm.
static asm void OSExceptionVector(void)
References __DBVECTOR, __OSEVEnd, __OSEVSetNumber, __OSEVStart, CARD_MAX_MOUNT_STEP, MSR_RI_BIT, OS_CONTEXT_CR, OS_CONTEXT_CTR, OS_CONTEXT_LR, OS_CONTEXT_R3, OS_CONTEXT_R4, OS_CONTEXT_R5, OS_CONTEXT_SRR0, OS_CONTEXT_SRR1, OS_CONTEXT_STATE, OS_CONTEXT_STATE_EXC, OS_CONTEXT_XER, OS_CURRENTCONTEXT_PADDR, OS_EXCEPTIONTABLE_ADDR, OSDefaultExceptionHandler, r3, r4, r5.
void __OSUnhandledException(__OSException exception, OSContext *context, u32 dsisr, u32 dar)
References __OS_EXCEPTION_ALIGNMENT, __OS_EXCEPTION_DECREMENTER, __OS_EXCEPTION_DSI, __OS_EXCEPTION_ISI, __OS_EXCEPTION_PROGRAM, __OSExceptionNames, CARD_MAX_MOUNT_STEP, MSR_RI, OSDumpContext, OSErrorTable, OSLoadContext, OSReport, PPCHalt, OSContext::srr0, OSContext::srr1.
Referenced by OSDefaultExceptionHandler.
asm void OSDefaultExceptionHandler(register __OSException exception, register OSContext *context)
References __OSUnhandledException, CARD_MAX_MOUNT_STEP, OS_EXCEPTION_SAVE_GPRS, r5.
void __OSPSInit(void)
References CARD_MAX_MOUNT_STEP, GQR0, ICFlashInvalidate, PPCMfhid2, PPCMthid2, r3.
Referenced by __declspec.
u8 __OSGetDIConfig(void)
References CARD_MAX_MOUNT_STEP, DI_CFG.
Referenced by EXISync.