OSLink.c
SHN_UNDEF
SHN_LORESERVE
SHN_LOPROC
SHN_HIPROC
SHN_ABS
SHN_COMMON
SHN_HIRESERVE
ELF32_R_SYM
ELF32_R_TYPE
ELF32_R_INFO
R_PPC_NONE
R_PPC_ADDR32
R_PPC_ADDR24
R_PPC_ADDR16
R_PPC_ADDR16_LO
R_PPC_ADDR16_HI
R_PPC_ADDR16_HA
R_PPC_ADDR14
R_PPC_ADDR14_BRTAKEN
R_PPC_ADDR14_BRNTAKEN
R_PPC_REL24
R_PPC_REL14
R_PPC_REL14_BRTAKEN
R_PPC_REL14_BRNTAKEN
R_PPC_GOT16
R_PPC_GOT16_LO
R_PPC_GOT16_HI
R_PPC_GOT16_HA
R_PPC_PLTREL24
R_PPC_COPY
R_PPC_GLOB_DAT
R_PPC_JMP_SLOT
R_PPC_RELATIVE
R_PPC_LOCAL24PC
R_PPC_UADDR32
R_PPC_UADDR16
R_PPC_REL32
R_PPC_PLT32
R_PPC_PLTREL32
R_PPC_PLT16_LO
R_PPL_PLT16_HI
R_PPC_PLT16_HA
R_PPC_SDAREL16
R_PPC_SECTOFF
R_PPC_SECTOFF_LO
R_PPC_SECTOFF_HI
R_PPC_SECTOFF_HA
R_PPC_ADDR30
R_PPC_EMB_NADDR32
R_PPC_EMB_NADDR16
R_PPC_EMB_NADDR16_LO
R_PPC_EMB_NADDR16_HI
R_PPC_EMB_NADDR16_HA
R_PPC_EMB_SDAI16
R_PPC_EMB_SDA2I16
R_PPC_EMB_SDA2REL
R_PPC_EMB_SDA21
R_PPC_EMB_MRKREF
R_PPC_EMB_RELSEC16
R_PPC_EMB_RELST_LO
R_PPC_EMB_RELST_HI
R_PPC_EMB_RELST_HA
R_PPC_EMB_BIT_FLD
R_PPC_EMB_RELSDA
ENQUEUE_INFO
DEQUEUE_INFO
OSModuleQueue __OSModuleInfoList AT_ADDRESS(OS_BASE_CACHED|0x30C8)
void OSNotifyLink()
Referenced by OSLink.
void OSNotifyUnlink()
Referenced by OSUnlink.
void OSSetStringTable(const void *stringTable)
References CARD_MAX_MOUNT_STEP.
static BOOL Relocate(OSModuleHeader *newModule, OSModuleHeader *module)
References CARD_MAX_MOUNT_STEP, DCFlushRange, FALSE, ICInvalidateRange, OSSectionInfo::offset, OS_SECTIONINFO_EXEC, OS_SECTIONINFO_OFFSET, OSGetSectionInfo, OSReport, R_DOLPHIN_END, R_DOLPHIN_NOP, R_DOLPHIN_SECTION, R_PPC_ADDR16, R_PPC_ADDR16_HA, R_PPC_ADDR16_HI, R_PPC_ADDR16_LO, R_PPC_ADDR24, R_PPC_ADDR32, R_PPC_NONE, R_PPC_REL24, TRUE.
Referenced by OSLink.
BOOL OSLink(OSModuleInfo *newModule, void *bss)
References CARD_MAX_MOUNT_STEP, ENQUEUE_INFO, OS_MODULE_VERSION, OS_SECTIONINFO_OFFSET, OSGetSectionInfo, OSNotifyLink, Relocate, SHN_UNDEF, TRUE.
static BOOL Undo(OSModuleHeader *newModule, OSModuleHeader *module)
References CARD_MAX_MOUNT_STEP, DCFlushRange, FALSE, ICInvalidateRange, OS_SECTIONINFO_EXEC, OS_SECTIONINFO_OFFSET, OSGetSectionInfo, OSReport, R_DOLPHIN_END, R_DOLPHIN_NOP, R_DOLPHIN_SECTION, R_PPC_ADDR16, R_PPC_ADDR16_HA, R_PPC_ADDR16_HI, R_PPC_ADDR16_LO, R_PPC_ADDR24, R_PPC_ADDR32, R_PPC_NONE, R_PPC_REL24, SHN_UNDEF, TRUE.
Referenced by OSUnlink.
BOOL OSUnlink(OSModuleInfo *oldModule)
References CARD_MAX_MOUNT_STEP, DEQUEUE_INFO, OS_MODULE_VERSION, OSNotifyUnlink, TRUE, Undo.
void __OSModuleInit(void)
References CARD_MAX_MOUNT_STEP.
Referenced by OSInit.