OSSerial.c
CHAN_NONE
SI_MAX_CHAN
SI_COMCSR_IDX
SI_STATUS_IDX
SI_COMCSR_TCINT_MASK
SI_COMCSR_TCINTMSK_MASK
SI_COMCSR_COMERR_MASK
SI_COMCSR_RDSTINT_MASK
SI_COMCSR_RDSTINTMSK_MASK
SI_COMCSR_OUTLNGTH_MASK
SI_COMCSR_INLNGTH_MASK
SI_COMCSR_CHANNEL_MASK
SI_COMCSR_TSTART_MASK
ROUND
typedef struct SIControl SIControl
typedef struct SIPacket SIPacket
struct SIControl Si
Referenced by __SITransfer, CompleteTransfer, SIBusy, SIDisablePolling, SIEnablePolling, SIIntrruptHandler, SISetXY.
struct SIPacket Packet[4][4]
Referenced by AlarmHandler, SIInit, SITransfer, SITransferNext.
struct OSAlarm Alarm[4][4]
Referenced by AlarmHandler, SITransfer, SITransferNext.
static u32 CompleteTransfer()
References CARD_MAX_MOUNT_STEP, SIControl::chan, SIControl::input, SIControl::inputBytes, Si, SI_COMCSR_IDX, SI_COMCSR_TCINT_MASK, SI_STATUS_IDX.
Referenced by EXISync, SIIntrruptHandler, SISync, TCIntrruptHandler.
static void SITransferNext(s32 chan)
References __SITransfer, Alarm, CARD_MAX_MOUNT_STEP, SIPacket::chan, OSCancelAlarm, OSGetTime, Packet.
Referenced by SIIntrruptHandler, SISync.
static void SIIntrruptHandler(s16 unused, OSContext *context)
References SIControl::callback, SIPacket::callback, CARD_MAX_MOUNT_STEP, SIControl::chan, SIPacket::chan, CHAN_NONE, CompleteTransfer, NULL, Si, SITransferNext.
Referenced by SIInit.
static BOOL __SITransfer(s32 chan, void *output, u32 outputBytes, void *input, u32 inputBytes, void(*callback)(s32, u32, OSContext *))
References SIControl::callback, SIPacket::callback, CARD_MAX_MOUNT_STEP, SIControl::chan, SIPacket::chan, FALSE, SIControl::input, SIPacket::input, SIControl::inputBytes, SIPacket::inputBytes, OSDisableInterrupts, OSRestoreInterrupts, SIPacket::output, SIPacket::outputBytes, ROUND, Si, SI_COMCSR_IDX, SI_COMCSR_TCINT_MASK, SI_COMCSR_TSTART_MASK, SI_STATUS_IDX, TRUE.
Referenced by AlarmHandler, SITransfer, SITransferNext.
static void AlarmHandler(struct OSAlarm *alarm, OSContext *context)
References __SITransfer, Alarm, CARD_MAX_MOUNT_STEP, SIPacket::chan, OSGetTime, Packet, SI_MAX_CHAN.
int SIBusy()
References SIControl::chan, Si.
Referenced by PADSync.
void SIInit()
References __OSSetInterruptHandler, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, SIPacket::chan, Packet, SI_COMCSR_IDX, SI_COMCSR_TCINT_MASK, SI_COMCSR_TSTART_MASK, SIIntrruptHandler.
Referenced by OSInit.
u32 SISync()
References CARD_MAX_MOUNT_STEP, CompleteTransfer, OSDisableInterrupts, OSRestoreInterrupts, SI_COMCSR_IDX, SI_COMCSR_TSTART_MASK, SITransferNext.
u32 SIGetStatus()
References CARD_MAX_MOUNT_STEP, SI_STATUS_IDX.
Referenced by PADRead.
void SISetCommand(s32 chan, u32 command)
References CARD_MAX_MOUNT_STEP, SIPacket::chan.
Referenced by PADControlAllMotors, PADControlMotor, PADEnable, ProbeWireless.
u32 SIGetCommand(s32 chan)
References CARD_MAX_MOUNT_STEP, SIPacket::chan.
void SITransferCommands()
References CARD_MAX_MOUNT_STEP, SI_COMCSR_TCINT_MASK, SI_STATUS_IDX.
Referenced by PADControlAllMotors, PADControlMotor.
u32 SISetXY(u32 x, u32 y)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, SIControl::poll, Si.
Referenced by PADSetSamplingRate.
u32 SIEnablePolling(u32 poll)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, SIControl::poll, Si.
Referenced by PADEnable, PADSetSamplingRate, ProbeWireless.
u32 SIDisablePolling(u32 poll)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, SIControl::poll, Si.
Referenced by PADDisable, PADRecalibrate, PADReset, PADSetAnalogMode.
void SIGetResponse(s32 chan, void *data)
References CARD_MAX_MOUNT_STEP, SIPacket::chan.
Referenced by PADEnable, PADRead, ProbeWireless.
BOOL SITransfer(s32 chan, void *output, u32 outputBytes, void *input, u32 inputBytes, void(*callback)(s32, u32, OSContext *), s64 time)
References __SITransfer, Alarm, AlarmHandler, SIPacket::callback, CARD_MAX_MOUNT_STEP, SIPacket::chan, FALSE, SIPacket::input, SIPacket::inputBytes, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts, OSSetAbsAlarm, SIPacket::output, SIPacket::outputBytes, Packet, SIPacket::time, TRUE.
Referenced by DoReset, PADFixCallback, PADRead, PADReceiveCheckCallback, PADResetCallback.