OSThread.h
OS_PRIORITY_MIN
OS_PRIORITY_MAX
OS_PRIORITY_IDLE
OS_THREAD_ATTR_DETACH
OS_THREAD_STACK_MAGIC
OS_THREAD_STATE
typedef struct OSThread OSThread
typedef struct OSThreadQueue OSThreadQueue
typedef struct OSThreadLink OSThreadLink
typedef s32 OSPriority
typedef struct OSMutex OSMutex
typedef struct OSMutexQueue OSMutexQueue
typedef struct OSMutexLink OSMutexLink
typedef struct OSCond OSCond
typedef void(* OSIdleFunction) (void *param))(void *param)
void OSInitThreadQueue(OSThreadQueue *queue)
References OSThreadQueue::head, OSThreadQueue::tail.
Referenced by __GXPEInit, __OSThreadInit, CARDInit, DVDInit, OSCreateThread, OSInitCond, OSInitMessageQueue, OSInitMutex, VIInit.
OSThread * OSGetCurrentThread(void)
References __OSCurrentThread.
Referenced by __GXFifoInit, GXSetCurrentGXThread, OSExitThread, OSLockMutex, OSSleepThread, OSTryLockMutex, OSUnlockMutex, OSWaitCond, SelectThread.
BOOL OSIsThreadSuspended(OSThread *thread)
References FALSE, OSThread::suspend, TRUE.
BOOL OSIsThreadTerminated(OSThread *thread)
References OSThread::state.
s32 OSDisableScheduler(void)
References OSDisableInterrupts, OSRestoreInterrupts, Reschedule.
Referenced by __OSDispatchInterrupt, DecrementerExceptionCallback, OSResetSystem, OSWaitCond.
s32 OSEnableScheduler(void)
References OSDisableInterrupts, OSRestoreInterrupts, Reschedule.
Referenced by __OSDispatchInterrupt, DecrementerExceptionCallback, OSResetSystem, OSWaitCond.
void OSYieldThread(void)
References OSDisableInterrupts, OSRestoreInterrupts, SelectThread.
BOOL OSCreateThread(OSThread *thread, void *(*func)(void *), void *param, void *stack, u32 stackSize, OSPriority priority, u16 attr)
References __OSActiveThreadQueue, __OSIsThreadActive, OSThread::attr, OSThread::base, CARD_MAX_MOUNT_STEP, OSThread::context, ENQUEUE_THREAD, FALSE, OSContext::gpr, OSContext::lr, OSThread::mutex, NULL, OSDisableInterrupts, OSExitThread, OSInitContext, OSInitThreadQueue, OSRestoreInterrupts, OSThread::priority, OSThread::queueJoin, OSThread::queueMutex, OSThread::stackBase, OSThread::stackEnd, OSThread::state, OSThread::suspend, TRUE, OSThread::val.
Referenced by OSSetIdleFunction.
void OSExitThread(void *val)
References __OSActiveThreadQueue, __OSIsThreadActive, __OSReschedule, __OSUnlockAllMutex, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, OSClearContext, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, OSWakeupThread, RunQueueHint, SelectThread.
Referenced by OSCreateThread.
void OSCancelThread(OSThread *thread)
References __OSActiveThreadQueue, __OSIsThreadActive, __OSReschedule, __OSUnlockAllMutex, OSThread::attr, CARD_MAX_MOUNT_STEP, OSThread::context, DEQUEUE_THREAD, OSThread::mutex, OSClearContext, OSDisableInterrupts, OSRestoreInterrupts, OSWakeupThread, OSThread::queue, OSThread::queueJoin, RunQueueHint, OSThread::state, OSThread::suspend, OSMutex::thread, UnsetRun, UpdatePriority.
Referenced by KillThreads, OSSetIdleFunction.
BOOL OSJoinThread(OSThread *thread, void **val)
References __OSActiveThreadQueue, __OSIsThreadActive, OSThread::attr, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, FALSE, OSThreadQueue::head, NULL, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, OSThread::queueJoin, OSThread::state, TRUE, OSThread::val.
void OSDetachThread(OSThread *thread)
References __OSActiveThreadQueue, __OSIsThreadActive, OSThread::attr, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, OSDisableInterrupts, OSRestoreInterrupts, OSWakeupThread, OSThread::queueJoin, OSThread::state.
s32 OSResumeThread(OSThread *thread)
References __OSGetEffectivePriority, __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, ENQUEUE_THREAD_PRIO, OSThread::mutex, OSDisableInterrupts, OSRestoreInterrupts, OSThread::priority, OSThread::queue, SetRun, OSThread::state, OSThread::suspend, OSMutex::thread, UpdatePriority.
Referenced by GXUnderflowHandler, OSSetIdleFunction.
s32 OSSuspendThread(OSThread *thread)
References __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, ENQUEUE_THREAD, OSThread::mutex, OSDisableInterrupts, OSRestoreInterrupts, OSThread::priority, OSThread::queue, RunQueueHint, OSThread::state, OSThread::suspend, OSMutex::thread, UnsetRun, UpdatePriority.
Referenced by GXOverflowHandler.
BOOL OSSetThreadPriority(OSThread *thread, OSPriority priority)
References __OSIsThreadActive, __OSReschedule, OSThread::base, CARD_MAX_MOUNT_STEP, FALSE, OSDisableInterrupts, OSRestoreInterrupts, OSThread::state, TRUE, UpdatePriority.
OSPriority OSGetThreadPriority(OSThread *thread)
References OSThread::base.
void OSSleepThread(OSThreadQueue *queue)
References __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, ENQUEUE_THREAD_PRIO, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, RunQueueHint.
Referenced by __CARDSync, DVDCancel, DVDCancelAll, DVDCancelStream, DVDChangeDisk, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInquiry, DVDPrepareStream, DVDReadPrio, DVDSeekPrio, DVDStopStreamAtEnd, GXWaitDrawDone, OSJamMessage, OSJoinThread, OSLockMutex, OSReceiveMessage, OSSendMessage, OSWaitCond, VIWaitForRetrace.
void OSWakeupThread(OSThreadQueue *queue)
References __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, DEQUEUE_HEAD, OSThreadQueue::head, OS_THREAD_STATE_MORIBUND, OSDisableInterrupts, OSRestoreInterrupts, OSThread::queue, SetRun, OSThread::state, OSThread::suspend.
Referenced by __CARDSyncCallback, __OSUnlockAllMutex, __VIRetraceHandler, cbForCancelAllSync, cbForCancelStreamSync, cbForCancelSync, cbForChangeDiskSync, cbForGetStreamErrorStatusSync, cbForGetStreamLengthSync, cbForGetStreamPlayAddrSync, cbForGetStreamStartAddrSync, cbForInquirySync, cbForPrepareStreamSync, cbForReadSync, cbForSeekSync, cbForStopStreamAtEndSync, GXFinishInterruptHandler, OSCancelThread, OSDetachThread, OSExitThread, OSJamMessage, OSReceiveMessage, OSSendMessage, OSSignalCond, OSUnlockMutex, OSWaitCond.
OSThread * OSSetIdleFunction(OSIdleFunction idleFunction, void *param, void *stack, u32 stackSize)
OSThread * OSGetIdleFunction(void)
References IdleThread, NULL, OSThread::state.
s32 OSCheckActiveThreads(void)
References __OSActiveThreadQueue, __OSCheckDeadLock, __OSCheckMutexes, __OSGetEffectivePriority, ASSERTREPORT, CARD_MAX_MOUNT_STEP, CheckThreadQueue, OSThreadQueue::head, OSMutexQueue::head, IsMember, IsSuspended, OSThread::linkActive, OSThreadLink::next, NULL, OS_PRIORITY_MAX, OS_THREAD_STACK_MAGIC, OSDisableInterrupts, OSPanic, OSReport, OSRestoreInterrupts, OSThreadLink::prev, OSThread::priority, OSThread::queue, OSThread::queueJoin, OSThread::queueMutex, RunQueue, RunQueueBits, OSThread::stackEnd, OSThread::state, OSThread::suspend, OSThreadQueue::tail, OSMutexQueue::tail.