OSSync.c
void __OSSystemCallVectorStart()
Referenced by __OSInitSystemCall, SystemCallVector.
void __OSSystemCallVectorEnd()
Referenced by __OSInitSystemCall, SystemCallVector.
static asm void SystemCallVector(void)
References __OSSystemCallVectorEnd, __OSSystemCallVectorStart, CARD_MAX_MOUNT_STEP, HID0, isync, sync.
void __OSInitSystemCall(void)
References __OSSystemCallVectorEnd, __OSSystemCallVectorStart, CARD_MAX_MOUNT_STEP, DCFlushRangeNoSync, ICInvalidateRange, OSPhysicalToCached.
Referenced by OSInit.