OSTime.c
int YearDays[MONTH_MAX][MONTH_MAX]
Referenced by GetDates, GetYearDays.
int LeapYearDays[MONTH_MAX][MONTH_MAX]
Referenced by GetDates, GetYearDays.
asm s64 OSGetTime(void)
References blr, CARD_MAX_MOUNT_STEP, OSGetTime, r3, r4, r5.
Referenced by __AI_SRC_INIT, __AXDSPResumeCallback, __AXOutAiCallback, __AXOutNewFrame, __get_time, __GXAbortWait, __OSGetSystemTime, __OSSetTime, __VIInitI2C, AlarmHandler, CARDFormatAsync, CARDRenameAsync, CARDSetStatusAsync, CreateCallbackFat, DecrementerExceptionCallback, EXIProbe, InsertAlarm, OSCheckStopwatch, OSGetTime, OSSetAlarm, OSStartStopwatch, OSStopStopwatch, PADInit, PERFStartAutoSampling, SetTimer, SITransfer, SITransferNext, WriteCallback.
asm u32 OSGetTick(void)
References blr, CARD_MAX_MOUNT_STEP, r3.
Referenced by __OSInitAudioSystem, __OSStopAudioSystem, DummyLen, FIOQuery, GetInitVal, MPDWaiting, NotifyCompulsorily, TTYQuery, ttyWaiting, WaitAMinute.
static asm void __SetTime(s64 time)
References blr, CARD_MAX_MOUNT_STEP, r3, r4, r5.
Referenced by __OSSetTime.
void __OSSetTime(s64 time)
References __SetTime, CARD_MAX_MOUNT_STEP, EXIProbeReset, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts.
s64 __OSGetSystemTime()
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts.
Referenced by __DVDInterruptHandler, __OSResetSWInterruptHandler, DVDLowGetCoverStatus, DVDLowRead, DVDLowReset, OSGetResetSwitchState, Read.
asm void __OSSetTick(register u32 newTicks)
References blr, CARD_MAX_MOUNT_STEP.
static int IsLeapYear(int year)
Referenced by GetDates, GetYearDays.
static int GetYearDays(int year, int mon)
References CARD_MAX_MOUNT_STEP, IsLeapYear, LeapYearDays, YearDays.
Referenced by OSCalendarTimeToTicks.
static int GetLeapDays(int year)
References CARD_MAX_MOUNT_STEP.
Referenced by GetDates, OSCalendarTimeToTicks.
static void GetDates(int days, OSCalendarTime *td)
References CARD_MAX_MOUNT_STEP, GetLeapDays, IsLeapYear, LeapYearDays, MONTH_MAX, WEEK_DAY_MAX, YEAR_DAY_MAX, YearDays.
Referenced by OSTicksToCalendarTime.
void OSTicksToCalendarTime(s64 ticks, OSCalendarTime *td)
References BIAS, CARD_MAX_MOUNT_STEP, GetDates, MSEC_MAX, OS_SEC_TO_TICKS, OS_TICKS_TO_MSEC, OS_TICKS_TO_SEC, OS_TICKS_TO_USEC, OSSecondsToTicks, OSTicksToSeconds, SECS_IN_DAY, USEC_MAX.
OSTime OSCalendarTimeToTicks(OSCalendarTime *td)
References CARD_MAX_MOUNT_STEP, GetLeapDays, GetYearDays, MONTH_MAX, OS_MSEC_TO_TICKS, OS_SEC_TO_TICKS, OS_USEC_TO_TICKS, SECS_IN_DAY, SECS_IN_HOUR, SECS_IN_MIN, SECS_IN_YEAR.