OSInterrupt.h
__OS_INTERRUPT_MEM_0
__OS_INTERRUPT_MEM_1
__OS_INTERRUPT_MEM_2
__OS_INTERRUPT_MEM_3
__OS_INTERRUPT_MEM_ADDRESS
__OS_INTERRUPT_DSP_AI
__OS_INTERRUPT_DSP_ARAM
__OS_INTERRUPT_DSP_DSP
__OS_INTERRUPT_AI_AI
__OS_INTERRUPT_EXI_0_EXI
__OS_INTERRUPT_EXI_0_TC
__OS_INTERRUPT_EXI_0_EXT
__OS_INTERRUPT_EXI_1_EXI
__OS_INTERRUPT_EXI_1_TC
__OS_INTERRUPT_EXI_1_EXT
__OS_INTERRUPT_EXI_2_EXI
__OS_INTERRUPT_EXI_2_TC
__OS_INTERRUPT_PI_CP
__OS_INTERRUPT_PI_PE_TOKEN
__OS_INTERRUPT_PI_PE_FINISH
__OS_INTERRUPT_PI_SI
__OS_INTERRUPT_PI_DI
__OS_INTERRUPT_PI_RSW
__OS_INTERRUPT_PI_ERROR
__OS_INTERRUPT_PI_VI
__OS_INTERRUPT_PI_DEBUG
__OS_INTERRUPT_PI_HSP
__OS_INTERRUPT_MAX
OS_INTERRUPTMASK
OS_INTERRUPTMASK_MEM_0
OS_INTERRUPTMASK_MEM_1
OS_INTERRUPTMASK_MEM_2
OS_INTERRUPTMASK_MEM_3
OS_INTERRUPTMASK_MEM_ADDRESS
OS_INTERRUPTMASK_MEM
OS_INTERRUPTMASK_DSP_AI
OS_INTERRUPTMASK_DSP_ARAM
OS_INTERRUPTMASK_DSP_DSP
OS_INTERRUPTMASK_DSP
OS_INTERRUPTMASK_AI_AI
OS_INTERRUPTMASK_AI
OS_INTERRUPTMASK_EXI_0_EXI
OS_INTERRUPTMASK_EXI_0_TC
OS_INTERRUPTMASK_EXI_0_EXT
OS_INTERRUPTMASK_EXI_0
OS_INTERRUPTMASK_EXI_1_EXI
OS_INTERRUPTMASK_EXI_1_TC
OS_INTERRUPTMASK_EXI_1_EXT
OS_INTERRUPTMASK_EXI_1
OS_INTERRUPTMASK_EXI_2_EXI
OS_INTERRUPTMASK_EXI_2_TC
OS_INTERRUPTMASK_EXI_2
OS_INTERRUPTMASK_EXI
OS_INTERRUPTMASK_PI_PE_TOKEN
OS_INTERRUPTMASK_PI_PE_FINISH
OS_INTERRUPTMASK_PI_PE
OS_INTERRUPTMASK_PI_CP
OS_INTERRUPTMASK_PI_SI
OS_INTERRUPTMASK_PI_DI
OS_INTERRUPTMASK_PI_RSW
OS_INTERRUPTMASK_PI_ERROR
OS_INTERRUPTMASK_PI_VI
OS_INTERRUPTMASK_PI_DEBUG
OS_INTERRUPTMASK_PI_HSP
OS_INTERRUPTMASK_PI
typedef s16 __OSInterrupt
typedef u32 OSInterruptMask
typedef void(* __OSInterruptHandler) (__OSInterrupt interrupt, OSContext *context))(__OSInterrupt interrupt, OSContext *context)
volatile __OSInterrupt __OSLastInterrupt
volatile u32 __OSLastInterruptSrr0
volatile OSTime __OSLastInterruptTime
__OSInterruptHandler __OSSetInterruptHandler(__OSInterrupt interrupt, __OSInterruptHandler handler)
References CARD_MAX_MOUNT_STEP, InterruptHandlerTable.
Referenced by __GXFifoInit, __GXPEInit, AIInit, ARInit, DBInitInterrupts, DSPInit, DVDInit, EXIInit, HIOInit, OSInit, SIInit, VIInit.
__OSInterruptHandler __OSGetInterruptHandler(__OSInterrupt interrupt)
References CARD_MAX_MOUNT_STEP, InterruptHandlerTable.
Referenced by SetExiInterruptMask.
void __OSDispatchInterrupt(__OSException exception, OSContext *context)
References __OSGetInterruptHandler, __OSInterruptNames, __OSPIErrors, __OSReschedule, __OSSpuriousInterrupts, CARD_MAX_MOUNT_STEP, InterruptPrioTable, OS_INTERRUPTMASK_AI_AI, OS_INTERRUPTMASK_DSP_AI, OS_INTERRUPTMASK_DSP_ARAM, OS_INTERRUPTMASK_DSP_DSP, OS_INTERRUPTMASK_EXI_0_EXI, OS_INTERRUPTMASK_EXI_0_EXT, OS_INTERRUPTMASK_EXI_0_TC, OS_INTERRUPTMASK_EXI_1_EXI, OS_INTERRUPTMASK_EXI_1_EXT, OS_INTERRUPTMASK_EXI_1_TC, OS_INTERRUPTMASK_EXI_2_EXI, OS_INTERRUPTMASK_EXI_2_TC, OS_INTERRUPTMASK_MEM_0, OS_INTERRUPTMASK_MEM_1, OS_INTERRUPTMASK_MEM_2, OS_INTERRUPTMASK_MEM_3, OS_INTERRUPTMASK_MEM_ADDRESS, OS_INTERRUPTMASK_PI_CP, OS_INTERRUPTMASK_PI_DEBUG, OS_INTERRUPTMASK_PI_DI, OS_INTERRUPTMASK_PI_ERROR, OS_INTERRUPTMASK_PI_HSP, OS_INTERRUPTMASK_PI_PE_FINISH, OS_INTERRUPTMASK_PI_PE_TOKEN, OS_INTERRUPTMASK_PI_RSW, OS_INTERRUPTMASK_PI_SI, OS_INTERRUPTMASK_PI_VI, OSDisableScheduler, OSDumpContext, OSEnableScheduler, OSLoadContext, OSPhysicalToCached, OSReport.
OSInterruptMask OSGetInterruptMask(void)
References OSPhysicalToCached.
OSInterruptMask OSSetInterruptMask(OSInterruptMask mask)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, prev, SetInterruptMask.
OSInterruptMask __OSMaskInterrupts(OSInterruptMask mask)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, prev, SetInterruptMask.
Referenced by __OSReboot, __OSResetSWInterruptHandler, AlarmHandlerForTimeout, DBGEXIInit, DBInitInterrupts, EXIDetach, EXIInit, EXISelect, EXTIntrruptHandler, OSSetResetCallback, SetExiInterruptMask, TCIntrruptHandler.
OSInterruptMask __OSUnmaskInterrupts(OSInterruptMask mask)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSPhysicalToCached, OSRestoreInterrupts, prev, SetInterruptMask.
Referenced by __GXFifoInit, __GXPEInit, __OSReboot, AIInit, ARInit, DBInitInterrupts, DSPInit, DVDInit, EXIAttach, EXIDeselect, EXIDma, EXIImm, HIOInit, OSSetResetCallback, SetExiInterruptMask, SIInit, VIInit.