OSThread.c
ENQUEUE_THREAD
DEQUEUE_THREAD
ENQUEUE_THREAD_PRIO
DEQUEUE_HEAD
ALIGN4
ALIGN8
ASSERTREPORT
IsSuspended
OSThreadQueue __OSActiveThreadQueue
Referenced by __OSIsThreadActive, __OSThreadInit, OSCancelThread, OSCheckActiveThreads, OSCreateThread, OSDetachThread, OSExitThread, OSJoinThread.
OSThread* __OSFPUContext
Referenced by __OSContextInit, __OSThreadInit, OSClearContext.
OSThread* __OSCurrentThread
Referenced by __OSSwitchThread, __OSThreadInit, OSGetCurrentThread, SelectThread.
u16 _stack_end[][]
Referenced by __OSThreadInit.
u16 _stack_addr[][]
Referenced by __OSThreadInit.
OSThreadQueue RunQueue[32][32]
Referenced by __OSThreadInit, OSCheckActiveThreads, SelectThread, SetRun, UnsetRun.
OSThread IdleThread
Referenced by OSGetIdleFunction, OSSetIdleFunction.
OSThread DefaultThread
Referenced by __OSThreadInit.
OSContext IdleContext
Referenced by __OSThreadInit, SelectThread.
vu32 RunQueueBits
Referenced by __OSThreadInit, OSCheckActiveThreads, SelectThread, SetRun, UnsetRun.
volatile int RunQueueHint
Referenced by __OSReschedule, __OSThreadInit, OSCancelThread, OSExitThread, OSSleepThread, OSSuspendThread, SelectThread, SetEffectivePriority, SetRun.
s32 Reschedule
Referenced by __OSThreadInit, OSDisableScheduler, OSEnableScheduler, SelectThread.
void __OSThreadInit()
References __OSActiveThreadQueue, __OSCurrentThread, __OSFPUContext, _stack_addr, _stack_end, OSThread::attr, OSThread::base, CARD_MAX_MOUNT_STEP, OSThread::context, DefaultThread, ENQUEUE_THREAD, OSMutexQueue::head, IdleContext, MSR_FP, OSThread::mutex, OSClearContext, OSInitThreadQueue, OSSetCurrentContext, PPCMfmsr, OSThread::priority, OSThread::queueJoin, OSThread::queueMutex, Reschedule, RunQueue, RunQueueBits, RunQueueHint, OSThread::stackBase, OSThread::stackEnd, OSThread::state, OSThread::suspend, OSMutexQueue::tail, OSThread::val.
Referenced by OSInit.
void OSInitThreadQueue(OSThreadQueue *queue)
References OSThreadQueue::head, OSThreadQueue::tail.
Referenced by __GXPEInit, __OSThreadInit, CARDInit, DVDInit, OSCreateThread, OSInitCond, OSInitMessageQueue, OSInitMutex, VIInit.
OSThread * OSGetCurrentThread()
References __OSCurrentThread.
Referenced by __GXFifoInit, GXSetCurrentGXThread, OSExitThread, OSLockMutex, OSSleepThread, OSTryLockMutex, OSUnlockMutex, OSWaitCond, SelectThread.
static void __OSSwitchThread(OSThread *nextThread)
References __OSCurrentThread, CARD_MAX_MOUNT_STEP, OSLoadContext, OSSetCurrentContext.
Referenced by SelectThread.
BOOL OSIsThreadSuspended(OSThread *thread)
References FALSE, OSThread::suspend, TRUE.
int OSIsThreadTerminated(OSThread *thread)
References OSThread::state.
static int __OSIsThreadActive(OSThread *thread)
References __OSActiveThreadQueue, CARD_MAX_MOUNT_STEP, FALSE, OSThreadQueue::head, OSThread::state, TRUE.
Referenced by OSCancelThread, OSCreateThread, OSDetachThread, OSExitThread, OSJoinThread, OSResumeThread, OSSetThreadPriority, OSSleepThread, OSSuspendThread, OSWakeupThread.
s32 OSDisableScheduler(void)
References OSDisableInterrupts, OSRestoreInterrupts, Reschedule.
Referenced by __OSDispatchInterrupt, DecrementerExceptionCallback, OSResetSystem, OSWaitCond.
s32 OSEnableScheduler(void)
References OSDisableInterrupts, OSRestoreInterrupts, Reschedule.
Referenced by __OSDispatchInterrupt, DecrementerExceptionCallback, OSResetSystem, OSWaitCond.
static void SetRun(OSThread *thread)
References CARD_MAX_MOUNT_STEP, ENQUEUE_THREAD, IsSuspended, OS_PRIORITY_MAX, OS_THREAD_STATE_READY, OSThread::priority, OSThread::queue, RunQueue, RunQueueBits, RunQueueHint, OSThread::state, OSThread::suspend.
Referenced by OSResumeThread, OSWakeupThread, SelectThread, SetEffectivePriority.
static void UnsetRun(OSThread *thread)
References CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, OSThreadQueue::head, NULL, OS_PRIORITY_MAX, OS_THREAD_STATE_READY, OSThread::priority, OSThread::queue, RunQueue, RunQueueBits, OSThread::state.
Referenced by OSCancelThread, OSSuspendThread, SetEffectivePriority.
s32 __OSGetEffectivePriority(OSThread *thread)
References OSThread::base, CARD_MAX_MOUNT_STEP, OSThreadQueue::head, OSMutexQueue::head, OSMutex::link, OSMutexLink::next, OSThread::priority, OSMutex::queue, OSThread::queueMutex.
Referenced by OSCheckActiveThreads, OSResumeThread, OSUnlockMutex, OSWaitCond, UpdatePriority.
static OSThread * SetEffectivePriority(OSThread *thread, s32 priority)
References CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, ENQUEUE_THREAD_PRIO, FALSE, IsSuspended, OSThread::mutex, OSThread::priority, OSThread::queue, RunQueueHint, SetRun, OSThread::state, OSThread::suspend, OSMutex::thread, UnsetRun.
Referenced by __OSPromoteThread, UpdatePriority.
static void UpdatePriority(OSThread *thread)
References __OSGetEffectivePriority, OSThread::priority, SetEffectivePriority, OSThread::suspend.
Referenced by OSCancelThread, OSResumeThread, OSSetThreadPriority, OSSuspendThread.
void __OSPromoteThread(OSThread *thread, s32 priority)
References OSThread::priority, SetEffectivePriority, OSThread::suspend.
Referenced by OSLockMutex.
static OSThread * SelectThread(int yield)
References __OSCurrentThread, __OSSwitchThread, CARD_MAX_MOUNT_STEP, DEQUEUE_HEAD, OSThreadQueue::head, IdleContext, NULL, OS_PRIORITY_MAX, OS_PRIORITY_MIN, OSClearContext, OSDisableInterrupts, OSEnableInterrupts, OSGetCurrentContext, OSGetCurrentThread, OSSaveContext, OSSetCurrentContext, Reschedule, RunQueue, RunQueueBits, RunQueueHint, SetRun.
Referenced by __OSReschedule, OSExitThread, OSYieldThread.
void __OSReschedule(void)
References RunQueueHint, SelectThread.
Referenced by __OSDispatchInterrupt, DecrementerExceptionCallback, OSCancelThread, OSExitThread, OSResumeThread, OSSetThreadPriority, OSSleepThread, OSSuspendThread, OSWakeupThread.
void OSYieldThread(void)
References OSDisableInterrupts, OSRestoreInterrupts, SelectThread.
int OSCreateThread(OSThread *thread, void *(*func)(void *), void *param, void *stack, u32 stackSize, s32 priority, u16 attr)
References __OSActiveThreadQueue, __OSIsThreadActive, OSThread::attr, OSThread::base, CARD_MAX_MOUNT_STEP, OSThread::context, ENQUEUE_THREAD, FALSE, OSContext::gpr, OSContext::lr, OSThread::mutex, NULL, OSDisableInterrupts, OSExitThread, OSInitContext, OSInitThreadQueue, OSRestoreInterrupts, OSThread::priority, OSThread::queueJoin, OSThread::queueMutex, OSThread::stackBase, OSThread::stackEnd, OSThread::state, OSThread::suspend, TRUE, OSThread::val.
Referenced by OSSetIdleFunction.
void OSExitThread(void *val)
References __OSActiveThreadQueue, __OSIsThreadActive, __OSReschedule, __OSUnlockAllMutex, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, OSClearContext, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, OSWakeupThread, RunQueueHint, SelectThread.
Referenced by OSCreateThread.
void OSCancelThread(OSThread *thread)
References __OSActiveThreadQueue, __OSIsThreadActive, __OSReschedule, __OSUnlockAllMutex, OSThread::attr, CARD_MAX_MOUNT_STEP, OSThread::context, DEQUEUE_THREAD, OSThread::mutex, OSClearContext, OSDisableInterrupts, OSRestoreInterrupts, OSWakeupThread, OSThread::queue, OSThread::queueJoin, RunQueueHint, OSThread::state, OSThread::suspend, OSMutex::thread, UnsetRun, UpdatePriority.
Referenced by KillThreads, OSSetIdleFunction.
int OSJoinThread(OSThread *thread, void **val)
References __OSActiveThreadQueue, __OSIsThreadActive, OSThread::attr, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, FALSE, OSThreadQueue::head, NULL, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, OSThread::queueJoin, OSThread::state, TRUE, OSThread::val.
void OSDetachThread(OSThread *thread)
References __OSActiveThreadQueue, __OSIsThreadActive, OSThread::attr, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, OSDisableInterrupts, OSRestoreInterrupts, OSWakeupThread, OSThread::queueJoin, OSThread::state.
s32 OSResumeThread(OSThread *thread)
References __OSGetEffectivePriority, __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, ENQUEUE_THREAD_PRIO, OSThread::mutex, OSDisableInterrupts, OSRestoreInterrupts, OSThread::priority, OSThread::queue, SetRun, OSThread::state, OSThread::suspend, OSMutex::thread, UpdatePriority.
Referenced by GXUnderflowHandler, OSSetIdleFunction.
s32 OSSuspendThread(OSThread *thread)
References __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, DEQUEUE_THREAD, ENQUEUE_THREAD, OSThread::mutex, OSDisableInterrupts, OSRestoreInterrupts, OSThread::priority, OSThread::queue, RunQueueHint, OSThread::state, OSThread::suspend, OSMutex::thread, UnsetRun, UpdatePriority.
Referenced by GXOverflowHandler.
void OSSleepThread(OSThreadQueue *queue)
References __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, ENQUEUE_THREAD_PRIO, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, RunQueueHint.
Referenced by __CARDSync, DVDCancel, DVDCancelAll, DVDCancelStream, DVDChangeDisk, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInquiry, DVDPrepareStream, DVDReadPrio, DVDSeekPrio, DVDStopStreamAtEnd, GXWaitDrawDone, OSJamMessage, OSJoinThread, OSLockMutex, OSReceiveMessage, OSSendMessage, OSWaitCond, VIWaitForRetrace.
void OSWakeupThread(OSThreadQueue *queue)
References __OSIsThreadActive, __OSReschedule, CARD_MAX_MOUNT_STEP, DEQUEUE_HEAD, OSThreadQueue::head, OS_THREAD_STATE_MORIBUND, OSDisableInterrupts, OSRestoreInterrupts, OSThread::queue, SetRun, OSThread::state, OSThread::suspend.
Referenced by __CARDSyncCallback, __OSUnlockAllMutex, __VIRetraceHandler, cbForCancelAllSync, cbForCancelStreamSync, cbForCancelSync, cbForChangeDiskSync, cbForGetStreamErrorStatusSync, cbForGetStreamLengthSync, cbForGetStreamPlayAddrSync, cbForGetStreamStartAddrSync, cbForInquirySync, cbForPrepareStreamSync, cbForReadSync, cbForSeekSync, cbForStopStreamAtEndSync, GXFinishInterruptHandler, OSCancelThread, OSDetachThread, OSExitThread, OSJamMessage, OSReceiveMessage, OSSendMessage, OSSignalCond, OSUnlockMutex, OSWaitCond.
BOOL OSSetThreadPriority(OSThread *thread, s32 priority)
References __OSIsThreadActive, __OSReschedule, OSThread::base, CARD_MAX_MOUNT_STEP, FALSE, OSDisableInterrupts, OSRestoreInterrupts, OSThread::state, TRUE, UpdatePriority.
s32 OSGetThreadPriority(OSThread *thread)
References OSThread::base.
OSThread * OSSetIdleFunction(void(*idleFunction)(void *), void *param, void *stack, u32 stackSize)
References CARD_MAX_MOUNT_STEP, IdleThread, NULL, OSCancelThread, OSCreateThread, OSResumeThread, OSThread::state.
OSThread * OSGetIdleFunction()
References IdleThread, NULL, OSThread::state.
static int CheckThreadQueue(OSThreadQueue *queue)
References FALSE, OSThreadQueue::head, OSThread::link, OSThreadLink::next, NULL, OSThreadLink::prev, OSThreadQueue::tail, TRUE.
Referenced by OSCheckActiveThreads.
static BOOL IsMember(OSThreadQueue *queue, OSThread *thread)
References CARD_MAX_MOUNT_STEP, FALSE, OSThreadQueue::head, OSThread::link, OSThreadLink::next, TRUE.
Referenced by OSCheckActiveThreads.
s32 OSCheckActiveThreads()
References __OSActiveThreadQueue, __OSCheckDeadLock, __OSCheckMutexes, __OSGetEffectivePriority, ASSERTREPORT, CARD_MAX_MOUNT_STEP, CheckThreadQueue, OSThreadQueue::head, OSMutexQueue::head, IsMember, IsSuspended, OSThread::linkActive, OSThreadLink::next, NULL, OS_PRIORITY_MAX, OS_THREAD_STACK_MAGIC, OSDisableInterrupts, OSPanic, OSReport, OSRestoreInterrupts, OSThreadLink::prev, OSThread::priority, OSThread::queue, OSThread::queueJoin, OSThread::queueMutex, RunQueue, RunQueueBits, OSThread::stackEnd, OSThread::state, OSThread::suspend, OSThreadQueue::tail, OSMutexQueue::tail.