OSCache.h
LC_BASE_PREFIX
LC_BASE
LCGetBase
void DCInvalidateRange(void *addr, u32 nBytes)
Referenced by __ARChecksize, __AXProcessAux, __AXSyncPBs, __CARDRawReadAsync, __CARDUnlock, __OSReadROM, __OSReadROMAsync, AlarmHandler, CARDReadAsync, DoMount, DVDChangeDiskAsync, GetUsbAdapterMode, InitializeCodeCheck, issueCommand, LoadChannelInfo, MCCRead, ReadSram, SetUsbAdapterMode, stateCheckID.
void DCFlushRange(void *addr, u32 nBytes)
Referenced by __ARChecksize, __AXNextFrame, __AXOutInit, __AXPrintStudio, __AXSyncPBs, __AXVPBInit, __CARDUnlock, __OSInitAudioSystem, DOLLoadImage, FlushChannelInfo, InitializeCodeClear, InitializeCodeSet, MCCWrite, Relocate, SetUsbAdapterMode, Undo.
void DCStoreRange(void *addr, u32 nBytes)
Referenced by __CARDUpdateDir, __CARDUpdateFatBlock, CARDFormatAsync, CARDWriteAsync, ExpandFontSheet.
void DCFlushRangeNoSync(void *addr, u32 nBytes)
Referenced by __AXProcessAux, __OSInitSystemCall, OSExceptionInit.
void DCStoreRangeNoSync(void *addr, u32 nBytes)
void DCZeroRange(void *addr, u32 nBytes)
void DCTouchRange(void *addr, u32 nBytes)
void ICInvalidateRange(void *addr, u32 nBytes)
Referenced by __OSInitSystemCall, __OSReboot, OSExceptionInit, Relocate, Undo.
void LCEnable(void)
References __LCEnable, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by LCAlloc, LCAllocNoInvalidate.
void LCDisable(void)
References blr, CARD_MAX_MOUNT_STEP, HID2, LC_BASE_PREFIX, LC_LINES, r3, r4.
void LCLoadBlocks(void *destTag, void *srcAddr, u32 numBlocks)
void LCStoreBlocks(void *destAddr, void *srcTag, u32 numBlocks)
u32 LCLoadData(void *destAddr, void *srcAddr, u32 nBytes)
References CARD_MAX_MOUNT_STEP, LCLoadBlocks.
u32 LCStoreData(void *destAddr, void *srcAddr, u32 nBytes)
References CARD_MAX_MOUNT_STEP, LCStoreBlocks.
u32 LCQueueLength(void)
References blr, CARD_MAX_MOUNT_STEP, HID2, r3, r4.
void LCQueueWait(u32 len)
void LCFlushQueue(void)
References CARD_MAX_MOUNT_STEP, PPCMtdmaL, PPCMtdmaU, PPCSync.
void __OSCacheInit(void)
References DBPrintf, DCEnable, DMAErrorHandler, HID0_DCE, HID0_ICE, ICEnable, L2CR_L2E, L2Enable, L2Init, OS_ERROR_MACHINE_CHECK, OSSetErrorHandler, PPCMfhid0, PPCMfl2cr.
Referenced by __declspec, OSInit.