OSMutex.c
ENQUEUE_MUTEX
DEQUEUE_MUTEX
DEQUEUE_HEAD
static BOOL IsMember(OSMutexQueue *queue, OSMutex *mutex)
References CARD_MAX_MOUNT_STEP, FALSE, OSMutexQueue::head, OSMutex::link, OSMutexLink::next, TRUE.
BOOL __OSCheckMutex(OSMutex *mutex)
References OSMutex::count, FALSE, OSThreadQueue::head, OSThread::link, OSThreadLink::next, NULL, OSThreadLink::prev, OSThread::priority, OSMutex::queue, OSThread::state, OSThreadQueue::tail, OSMutex::thread, TRUE.
Referenced by __OSCheckMutexes.
BOOL __OSCheckDeadLock(OSThread *thread)
References FALSE, OSThread::mutex, OSMutex::thread, TRUE.
Referenced by OSCheckActiveThreads, OSLockMutex.
BOOL __OSCheckMutexes(OSThread *thread)
References __OSCheckMutex, FALSE, OSMutexQueue::head, OSMutex::link, OSMutexLink::next, OSThread::queueMutex, OSMutex::thread, TRUE.
Referenced by OSCheckActiveThreads.
void OSInitMutex(OSMutex *mutex)
References OSMutex::count, OSInitThreadQueue, OSMutex::queue, OSMutex::thread.
void OSLockMutex(OSMutex *mutex)
References __OSCheckDeadLock, __OSPromoteThread, CARD_MAX_MOUNT_STEP, OSMutex::count, ENQUEUE_MUTEX, NULL, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, OSSleepThread, OSThread::priority, OSMutex::queue, OSMutex::thread.
Referenced by OSWaitCond.
void OSUnlockMutex(OSMutex *mutex)
References __OSGetEffectivePriority, CARD_MAX_MOUNT_STEP, OSMutex::count, DEQUEUE_MUTEX, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, OSWakeupThread, OSThread::priority, OSMutex::queue, OSMutex::thread.
void __OSUnlockAllMutex(OSThread *thread)
References CARD_MAX_MOUNT_STEP, OSMutex::count, DEQUEUE_HEAD, OSMutexQueue::head, OSWakeupThread, OSMutex::queue, OSThread::queueMutex, OSMutex::thread.
Referenced by OSCancelThread, OSExitThread.
BOOL OSTryLockMutex(OSMutex *mutex)
References CARD_MAX_MOUNT_STEP, OSMutex::count, ENQUEUE_MUTEX, FALSE, OSDisableInterrupts, OSGetCurrentThread, OSRestoreInterrupts, OSMutex::thread, TRUE.
void OSInitCond(OSCond *cond)
References CARD_MAX_MOUNT_STEP, OSInitThreadQueue.
void OSWaitCond(OSCond *cond, OSMutex *mutex)
References __OSGetEffectivePriority, CARD_MAX_MOUNT_STEP, OSMutex::count, DEQUEUE_MUTEX, OSDisableInterrupts, OSDisableScheduler, OSEnableScheduler, OSGetCurrentThread, OSLockMutex, OSRestoreInterrupts, OSSleepThread, OSWakeupThread, OSThread::priority, OSMutex::queue, OSMutex::thread.
void OSSignalCond(OSCond *cond)
References CARD_MAX_MOUNT_STEP, OSWakeupThread.