OSCache.c
HID2
LC_LINES
CACHE_LINES
void DMAErrorHandler(OSError error, OSContext *context,...)
References CARD_MAX_MOUNT_STEP, HID2_DCHERR, HID2_DCMERR, HID2_DNCERR, HID2_DQOERR, OSDumpContext, OSReport, PPCHalt, PPCMfhid2, PPCMthid2, OSContext::srr1, SRR1_DMA_BIT.
Referenced by __OSCacheInit.
asm void DCFlashInvalidate(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, r3.
asm void DCEnable(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, r3, sync.
Referenced by __OSCacheInit.
asm void DCDisable(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, r3, sync.
asm void DCFreeze(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, r3, sync.
asm void DCUnfreeze(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, r3.
asm void DCTouchLoad(register void *addr)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCBlockZero(register void *addr)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCBlockStore(register void *addr)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCBlockFlush(register void *addr)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCBlockInvalidate(register void *addr)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCInvalidateRange(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCFlushRange(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCStoreRange(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCFlushRangeNoSync(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCStoreRangeNoSync(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCZeroRange(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP.
asm void DCTouchRange(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP.
asm void ICInvalidateRange(register void *addr, register u32 nBytes)
References blr, CARD_MAX_MOUNT_STEP, icbi, isync, sync.
asm void ICFlashInvalidate(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, r3.
Referenced by __OSDoHotReset, __OSPSInit, DOLLoadImage, Run.
asm void ICEnable(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, isync, r3.
Referenced by __OSCacheInit.
asm void ICDisable(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, isync, r3.
asm void ICFreeze(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, isync, r3.
asm void ICUnfreeze(void)
References blr, CARD_MAX_MOUNT_STEP, HID0, r3.
asm void ICBlockInvalidate(register void *addr)
References blr, CARD_MAX_MOUNT_STEP, icbi.
asm void ICSync(void)
References blr, CARD_MAX_MOUNT_STEP, isync.
Referenced by DOLLoadImage.
static asm void __LCEnable(void)
References blr, CACHE_LINES, CARD_MAX_MOUNT_STEP, DBAT3L, DBAT3U, HID2, isync, LC_BASE_PREFIX, LC_LINES, OS_CACHED_REGION_PREFIX, r3, r4, r5.
Referenced by LCEnable.
void LCEnable(void)
References __LCEnable, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by LCAlloc, LCAllocNoInvalidate.
asm void LCDisable(void)
References blr, CARD_MAX_MOUNT_STEP, HID2, LC_BASE_PREFIX, LC_LINES, r3, r4.
asm void LCAllocOneTag(register BOOL invalidate, register void *tag)
References blr, CARD_MAX_MOUNT_STEP.
asm void LCAllocTags(register BOOL invalidate, register void *startTag, register u32 numBlocks)
References blr, CARD_MAX_MOUNT_STEP.
Referenced by LCAlloc, LCAllocNoInvalidate.
asm void LCLoadBlocks(register void *destTag, register void *srcAddr, register u32 numBlocks)
References blr, CARD_MAX_MOUNT_STEP, DMA_L, DMA_U.
Referenced by LCLoadData.
asm void LCStoreBlocks(register void *destAddr, register void *srcTag, register u32 numBlocks)
References blr, CARD_MAX_MOUNT_STEP, DMA_L, DMA_U.
Referenced by LCStoreData.
void LCAlloc(void *addr, u32 nBytes)
References CARD_MAX_MOUNT_STEP, LCAllocTags, LCEnable, PPCMfhid2.
void LCAllocNoInvalidate(void *addr, u32 nBytes)
References CARD_MAX_MOUNT_STEP, LCAllocTags, LCEnable, PPCMfhid2.
u32 LCLoadData(void *destAddr, void *srcAddr, u32 nBytes)
References CARD_MAX_MOUNT_STEP, LCLoadBlocks.
u32 LCStoreData(void *destAddr, void *srcAddr, u32 nBytes)
References CARD_MAX_MOUNT_STEP, LCStoreBlocks.
asm u32 LCQueueLength(void)
References blr, CARD_MAX_MOUNT_STEP, HID2, r3, r4.
asm void LCQueueWait(register u32 len)
References blr, CARD_MAX_MOUNT_STEP, HID2, r3, r4.
void LCFlushQueue()
References CARD_MAX_MOUNT_STEP, PPCMtdmaL, PPCMtdmaU, PPCSync.
static void L2Init(void)
References CARD_MAX_MOUNT_STEP, L2Disable, L2GlobalInvalidate, MSR_DR, MSR_IR, PPCMfmsr, PPCMtmsr.
Referenced by __OSCacheInit.
void L2Enable(void)
References L2CR_L2E, L2CR_L2I, PPCMfl2cr, PPCMtl2cr.
Referenced by __OSCacheInit.
void L2Disable(void)
References CARD_MAX_MOUNT_STEP, PPCMfl2cr, PPCMtl2cr.
Referenced by L2GlobalInvalidate, L2Init.
void L2GlobalInvalidate(void)
References DBPrintf, L2Disable, PPCMfl2cr, PPCMtl2cr.
Referenced by L2Init.
void L2SetDataOnly(BOOL dataOnly)
References CARD_MAX_MOUNT_STEP, PPCMfl2cr, PPCMtl2cr.
void L2SetWriteThrough(BOOL writeThrough)
References CARD_MAX_MOUNT_STEP, PPCMfl2cr, PPCMtl2cr.
void __OSCacheInit()
References DBPrintf, DCEnable, DMAErrorHandler, HID0_DCE, HID0_ICE, ICEnable, L2CR_L2E, L2Enable, L2Init, OS_ERROR_MACHINE_CHECK, OSSetErrorHandler, PPCMfhid0, PPCMfl2cr.
Referenced by __declspec, OSInit.