OSArena.c
ROUND
TRUNC
void* __OSArenaHi
Referenced by OSGetArenaHi, OSGetArenaLo, OSSetArenaHi.
void* __OSArenaLo
Referenced by OSGetArenaHi, OSGetArenaLo, OSSetArenaLo.
void * OSGetArenaHi()
References __OSArenaHi, __OSArenaLo, CARD_MAX_MOUNT_STEP.
Referenced by __DEMOInitMem, __fstLoad, LoadMemInfo, OSAllocFromArenaHi, OSInit.
void * OSGetArenaLo()
References __OSArenaHi, __OSArenaLo, CARD_MAX_MOUNT_STEP.
Referenced by __DEMOInitMem, LoadMemInfo, OSAllocFromArenaLo, OSInit.
void OSSetArenaHi(void *newHi)
References __OSArenaHi, CARD_MAX_MOUNT_STEP.
Referenced by __fstLoad, LoadMemInfo, OSAllocFromArenaHi, OSInit.
void OSSetArenaLo(void *newLo)
References __OSArenaLo, CARD_MAX_MOUNT_STEP.
Referenced by __DEMOInitMem, LoadMemInfo, OSAllocFromArenaLo, OSInit.
void * OSAllocFromArenaLo(u32 size, u32 align)
References CARD_MAX_MOUNT_STEP, OSGetArenaLo, OSSetArenaLo, ROUND, size.
void * OSAllocFromArenaHi(u32 size, u32 align)
References CARD_MAX_MOUNT_STEP, OSGetArenaHi, OSSetArenaHi, size, TRUNC.