OSFont.c
OSFontHeader* FontData
Referenced by ExpandFontSheet, OSGetFontTexel, OSGetFontTexture, OSInitFont, OSLoadFont.
u8* SheetImage
Referenced by OSGetFontTexel, OSGetFontTexture, OSInitFont, OSLoadFont.
u8* WidthTable
Referenced by OSGetFontTexel, OSGetFontTexture, OSGetFontWidth, OSLoadFont.
int CharsInSheet
Referenced by OSGetFontTexel, OSGetFontTexture, OSLoadFont.
u16 HankakuToCode[][]
Referenced by GetFontCode.
u16 Zenkaku2Code[][]
Referenced by GetFontCode.
static int GetFontCode(u16 code)
References CARD_MAX_MOUNT_STEP, HankakuToCode, OS_FONT_ENCODE_SJIS, OSGetFontEncode, Zenkaku2Code.
Referenced by OSGetFontTexel, OSGetFontTexture, OSGetFontWidth.
static void Decode(u16 *s, u16 *d)
References CARD_MAX_MOUNT_STEP.
Referenced by OSLoadFont.
static u32 GetFontSize(u8 *buf)
References CARD_MAX_MOUNT_STEP.
Referenced by ReadFont.
u16 OSGetFontEncode(void)
References CARD_MAX_MOUNT_STEP, OS_FONT_ENCODE_ANSI, OS_FONT_ENCODE_SJIS, OSPhysicalToCached, VI_DEBUG, VI_DEBUG_PAL, VI_DTV_STAT, VI_EURGB60, VI_MPAL, VI_NTSC, VI_PAL.
Referenced by CARDFormatAsync, DEMODumpROMFont, DEMOInitROMFont, GetFontCode, OSGetFontTexel, OSGetFontTexture, OSGetFontWidth, OSInitFont, ReadFont, VerifyID.
static void ReadROM(void *buf, int length, int offset)
References __OSReadROM, CARD_MAX_MOUNT_STEP.
Referenced by ReadFont.
static u32 ReadFont(void *img)
References CARD_MAX_MOUNT_STEP, GetFontSize, OS_FONT_ENCODE_SJIS, OS_FONT_ROM_SIZE_ANSI, OS_FONT_ROM_SIZE_SJIS, OSGetFontEncode, ReadROM.
Referenced by OSLoadFont.
u32 OSLoadFont(OSFontHeader *fontData, void *temp)
References CARD_MAX_MOUNT_STEP, CharsInSheet, Decode, FontData, NULL, ReadFont, OSFontHeader::sheetColumn, SheetImage, OSFontHeader::sheetRow, size, OSFontHeader::widthTable, WidthTable.
Referenced by DEMODumpROMFont, OSInitFont.
char * OSGetFontTexel(char *string, void *image, s32 pos, long stride, long *width)
References OSFontHeader::c0, CARD_MAX_MOUNT_STEP, OSFontHeader::cellHeight, OSFontHeader::cellWidth, CharsInSheet, FontData, GetFontCode, GX_TF_I4, OS_FONT_ENCODE_SJIS, OSGetFontEncode, OSFontHeader::sheetColumn, OSFontHeader::sheetFormat, OSFontHeader::sheetImage, SheetImage, OSFontHeader::sheetSize, OSFontHeader::sheetWidth, src, WidthTable.
static void ExpandFontSheet(u8 *src, u8 *dst)
References OSFontHeader::c0, CARD_MAX_MOUNT_STEP, DCStoreRange, FontData, GX_TF_I4, GX_TF_IA4, OSFontHeader::sheetFormat, OSFontHeader::sheetFullSize, src.
Referenced by OSInitFont.
int OSInitFont(OSFontHeader *fontData)
References CARD_MAX_MOUNT_STEP, ExpandFontSheet, FontData, OS_FONT_ENCODE_SJIS, OSGetFontEncode, OSLoadFont, OSFontHeader::sheetImage, SheetImage, size.
Referenced by DEMODumpROMFont, DEMOInitROMFont.
char * OSGetFontTexture(char *string, void **image, s32 *x, long *y, long *width)
References CARD_MAX_MOUNT_STEP, OSFontHeader::cellHeight, OSFontHeader::cellWidth, CharsInSheet, FontData, GetFontCode, NULL, OS_FONT_ENCODE_SJIS, OSGetFontEncode, OSFontHeader::sheetColumn, SheetImage, OSFontHeader::sheetSize, WidthTable.
char * OSGetFontWidth(char *string, s32 *width)
References CARD_MAX_MOUNT_STEP, GetFontCode, OS_FONT_ENCODE_SJIS, OSGetFontEncode, WidthTable.
Referenced by DEMOGetRFTextWidth.