PPCArch.h
CTR
XER
LR
UPMC1
UPMC2
UPMC3
UPMC4
USIA
UMMCR0
UMMCR1
HID0
HID1
PVR
IBAT0U
IBAT0L
IBAT1U
IBAT1L
IBAT2U
IBAT2L
IBAT3U
IBAT3L
DBAT0U
DBAT0L
DBAT1U
DBAT1L
DBAT2U
DBAT2L
DBAT3U
DBAT3L
SDR1
SPRG0
SPRG1
SPRG2
SPRG3
DAR
DSISR
SRR0
SRR1
EAR
DABR
TBL
TBU
L2CR
DEC
IABR
PMC1
PMC2
PMC3
PMC4
SIA
MMCR0
MMCR1
THRM1
THRM2
THRM3
ICTC
GQR0
GQR1
GQR2
GQR3
GQR4
GQR5
GQR6
GQR7
HID2
WPAR
DMA_U
DMA_L
MSR_POW
MSR_ILE
MSR_EE
MSR_PR
MSR_FP
MSR_ME
MSR_FE0
MSR_SE
MSR_BE
MSR_FE1
MSR_IP
MSR_IR
MSR_DR
MSR_PM
MSR_RI
MSR_LE
MSR_POW_BIT
MSR_ILE_BIT
MSR_EE_BIT
MSR_PR_BIT
MSR_FP_BIT
MSR_ME_BIT
MSR_FE0_BIT
MSR_SE_BIT
MSR_BE_BIT
MSR_FE1_BIT
MSR_IP_BIT
MSR_IR_BIT
MSR_DR_BIT
MSR_PM_BIT
MSR_RI_BIT
MSR_LE_BIT
HID0_EMCP
HID0_DBP
HID0_EBA
HID0_EBD
HID0_BCLK
HID0_ECLK
HID0_PAR
HID0_DOZE
HID0_NAP
HID0_SLEEP
HID0_DPM
HID0_NHR
HID0_ICE
HID0_DCE
HID0_ILOCK
HID0_DLOCK
HID0_ICFI
HID0_DCFI
HID0_SPD
HID0_IFEM
HID0_SGE
HID0_DCFA
HID0_BTIC
HID0_ABE
HID0_BHT
HID0_NOOPTI
HID0_ICE_BIT
HID0_DCE_BIT
HID0_ILOCK_BIT
HID0_DLOCK_BIT
HID2_LSQE
HID2_WPE
HID2_PSE
HID2_LCE
HID2_DCHERR
HID2_DNCERR
HID2_DCMERR
HID2_DQOERR
HID2_DCHEE
HID2_DNCEE
HID2_DCMEE
HID2_DQOEE
HID2_DMAQL_MASK
HID2_DMAQL_SHIFT
HID2_LSQE_BIT
HID2_WPE_BIT
HID2_PSE_BIT
HID2_LCE_BIT
HID2_DCHERR_BIT
HID2_DNCERR_BIT
HID2_DCMERR_BIT
HID2_DQOERR_BIT
HID2_DCHEE_BIT
HID2_DNCEE_BIT
HID2_DCMEE_BIT
HID2_DQOEE_BIT
GQR_LOAD_SCALE_MASK
GQR_LOAD_TYPE_MASK
GQR_STORE_SCALE_MASK
GQR_STORE_TYPE_MASK
DMA_U_ADDR_MASK
DMA_U_LEN_U_MASK
DMA_L_LC_ADDR_MASK
DMA_L_LOAD
DMA_L_STORE
DMA_L_LEN_MASK
DMA_L_TRIGGER
DMA_L_FLUSH
WPAR_ADDR
WPAR_BNE
SRR1_DMA_BIT
SRR1_L2DP_BIT
L2CR_L2E
L2CR_L2PE
L2CR_L2SIZ_256K
L2CR_L2SIZ_512K
L2CR_L2SIZ_1M
L2CR_L2CLK_1_0
L2CR_L2CLK_1_5
L2CR_L2CLK_2_0
L2CR_L2CLK_2_5
L2CR_L2CLK_3_0
L2CR_RAM_FLOW_THRU_BURST
L2CR_RAM_PIPELINE_BURST
L2CR_RAM_PIPELINE_LATE
L2CR_L2DO
L2CR_L2I
L2CR_L2CTL
L2CR_L2WT
L2CR_L2TS
L2CR_L2OH_0_5
L2CR_L2OH_1_0
L2CR_L2SL
L2CR_L2DF
L2CR_L2BYP
L2CR_L2CS
L2CR_L2DRO
L2CR_L2CTR_MASK
L2CR_L2IP
MMCR0_DIS
MMCR0_DP
MMCR0_DU
MMCR0_DMS
MMCR0_DMR
MMCR0_ENINT
MMCR0_DISCOUNT
MMCR0_RTCSELECT_MASK
MMCR0_RTCSELECT_63
MMCR0_RTCSELECT_55
MMCR0_RTCSELECT_51
MMCR0_RTCSELECT_47
MMCR0_INTONBITTRANS
MMCR0_THRESHOLD_MASK
MMCR0_THRESHOLD
MMCR0_PMC1INTCONTROL
MMCR0_PMC2INTCONTROL
MMCR0_PMCTRIGGER
MMCR0_PMC1SELECT_MASK
MMCR0_PMC2SELECT_MASK
MMCR1_PMC3SELECT_MASK
MMCR1_PMC4SELECT_MASK
PMC1_OV
PMC1_COUNTER
PMC2_OV
PMC2_COUNTER
PMC3_OV
PMC3_COUNTER
PMC4_OV
PMC4_COUNTER
MMCR0_PMC1_HOLD
MMCR0_PMC1_CYCLE
MMCR0_PMC1_INSTRUCTION
MMCR0_PMC1_TRANSITION
MMCR0_PMC1_DISPATCHED
MMCR0_PMC1_EIEIO
MMCR0_PMC1_ITLB_CYCLE
MMCR0_PMC1_L2_HIT
MMCR0_PMC1_EA
MMCR0_PMC1_IABR
MMCR0_PMC1_L1_MISS
MMCR0_PMC1_Bx_UNRESOLVED
MMCR0_PMC1_Bx_STALL_CYCLE
MMCR0_PMC1_IC_FETCH_MISS
MMCR0_PMC2_HOLD
MMCR0_PMC2_CYCLE
MMCR0_PMC2_INSTRUCTION
MMCR0_PMC2_TRANSITION
MMCR0_PMC2_DISPATCHED
MMCR0_PMC2_IC_MISS
MMCR0_PMC2_ITLB_MISS
MMCR0_PMC2_L2_I_MISS
MMCR0_PMC2_Bx_FALL_TROUGH
MMCR0_PMC2_PR_SWITCH
MMCR0_PMC2_RESERVED_LOAD
MMCR0_PMC2_LOAD_STORE
MMCR0_PMC2_SNOOP
MMCR0_PMC2_L1_CASTOUT
MMCR0_PMC2_SYSTEM
MMCR0_PMC2_IC_FETCH_MISS
MMCR0_PMC2_Bx_OUT_OF_ORDER
MMCR1_PMC3_HOLD
MMCR1_PMC3_CYCLE
MMCR1_PMC3_INSTRUCTION
MMCR1_PMC3_TRANSITION
MMCR1_PMC3_DISPATCHED
MMCR1_PMC3_DC_MISS
MMCR1_PMC3_DTLB_MISS
MMCR1_PMC3_L2_D_MISS
MMCR1_PMC3_Bx_TAKEN
MMCR1_PMC3_PM_SWITCH
MMCR1_PMC3_COND_STORE
MMCR1_PMC3_FPU
MMCR1_PMC3_L2_SNOOP_CASTOUT
MMCR1_PMC3_L2_HIT
MMCR1_PMC3_L1_MISS_CYCLE
MMCR1_PMC3_Bx_SECOND
MMCR1_PMC3_BPU_LR_CR
MMCR1_PMC4_HOLD
MMCR1_PMC4_CYCLE
MMCR1_PMC4_INSTRUCTION
MMCR1_PMC4_TRANSITION
MMCR1_PMC4_DISPATCHED
MMCR1_PMC4_L2_CASTOUT
MMCR1_PMC4_DTLB_CYCLE
MMCR1_PMC4_Bx_MISSED
MMCR1_PMC4_COND_STORE_INT
MMCR1_PMC4_SYNC
MMCR1_PMC4_SNOOP_RETRY
MMCR1_PMC4_INTEGER
MMCR1_PMC4_BPU_THIRD
MMCR1_PMC4_DC_MISS
FPSCR_FX
FPSCR_FEX
FPSCR_VX
FPSCR_OX
FPSCR_UX
FPSCR_ZX
FPSCR_XX
FPSCR_VXSNAN
FPSCR_VXISI
FPSCR_VXIDI
FPSCR_VXZDZ
FPSCR_VXIMZ
FPSCR_VXVC
FPSCR_FR
FPSCR_FI
FPSCR_VXSOFT
FPSCR_VXSQRT
FPSCR_VXCVI
FPSCR_VE
FPSCR_OE
FPSCR_UE
FPSCR_ZE
FPSCR_XE
FPSCR_NI
FPSCR_FX_BIT
FPSCR_FEX_BIT
FPSCR_VX_BIT
FPSCR_OX_BIT
FPSCR_UX_BIT
FPSCR_ZX_BIT
FPSCR_XX_BIT
FPSCR_VXSNAN_BIT
FPSCR_VXISI_BIT
FPSCR_VXIDI_BIT
FPSCR_VXZDZ_BIT
FPSCR_VXIMZ_BIT
FPSCR_VXVC_BIT
FPSCR_FR_BIT
FPSCR_FI_BIT
FPSCR_VXSOFT_BIT
FPSCR_VXSQRT_BIT
FPSCR_VXCVI_BIT
FPSCR_VE_BIT
FPSCR_OE_BIT
FPSCR_UE_BIT
FPSCR_ZE_BIT
FPSCR_XE_BIT
FPSCR_NI_BIT
u32 PPCMfmsr()
References blr, r3.
Referenced by __OSThreadInit, L2Init.
void PPCMtmsr(u32 newMSR)
Referenced by L2Init.
u32 PPCOrMsr(u32 value)
u32 PPCMfhid0()
References blr, HID0, r3.
Referenced by __OSCacheInit.
void PPCMthid0(u32 newHID0)
u32 PPCMfl2cr()
References blr, L2CR, r3.
Referenced by __OSCacheInit, L2Disable, L2Enable, L2GlobalInvalidate, L2SetDataOnly, L2SetWriteThrough.
void PPCMtl2cr(u32 newL2cr)
Referenced by L2Disable, L2Enable, L2GlobalInvalidate, L2SetDataOnly, L2SetWriteThrough.
void PPCMtdec(u32 newDec)
Referenced by DecrementerExceptionCallback, OSStartTimer, SetTimer.
void PPCSync()
References blr.
Referenced by GXFlush, LCFlushQueue.
void PPCHalt()
References r3, sync.
Referenced by __DBExceptionDestinationAux, __OSUnhandledException, _ExitProcess, DMAErrorHandler, OSPanic.
u32 PPCMffpscr()
void PPCMtfpscr(u32 newFPSCR)
u32 PPCMfhid2()
References blr, HID2, r3.
Referenced by __OSPSInit, DisableWriteGatherPipe, DMAErrorHandler, EnableWriteGatherPipe, LCAlloc, LCAllocNoInvalidate.
void PPCMthid2(u32 newhid2)
Referenced by __OSPSInit, DisableWriteGatherPipe, DMAErrorHandler, EnableWriteGatherPipe.
u32 PPCMfwpar()
References blr, r3, sync, WPAR.
Referenced by GXRedirectWriteGatherPipe, GXResetWriteGatherPipe.
void PPCMtwpar(u32 newwpar)
Referenced by EnableWriteGatherPipe, GXRedirectWriteGatherPipe, GXResetWriteGatherPipe.
void PPCEnableSpeculation()
void PPCDisableSpeculation()
void PPCSetFpIEEEMode()
void PPCSetFpNonIEEEMode()
u32 PPCMfpmc4()
References blr, PMC4, r3.
Referenced by PERFEndAutoSample, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartAutoSample, PERFStopAutoSampling, PERFTimerCallback, PERFTokenCallback, PMInstructions.
u32 PPCMfpmc3()
References blr, PMC3, r3.
Referenced by PERFEndAutoSample, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartAutoSample, PERFTimerCallback, PERFTokenCallback, PML1MissCycles.
u32 PPCMfpmc1()
References blr, PMC1, r3.
Referenced by PERFEndAutoSample, PERFEventEnd, PERFEventStart, PERFStartAutoSample, PERFTimerCallback, PERFTokenCallback, PMCycles.
void PPCMtpmc1(u32 newPmc1)
Referenced by PERFStartFrame, PMBegin.
void PPCMtpmc2(u32 newPmc1)
Referenced by PERFStartFrame, PMBegin.
void PPCMtpmc3(u32 newPmc1)
Referenced by PERFStartFrame, PMBegin.
void PPCMtpmc4(u32 newPmc1)
Referenced by PERFStartFrame, PMBegin.
void PPCMtmmcr0(u32 newMmcr0)
Referenced by PERFStartFrame, PMBegin, PMEnd.
void PPCMtmmcr1(u32 newMmcr0)
Referenced by PERFStartFrame, PMBegin, PMEnd.
void PPCMtdmaU(u32 newdmau)
Referenced by LCFlushQueue.
void PPCMtdmaL(u32 newdmal)
Referenced by LCFlushQueue.
u32 PPCMfdec(void)
References blr, r3.
Referenced by OSStopTimer.
u32 PPCAndMsr(u32 value)
u32 PPCAndCMsr(u32 value)
u32 PPCMfhid1()
References blr, HID1, r3.
void PPCEieio()
References blr, HID0, isync, r3, r4, r5.
u32 PPCMfmmcr0()
References blr, MMCR0, r3.
u32 PPCMfmmcr1()
References blr, MMCR1, r3.
u32 PPCMfpmc2()
References blr, PMC2, r3.
Referenced by PML1FetchMisses.
u32 PPCMfsia()
References blr, r3, SIA.
void PPCMtsia(u32 newSia)
u32 PPCMfdmaL()
References blr, DMA_L, r3.
u32 PPCMfpvr()
References blr, PVR, r3.
u32 PPCMfdmaU()
References blr, DMA_U, r3.
void PMBegin(void)
References PPCMtmmcr0, PPCMtmmcr1, PPCMtpmc1, PPCMtpmc2, PPCMtpmc3, PPCMtpmc4.
void PMEnd(void)
References PPCMtmmcr0, PPCMtmmcr1.
void PMCycles(void)
References PPCMfpmc1.
void PML1FetchMisses(void)
References PPCMfpmc2.
void PML1MissCycles(void)
References PPCMfpmc3.
void PMInstructions(void)
References PPCMfpmc4.