PPCArch.c
asm u32 PPCMfmsr()
References blr, r3.
Referenced by __OSThreadInit, L2Init.
asm void PPCMtmsr(register u32 newMSR)
References blr.
asm u32 PPCOrMsr(register u32 value)
References blr, r4.
asm u32 PPCAndMsr(register u32 value)
References blr, r4.
asm u32 PPCAndCMsr(register u32 value)
References blr, r4.
asm u32 PPCMfhid0()
References blr, HID0, r3.
Referenced by __OSCacheInit.
asm void PPCMthid0(register u32 newHID0)
References blr, HID0.
asm u32 PPCMfhid1()
References blr, HID1, r3.
asm u32 PPCMfl2cr()
References blr, L2CR, r3.
Referenced by __OSCacheInit, L2Disable, L2Enable, L2GlobalInvalidate, L2SetDataOnly, L2SetWriteThrough.
asm void PPCMtl2cr(register u32 newL2cr)
References blr, L2CR.
asm void PPCMtdec(register u32 newDec)
References blr.
asm u32 PPCMfdec()
References blr, r3.
Referenced by OSStopTimer.
asm void PPCSync()
References blr.
Referenced by GXFlush, LCFlushQueue.
asm void PPCEieio()
References blr, HID0, isync, r3, r4, r5.
asm void PPCHalt()
References r3, sync.
Referenced by __DBExceptionDestinationAux, __OSUnhandledException, _ExitProcess, DMAErrorHandler, OSPanic.
asm u32 PPCMfmmcr0()
References blr, MMCR0, r3.
asm void PPCMtmmcr0(register u32 newMmcr0)
References blr, MMCR0.
asm u32 PPCMfmmcr1()
References blr, MMCR1, r3.
asm void PPCMtmmcr1(register u32 newMmcr1)
References blr, MMCR1.
asm u32 PPCMfpmc1()
References blr, PMC1, r3.
Referenced by PERFEndAutoSample, PERFEventEnd, PERFEventStart, PERFStartAutoSample, PERFTimerCallback, PERFTokenCallback, PMCycles.
asm void PPCMtpmc1(register u32 newPmc1)
References blr, PMC1.
asm u32 PPCMfpmc2()
References blr, PMC2, r3.
Referenced by PML1FetchMisses.
asm void PPCMtpmc2(register u32 newPmc2)
References blr, PMC2.
asm u32 PPCMfpmc3()
References blr, PMC3, r3.
Referenced by PERFEndAutoSample, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartAutoSample, PERFTimerCallback, PERFTokenCallback, PML1MissCycles.
asm void PPCMtpmc3(register u32 newPmc3)
References blr, PMC3.
asm u32 PPCMfpmc4()
References blr, PMC4, r3.
Referenced by PERFEndAutoSample, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartAutoSample, PERFStopAutoSampling, PERFTimerCallback, PERFTokenCallback, PMInstructions.
asm void PPCMtpmc4(register u32 newPmc4)
References blr, PMC4.
asm u32 PPCMfsia()
References blr, r3, SIA.
asm void PPCMtsia(register u32 newSia)
References blr, SIA.
asm u32 PPCMfhid2()
References blr, HID2, r3.
Referenced by __OSPSInit, DisableWriteGatherPipe, DMAErrorHandler, EnableWriteGatherPipe, LCAlloc, LCAllocNoInvalidate.
asm void PPCMthid2(register u32 newhid2)
References blr, HID2.
asm u32 PPCMfwpar()
References blr, r3, sync, WPAR.
Referenced by GXRedirectWriteGatherPipe, GXResetWriteGatherPipe.
asm void PPCMtwpar(register u32 newwpar)
References blr, WPAR.
asm u32 PPCMfdmaU()
References blr, DMA_U, r3.
asm u32 PPCMfdmaL()
References blr, DMA_L, r3.
asm void PPCMtdmaU(register u32 newdmau)
References blr, DMA_U.
asm void PPCMtdmaL(register u32 newdmal)
References blr, DMA_L.
asm u32 PPCMfpvr()
References blr, PVR, r3.