Pad.c
typedef struct XY XY
OSResetFunctionInfo ResetFunctionInfo
Referenced by PADInit.
u32 __PADFixBits
Referenced by PADInit, PADResetCallback.
u32 __PADSpec
Referenced by OSInit, PADInit, PADSetSpec.
XY XYNTSC[12][12]
Referenced by PADSetSamplingRate.
XY XYPAL[12][12]
Referenced by PADSetSamplingRate.
static u16 GetWirelessID(s32 chan)
References __OSLockSramEx, __OSUnlockSramEx, OSSramEx::wirelessPadID.
Referenced by PADFixCallback, PADResetCallback.
static void SetWirelessID(s32 chan, u16 id)
References __OSLockSramEx, __OSUnlockSramEx, OSSramEx::wirelessPadID.
Referenced by PADDisable, PADResetCallback.
static int DoReset()
References CARD_MAX_MOUNT_STEP, cmdTypeAndStatus, Origin, PADResetCallback, PADType, ResettingBits, ResettingChan, SITransfer, Type.
Referenced by PADFixCallback, PADOriginCallback, PADProbeCallback, PADRecalibrate, PADReset, PADResetCallback.
static void PADEnable(s32 chan)
References AnalogMode, CARD_MAX_MOUNT_STEP, EnabledBits, RES_WIRELESS_LITE, SIEnablePolling, SIGetResponse, SISetCommand, Type.
Referenced by PADOriginCallback, PADProbeCallback, PADResetCallback.
static void ProbeWireless(s32 chan)
References __OSWirelessPadFixMode, CARD_MAX_MOUNT_STEP, EnabledBits, ProbingBits, SIEnablePolling, SIGetResponse, SISetCommand, Type.
Referenced by PADProbeCallback, PADResetCallback.
static void PADProbeCallback(s32 chan, u32 error, OSContext *context)
References CARD_MAX_MOUNT_STEP, DoReset, PAD_CHAN0_BIT, PADEnable, ProbeWireless, ResettingChan, SI_ERROR_COLLISION, SI_ERROR_NO_RESPONSE, SI_ERROR_OVER_RUN, SI_ERROR_UNDER_RUN, SI_MAX_CHAN, Type, WaitingBits.
Referenced by PADFixCallback, PADResetCallback.
static void PADDisable(s32 chan)
References CARD_MAX_MOUNT_STEP, CheckingBits, EnabledBits, OSDisableInterrupts, OSRestoreInterrupts, ProbingBits, SetWirelessID, SIDisablePolling, WaitingBits.
Referenced by PADRead, PADReceiveCheckCallback.
static void UpdateOrigin(s32 chan)
References AnalogMode, CARD_MAX_MOUNT_STEP, Origin, PADStatus::triggerLeft, Type, XPatchBits.
Referenced by PADOriginCallback, PADOriginUpdateCallback.
static void PADOriginCallback(s32 chan, u32 error, OSContext *context)
References CARD_MAX_MOUNT_STEP, DoReset, PADEnable, ResettingChan, SI_ERROR_COLLISION, SI_ERROR_NO_RESPONSE, SI_ERROR_OVER_RUN, SI_ERROR_UNDER_RUN, SI_MAX_CHAN, UpdateOrigin.
Referenced by PADFixCallback, PADResetCallback.
static void PADOriginUpdateCallback(s32 chan, u32 error, OSContext *context)
References CARD_MAX_MOUNT_STEP, EnabledBits, PAD_CHAN0_BIT, SI_ERROR_COLLISION, SI_ERROR_NO_RESPONSE, SI_ERROR_OVER_RUN, SI_ERROR_UNDER_RUN, SI_MAX_CHAN, UpdateOrigin.
Referenced by PADRead, PADReceiveCheckCallback.
static void PADFixCallback(s32 chan, u32 error, OSContext *context)
References CARD_MAX_MOUNT_STEP, cmdProbeDevice, cmdReadOrigin, DoReset, GetWirelessID, Origin, PADOriginCallback, PADProbeCallback, ResettingChan, SI_MAX_CHAN, SITransfer, Type.
Referenced by PADResetCallback.
static void PADResetCallback(s32 chan, u32 error, OSContext *context)
References __PADFixBits, CARD_MAX_MOUNT_STEP, cmdCalibrate, cmdFixDevice, cmdProbeDevice, cmdReadOrigin, DoReset, GetWirelessID, Origin, PADEnable, PADFixCallback, PADOriginCallback, PADProbeCallback, PADType, ProbeWireless, RecalibrateBits, ResettingChan, SetWirelessID, SI_MAX_CHAN, SITransfer, Spec, Type.
Referenced by DoReset.
int PADReset(u32 mask)
References CARD_MAX_MOUNT_STEP, CheckingBits, DoReset, EnabledBits, OSDisableInterrupts, OSRestoreInterrupts, ProbingBits, RecalibrateBits, ResettingBits, ResettingChan, SIDisablePolling, Spec, WaitingBits.
Referenced by DEMOPadRead, PADInit.
BOOL PADRecalibrate(u32 mask)
References CARD_MAX_MOUNT_STEP, CheckingBits, DoReset, EnabledBits, FALSE, OSDisableInterrupts, OSRestoreInterrupts, ProbingBits, RecalibrateBits, ResettingBits, ResettingChan, SIDisablePolling, WaitingBits.
Referenced by OnReset.
BOOL PADInit()
References __OSWirelessPadFixMode, __PADFixBits, __PADSpec, cmdProbeDevice, Initialized, OSGetTime, OSRegisterResetFunction, PAD_CHAN0_BIT, PAD_CHAN1_BIT, PAD_CHAN2_BIT, PAD_CHAN3_BIT, PADReset, PADSetSamplingRate, PADSetSpec, ResetFunctionInfo, SI_MAX_CHAN, TRUE.
Referenced by DEMOPadInit.
static void PADReceiveCheckCallback(s32 chan, u32 error, OSContext *context)
References CARD_MAX_MOUNT_STEP, CheckingBits, cmdReadOrigin, EnabledBits, Origin, PADDisable, PADOriginUpdateCallback, SITransfer, Type, WaitingBits.
Referenced by PADRead.
u32 PADRead(struct PADStatus *status)
References CARD_MAX_MOUNT_STEP, CheckingBits, cmdReadOrigin, cmdTypeAndStatus, EnabledBits, MakeStatus, Origin, OSDisableInterrupts, OSRestoreInterrupts, PADDisable, PADOriginUpdateCallback, PADReceiveCheckCallback, ProbingBits, ResettingBits, ResettingChan, SI_MAX_CHAN, SIGetResponse, SIGetStatus, SITransfer, status, Type, WaitingBits.
Referenced by DEMOPadRead, DEMOWinPadRead.
void PADSetSamplingRate(u32 msec)
References CARD_MAX_MOUNT_STEP, EnabledBits, OSPanic, SIEnablePolling, SISetXY, VI_MPAL, VI_NTSC, VI_PAL, VIGetTvFormat, XYNTSC, XYPAL.
Referenced by PADInit.
void PADControlAllMotors(const u32 *commandArray)
References AnalogMode, CARD_MAX_MOUNT_STEP, EnabledBits, FALSE, OSDisableInterrupts, OSRestoreInterrupts, PAD_CHAN0_BIT, PAD_MOTOR_STOP, PAD_MOTOR_STOP_HARD, PAD_SPEC_2, ProbingBits, SI_MAX_CHAN, SISetCommand, SITransferCommands, Spec, TRUE, Type.
void PADControlMotor(s32 chan, u32 command)
References AnalogMode, CARD_MAX_MOUNT_STEP, EnabledBits, OSDisableInterrupts, OSRestoreInterrupts, PAD_CHAN0_BIT, PAD_MOTOR_STOP, PAD_MOTOR_STOP_HARD, PAD_SPEC_2, ProbingBits, SISetCommand, SITransferCommands, Spec, Type.
void PADSetSpec(u32 spec)
References __PADSpec, CARD_MAX_MOUNT_STEP, Initialized, MakeStatus, PAD_SPEC_0, PAD_SPEC_1, PAD_SPEC_2, PAD_SPEC_3, PAD_SPEC_4, PAD_SPEC_5, Spec, SPEC0_MakeStatus, SPEC1_MakeStatus, SPEC2_MakeStatus.
Referenced by PADInit.
u32 PADGetSpec(void)
References Spec.
static void SPEC0_MakeStatus(s32 chan, PADStatus *status, u32 data[2])
References PAD_BUTTON_A, PAD_BUTTON_B, PAD_BUTTON_START, PAD_BUTTON_X, PAD_BUTTON_Y, PAD_TRIGGER_L, PAD_TRIGGER_R, status.
Referenced by PADSetSpec.
static void SPEC1_MakeStatus(s32 chan, PADStatus *status, u32 data[2])
References PAD_BUTTON_A, PAD_BUTTON_B, PAD_BUTTON_START, PAD_BUTTON_X, PAD_BUTTON_Y, PAD_TRIGGER_L, PAD_TRIGGER_R, status.
Referenced by PADSetSpec.
static s8 ClampS8(s8 var, s8 org)
References CARD_MAX_MOUNT_STEP.
Referenced by SPEC2_MakeStatus.
static u8 ClampU8(u8 var, u8 org)
References CARD_MAX_MOUNT_STEP.
Referenced by SPEC2_MakeStatus.
static void SPEC2_MakeStatus(s32 chan, PADStatus *status, u32 data[2])
References AnalogMode, PADStatus::button, CARD_MAX_MOUNT_STEP, ClampS8, ClampU8, Origin, PAD_ALL, status, PADStatus::stickX.
Referenced by PADSetSpec.
int PADGetType(s32 chan, u32 *type)
References CARD_MAX_MOUNT_STEP, EnabledBits, ResettingBits, ResettingChan, Type.
BOOL PADSync(void)
References ResettingBits, ResettingChan, SIBusy.
Referenced by OnReset.
void PADSetAnalogMode(u32 mode)
References AnalogMode, CARD_MAX_MOUNT_STEP, CheckingBits, EnabledBits, OSDisableInterrupts, OSRestoreInterrupts, SIDisablePolling, WaitingBits.
static BOOL OnReset(BOOL f)
References CARD_MAX_MOUNT_STEP, FALSE, PAD_CHAN0_BIT, PAD_CHAN1_BIT, PAD_CHAN2_BIT, PAD_CHAN3_BIT, PADRecalibrate, PADSync, sync, TRUE.