Padclamp.c
typedef struct PADClampRegion PADClampRegion
PADClampRegion ClampRegion
Referenced by ClampTrigger, PADClamp.
static void ClampStick(s8 *px, s8 *py, s8 max, s8 xy, s8 min)
References CARD_MAX_MOUNT_STEP.
Referenced by PADClamp.
static void ClampTrigger(u8 *trigger)
References ClampRegion, PADClampRegion::maxTrigger, PADClampRegion::minTrigger.
Referenced by PADClamp.
void PADClamp(PADStatus *status)
References CARD_MAX_MOUNT_STEP, ClampRegion, ClampStick, ClampTrigger, PADClampRegion::maxStick, PADClampRegion::maxSubstick, PADClampRegion::minStick, PADClampRegion::minSubstick, PAD_ERR_NONE, status, PADClampRegion::xyStick, PADClampRegion::xySubstick.
Referenced by DEMOPadRead.