SYNPrivate.h
struct SYNSYNTH* __SYNSynthList
Referenced by __SYNAddSynthToList, __SYNRemoveSynthFromList, SYNInit, SYNRunAudioFrame.
float __SYNn128[128][128]
Referenced by __SYNGetEnvelopeTime, __SYNRunLfo.
s32 __SYNVolumeAttenuation[128][128]
Referenced by __SYNSetController, __SYNSetupVolume.
s32 __SYNAttackAttnTable[100][100]
Referenced by __SYNRunVolumeEnvelope.
struct SYNVOICE __SYNVoice[64][64]
Referenced by __SYNClearVoiceReferences, __SYNNoteOn, __SYNServiceVoice, SYNInit, SYNQuitSynth.
void __SYNClearAllNotes(struct SYNSYNTH *synth)
References __SYNReleaseChannelNotes, CARD_MAX_MOUNT_STEP, SYNVOICE::synth.
void __SYNSetController(struct SYNSYNTH *synth, u8 midiChannel, u8 function, u8 value)
References __SYNReleaseChannelNotes, __SYNResetController, __SYNResetController0, __SYNSetData, __SYNSetSustainPedal, __SYNVolumeAttenuation, SYNSYNTH::auxAAttn, SYNSYNTH::auxBAttn, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNSYNTH::expAttn, SYNVOICE::midiChannel, SYNSYNTH::rpn, SYNVOICE::synth, SYNSYNTH::volAttn.
Referenced by __SYNMidiIn, __SYNResetController, __SYNResetController0.
void __SYNResetController0(struct SYNSYNTH *synth, u8 midiChannel)
References __SYNSetController, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::midiChannel, SYNVOICE::pan, SYNSYNTH::pwCents, SYNSYNTH::pwMaxCents, SYNVOICE::synth.
Referenced by __SYNSetController.
void __SYNResetController(struct SYNSYNTH *synth, u8 midiChannel)
References __SYNSetController, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::midiChannel, SYNSYNTH::pwCents, SYNSYNTH::pwMaxCents, SYNVOICE::synth.
Referenced by __SYNResetAllControllers, __SYNSetController.
void __SYNResetAllControllers(struct SYNSYNTH *synth)
References __SYNProgramChange, __SYNResetController, CARD_MAX_MOUNT_STEP, SYNVOICE::midiChannel, SYNVOICE::synth.
Referenced by SYNInitSynth.
void __SYNRunInputBufferEvents(struct SYNSYNTH *synth)
References __SYNMidiIn, SYNSYNTH::input, SYNSYNTH::inputCounter, SYNSYNTH::inputPosition, SYNVOICE::synth.
Referenced by SYNRunAudioFrame.
s32 __SYNGetEnvelopeTime(s32 scale, s32 mod, u8 key)
References __SYNn128, CARD_MAX_MOUNT_STEP.
Referenced by __SYNSetupPitchEnvelope, __SYNSetupVolumeEnvelope.
void __SYNSetupVolumeEnvelope(struct SYNVOICE *voice)
References __SYNGetEnvelopeTime, SYNVOICE::art, CARD_MAX_MOUNT_STEP, WTART::eg1Attack, WTART::eg1Decay, WTART::eg1Key2Decay, WTART::eg1Release, WTART::eg1Sustain, WTART::eg1Vel2Attack, SYNVOICE::keyNum, SYNVOICE::keyVel, SYNVOICE::veAttack, SYNVOICE::veAttackDelta, SYNVOICE::veAttn, SYNVOICE::veDecay, SYNVOICE::veRelease, SYNVOICE::veState, SYNVOICE::veSustain.
Referenced by __SYNNoteOn.
void __SYNSetupPitchEnvelope(struct SYNVOICE *voice)
References __SYNGetEnvelopeTime, SYNVOICE::art, CARD_MAX_MOUNT_STEP, WTART::eg2Attack, WTART::eg2Decay, WTART::eg2Key2Decay, WTART::eg2Pitch, WTART::eg2Release, WTART::eg2Sustain, WTART::eg2Vel2Attack, SYNVOICE::keyNum, SYNVOICE::keyVel, SYNVOICE::peAttack, SYNVOICE::peCents, SYNVOICE::peDecay, SYNVOICE::pePitch, SYNVOICE::peRelease, SYNVOICE::peState, SYNVOICE::peSustain.
Referenced by __SYNNoteOn.
void __SYNRunVolumeEnvelope(struct SYNVOICE *voice)
References __SYNAttackAttnTable, CARD_MAX_MOUNT_STEP, SYNVOICE::keyNum, SYNVOICE::midiChannel, SYNVOICE::synth, SYNVOICE::veAttack, SYNVOICE::veAttackDelta, SYNVOICE::veAttn, SYNVOICE::veDecay, SYNVOICE::veRelease, SYNVOICE::veState, SYNVOICE::veSustain, SYNSYNTH::voice.
Referenced by __SYNServiceVoice.
void __SYNRunPitchEnvelope(struct SYNVOICE *voice)
References CARD_MAX_MOUNT_STEP, SYNVOICE::peAttack, SYNVOICE::peCents, SYNVOICE::peDecay, SYNVOICE::pePitch, SYNVOICE::peRelease, SYNVOICE::peState, SYNVOICE::peSustain.
Referenced by __SYNServiceVoice.
void __SYNSetupLfo(struct SYNVOICE *voice)
References SYNVOICE::art, CARD_MAX_MOUNT_STEP, WTART::lfoAtten, SYNVOICE::lfoAttn, SYNVOICE::lfoAttn_, SYNVOICE::lfoCents, WTART::lfoDelay, SYNVOICE::lfoDelay, WTART::lfoFreq, SYNVOICE::lfoFreq, WTART::lfoMod2Atten, WTART::lfoMod2Pitch, SYNVOICE::lfoModAttn, SYNVOICE::lfoModCents, WTART::lfoPitch, SYNVOICE::lfoState.
Referenced by __SYNNoteOn.
void __SYNRunLfo(struct SYNVOICE *voice)
References __SYNLfo, __SYNn128, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::lfoAttn, SYNVOICE::lfoAttn_, SYNVOICE::lfoCents, SYNVOICE::lfoCents_, SYNVOICE::lfoDelay, SYNVOICE::lfoFreq, SYNVOICE::lfoModAttn, SYNVOICE::lfoModCents, SYNVOICE::lfoState, SYNVOICE::midiChannel, SYNVOICE::synth.
Referenced by __SYNServiceVoice.
void __SYNSetupVolume(struct SYNVOICE *voice)
References __SYNVolumeAttenuation, WTREGION::attn, SYNVOICE::attn, CARD_MAX_MOUNT_STEP, SYNVOICE::keyVel, SYNVOICE::region.
Referenced by __SYNNoteOn.
void __SYNSetupPan(struct SYNVOICE *voice)
References SYNVOICE::art, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::midiChannel, WTART::pan, SYNVOICE::pan, SYNVOICE::synth.
Referenced by __SYNNoteOn.
s32 __SYNGetVoiceInput(struct SYNVOICE *voice)
References SYNVOICE::attn, SYNVOICE::lfoAttn, SYNVOICE::veAttn.
Referenced by __SYNNoteOn, __SYNUpdateMix.
s32 __SYNGetVoiceFader(struct SYNVOICE *voice)
References SYNSYNTH::expAttn, SYNSYNTH::masterVolume, SYNVOICE::midiChannel, SYNVOICE::synth, SYNSYNTH::volAttn.
Referenced by __SYNNoteOn, __SYNUpdateMix.
void __SYNUpdateMix(struct SYNVOICE *voice)
References __SYNGetVoiceFader, __SYNGetVoiceInput, SYNSYNTH::auxAAttn, SYNSYNTH::auxBAttn, SYNVOICE::axvpb, SYNSYNTH::controller, SYNVOICE::midiChannel, MIXSetAuxA, MIXSetAuxB, MIXSetFader, MIXSetInput, MIXSetPan, SYNVOICE::synth.
Referenced by __SYNServiceVoice.
float __SYNGetRelativePitch(struct SYNVOICE *voice)
References __SYNCentsTable, __SYNOctavesTableUp, __SYNSemitonesTableDown, __SYNSemitonesTableUp, CARD_MAX_MOUNT_STEP, SYNVOICE::cents, SYNVOICE::lfoCents, SYNVOICE::midiChannel, SYNVOICE::peCents, SYNSYNTH::pwCents, SYNVOICE::synth.
Referenced by __SYNSetupSrc, __SYNUpdateSrc.
void __SYNSetupPitch(struct SYNVOICE *voice)
References SYNVOICE::cents, WTREGION::fineTune, SYNVOICE::keyNum, SYNVOICE::region, SYNVOICE::sample, WTSAMPLE::sampleRate, SYNVOICE::srcRatio, WTREGION::unityNote.
Referenced by __SYNNoteOn.
void __SYNSetupSrc(struct SYNVOICE *voice)
References __SYNGetRelativePitch, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, _AXVPB::pb, _AXPB::src, SYNVOICE::srcRatio, _AXPB::srcSelect, _AXVPB::sync.
Referenced by __SYNNoteOn.
void __SYNUpdateSrc(struct SYNVOICE *voice)
References __SYNGetRelativePitch, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPB::src, SYNVOICE::srcRatio, _AXVPB::sync.
Referenced by __SYNServiceVoice.
void __SYNSetupSample(struct SYNVOICE *voice)
References __SYNSetupAdpcm, __SYNSetupPcm16, __SYNSetupPcm8, CARD_MAX_MOUNT_STEP, FALSE, WTSAMPLE::format, SYNVOICE::sample, SYN_SAMPLE_FORMAT_ADPCM, SYN_SAMPLE_FORMAT_PCM16, SYN_SAMPLE_FORMAT_PCM8.
Referenced by __SYNNoteOn.
void __SYNClearVoiceReferences(void *p)
References __SYNVoice, AX_MAX_VOICES, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, _AXVPB::index, SYNSYNTH::keyGroup, SYNVOICE::keyGroup, SYNVOICE::keyNum, SYNVOICE::midiChannel, MIXReleaseChannel, SYNSYNTH::notes, SYNVOICE::synth, _AXVPB::userContext, SYNSYNTH::voice.
Referenced by __SYNNoteOn.
void __SYNSetVoiceToRelease(struct SYNVOICE *voice, u32 priority)
References AXSetVoicePriority, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, SYNVOICE::peState, SYNVOICE::veState.
Referenced by __SYNNoteOff, __SYNNoteOn, __SYNReleaseChannelNotes, __SYNSetSustainPedal.
void __SYNServiceVoice(int i)
References __SYNRunLfo, __SYNRunPitchEnvelope, __SYNRunVolumeEnvelope, __SYNUpdateMix, __SYNUpdateSrc, __SYNVoice, AXFreeVoice, CARD_MAX_MOUNT_STEP, SYNSYNTH::keyGroup, MIXReleaseChannel, SYNSYNTH::notes, NULL, SYNSYNTH::voice.
Referenced by SYNRunAudioFrame.
int __SYNGetWavetableData(struct SYNVOICE *voice)
References SYNSYNTH::adpcm, SYNSYNTH::art, CARD_MAX_MOUNT_STEP, SYNSYNTH::inst, WTINST::keyRegion, SYNSYNTH::region, SYNSYNTH::sample, SYNSYNTH::voice.
Referenced by __SYNNoteOn.