ai.h
AI_STREAM_START
AI_STREAM_STOP
AI_SAMPLERATE_32KHZ
AI_SAMPLERATE_48KHZ
typedef void(* AISCallback) (u32 count))(u32 count)
typedef void(* AIDCallback) ())()
AIDCallback AIRegisterDMACallback(AIDCallback callback)
References __AID_Callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __AXOutInit.
void AIInitDMA(u32 start_addr, u32 length)
References OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __AXOutInit, __AXOutNewFrame.
BOOL AIGetDMAEnableFlag(void)
void AIStartDMA(void)
Referenced by __AXOutInit.
void AIStopDMA(void)
Referenced by __AXOutQuit.
u32 AIGetDMABytesLeft(void)
u32 AIGetDMAStartAddr(void)
u32 AIGetDMALength(void)
BOOL AICheckInit(void)
References __AI_init_flag.
AISCallback AIRegisterStreamCallback(AISCallback callback)
References __AIS_Callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by DTKInit, DTKShutdown.
u32 AIGetStreamSampleCount(void)
void AIResetStreamSampleCount(void)
Referenced by __DTKStartAi, AIInit, DTKInit, DTKSetInterruptFrequency, DTKShutdown.
void AISetStreamTrigger(u32 trigger)
Referenced by __DTKCallbackForAIInterrupt, __DTKStartAi, AIInit, DTKSetInterruptFrequency.
u32 AIGetStreamTrigger(void)
void AISetStreamPlayState(u32 state)
References __AI_SRC_INIT, AI_STREAM_START, AIGetStreamPlayState, AIGetStreamSampleRate, AIGetStreamVolLeft, AIGetStreamVolRight, AISetStreamVolLeft, AISetStreamVolRight, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, __DTKCallbackForFlush, __DTKCallbackForNextTrack, __DTKCallbackForPrevTrack, __DTKStartAi, __DTKStopAi, DTKInit, DTKSetState, DTKShutdown.
u32 AIGetStreamPlayState(void)
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AISetDSPSampleRate(u32 rate)
References __AI_SRC_INIT, AI_SAMPLERATE_32KHZ, AIGetDSPSampleRate, AIGetStreamPlayState, AIGetStreamSampleRate, AIGetStreamVolLeft, AIGetStreamVolRight, AISetStreamVolLeft, AISetStreamVolRight, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by AIInit.
u32 AIGetDSPSampleRate(void)
References GET_REG_FIELD.
Referenced by AISetDSPSampleRate.
void AISetStreamSampleRate(u32 rate)
References __AI_set_stream_sample_rate, AI_SAMPLERATE_48KHZ, OSReport.
u32 AIGetStreamSampleRate(void)
References GET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AISetStreamVolLeft(u8 vol)
References SET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, __DTKStartAi, __DTKStopAi, AIInit, AISetDSPSampleRate, AISetStreamPlayState, DTKInit, DTKNextTrack, DTKPrevTrack, DTKSetState, DTKSetVolume, DTKShutdown, MIXUpdateSettings.
u8 AIGetStreamVolLeft(void)
References GET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AISetStreamVolRight(u8 vol)
References SET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, __DTKStartAi, __DTKStopAi, AIInit, AISetDSPSampleRate, AISetStreamPlayState, DTKInit, DTKNextTrack, DTKPrevTrack, DTKSetState, DTKSetVolume, DTKShutdown, MIXUpdateSettings.
u8 AIGetStreamVolRight(void)
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AIInit(u8 *stack)
References __AI_init_flag, __AI_set_stream_sample_rate, __AID_Callback, __AIDHandler, __AIS_Callback, __AISHandler, __CallbackStack, __OSSetInterruptHandler, __OSUnmaskInterrupts, AI_SAMPLERATE_32KHZ, AI_SAMPLERATE_48KHZ, AIResetStreamSampleCount, AISetDSPSampleRate, AISetStreamTrigger, AISetStreamVolLeft, AISetStreamVolRight, bound_32KHz, bound_48KHz, buffer, max_wait, min_wait, NULL, OSNanosecondsToTicks, OSReport, TRUE.
void AIReset(void)
References __AI_init_flag, FALSE.