ai.c
AISCallback __AIS_Callback
Referenced by __AISHandler, AIInit, AIRegisterStreamCallback.
AIDCallback __AID_Callback
Referenced by __AIDHandler, AIInit, AIRegisterDMACallback.
u8* __CallbackStack
Referenced by __AICallbackStackSwitch, __AIDHandler, AIInit.
u8* __OldStack
Referenced by __AICallbackStackSwitch.
BOOL __AI_init_flag
Referenced by AICheckInit, AIInit, AIReset.
OSTime bound_32KHz
Referenced by __AI_SRC_INIT, AIInit.
OSTime bound_48KHz
Referenced by __AI_SRC_INIT, AIInit.
OSTime min_wait
Referenced by __AI_SRC_INIT, AIInit.
OSTime max_wait
Referenced by __AI_SRC_INIT, AIInit.
OSTime buffer
Referenced by __AI_SRC_INIT, __ARChecksize, __AXNextFrame, __OSReadROM, __OSReadROMAsync, AIInit, DEMOWinLogPrintf, DOLLoadImage, fioPacketRead, fioPacketResultRead, fioPacketResultWrite, fioPacketWrite, HIORead, HIOReadAsync, HIOWrite, HIOWriteAsync, ReadSram, send7120Data, WriteSram.
struct STRUCT_TIMELOG profile
Referenced by __ai_src_get_time, __AI_SRC_INIT, __AXGetCurrentProfile, __AXOutNewFrame, AXInitProfile.
OSTime __ai_src_time_end
OSTime __ai_src_time_start
void __AI_DEBUG_set_stream_sample_rate(u32 rate)
References __AI_set_stream_sample_rate.
struct STRUCT_TIMELOG * __ai_src_get_time(void)
References NULL, profile.
static void __AI_set_stream_sample_rate(u32 rate)
References __AI_SRC_INIT, AIGetStreamPlayState, AIGetStreamSampleRate, AIGetStreamVolLeft, AIGetStreamVolRight, AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by __AI_DEBUG_set_stream_sample_rate, AIInit, AISetStreamSampleRate.
static void __AIDHandler(__OSInterrupt interrupt, OSContext *context)
References __AICallbackStackSwitch, __AID_Callback, __CallbackStack, OSClearContext, OSSetCurrentContext, tmp.
Referenced by AIInit.
static void __AISHandler(__OSInterrupt interrupt, OSContext *context)
References __AIS_Callback, OSClearContext, OSSetCurrentContext.
Referenced by AIInit.
static void __AICallbackStackSwitch(void *cb)
Referenced by __AIDHandler.
void __AI_SRC_INIT(void)
References AI_STREAM_START, AI_STREAM_STOP, bound_32KHz, bound_48KHz, buffer, max_wait, min_wait, OSGetTime, profile, SET_REG_FIELD, t1, STRUCT_TIMELOG::t_end, STRUCT_TIMELOG::t_start.
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
AIDCallback AIRegisterDMACallback(AIDCallback callback)
References __AID_Callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __AXOutInit.
void AIInitDMA(u32 start_addr, u32 length)
References OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __AXOutInit, __AXOutNewFrame.
BOOL AIGetDMAEnableFlag(void)
void AIStartDMA(void)
Referenced by __AXOutInit.
void AIStopDMA(void)
Referenced by __AXOutQuit.
u32 AIGetDMABytesLeft(void)
u32 AIGetDMAStartAddr(void)
u32 AIGetDMALength(void)
BOOL AICheckInit(void)
References __AI_init_flag.
AISCallback AIRegisterStreamCallback(AISCallback callback)
References __AIS_Callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by DTKInit, DTKShutdown.
u32 AIGetStreamSampleCount(void)
void AIResetStreamSampleCount(void)
Referenced by __DTKStartAi, AIInit, DTKInit, DTKSetInterruptFrequency, DTKShutdown.
void AISetStreamTrigger(u32 trigger)
Referenced by __DTKCallbackForAIInterrupt, __DTKStartAi, AIInit, DTKSetInterruptFrequency.
u32 AIGetStreamTrigger(void)
void AISetStreamPlayState(u32 state)
References __AI_SRC_INIT, AI_STREAM_START, AIGetStreamPlayState, AIGetStreamSampleRate, AIGetStreamVolLeft, AIGetStreamVolRight, AISetStreamVolLeft, AISetStreamVolRight, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, __DTKCallbackForFlush, __DTKCallbackForNextTrack, __DTKCallbackForPrevTrack, __DTKStartAi, __DTKStopAi, DTKInit, DTKSetState, DTKShutdown.
u32 AIGetStreamPlayState(void)
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AISetDSPSampleRate(u32 rate)
References __AI_SRC_INIT, AI_SAMPLERATE_32KHZ, AIGetDSPSampleRate, AIGetStreamPlayState, AIGetStreamSampleRate, AIGetStreamVolLeft, AIGetStreamVolRight, AISetStreamVolLeft, AISetStreamVolRight, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by AIInit.
u32 AIGetDSPSampleRate(void)
References GET_REG_FIELD.
Referenced by AISetDSPSampleRate.
void AISetStreamSampleRate(u32 rate)
References __AI_set_stream_sample_rate, AI_SAMPLERATE_48KHZ, OSReport.
u32 AIGetStreamSampleRate(void)
References GET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AISetStreamVolLeft(u8 vol)
References SET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, __DTKStartAi, __DTKStopAi, AIInit, AISetDSPSampleRate, AISetStreamPlayState, DTKInit, DTKNextTrack, DTKPrevTrack, DTKSetState, DTKSetVolume, DTKShutdown, MIXUpdateSettings.
u8 AIGetStreamVolLeft(void)
References GET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AISetStreamVolRight(u8 vol)
References SET_REG_FIELD.
Referenced by __AI_set_stream_sample_rate, __DTKStartAi, __DTKStopAi, AIInit, AISetDSPSampleRate, AISetStreamPlayState, DTKInit, DTKNextTrack, DTKPrevTrack, DTKSetState, DTKSetVolume, DTKShutdown, MIXUpdateSettings.
u8 AIGetStreamVolRight(void)
Referenced by __AI_set_stream_sample_rate, AISetDSPSampleRate, AISetStreamPlayState.
void AIInit(u8 *stack)
References __AI_init_flag, __AI_set_stream_sample_rate, __AID_Callback, __AIDHandler, __AIS_Callback, __AISHandler, __CallbackStack, __OSSetInterruptHandler, __OSUnmaskInterrupts, AI_SAMPLERATE_32KHZ, AI_SAMPLERATE_48KHZ, AIResetStreamSampleCount, AISetDSPSampleRate, AISetStreamTrigger, AISetStreamVolLeft, AISetStreamVolRight, bound_32KHz, bound_48KHz, buffer, max_wait, min_wait, NULL, OSNanosecondsToTicks, OSReport, TRUE.
void AIReset(void)
References __AI_init_flag, FALSE.
static asm void __AICallbackStackSwitch(register void *cb)
References __CallbackStack, __OldStack, blr, r3, r5.