ar.h
ARQ_DMA_ALIGNMENT
ARAM_DIR_MRAM_TO_ARAM
ARAM_DIR_ARAM_TO_MRAM
ARStartDMARead
ARStartDMAWrite
ARQ_TYPE_MRAM_TO_ARAM
ARQ_TYPE_ARAM_TO_MRAM
ARQ_PRIORITY_LOW
ARQ_PRIORITY_HIGH
typedef void(* ARQCallback) (u32 pointerToARQRequest))(u32 pointerToARQRequest)
typedef struct ARQRequest ARQRequest
ARQCallback ARRegisterDMACallback(ARQCallback callback)
References __AR_Callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by ARQInit.
u32 ARGetDMAStatus(void)
References OSDisableInterrupts, OSRestoreInterrupts.
void ARStartDMA(u32 type, u32 mainmem_addr, u32 aram_addr, u32 length)
References OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __ARQPopTaskQueueHi, __ARQServiceQueueLo.
u32 ARAlloc(u32 length)
References __AR_BlockLength, __AR_FreeBlocks, __AR_Size, __AR_StackPointer, OSDisableInterrupts, OSRestoreInterrupts, tmp.
u32 ARFree(u32 *length)
References __AR_BlockLength, __AR_FreeBlocks, __AR_StackPointer, OSDisableInterrupts, OSRestoreInterrupts.
int ARCheckInit(void)
References __AR_init_flag.
u32 ARInit(u32 *stack_index_addr, u32 num_entries)
References __AR_BlockLength, __AR_Callback, __AR_FreeBlocks, __AR_init_flag, __AR_StackPointer, __ARChecksize, __ARHandler, __OSSetInterruptHandler, __OSUnmaskInterrupts, ARGetSize, NULL, OS_BUS_CLOCK, OSDisableInterrupts, OSReport, OSRestoreInterrupts.
void ARReset(void)
References __AR_init_flag.
void ARSetSize(void)
References OSReport.
u32 ARGetBaseAddress(void)
u32 ARGetSize(void)
References __AR_Size.
Referenced by ARInit.
void ARQInit(void)
References __ARQ_init_flag, __ARQCallbackHi, __ARQCallbackLo, __ARQChunkSize, __ARQInterruptServiceRoutine, __ARQRequestPendingHi, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, ARRegisterDMACallback, NULL.
void ARQReset(void)
References __ARQ_init_flag.
void ARQPostRequest(struct ARQRequest *request, u32 owner, u32 type, u32 priority, u32 source, u32 dest, u32 length, ARQCallback callback)
References __ARQCallbackHack, __ARQPopTaskQueueHi, __ARQRequestPendingHi, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestTailHi, __ARQRequestTailLo, __ARQServiceQueueLo, ARQ_DMA_ALIGNMENT, ARQ_PRIORITY_HIGH, ARQ_PRIORITY_LOW, ARQ_TYPE_ARAM_TO_MRAM, ARQ_TYPE_MRAM_TO_ARAM, ARQRequest::callback, ARQRequest::dest, ARQRequest::length, ARQRequest::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, ARQRequest::owner, ARQRequest::source, ARQRequest::type.
void ARQRemoveRequest(struct ARQRequest *request)
References __ARQCallbackLo, __ARQInitTempQueue, __ARQPushTempQueue, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestQueueTemp, __ARQRequestTailHi, __ARQRequestTailLo, __ARQRequestTailTemp, ARQRequest::next, NULL, OSDisableInterrupts, OSRestoreInterrupts.
void ARQRemoveOwnerRequest(u32 owner)
References __ARQCallbackLo, __ARQInitTempQueue, __ARQPushTempQueue, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestQueueTemp, __ARQRequestTailHi, __ARQRequestTailLo, __ARQRequestTailTemp, ARQRequest::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, ARQRequest::owner.
void ARQFlushQueue(void)
References __ARQCallbackLo, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestTailHi, __ARQRequestTailLo, NULL, OSDisableInterrupts, OSRestoreInterrupts.
void ARQSetChunkSize(u32 size)
References __ARQChunkSize, size.
u32 ARQGetChunkSize(void)
References __ARQChunkSize.