ar.c
void(* __AR_Callback) ())()
Referenced by __ARHandler, ARInit, ARRegisterDMACallback.
u32 __AR_Size
Referenced by __ARChecksize, ARAlloc, ARGetSize.
u32 __AR_StackPointer
Referenced by ARAlloc, ARFree, ARInit.
u32 __AR_FreeBlocks
Referenced by ARAlloc, ARFree, ARInit.
u32* __AR_BlockLength
Referenced by ARAlloc, ARFree, ARInit.
int __AR_init_flag
Referenced by ARCheckInit, ARInit, ARReset.
static void __ARHandler(s16 exception, OSContext *context)
References __AR_Callback, OSClearContext, OSSetCurrentContext, tmp.
Referenced by ARInit.
static void __ARWaitForDMA(void)
Referenced by __ARReadDMA, __ARWriteDMA.
static void __ARWriteDMA(u32 mmem_addr, u32 aram_addr, u32 length)
References __ARWaitForDMA, DSP_AR_DMA_ARAM, DSP_AR_DMA_ARAM_U, DSP_AR_DMA_MM, DSP_AR_DMA_MM_U, DSP_AR_DMA_SIZE, DSP_AR_DMA_SIZE_U.
Referenced by __ARChecksize.
static void __ARReadDMA(u32 mmem_addr, u32 aram_addr, u32 length)
References __ARWaitForDMA, DSP_AR_DMA_ARAM, DSP_AR_DMA_ARAM_U, DSP_AR_DMA_MM, DSP_AR_DMA_MM_U, DSP_AR_DMA_SIZE, DSP_AR_DMA_SIZE_U.
Referenced by __ARChecksize.
static void __ARChecksize(void)
References __AR_Size, __ARReadDMA, __ARWriteDMA, buffer, DCFlushRange, DCInvalidateRange, OSPhysicalToUncached, OSReport, OSRoundUp32B.
Referenced by ARInit.
ARQCallback ARRegisterDMACallback(ARQCallback callback)
References __AR_Callback, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by ARQInit.
u32 ARGetDMAStatus(void)
References OSDisableInterrupts, OSRestoreInterrupts.
void ARStartDMA(u32 type, u32 mainmem_addr, u32 aram_addr, u32 length)
References OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __ARQPopTaskQueueHi, __ARQServiceQueueLo.
u32 ARAlloc(u32 length)
References __AR_BlockLength, __AR_FreeBlocks, __AR_Size, __AR_StackPointer, OSDisableInterrupts, OSRestoreInterrupts, tmp.
u32 ARFree(u32 *length)
References __AR_BlockLength, __AR_FreeBlocks, __AR_StackPointer, OSDisableInterrupts, OSRestoreInterrupts.
int ARCheckInit(void)
References __AR_init_flag.
u32 ARInit(u32 *stack_index_addr, u32 num_entries)
References __AR_BlockLength, __AR_Callback, __AR_FreeBlocks, __AR_init_flag, __AR_StackPointer, __ARChecksize, __ARHandler, __OSSetInterruptHandler, __OSUnmaskInterrupts, ARGetSize, NULL, OS_BUS_CLOCK, OSDisableInterrupts, OSReport, OSRestoreInterrupts.
void ARReset(void)
References __AR_init_flag.
void ARSetSize(void)
References OSReport.
u32 ARGetBaseAddress(void)
u32 ARGetSize(void)
References __AR_Size.
Referenced by ARInit.