ar_private.h
void __ARQPopTaskQueueHi(void)
References __ARQCallbackHi, __ARQRequestPendingHi, __ARQRequestQueueHi, ARStartDMA, ARQRequest::callback, ARQRequest::dest, ARQRequest::length, ARQRequest::next, ARQRequest::source, ARQRequest::type.
Referenced by __ARQInterruptServiceRoutine, ARQPostRequest.
void __ARQServiceQueueLo(void)
References __ARQCallbackLo, __ARQChunkSize, __ARQRequestPendingLo, __ARQRequestQueueLo, ARStartDMA, ARQRequest::callback, ARQRequest::dest, ARQRequest::length, ARQRequest::next, ARQRequest::source, ARQRequest::type.
Referenced by __ARQInterruptServiceRoutine, ARQPostRequest.
void __ARQCallbackHack(u32 pointerToARQRequest)
Referenced by ARQPostRequest.
void __ARQInterruptServiceRoutine(void)
References __ARQCallbackHi, __ARQCallbackLo, __ARQPopTaskQueueHi, __ARQRequestPendingHi, __ARQRequestPendingLo, __ARQServiceQueueLo, NULL.
Referenced by ARQInit.
void __ARQInitTempQueue(void)
References __ARQRequestQueueTemp, __ARQRequestTailTemp, NULL.
Referenced by ARQRemoveOwnerRequest, ARQRemoveRequest.
void __ARQPushTempQueue(struct ARQRequest *task)
References __ARQRequestQueueTemp, __ARQRequestTailTemp, ARQRequest::next, task.
Referenced by ARQRemoveOwnerRequest, ARQRemoveRequest.