arq.c
ARQRequest* __ARQRequestQueueHi
Referenced by __ARQPopTaskQueueHi, ARQFlushQueue, ARQInit, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest.
ARQRequest* __ARQRequestTailHi
Referenced by ARQFlushQueue, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest.
ARQRequest* __ARQRequestQueueLo
Referenced by __ARQServiceQueueLo, ARQFlushQueue, ARQInit, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest.
ARQRequest* __ARQRequestTailLo
Referenced by ARQFlushQueue, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest.
ARQRequest* __ARQRequestQueueTemp
Referenced by __ARQInitTempQueue, __ARQPushTempQueue, ARQRemoveOwnerRequest, ARQRemoveRequest.
ARQRequest* __ARQRequestTailTemp
Referenced by __ARQInitTempQueue, __ARQPushTempQueue, ARQRemoveOwnerRequest, ARQRemoveRequest.
ARQRequest* __ARQRequestPendingHi
Referenced by __ARQInterruptServiceRoutine, __ARQPopTaskQueueHi, ARQInit, ARQPostRequest.
ARQRequest* __ARQRequestPendingLo
Referenced by __ARQInterruptServiceRoutine, __ARQServiceQueueLo, ARQFlushQueue, ARQInit, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest.
ARQCallback __ARQCallbackHi
Referenced by __ARQInterruptServiceRoutine, __ARQPopTaskQueueHi, ARQInit.
ARQCallback __ARQCallbackLo
Referenced by __ARQInterruptServiceRoutine, __ARQServiceQueueLo, ARQFlushQueue, ARQInit, ARQRemoveOwnerRequest, ARQRemoveRequest.
u32 __ARQChunkSize
Referenced by __ARQServiceQueueLo, ARQGetChunkSize, ARQInit, ARQSetChunkSize.
int __ARQ_init_flag
Referenced by ARQInit, ARQReset.
void __ARQPopTaskQueueHi(void)
References __ARQCallbackHi, __ARQRequestPendingHi, __ARQRequestQueueHi, ARStartDMA, ARQRequest::callback, ARQRequest::dest, ARQRequest::length, ARQRequest::next, ARQRequest::source, ARQRequest::type.
Referenced by __ARQInterruptServiceRoutine, ARQPostRequest.
void __ARQServiceQueueLo(void)
References __ARQCallbackLo, __ARQChunkSize, __ARQRequestPendingLo, __ARQRequestQueueLo, ARStartDMA, ARQRequest::callback, ARQRequest::dest, ARQRequest::length, ARQRequest::next, ARQRequest::source, ARQRequest::type.
Referenced by __ARQInterruptServiceRoutine, ARQPostRequest.
void __ARQCallbackHack(u32 unused)
Referenced by ARQPostRequest.
void __ARQInterruptServiceRoutine()
References __ARQCallbackHi, __ARQCallbackLo, __ARQPopTaskQueueHi, __ARQRequestPendingHi, __ARQRequestPendingLo, __ARQServiceQueueLo, NULL.
Referenced by ARQInit.
void __ARQInitTempQueue(void)
References __ARQRequestQueueTemp, __ARQRequestTailTemp, NULL.
Referenced by ARQRemoveOwnerRequest, ARQRemoveRequest.
void __ARQPushTempQueue(ARQRequest *task)
References __ARQRequestQueueTemp, __ARQRequestTailTemp, ARQRequest::next, task.
Referenced by ARQRemoveOwnerRequest, ARQRemoveRequest.
void ARQInit(void)
References __ARQ_init_flag, __ARQCallbackHi, __ARQCallbackLo, __ARQChunkSize, __ARQInterruptServiceRoutine, __ARQRequestPendingHi, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, ARRegisterDMACallback, NULL.
void ARQReset(void)
References __ARQ_init_flag.
void ARQPostRequest(ARQRequest *request, u32 owner, u32 type, u32 priority, u32 source, u32 dest, u32 length, ARQCallback callback)
References __ARQCallbackHack, __ARQPopTaskQueueHi, __ARQRequestPendingHi, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestTailHi, __ARQRequestTailLo, __ARQServiceQueueLo, ARQ_DMA_ALIGNMENT, ARQ_PRIORITY_HIGH, ARQ_PRIORITY_LOW, ARQ_TYPE_ARAM_TO_MRAM, ARQ_TYPE_MRAM_TO_ARAM, ARQRequest::callback, ARQRequest::dest, ARQRequest::length, ARQRequest::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, ARQRequest::owner, ARQRequest::source, ARQRequest::type.
void ARQRemoveRequest(ARQRequest *request)
References __ARQCallbackLo, __ARQInitTempQueue, __ARQPushTempQueue, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestQueueTemp, __ARQRequestTailHi, __ARQRequestTailLo, __ARQRequestTailTemp, ARQRequest::next, NULL, OSDisableInterrupts, OSRestoreInterrupts.
void ARQRemoveOwnerRequest(u32 owner)
References __ARQCallbackLo, __ARQInitTempQueue, __ARQPushTempQueue, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestQueueTemp, __ARQRequestTailHi, __ARQRequestTailLo, __ARQRequestTailTemp, ARQRequest::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, ARQRequest::owner.
void ARQFlushQueue(void)
References __ARQCallbackLo, __ARQRequestPendingLo, __ARQRequestQueueHi, __ARQRequestQueueLo, __ARQRequestTailHi, __ARQRequestTailLo, NULL, OSDisableInterrupts, OSRestoreInterrupts.
void ARQSetChunkSize(u32 size)
References __ARQChunkSize, size.
u32 ARQGetChunkSize(void)
References __ARQChunkSize.