ax.h
AX_DSP_SLAVE_LENGTH
AX_MAX_VOICES
AX_SRC_TYPE_NONE
AX_SRC_TYPE_LINEAR
AX_SRC_TYPE_4TAP_8K
AX_SRC_TYPE_4TAP_12K
AX_SRC_TYPE_4TAP_16K
AX_SYNC_FLAG_COPYALL
AX_SYNC_FLAG_UNK1
AX_SYNC_FLAG_UNK2
AX_SYNC_FLAG_UNK3
AX_SYNC_FLAG_UNK4
AX_SYNC_FLAG_UNK5
AX_SYNC_FLAG_UNK6
AX_SYNC_FLAG_UNK7
AX_SYNC_FLAG_UNK8
AX_SYNC_FLAG_UNK9
AX_SYNC_FLAG_UNK10
AX_SYNC_FLAG_COPYADPCMLOOP
AX_SYNC_FLAG_COPYRATIO
AX_SYNC_FLAG_COPYSRC
AX_SYNC_FLAG_COPYADPCM
AX_SYNC_FLAG_COPYCURADDR
AX_SYNC_FLAG_COPYENDADDR
AX_SYNC_FLAG_COPYLOOPADDR
AX_SYNC_FLAG_COPYLOOP
AX_SYNC_FLAG_COPYADDR
AX_SYNC_FLAG_COPYFIR
AX_SYNC_FLAG_SWAPVOL
AX_SYNC_FLAG_COPYVOL
AX_SYNC_FLAG_COPYDPOP
AX_SYNC_FLAG_COPYUPDATE
AX_SYNC_FLAG_COPYTSHIFT
AX_SYNC_FLAG_COPYITD
AX_SYNC_FLAG_COPYAXPBMIX
AX_SYNC_FLAG_COPYTYPE
AX_SYNC_FLAG_COPYSTATE
AX_SYNC_FLAG_COPYMXRCTRL
AX_SYNC_FLAG_COPYSELECT
AX_PRIORITY_STACKS
typedef struct _AXPBMIX AXPBMIX
typedef struct _AXPBITD AXPBITD
typedef struct _AXPBUPDATE AXPBUPDATE
typedef struct _AXPBDPOP AXPBDPOP
typedef struct _AXPBVE AXPBVE
typedef struct _AXPBFIR AXPBFIR
typedef struct _AXPBADDR AXPBADDR
typedef struct _AXPBADPCM AXPBADPCM
typedef struct _AXPBSRC AXPBSRC
typedef struct _AXPBADPCMLOOP AXPBADPCMLOOP
typedef struct _AXPB AXPB
typedef struct _AXVPB AXVPB
typedef struct _AXPBITDBUFFER AXPBITDBUFFER
typedef struct _AXPBU AXPBU
typedef struct _AXSPB AXSPB
typedef struct _AXPROFILE AXPROFILE
AXPROFILE __AXLocalProfile
Referenced by __AXOutNewFrame.
DSPTaskInfo task
Referenced by __ARQPushTempQueue, __AXOutAiCallback, __AXOutInitDSP, __CARDUnlock, __DSP_add_task, __DSP_boot_task, __DSP_insert_task, __DSP_remove_task, DoneCallback, DSPAddTask, DSPAssertTask, DSPCancelTask, InitCallback.
u16 ax_dram_image[8192][8192]
Referenced by __AXOutInitDSP.
u16 axDspSlaveLength
Referenced by __AXOutInitDSP.
u16 axDspSlave[AX_DSP_SLAVE_LENGTH][AX_DSP_SLAVE_LENGTH]
Referenced by __AXOutInitDSP.
void AXInit(void)
References __AXAllocInit, __AXAuxInit, __AXClInit, __AXOutInit, __AXSPBInit, __AXVPBInit, OSReport.
void AXQuit(void)
References __AXAllocQuit, __AXAuxQuit, __AXClQuit, __AXOutQuit, __AXSPBQuit, __AXVPBQuit, OSReport.
void AXFreeVoice(AXVPB *p)
References __AXPushFreeStack, __AXRemoveFromStack, __AXSetPBDefault, _AXVPB::depop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::state.
Referenced by __SYNNoteOn, __SYNServiceVoice, SYNQuitSynth.
AXVPB * AXAcquireVoice(u32 priority, void(*callback)(void *), u32 userContext)
References __AXPopFreeStack, __AXPopStackFromBottom, __AXPushStackHead, __AXSetPBDefault, AX_PRIORITY_STACKS, _AXVPB::callback, _AXVPB::depop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::state, _AXVPB::userContext.
Referenced by __SYNNoteOn.
void AXSetVoicePriority(AXVPB *p, u32 priority)
References __AXPushStackHead, __AXRemoveFromStack, AX_PRIORITY_STACKS, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __SYNNoteOn, __SYNSetVoiceToRelease.
void AXRegisterAuxACallback(void(*callback)(void *, void *), void *context)
References __AXCallbackAuxA, __AXContextAuxA.
void AXRegisterAuxBCallback(void(*callback)(void *, void *), void *context)
References __AXCallbackAuxB, __AXContextAuxB.
void AXSetMode(u32 mode)
References __AXClMode, __AXHRTFHistory.
u32 AXGetMode(void)
References __AXClMode.
void AXRegisterCallback(void(*callback)())
References __AXUserFrameCallback.
void AXInitProfile(AXPROFILE *profile, u32 maxProfiles)
References __AXCurrentProfile, __AXMaxProfiles, __AXProfile, __AXProfileInitialized, profile.
u32 AXGetProfile(void)
References __AXCurrentProfile, OSDisableInterrupts, OSRestoreInterrupts.
void AXSetVoiceSrcType(AXVPB *p, u32 type)
References AX_SRC_TYPE_4TAP_12K, AX_SRC_TYPE_4TAP_16K, AX_SRC_TYPE_4TAP_8K, AX_SRC_TYPE_LINEAR, AX_SRC_TYPE_NONE, AX_SYNC_FLAG_COPYSELECT, _AXPB::coefSelect, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::srcSelect, _AXVPB::sync.
void AXSetVoiceState(AXVPB *p, u16 state)
References AX_SYNC_FLAG_COPYSTATE, _AXVPB::depop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::state, _AXVPB::sync.
void AXSetVoiceType(AXVPB *p, u16 type)
References AX_SYNC_FLAG_COPYTYPE, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPB::type.
void AXSetVoiceMix(AXVPB *p, AXPBMIX *mix)
References __AXClMode, AX_SYNC_FLAG_COPYAXPBMIX, AX_SYNC_FLAG_COPYMXRCTRL, _AXPB::mix, _AXPB::mixerCtrl, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync, _AXPBMIX::vAuxAL, _AXPBMIX::vAuxAR, _AXPBMIX::vAuxAS, _AXPBMIX::vAuxBL, _AXPBMIX::vAuxBR, _AXPBMIX::vAuxBS, _AXPBMIX::vDeltaAuxAL, _AXPBMIX::vDeltaAuxAR, _AXPBMIX::vDeltaAuxAS, _AXPBMIX::vDeltaAuxBL, _AXPBMIX::vDeltaAuxBR, _AXPBMIX::vDeltaAuxBS, _AXPBMIX::vDeltaL, _AXPBMIX::vDeltaR, _AXPBMIX::vDeltaS, _AXPBMIX::vS.
void AXSetVoiceItdOn(AXVPB *p)
References AX_SYNC_FLAG_COPYITD, AX_SYNC_FLAG_COPYTSHIFT, _AXPBITD::flag, _AXPB::itd, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPBITD::shiftL, _AXPBITD::shiftR, _AXVPB::sync, _AXPBITD::targetShiftL, _AXPBITD::targetShiftR.
void AXSetVoiceItdTarget(AXVPB *p, u16 lShift, u16 rShift)
References AX_SYNC_FLAG_COPYTSHIFT, _AXPB::itd, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPBITD::targetShiftL, _AXPBITD::targetShiftR.
void AXSetVoiceUpdateIncrement(AXVPB *p)
References AX_SYNC_FLAG_COPYUPDATE, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::sync, _AXVPB::updateMS.
void AXSetVoiceUpdateWrite(AXVPB *p, u16 param, u16 data)
References AX_SYNC_FLAG_COPYUPDATE, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::sync, _AXVPB::updateCounter, _AXVPB::updateWrite.
void AXSetVoiceDpop(AXVPB *p, AXPBDPOP *dpop)
References AX_SYNC_FLAG_COPYDPOP, _AXPB::dpop, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetVoiceVe(AXVPB *p, AXPBVE *ve)
References AX_SYNC_FLAG_COPYVOL, _AXPBVE::currentDelta, _AXPBVE::currentVolume, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPB::ve.
void AXSetVoiceVeDelta(AXVPB *p, s16 delta)
References AX_SYNC_FLAG_SWAPVOL, _AXPBVE::currentDelta, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync, _AXPB::ve.
void AXSetVoiceFir(AXVPB *p, AXPBFIR *fir)
References AX_SYNC_FLAG_COPYFIR, _AXPBFIR::coefsHi, _AXPBFIR::coefsLo, _AXPB::fir, _AXPBFIR::numCoefs, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceAddr(AXVPB *p, AXPBADDR *addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYADDR, AX_SYNC_FLAG_COPYADPCM, AX_SYNC_FLAG_COPYCURADDR, AX_SYNC_FLAG_COPYENDADDR, AX_SYNC_FLAG_COPYLOOP, AX_SYNC_FLAG_COPYLOOPADDR, _AXPBADDR::currentAddressLo, _AXPBADDR::endAddressLo, _AXPBADDR::format, _AXPBADDR::loopAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetVoiceLoop(AXVPB *p, u16 loop)
References _AXPB::addr, AX_SYNC_FLAG_COPYLOOP, _AXPBADDR::loopFlag, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceLoopAddr(AXVPB *p, u32 addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYLOOPADDR, _AXPBADDR::loopAddressHi, _AXPBADDR::loopAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceEndAddr(AXVPB *p, u32 addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYENDADDR, _AXPBADDR::endAddressHi, _AXPBADDR::endAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceCurrentAddr(AXVPB *p, u32 addr)
References _AXPB::addr, AX_SYNC_FLAG_COPYCURADDR, _AXPBADDR::currentAddressHi, _AXPBADDR::currentAddressLo, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXVPB::sync.
void AXSetVoiceAdpcm(AXVPB *p, AXPBADPCM *adpcm)
References _AXPB::adpcm, AX_SYNC_FLAG_COPYADPCM, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetVoiceSrc(AXVPB *p, AXPBSRC *src_)
References AX_SYNC_FLAG_COPYRATIO, AX_SYNC_FLAG_COPYSRC, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPB::src, src, _AXVPB::sync.
void AXSetVoiceSrcRatio(AXVPB *p, float ratio)
References AX_SYNC_FLAG_COPYRATIO, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPBSRC::ratioLo, _AXPB::src, _AXVPB::sync.
void AXSetVoiceAdpcmLoop(AXVPB *p, AXPBADPCMLOOP *adpcmloop)
References _AXPB::adpcmLoop, AX_SYNC_FLAG_COPYADPCMLOOP, OSDisableInterrupts, OSRestoreInterrupts, _AXVPB::pb, src, _AXVPB::sync.
void AXSetMaxDspCycles(u32 cycles)
References __AXMaxDspCycles.
u32 AXGetMaxDspCycles(void)
References __AXMaxDspCycles.
u32 AXGetDspCycles(void)
References __AXRecDspCycles.