axfx.h
int AXFXChorusInit(struct AXFX_CHORUS *c)
References __OSCurrHeap, AXFXChorusSettings, AXFX_CHORUS_WORK::currentLast, AXFX_CHORUS_WORK::lastLeft, AXFX_CHORUS_WORK::lastRight, AXFX_CHORUS_WORK::lastSur, NULL, AXFX_CHORUS_WORK::oldLeft, AXFX_CHORUS_WORK::oldRight, AXFX_CHORUS_WORK::oldSur, OSAllocFromHeap, OSDisableInterrupts, OSRestoreInterrupts, AXFX_CHORUS_WORK::src, AXFX_CHORUS_SRCINFO::target, AXFX_CHORUS_SRCINFO::trigger, AXFX_CHORUS::work.
int AXFXChorusShutdown(struct AXFX_CHORUS *c)
References __OSCurrHeap, AXFX_CHORUS_WORK::lastLeft, OSDisableInterrupts, OSFreeToHeap, OSRestoreInterrupts, AXFX_CHORUS::work.
int AXFXChorusSettings(struct AXFX_CHORUS *c)
References AXFX_CHORUS::baseDelay, AXFX_CHORUS_WORK::currentLast, AXFX_CHORUS_WORK::currentPosHi, AXFX_CHORUS_WORK::currentPosLo, OSDisableInterrupts, OSRestoreInterrupts, AXFX_CHORUS::period, AXFX_CHORUS_WORK::pitchOffset, AXFX_CHORUS_WORK::pitchOffsetPeriod, AXFX_CHORUS_WORK::pitchOffsetPeriodCount, AXFX_CHORUS::variation, AXFX_CHORUS::work.
Referenced by AXFXChorusInit.
void AXFXChorusCallback(struct AXFX_BUFFERUPDATE *bufferUpdate, struct AXFX_CHORUS *chorus)
References AXFX_CHORUS_WORK::currentLast, AXFX_CHORUS_WORK::currentPosHi, AXFX_CHORUS_WORK::currentPosLo, AXFX_CHORUS_SRCINFO::dest, do_src1, do_src2, AXFX_CHORUS_WORK::lastLeft, AXFX_CHORUS_WORK::lastRight, AXFX_CHORUS_WORK::lastSur, AXFX_BUFFERUPDATE::left, AXFX_CHORUS_SRCINFO::old, AXFX_CHORUS_WORK::oldLeft, AXFX_CHORUS_WORK::oldRight, AXFX_CHORUS_WORK::oldSur, AXFX_CHORUS_SRCINFO::pitchHi, AXFX_CHORUS_SRCINFO::pitchLo, AXFX_CHORUS_WORK::pitchOffset, AXFX_CHORUS_WORK::pitchOffsetPeriod, AXFX_CHORUS_WORK::pitchOffsetPeriodCount, AXFX_CHORUS_SRCINFO::posHi, AXFX_CHORUS_SRCINFO::posLo, AXFX_BUFFERUPDATE::right, AXFX_CHORUS_SRCINFO::smpBase, AXFX_CHORUS_WORK::src, AXFX_BUFFERUPDATE::surround, AXFX_CHORUS::work.
void AXFXDelayCallback(struct AXFX_BUFFERUPDATE *bufferUpdate, struct AXFX_DELAY *delay)
References AXFX_DELAY::currentFeedback, AXFX_DELAY::currentOutput, AXFX_DELAY::currentPos, AXFX_DELAY::currentSize, AXFX_BUFFERUPDATE::left, AXFX_DELAY::left, AXFX_BUFFERUPDATE::right, AXFX_DELAY::right, AXFX_DELAY::sur, AXFX_BUFFERUPDATE::surround.
int AXFXDelaySettings(struct AXFX_DELAY *delay)
References __OSCurrHeap, AXFXDelayShutdown, AXFX_DELAY::currentFeedback, AXFX_DELAY::currentOutput, AXFX_DELAY::currentPos, AXFX_DELAY::currentSize, AXFX_DELAY::delay, AXFX_DELAY::feedback, AXFX_DELAY::left, NULL, OSAllocFromHeap, OSDisableInterrupts, OSRestoreInterrupts, AXFX_DELAY::output, AXFX_DELAY::right, AXFX_DELAY::sur.
Referenced by AXFXDelayInit.
int AXFXDelayInit(struct AXFX_DELAY *delay)
References AXFXDelaySettings, AXFX_DELAY::left, NULL, OSDisableInterrupts, OSRestoreInterrupts, AXFX_DELAY::right, AXFX_DELAY::sur.
int AXFXDelayShutdown(struct AXFX_DELAY *delay)
References __OSCurrHeap, AXFX_DELAY::left, OSDisableInterrupts, OSFreeToHeap, OSRestoreInterrupts, AXFX_DELAY::right, AXFX_DELAY::sur.
Referenced by AXFXDelaySettings.
void DoCrossTalk(s32 *l, long *r, float cross, float invcross)
int AXFXReverbHiInit(struct AXFX_REVERBHI *rev)
References AXFX_REVERBHI::coloration, AXFX_REVERBHI::crosstalk, AXFX_REVERBHI::damping, AXFX_REVERBHI::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBHI::preDelay, ReverbHICreate, AXFX_REVERBHI::rv, AXFX_REVERBHI::tempDisableFX, AXFX_REVERBHI::time.
int AXFXReverbHiShutdown(struct AXFX_REVERBHI *rev)
References OSDisableInterrupts, OSRestoreInterrupts, ReverbHIFree, AXFX_REVERBHI::rv.
int AXFXReverbHiSettings(struct AXFX_REVERBHI *rev)
References AXFX_REVERBHI::coloration, AXFX_REVERBHI::crosstalk, AXFX_REVERBHI::damping, AXFX_REVERBHI::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBHI::preDelay, ReverbHIModify, AXFX_REVERBHI::rv, AXFX_REVERBHI::tempDisableFX, AXFX_REVERBHI::time.
void AXFXReverbHiCallback(struct AXFX_BUFFERUPDATE *bufferUpdate, struct AXFX_REVERBHI *reverb)
References AXFX_BUFFERUPDATE::left, ReverbHICallback, AXFX_BUFFERUPDATE::right, AXFX_REVERBHI::rv, AXFX_BUFFERUPDATE::surround, AXFX_REVERBHI::tempDisableFX.
int AXFXReverbStdInit(struct AXFX_REVERBSTD *rev)
References AXFX_REVERBSTD::coloration, AXFX_REVERBSTD::damping, AXFX_REVERBSTD::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBSTD::preDelay, ReverbSTDCreate, AXFX_REVERBSTD::rv, AXFX_REVERBSTD::tempDisableFX, AXFX_REVERBSTD::time.
int AXFXReverbStdShutdown(struct AXFX_REVERBSTD *rev)
References OSDisableInterrupts, OSRestoreInterrupts, ReverbSTDFree, AXFX_REVERBSTD::rv.
int AXFXReverbStdSettings(struct AXFX_REVERBSTD *rev)
References AXFX_REVERBSTD::coloration, AXFX_REVERBSTD::damping, AXFX_REVERBSTD::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBSTD::preDelay, ReverbSTDModify, AXFX_REVERBSTD::rv, AXFX_REVERBSTD::tempDisableFX, AXFX_REVERBSTD::time.
void AXFXReverbStdCallback(struct AXFX_BUFFERUPDATE *bufferUpdate, struct AXFX_REVERBSTD *reverb)
References AXFX_BUFFERUPDATE::left, ReverbSTDCallback, AXFX_BUFFERUPDATE::right, AXFX_REVERBSTD::rv, AXFX_BUFFERUPDATE::surround, AXFX_REVERBSTD::tempDisableFX.