card.h
CARD_WORKAREA_SIZE
CARD_READ_SIZE
CARD_MAX_FILE
CARD_COMMENT_SIZE
CARD_XFER_CREATE
CARD_XFER_DELETE
CARD_XFER_MOUNT
CARD_XFER_FORMAT
CARD_XFER_SETSTATUS
CARD_XFER_RENAME
CARD_ENCODE_ANSI
CARD_ENCODE_SJIS
CARD_FILENAME_MAX
CARD_ICON_MAX
CARD_ICON_WIDTH
CARD_ICON_HEIGHT
CARD_BANNER_WIDTH
CARD_BANNER_HEIGHT
CARDGetBannerFormat
CARDGetIconAnim
CARDGetIconFormat
CARDGetIconSpeed
CARDSetIconFormat
CARDSetIconSpeed
CARD_STAT_ICON_NONE
CARD_STAT_ICON_C8
CARD_STAT_ICON_RGB5A3
CARD_STAT_ICON_MASK
CARD_STAT_BANNER_NONE
CARD_STAT_BANNER_C8
CARD_STAT_BANNER_RGB5A3
CARD_STAT_BANNER_MASK
CARD_STAT_ANIM_LOOP
CARD_STAT_ANIM_BOUNCE
CARD_STAT_ANIM_MASK
CARD_STAT_SPEED_END
CARD_STAT_SPEED_FAST
CARD_STAT_SPEED_MIDDLE
CARD_STAT_SPEED_SLOW
CARD_STAT_SPEED_MASK
CARD_ATTR_UNK0
CARD_ATTR_UNK1
CARD_ATTR_PUBLIC
CARD_ATTR_NO_COPY
CARD_ATTR_NO_MOVE
CARD_ATTR_GLOBAL
CARD_ATTR_COMPANY
CARDGetFileNo
CARD_RESULT_UNLOCKED
CARD_RESULT_READY
CARD_RESULT_BUSY
CARD_RESULT_WRONGDEVICE
CARD_RESULT_NOCARD
CARD_RESULT_NOFILE
CARD_RESULT_IOERROR
CARD_RESULT_BROKEN
CARD_RESULT_EXIST
CARD_RESULT_NOENT
CARD_RESULT_INSSPACE
CARD_RESULT_NOPERM
CARD_RESULT_LIMIT
CARD_RESULT_NAMETOOLONG
CARD_RESULT_ENCODING
CARD_RESULT_CANCELED
CARD_RESULT_FATAL_ERROR
typedef struct CARDFileInfo CARDFileInfo
typedef struct CARDStat CARDStat
typedef void(* CARDCallback) (s32 chan, s32 result))(s32 chan, s32 result)
void CARDInit(void)
References __CARDBlock, __CARDDiskID, __CARDSetDiskID, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, DSPInit, OSCreateAlarm, OSInitAlarm, OSInitThreadQueue, OSPhysicalToCached, OSRegisterResetFunction, ResetFunctionInfo, CARDControl::result.
s32 CARDCheck(s32 chan)
References CARD_MAX_MOUNT_STEP, CARDCheckEx.
s32 CARDCheckAsync(s32 chan, CARDCallback callback)
References CARD_MAX_MOUNT_STEP, CARDCheckExAsync.
s32 CARDCheckEx(s32 chan, s32 *xferBytes)
References __CARDSync, __CARDSyncCallback, CARD_MAX_MOUNT_STEP, CARDCheckExAsync.
Referenced by CARDCheck.
s32 CARDCheckExAsync(s32 chan, s32 *xferBytes, CARDCallback callback)
References __CARDCheckSum, __CARDGetControlBlock, __CARDPutControlBlock, __CARDUpdateDir, __CARDUpdateFatBlock, CARD_FAT_AVAIL, CARD_FAT_CHECKCODE, CARD_FAT_CHECKSUM, CARD_FAT_CHECKSUMINV, CARD_FAT_FREEBLOCKS, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_NUM_SYSTEM_BLOCK, CARD_RESULT_BROKEN, CARD_RESULT_READY, CARD_SYSTEM_BLOCK_SIZE, CARDIsValidBlockNo, FALSE, OSDisableInterrupts, OSRestoreInterrupts, TRUE, VerifyDir, VerifyFAT, VerifyID.
Referenced by CARDCheckAsync, CARDCheckEx.
s32 CARDCreate(s32 chan, char *fileName, u32 size, CARDFileInfo *fileInfo)
References __CARDSync, __CARDSyncCallback, CARDCreateAsync, CARDDir::fileName, size.
s32 CARDCreateAsync(s32 chan, char *fileName, u32 size, CARDFileInfo *fileInfo, CARDCallback callback)
References __CARDAllocBlock, __CARDCompareFileName, __CARDDefaultApiCallback, __CARDDiskID, __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFatBlock, __CARDPutControlBlock, CARD_FAT_FREEBLOCKS, CARD_FILENAME_MAX, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_EXIST, CARD_RESULT_FATAL_ERROR, CARD_RESULT_INSSPACE, CARD_RESULT_NAMETOOLONG, CARD_RESULT_NOENT, CARDFileInfo::chan, DVDDiskID::company, CreateCallbackFat, CARDDir::fileName, CARDFileInfo::fileNo, DVDDiskID::gameName, size.
Referenced by CARDCreate.
s32 CARDDelete(s32 chan, char *fileName)
References __CARDSync, __CARDSyncCallback, CARDDeleteAsync.
s32 CARDDeleteAsync(s32 chan, char *fileName, CARDCallback callback)
References __CARDDefaultApiCallback, __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFileNo, __CARDIsOpened, __CARDPutControlBlock, __CARDUpdateDir, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, DeleteCallback.
Referenced by CARDDelete.
s32 CARDFastDelete(s32 chan, s32 fileNo)
s32 CARDFastDeleteAsync(s32 chan, s32 fileNo, CARDCallback callback)
References __CARDAccess, __CARDDefaultApiCallback, __CARDGetControlBlock, __CARDGetDirBlock, __CARDIsOpened, __CARDPutControlBlock, __CARDUpdateDir, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, DeleteCallback.
Referenced by CARDFastDelete.
s32 CARDFastOpen(s32 chan, s32 fileNo, CARDFileInfo *fileInfo)
References __CARDAccess, __CARDGetControlBlock, __CARDGetDirBlock, __CARDIsPublic, __CARDPutControlBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOPERM, CARDIsValidBlockNo, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::offset.
s32 CARDFormat(s32 chan)
References __CARDSync, __CARDSyncCallback, CARDFormatAsync.
s32 CARDFormatAsync(s32 chan, CARDCallback callback)
References __CARDCheckSum, __CARDDefaultApiCallback, __CARDEraseSector, __CARDGetControlBlock, __CARDPutControlBlock, __OSLockSram, __OSLockSramEx, __OSUnlockSram, __OSUnlockSramEx, CARD_FAT_CHECKCODE, CARD_FAT_CHECKSUM, CARD_FAT_CHECKSUMINV, CARD_FAT_FREEBLOCKS, CARD_FAT_LASTSLOT, CARD_MAX_MOUNT_STEP, CARD_NUM_SYSTEM_BLOCK, CARD_SYSTEM_BLOCK_SIZE, CARD_WORKAREA_SIZE, CARDGetDirCheck, CARDID::checkSum, CARDID::checkSumInv, OSSram::counterBias, DCStoreRange, FALSE, FormatCallback, OSSram::language, OSGetFontEncode, OSGetTime, CARDID::serial.
s32 CARDFreeBlocks(s32 chan, s32 *byteNotUsed, s32 *filesNotUsed)
References __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFatBlock, __CARDPutControlBlock, CARD_FAT_FREEBLOCKS, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARD_RESULT_READY, CARDControl::result.
s32 CARDGetSectorSize(s32 chan, u32 *size)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARDControl::result, size.
s32 CARDGetEncoding(s32 chan, u16 *encode)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARDID::encode.
s32 CARDGetMemSize(s32 chan, u16 *size)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARDControl::result, size.
s32 CARDGetResultCode(s32 chan)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARDControl::result.
Referenced by __CARDSync.
s32 CARDGetStatus(s32 chan, s32 fileNo, CARDStat *stat)
References __CARDAccess, __CARDGetControlBlock, __CARDGetDirBlock, __CARDIsPublic, __CARDPutControlBlock, CARDStat::bannerFormat, CARD_FILENAME_MAX, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOPERM, CARDStat::commentAddr, CARDStat::company, CARDStat::fileName, CARDStat::gameName, CARDStat::iconAddr, CARDStat::iconFormat, CARDStat::iconSpeed, CARDStat::length, CARDStat::time, UpdateIconOffsets.
s32 CARDGetXferredBytes(s32 chan)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARDControl::xferred.
s32 CARDMount(s32 chan, void *workArea, CARDCallback detachCallback)
References __CARDSync, __CARDSyncCallback, CARD_MAX_MOUNT_STEP, CARDMountAsync.
s32 CARDMountAsync(s32 chan, void *workArea, CARDCallback detachCallback, CARDCallback attachCallback)
References __CARDBlock, __CARDDefaultApiCallback, __CARDExtHandler, __CARDMountCallback, __CARDUnlockedHandler, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_WRONGDEVICE, DoMount, EXIAttach, EXIGetState, EXILock, EXISetExiCallback, OSCancelAlarm, OSDisableInterrupts, OSRestoreInterrupts, TRUE.
Referenced by CARDMount.
s32 CARDOpen(s32 chan, char *fileName, CARDFileInfo *fileInfo)
References __CARDGetControlBlock, __CARDGetDirBlock, __CARDGetFileNo, __CARDPutControlBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BROKEN, CARDIsValidBlockNo, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::offset.
BOOL CARDProbe(s32 chan)
References EXIProbe.
s32 CARDProbeEx(s32 chan, s32 *memSize, s32 *sectorSize)
References __CARDBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARD_RESULT_WRONGDEVICE, EXIGetID, EXIGetState, EXIProbeEx, OSDisableInterrupts, OSRestoreInterrupts, SectorSizeTable.
s32 CARDRename(s32 chan, char *oldName, char *newName)
References __CARDSync, __CARDSyncCallback, CARD_MAX_MOUNT_STEP, CARDRenameAsync.
s32 CARDRenameAsync(s32 chan, char *oldName, char *newName, CARDCallback callback)
s32 CARDSetStatus(s32 chan, s32 fileNo, CARDStat *stat)
s32 CARDSetStatusAsync(s32 chan, s32 fileNo, CARDStat *stat, CARDCallback callback)
References __CARDAccess, __CARDGetControlBlock, __CARDGetDirBlock, __CARDPutControlBlock, __CARDUpdateDir, CARDStat::bannerFormat, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_STAT_SPEED_FAST, CARDSetIconSpeed, CARDStat::commentAddr, CARDStat::iconAddr, CARDStat::iconFormat, CARDStat::iconSpeed, OSGetTime, OSTicksToSeconds, UpdateIconOffsets.
Referenced by CARDSetStatus.
s32 CARDUnmount(s32 chan)
References __CARDGetControlBlock, CARD_MAX_MOUNT_STEP, CARD_RESULT_NOCARD, CARD_RESULT_READY, DoUnmount.
Referenced by OnReset.
s32 CARDCancel(CARDFileInfo *fileInfo)
References __CARDBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_BUSY, CARD_RESULT_CANCELED, CARD_RESULT_NOCARD, CARD_RESULT_READY, CARDFileInfo::chan, CARDFileInfo::fileNo, CARDFileInfo::length, OSDisableInterrupts, OSRestoreInterrupts.
s32 CARDClose(CARDFileInfo *fileInfo)
References __CARDGetControlBlock, __CARDPutControlBlock, CARD_MAX_FILE, CARD_MAX_MOUNT_STEP, CARD_RESULT_READY, CARDFileInfo::chan, CARDFileInfo::fileNo.
s32 CARDRead(CARDFileInfo *fileInfo, void *addr, s32 length, s32 offset)
s32 CARDReadAsync(CARDFileInfo *fileInfo, void *addr, s32 length, s32 offset, CARDCallback callback)
References __CARDAccess, __CARDDefaultApiCallback, __CARDGetDirBlock, __CARDIsPublic, __CARDPutControlBlock, __CARDRead, __CARDSeek, CARD_MAX_MOUNT_STEP, CARD_RESULT_FATAL_ERROR, CARD_RESULT_NOPERM, CARD_SEG_SIZE, CARDFileInfo::chan, DCInvalidateRange, CARDFileInfo::fileNo, CARDFileInfo::iBlock, CARDFileInfo::offset, OFFSET, ReadCallback.
Referenced by CARDRead.
s32 CARDWrite(CARDFileInfo *fileInfo, void *addr, s32 length, s32 offset)
s32 CARDWriteAsync(CARDFileInfo *fileInfo, void *addr, s32 length, s32 offset, CARDCallback callback)