chorus.c
f32 rsmpTab12khz[512][512]
Referenced by do_src1, do_src2.
const double i2fMagic
Referenced by do_src1, do_src2.
static void do_src1(struct AXFX_CHORUS_SRCINFO *src)
Referenced by AXFXChorusCallback.
static void do_src2(struct AXFX_CHORUS_SRCINFO *src)
Referenced by AXFXChorusCallback.
static asm void do_src1(register struct AXFX_CHORUS_SRCINFO *src)
References blr, AXFX_CHORUS_SRCINFO::dest, i2fMagic, AXFX_CHORUS_SRCINFO::old, AXFX_CHORUS_SRCINFO::pitchLo, AXFX_CHORUS_SRCINFO::posHi, AXFX_CHORUS_SRCINFO::posLo, r4, r5, rsmpTab12khz, AXFX_CHORUS_SRCINFO::smpBase, src, AXFX_CHORUS_SRCINFO::target, AXFX_CHORUS_SRCINFO::trigger.
static asm void do_src2(register struct AXFX_CHORUS_SRCINFO *src)
References blr, AXFX_CHORUS_SRCINFO::dest, i2fMagic, AXFX_CHORUS_SRCINFO::old, AXFX_CHORUS_SRCINFO::pitchLo, AXFX_CHORUS_SRCINFO::posHi, AXFX_CHORUS_SRCINFO::posLo, r4, r5, rsmpTab12khz, AXFX_CHORUS_SRCINFO::smpBase, src, AXFX_CHORUS_SRCINFO::target, AXFX_CHORUS_SRCINFO::trigger.
int AXFXChorusInit(struct AXFX_CHORUS *c)
References __OSCurrHeap, AXFXChorusSettings, AXFX_CHORUS_WORK::currentLast, AXFX_CHORUS_WORK::lastLeft, AXFX_CHORUS_WORK::lastRight, AXFX_CHORUS_WORK::lastSur, NULL, AXFX_CHORUS_WORK::oldLeft, AXFX_CHORUS_WORK::oldRight, AXFX_CHORUS_WORK::oldSur, OSAllocFromHeap, OSDisableInterrupts, OSRestoreInterrupts, AXFX_CHORUS_WORK::src, AXFX_CHORUS_SRCINFO::target, AXFX_CHORUS_SRCINFO::trigger, AXFX_CHORUS::work.
int AXFXChorusShutdown(struct AXFX_CHORUS *c)
References __OSCurrHeap, AXFX_CHORUS_WORK::lastLeft, OSDisableInterrupts, OSFreeToHeap, OSRestoreInterrupts, AXFX_CHORUS::work.
int AXFXChorusSettings(struct AXFX_CHORUS *c)
References AXFX_CHORUS::baseDelay, AXFX_CHORUS_WORK::currentLast, AXFX_CHORUS_WORK::currentPosHi, AXFX_CHORUS_WORK::currentPosLo, OSDisableInterrupts, OSRestoreInterrupts, AXFX_CHORUS::period, AXFX_CHORUS_WORK::pitchOffset, AXFX_CHORUS_WORK::pitchOffsetPeriod, AXFX_CHORUS_WORK::pitchOffsetPeriodCount, AXFX_CHORUS::variation, AXFX_CHORUS::work.
Referenced by AXFXChorusInit.
void AXFXChorusCallback(struct AXFX_BUFFERUPDATE *bufferUpdate, struct AXFX_CHORUS *chorus)
References AXFX_CHORUS_WORK::currentLast, AXFX_CHORUS_WORK::currentPosHi, AXFX_CHORUS_WORK::currentPosLo, AXFX_CHORUS_SRCINFO::dest, do_src1, do_src2, AXFX_CHORUS_WORK::lastLeft, AXFX_CHORUS_WORK::lastRight, AXFX_CHORUS_WORK::lastSur, AXFX_BUFFERUPDATE::left, AXFX_CHORUS_SRCINFO::old, AXFX_CHORUS_WORK::oldLeft, AXFX_CHORUS_WORK::oldRight, AXFX_CHORUS_WORK::oldSur, AXFX_CHORUS_SRCINFO::pitchHi, AXFX_CHORUS_SRCINFO::pitchLo, AXFX_CHORUS_WORK::pitchOffset, AXFX_CHORUS_WORK::pitchOffsetPeriod, AXFX_CHORUS_WORK::pitchOffsetPeriodCount, AXFX_CHORUS_SRCINFO::posHi, AXFX_CHORUS_SRCINFO::posLo, AXFX_BUFFERUPDATE::right, AXFX_CHORUS_SRCINFO::smpBase, AXFX_CHORUS_WORK::src, AXFX_BUFFERUPDATE::surround, AXFX_CHORUS::work.