db.h
OS_DBINTERFACE_ADDR
BOOL DBIsDebuggerPresent(void)
References __DBInterface, DBInterface::bPresent, FALSE, NULL.
void DBPrintf(char *str,...)
Referenced by __OSCacheInit, DOLLoadImage, L2GlobalInvalidate, OSExceptionInit.