db.c
u8 DBStack[4096][4096]
u8* DBStackEnd
BOOL DBVerbose
Referenced by DBInit.
struct DBInterface* __DBInterface
Referenced by __DBIsExceptionMarked, __DBMarkException, __DBSetPresent, DBInit, DBIsDebuggerPresent.
void DBInit(void)
References __DBExceptionDestination, __DBInterface, DBVerbose, DBInterface::ExceptionDestination, OSCachedToPhysical, OSPhysicalToCached, TRUE.
BOOL DBIsDebuggerPresent(void)
References __DBInterface, DBInterface::bPresent, FALSE, NULL.
void __DBExceptionDestinationAux(void)
References CARD_MAX_MOUNT_STEP, OSDumpContext, OSPhysicalToCached, OSReport, PPCHalt.
Referenced by __DBExceptionDestination.
asm void __DBExceptionDestination(void)
References __DBExceptionDestinationAux, CARD_MAX_MOUNT_STEP, r3.
Referenced by DBInit.
BOOL __DBIsExceptionMarked(__OSException exception)
References __DBInterface, CARD_MAX_MOUNT_STEP, DBInterface::exceptionMask.
Referenced by OSExceptionInit.
void __DBMarkException(u8 exception, int value)
References __DBInterface, CARD_MAX_MOUNT_STEP, DBInterface::exceptionMask.
void __DBSetPresent(u32 value)
References __DBInterface, DBInterface::bPresent, CARD_MAX_MOUNT_STEP.
void DBPrintf(char *str,...)
Referenced by __OSCacheInit, __OSContextInit, DOLLoadImage, L2GlobalInvalidate, OSExceptionInit.