demo.h
u32 DEMOFontBitmap[768][768]
void DEMOPrintf(s16 x, s16 y, s16 priority, char *str,...)
References CARD_MAX_MOUNT_STEP, DEMOPuts.
Referenced by DEMOPrintStats, DEMOWinRefresh.
struct _GXRenderModeObj * DEMOGetRenderModeObj()
References rmode.
Referenced by DEMOPrintStats, DEMOWinInit.