dsp_debug.c
DSPTaskInfo* __DSP_first_task
DSPTaskInfo* __DSP_last_task
DSPTaskInfo* __DSP_curr_task
Referenced by __DSPGetCurrentTask.
DSPTaskInfo* __DSP_tmp_task
void __DSP_debug_printf(const char *fmt,...)
Referenced by __DSP_add_task, __DSP_boot_task, DSPInit.
DSPTaskInfo * __DSPGetCurrentTask(void)
References __DSP_curr_task.