dsp_task.c
u32 t0
Referenced by __OSGetRTC.
u32 t1
Referenced by __AI_SRC_INIT, __OSGetRTC.
u32 t2
DSPTaskInfo* __DSP_first_task
Referenced by __DSP_add_task, __DSP_insert_task, __DSP_remove_task, __DSPHandler.
DSPTaskInfo* __DSP_last_task
Referenced by __DSP_add_task, __DSP_insert_task, __DSP_remove_task, __DSPHandler.
DSPTaskInfo* __DSP_curr_task
Referenced by __DSP_add_task, __DSP_insert_task, __DSP_remove_task, __DSPHandler.
DSPTaskInfo* __DSP_tmp_task
DSPTaskInfo* __DSP_rude_task
Referenced by __DSPHandler, DSPAssertTask.
int __DSP_rude_task_pending
Referenced by __DSPHandler, DSPAssertTask.
void __DSPHandler(__OSInterrupt intr, OSContext *context)
References __DSP_curr_task, __DSP_exec_task, __DSP_first_task, __DSP_last_task, __DSP_remove_task, __DSP_rude_task, __DSP_rude_task_pending, CARD_MAX_MOUNT_STEP, STRUCT_DSP_TASK::done_cb, DSPCheckMailFromDSP, DSPCheckMailToDSP, DSPReadMailFromDSP, DSPSendMailToDSP, STRUCT_DSP_TASK::flags, STRUCT_DSP_TASK::init_cb, STRUCT_DSP_TASK::next, NULL, OSClearContext, OSSetCurrentContext, STRUCT_DSP_TASK::prev, STRUCT_DSP_TASK::req_cb, STRUCT_DSP_TASK::res_cb, STRUCT_DSP_TASK::state, tmp.
Referenced by DSPInit.
void __DSP_exec_task(DSPTaskInfo *curr, DSPTaskInfo *next)
References CARD_MAX_MOUNT_STEP, DSPCheckMailToDSP, DSPSendMailToDSP, next, NULL, DVDCommandBlock::state.
Referenced by __DSPHandler.
void __DSP_boot_task(DSPTaskInfo *task)
References __DSP_debug_printf, CARD_MAX_MOUNT_STEP, STRUCT_DSP_TASK::dram_length, STRUCT_DSP_TASK::dsp_init_vector, DSPCheckMailFromDSP, DSPCheckMailToDSP, DSPReadMailFromDSP, DSPSendMailToDSP, STRUCT_DSP_TASK::iram_addr, STRUCT_DSP_TASK::iram_length, STRUCT_DSP_TASK::iram_mmem_addr, NULL, task.
Referenced by DSPAddTask.
void __DSP_insert_task(DSPTaskInfo *task)
References __DSP_curr_task, __DSP_first_task, __DSP_last_task, CARD_MAX_MOUNT_STEP, STRUCT_DSP_TASK::next, NULL, STRUCT_DSP_TASK::prev, STRUCT_DSP_TASK::priority, task.
Referenced by DSPAddTask.
void __DSP_add_task(DSPTaskInfo *task)
References __DSP_curr_task, __DSP_debug_printf, __DSP_first_task, __DSP_last_task, CARD_MAX_MOUNT_STEP, STRUCT_DSP_TASK::next, NULL, STRUCT_DSP_TASK::prev, STRUCT_DSP_TASK::state, task.
void __DSP_remove_task(DSPTaskInfo *task)
References __DSP_curr_task, __DSP_first_task, __DSP_last_task, CARD_MAX_MOUNT_STEP, STRUCT_DSP_TASK::flags, STRUCT_DSP_TASK::next, NULL, STRUCT_DSP_TASK::prev, STRUCT_DSP_TASK::state, task.
Referenced by __DSPHandler.