dsp.c
BOOL __DSP_init_flag
Referenced by DSPAddTask, DSPAssertTask, DSPCancelTask, DSPCheckInit, DSPInit, DSPReset.
DSPTaskInfo* __DSP_first_task
Referenced by DSPAddTask, DSPInit.
DSPTaskInfo* __DSP_last_task
Referenced by DSPInit.
DSPTaskInfo* __DSP_curr_task
Referenced by DSPAssertTask, DSPInit.
DSPTaskInfo* __DSP_tmp_task
Referenced by DSPInit.
DSPTaskInfo* __DSP_rude_task
Referenced by __DSPHandler, DSPAssertTask.
int __DSP_rude_task_pending
Referenced by __DSPHandler, DSPAssertTask.
u32 DSPCheckMailToDSP(void)
References CARD_MAX_MOUNT_STEP.
Referenced by __AXOutNewFrame, __DSP_boot_task, __DSP_exec_task, __DSPHandler, InitCallback.
u32 DSPCheckMailFromDSP(void)
References CARD_MAX_MOUNT_STEP.
Referenced by __DSP_boot_task, __DSPHandler.
u32 DSPReadCPUToDSPMbox(void)
References CARD_MAX_MOUNT_STEP.
u32 DSPReadMailFromDSP(void)
References CARD_MAX_MOUNT_STEP.
Referenced by __DSP_boot_task, __DSPHandler.
void DSPSendMailToDSP(u32 mail)
References CARD_MAX_MOUNT_STEP.
Referenced by __AXOutNewFrame, __DSP_boot_task, __DSP_exec_task, __DSPHandler, InitCallback.
void DSPAssertInt(void)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, tmp.
Referenced by DSPAssertTask.
void DSPInit(void)
References __DSP_curr_task, __DSP_debug_printf, __DSP_first_task, __DSP_init_flag, __DSP_last_task, __DSP_tmp_task, __DSPHandler, __OSSetInterruptHandler, __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, NULL, OS_INTERRUPTMASK_DSP_DSP, OSDisableInterrupts, OSRestoreInterrupts, tmp, TRUE.
Referenced by __AXOutInitDSP, CARDInit.
BOOL DSPCheckInit(void)
References __DSP_init_flag.
Referenced by __AXOutInitDSP.
void DSPReset(void)
References __DSP_init_flag, CARD_MAX_MOUNT_STEP, FALSE, OSDisableInterrupts, OSRestoreInterrupts, tmp.
Referenced by __AXOutQuit.
void DSPHalt(void)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, tmp.
Referenced by __AXOutQuit.
void DSPUnhalt(void)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, tmp.
u32 DSPGetDMAStatus(void)
References CARD_MAX_MOUNT_STEP.
Referenced by __AXOutQuit.
DSPTaskInfo * DSPAddTask(DSPTaskInfo *task)
References __DSP_boot_task, __DSP_first_task, __DSP_init_flag, __DSP_insert_task, CARD_MAX_MOUNT_STEP, STRUCT_DSP_TASK::flags, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DSP_TASK::state, task, TRUE.
Referenced by __AXOutInitDSP, __CARDUnlock.
DSPTaskInfo * DSPCancelTask(DSPTaskInfo *task)
References __DSP_init_flag, CARD_MAX_MOUNT_STEP, STRUCT_DSP_TASK::flags, OSDisableInterrupts, OSRestoreInterrupts, task.
DSPTaskInfo * DSPAssertTask(DSPTaskInfo *task)
References __DSP_curr_task, __DSP_init_flag, __DSP_rude_task, __DSP_rude_task_pending, CARD_MAX_MOUNT_STEP, DSPAssertInt, STRUCT_DSP_TASK::flags, NULL, OSDisableInterrupts, OSRestoreInterrupts, STRUCT_DSP_TASK::priority, STRUCT_DSP_TASK::state, task, TRUE.
Referenced by __AXOutAiCallback.