dtk.c
DTKTrack* __DTKCurrentTrack
Referenced by __DTKBackward, __DTKCallbackForAIInterrupt, __DTKCallbackForFlush, __DTKCallbackForPlaylist, __DTKCallbackForPreparePaused, __DTKCallbackForRun, __DTKCallbackForStop, __DTKForward, __DTKPrepareCurrentTrack, __DTKPrepareCurrentTrackPaused, DTKGetCurrentTrack, DTKInit, DTKNextTrack, DTKPrevTrack, DTKQueueTrack, DTKRemoveTrack, DTKSetState.
DTKTrack* __DTKPlayListHead
Referenced by __DTKCallbackForFlush, __DTKCallbackForPlaylist, DTKInit, DTKQueueTrack, DTKRemoveTrack.
DTKTrack* __DTKPlayListTail
Referenced by __DTKCallbackForFlush, DTKInit, DTKQueueTrack, DTKRemoveTrack.
volatile u32 __DTKState
Referenced by __DTKCallbackForFlush, __DTKCallbackForNextTrack, __DTKCallbackForPlaylist, __DTKCallbackForPreparePaused, __DTKCallbackForPrevTrack, __DTKCallbackForRun, __DTKCallbackForStop, DTKFlushTracks, DTKGetState, DTKInit, DTKNextTrack, DTKPrevTrack, DTKQueueTrack, DTKSetState, DTKSetVolume, DTKShutdown.
volatile u32 __DTKTempState
Referenced by __DTKCallbackForNextTrack, __DTKCallbackForPrevTrack, DTKNextTrack, DTKPrevTrack.
volatile u32 __DTKRepeatMode
Referenced by __DTKCallbackForPlaylist, DTKGetRepeatMode, DTKInit, DTKRemoveTrack, DTKSetRepeatMode.
volatile u32 __DTKPosition
Referenced by __DTKCallbackForPlaylist, __DTKCallbackForStreamStatus, DTKGetPosition, DTKInit.
volatile u32 __DTKInterruptFrequency
Referenced by __DTKCallbackForAIInterrupt, __DTKStartAi, DTKGetInterruptFrequency, DTKInit, DTKSetInterruptFrequency.
volatile u8 __DTKVolumeL
Referenced by __DTKStartAi, DTKGetVolume, DTKInit, DTKSetVolume.
volatile u8 __DTKVolumeR
Referenced by __DTKStartAi, DTKGetVolume, DTKInit, DTKSetVolume.
volatile u32 __DTKShutdownFlag
Referenced by __DTKCallbackForFlush, DTKShutdown.
volatile u32 __DTKTrackEnded
Referenced by __DTKCallbackForPlaylist, __DTKCallbackForStreamStatus, DTKSetState.
DTKFlushCallback __DTKFlushCallback
Referenced by __DTKCallbackForFlush, DTKFlushTracks.
DVDCommandBlock __block_for_run_callback
Referenced by __DTKCallbackForRun.
DVDCommandBlock __block_for_prep_callback
Referenced by __DTKCallbackForPreparePaused.
DVDCommandBlock __block_for_stream_status
Referenced by __DTKCallbackForPlaylist.
DVDCommandBlock __block_for_ais_isr
Referenced by __DTKCallbackForAIInterrupt.
DVDCommandBlock __block_for_flushtracks
Referenced by DTKFlushTracks.
DVDCommandBlock __block_for_repeatmode
DVDCommandBlock __block_for_set_state
Referenced by DTKSetState.
DVDCommandBlock __block_for_next_track
Referenced by DTKNextTrack.
DVDCommandBlock __block_for_prev_track
Referenced by DTKPrevTrack.
static void __DTKStartAi(void)
References __DTKInterruptFrequency, __DTKVolumeL, __DTKVolumeR, AIResetStreamSampleCount, AISetStreamPlayState, AISetStreamTrigger, AISetStreamVolLeft, AISetStreamVolRight.
Referenced by __DTKCallbackForRun, DTKSetState.
static void __DTKStopAi(void)
References AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight.
Referenced by __DTKCallbackForPlaylist, __DTKCallbackForPreparePaused.
static void __DTKCheckUserCallback(struct DTKTrack *track, u32 event)
References DTKTrack::callback, CARD_MAX_MOUNT_STEP, DTKTrack::eventMask.
Referenced by __DTKCallbackForPlaylist, __DTKCallbackForPreparePaused, __DTKCallbackForRun, __DTKCallbackForStop, DTKQueueTrack, DTKSetState.
static void __DTKForward(void)
References __DTKCurrentTrack, DTKTrack::next, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __DTKCallbackForNextTrack, DTKNextTrack.
static void __DTKBackward(void)
References __DTKCurrentTrack, OSDisableInterrupts, OSRestoreInterrupts, DTKTrack::prev.
Referenced by __DTKCallbackForPrevTrack, DTKPrevTrack.
static void __DTKCallbackForStreamStatus(s32 result, DVDCommandBlock *block)
References __DTKPosition, __DTKTrackEnded.
Referenced by __DTKCallbackForPlaylist.
static void __DTKCallbackForRun(s32 result, DVDFileInfo *fileInfo)
References __block_for_run_callback, __DTKCheckUserCallback, __DTKCurrentTrack, __DTKStartAi, __DTKState, DTK_STATE_RUN, DVDStopStreamAtEndAsync.
Referenced by __DTKPrepareCurrentTrack.
static void __DTKCallbackForPreparePaused(s32 result, DVDFileInfo *fileInfo)
References __block_for_prep_callback, __DTKCheckUserCallback, __DTKCurrentTrack, __DTKState, __DTKStopAi, DTK_STATE_PAUSE, DVDStopStreamAtEndAsync.
Referenced by __DTKPrepareCurrentTrackPaused.
static void __DTKPrepareCurrentTrack(void)
References __DTKCallbackForRun, __DTKCurrentTrack, DTKTrack::dvdFileInfo, DVDPrepareStreamAsync.
Referenced by __DTKCallbackForPlaylist, DTKQueueTrack, DTKSetState.
static void __DTKPrepareCurrentTrackPaused(void)
References __DTKCallbackForPreparePaused, __DTKCurrentTrack, DTKTrack::dvdFileInfo, DVDPrepareStreamAsync.
Referenced by DTKSetState.
static void __DTKCallbackForPlaylist(s32 result, DVDCommandBlock *block)
References __block_for_stream_status, __DTKCallbackForStreamStatus, __DTKCheckUserCallback, __DTKCurrentTrack, __DTKPlayListHead, __DTKPosition, __DTKPrepareCurrentTrack, __DTKRepeatMode, __DTKState, __DTKStopAi, __DTKTrackEnded, DTK_MODE_ALLREPEAT, DTK_MODE_NOREPEAT, DTK_MODE_REPEAT1, DTK_STATE_BUSY, DTK_STATE_STOP, DVDGetStreamErrorStatusAsync, DTKTrack::next.
Referenced by __DTKCallbackForAIInterrupt.
static void __DTKCallbackForAIInterrupt(u32 count)
References __block_for_ais_isr, __DTKCallbackForPlaylist, __DTKCurrentTrack, __DTKInterruptFrequency, AISetStreamTrigger, DVDGetStreamPlayAddrAsync.
Referenced by DTKInit.
static void __DTKCallbackForFlush(s32 result, DVDCommandBlock *block)
References __DTKCurrentTrack, __DTKFlushCallback, __DTKPlayListHead, __DTKPlayListTail, __DTKShutdownFlag, __DTKState, AISetStreamPlayState, DTK_STATE_STOP, DVDClose, DTKTrack::dvdFileInfo, DTKTrack::next, NULL.
Referenced by DTKFlushTracks.
static void __DTKCallbackForStop(s32 result, DVDCommandBlock *block)
References __DTKCheckUserCallback, __DTKCurrentTrack, __DTKState, DTK_STATE_STOP.
Referenced by DTKSetState.
static void __DTKCallbackForNextTrack(s32 result, DVDCommandBlock *block)
References __DTKForward, __DTKState, __DTKTempState, AISetStreamPlayState, DTK_STATE_STOP, DTKSetState.
Referenced by DTKNextTrack.
static void __DTKCallbackForPrevTrack(s32 result, DVDCommandBlock *block)
References __DTKBackward, __DTKState, __DTKTempState, AISetStreamPlayState, DTK_STATE_STOP, DTKSetState.
Referenced by DTKPrevTrack.
void DTKInit(void)
References __DTKCallbackForAIInterrupt, __DTKCurrentTrack, __DTKInterruptFrequency, __DTKPlayListHead, __DTKPlayListTail, __DTKPosition, __DTKRepeatMode, __DTKState, __DTKVolumeL, __DTKVolumeR, AIRegisterStreamCallback, AIResetStreamSampleCount, AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight, DTK_MODE_NOREPEAT, DTK_STATE_STOP, NULL.
void DTKShutdown(void)
References __DTKShutdownFlag, __DTKState, AIRegisterStreamCallback, AIResetStreamSampleCount, AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_STOP, DTKFlushTracks, NULL.
u32 DTKQueueTrack(char *fileName, DTKTrack *track, u32 eventMask, DTKCallback callback)
References __DTKCheckUserCallback, __DTKCurrentTrack, __DTKPlayListHead, __DTKPlayListTail, __DTKPrepareCurrentTrack, __DTKState, DTKTrack::callback, CARD_MAX_MOUNT_STEP, DTK_STATE_BUSY, DTK_STATE_RUN, DTKTrack::dvdFileInfo, DVDOpen, DTKTrack::eventMask, DTKTrack::fileName, DTKTrack::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, DTKTrack::prev.
u32 DTKRemoveTrack(struct DTKTrack *track)
References __DTKCurrentTrack, __DTKPlayListHead, __DTKPlayListTail, __DTKRepeatMode, DTK_MODE_ALLREPEAT, DVDClose, DTKTrack::dvdFileInfo, DTKTrack::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, DTKTrack::prev.
void DTKFlushTracks(DTKFlushCallback callback)
References __block_for_flushtracks, __DTKCallbackForFlush, __DTKFlushCallback, __DTKState, DTKTrack::callback, CARD_MAX_MOUNT_STEP, DTK_STATE_BUSY, DTK_STATE_RUN, DVDCancelStreamAsync.
Referenced by DTKShutdown.
void DTKSetSampleRate(u32 samplerate)
void DTKSetInterruptFrequency(u32 samples)
References __DTKInterruptFrequency, AIResetStreamSampleCount, AISetStreamTrigger.
void DTKSetRepeatMode(u32 repeat)
References __DTKRepeatMode.
void DTKSetState(u32 state)
References __block_for_set_state, __DTKCallbackForStop, __DTKCheckUserCallback, __DTKCurrentTrack, __DTKPrepareCurrentTrack, __DTKPrepareCurrentTrackPaused, __DTKStartAi, __DTKState, __DTKTrackEnded, AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_BUSY, DTK_STATE_PAUSE, DTK_STATE_PREPARE, DTK_STATE_RUN, DTK_STATE_STOP, DVDCancelStreamAsync.
Referenced by __DTKCallbackForNextTrack, __DTKCallbackForPrevTrack.
void DTKNextTrack(void)
References __block_for_next_track, __DTKCallbackForNextTrack, __DTKCurrentTrack, __DTKForward, __DTKState, __DTKTempState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_BUSY, DTK_STATE_RUN, DVDCancelStreamAsync.
void DTKPrevTrack(void)
References __block_for_prev_track, __DTKBackward, __DTKCallbackForPrevTrack, __DTKCurrentTrack, __DTKState, __DTKTempState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_BUSY, DTK_STATE_RUN, DVDCancelStreamAsync.
u32 DTKGetSampleRate(void)
u32 DTKGetRepeatMode(void)
References __DTKRepeatMode.
u32 DTKGetState(void)
References __DTKState.
u32 DTKGetPosition(void)
References __DTKPosition.
u32 DTKGetInterruptFrequency(void)
References __DTKInterruptFrequency.
DTKTrack * DTKGetCurrentTrack(void)
References __DTKCurrentTrack.
void DTKSetVolume(u8 left, u8 right)
References __DTKState, __DTKVolumeL, __DTKVolumeR, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_RUN.
u16 DTKGetVolume(void)
References __DTKVolumeL, __DTKVolumeR.