dtk.h
DTK_STATE_STOP
DTK_STATE_RUN
DTK_STATE_PAUSE
DTK_STATE_BUSY
DTK_STATE_PREPARE
DTK_MODE_NOREPEAT
DTK_MODE_ALLREPEAT
DTK_MODE_REPEAT1
typedef void(* DTKCallback) (u32 eventMask))(u32 eventMask)
typedef void(* DTKFlushCallback) (void))(void)
typedef struct DTKTrack DTKTrack
void DTKInit(void)
References __DTKCallbackForAIInterrupt, __DTKCurrentTrack, __DTKInterruptFrequency, __DTKPlayListHead, __DTKPlayListTail, __DTKPosition, __DTKRepeatMode, __DTKState, __DTKVolumeL, __DTKVolumeR, AIRegisterStreamCallback, AIResetStreamSampleCount, AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight, DTK_MODE_NOREPEAT, DTK_STATE_STOP, NULL.
void DTKShutdown(void)
References __DTKShutdownFlag, __DTKState, AIRegisterStreamCallback, AIResetStreamSampleCount, AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_STOP, DTKFlushTracks, NULL.
u32 DTKQueueTrack(char *fileName, DTKTrack *track, u32 eventMask, DTKCallback callback)
References __DTKCheckUserCallback, __DTKCurrentTrack, __DTKPlayListHead, __DTKPlayListTail, __DTKPrepareCurrentTrack, __DTKState, DTKTrack::callback, CARD_MAX_MOUNT_STEP, DTK_STATE_BUSY, DTK_STATE_RUN, DTKTrack::dvdFileInfo, DVDOpen, DTKTrack::eventMask, DTKTrack::fileName, DTKTrack::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, DTKTrack::prev.
u32 DTKRemoveTrack(struct DTKTrack *track)
References __DTKCurrentTrack, __DTKPlayListHead, __DTKPlayListTail, __DTKRepeatMode, DTK_MODE_ALLREPEAT, DVDClose, DTKTrack::dvdFileInfo, DTKTrack::next, NULL, OSDisableInterrupts, OSRestoreInterrupts, DTKTrack::prev.
void DTKFlushTracks(DTKFlushCallback callback)
References __block_for_flushtracks, __DTKCallbackForFlush, __DTKFlushCallback, __DTKState, DTKTrack::callback, CARD_MAX_MOUNT_STEP, DTK_STATE_BUSY, DTK_STATE_RUN, DVDCancelStreamAsync.
Referenced by DTKShutdown.
void DTKSetSampleRate(u32 samplerate)
void DTKSetInterruptFrequency(u32 samples)
References __DTKInterruptFrequency, AIResetStreamSampleCount, AISetStreamTrigger.
void DTKSetRepeatMode(u32 repeat)
References __DTKRepeatMode.
void DTKSetState(u32 state)
References __block_for_set_state, __DTKCallbackForStop, __DTKCheckUserCallback, __DTKCurrentTrack, __DTKPrepareCurrentTrack, __DTKPrepareCurrentTrackPaused, __DTKStartAi, __DTKState, __DTKTrackEnded, AISetStreamPlayState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_BUSY, DTK_STATE_PAUSE, DTK_STATE_PREPARE, DTK_STATE_RUN, DTK_STATE_STOP, DVDCancelStreamAsync.
Referenced by __DTKCallbackForNextTrack, __DTKCallbackForPrevTrack.
void DTKNextTrack(void)
References __block_for_next_track, __DTKCallbackForNextTrack, __DTKCurrentTrack, __DTKForward, __DTKState, __DTKTempState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_BUSY, DTK_STATE_RUN, DVDCancelStreamAsync.
void DTKPrevTrack(void)
References __block_for_prev_track, __DTKBackward, __DTKCallbackForPrevTrack, __DTKCurrentTrack, __DTKState, __DTKTempState, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_BUSY, DTK_STATE_RUN, DVDCancelStreamAsync.
u32 DTKGetSampleRate(void)
u32 DTKGetRepeatMode(void)
References __DTKRepeatMode.
u32 DTKGetState(void)
References __DTKState.
u32 DTKGetPosition(void)
References __DTKPosition.
u32 DTKGetInterruptFrequency(void)
References __DTKInterruptFrequency.
DTKTrack * DTKGetCurrentTrack(void)
References __DTKCurrentTrack.
void DTKSetVolume(u8 left, u8 right)
References __DTKState, __DTKVolumeL, __DTKVolumeR, AISetStreamVolLeft, AISetStreamVolRight, DTK_STATE_RUN.
u16 DTKGetVolume(void)
References __DTKVolumeL, __DTKVolumeR.