dvd.h
DVDReadAsync
DVD_MIN_TRANSFER_SIZE
DVD_STATE_FATAL_ERROR
DVD_STATE_END
DVD_STATE_BUSY
DVD_STATE_WAITING
DVD_STATE_COVER_CLOSED
DVD_STATE_NO_DISK
DVD_STATE_COVER_OPEN
DVD_STATE_WRONG_DISK
DVD_STATE_MOTOR_STOPPED
DVD_STATE_PAUSING
DVD_STATE_IGNORED
DVD_STATE_CANCELED
DVD_STATE_RETRY
DVD_RESULT_FATAL_ERROR
DVD_RESULT_COVER_CLOSED
DVD_RESULT_COVER_OPEN
DVD_RESULT_NO_DISK
DVD_RESULT_IGNORED
DVD_RESULT_CANCELED
DVD_INTTYPE_TC
DVD_INTTYPE_DE
DVD_INTTYPE_CVR
DVD_INTTYPE_BRK
DVD_INTTYPE_TIMEOUT
DVD_INTTYPE_SECURITY_ERROR
DVD_COMMAND_NONE
DVD_COMMAND_READ
DVD_COMMAND_SEEK
DVD_COMMAND_CHANGE_DISK
DVD_COMMAND_BSREAD
DVD_COMMAND_READID
DVD_COMMAND_INITSTREAM
DVD_COMMAND_CANCELSTREAM
DVD_COMMAND_STOP_STREAM_AT_END
DVD_COMMAND_REQUEST_AUDIO_ERROR
DVD_COMMAND_REQUEST_PLAY_ADDR
DVD_COMMAND_REQUEST_START_ADDR
DVD_COMMAND_REQUEST_LENGTH
DVD_COMMAND_AUDIO_BUFFER_CONFIG
DVD_COMMAND_INQUIRY
DVD_COMMAND_BS_CHANGE_DISK
typedef struct DVDDiskID DVDDiskID
typedef struct DVDCommandBlock DVDCommandBlock
typedef void(* DVDCBCallback) (s32 result, DVDCommandBlock *block))(s32 result, DVDCommandBlock *block)
typedef struct DVDFileInfo DVDFileInfo
typedef void(* DVDCallback) (s32 result, DVDFileInfo *fileInfo))(s32 result, DVDFileInfo *fileInfo)
typedef struct DVDBB2 DVDBB2
typedef struct DVDDriveInfo DVDDriveInfo
typedef void(* DVDLowCallback) (u32))(u32)
void(*)(u32) DVDLowSetResetCoverCallback(DVDLowCallback callback)(DVDLowCallback callback)
void(*)(u32) DVDLowClearCallback()()
Referenced by DVDCancelAsync.
void DVDDumpWaitingQueue(void)
References CARD_MAX_MOUNT_STEP, CommandNames, DVDCommandBlock::next, OSReport, WaitingQueue.
BOOL DVDLowRead(void *addr, u32 length, u32 offset, DVDLowCallback callback)
References __OSGetSystemTime, DVDBuffer::addr, CARD_MAX_MOUNT_STEP, Curr, DoJustRead, FALSE, FirstRead, HitCache, LastReadFinished, DVDBuffer::length, DVDBuffer::offset, OSMicrosecondsToTicks, OSMillisecondsToTicks, Prev, SeekTwiceBeforeRead, TRUE, WaitBeforeRead, WorkAroundType.
Referenced by stateBusy, stateCheckID2, stateReadingFST.
BOOL DVDLowSeek(u32 offset, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateGettingError, ProcessNextCommand, SeekTwiceBeforeRead, stateBusy.
BOOL DVDLowWaitCoverClose(DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, TRUE, WaitingCoverClose.
Referenced by stateMotorStopped.
BOOL DVDLowReadDiskID(DVDDiskID *diskID, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by stateBusy, stateCoverClosed_CMD.
BOOL DVDLowStopMotor(DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateCheckID1, stateBusy, stateCheckID, stateError, stateGoToRetry.
BOOL DVDLowRequestError(DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateCheckID3, cbForUnrecoveredError, stateGettingError.
BOOL DVDLowInquiry(struct DVDDriveInfo *info, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by stateBusy.
BOOL DVDLowAudioStream(u32 subcmd, u32 length, u32 offset, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateBusy, stateBusy.
BOOL DVDLowRequestAudioStatus(u32 subcmd, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by stateBusy.
BOOL DVDLowAudioBufferConfig(int enable, u32 size, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, size, TRUE.
Referenced by stateBusy, stateCheckID3.
void DVDLowReset()
References __OSGetSystemTime, CARD_MAX_MOUNT_STEP, LastResetEnd, OSMicrosecondsToTicks, ResetOccurred, TRUE.
Referenced by DVDReset.
BOOL DVDLowBreak()
References AlarmHandlerForBreak, NULL, TRUE.
Referenced by DVDCancelAsync.
u32 DVDLowGetCoverStatus()
References __OSGetSystemTime, CARD_MAX_MOUNT_STEP, FALSE, LastResetEnd, OSMillisecondsToTicks, TRUE.
void DVDInit()
References __DVDClearWaitingQueue, __DVDFSInit, __DVDInitWA, __DVDInterruptHandler, __DVDThreadQueue, __fstLoad, __OSSetInterruptHandler, __OSUnmaskInterrupts, bootInfo, CARD_MAX_MOUNT_STEP, currID, DI_CVR, DI_SR, OSBootInfo_s::DVDDiskID, DVDInitialized, FirstTimeInBootrom, OSBootInfo_s::magic, OS_BOOTINFO_MAGIC, OS_BOOTINFO_MAGIC_JTAG, OSInitAlarm, OSInitThreadQueue, OSPhysicalToCached, OSReport.
Referenced by __OSReboot, DEMOInit.
int DVDReadAbsAsyncPrio(DVDCommandBlock *block, void *addr, s32 length, s32 offset, DVDCBCallback callback, s32 prio)
Referenced by DVDReadAsyncPrio, DVDReadPrio.
int DVDSeekAbsAsyncPrio(DVDCommandBlock *block, s32 offset, DVDCBCallback callback, s32 prio)
0x14
Referenced by DVDSeekAsyncPrio, DVDSeekPrio.
BOOL DVDReadAbsAsyncForBS(DVDCommandBlock *block, void *addr, s32 length, s32 offset, DVDCBCallback callback)
Referenced by cb, ReadApploader.
BOOL DVDReadDiskID(DVDCommandBlock *block, DVDDiskID *diskID, DVDCBCallback callback)
Referenced by __fstLoad, cb.
BOOL DVDPrepareStreamAbsAsync(DVDCommandBlock *block, u32 length, u32 offset, DVDCBCallback callback)
Referenced by DVDPrepareStream, DVDPrepareStreamAsync.
BOOL DVDCancelStreamAsync(DVDCommandBlock *block, DVDCBCallback callback)
Referenced by DTKFlushTracks, DTKNextTrack, DTKPrevTrack, DTKSetState.
s32 DVDCancelStream(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForCancelStreamSync, DVD_STATE_CANCELED, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDCancelStreamAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, TRUE.
BOOL DVDStopStreamAtEndAsync(DVDCommandBlock *block, DVDCBCallback callback)
Referenced by __DTKCallbackForPreparePaused, __DTKCallbackForRun.
s32 DVDStopStreamAtEnd(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForStopStreamAtEndSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDStopStreamAtEndAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamErrorStatusAsync(DVDCommandBlock *block, DVDCBCallback callback)
Referenced by __DTKCallbackForPlaylist.
s32 DVDGetStreamErrorStatus(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamErrorStatusSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamErrorStatusAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamPlayAddrAsync(DVDCommandBlock *block, DVDCBCallback callback)
Referenced by __DTKCallbackForAIInterrupt.
s32 DVDGetStreamPlayAddr(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamPlayAddrSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamPlayAddrAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamStartAddrAsync(DVDCommandBlock *block, DVDCBCallback callback)
s32 DVDGetStreamStartAddr(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamStartAddrSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamStartAddrAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamLengthAsync(DVDCommandBlock *block, DVDCBCallback callback)
s32 DVDGetStreamLength(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamLengthSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamLengthAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDChangeDiskAsyncForBS(DVDCommandBlock *block, DVDCBCallback callback)
BOOL DVDChangeDiskAsync(DVDCommandBlock *block, DVDDiskID *id, DVDCBCallback callback)
s32 DVDChangeDisk(DVDCommandBlock *block, DVDDiskID *id)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForChangeDiskSync, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDChangeDiskAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread.
int DVDInquiryAsync(DVDCommandBlock *block, struct DVDDriveInfo *info, DVDCBCallback callback)
s32 DVDInquiry(DVDCommandBlock *block, struct DVDDriveInfo *info)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForInquirySync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDInquiryAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
void DVDReset()
References CARD_MAX_MOUNT_STEP, DI_CVR, DI_SR, DVDLowReset, ResetRequired, ResumeFromHere.
Referenced by __fstLoad, AlarmHandler, cb, cbForStateBusy, cbForStateCheckID1, cbForStateCheckID2, cbForStateCheckID3, cbForStateCoverClosed, cbForStateGettingError, cbForStateGoToRetry, cbForUnrecoveredError, cbForUnrecoveredErrorRetry, stateCoverClosed, stateTimeout.
BOOL DVDResetRequired()
References ResetRequired.
s32 DVDGetCommandBlockStatus(DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, DVD_STATE_BUSY, DVD_STATE_COVER_CLOSED, OSDisableInterrupts, OSRestoreInterrupts, status.
Referenced by DVDGetDriveStatus.
s32 DVDGetDriveStatus()
References CARD_MAX_MOUNT_STEP, DummyCommandBlock, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_PAUSING, DVDGetCommandBlockStatus, executing, FALSE, FatalErrorFlag, NULL, OSDisableInterrupts, OSRestoreInterrupts, PausingFlag.
Referenced by __fstLoad.
BOOL DVDSetAutoInvalidation(int autoInval)
References autoInvalidation, CARD_MAX_MOUNT_STEP, prev.
void DVDPause()
References executing, NULL, OSDisableInterrupts, OSRestoreInterrupts, PauseFlag, PausingFlag.
Referenced by DVDCancelAllAsync.
void DVDResume()
References OSDisableInterrupts, OSRestoreInterrupts, PauseFlag, PausingFlag, stateReady.
Referenced by DVDCancelAllAsync.
BOOL DVDCancelAsync(DVDCommandBlock *block, DVDCBCallback callback)
s32 DVDCancel(volatile DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForCancelSync, DVD_COMMAND_AUDIO_BUFFER_CONFIG, DVD_COMMAND_BS_CHANGE_DISK, DVD_COMMAND_BSREAD, DVD_COMMAND_READID, DVD_STATE_CANCELED, DVD_STATE_COVER_CLOSED, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDCancelAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread.
Referenced by DVDClose.
BOOL DVDCancelAllAsync(DVDCBCallback callback)
s32 DVDCancelAll()
References __DVDThreadQueue, CancelAllSyncComplete, cbForCancelAllSync, DVDCancelAllAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread.
DVDDiskID * DVDGetCurrentDiskID()
References OSPhysicalToCached.
Referenced by AudioBufferOn.
BOOL DVDCheckDisk()
References CARD_MAX_MOUNT_STEP, DI_CVR, DummyCommandBlock, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_PAUSING, executing, FALSE, FatalErrorFlag, NULL, OSDisableInterrupts, OSRestoreInterrupts, PausingFlag, DVDCommandBlock::state, TRUE.
Referenced by __OSReboot.
void __DVDPrepareResetAsync(DVDCBCallback cb)
References __DVDClearWaitingQueue, DVDCommandBlock::callback, CancelCallback, Canceling, cb, DVDCancelAllAsync, executing, NULL, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __OSReboot.
s32 DVDConvertPathToEntrynum(u8 *pathPtr)
References __DVDLongFileNameFlag, CARD_MAX_MOUNT_STEP, currentDirectory, entryIsDir, FALSE, FstStringStart, isSame, nextDir, OSPanic, parentDir, stringOff, TRUE.
Referenced by DVDChangeDir, DVDOpen, DVDOpenDir.
BOOL DVDFastOpen(s32 entrynum, DVDFileInfo *fileInfo)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, DVD_STATE_END, entryIsDir, FALSE, fileLength, filePosition, DVDFileInfo::length, MaxEntryNum, NULL, DVDFileInfo::startAddr, DVDCommandBlock::state, TRUE.
BOOL DVDOpen(u8 *fileName, DVDFileInfo *fileInfo)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, DVD_STATE_END, DVDConvertPathToEntrynum, DVDGetCurrentDir, entryIsDir, FALSE, fileLength, filePosition, DVDFileInfo::length, NULL, OSReport, DVDFileInfo::startAddr, DVDCommandBlock::state, TRUE.
Referenced by DTKQueueTrack, LoadMemInfo, LoadTexPalette.
BOOL DVDClose(DVDFileInfo *fileInfo)
References CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, DVDCancel, TRUE.
Referenced by __DTKCallbackForFlush, DTKRemoveTrack, LoadMemInfo, LoadTexPalette.
BOOL DVDGetCurrentDir(u8 *path, u32 maxlen)
References CARD_MAX_MOUNT_STEP, currentDirectory, DVDConvertEntrynumToPath.
Referenced by DVDChangeDir, DVDOpen, DVDOpenDir.
BOOL DVDChangeDir(u8 *dirName)
References CARD_MAX_MOUNT_STEP, currentDirectory, DVDConvertPathToEntrynum, DVDGetCurrentDir, entryIsDir, FALSE, TRUE.
BOOL DVDReadAsyncPrio(DVDFileInfo *fileInfo, void *addr, s32 length, s32 offset, DVDCallback callback, s32 prio)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForReadAsync, DVD_MIN_TRANSFER_SIZE, DVDReadAbsAsyncPrio, OFFSET, OSPanic, DVDFileInfo::startAddr, TRUE.
s32 DVDReadPrio(DVDFileInfo *fileInfo, void *addr, s32 length, s32 offset, s32 prio)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForReadSync, DVD_MIN_TRANSFER_SIZE, DVDReadAbsAsyncPrio, OFFSET, OSDisableInterrupts, OSPanic, OSRestoreInterrupts, OSSleepThread, DVDFileInfo::startAddr.
Referenced by LoadMemInfo, LoadTexPalette.
BOOL DVDSeekAsyncPrio(DVDFileInfo *fileInfo, s32 offset, void(*callback)(s32, DVDFileInfo *), s32 prio)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForSeekAsync, DVDSeekAbsAsyncPrio, OSPanic, DVDFileInfo::startAddr, TRUE.
s32 DVDSeekPrio(DVDFileInfo *fileInfo, s32 offset, s32 prio)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForSeekSync, DVDSeekAbsAsyncPrio, DVDFileInfo::length, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, DVDFileInfo::startAddr.
s32 DVDGetFileInfoStatus(DVDFileInfo *fileInfo)
References DVDFileInfo::cb, DVDCommandBlock::state.
BOOL DVDOpenDir(u8 *dirName, DVDDir *dir)
References CARD_MAX_MOUNT_STEP, DVDConvertPathToEntrynum, DVDGetCurrentDir, entryIsDir, FALSE, nextDir, TRUE.
BOOL DVDReadDir(DVDDir *dir, DVDDirEntry *dirent)
References CARD_MAX_MOUNT_STEP, entryIsDir, FALSE, FstStringStart, nextDir, stringOff, TRUE.
BOOL DVDCloseDir(DVDDir *dir)
References TRUE.
void * DVDGetFSTLocation()
References BootInfo, OSBootInfo_s::FSTLocation.
BOOL DVDPrepareStreamAsync(DVDFileInfo *fileInfo, u32 length, u32 offset, DVDCallback callback)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForPrepareStreamAsync, DVDPrepareStreamAbsAsync, Is32KBAligned, DVDFileInfo::length, OSPanic, DVDFileInfo::startAddr.
Referenced by __DTKPrepareCurrentTrack, __DTKPrepareCurrentTrackPaused.
s32 DVDPrepareStream(DVDFileInfo *fileInfo, u32 length, u32 offset)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForPrepareStreamSync, DVD_RESULT_CANCELED, DVD_RESULT_FATAL_ERROR, DVD_STATE_CANCELED, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDPrepareStreamAbsAsync, FALSE, Is32KBAligned, DVDFileInfo::length, OSDisableInterrupts, OSPanic, OSRestoreInterrupts, OSSleepThread, DVDFileInfo::startAddr.
s32 DVDGetTransferredSize(DVDFileInfo *fileinfo)
References CARD_MAX_MOUNT_STEP, cb, DVD_STATE_BUSY, DVD_STATE_CANCELED, DVD_STATE_COVER_CLOSED, DVD_STATE_COVER_OPEN, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_MOTOR_STOPPED, DVD_STATE_NO_DISK, DVD_STATE_WAITING, DVD_STATE_WRONG_DISK, FALSE, DVDCommandBlock::transferredSize.
int DVDPrepareStreamAbsAsync(DVDCommandBlock *block, u32 length, u32 offset, void(*callback)(s32, DVDCommandBlock *))
0x14
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_INITSTREAM, issueCommand.