dvd.c
ERROR_FATAL
ERROR_RETRY
ERROR_RETRY_INTERNALLY
DVDCommandBlock DummyCommandBlock
Referenced by cbForStateBusy, cbForStateError, cbForStateReadingFST, CheckCancel, DVDCheckDisk, DVDGetDriveStatus, stateCoverClosed, stateReady, stateTimeout.
OSAlarm ResetAlarm
Referenced by stateCoverClosed.
BOOL autoInvalidation
Referenced by DVDSetAutoInvalidation, issueCommand.
DVDCommandBlock* executing
Referenced by __DVDPrepareResetAsync, AlarmHandler, CategorizeError, cbForStateBusy, cbForStateCheckID1, cbForStateCheckID2, cbForStateCheckID3, cbForStateCoverClosed, cbForStateError, cbForStateGettingError, cbForStateGoToRetry, cbForStateMotorStopped, cbForStateReadingFST, cbForUnrecoveredError, cbForUnrecoveredErrorRetry, CheckCancel, DVDCancelAllAsync, DVDCheckDisk, DVDGetDriveStatus, DVDPause, issueCommand, stateBusy, stateCheckID, stateCoverClosed, stateReady, stateTimeout.
void* tmp
Referenced by __AIDHandler, __ARHandler, __DSPHandler, ARAlloc, calcFbbs, DSPAssertInt, DSPHalt, DSPInit, DSPReset, DSPUnhalt, DummyLen, GetInitVal, GXGetTexObjLODAll, GXGetTexObjLODBias, MTXFrustum, MTXLightFrustum, MTXLightOrtho, MTXOrtho, MTXPerspective, PopWaitingQueuePrio.
DVDDiskID* currID
Referenced by DVDInit, stateCheckID, stateCheckID3.
OSBootInfo* bootInfo
Referenced by __fstLoad, DVDChangeDiskAsync, DVDInit, stateReadingFST.
volatile BOOL PauseFlag
Referenced by DVDPause, DVDResume, issueCommand, stateReady.
volatile BOOL PausingFlag
Referenced by DVDCheckDisk, DVDGetDriveStatus, DVDPause, DVDResume, stateReady.
BOOL AutoFinishing
Referenced by cbForStateBusy, stateBusy.
volatile BOOL FatalErrorFlag
Referenced by cbForStateError, DVDCheckDisk, DVDGetDriveStatus, stateReady, stateTimeout.
vu32 CurrCommand
Referenced by cbForStateBusy, cbForStateCoverClosed, cbForStateGoToRetry, stateCheckID, stateCoverClosed, stateReady.
vu32 Canceling
Referenced by __DVDPrepareResetAsync, cbForStateBusy, cbForStateError, CheckCancel, DVDCancelAsync, stateTimeout.
DVDCommandBlock* CancelingCommandBlock
void(* CancelCallback) (s32, DVDCommandBlock *))(s32, DVDCommandBlock *)
Referenced by __DVDPrepareResetAsync, cbForStateBusy, cbForStateError, CheckCancel, DVDCancelAsync, stateTimeout.
vu32 ResumeFromHere
Referenced by CheckCancel, DVDCancelAsync, DVDReset, stateReady.
vu32 CancelLastError
Referenced by stateReady.
u32 LastError
Referenced by CategorizeError.
vs32 NumInternalRetry
Referenced by CategorizeError, cbForStateBusy, cbForStateCheckID1, cbForStateCheckID2, cbForStateCheckID3, cbForStateCoverClosed, cbForStateGoToRetry, cbForStateReadingFST.
BOOL ResetRequired
Referenced by cbForStateBusy, cbForStateGoToRetry, DVDReset, DVDResetRequired.
BOOL CancelAllSyncComplete
Referenced by cbForCancelAllSync, DVDCancelAll.
vu32 ResetCount
BOOL FirstTimeInBootrom
Referenced by DVDInit.
s32 ResultForSyncCommand
Referenced by cbForGetStreamErrorStatusSync, cbForGetStreamPlayAddrSync, cbForGetStreamStartAddrSync, cbForInquirySync, cbForStopStreamAtEndSync, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInquiry, DVDStopStreamAtEnd.
BOOL DVDInitialized
Referenced by DVDInit.
void(* LastState) (DVDCommandBlock *))(DVDCommandBlock *)
Referenced by AlarmHandler, stateBusy, stateCheckID, stateReadingFST.
static u16 *tmpBuffer[32] ALIGN(32)
static void stateReadingFST()
References bootInfo, CARD_MAX_MOUNT_STEP, cbForStateReadingFST, DVDLowRead, OSBootInfo_s::FSTLocation, LastState, OSRoundUp32B, stateReadingFST.
Referenced by cbForStateCheckID2, stateReadingFST.
static void cbForStateReadingFST(u32 intType)
References CARD_MAX_MOUNT_STEP, DummyCommandBlock, DVD_INTTYPE_CVR, DVD_INTTYPE_DE, DVD_INTTYPE_TIMEOUT, DVD_STATE_END, DVD_STATE_FATAL_ERROR, executing, NumInternalRetry, DVDCommandBlock::state, stateGettingError, stateReady, stateTimeout.
Referenced by stateReadingFST.
static void cbForStateError(u32 intType)
References CancelCallback, Canceling, CARD_MAX_MOUNT_STEP, DummyCommandBlock, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, executing, FALSE, FatalErrorFlag, DVDCommandBlock::state, stateReady, stateTimeout, TRUE.
Referenced by cbForStateBusy, cbForStateCheckID1, cbForStateCheckID2, cbForStateCheckID3, cbForStateCoverClosed, cbForStateGettingError, cbForStateGoToRetry, cbForUnrecoveredError, cbForUnrecoveredErrorRetry, stateError.
static void stateError(u32 error)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, DVDLowStopMotor.
Referenced by cbForStateBusy, cbForStateGettingError, cbForStateGoToRetry, cbForUnrecoveredErrorRetry, stateReady.
static void stateTimeout()
References __DVDStoreErrorCode, CancelCallback, Canceling, CARD_MAX_MOUNT_STEP, DummyCommandBlock, DVD_TIMEOUT_ERROR_CODE, DVDReset, executing, FatalErrorFlag, stateReady, TRUE.
Referenced by cbForStateError, cbForStateReadingFST.
static void stateGettingError()
References cbForStateGettingError, DVDLowRequestError.
Referenced by cbForStateBusy, cbForStateCheckID2, cbForStateCoverClosed, cbForStateReadingFST.
static u32 CategorizeError(u32 error)
References CARD_MAX_MOUNT_STEP, DVDCommandBlock::command, executing, LastError, NumInternalRetry.
Referenced by cbForStateGettingError.
static BOOL CheckCancel(u32 resume)
References CancelCallback, Canceling, CARD_MAX_MOUNT_STEP, DummyCommandBlock, executing, FALSE, ResumeFromHere, DVDCommandBlock::state, stateReady, TRUE.
Referenced by cbForStateBusy, cbForStateCheckID1, cbForStateCheckID3, cbForStateGettingError, cbForStateGoToRetry.
static void cbForStateGettingError(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, CategorizeError, cbForStateError, cbForUnrecoveredError, CheckCancel, DI_IMMBUF, DVD_DE_INT_ERROR_CODE, DVD_INTTYPE_DE, DVD_INTTYPE_TC, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_TIMEOUT_ERROR_CODE, DVDLowSeek, DVDReset, ERROR_FATAL, ERROR_RETRY, ERROR_RETRY_INTERNALLY, executing, DVDCommandBlock::offset, DVDCommandBlock::state, stateCoverClosed, stateError, stateGoToRetry, stateMotorStopped, status.
Referenced by cbForStateCheckID3, stateGettingError.
static void cbForUnrecoveredError(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, cbForUnrecoveredErrorRetry, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_TIMEOUT_ERROR_CODE, DVDLowRequestError, DVDReset, executing, DVDCommandBlock::state, stateGoToRetry.
Referenced by cbForStateGettingError.
static void cbForUnrecoveredErrorRetry(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, DI_IMMBUF, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_TIMEOUT_ERROR_CODE, DVDReset, executing, DVDCommandBlock::state, stateError.
Referenced by cbForUnrecoveredError.
static void stateGoToRetry()
References cbForStateGoToRetry, DVDLowStopMotor.
Referenced by cbForStateGettingError, cbForUnrecoveredError.
static void cbForStateGoToRetry(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, CheckCancel, CurrCommand, DVD_COMMAND_AUDIO_BUFFER_CONFIG, DVD_COMMAND_BS_CHANGE_DISK, DVD_COMMAND_BSREAD, DVD_COMMAND_READID, DVD_DE_INT_ERROR_CODE, DVD_INTTYPE_TC, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_STATE_RETRY, DVD_TIMEOUT_ERROR_CODE, DVDReset, executing, FALSE, NumInternalRetry, ResetRequired, DVDCommandBlock::state, stateError, stateMotorStopped, TRUE.
Referenced by stateGoToRetry.
static void stateCheckID()
References CARD_MAX_MOUNT_STEP, cbForStateCheckID1, CurrCommand, currID, DCInvalidateRange, DVD_COMMAND_CHANGE_DISK, DVD_STATE_BUSY, DVDLowStopMotor, executing, FALSE, DVDCommandBlock::id, LastState, DVDCommandBlock::state, stateCheckID2, stateCheckID3.
Referenced by cbForStateCoverClosed.
static void stateCheckID3(DVDCommandBlock *block)
References cbForStateCheckID3, currID, DVDLowAudioBufferConfig, DVDDiskID::streaming.
Referenced by stateCheckID.
static void stateCheckID2(DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, cbForStateCheckID2, DVDLowRead.
Referenced by stateCheckID.
static void cbForStateCheckID1(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, CheckCancel, DVD_INTTYPE_DE, DVD_INTTYPE_TC, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_STATE_WRONG_DISK, DVD_TIMEOUT_ERROR_CODE, DVDLowStopMotor, DVDReset, executing, NumInternalRetry, DVDCommandBlock::state, stateMotorStopped, TRUE.
Referenced by stateCheckID.
static void cbForStateCheckID2(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, DVD_INTTYPE_CVR, DVD_INTTYPE_DE, DVD_INTTYPE_TC, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_TIMEOUT_ERROR_CODE, DVDReset, executing, NumInternalRetry, DVDCommandBlock::state, stateGettingError, stateReadingFST.
Referenced by stateCheckID2.
static void cbForStateCheckID3(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, cbForStateGettingError, CheckCancel, DVD_INTTYPE_TC, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_TIMEOUT_ERROR_CODE, DVDLowRequestError, DVDReset, executing, FALSE, NumInternalRetry, DVDCommandBlock::state, stateBusy.
Referenced by stateCheckID3.
static void stateCoverClosed()
References __DVDClearWaitingQueue, AlarmHandler, DVDCommandBlock::callback, CARD_MAX_MOUNT_STEP, CurrCommand, DummyCommandBlock, DVD_COMMAND_AUDIO_BUFFER_CONFIG, DVD_COMMAND_BS_CHANGE_DISK, DVD_COMMAND_BSREAD, DVD_COMMAND_READID, DVDReset, executing, OSCreateAlarm, OSMillisecondsToTicks, OSSetAlarm, ResetAlarm, stateReady.
Referenced by cbForStateGettingError, cbForStateMotorStopped, stateReady.
static void stateCoverClosed_CMD(DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, cbForStateCoverClosed, DVDLowReadDiskID.
Referenced by AlarmHandler.
static void cbForStateCoverClosed(u32 intType)
References __DVDStoreErrorCode, CARD_MAX_MOUNT_STEP, cbForStateError, CurrCommand, DVD_COMMAND_CHANGE_DISK, DVD_COMMAND_READ, DVD_COMMAND_SEEK, DVD_INTTYPE_CVR, DVD_INTTYPE_DE, DVD_INTTYPE_TC, DVD_INTTYPE_TIMEOUT, DVD_STATE_FATAL_ERROR, DVD_TIMEOUT_ERROR_CODE, DVDReset, executing, NumInternalRetry, DVDCommandBlock::state, stateCheckID, stateGettingError.
Referenced by stateCoverClosed_CMD.
static void stateMotorStopped()
References cbForStateMotorStopped, DVDLowWaitCoverClose.
Referenced by cbForStateBusy, cbForStateCheckID1, cbForStateGettingError, cbForStateGoToRetry, stateReady.
static void cbForStateMotorStopped(u32 intType)
References CARD_MAX_MOUNT_STEP, DI_CVR, DVD_INTTYPE_CVR, DVD_STATE_COVER_CLOSED, executing, DVDCommandBlock::state, stateCoverClosed.
Referenced by DVDCancelAsync, stateMotorStopped.
static void stateReady()
References __DVDCheckWaitingQueue, __DVDPopWaitingQueue, CancelLastError, CARD_MAX_MOUNT_STEP, DVDCommandBlock::command, CurrCommand, DummyCommandBlock, DVD_STATE_BUSY, DVD_STATE_COVER_CLOSED, DVD_STATE_COVER_OPEN, DVD_STATE_FATAL_ERROR, DVD_STATE_MOTOR_STOPPED, DVD_STATE_NO_DISK, DVD_STATE_RETRY, DVD_STATE_WRONG_DISK, executing, FatalErrorFlag, NULL, PauseFlag, PausingFlag, ResumeFromHere, DVDCommandBlock::state, stateBusy, stateCoverClosed, stateError, stateMotorStopped, stateReady, TRUE.
Referenced by cbForStateBusy, cbForStateError, cbForStateReadingFST, CheckCancel, DVDCancelAsync, DVDResume, issueCommand, stateCoverClosed, stateReady, stateTimeout.
static void stateBusy(DVDCommandBlock *block)
References AutoFinishing, CARD_MAX_MOUNT_STEP, cbForStateBusy, DVDCommandBlock::currTransferSize, DI_CVR, DVD_COMMAND_AUDIO_BUFFER_CONFIG, DVD_COMMAND_BS_CHANGE_DISK, DVD_COMMAND_BSREAD, DVD_COMMAND_CANCELSTREAM, DVD_COMMAND_CHANGE_DISK, DVD_COMMAND_INITSTREAM, DVD_COMMAND_INQUIRY, DVD_COMMAND_READ, DVD_COMMAND_READID, DVD_COMMAND_REQUEST_AUDIO_ERROR, DVD_COMMAND_REQUEST_LENGTH, DVD_COMMAND_REQUEST_PLAY_ADDR, DVD_COMMAND_REQUEST_START_ADDR, DVD_COMMAND_SEEK, DVD_COMMAND_STOP_STREAM_AT_END, DVDLowAudioBufferConfig, DVDLowAudioStream, DVDLowInquiry, DVDLowRead, DVDLowReadDiskID, DVDLowRequestAudioStatus, DVDLowSeek, DVDLowStopMotor, executing, LastState, stateBusy.
Referenced by cbForStateBusy, cbForStateCheckID3, stateBusy, stateReady.
static void cbForStateBusy(u32 intType)
References __DVDStoreErrorCode, AutoFinishing, CancelCallback, Canceling, CARD_MAX_MOUNT_STEP, cbForStateBusy, cbForStateError, CheckCancel, CurrCommand, DVDCommandBlock::currTransferSize, DI_IMMBUF, DI_LENGTH, DummyCommandBlock, DVD_COMMAND_BS_CHANGE_DISK, DVD_COMMAND_BSREAD, DVD_COMMAND_CHANGE_DISK, DVD_COMMAND_INITSTREAM, DVD_COMMAND_INQUIRY, DVD_COMMAND_READ, DVD_COMMAND_READID, DVD_COMMAND_REQUEST_AUDIO_ERROR, DVD_COMMAND_REQUEST_LENGTH, DVD_COMMAND_REQUEST_PLAY_ADDR, DVD_COMMAND_REQUEST_START_ADDR, DVD_DE_INT_ERROR_CODE, DVD_INTTYPE_CVR, DVD_INTTYPE_DE, DVD_INTTYPE_TC, DVD_INTTYPE_TIMEOUT, DVD_STATE_CANCELED, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_IGNORED, DVD_STATE_MOTOR_STOPPED, DVD_TIMEOUT_ERROR_CODE, DVDLowAudioStream, DVDReset, executing, DVDCommandBlock::length, NumInternalRetry, DVDCommandBlock::offset, ResetRequired, DVDCommandBlock::state, stateBusy, stateError, stateGettingError, stateMotorStopped, stateReady, DVDCommandBlock::transferredSize.
Referenced by cbForStateBusy, stateBusy.
static BOOL issueCommand(s32 prio, DVDCommandBlock *block)
References __DVDIsBlockInWaitingQueue, __DVDPushWaitingQueue, autoInvalidation, CARD_MAX_MOUNT_STEP, DCInvalidateRange, DVD_COMMAND_BSREAD, DVD_COMMAND_INQUIRY, DVD_COMMAND_READ, DVD_COMMAND_READID, DVD_STATE_WAITING, executing, FALSE, NULL, OSDisableInterrupts, OSRestoreInterrupts, PauseFlag, DVDCommandBlock::state, stateReady.
Referenced by __DVDAudioBufferConfig, DVDCancelStreamAsync, DVDChangeDiskAsync, DVDChangeDiskAsyncForBS, DVDGetStreamErrorStatusAsync, DVDGetStreamLengthAsync, DVDGetStreamPlayAddrAsync, DVDGetStreamStartAddrAsync, DVDInquiryAsync, DVDPrepareStreamAbsAsync, DVDReadAbsAsyncForBS, DVDReadAbsAsyncPrio, DVDReadDiskID, DVDSeekAbsAsyncPrio, DVDStopStreamAtEndAsync.
static void cbForCancelStreamSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, OSWakeupThread.
Referenced by DVDCancelStream.
static void cbForStopStreamAtEndSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread, ResultForSyncCommand.
Referenced by DVDStopStreamAtEnd.
static void cbForGetStreamErrorStatusSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread, ResultForSyncCommand.
Referenced by DVDGetStreamErrorStatus.
static void cbForGetStreamPlayAddrSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread, ResultForSyncCommand.
Referenced by DVDGetStreamPlayAddr.
static void cbForGetStreamStartAddrSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread, ResultForSyncCommand.
Referenced by DVDGetStreamStartAddr.
static void cbForGetStreamLengthSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, OSWakeupThread.
Referenced by DVDGetStreamLength.
static void cbForChangeDiskSync()
References __DVDThreadQueue, OSWakeupThread.
Referenced by DVDChangeDisk.
static void cbForInquirySync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread, ResultForSyncCommand.
Referenced by DVDInquiry.
static void cbForCancelSync()
References __DVDThreadQueue, OSWakeupThread.
Referenced by DVDCancel.
static void cbForCancelAllSync()
References __DVDThreadQueue, CancelAllSyncComplete, OSWakeupThread.
Referenced by DVDCancelAll.
void DVDInit()
References __DVDClearWaitingQueue, __DVDFSInit, __DVDInitWA, __DVDInterruptHandler, __DVDThreadQueue, __fstLoad, __OSSetInterruptHandler, __OSUnmaskInterrupts, bootInfo, CARD_MAX_MOUNT_STEP, currID, DI_CVR, DI_SR, OSBootInfo_s::DVDDiskID, DVDInitialized, FirstTimeInBootrom, OSBootInfo_s::magic, OS_BOOTINFO_MAGIC, OS_BOOTINFO_MAGIC_JTAG, OSInitAlarm, OSInitThreadQueue, OSPhysicalToCached, OSReport.
Referenced by __OSReboot, DEMOInit.
static void AlarmHandler()
References CARD_MAX_MOUNT_STEP, DCInvalidateRange, DVDReset, executing, LastState, stateCoverClosed_CMD.
Referenced by SITransfer, stateCoverClosed, WaitBeforeRead.
BOOL DVDReadAbsAsyncPrio(DVDCommandBlock *block, void *addr, s32 length, s32 offset, void(*callback)(s32, DVDCommandBlock *), s32 prio)
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_READ, issueCommand, OFFSET.
BOOL DVDSeekAbsAsyncPrio(DVDCommandBlock *block, s32 offset, void(*callback)(long, DVDCommandBlock *), s32 prio)
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_SEEK, issueCommand.
BOOL DVDReadAbsAsyncForBS(DVDCommandBlock *block, void *addr, s32 length, s32 offset, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_BSREAD, issueCommand, OFFSET.
BOOL DVDReadDiskID(DVDCommandBlock *block, DVDDiskID *diskID, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_READID, issueCommand, OFFSET.
BOOL DVDPrepareStreamAbsAsync(DVDCommandBlock *block, u32 length, u32 offset, void(*callback)(s32, DVDCommandBlock *))
0x14
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_INITSTREAM, issueCommand.
BOOL DVDCancelStreamAsync(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_CANCELSTREAM, issueCommand.
Referenced by DVDCancelStream.
s32 DVDCancelStream(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForCancelStreamSync, DVD_STATE_CANCELED, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDCancelStreamAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, TRUE.
BOOL DVDStopStreamAtEndAsync(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_STOP_STREAM_AT_END, issueCommand.
Referenced by DVDStopStreamAtEnd.
s32 DVDStopStreamAtEnd(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForStopStreamAtEndSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDStopStreamAtEndAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamErrorStatusAsync(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_REQUEST_AUDIO_ERROR, issueCommand.
Referenced by DVDGetStreamErrorStatus.
s32 DVDGetStreamErrorStatus(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamErrorStatusSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamErrorStatusAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamPlayAddrAsync(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_REQUEST_PLAY_ADDR, issueCommand.
Referenced by DVDGetStreamPlayAddr.
s32 DVDGetStreamPlayAddr(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamPlayAddrSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamPlayAddrAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamStartAddrAsync(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_REQUEST_START_ADDR, issueCommand.
Referenced by DVDGetStreamStartAddr.
s32 DVDGetStreamStartAddr(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamStartAddrSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamStartAddrAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
BOOL DVDGetStreamLengthAsync(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_REQUEST_LENGTH, issueCommand.
Referenced by DVDGetStreamLength.
s32 DVDGetStreamLength(DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForGetStreamLengthSync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDGetStreamLengthAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
void __DVDAudioBufferConfig(DVDCommandBlock *block, u32 enable, u32 size, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_AUDIO_BUFFER_CONFIG, issueCommand, size.
BOOL DVDChangeDiskAsyncForBS(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, DVD_COMMAND_BS_CHANGE_DISK, issueCommand.
BOOL DVDChangeDiskAsync(DVDCommandBlock *block, DVDDiskID *id, void(*callback)(s32, DVDCommandBlock *))
References bootInfo, CARD_MAX_MOUNT_STEP, DCInvalidateRange, DVD_COMMAND_CHANGE_DISK, OSBootInfo_s::FSTLocation, OSBootInfo_s::FSTMaxLength, issueCommand.
Referenced by DVDChangeDisk.
s32 DVDChangeDisk(DVDCommandBlock *block, DVDDiskID *id)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForChangeDiskSync, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDChangeDiskAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread.
BOOL DVDInquiryAsync(DVDCommandBlock *block, struct DVDDriveInfo *info, void(*callback)(s32, DVDCommandBlock *))
References CARD_MAX_MOUNT_STEP, issueCommand, OFFSET.
Referenced by DVDInquiry.
s32 DVDInquiry(DVDCommandBlock *block, struct DVDDriveInfo *info)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForInquirySync, DVD_STATE_BUSY, DVD_STATE_WAITING, DVDInquiryAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, ResultForSyncCommand.
void DVDReset()
References CARD_MAX_MOUNT_STEP, DI_CVR, DI_SR, DVDLowReset, ResetRequired, ResumeFromHere.
Referenced by __fstLoad, AlarmHandler, cb, cbForStateBusy, cbForStateCheckID1, cbForStateCheckID2, cbForStateCheckID3, cbForStateCoverClosed, cbForStateGettingError, cbForStateGoToRetry, cbForUnrecoveredError, cbForUnrecoveredErrorRetry, stateCoverClosed, stateTimeout.
BOOL DVDResetRequired()
References ResetRequired.
s32 DVDGetCommandBlockStatus(DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, DVD_STATE_BUSY, DVD_STATE_COVER_CLOSED, OSDisableInterrupts, OSRestoreInterrupts, status.
Referenced by DVDGetDriveStatus.
s32 DVDGetDriveStatus()
References CARD_MAX_MOUNT_STEP, DummyCommandBlock, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_PAUSING, DVDGetCommandBlockStatus, executing, FALSE, FatalErrorFlag, NULL, OSDisableInterrupts, OSRestoreInterrupts, PausingFlag.
Referenced by __fstLoad.
int DVDSetAutoInvalidation(BOOL autoInval)
References autoInvalidation, CARD_MAX_MOUNT_STEP, prev.
void DVDPause()
References executing, NULL, OSDisableInterrupts, OSRestoreInterrupts, PauseFlag, PausingFlag.
Referenced by DVDCancelAllAsync.
void DVDResume()
References OSDisableInterrupts, OSRestoreInterrupts, PauseFlag, PausingFlag, stateReady.
Referenced by DVDCancelAllAsync.
BOOL DVDCancelAsync(DVDCommandBlock *block, void(*callback)(s32, DVDCommandBlock *))
References __DVDDequeueWaitingQueue, CancelCallback, Canceling, CARD_MAX_MOUNT_STEP, cbForStateMotorStopped, DVD_COMMAND_AUDIO_BUFFER_CONFIG, DVD_COMMAND_BS_CHANGE_DISK, DVD_COMMAND_BSREAD, DVD_COMMAND_READ, DVD_COMMAND_READID, DVD_STATE_BUSY, DVD_STATE_CANCELED, DVD_STATE_COVER_CLOSED, DVD_STATE_COVER_OPEN, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_MOTOR_STOPPED, DVD_STATE_NO_DISK, DVD_STATE_RETRY, DVD_STATE_WAITING, DVD_STATE_WRONG_DISK, DVDLowBreak, DVDLowClearCallback, FALSE, OSDisableInterrupts, OSRestoreInterrupts, ResumeFromHere, stateReady, TRUE.
Referenced by DVDCancel, DVDCancelAllAsync.
s32 DVDCancel(volatile DVDCommandBlock *block)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, cbForCancelSync, DVD_COMMAND_AUDIO_BUFFER_CONFIG, DVD_COMMAND_BS_CHANGE_DISK, DVD_COMMAND_BSREAD, DVD_COMMAND_READID, DVD_STATE_CANCELED, DVD_STATE_COVER_CLOSED, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDCancelAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread.
Referenced by DVDClose.
int DVDCancelAllAsync(void(*callback)(s32, DVDCommandBlock *))
References __DVDPopWaitingQueue, CARD_MAX_MOUNT_STEP, DVDCancelAsync, DVDPause, DVDResume, executing, NULL, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __DVDPrepareResetAsync, DVDCancelAll.
s32 DVDCancelAll()
References __DVDThreadQueue, CancelAllSyncComplete, cbForCancelAllSync, DVDCancelAllAsync, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread.
DVDDiskID * DVDGetCurrentDiskID()
References OSPhysicalToCached.
Referenced by AudioBufferOn.
BOOL DVDCheckDisk()
References CARD_MAX_MOUNT_STEP, DI_CVR, DummyCommandBlock, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_PAUSING, executing, FALSE, FatalErrorFlag, NULL, OSDisableInterrupts, OSRestoreInterrupts, PausingFlag, DVDCommandBlock::state, TRUE.
Referenced by __OSReboot.
void __DVDPrepareResetAsync(DVDCBCallback cb)
References __DVDClearWaitingQueue, DVDCommandBlock::callback, CancelCallback, Canceling, cb, DVDCancelAllAsync, executing, NULL, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __OSReboot.