dvd_private.h
DVD_DE_INT_ERROR_CODE
DVD_TIMEOUT_ERROR_CODE
OSThreadQueue __DVDThreadQueue
Referenced by cbForCancelAllSync, cbForCancelStreamSync, cbForCancelSync, cbForChangeDiskSync, cbForGetStreamErrorStatusSync, cbForGetStreamLengthSync, cbForGetStreamPlayAddrSync, cbForGetStreamStartAddrSync, cbForInquirySync, cbForPrepareStreamSync, cbForReadSync, cbForSeekSync, cbForStopStreamAtEndSync, DVDCancel, DVDCancelAll, DVDCancelStream, DVDChangeDisk, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInit, DVDInquiry, DVDPrepareStream, DVDReadPrio, DVDSeekPrio, DVDStopStreamAtEnd.
u32 __DVDLongFileNameFlag
void __DVDAudioBufferConfig(DVDCommandBlock *block, u32 enable, u32 size, void(*callback)(s32, struct DVDCommandBlock *))
void __DVDInitWA()
References __DVDLowSetWAType, DVDCommand::command, CommandList, NextCommandNumber, OSInitAlarm.
Referenced by DVDInit.
void __DVDFSInit()
References BootInfo, OSBootInfo_s::FSTLocation, FstStart, FstStringStart, MaxEntryNum, FSTEntry::nextEntryOrLength, OSPhysicalToCached.
Referenced by DVDInit.
void __DVDLowSetWAType(u32 type, s32 seekLoc)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, WorkAroundSeekLocation, WorkAroundType.
Referenced by __DVDInitWA.
BOOL __DVDLowTestAlarm(const OSAlarm *alarm)
References AlarmForBreak, AlarmForTimeout, FALSE, TRUE.
void __DVDInterruptHandler(s16 unused, OSContext *context)
References __OSGetSystemTime, DVDBuffer::addr, AlarmForBreak, AlarmForTimeout, Breaking, Callback, CARD_MAX_MOUNT_STEP, cb, DVDCommand::command, CommandList, Curr, FALSE, FirstRead, LastCommandWasRead, LastReadFinished, LastResetEnd, DVDBuffer::length, NextCommandNumber, NULL, DVDBuffer::offset, OSCancelAlarm, OSClearContext, OSMillisecondsToTicks, OSSetCurrentContext, Prev, ProcessNextCommand, ResetCoverCallback, ResetOccurred, WaitingCoverClose.
Referenced by DVDInit.
void __DVDClearWaitingQueue()
References CARD_MAX_MOUNT_STEP, DVDCommandBlock::next, next, DVDCommandBlock::prev, WaitingQueue.
Referenced by __DVDPrepareResetAsync, DVDInit, stateCoverClosed.
BOOL __DVDPushWaitingQueue(s32 prio, struct DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, DVDCommandBlock::next, OSDisableInterrupts, OSRestoreInterrupts, DVDCommandBlock::prev, TRUE, WaitingQueue.
Referenced by issueCommand.
struct DVDCommandBlock * __DVDPopWaitingQueue()
References CARD_MAX_MOUNT_STEP, NULL, OSDisableInterrupts, OSRestoreInterrupts, PopWaitingQueuePrio, WaitingQueue.
Referenced by DVDCancelAllAsync, stateReady.
BOOL __DVDCheckWaitingQueue()
References CARD_MAX_MOUNT_STEP, FALSE, OSDisableInterrupts, OSRestoreInterrupts, TRUE, WaitingQueue.
Referenced by stateReady.
BOOL __DVDDequeueWaitingQueue(struct DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, FALSE, DVDCommandBlock::next, next, NULL, OSDisableInterrupts, OSRestoreInterrupts, DVDCommandBlock::prev, prev, TRUE.
Referenced by DVDCancelAsync.
BOOL __DVDIsBlockInWaitingQueue(struct DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, FALSE, DVDCommandBlock::next, TRUE, WaitingQueue.
Referenced by issueCommand.
void __fstLoad()
References bb2, bb2Buf, bootInfo, CARD_MAX_MOUNT_STEP, cb, DVDDiskID::company, DVDDiskID::diskNumber, DVD_STATE_BUSY, DVD_STATE_COVER_CLOSED, DVD_STATE_COVER_OPEN, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_MOTOR_STOPPED, DVD_STATE_NO_DISK, DVD_STATE_WAITING, OSBootInfo_s::DVDDiskID, DVDGetDriveStatus, DVDReadDiskID, DVDReset, DVDBB2::FSTAddress, OSBootInfo_s::FSTLocation, DVDBB2::FSTMaxLength, OSBootInfo_s::FSTMaxLength, DVDDiskID::gameName, DVDDiskID::gameVersion, idTmp, OSGetArenaHi, OSPhysicalToCached, OSReport, OSRoundUp32B, OSSetArenaHi, DVDDiskID::streaming.
Referenced by DVDInit.
void __DVDStoreErrorCode(u32 code)
References __OSLockSramEx, __OSUnlockSramEx, CARD_MAX_MOUNT_STEP, Convert, OSSramEx::dvdErrorCode, TRUE.
Referenced by cbForStateBusy, cbForStateCheckID1, cbForStateCheckID2, cbForStateCheckID3, cbForStateCoverClosed, cbForStateGettingError, cbForStateGoToRetry, cbForUnrecoveredError, cbForUnrecoveredErrorRetry, stateError, stateTimeout.