dvderror.c
u32 ErrorTable[][]
Referenced by ErrorCode2Num.
u8 ErrorCode2Num(u32 errorCode)
References CARD_MAX_MOUNT_STEP, ErrorTable.
Referenced by Convert.
u8 Convert(u32 error)
References CARD_MAX_MOUNT_STEP, ErrorCode2Num.
Referenced by __DVDStoreErrorCode.
void __DVDStoreErrorCode(u32 error)
References __OSLockSramEx, __OSUnlockSramEx, CARD_MAX_MOUNT_STEP, Convert, OSSramEx::dvdErrorCode, TRUE.
Referenced by cbForStateBusy, cbForStateCheckID1, cbForStateCheckID2, cbForStateCheckID3, cbForStateCoverClosed, cbForStateGettingError, cbForStateGoToRetry, cbForUnrecoveredError, cbForUnrecoveredErrorRetry, stateError, stateTimeout.