dvdfs.c
entryIsDir
stringOff
parentDir
nextDir
filePosition
fileLength
RoundUp32KB
Is32KBAligned
typedef struct FSTEntry FSTEntry
OSBootInfo* BootInfo
Referenced by __DVDFSInit, DVDGetFSTLocation, OSGetPhysicalMemSize.
FSTEntry* FstStart
Referenced by __DVDFSInit.
u8* FstStringStart
Referenced by __DVDFSInit, DVDConvertPathToEntrynum, DVDReadDir, entryToPath.
u32 MaxEntryNum
Referenced by __DVDFSInit, DVDConvertEntrynumToPath, DVDFastOpen.
u32 currentDirectory
Referenced by DVDChangeDir, DVDConvertPathToEntrynum, DVDGetCurrentDir.
OSThreadQueue __DVDThreadQueue
Referenced by cbForCancelAllSync, cbForCancelStreamSync, cbForCancelSync, cbForChangeDiskSync, cbForGetStreamErrorStatusSync, cbForGetStreamLengthSync, cbForGetStreamPlayAddrSync, cbForGetStreamStartAddrSync, cbForInquirySync, cbForPrepareStreamSync, cbForReadSync, cbForSeekSync, cbForStopStreamAtEndSync, DVDCancel, DVDCancelAll, DVDCancelStream, DVDChangeDisk, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInit, DVDInquiry, DVDPrepareStream, DVDReadPrio, DVDSeekPrio, DVDStopStreamAtEnd.
u32 __DVDLongFileNameFlag
Referenced by DVDConvertPathToEntrynum, OSInit.
static BOOL isSame(const u8 *path, const u8 *string)
References CARD_MAX_MOUNT_STEP, FALSE, TRUE.
Referenced by DVDConvertPathToEntrynum.
static u32 myStrncpy(u8 *dest, u8 *src, u32 maxlen)
References CARD_MAX_MOUNT_STEP, src.
Referenced by entryToPath.
static u32 entryToPath(u32 entry, u8 *path, u32 maxlen)
References CARD_MAX_MOUNT_STEP, entryToPath, FALSE, FstStringStart, myStrncpy, parentDir, stringOff.
Referenced by DVDConvertEntrynumToPath, entryToPath.
static BOOL DVDConvertEntrynumToPath(s32 entrynum, u8 *path, u32 maxlen)
References CARD_MAX_MOUNT_STEP, entryIsDir, entryToPath, FALSE, MaxEntryNum, TRUE.
Referenced by DVDGetCurrentDir.
static void cbForReadAsync(s32 result, DVDCommandBlock *block)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cb.
Referenced by DVDReadAsyncPrio.
static void cbForReadSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread.
Referenced by DVDReadPrio.
static void cbForSeekAsync(s32 result, DVDCommandBlock *block)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb.
Referenced by DVDSeekAsyncPrio.
static void cbForSeekSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread.
Referenced by DVDSeekPrio.
static void cbForPrepareStreamAsync(s32 result, DVDCommandBlock *block)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cb.
Referenced by DVDPrepareStreamAsync.
static void cbForPrepareStreamSync(s32 result, DVDCommandBlock *block)
References __DVDThreadQueue, OSWakeupThread.
Referenced by DVDPrepareStream.
void __DVDFSInit()
References BootInfo, OSBootInfo_s::FSTLocation, FstStart, FstStringStart, MaxEntryNum, FSTEntry::nextEntryOrLength, OSPhysicalToCached.
Referenced by DVDInit.
s32 DVDConvertPathToEntrynum(u8 *pathPtr)
References __DVDLongFileNameFlag, CARD_MAX_MOUNT_STEP, currentDirectory, entryIsDir, FALSE, FstStringStart, isSame, nextDir, OSPanic, parentDir, stringOff, TRUE.
Referenced by DVDChangeDir, DVDOpen, DVDOpenDir.
BOOL DVDFastOpen(s32 entrynum, DVDFileInfo *fileInfo)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, DVD_STATE_END, entryIsDir, FALSE, fileLength, filePosition, DVDFileInfo::length, MaxEntryNum, NULL, DVDFileInfo::startAddr, DVDCommandBlock::state, TRUE.
BOOL DVDOpen(u8 *fileName, DVDFileInfo *fileInfo)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, DVD_STATE_END, DVDConvertPathToEntrynum, DVDGetCurrentDir, entryIsDir, FALSE, fileLength, filePosition, DVDFileInfo::length, NULL, OSReport, DVDFileInfo::startAddr, DVDCommandBlock::state, TRUE.
Referenced by DTKQueueTrack, LoadMemInfo, LoadTexPalette.
BOOL DVDClose(DVDFileInfo *fileInfo)
References CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, DVDCancel, TRUE.
Referenced by __DTKCallbackForFlush, DTKRemoveTrack, LoadMemInfo, LoadTexPalette.
BOOL DVDGetCurrentDir(u8 *path, u32 maxlen)
References CARD_MAX_MOUNT_STEP, currentDirectory, DVDConvertEntrynumToPath.
Referenced by DVDChangeDir, DVDOpen, DVDOpenDir.
BOOL DVDChangeDir(u8 *dirName)
References CARD_MAX_MOUNT_STEP, currentDirectory, DVDConvertPathToEntrynum, DVDGetCurrentDir, entryIsDir, FALSE, TRUE.
BOOL DVDReadAsyncPrio(DVDFileInfo *fileInfo, void *addr, s32 length, s32 offset, DVDCallback callback, s32 prio)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForReadAsync, DVD_MIN_TRANSFER_SIZE, DVDReadAbsAsyncPrio, OFFSET, OSPanic, DVDFileInfo::startAddr, TRUE.
s32 DVDReadPrio(DVDFileInfo *fileInfo, void *addr, s32 length, s32 offset, s32 prio)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForReadSync, DVD_MIN_TRANSFER_SIZE, DVDReadAbsAsyncPrio, OFFSET, OSDisableInterrupts, OSPanic, OSRestoreInterrupts, OSSleepThread, DVDFileInfo::startAddr.
Referenced by LoadMemInfo, LoadTexPalette.
BOOL DVDSeekAsyncPrio(DVDFileInfo *fileInfo, s32 offset, void(*callback)(s32, DVDFileInfo *), s32 prio)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForSeekAsync, DVDSeekAbsAsyncPrio, OSPanic, DVDFileInfo::startAddr, TRUE.
s32 DVDSeekPrio(DVDFileInfo *fileInfo, s32 offset, s32 prio)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForSeekSync, DVDSeekAbsAsyncPrio, DVDFileInfo::length, OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, DVDFileInfo::startAddr.
s32 DVDGetFileInfoStatus(DVDFileInfo *fileInfo)
References DVDFileInfo::cb, DVDCommandBlock::state.
int DVDOpenDir(u8 *dirName, DVDDir *dir)
References CARD_MAX_MOUNT_STEP, DVDConvertPathToEntrynum, DVDGetCurrentDir, entryIsDir, FALSE, nextDir, TRUE.
BOOL DVDReadDir(DVDDir *dir, DVDDirEntry *dirent)
References CARD_MAX_MOUNT_STEP, entryIsDir, FALSE, FstStringStart, nextDir, stringOff, TRUE.
BOOL DVDCloseDir(DVDDir *dir)
References TRUE.
void * DVDGetFSTLocation()
References BootInfo, OSBootInfo_s::FSTLocation.
BOOL DVDPrepareStreamAsync(DVDFileInfo *fileInfo, u32 length, u32 offset, DVDCallback callback)
References DVDFileInfo::callback, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForPrepareStreamAsync, DVDPrepareStreamAbsAsync, Is32KBAligned, DVDFileInfo::length, OSPanic, DVDFileInfo::startAddr.
Referenced by __DTKPrepareCurrentTrack, __DTKPrepareCurrentTrackPaused.
s32 DVDPrepareStream(DVDFileInfo *fileInfo, u32 length, u32 offset)
References __DVDThreadQueue, CARD_MAX_MOUNT_STEP, DVDFileInfo::cb, cbForPrepareStreamSync, DVD_RESULT_CANCELED, DVD_RESULT_FATAL_ERROR, DVD_STATE_CANCELED, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVDPrepareStreamAbsAsync, FALSE, Is32KBAligned, DVDFileInfo::length, OSDisableInterrupts, OSPanic, OSRestoreInterrupts, OSSleepThread, DVDFileInfo::startAddr.
s32 DVDGetTransferredSize(DVDFileInfo *fileinfo)
References CARD_MAX_MOUNT_STEP, cb, DVD_STATE_BUSY, DVD_STATE_CANCELED, DVD_STATE_COVER_CLOSED, DVD_STATE_COVER_OPEN, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_MOTOR_STOPPED, DVD_STATE_NO_DISK, DVD_STATE_WAITING, DVD_STATE_WRONG_DISK, FALSE, DVDCommandBlock::transferredSize.