dvdlow.c
BOOL FirstRead
Referenced by __DVDInterruptHandler, DVDLowRead.
u32 LastLength
Referenced by AlarmHandlerForBreak, Read.
DVDLowCallback Callback
Referenced by __DVDInterruptHandler, __OSReboot, AlarmHandlerForTimeout, DVDLowAudioBufferConfig, DVDLowAudioStream, DVDLowClearCallback, DVDLowInquiry, DVDLowReadDiskID, DVDLowRequestAudioStatus, DVDLowRequestError, DVDLowSeek, DVDLowStopMotor, DVDLowWaitCoverClose, Read.
DVDLowCallback ResetCoverCallback
Referenced by __DVDInterruptHandler, DVDLowSetResetCoverCallback.
volatile OSTime LastResetEnd
Referenced by __DVDInterruptHandler, DVDLowGetCoverStatus, DVDLowReset.
vu32 ResetOccurred
Referenced by __DVDInterruptHandler, DVDLowReset.
volatile BOOL WaitingCoverClose
Referenced by __DVDInterruptHandler, DVDLowWaitCoverClose.
volatile BOOL Breaking
Referenced by __DVDInterruptHandler, DoBreak.
vu32 WorkAroundType
Referenced by __DVDLowSetWAType, DVDLowRead.
u32 WorkAroundSeekLocation
Referenced by __DVDLowSetWAType, SeekTwiceBeforeRead.
volatile OSTime LastReadFinished
Referenced by __DVDInterruptHandler, DVDLowRead.
OSTime LastReadIssued
Referenced by Read.
volatile BOOL LastCommandWasRead
Referenced by __DVDInterruptHandler, Read.
vu32 NextCommandNumber
Referenced by __DVDInitWA, __DVDInterruptHandler, DoJustRead, ProcessNextCommand, SeekTwiceBeforeRead, WaitBeforeRead.
DVDCommand CommandList[3][3]
Referenced by __DVDInitWA, __DVDInterruptHandler, DoJustRead, ProcessNextCommand, SeekTwiceBeforeRead, WaitBeforeRead.
OSAlarm AlarmForWA
Referenced by WaitBeforeRead.
OSAlarm AlarmForTimeout
Referenced by __DVDInterruptHandler, __DVDLowTestAlarm, SetTimeoutAlarm.
OSAlarm AlarmForBreak
Referenced by __DVDInterruptHandler, __DVDLowTestAlarm, SetBreakAlarm.
DVDBuffer Prev
Referenced by __DVDInterruptHandler, DSRemoveBranch, DSRemoveListObject, DVDLowRead.
DVDBuffer Curr
Referenced by __DVDInterruptHandler, DVDLowRead.
static void Read(void *address, u32 length, u32 offset, DVDLowCallback callback)
References __OSGetSystemTime, Callback, CARD_MAX_MOUNT_STEP, LastCommandWasRead, LastLength, LastReadIssued, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by DoJustRead, ProcessNextCommand.
static void SetBreakAlarm(OSTime timeout)
References AlarmForBreak, AlarmHandlerForBreak, CARD_MAX_MOUNT_STEP, OSCreateAlarm, OSSetAlarm.
Referenced by AlarmHandlerForBreak.
void __DVDInitWA(void)
References __DVDLowSetWAType, DVDCommand::command, CommandList, NextCommandNumber, OSInitAlarm.
Referenced by DVDInit.
static BOOL ProcessNextCommand(void)
References CARD_MAX_MOUNT_STEP, CommandList, DVDLowSeek, FALSE, NextCommandNumber, Read, TRUE.
Referenced by __DVDInterruptHandler, AlarmHandler.
void __DVDInterruptHandler(__OSInterrupt interrupt, OSContext *context)
References __OSGetSystemTime, DVDBuffer::addr, AlarmForBreak, AlarmForTimeout, Breaking, Callback, CARD_MAX_MOUNT_STEP, cb, DVDCommand::command, CommandList, Curr, FALSE, FirstRead, LastCommandWasRead, LastReadFinished, LastResetEnd, DVDBuffer::length, NextCommandNumber, NULL, DVDBuffer::offset, OSCancelAlarm, OSClearContext, OSMillisecondsToTicks, OSSetCurrentContext, Prev, ProcessNextCommand, ResetCoverCallback, ResetOccurred, WaitingCoverClose.
Referenced by DVDInit.
static void AlarmHandler(OSAlarm *alarm, OSContext *context)
References CARD_MAX_MOUNT_STEP, ProcessNextCommand.
static void AlarmHandlerForTimeout(OSAlarm *alarm, OSContext *context)
References __OSMaskInterrupts, Callback, CARD_MAX_MOUNT_STEP, cb, NULL, OSClearContext, OSSetCurrentContext.
Referenced by SetTimeoutAlarm.
static void SetTimeoutAlarm(OSTime timeout)
References AlarmForTimeout, AlarmHandlerForTimeout, CARD_MAX_MOUNT_STEP, OSCreateAlarm, OSSetAlarm.
Referenced by DVDLowAudioBufferConfig, DVDLowAudioStream, DVDLowInquiry, DVDLowReadDiskID, DVDLowRequestAudioStatus, DVDLowRequestError, DVDLowSeek, DVDLowStopMotor, Read.
static BOOL AudioBufferOn(void)
References DVDGetCurrentDiskID, FALSE, DVDDiskID::streaming, TRUE.
Referenced by HitCache.
static BOOL HitCache(DVDBuffer *curr, DVDBuffer *prev)
References AudioBufferOn, CARD_MAX_MOUNT_STEP, FALSE, DVDCommandBlock::length, DVDCommandBlock::offset, prev, TRUE.
Referenced by DVDLowRead.
static void DoJustRead(void *addr, u32 length, u32 offset, DVDLowCallback callback)
References DVDCommand::command, CommandList, NextCommandNumber, Read.
Referenced by DVDLowRead.
static void SeekTwiceBeforeRead(void *addr, u32 length, u32 offset, DVDLowCallback callback)
References DVDCommand::address, DVDCommand::callback, CARD_MAX_MOUNT_STEP, DVDCommand::command, CommandList, DVDLowSeek, DVDCommand::length, NextCommandNumber, DVDCommand::offset, WorkAroundSeekLocation.
Referenced by DVDLowRead.
static void WaitBeforeRead(void *addr, u32 length, u32 offset, DVDLowCallback callback, OSTime wait)
References DVDCommand::address, AlarmForWA, AlarmHandler, DVDCommand::callback, CARD_MAX_MOUNT_STEP, DVDCommand::command, CommandList, DVDCommand::length, NextCommandNumber, DVDCommand::offset, OSCreateAlarm, OSSetAlarm.
Referenced by DVDLowRead.
BOOL DVDLowRead(void *addr, u32 length, u32 offset, DVDLowCallback callback)
References __OSGetSystemTime, DVDBuffer::addr, CARD_MAX_MOUNT_STEP, Curr, DoJustRead, FALSE, FirstRead, HitCache, LastReadFinished, DVDBuffer::length, DVDBuffer::offset, OSMicrosecondsToTicks, OSMillisecondsToTicks, Prev, SeekTwiceBeforeRead, TRUE, WaitBeforeRead, WorkAroundType.
Referenced by stateBusy, stateCheckID2, stateReadingFST.
BOOL DVDLowSeek(u32 offset, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateGettingError, ProcessNextCommand, SeekTwiceBeforeRead, stateBusy.
BOOL DVDLowWaitCoverClose(DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, TRUE, WaitingCoverClose.
Referenced by stateMotorStopped.
BOOL DVDLowReadDiskID(DVDDiskID *diskID, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by stateBusy, stateCoverClosed_CMD.
BOOL DVDLowStopMotor(DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateCheckID1, stateBusy, stateCheckID, stateError, stateGoToRetry.
BOOL DVDLowRequestError(DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateCheckID3, cbForUnrecoveredError, stateGettingError.
BOOL DVDLowInquiry(DVDDriveInfo *info, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by stateBusy.
BOOL DVDLowAudioStream(u32 subcmd, u32 length, u32 offset, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by cbForStateBusy, stateBusy.
BOOL DVDLowRequestAudioStatus(u32 subcmd, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, TRUE.
Referenced by stateBusy.
BOOL DVDLowAudioBufferConfig(BOOL enable, u32 size, DVDLowCallback callback)
References Callback, CARD_MAX_MOUNT_STEP, OSSecondsToTicks, SetTimeoutAlarm, size, TRUE.
Referenced by stateBusy, stateCheckID3.
void DVDLowReset(void)
References __OSGetSystemTime, CARD_MAX_MOUNT_STEP, LastResetEnd, OSMicrosecondsToTicks, ResetOccurred, TRUE.
Referenced by DVDReset.
DVDLowCallback DVDLowSetResetCoverCallback(DVDLowCallback callback)
References OSDisableInterrupts, OSRestoreInterrupts, ResetCoverCallback.
static void DoBreak(void)
References Breaking, CARD_MAX_MOUNT_STEP, TRUE.
Referenced by AlarmHandlerForBreak.
static void AlarmHandlerForBreak(OSAlarm *alarm, OSContext *context)
References CARD_MAX_MOUNT_STEP, DoBreak, LastLength, OSMillisecondsToTicks, SetBreakAlarm.
Referenced by DVDLowBreak, SetBreakAlarm.
BOOL DVDLowBreak(void)
References AlarmHandlerForBreak, NULL, TRUE.
Referenced by DVDCancelAsync.
DVDLowCallback DVDLowClearCallback(void)
References Callback, CARD_MAX_MOUNT_STEP, NULL.
u32 DVDLowGetCoverStatus(void)
References __OSGetSystemTime, CARD_MAX_MOUNT_STEP, FALSE, LastResetEnd, OSMillisecondsToTicks, TRUE.
void __DVDLowSetWAType(u32 type, s32 seekLoc)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, WorkAroundSeekLocation, WorkAroundType.
Referenced by __DVDInitWA.
BOOL __DVDLowTestAlarm(const OSAlarm *alarm)
References AlarmForBreak, AlarmForTimeout, FALSE, TRUE.