dvdqueue.c
DVDCommandBlock* next
0x00
Referenced by __DSP_exec_task, __DVDClearWaitingQueue, __DVDDequeueWaitingQueue, __SEQRemoveSequenceFromList, DecrementerExceptionCallback, DLInsert, DSExtractBranch, InsertAlarm, KillThreads, OSCancelAlarm.
DVDCommandBlock* prev
0x04
Referenced by __DVDDequeueWaitingQueue, __OSMaskInterrupts, __OSUnmaskInterrupts, DLInsert, DVDSetAutoInvalidation, EXIClearInterrupts, EXISetExiCallback, GXSetCurrentGXThread, HitCache, InsertAlarm, OSSetCurrentHeap, OSSetInterruptMask.
struct WaitingQueue[4][4]
Referenced by __DVDCheckWaitingQueue, __DVDClearWaitingQueue, __DVDIsBlockInWaitingQueue, __DVDPopWaitingQueue, __DVDPushWaitingQueue, DVDDumpWaitingQueue, PopWaitingQueuePrio.
char* CommandNames[16][16]
Referenced by DVDDumpWaitingQueue.
static DVDCommandBlock * PopWaitingQueuePrio(s32 prio)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, tmp, WaitingQueue.
Referenced by __DVDPopWaitingQueue.
void __DVDClearWaitingQueue(void)
References CARD_MAX_MOUNT_STEP, DVDCommandBlock::next, next, DVDCommandBlock::prev, WaitingQueue.
Referenced by __DVDPrepareResetAsync, DVDInit, stateCoverClosed.
BOOL __DVDPushWaitingQueue(s32 prio, DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, DVDCommandBlock::next, OSDisableInterrupts, OSRestoreInterrupts, DVDCommandBlock::prev, TRUE, WaitingQueue.
Referenced by issueCommand.
DVDCommandBlock * __DVDPopWaitingQueue(void)
References CARD_MAX_MOUNT_STEP, NULL, OSDisableInterrupts, OSRestoreInterrupts, PopWaitingQueuePrio, WaitingQueue.
Referenced by DVDCancelAllAsync, stateReady.
int __DVDCheckWaitingQueue(void)
References CARD_MAX_MOUNT_STEP, FALSE, OSDisableInterrupts, OSRestoreInterrupts, TRUE, WaitingQueue.
Referenced by stateReady.
int __DVDDequeueWaitingQueue(DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, FALSE, DVDCommandBlock::next, next, NULL, OSDisableInterrupts, OSRestoreInterrupts, DVDCommandBlock::prev, prev, TRUE.
Referenced by DVDCancelAsync.
int __DVDIsBlockInWaitingQueue(DVDCommandBlock *block)
References CARD_MAX_MOUNT_STEP, FALSE, DVDCommandBlock::next, TRUE, WaitingQueue.
Referenced by issueCommand.
void DVDDumpWaitingQueue(void)
References CARD_MAX_MOUNT_STEP, CommandNames, DVDCommandBlock::next, OSReport, WaitingQueue.