exi.h
typedef void(* EXICallback) (s32 chan, OSContext *context))(s32 chan, OSContext *context)
EXICallback EXISetExiCallback(s32 channel, EXICallback callback)
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, prev, SetExiInterruptMask.
Referenced by __CARDExtHandler, CARDMountAsync, DoMount, DoUnmount, HIOInit, TimeoutHandler.
void EXIInit(void)
References __OSMaskInterrupts, __OSSetInterruptHandler, CARD_MAX_MOUNT_STEP, EXIIntrruptHandler, EXIProbeReset, EXTIntrruptHandler, OSGetConsoleType, TCIntrruptHandler.
Referenced by OSInit.
BOOL EXILock(s32 channel, u32 device, EXICallback callback)
Referenced by __CARDExiHandler, __CARDStart, __OSReadROM, __OSReadROMAsync, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, CARDMountAsync, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, ReadSram, UnlockedCallback, WriteSram, WriteUARTN.
int EXIUnlock(s32 channel)
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, SetExiInterruptMask, STATE_LOCKED.
Referenced by __CARDErase, __CARDEraseSector, __CARDExiHandler, __CARDReadSegment, __CARDStart, __CARDTxHandler, __CARDWritePage, __OSReadROM, __OSReadROMAsync, __OSReadROMCallback, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, DoMount, DoneCallback, EXIGetID, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, ReadSram, Retry, RxHandler, TxHandler, WriteSram, WriteUARTN.
int EXISelect(s32 channel, u32 device, u32 frequency)
References __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIProbe, MAX_CHAN, MAX_DEV, MAX_FREQ, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED, STATE_LOCKED, STATE_SELECTED.
Referenced by __CARDClearStatus, __CARDEnableInterrupt, __CARDReadNintendoID, __CARDReadStatus, __CARDSleep, __CARDStart, __CARDWakeup, __OSReadROM, __OSReadROMAsync, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, EXIGetID, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, QueueLength, ReadArrayUnlock, ReadSram, Retry, WriteSram, WriteUARTN.
int EXIDeselect(s32 channel)
References __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIProbe, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED, STATE_SELECTED.
Referenced by __CARDClearStatus, __CARDEnableInterrupt, __CARDErase, __CARDEraseSector, __CARDReadNintendoID, __CARDReadSegment, __CARDReadStatus, __CARDSleep, __CARDTxHandler, __CARDWakeup, __CARDWritePage, __OSReadROM, __OSReadROMCallback, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, EXIGetID, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteMailbox, QueueLength, ReadArrayUnlock, ReadSram, Retry, RxHandler, TxHandler, WriteSram, WriteUARTN.
BOOL EXIImm(s32 channel, void *buffer, s32 length, u32 type, EXICallback callback)
Referenced by __CARDClearStatus, __CARDEnableInterrupt, __CARDReadNintendoID, __CARDReadStatus, __CARDSleep, __CARDWakeup, __OSReadROM, __OSReadROMAsync, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, QueueLength, ReadSram, WriteSram, WriteUARTN.
BOOL EXIImmEx(s32 channel, void *buffer, s32 length, u32 type)
Referenced by __CARDErase, __CARDEraseSector, __CARDReadSegment, __CARDWritePage, ReadArrayUnlock, Retry, WriteSram.
BOOL EXIDma(s32 channel, void *buffer, s32 length, u32 type, EXICallback callback)
Referenced by __CARDReadSegment, __CARDWritePage, __OSReadROM, __OSReadROMAsync, HIORead, HIOReadAsync, HIOWrite, HIOWriteAsync, ReadSram, Retry.
int EXISync(s32 channel)
References __OSGetDIConfig, CARD_MAX_MOUNT_STEP, CompleteTransfer, Ecb, FALSE, MAX_CHAN, OSDisableInterrupts, OSRestoreInterrupts, STATE_BUSY, STATE_SELECTED, TRUE.
Referenced by __CARDClearStatus, __CARDEnableInterrupt, __CARDReadNintendoID, __CARDReadStatus, __CARDSleep, __CARDWakeup, __OSReadROM, __OSReadROMAsync, __OSSetRTC, AD16Init, AD16ReadReg, AD16WriteReg, EXIGetID, EXIImmEx, GetRTC, gpioInput, gpioOut, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, QueueLength, ReadSram, WriteSram, WriteUARTN.
int EXIProbe(s32 channel)
References __gUnknown800030C0, CARD_MAX_MOUNT_STEP, Ecb, EXIClearInterrupts, MAX_CHAN, OSDisableInterrupts, OSGetTime, OSRestoreInterrupts, OSTicksToMilliseconds, STATE_ATTACHED.
Referenced by __CARDTxHandler, __CARDUnlockedHandler, CARDProbe, DoMount, DoneCallback, EXIAttach, EXIDeselect, EXIProbeEx, EXIProbeReset, EXISelect.
int EXIProbeEx(s32 channel)
References __gUnknown800030C0, EXIProbe.
Referenced by CARDProbeEx, HIOEnumDevices, HIOInit.
int EXIAttach(s32 channel, EXICallback callback)
References __OSUnmaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, EXIClearInterrupts, EXIProbe, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED.
Referenced by CARDMountAsync, EXIGetID, HIOEnumDevices, HIOInit.
int EXIDetach(s32 channel)
References __OSMaskInterrupts, CARD_MAX_MOUNT_STEP, Ecb, OSDisableInterrupts, OSRestoreInterrupts, STATE_ATTACHED, STATE_LOCKED.
Referenced by DoUnmount, EXIGetID, HIOEnumDevices, HIOInit.
u32 EXIGetState(s32 channel)
References CARD_MAX_MOUNT_STEP, Ecb, MAX_CHAN.
Referenced by CARDMountAsync, CARDProbeEx.
int EXIGetID(s32 channel, u32 device, u32 *id)
References CARD_MAX_MOUNT_STEP, EXIAttach, EXIDeselect, EXIDetach, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, MAX_CHAN.
Referenced by CARDProbeEx.
void EXIProbeReset(void)
References __gUnknown800030C0, EXIProbe.
Referenced by __OSSetTime, EXIInit.