fileCache.c
DSCache DODisplayCache
Referenced by CSHInitDisplayCache, TEXGetPalette, TEXReleasePalette.
u8 DOCacheInitialized
Referenced by CSHInitDisplayCache, TEXGetPalette, TEXReleasePalette.
static u8 AllocCacheNode(DSCacheNodePtr *cacheNode, char *name)
References CARD_MAX_MOUNT_STEP, FALSE, FreeCacheNode, OSAlloc, Strlen, TRUE.
Referenced by DSAddCacheNode.
static void FreeCacheNode(DSCacheNodePtr *cacheNode)
References CARD_MAX_MOUNT_STEP, NULL, OSFree.
Referenced by AllocCacheNode, DSEmptyCache, DSPurgeCache, DSReleaseCacheObj.
DSCacheNodePtr DSAddCacheNode(DSCachePtr cache, char *name, Ptr data, Ptr OSFreeFunc)
References AllocCacheNode, CARD_MAX_MOUNT_STEP, DSInsertListObject, NULL, Strcpy.
Referenced by TEXGetPalette.
void DSEmptyCache(DSCachePtr cache)
References CARD_MAX_MOUNT_STEP, DSRemoveListObject, FreeCacheNode.
static DSCacheNodePtr FindCacheNode(DSCachePtr cache, char *name, Ptr data)
References CARD_MAX_MOUNT_STEP, NULL, Strcmp.
Referenced by DSGetCacheObj, DSReleaseCacheObj.
Ptr DSGetCacheObj(DSCachePtr cache, char *name)
References CARD_MAX_MOUNT_STEP, FindCacheNode, NULL.
Referenced by TEXGetPalette.
void DSInitCache(DSCachePtr cache)
References CARD_MAX_MOUNT_STEP, DSInitList.
Referenced by CSHInitDisplayCache.
void DSPurgeCache(DSCachePtr cache)
References CARD_MAX_MOUNT_STEP, DSRemoveListObject, FreeCacheNode.
void DSReleaseCacheObj(DSCachePtr cache, Ptr data)
References CARD_MAX_MOUNT_STEP, DSRemoveListObject, FindCacheNode, FreeCacheNode, NULL.
Referenced by TEXReleasePalette.
void DSSetCachePurgeFlag(DSCachePtr cache, u8 purgeFlag)
References CARD_MAX_MOUNT_STEP.
void CSHInitDisplayCache(void)
References DOCacheInitialized, DODisplayCache, DSInitCache, TRUE.