fio.c
u8 gBuf[8192][8192]
Referenced by fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket.
u8 gPrintBuf[1024][1024]
Referenced by FIOFprintf.
u8 gmSizeOfBlocks
Referenced by FIOExit, FIOInit, fioPacketResultRead, fioPacketResultWrite.
u8 gSizeOfBlocks
Referenced by FIOExit, FIOGetAsyncBufferSize, FIOInit.
volatile int gProcDone
Referenced by FIOExit, FIOInit, fioMccChannelEvent, fioPacketReceiveResult, fioPacketSendPacket.
enum MCC_CHANNEL gmChID
Referenced by FIOExit, FIOInit, fioPacketResultRead, fioPacketResultWrite.
enum MCC_CHANNEL gChID
Referenced by FIOExit, FIOGetAsyncBufferSize, FIOInit, fioIsInitialized, fioMccChannelEvent, fioPacketReceiveResult, fioPacketResultRead, fioPacketResultWrite, fioPacketSendPacket, FIOQuery.
int gQuery
Referenced by FIOExit, FIOInit, fioMccChannelEvent, FIOQuery.
volatile int gProcBusy
Referenced by FIOExit, FIOInit, fioPacketReceiveDone, fioPacketSendPacket.
volatile u32 gStreamReady
Referenced by fioMccChannelEvent, fioPacketRead, fioPacketResultRead, fioPacketWrite.
u8 gLastErr
Referenced by FIOExit, FIOFclose, FIOFerror, FIOFflush, FIOFindFirst, FIOFindNext, FIOFopen, FIOFprintf, FIOFread, FIOFreadAsync, FIOFseek, FIOFstat, FIOFwrite, FIOFwriteAsync, FIOGetLastError, FIOInit, fioPacketReceiveResult, fioPacketResultRead, fioPacketResultWrite, fioPacketSendPacket, FIOQuery.
int bAsyncIsRead
Referenced by FIOCheckAsyncDone, FIOExit, FIOFreadAsync, FIOFwriteAsync, FIOInit.
enum FIO_ASYNC_STATE bAsyncBusy
Referenced by FIOCheckAsyncDone, FIOExit, FIOFclose, FIOFerror, FIOFflush, FIOFindFirst, FIOFindNext, FIOFopen, FIOFprintf, FIOFread, FIOFreadAsync, FIOFseek, FIOFstat, FIOFwrite, FIOFwriteAsync, FIOInit, fioMccChannelEvent.
void* bAsyncBuffer
Referenced by FIOCheckAsyncDone, FIOExit, FIOFreadAsync, FIOFwriteAsync, FIOInit.
u32 gAsyncDataSize
Referenced by FIOCheckAsyncDone, fioPacketRead, fioPacketWrite.
u32 gRequestSequenceNumber
Referenced by fioPacketMakeHeader, fioPacketReceiveResult.
static int fioIsInitialized()
References gChID.
Referenced by FIOQuery.
static u16 EndianConvert16(u16 n)
References CARD_MAX_MOUNT_STEP.
Referenced by EndianConvert32, fioPacketMakeHeader.
static u32 EndianConvert32(u32 n)
References CARD_MAX_MOUNT_STEP, EndianConvert16.
Referenced by fioPacketMakeHeader.
static int MPDWaiting(int timeout, volatile int *flag, int value)
References CARD_MAX_MOUNT_STEP, OSGetTick, OSReport, OSTicksToSeconds.
Referenced by fioPacketReceiveResult, FIOQuery.
static void ShowChannelInfo(enum MCC_CHANNEL chID)
References MCC_Info::blockLength, CARD_MAX_MOUNT_STEP, MCC_Info::connect, MCC_Info::firstBlock, MCC_Info::isLocked, MCCGetChannelInfo, OSReport.
static void fioErrorReport(char *msg)
References CARD_MAX_MOUNT_STEP, OSReport.
Referenced by fioPacketResultRead, fioPacketResultWrite, fioPacketSendPacket.
static void fioMccChannelEvent(enum MCC_CHANNEL chID, u32 event, u32 value)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, gChID, gProcDone, gQuery, gStreamReady.
Referenced by FIOInit, fioPacketResultRead, fioPacketResultWrite.
static void * fioPacketMakeHeader(u32 fioCode, u32 dataSize, int bEndianConvert)
References CARD_MAX_MOUNT_STEP, MCC_HdrFio::code, EndianConvert16, EndianConvert32, gBuf, gRequestSequenceNumber.
Referenced by FIOFclose, FIOFerror, FIOFflush, FIOFindFirst, FIOFindNext, FIOFopen, FIOFseek, FIOFstat, fioPacketRead, fioPacketWrite.
static int fioPacketSendPacket(u8 sizeOfBlocks, void *pTopOfSecondBlockData)
References CARD_MAX_MOUNT_STEP, fioErrorReport, gBuf, gChID, gLastErr, gProcBusy, gProcDone, MCCNotify, MCCSetChannelEventMask, MCCWrite.
Referenced by FIOFclose, FIOFerror, FIOFflush, FIOFindFirst, FIOFindNext, FIOFopen, FIOFseek, FIOFstat, fioPacketRead, fioPacketWrite.
static void * fioPacketReceiveResult(u32 fioCode, int bDone)
References CARD_MAX_MOUNT_STEP, exit, fioPacketReceiveDone, gBuf, gChID, gLastErr, gProcDone, gRequestSequenceNumber, MCCRead, MCCSetChannelEventMask, MPDWaiting, NULL.
Referenced by FIOFclose, FIOFerror, FIOFflush, FIOFindFirst, FIOFindNext, FIOFopen, FIOFseek, FIOFstat, fioPacketResultRead, fioPacketResultWrite.
static void fioPacketReceiveDone(void)
References gProcBusy.
Referenced by fioPacketReceiveResult, fioPacketResultRead.
static int fioPacketRead(int fd, void *buffer, int size, int async)
References buffer, CARD_MAX_MOUNT_STEP, fioPacketMakeHeader, fioPacketResultRead, fioPacketSendPacket, gAsyncDataSize, gStreamReady, NULL, size.
Referenced by FIOFread, FIOFreadAsync.
static int fioPacketWrite(int fd, void *buffer, int size, int async)
References buffer, CARD_MAX_MOUNT_STEP, fioPacketMakeHeader, fioPacketResultWrite, fioPacketSendPacket, gAsyncDataSize, gStreamReady, NULL, size.
Referenced by FIOFwrite, FIOFwriteAsync.
static int fioPacketResultRead(void *buffer, u32 dataSize)
References buffer, CARD_MAX_MOUNT_STEP, exit, fioErrorReport, fioMccChannelEvent, fioPacketReceiveDone, fioPacketReceiveResult, gChID, gLastErr, gmChID, gmSizeOfBlocks, gStreamReady, MCCClose, MCCGetConnectionStatus, MCCGetLastError, MCCOpen, MCCRead, MCCSetChannelEventMask, MCCStreamClose, MCCStreamOpen, MCCStreamRead, NULL, OSReport, OSRoundUp32B.
Referenced by FIOCheckAsyncDone, fioPacketRead.
static int fioPacketResultWrite(void *buffer, u32 dataSize)
References buffer, CARD_MAX_MOUNT_STEP, exit, fioErrorReport, fioMccChannelEvent, fioPacketReceiveResult, gChID, gLastErr, gmChID, gmSizeOfBlocks, MCCClose, MCCGetConnectionStatus, MCCOpen, MCCSetChannelEventMask, MCCStreamClose, MCCStreamOpen, MCCStreamWrite, NULL, OSReport.
Referenced by FIOCheckAsyncDone, fioPacketWrite.
int FIOInit(enum MCC_EXI exiChannel, enum MCC_CHANNEL chID, u8 blockSize)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, CARD_MAX_MOUNT_STEP, exit, fioMccChannelEvent, gChID, gLastErr, gmChID, gmSizeOfBlocks, gProcBusy, gProcDone, gQuery, gSizeOfBlocks, MCCInit, MCCOpen, NULL.
void FIOExit(void)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, gChID, gLastErr, gmChID, gmSizeOfBlocks, gProcBusy, gProcDone, gQuery, gSizeOfBlocks, MCCClose, NULL.
int FIOQuery(void)
References CARD_MAX_MOUNT_STEP, exit, fioIsInitialized, gChID, gLastErr, gQuery, MCCNotify, MPDWaiting, OSGetTick, OSTicksToSeconds.
u8 FIOGetLastError()
References gLastErr.
int FIOFopen(const char *filename, u32 mode)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFclose(int handle)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
u32 FIOFread(int handle, void *data, u32 size)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketRead, gLastErr, NULL, size.
u32 FIOFwrite(int handle, void *data, u32 size)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketWrite, gLastErr, NULL, size.
Referenced by FIOFprintf.
u32 FIOFseek(int handle, s32 offset, u32 mode)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFprintf(int handle, const char *format,...)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, FIOFwrite, gLastErr, gPrintBuf, NULL.
int FIOFflush(int handle)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFstat(int handle, struct FIO_Stat *stat)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFerror(int handle)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFindFirst(const char *filename, struct FIO_Finddata *finddata)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, FIO_Finddata::filename, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFindNext(struct FIO_Finddata *finddata)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
u32 FIOGetAsyncBufferSize(void)
References CARD_MAX_MOUNT_STEP, gChID, gSizeOfBlocks.
Referenced by FIOFreadAsync, FIOFwriteAsync.
int FIOFreadAsync(int handle, void *data, u32 size)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, exit, FIOGetAsyncBufferSize, fioPacketRead, gLastErr, NULL, size.
int FIOFwriteAsync(int handle, void *data, u32 size)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, exit, FIOGetAsyncBufferSize, fioPacketWrite, gLastErr, NULL, size.
int FIOCheckAsyncDone(u32 *result)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, fioPacketResultRead, fioPacketResultWrite, gAsyncDataSize.