fstload.c
u32 status
Referenced by __CARDExiHandler, __CARDReadStatus, cb, cbForStateGettingError, DBGReadStatus, DoMount, DVDGetCommandBlockStatus, HIOReadStatus, MCCInit, NotifyCompulsorily, PADClamp, PADRead, SPEC0_MakeStatus, SPEC1_MakeStatus, SPEC2_MakeStatus.
u8 bb2Buf[63][63]
Referenced by __fstLoad.
DVDBB2* bb2
Referenced by __fstLoad, cb.
DVDDiskID* idTmp
Referenced by __fstLoad, cb.
static void cb(s32 result, DVDCommandBlock *block)
References bb2, CARD_MAX_MOUNT_STEP, cb, DVD_RESULT_FATAL_ERROR, DVD_RESULT_NO_DISK, DVDReadAbsAsyncForBS, DVDReadDiskID, DVDReset, DVDBB2::FSTAddress, DVDBB2::FSTLength, DVDBB2::FSTPosition, idTmp, OSRoundUp32B, status.
Referenced by __DVDInterruptHandler, __DVDPrepareResetAsync, __fstLoad, AlarmHandlerForTimeout, cb, cbForPrepareStreamAsync, cbForReadAsync, DVDGetTransferredSize, GXSetBreakPtCallback, GXSetDrawDoneCallback, GXSetDrawSyncCallback, OSExceptionInit, PERFSetDrawSyncCallback, VISetPostRetraceCallback, VISetPreRetraceCallback.
void __fstLoad()
References bb2, bb2Buf, bootInfo, CARD_MAX_MOUNT_STEP, cb, DVDDiskID::company, DVDDiskID::diskNumber, DVD_STATE_BUSY, DVD_STATE_COVER_CLOSED, DVD_STATE_COVER_OPEN, DVD_STATE_END, DVD_STATE_FATAL_ERROR, DVD_STATE_MOTOR_STOPPED, DVD_STATE_NO_DISK, DVD_STATE_WAITING, OSBootInfo_s::DVDDiskID, DVDGetDriveStatus, DVDReadDiskID, DVDReset, DVDBB2::FSTAddress, OSBootInfo_s::FSTLocation, DVDBB2::FSTMaxLength, OSBootInfo_s::FSTMaxLength, DVDDiskID::gameName, DVDDiskID::gameVersion, idTmp, OSGetArenaHi, OSPhysicalToCached, OSReport, OSRoundUp32B, OSSetArenaHi, DVDDiskID::streaming.
Referenced by DVDInit.