gpioexi.c
u8 shadowGPIOOE
Referenced by __VISetSCL, __VISetSDA, initGpioExi, setI2CEnable, setVideoReset.
u8 shadowGPIOData
Referenced by initGpioExi, setI2CEnable, setVideoReset.
static void initGpioExi(void)
References gpioOE, gpioOutput, shadowGPIOData, shadowGPIOOE.
Referenced by __VIInitI2C.
static void setVideoReset(int value)
References CARD_MAX_MOUNT_STEP, gpioOE, gpioOutput, shadowGPIOData, shadowGPIOOE.
Referenced by __VIInitI2C.
static void setI2CEnable(int value)
References CARD_MAX_MOUNT_STEP, gpioOE, gpioOutput, shadowGPIOData, shadowGPIOOE.
Referenced by __VIInitI2C.
static int gpioOutput(u8 value)
References CARD_MAX_MOUNT_STEP, gpioOut.
Referenced by initGpioExi, setI2CEnable, setVideoReset.
static int gpioOE(u8 value)
References CARD_MAX_MOUNT_STEP, gpioOut.
Referenced by __VISetSCL, __VISetSDA, initGpioExi, setI2CEnable, setVideoReset.
static int gpioOut(u32 addr, u8 value)
References CARD_MAX_MOUNT_STEP, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock.
Referenced by gpioOE, gpioOutput.
static int gpioInput(u8 *p)
References CARD_MAX_MOUNT_STEP, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock.
Referenced by __VIGetSCL, __VIGetSDA.
void __VIInitI2C(void)
References initGpioExi, OS_USEC_TO_TICKS, OSGetTime, setI2CEnable, setVideoReset.
Referenced by __VIInitPhilips.
void __VISetSCL(int value)
References CARD_MAX_MOUNT_STEP, gpioOE, shadowGPIOOE.
Referenced by __VISendI2CData, sendSlaveAddr.
int __VIGetSCL(void)
References CARD_MAX_MOUNT_STEP, gpioInput.
Referenced by wait4ClkHigh.
void __VISetSDA(int value)
References CARD_MAX_MOUNT_STEP, gpioOE, shadowGPIOOE.
Referenced by __VISendI2CData, sendSlaveAddr.
int __VIGetSDA(void)
References CARD_MAX_MOUNT_STEP, gpioInput.
Referenced by __VISendI2CData, sendSlaveAddr.