gx.h
void(*)(u16) GXSetDrawSyncCallback(void(*cb)(u16))(void(*cb)(u16))
Referenced by PERFEndFrame, PERFInit, PERFStartFrame.
void GXSetDrawSync(u16 token)
References __GXData, __GXData_struct::bpSent, CARD_MAX_MOUNT_STEP, CHECK_GXBEGIN, GX_WRITE_RAS_REG, GXFlush, OSDisableInterrupts, OSRestoreInterrupts, SET_REG_FIELD.
Referenced by __BypassDoneRender, DEMOBeforeRender, PERFEventEnd, PERFEventStart.