hio.c
s32 Chan
Referenced by ExtHandler, HIOEnumDevices, HIOInit, HIORead, HIOReadAsync, HIOReadMailbox, HIOReadStatus, HIOWrite, HIOWriteAsync, HIOWriteMailbox, RxHandler, TxHandler.
HIOCallback ExiCallback
Referenced by DbgHandler, ExiHandler, HIOInit.
HIOCallback TxCallback
Referenced by HIOInit, HIOWriteAsync, TxHandler.
HIOCallback RxCallback
Referenced by HIOInit, HIOReadAsync, RxHandler.
static void ExtHandler(s32 chan, OSContext *context)
References Chan.
Referenced by HIOEnumDevices, HIOInit.
static void ExiHandler(s32 chan, OSContext *context)
References ExiCallback.
Referenced by HIOInit.
static void DbgHandler(__OSInterrupt interrupt, OSContext *context)
References CARD_MAX_MOUNT_STEP, ExiCallback.
Referenced by HIOInit.
static void TxHandler(s32 chan, OSContext *context)
References Chan, EXIDeselect, EXIUnlock, TxCallback.
Referenced by HIOWriteAsync.
static void RxHandler(s32 chan, OSContext *context)
References Chan, EXIDeselect, EXIUnlock, RxCallback.
Referenced by HIOReadAsync.
BOOL HIOEnumDevices(HIOEnumCallback callback)
References Chan, EXIAttach, EXIDeselect, EXIDetach, EXIImm, EXILock, EXIProbeEx, EXISelect, EXISync, EXIUnlock, ExtHandler.
Referenced by MCCEnumDevices.
BOOL HIOInit(s32 chan, HIOCallback callback)
References __OSSetInterruptHandler, __OSUnmaskInterrupts, Chan, DbgHandler, EXIAttach, ExiCallback, EXIDeselect, EXIDetach, ExiHandler, EXIImm, EXILock, EXIProbeEx, EXISelect, EXISetExiCallback, EXISync, EXIUnlock, ExtHandler, NULL, RxCallback, TxCallback.
Referenced by MCCInit.
BOOL HIOReadMailbox(u32 *word)
References CARD_MAX_MOUNT_STEP, Chan, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock.
Referenced by MailboxCheck, MCCInit.
BOOL HIOWriteMailbox(u32 word)
References CARD_MAX_MOUNT_STEP, Chan, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock.
Referenced by NotifyCompulsorily.
BOOL HIORead(u32 addr, void *buffer, s32 size)
References buffer, CARD_MAX_MOUNT_STEP, Chan, EXIDeselect, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, NULL, size.
Referenced by GetUsbAdapterMode, InitializeCodeCheck, LoadChannelInfo, MCCRead, SetUsbAdapterMode.
BOOL HIOWrite(u32 addr, void *buffer, s32 size)
References buffer, CARD_MAX_MOUNT_STEP, Chan, EXIDeselect, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, NULL, size.
Referenced by FlushChannelInfo, InitializeCodeClear, InitializeCodeSet, MCCWrite, SetUsbAdapterMode.
BOOL HIOReadAsync(u32 addr, void *buffer, s32 size, HIOCallback callback)
References buffer, CARD_MAX_MOUNT_STEP, Chan, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, RxCallback, RxHandler, size.
Referenced by MCCRead.
BOOL HIOWriteAsync(u32 addr, void *buffer, s32 size, HIOCallback callback)
References buffer, CARD_MAX_MOUNT_STEP, Chan, EXIDma, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, size, TxCallback, TxHandler.
Referenced by MCCWrite.
BOOL HIOReadStatus(u32 *status)
References Chan, EXIDeselect, EXIImm, EXILock, EXISelect, EXISync, EXIUnlock, status.
Referenced by MCCInit, NotifyCompulsorily.