i2c.c
int lastError
Referenced by __VISendI2CData, sendSlaveAddr, wait4ClkHigh.
static int wait4ClkHigh(void)
References __VIGetSCL, CARD_MAX_MOUNT_STEP, lastError.
Referenced by __VISendI2CData, sendSlaveAddr.
static int sendSlaveAddr(u8 slaveAddr)
References __VIGetSDA, __VISetSCL, __VISetSDA, CARD_MAX_MOUNT_STEP, lastError, wait4ClkHigh.
Referenced by __VISendI2CData.
int __VISendI2CData(u8 slaveAddr, u8 *pData, int nBytes)
References __VIGetSDA, __VISetSCL, __VISetSDA, CARD_MAX_MOUNT_STEP, lastError, sendSlaveAddr, wait4ClkHigh.
Referenced by send7120Data.