mcc.h
MCC_CHANNEL
MCC_EXI
MCC_SYSEVENT
MCC_MODE
MCC_CONNECT
MCC_SYNC_STATE
FIO_ASYNC_STATE
typedef void(* MCC_CBEvent) (enum MCC_CHANNEL channel, u32, u32))(enum MCC_CHANNEL channel, u32, u32)
typedef void(* MCC_CBSysEvent) (enum MCC_SYSEVENT sysEvent))(enum MCC_SYSEVENT sysEvent)
typedef int(* MCC_CBEnumDevices) (s32))(s32)
int FIOInit(enum MCC_EXI exiChannel, enum MCC_CHANNEL chID, u8 blockSize)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, CARD_MAX_MOUNT_STEP, exit, fioMccChannelEvent, gChID, gLastErr, gmChID, gmSizeOfBlocks, gProcBusy, gProcDone, gQuery, gSizeOfBlocks, MCCInit, MCCOpen, NULL.
void FIOExit(void)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, gChID, gLastErr, gmChID, gmSizeOfBlocks, gProcBusy, gProcDone, gQuery, gSizeOfBlocks, MCCClose, NULL.
int FIOQuery(void)
References CARD_MAX_MOUNT_STEP, exit, fioIsInitialized, gChID, gLastErr, gQuery, MCCNotify, MPDWaiting, OSGetTick, OSTicksToSeconds.
u8 FIOGetLastError()
References gLastErr.
int FIOFopen(const char *filename, u32 mode)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFclose(int handle)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
u32 FIOFread(int handle, void *data, u32 size)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketRead, gLastErr, NULL, size.
u32 FIOFwrite(int handle, void *data, u32 size)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketWrite, gLastErr, NULL, size.
Referenced by FIOFprintf.
u32 FIOFseek(int handle, s32 offset, u32 mode)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFprintf(int handle, const char *format,...)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, FIOFwrite, gLastErr, gPrintBuf, NULL.
int FIOFflush(int handle)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFstat(int handle, struct FIO_Stat *stat)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFerror(int handle)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFindFirst(const char *filename, struct FIO_Finddata *finddata)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, FIO_Finddata::filename, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
int FIOFindNext(struct FIO_Finddata *finddata)
References bAsyncBusy, CARD_MAX_MOUNT_STEP, exit, fioPacketMakeHeader, fioPacketReceiveResult, fioPacketSendPacket, gLastErr, NULL.
u32 FIOGetAsyncBufferSize(void)
References CARD_MAX_MOUNT_STEP, gChID, gSizeOfBlocks.
Referenced by FIOFreadAsync, FIOFwriteAsync.
int FIOFreadAsync(int handle, void *data, u32 size)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, exit, FIOGetAsyncBufferSize, fioPacketRead, gLastErr, NULL, size.
int FIOFwriteAsync(int handle, void *data, u32 size)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, exit, FIOGetAsyncBufferSize, fioPacketWrite, gLastErr, NULL, size.
int FIOCheckAsyncDone(u32 *result)
References bAsyncBuffer, bAsyncBusy, bAsyncIsRead, fioPacketResultRead, fioPacketResultWrite, gAsyncDataSize.
int MCCStreamOpen(enum MCC_CHANNEL chID, u8 blockSize)
References callbackEventStream, CARD_MAX_MOUNT_STEP, MCCOpen.
Referenced by fioPacketResultRead, fioPacketResultWrite.
int MCCStreamClose(enum MCC_CHANNEL chID)
References CARD_MAX_MOUNT_STEP, MCCClose.
Referenced by fioPacketResultRead, fioPacketResultWrite.
int MCCStreamWrite(enum MCC_CHANNEL chID, void *data, u32 dataBlockSize)
References MCC_Info::blockLength, CARD_MAX_MOUNT_STEP, exit, gLastError, gMccInitialized, LoadChannelInfo, MCCGetChannelInfo, MCCWrite, WaitAMinute.
Referenced by fioPacketResultWrite.
u32 MCCStreamRead(enum MCC_CHANNEL chID, void *data)
References MCC_Info::blockLength, CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, MCCGetChannelInfo, MCCRead, WaitAMinute.
Referenced by fioPacketResultRead.
int MCCInit(enum MCC_EXI exiChannel, u8 timeout, MCC_CBSysEvent callbackSysEvent)
References AsyncResourceClearState, CARD_MAX_MOUNT_STEP, ClearChannelInfo, gCallbackSysEvent, GetUsbAdapterMode, gLastError, gMccInitialized, HIOInit, HIOReadMailbox, HIOReadStatus, mccDebugPrint, MCCExiCallback, mccInitializeCheck, NotifyInit, SetChannelInfoDirty, SetUsbAdapterMode, status, WaitAMinute.
Referenced by FIOInit, TTYInit.
void MCCExit(void)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, gMccSession, IsChannelOpened, MCCClose, mccDebugPrint.
int MCCPing(void)
References gLastError, gMccInitialized, gPingFlag, mccDebugPrint, NotifyCompulsorily.
int MCCEnumDevices(MCC_CBEnumDevices callbackEnumDevices)
References CARD_MAX_MOUNT_STEP, gLastError, HIOEnumDevices, NULL.
u8 MCCGetFreeBlocks(enum MCC_MODE mode)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint, NULL, SearchFreeBlocks.
u8 MCCGetLastError(void)
References gLastError, mccDebugPrint.
Referenced by fioPacketResultRead.
int MCCGetChannelInfo(enum MCC_CHANNEL chID, MCC_Info *info)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint.
Referenced by MCCGetConnectionStatus, MCCStreamRead, MCCStreamWrite, ShowChannelInfo, ShowChannelInfo.
int MCCGetConnectionStatus(enum MCC_CHANNEL chID, enum MCC_CONNECT *connect)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, MCC_Info::connect, gLastError, gMccInitialized, mccDebugPrint, MCCGetChannelInfo.
Referenced by fioPacketResultRead, fioPacketResultWrite, MCCNotify.
int MCCNotify(enum MCC_CHANNEL chID, u32 notify)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint, MCCGetConnectionStatus, NotifyCompulsorily.
Referenced by fioPacketSendPacket, FIOQuery, ttyFlush, TTYQuery.
u32 MCCSetChannelEventMask(enum MCC_CHANNEL chID, u32 event)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint.
Referenced by fioPacketReceiveResult, fioPacketResultRead, fioPacketResultWrite, fioPacketSendPacket, TTYExit, TTYInit.
int MCCOpen(enum MCC_CHANNEL chID, u8 blockSize, MCC_CBEvent callbackEvent)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, exit, FlushChannelInfo, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint, NotifyCompulsorily, SearchFreeBlocks.
Referenced by FIOInit, fioPacketResultRead, fioPacketResultWrite, MCCStreamOpen, TTYInit.
int MCCClose(enum MCC_CHANNEL chID)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, ClearChannelInfo, exit, FlushChannelInfo, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyCompulsorily.
Referenced by FIOExit, fioPacketResultRead, fioPacketResultWrite, MCCExit, MCCStreamClose, TTYExit.
int MCCLock(enum MCC_CHANNEL chID)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, exit, FlushChannelInfo, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyChannelEvent.
int MCCUnlock(enum MCC_CHANNEL chID)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, exit, FlushChannelInfo, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyChannelEvent.
int MCCRead(enum MCC_CHANNEL chID, u32 offset, void *data, s32 size, enum MCC_SYNC_STATE async)
References AsyncResourceIsBusy, AsyncResourceStateBusy, CARD_MAX_MOUNT_STEP, DCInvalidateRange, exit, gLastError, gMccInitialized, HIORead, HIOReadAsync, IsChannelOpened, LoadChannelInfo, MCCCheckAsyncDone, mccDebugPrint, MCCRxCallback, NotifyChannelEvent, size.
Referenced by fioPacketReceiveResult, fioPacketResultRead, MCCStreamRead.
int MCCWrite(enum MCC_CHANNEL chID, u32 offset, void *data, s32 size, enum MCC_SYNC_STATE async)
References AsyncResourceIsBusy, AsyncResourceStateBusy, CARD_MAX_MOUNT_STEP, DCFlushRange, exit, gLastError, gMccInitialized, HIOWrite, HIOWriteAsync, IsChannelOpened, LoadChannelInfo, MCCCheckAsyncDone, mccDebugPrint, MCCTxCallback, NotifyChannelEvent, size.
Referenced by fioPacketSendPacket, MCCStreamWrite, ttyWrite.
int MCCCheckAsyncDone()
References AsyncResourceClearState, AsyncResourceGetChannel, AsyncResourceGetMode, AsyncResourceGetStat, CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, NotifyChannelEvent.
Referenced by MCCRead, MCCWrite.