mcc.c
volatile int gIsChannelinfoDirty
Referenced by LoadChannelInfo, SetChannelInfoDirty.
void(*volatile gCallbackSysEvent) (enum MCC_SYSEVENT))(enum MCC_SYSEVENT)
Referenced by MailboxCheck, MCCInit, mccInitializeCheck.
int gOtherSideInitDone
Referenced by MailboxCheck, mccInitializeCheck.
volatile u16 gLastError
Referenced by IsChannelOpened, MailboxCheck, MakeMemoryMap, MCCCheckAsyncDone, MCCClose, MCCEnumDevices, MCCExit, MCCGetChannelInfo, MCCGetConnectionStatus, MCCGetFreeBlocks, MCCGetLastError, MCCInit, mccInitializeCheck, MCCLock, MCCNotify, MCCOpen, MCCPing, MCCRead, MCCSetChannelEventMask, MCCStreamRead, MCCStreamWrite, MCCUnlock, MCCWrite, NotifyChannelEvent, NotifyCompulsorily.
int gMccInitialized
Referenced by MailboxCheck, MCCCheckAsyncDone, MCCClose, MCCExit, MCCGetChannelInfo, MCCGetConnectionStatus, MCCGetFreeBlocks, MCCInit, mccInitializeCheck, MCCLock, MCCNotify, MCCOpen, MCCPing, MCCRead, MCCSetChannelEventMask, MCCStreamRead, MCCStreamWrite, MCCUnlock, MCCWrite.
int gMccSession
Referenced by MailboxCheck, MCCExit, mccInitializeCheck.
volatile int gPingFlag
Referenced by MailboxCheck, MCCPing.
volatile u16 gAsyncResourceStatus
Referenced by AsyncResourceClearState, AsyncResourceGetChannel, AsyncResourceGetMode, AsyncResourceGetStat, AsyncResourceSetState, AsyncResourceStateBusy.
static MCC_ChannelInfo gChannelInfo[16] ALIGN(32)
static void mccDebugPrint(char *str)
Referenced by LoadChannelInfo, MailboxCheck, MCCClose, MCCExit, MCCGetChannelInfo, MCCGetConnectionStatus, MCCGetFreeBlocks, MCCGetLastError, MCCInit, mccInitializeCheck, MCCLock, MCCNotify, MCCOpen, MCCPing, MCCRead, MCCSetChannelEventMask, MCCUnlock, MCCWrite, NotifyChannelEvent, NotifyCompulsorily, WaitAMinute.
static void callbackEventStream(enum MCC_CHANNEL chID, u32 event, u32 value)
References CARD_MAX_MOUNT_STEP.
Referenced by MCCStreamOpen.
static int SetUsbAdapterMode(u8 mode)
References CARD_MAX_MOUNT_STEP, DCFlushRange, DCInvalidateRange, HIORead, HIOWrite.
Referenced by MCCInit.
static u8 GetUsbAdapterMode(void)
References CARD_MAX_MOUNT_STEP, DCInvalidateRange, HIORead.
Referenced by MCCInit.
static int InitializeCodeClear(void)
References CARD_MAX_MOUNT_STEP, DCFlushRange, HIOWrite.
Referenced by mccInitializeCheck.
static int InitializeCodeSet(void)
References CARD_MAX_MOUNT_STEP, DCFlushRange, HIOWrite.
Referenced by mccInitializeCheck.
static int InitializeCodeCheck(void)
References CARD_MAX_MOUNT_STEP, DCInvalidateRange, HIORead.
Referenced by mccInitializeCheck.
static void AsyncResourceClearState(void)
References gAsyncResourceStatus.
Referenced by AsyncResourceStateBusy, MCCCheckAsyncDone, MCCInit.
static void AsyncResourceSetState(u16 state)
References gAsyncResourceStatus.
Referenced by AsyncResourceStateBusy, AsyncResourceStateDone.
static void AsyncResourceStateBusy(u8 channel, u16 mode)
References AsyncResourceClearState, AsyncResourceSetState, CARD_MAX_MOUNT_STEP, gAsyncResourceStatus.
Referenced by MCCRead, MCCWrite.
static void AsyncResourceStateDone(void)
References AsyncResourceSetState.
Referenced by MCCRxCallback, MCCTxCallback.
static u16 AsyncResourceGetStat(void)
References gAsyncResourceStatus.
Referenced by AsyncResourceIsBusy, MCCCheckAsyncDone.
static u16 AsyncResourceGetMode(void)
References gAsyncResourceStatus.
Referenced by MCCCheckAsyncDone.
static u8 AsyncResourceGetChannel(void)
References gAsyncResourceStatus.
Referenced by MCCCheckAsyncDone.
static int AsyncResourceIsBusy(void)
References AsyncResourceGetStat.
Referenced by MCCClose, MCCGetConnectionStatus, MCCLock, MCCOpen, MCCRead, MCCUnlock, MCCWrite.
static int LoadChannelInfo(MCC_ChannelInfo *info)
References CARD_MAX_MOUNT_STEP, DCInvalidateRange, gIsChannelinfoDirty, HIORead, MCC_ChannelInfo::info, mccDebugPrint, SetChannelInfoDirty.
Referenced by MailboxCheck, MCCClose, MCCGetChannelInfo, MCCGetFreeBlocks, MCCLock, MCCNotify, MCCOpen, MCCRead, MCCSetChannelEventMask, MCCStreamRead, MCCStreamWrite, MCCUnlock, MCCWrite, NotifyChannelEvent.
static int FlushChannelInfo(MCC_ChannelInfo *info)
References CARD_MAX_MOUNT_STEP, DCFlushRange, HIOWrite, MCC_ChannelInfo::info, NotifyCompulsorily, SetChannelInfoDirty.
Referenced by MCCClose, mccInitializeCheck, MCCLock, MCCOpen, MCCUnlock.
static void SetChannelInfoDirty(int dirty)
References CARD_MAX_MOUNT_STEP, gIsChannelinfoDirty.
Referenced by FlushChannelInfo, LoadChannelInfo, MailboxCheck, MCCInit, mccInitializeCheck.
static void ClearChannelInfo(int i)
References CARD_MAX_MOUNT_STEP, NULL.
Referenced by MCCClose, MCCInit, mccInitializeCheck.
static void MakeMemoryMap(u8 *map)
References CARD_MAX_MOUNT_STEP, gLastError.
Referenced by SearchFreeBlocks.
static int IsChannelOpened(enum MCC_CHANNEL chID)
References CARD_MAX_MOUNT_STEP, exit, gLastError.
Referenced by MailboxCheck, MCCClose, MCCExit, MCCLock, MCCRead, MCCSetChannelEventMask, MCCUnlock, MCCWrite, NotifyChannelEvent.
static u8 SearchFreeBlocks(enum MCC_MODE mode, u8 *index)
References CARD_MAX_MOUNT_STEP, index, MakeMemoryMap.
Referenced by MCCGetFreeBlocks, MCCOpen.
static int NotifyCompulsorily(enum MCC_CHANNEL chID, u32 notify, u32 timeout)
References CARD_MAX_MOUNT_STEP, exit, gLastError, HIOReadStatus, HIOWriteMailbox, mccDebugPrint, OSGetTick, OSTicksToSeconds, status.
Referenced by FlushChannelInfo, MailboxCheck, MCCClose, MCCNotify, MCCOpen, MCCPing, NotifyChannelEvent, NotifyInit, NotifyInitDone.
static int NotifyInit(void)
References CARD_MAX_MOUNT_STEP, NotifyCompulsorily.
Referenced by MCCInit.
static int NotifyInitDone(void)
References CARD_MAX_MOUNT_STEP, NotifyCompulsorily.
Referenced by mccInitializeCheck.
static int NotifyChannelEvent(enum MCC_CHANNEL chID, u32 notify)
References CARD_MAX_MOUNT_STEP, gLastError, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyCompulsorily.
Referenced by MCCCheckAsyncDone, MCCLock, MCCRead, MCCUnlock, MCCWrite.
static int WaitAMinute(int timeout, volatile int *flag, int value)
References CARD_MAX_MOUNT_STEP, mccDebugPrint, OSGetTick, OSTicksToSeconds.
Referenced by MCCInit, mccInitializeCheck, MCCStreamRead, MCCStreamWrite.
static void MailboxCheck(void)
References CARD_MAX_MOUNT_STEP, gCallbackSysEvent, gLastError, gMccInitialized, gMccSession, gOtherSideInitDone, gPingFlag, HIOReadMailbox, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyCompulsorily, SetChannelInfoDirty.
Referenced by MCCExiCallback.
static void MCCExiCallback(void)
References MailboxCheck.
Referenced by MCCInit.
static void MCCTxCallback(void)
References AsyncResourceStateDone.
Referenced by MCCWrite.
static void MCCRxCallback(void)
References AsyncResourceStateDone.
Referenced by MCCRead.
static int mccInitializeCheck(u8 timeout)
References CARD_MAX_MOUNT_STEP, ClearChannelInfo, FlushChannelInfo, gCallbackSysEvent, gLastError, gMccInitialized, gMccSession, gOtherSideInitDone, InitializeCodeCheck, InitializeCodeClear, InitializeCodeSet, mccDebugPrint, NotifyInitDone, SetChannelInfoDirty, WaitAMinute.
Referenced by MCCInit.
int MCCStreamOpen(enum MCC_CHANNEL chID, u8 blockSize)
References callbackEventStream, CARD_MAX_MOUNT_STEP, MCCOpen.
Referenced by fioPacketResultRead, fioPacketResultWrite.
int MCCStreamClose(enum MCC_CHANNEL chID)
References CARD_MAX_MOUNT_STEP, MCCClose.
Referenced by fioPacketResultRead, fioPacketResultWrite.
int MCCStreamWrite(enum MCC_CHANNEL chID, void *data, u32 dataBlockSize)
References MCC_Info::blockLength, CARD_MAX_MOUNT_STEP, exit, gLastError, gMccInitialized, LoadChannelInfo, MCCGetChannelInfo, MCCWrite, WaitAMinute.
Referenced by fioPacketResultWrite.
u32 MCCStreamRead(enum MCC_CHANNEL chID, void *data)
References MCC_Info::blockLength, CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, MCCGetChannelInfo, MCCRead, WaitAMinute.
Referenced by fioPacketResultRead.
int MCCInit(enum MCC_EXI exiChannel, u8 timeout, MCC_CBSysEvent callbackSysEvent)
References AsyncResourceClearState, CARD_MAX_MOUNT_STEP, ClearChannelInfo, gCallbackSysEvent, GetUsbAdapterMode, gLastError, gMccInitialized, HIOInit, HIOReadMailbox, HIOReadStatus, mccDebugPrint, MCCExiCallback, mccInitializeCheck, NotifyInit, SetChannelInfoDirty, SetUsbAdapterMode, status, WaitAMinute.
Referenced by FIOInit, TTYInit.
void MCCExit(void)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, gMccSession, IsChannelOpened, MCCClose, mccDebugPrint.
int MCCPing(void)
References gLastError, gMccInitialized, gPingFlag, mccDebugPrint, NotifyCompulsorily.
int MCCEnumDevices(MCC_CBEnumDevices callbackEnumDevices)
References CARD_MAX_MOUNT_STEP, gLastError, HIOEnumDevices, NULL.
u8 MCCGetFreeBlocks(enum MCC_MODE mode)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint, NULL, SearchFreeBlocks.
u8 MCCGetLastError(void)
References gLastError, mccDebugPrint.
Referenced by fioPacketResultRead.
int MCCGetChannelInfo(enum MCC_CHANNEL chID, MCC_Info *info)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint.
Referenced by MCCGetConnectionStatus, MCCStreamRead, MCCStreamWrite, ShowChannelInfo, ShowChannelInfo.
int MCCGetConnectionStatus(enum MCC_CHANNEL chID, enum MCC_CONNECT *connect)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, MCC_Info::connect, gLastError, gMccInitialized, mccDebugPrint, MCCGetChannelInfo.
Referenced by fioPacketResultRead, fioPacketResultWrite, MCCNotify.
int MCCNotify(enum MCC_CHANNEL chID, u32 notify)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint, MCCGetConnectionStatus, NotifyCompulsorily.
Referenced by fioPacketSendPacket, FIOQuery, ttyFlush, TTYQuery.
u32 MCCSetChannelEventMask(enum MCC_CHANNEL chID, u32 event)
References CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint.
Referenced by fioPacketReceiveResult, fioPacketResultRead, fioPacketResultWrite, fioPacketSendPacket, TTYExit, TTYInit.
int MCCOpen(enum MCC_CHANNEL chID, u8 blockSize, MCC_CBEvent callbackEvent)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, exit, FlushChannelInfo, gLastError, gMccInitialized, LoadChannelInfo, mccDebugPrint, NotifyCompulsorily, SearchFreeBlocks.
Referenced by FIOInit, fioPacketResultRead, fioPacketResultWrite, MCCStreamOpen, TTYInit.
int MCCClose(enum MCC_CHANNEL chID)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, ClearChannelInfo, exit, FlushChannelInfo, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyCompulsorily.
Referenced by FIOExit, fioPacketResultRead, fioPacketResultWrite, MCCExit, MCCStreamClose, TTYExit.
int MCCLock(enum MCC_CHANNEL chID)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, exit, FlushChannelInfo, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyChannelEvent.
int MCCUnlock(enum MCC_CHANNEL chID)
References AsyncResourceIsBusy, CARD_MAX_MOUNT_STEP, exit, FlushChannelInfo, gLastError, gMccInitialized, IsChannelOpened, LoadChannelInfo, mccDebugPrint, NotifyChannelEvent.
int MCCRead(enum MCC_CHANNEL chID, u32 offset, void *data, s32 size, enum MCC_SYNC_STATE async)
References AsyncResourceIsBusy, AsyncResourceStateBusy, CARD_MAX_MOUNT_STEP, DCInvalidateRange, exit, gLastError, gMccInitialized, HIORead, HIOReadAsync, IsChannelOpened, LoadChannelInfo, MCCCheckAsyncDone, mccDebugPrint, MCCRxCallback, NotifyChannelEvent, size.
Referenced by fioPacketReceiveResult, fioPacketResultRead, MCCStreamRead.
int MCCWrite(enum MCC_CHANNEL chID, u32 offset, void *data, s32 size, enum MCC_SYNC_STATE async)
References AsyncResourceIsBusy, AsyncResourceStateBusy, CARD_MAX_MOUNT_STEP, DCFlushRange, exit, gLastError, gMccInitialized, HIOWrite, HIOWriteAsync, IsChannelOpened, LoadChannelInfo, MCCCheckAsyncDone, mccDebugPrint, MCCTxCallback, NotifyChannelEvent, size.
Referenced by fioPacketSendPacket, MCCStreamWrite, ttyWrite.
int MCCCheckAsyncDone()
References AsyncResourceClearState, AsyncResourceGetChannel, AsyncResourceGetMode, AsyncResourceGetStat, CARD_MAX_MOUNT_STEP, gLastError, gMccInitialized, NotifyChannelEvent.
Referenced by MCCRead, MCCWrite.