mix.c
u16 __MIXVolumeTable[965][965]
Referenced by __MIXGetVolume.
int __MIXPanTableL[128][128]
Referenced by __MIXGetPanL.
int __MIXPanTableR[128][128]
Referenced by __MIXGetPanR.
u8 __MIXAIVolumeTable[50][50]
Referenced by MIXUpdateSettings.
struct MIXChannel __MIXChannel[64][64]
Referenced by MIXAdjustAuxA, MIXAdjustAuxB, MIXAdjustFader, MIXAdjustInput, MIXAdjustPan, MIXAdjustSPan, MIXAuxAIsPostFader, MIXAuxAPostFader, MIXAuxAPreFader, MIXAuxBIsPostFader, MIXAuxBPostFader, MIXAuxBPreFader, MIXGetAuxA, MIXGetAuxB, MIXGetFader, MIXGetInput, MIXGetPan, MIXGetSPan, MIXInit, MIXInitChannel, MIXIsMute, MIXMute, MIXReleaseChannel, MIXResetControls, MIXSetAuxA, MIXSetAuxB, MIXSetFader, MIXSetInput, MIXSetPan, MIXSetSPan, MIXUnMute, MIXUpdateSettings.
int __MIXDvdStreamAttenCurrent
Referenced by MIXInit, MIXUpdateSettings.
int __MIXDvdStreamAttenUser
Referenced by MIXGetDvdStreamFader, MIXInit, MIXSetDvdStreamFader, MIXUpdateSettings.
static u16 __MIXGetVolume(int db)
References __MIXVolumeTable, CARD_MAX_MOUNT_STEP.
Referenced by MIXInitChannel, MIXUpdateSettings.
static int __MIXGetPanL(int pan)
References __MIXPanTableL, CARD_MAX_MOUNT_STEP, MIXChannel::pan.
Referenced by __MIXResetChannel, __MIXSetPan.
static int __MIXGetPanR(int pan)
References __MIXPanTableR, CARD_MAX_MOUNT_STEP, MIXChannel::pan.
Referenced by __MIXResetChannel, __MIXSetPan.
static void __MIXResetChannel(struct MIXChannel *channel)
References __MIXGetPanL, __MIXGetPanR, CARD_MAX_MOUNT_STEP.
Referenced by MIXInit, MIXResetControls.
static void __MIXSetPan(struct MIXChannel *channel)
References __MIXGetPanL, __MIXGetPanR, CARD_MAX_MOUNT_STEP.
Referenced by MIXAdjustPan, MIXAdjustSPan, MIXInitChannel, MIXSetPan, MIXSetSPan.
static int __MIXClampPan(int pan)
References MIXChannel::pan.
Referenced by MIXAdjustPan, MIXAdjustSPan, MIXSetPan, MIXSetSPan.
void MIXInit(void)
References __MIXChannel, __MIXDvdStreamAttenCurrent, __MIXDvdStreamAttenUser, __MIXResetChannel, CARD_MAX_MOUNT_STEP.
void MIXQuit(void)
void MIXInitChannel(AXVPB *axvpb, u32 mode, int input, int auxA, int auxB, int pan, int span, int fader)
References __MIXChannel, __MIXGetVolume, __MIXSetPan, MIXChannel::auxA, MIXChannel::auxB, AX_SYNC_FLAG_COPYAXPBMIX, AX_SYNC_FLAG_COPYMXRCTRL, AX_SYNC_FLAG_COPYVOL, MIXChannel::axvpb, CARD_MAX_MOUNT_STEP, _AXPBVE::currentDelta, _AXPBVE::currentVolume, MIXChannel::fader, _AXVPB::index, MIXChannel::input, _AXPB::mix, _AXPB::mixerCtrl, MIXChannel::mode, OSDisableInterrupts, OSRestoreInterrupts, MIXChannel::pan, _AXVPB::pb, MIXChannel::span, _AXVPB::sync, _AXPBMIX::vAuxAL, _AXPBMIX::vAuxAR, _AXPBMIX::vAuxAS, _AXPBMIX::vAuxBL, _AXPBMIX::vAuxBR, _AXPBMIX::vAuxBS, _AXPB::ve, _AXPBMIX::vS.
Referenced by __SYNNoteOn.
void MIXReleaseChannel(AXVPB *axvpb)
References __MIXChannel, MIXChannel::axvpb, CARD_MAX_MOUNT_STEP, _AXVPB::index.
Referenced by __SYNClearVoiceReferences, __SYNNoteOn, __SYNServiceVoice, SYNQuitSynth.
void MIXResetControls(AXVPB *p)
References __MIXChannel, __MIXResetChannel, CARD_MAX_MOUNT_STEP.
void MIXSetInput(AXVPB *p, int dB)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::input.
Referenced by __SYNUpdateMix.
void MIXAdjustInput(AXVPB *p, int dB)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::input.
int MIXGetInput(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::input.
void MIXAuxAPostFader(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::mode.
void MIXAuxAPreFader(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::mode.
int MIXAuxAIsPostFader(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP.
void MIXSetAuxA(AXVPB *p, int dB)
References __MIXChannel, MIXChannel::auxA, CARD_MAX_MOUNT_STEP.
Referenced by __SYNUpdateMix.
void MIXAdjustAuxA(AXVPB *p, int dB)
References __MIXChannel, MIXChannel::auxA, CARD_MAX_MOUNT_STEP.
int MIXGetAuxA(AXVPB *p)
References __MIXChannel, MIXChannel::auxA, CARD_MAX_MOUNT_STEP.
void MIXAuxBPostFader(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::mode.
void MIXAuxBPreFader(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::mode.
int MIXAuxBIsPostFader(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP.
void MIXSetAuxB(AXVPB *p, int dB)
References __MIXChannel, MIXChannel::auxB, CARD_MAX_MOUNT_STEP.
Referenced by __SYNUpdateMix.
void MIXAdjustAuxB(AXVPB *p, int dB)
References __MIXChannel, MIXChannel::auxB, CARD_MAX_MOUNT_STEP.
int MIXGetAuxB(AXVPB *p)
References __MIXChannel, MIXChannel::auxB, CARD_MAX_MOUNT_STEP.
void MIXSetPan(AXVPB *p, int pan)
References __MIXChannel, __MIXClampPan, __MIXSetPan, CARD_MAX_MOUNT_STEP, MIXChannel::pan.
Referenced by __SYNUpdateMix.
void MIXAdjustPan(AXVPB *p, int pan)
References __MIXChannel, __MIXClampPan, __MIXSetPan, CARD_MAX_MOUNT_STEP, MIXChannel::pan.
int MIXGetPan(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::pan.
void MIXSetSPan(AXVPB *p, int span)
References __MIXChannel, __MIXClampPan, __MIXSetPan, CARD_MAX_MOUNT_STEP, MIXChannel::span.
void MIXAdjustSPan(AXVPB *p, int span)
References __MIXChannel, __MIXClampPan, __MIXSetPan, CARD_MAX_MOUNT_STEP, MIXChannel::span.
int MIXGetSPan(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::span.
void MIXMute(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::mode.
void MIXUnMute(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::mode.
int MIXIsMute(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP.
void MIXSetFader(AXVPB *p, int dB)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::fader.
Referenced by __SYNUpdateMix.
void MIXAdjustFader(AXVPB *p, int dB)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::fader.
int MIXGetFader(AXVPB *p)
References __MIXChannel, CARD_MAX_MOUNT_STEP, MIXChannel::fader.
void MIXSetDvdStreamFader(int dB)
References __MIXDvdStreamAttenUser, CARD_MAX_MOUNT_STEP.
int MIXGetDvdStreamFader(void)
References __MIXDvdStreamAttenUser.
void MIXUpdateSettings(void)
References __MIXAIVolumeTable, __MIXChannel, __MIXDvdStreamAttenCurrent, __MIXDvdStreamAttenUser, __MIXGetVolume, AISetStreamVolLeft, AISetStreamVolRight, MIXChannel::axvpb, CARD_MAX_MOUNT_STEP, _AXPBVE::currentDelta, _AXPBVE::currentVolume, _AXPB::mix, _AXPB::mixerCtrl, _AXVPB::pb, _AXVPB::sync, _AXPBMIX::vAuxAL, _AXPBMIX::vAuxAR, _AXPBMIX::vAuxAS, _AXPBMIX::vAuxBL, _AXPBMIX::vAuxBR, _AXPBMIX::vAuxBS, _AXPBMIX::vDeltaAuxAL, _AXPBMIX::vDeltaAuxAR, _AXPBMIX::vDeltaAuxAS, _AXPBMIX::vDeltaAuxBL, _AXPBMIX::vDeltaAuxBR, _AXPBMIX::vDeltaAuxBS, _AXPBMIX::vDeltaL, _AXPBMIX::vDeltaR, _AXPBMIX::vDeltaS, _AXPB::ve, _AXPBMIX::vS.