mtx.h
VECSquareMag
VECNormalize
VECAdd
VECDotProduct
VECSquareDistance
VECCrossProduct
MTXMultVec
MTXMultVecArray
MTXCopy
MTXConcat
MTXInverse
MTXTranspose
MTXIdentity
MTXReorder
MTXROMultVecArray
MTXROSkin2VecArray
MTXROMultS16VecArray
MTXMultS16VecArray
typedef struct Vec * VecPtr
typedef struct Vec Point3d
typedef struct Vec * Point3dPtr
typedef struct S16Vec * S16VecPtr
typedef struct Quaternion * QuaternionPtr
typedef struct Quaternion Qtrn
typedef struct Quaternion * QtrnPtr
typedef f32 Mtx[3][4][3][4]
typedef f32 Mtx44[4][4][4][4]
typedef f32(* MtxPtr)[4])[4]
typedef f32(* Mtx44Ptr)[4])[4]
typedef f32 ROMtx[4][3][4][3]
typedef f32(* ROMtxPtr)[3])[3]
void MTXScale(Mtx m, f32 xS, f32 yS, f32 zS)
References CARD_MAX_MOUNT_STEP.
Referenced by DEMOLoadFont, LoadSheet.
void MTXOrtho(Mtx44 m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 f)
Referenced by DEMOSetupScrnSpc, G2DInitWorld.
void C_MTXFrustum(Mtx44 m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 f)
void C_MTXPerspective(Mtx44 m, f32 fovY, f32 aspect, f32 n, f32 f)
void C_MTXLookAt(Mtx m, Point3dPtr camPos, VecPtr camUp, Point3dPtr target)
void MTXRotRad(Mtx m, s8 axis, f32 rad)
References CARD_MAX_MOUNT_STEP, cosf, MTXRotTrig, sinf.
void MTXRotTrig(Mtx m, s8 axis, f32 sinA, f32 cosA)
References CARD_MAX_MOUNT_STEP, FALSE.
Referenced by MTXRotRad.
void MTXRotAxisRad(Mtx m, Vec *axis, f32 rad)
References CARD_MAX_MOUNT_STEP, cosf, sinf, VECNormalize.
void MTXTrans(Mtx m, f32 xT, f32 yT, f32 zT)
References CARD_MAX_MOUNT_STEP.
void MTXTransApply(Mtx src, Mtx dst, f32 xT, f32 yT, f32 zT)
References CARD_MAX_MOUNT_STEP, src.
void MTXScaleApply(Mtx src, Mtx dst, f32 xS, f32 yS, f32 zS)
References CARD_MAX_MOUNT_STEP, src.
void MTXQuat(Mtx m, QuaternionPtr q)
References CARD_MAX_MOUNT_STEP.
void MTXReflect(Mtx m, Vec *p, Vec *n)
References CARD_MAX_MOUNT_STEP, VECDotProduct.
void MTXLookAt(Mtx m, Vec *camPos, Vec *camUp, Vec *target)
References CARD_MAX_MOUNT_STEP, VECCrossProduct, VECNormalize, Vec::x, Vec::y, Vec::z.
Referenced by G2DSetCamera.
void MTXLightFrustum(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 scaleS, f32 scaleT, f32 transS, f32 transT)
References CARD_MAX_MOUNT_STEP, tmp.
void MTXLightPerspective(Mtx m, f32 fovY, f32 aspect, f32 scaleS, f32 scaleT, f32 transS, f32 transT)
References CARD_MAX_MOUNT_STEP.
void MTXLightOrtho(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 scaleS, f32 scaleT, f32 transS, f32 transT)
References CARD_MAX_MOUNT_STEP, tmp.
void C_MTXIdentity(Mtx m)
References CARD_MAX_MOUNT_STEP.
Referenced by __PERFDrawInit.
void C_MTXCopy(Mtx src, Mtx dst)
References CARD_MAX_MOUNT_STEP, src.
Referenced by C_MTXConcat, C_MTXInverse, C_MTXInvXpose, C_MTXTranspose.
void C_MTXConcat(Mtx a, Mtx b, Mtx ab)
References C_MTXCopy, CARD_MAX_MOUNT_STEP.
void C_MTXTranspose(Mtx src, Mtx xPose)
References C_MTXCopy, CARD_MAX_MOUNT_STEP, src.
u32 C_MTXInverse(Mtx src, Mtx inv)
References C_MTXCopy, CARD_MAX_MOUNT_STEP, src.
u32 C_MTXInvXpose(Mtx src, Mtx invX)
References C_MTXCopy, CARD_MAX_MOUNT_STEP, src.
void PSMTXIdentity(Mtx m)
Referenced by __PERFDrawInit.
void PSMTXCopy(Mtx src, Mtx dst)
void PSMTXConcat(Mtx mA, Mtx mB, Mtx mAB)
void PSMTXTranspose(Mtx src, Mtx xPose)
u32 PSMTXInverse(Mtx src, Mtx inv)
u32 PSMTXInvXpose(Mtx src, Mtx invX)
void MTXInitStack(MTXStack *sPtr, u32 numMtx)
References CARD_MAX_MOUNT_STEP.
Mtx * MTXPush(MTXStack *sPtr, Mtx m)
References CARD_MAX_MOUNT_STEP, MTXCopy, NULL.
Mtx * MTXPushFwd(MTXStack *sPtr, Mtx m)
References CARD_MAX_MOUNT_STEP, MTXConcat, MTXCopy, NULL.
Mtx * MTXPushInv(MTXStack *sPtr, Mtx m)
References CARD_MAX_MOUNT_STEP, MTXConcat, MTXCopy, MTXInverse, NULL.
Mtx * MTXPushInvXpose(MTXStack *sPtr, Mtx m)
References CARD_MAX_MOUNT_STEP, MTXConcat, MTXCopy, MTXInverse, MTXTranspose, NULL.
Mtx * MTXPop(MTXStack *sPtr)
References CARD_MAX_MOUNT_STEP, NULL.
Mtx * MTXGetStackPtr(MTXStack *sPtr)
References CARD_MAX_MOUNT_STEP.
void MTXMultVecSR(Mtx44 m, Vec *src, Vec *dst)
References CARD_MAX_MOUNT_STEP, src.
void MTXMultVecArraySR(Mtx44 m, Vec *srcBase, Vec *dstBase, u32 count)
References CARD_MAX_MOUNT_STEP.
void C_MTXMultVec(Mtx44 m, Vec *src, Vec *dst)
References CARD_MAX_MOUNT_STEP, src.
void C_MTXMultVecArray(Mtx m, Vec *srcBase, Vec *dstBase, u32 count)
References CARD_MAX_MOUNT_STEP.
void PSMTXMultVec(Mtx44 m, Vec *src, Vec *dst)
void PSMTXMultVecArray(Mtx m, Vec *srcBase, Vec *dstBase, u32 count)
void PSMTXReorder(Mtx src, ROMtx dest)
void PSMTXROMultVecArray(ROMtx *m, Vec *srcBase, Vec *dstBase, u32 count)
void PSMTXROSkin2VecArray(ROMtx *m0, ROMtx *m1, f32 *wtBase, Vec *srcBase, Vec *dstBase, u32 count)
void PSMTXROMultS16VecArray(ROMtx *m, S16Vec *srcBase, Vec *dstBase, u32 count)
void PSMTXMultS16VecArray(Mtx44 *m, S16Vec *srcBase, Vec *dstBase, u32 count)
f32 VECMag(Vec *v)
References CARD_MAX_MOUNT_STEP, VECSquareMag.
void VECHalfAngle(Vec *a, Vec *b, Vec *half)
References CARD_MAX_MOUNT_STEP, VECAdd, VECDotProduct, VECNormalize, Vec::x, Vec::y, Vec::z.
void VECReflect(Vec *src, Vec *normal, Vec *dst)
References CARD_MAX_MOUNT_STEP, src, VECDotProduct, VECNormalize.
f32 VECDistance(Vec *a, Vec *b)
References CARD_MAX_MOUNT_STEP, VECSquareDistance.
void C_VECAdd(Vec *a, Vec *b, Vec *c)
References CARD_MAX_MOUNT_STEP, Vec::x, Vec::y, Vec::z.
void C_VECSubtract(Vec *a, Vec *b, Vec *c)
References CARD_MAX_MOUNT_STEP, Vec::x, Vec::y, Vec::z.
void C_VECScale(Vec *src, Vec *dst, f32 scale)
References CARD_MAX_MOUNT_STEP, src.
void C_VECNormalize(Vec *src, Vec *unit)
References CARD_MAX_MOUNT_STEP, src.
f32 C_VECSquareMag(Vec *v)
References CARD_MAX_MOUNT_STEP, Vec::x, Vec::y, Vec::z.
f32 C_VECDotProduct(Vec *a, Vec *b)
References CARD_MAX_MOUNT_STEP, Vec::x, Vec::y, Vec::z.
void C_VECCrossProduct(Vec *a, Vec *b, Vec *axb)
References CARD_MAX_MOUNT_STEP, Vec::x, Vec::y, Vec::z.
f32 C_VECSquareDistance(Vec *a, Vec *b)
References CARD_MAX_MOUNT_STEP, Vec::x, Vec::y, Vec::z.
void PSVECAdd(Vec *a, Vec *b, Vec *c)
void PSVECSubtract(Vec *a, Vec *b, Vec *c)
void PSVECScale(Vec *src, Vec *dst, f32 scale)
void PSVECNormalize(Vec *vec1, Vec *dst)
f32 PSVECSquareMag(Vec *vec1)
f32 PSVECDotProduct(Vec *vec1, Vec *vec2)
void PSVECCrossProduct(Vec *vec1, Vec *vec2, Vec *dst)
f32 PSVECSquareDistance(Vec *vec1, Vec *vec2)