mtx.c
qr0
float Unit01[2][2]
Referenced by PSMTXConcat.
f32 sinf(f32)
Referenced by GXDrawCylinder, GXDrawSphere, GXDrawTorus, MTXRotAxisRad, MTXRotRad.
f32 cosf(f32)
Referenced by GXDrawCylinder, GXDrawSphere, GXDrawTorus, GXInitLightSpot, MTXRotAxisRad, MTXRotRad.
void C_MTXIdentity(Mtx m)
References CARD_MAX_MOUNT_STEP.
Referenced by __PERFDrawInit.
void PSMTXIdentity(register Mtx m)
References CARD_MAX_MOUNT_STEP, qr0.
void C_MTXCopy(Mtx src, Mtx dst)
References CARD_MAX_MOUNT_STEP, src.
Referenced by C_MTXConcat, C_MTXInverse, C_MTXInvXpose, C_MTXTranspose.
asm void PSMTXCopy(register Mtx src, register Mtx dst)
References CARD_MAX_MOUNT_STEP, qr0, src.
void C_MTXConcat(Mtx a, Mtx b, Mtx ab)
References C_MTXCopy, CARD_MAX_MOUNT_STEP.
asm void PSMTXConcat(register Mtx mA, register Mtx mB, register Mtx mAB)
References blr, CARD_MAX_MOUNT_STEP, qr0, Unit01.
void C_MTXTranspose(Mtx src, Mtx xPose)
References C_MTXCopy, CARD_MAX_MOUNT_STEP, src.
void PSMTXTranspose(register Mtx src, register Mtx xPose)
References CARD_MAX_MOUNT_STEP, qr0, src.
u32 C_MTXInverse(Mtx src, Mtx inv)
References C_MTXCopy, CARD_MAX_MOUNT_STEP, src.
asm u32 PSMTXInverse(register Mtx src, register Mtx inv)
References blr, CARD_MAX_MOUNT_STEP, qr0, r3, src.
u32 C_MTXInvXpose(Mtx src, Mtx invX)
References C_MTXCopy, CARD_MAX_MOUNT_STEP, src.
asm u32 PSMTXInvXpose(register Mtx src, register Mtx invX)
References blr, CARD_MAX_MOUNT_STEP, qr0, r3, src.
void MTXRotRad(Mtx m, s8 axis, f32 rad)
References CARD_MAX_MOUNT_STEP, cosf, MTXRotTrig, sinf.
void MTXRotTrig(Mtx m, s8 axis, f32 sinA, f32 cosA)
References CARD_MAX_MOUNT_STEP, FALSE.
Referenced by MTXRotRad.
void MTXRotAxisRad(Mtx m, Vec *axis, f32 rad)
References CARD_MAX_MOUNT_STEP, cosf, sinf, VECNormalize.
void MTXTrans(Mtx m, f32 xT, f32 yT, f32 zT)
References CARD_MAX_MOUNT_STEP.
void MTXTransApply(Mtx src, Mtx dst, f32 xT, f32 yT, f32 zT)
References CARD_MAX_MOUNT_STEP, src.
void MTXScale(Mtx m, f32 xS, f32 yS, f32 zS)
References CARD_MAX_MOUNT_STEP.
Referenced by DEMOLoadFont, LoadSheet.
void MTXScaleApply(Mtx src, Mtx dst, f32 xS, f32 yS, f32 zS)
References CARD_MAX_MOUNT_STEP, src.
void MTXQuat(Mtx m, QuaternionPtr q)
References CARD_MAX_MOUNT_STEP.
void MTXReflect(Mtx m, Vec *p, Vec *n)
References CARD_MAX_MOUNT_STEP, VECDotProduct.
void MTXLookAt(Mtx m, Vec *camPos, Vec *camUp, Vec *target)
References CARD_MAX_MOUNT_STEP, VECCrossProduct, VECNormalize, Vec::x, Vec::y, Vec::z.
Referenced by G2DSetCamera.
void MTXLightFrustum(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 scaleS, f32 scaleT, f32 transS, f32 transT)
References CARD_MAX_MOUNT_STEP, tmp.
void MTXLightPerspective(Mtx m, f32 fovY, f32 aspect, f32 scaleS, f32 scaleT, f32 transS, f32 transT)
References CARD_MAX_MOUNT_STEP.
void MTXLightOrtho(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 scaleS, f32 scaleT, f32 transS, f32 transT)
References CARD_MAX_MOUNT_STEP, tmp.