os.h
OS_CACHED_REGION_PREFIX
OS_UNCACHED_REGION_PREFIX
OS_PHYSICAL_MASK
OS_BASE_CACHED
OS_BASE_UNCACHED
OS_BUS_CLOCK
OS_CORE_CLOCK
OS_TIMER_CLOCK
OSTicksToSeconds
OSTicksToMilliseconds
OSTicksToMicroseconds
OSSecondsToTicks
OSMillisecondsToTicks
OSNanosecondsToTicks
OSMicrosecondsToTicks
OS_CONSOLE_RETAIL
OS_CONSOLE_RETAIL2
OS_CONSOLE_RETAIL1
OS_CONSOLE_DEVHW2
OS_CONSOLE_DEVHW1
OS_CONSOLE_MINNOW
OS_CONSOLE_ARTHUR
OS_CONSOLE_PC_EMULATOR
OS_CONSOLE_EMULATOR
OS_CONSOLE_DEVELOPMENT
OS_SOUND_MODE_MONO
OS_SOUND_MODE_STEREO
OSRoundUp32B
OSRoundDown32B
OSPhysicalToCached
OSPhysicalToUncached
OSCachedToPhysical
OSUncachedToPhysical
OSCachedToUncached
OSUncachedToCached
typedef struct OSCalendarTime OSCalendarTime
u32 __OSBusClock
Referenced by GXInit, WriteCallback.
u32 __OSCoreClock
u32 OSGetPhysicalMemSize(void)
References BootInfo, CARD_MAX_MOUNT_STEP, OSBootInfo_s::memorySize, OSPhysicalToCached.
Referenced by __DEMOInitMem, LoadMemInfo.
u32 OSGetConsoleSimulatedMemSize(void)
References CARD_MAX_MOUNT_STEP, OSPhysicalToCached.
Referenced by __DEMOInitMem, LoadMemInfo.
u32 OSGetConsoleType(void)
References BootInfo, OSBootInfo_s::consoleType, OS_CONSOLE_ARTHUR.
Referenced by __DEMOInitMem, EXIInit, InitializeUART, OSInit.
void OSInit(void)
References __ArenaHi, __ArenaLo, __DVDLongFileNameFlag, __OSCacheInit, __OSContextInit, __OSInitAudioSystem, __OSInitSram, __OSInitSystemCall, __OSInterruptInit, __OSModuleInit, __OSResetSWInterruptHandler, __OSSetInterruptHandler, __OSThreadInit, __PADSpec, _stack_addr, OSBootInfo_s::arenaHi, OSBootInfo_s::arenaLo, AreWeInitialized, BI2DebugFlag, BootInfo, CARD_MAX_MOUNT_STEP, OSBootInfo_s::consoleType, EXIInit, OSBootInfo_s::memorySize, NULL, OS_CONSOLE_ARTHUR, OS_CONSOLE_DEVELOPMENT, OS_CONSOLE_DEVHW1, OS_CONSOLE_EMULATOR, OS_CONSOLE_MINNOW, OS_CONSOLE_PC_EMULATOR, OS_CONSOLE_RETAIL, OS_CONSOLE_RETAIL1, OSDisableInterrupts, OSEnableInterrupts, OSExceptionInit, OSGetArenaHi, OSGetArenaLo, OSGetConsoleType, OSPhysicalToCached, OSReport, OSSetArenaHi, OSSetArenaLo, SIInit.
Referenced by DEMOInit.
void * OSGetArenaHi(void)
References __OSArenaHi, __OSArenaLo, CARD_MAX_MOUNT_STEP.
Referenced by __DEMOInitMem, __fstLoad, LoadMemInfo, OSAllocFromArenaHi, OSInit.
void * OSGetArenaLo(void)
References __OSArenaHi, __OSArenaLo, CARD_MAX_MOUNT_STEP.
Referenced by __DEMOInitMem, LoadMemInfo, OSAllocFromArenaLo, OSInit.
void OSSetArenaHi(void *)
References __OSArenaHi, CARD_MAX_MOUNT_STEP.
Referenced by __fstLoad, LoadMemInfo, OSAllocFromArenaHi, OSInit.
void OSSetArenaLo(void *)
References __OSArenaLo, CARD_MAX_MOUNT_STEP.
Referenced by __DEMOInitMem, LoadMemInfo, OSAllocFromArenaLo, OSInit.
void * OSAllocFromArenaLo(u32 size, u32 align)
References CARD_MAX_MOUNT_STEP, OSGetArenaLo, OSSetArenaLo, ROUND, size.
void * OSAllocFromArenaHi(u32 size, u32 align)
References CARD_MAX_MOUNT_STEP, OSGetArenaHi, OSSetArenaHi, size, TRUNC.
void __OSPSInit()
References CARD_MAX_MOUNT_STEP, GQR0, ICFlashInvalidate, PPCMfhid2, PPCMthid2, r3.
Referenced by __declspec.
OSTick OSGetTick(void)
References blr, CARD_MAX_MOUNT_STEP, r3.
Referenced by __OSInitAudioSystem, __OSStopAudioSystem, DummyLen, FIOQuery, GetInitVal, MPDWaiting, NotifyCompulsorily, TTYQuery, ttyWaiting, WaitAMinute.
OSTime OSGetTime(void)
References blr, CARD_MAX_MOUNT_STEP, OSGetTime, r3, r4, r5.
Referenced by __AI_SRC_INIT, __AXDSPResumeCallback, __AXOutAiCallback, __AXOutNewFrame, __get_time, __GXAbortWait, __OSGetSystemTime, __OSSetTime, __VIInitI2C, AlarmHandler, CARDFormatAsync, CARDRenameAsync, CARDSetStatusAsync, CreateCallbackFat, DecrementerExceptionCallback, EXIProbe, InsertAlarm, OSCheckStopwatch, OSGetTime, OSSetAlarm, OSStartStopwatch, OSStopStopwatch, PADInit, PERFStartAutoSampling, SetTimer, SITransfer, SITransferNext, WriteCallback.
void OSTicksToCalendarTime(OSTime ticks, OSCalendarTime *td)
References BIAS, CARD_MAX_MOUNT_STEP, GetDates, MSEC_MAX, OS_SEC_TO_TICKS, OS_TICKS_TO_MSEC, OS_TICKS_TO_SEC, OS_TICKS_TO_USEC, OSSecondsToTicks, OSTicksToSeconds, SECS_IN_DAY, USEC_MAX.
OSTime OSCalendarTimeToTicks(OSCalendarTime *td)
References CARD_MAX_MOUNT_STEP, GetLeapDays, GetYearDays, MONTH_MAX, OS_MSEC_TO_TICKS, OS_SEC_TO_TICKS, OS_USEC_TO_TICKS, SECS_IN_DAY, SECS_IN_HOUR, SECS_IN_MIN, SECS_IN_YEAR.
BOOL OSEnableInterrupts(void)
References blr, CARD_MAX_MOUNT_STEP, FALSE, r3, r4.
Referenced by __AXOutNewFrame, __OSReboot, OSInit, SelectThread.
BOOL OSDisableInterrupts(void)
References __RAS_OSDisableInterrupts_begin, __RAS_OSDisableInterrupts_end, blr, CARD_MAX_MOUNT_STEP, FALSE, r3, r4.
Referenced by __AI_set_stream_sample_rate, __AXOutQuit, __AXServiceCallbackStack, __CARDGetControlBlock, __CARDPutControlBlock, __CARDSync, __DTKBackward, __DTKForward, __DVDCheckWaitingQueue, __DVDDequeueWaitingQueue, __DVDLowSetWAType, __DVDPopWaitingQueue, __DVDPrepareResetAsync, __DVDPushWaitingQueue, __GXSaveCPUFifoAux, __OSDoHotReset, __OSGetSystemTime, __OSMaskInterrupts, __OSReboot, __OSSetTime, __OSUnmaskInterrupts, __SEQPushSequenceList, __SEQRemoveSequenceFromList, __SITransfer, __SYNAddSynthToList, __SYNRemoveSynthFromList, __VIGetAdjustingValues, __VISetAdjustingValues, AIInitDMA, AIRegisterDMACallback, AIRegisterStreamCallback, AISetDSPSampleRate, AISetStreamPlayState, ARAlloc, ARFree, ARGetDMAStatus, ARInit, ARQFlushQueue, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest, ARRegisterDMACallback, ARStartDMA, AXAcquireVoice, AXFreeVoice, AXFXChorusInit, AXFXChorusSettings, AXFXChorusShutdown, AXFXDelayInit, AXFXDelaySettings, AXFXDelayShutdown, AXFXReverbHiInit, AXFXReverbHiSettings, AXFXReverbHiShutdown, AXFXReverbStdInit, AXFXReverbStdSettings, AXFXReverbStdShutdown, AXGetProfile, AXSetVoiceAddr, AXSetVoiceAdpcm, AXSetVoiceAdpcmLoop, AXSetVoiceCurrentAddr, AXSetVoiceDpop, AXSetVoiceEndAddr, AXSetVoiceFir, AXSetVoiceItdOn, AXSetVoiceItdTarget, AXSetVoiceLoop, AXSetVoiceLoopAddr, AXSetVoiceMix, AXSetVoicePriority, AXSetVoiceSrc, AXSetVoiceSrcRatio, AXSetVoiceSrcType, AXSetVoiceState, AXSetVoiceType, AXSetVoiceUpdateIncrement, AXSetVoiceUpdateWrite, AXSetVoiceVe, AXSetVoiceVeDelta, CARDCancel, CARDCheckExAsync, CARDMountAsync, CARDProbeEx, DBInitComm, DBQueryData, DBRead, DBWrite, DEMOWinClearBuffer, DEMOWinClearRow, DEMOWinClearWindow, DEMOWinDestroyWindow, DEMOWinLogPrintf, DEMOWinPrintfXY, DEMOWinRefresh, DEMOWinScrollWindow, DoUnmount, DSPAddTask, DSPAssertInt, DSPAssertTask, DSPCancelTask, DSPHalt, DSPInit, DSPReset, DSPUnhalt, DTKQueueTrack, DTKRemoveTrack, DVDCancel, DVDCancelAll, DVDCancelAllAsync, DVDCancelAsync, DVDCancelStream, DVDChangeDisk, DVDCheckDisk, DVDGetCommandBlockStatus, DVDGetDriveStatus, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInquiry, DVDLowSetResetCoverCallback, DVDPause, DVDPrepareStream, DVDReadPrio, DVDResume, DVDSeekPrio, DVDStopStreamAtEnd, EXIAttach, EXIDeselect, EXIDetach, EXIDma, EXIImm, EXILock, EXIProbe, EXISelect, EXISetExiCallback, EXISync, EXIUnlock, GXDisableBreakPt, GXEnableBreakPt, GXEndDisplayList, GXInitFifoPtrs, GXRedirectWriteGatherPipe, GXSetBreakPtCallback, GXSetCPUFifo, GXSetCurrentGXThread, GXSetDrawDone, GXSetDrawDoneCallback, GXSetDrawSync, GXSetDrawSyncCallback, GXSetGPFifo, GXWaitDrawDone, issueCommand, LCEnable, LockSram, MIXInitChannel, OSCancelAlarm, OSCancelThread, OSCheckActiveThreads, OSCreateThread, OSDetachThread, OSDisableScheduler, OSDumpContext, OSEnableScheduler, OSExitThread, OSGetResetSwitchState, OSInit, OSJamMessage, OSJoinThread, OSLockMutex, OSPanic, OSReceiveMessage, OSResetSystem, OSResumeThread, OSSendMessage, OSSetAbsAlarm, OSSetAlarm, OSSetInterruptMask, OSSetPeriodicAlarm, OSSetResetCallback, OSSetThreadPriority, OSSleepThread, OSStartTimer, OSStopTimer, OSSuspendThread, OSTryLockMutex, OSUnlockMutex, OSWaitCond, OSWakeupThread, OSYieldThread, PADControlAllMotors, PADControlMotor, PADDisable, PADRead, PADRecalibrate, PADReset, PADSetAnalogMode, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartFrame, PERFStopAutoSampling, PopWaitingQueuePrio, Run, SelectThread, SEQSetState, SIDisablePolling, SIEnablePolling, SISetXY, SISync, SITransfer, SYNQuitSynth, VIConfigure, VIConfigurePan, VIFlush, VIGetCurrentLine, VIGetDTVStatus, VIGetNextField, VISet3D, VISetBlack, VISetNextFrameBuffer, VISetNextRightFrameBuffer, VISetPostRetraceCallback, VISetPreRetraceCallback, VIWaitForRetrace.
BOOL OSRestoreInterrupts(BOOL level)
Referenced by __AI_set_stream_sample_rate, __AXOutNewFrame, __AXOutQuit, __AXServiceCallbackStack, __CARDGetControlBlock, __CARDPutControlBlock, __CARDSync, __DTKBackward, __DTKForward, __DVDCheckWaitingQueue, __DVDDequeueWaitingQueue, __DVDLowSetWAType, __DVDPopWaitingQueue, __DVDPrepareResetAsync, __DVDPushWaitingQueue, __GXSaveCPUFifoAux, __OSGetSystemTime, __OSSetTime, __SEQPushSequenceList, __SEQRemoveSequenceFromList, __SITransfer, __SYNAddSynthToList, __SYNRemoveSynthFromList, __VIGetAdjustingValues, __VISetAdjustingValues, AIInitDMA, AIRegisterDMACallback, AIRegisterStreamCallback, AISetDSPSampleRate, AISetStreamPlayState, ARAlloc, ARFree, ARGetDMAStatus, ARInit, ARQFlushQueue, ARQPostRequest, ARQRemoveOwnerRequest, ARQRemoveRequest, ARRegisterDMACallback, ARStartDMA, AXAcquireVoice, AXFreeVoice, AXFXChorusInit, AXFXChorusSettings, AXFXChorusShutdown, AXFXDelayInit, AXFXDelaySettings, AXFXDelayShutdown, AXFXReverbHiInit, AXFXReverbHiSettings, AXFXReverbHiShutdown, AXFXReverbStdInit, AXFXReverbStdSettings, AXFXReverbStdShutdown, AXGetProfile, AXSetVoiceAddr, AXSetVoiceAdpcm, AXSetVoiceAdpcmLoop, AXSetVoiceCurrentAddr, AXSetVoiceDpop, AXSetVoiceEndAddr, AXSetVoiceFir, AXSetVoiceItdOn, AXSetVoiceItdTarget, AXSetVoiceLoop, AXSetVoiceLoopAddr, AXSetVoiceMix, AXSetVoicePriority, AXSetVoiceSrc, AXSetVoiceSrcRatio, AXSetVoiceSrcType, AXSetVoiceState, AXSetVoiceType, AXSetVoiceUpdateIncrement, AXSetVoiceUpdateWrite, AXSetVoiceVe, AXSetVoiceVeDelta, CARDCancel, CARDCheckExAsync, CARDMountAsync, CARDProbeEx, DBInitComm, DBQueryData, DBRead, DBWrite, DEMOWinClearBuffer, DEMOWinClearRow, DEMOWinClearWindow, DEMOWinDestroyWindow, DEMOWinLogPrintf, DEMOWinPrintfXY, DEMOWinRefresh, DEMOWinScrollWindow, DoUnmount, DSPAddTask, DSPAssertInt, DSPAssertTask, DSPCancelTask, DSPHalt, DSPInit, DSPReset, DSPUnhalt, DTKQueueTrack, DTKRemoveTrack, DVDCancel, DVDCancelAll, DVDCancelAllAsync, DVDCancelAsync, DVDCancelStream, DVDChangeDisk, DVDCheckDisk, DVDGetCommandBlockStatus, DVDGetDriveStatus, DVDGetStreamErrorStatus, DVDGetStreamLength, DVDGetStreamPlayAddr, DVDGetStreamStartAddr, DVDInquiry, DVDLowSetResetCoverCallback, DVDPause, DVDPrepareStream, DVDReadPrio, DVDResume, DVDSeekPrio, DVDStopStreamAtEnd, EXIAttach, EXIDeselect, EXIDetach, EXIDma, EXIImm, EXILock, EXIProbe, EXISelect, EXISetExiCallback, EXISync, EXIUnlock, GXDisableBreakPt, GXEnableBreakPt, GXEndDisplayList, GXInitFifoPtrs, GXRedirectWriteGatherPipe, GXSetBreakPtCallback, GXSetCPUFifo, GXSetCurrentGXThread, GXSetDrawDone, GXSetDrawDoneCallback, GXSetDrawSync, GXSetDrawSyncCallback, GXSetGPFifo, GXWaitDrawDone, issueCommand, LCEnable, LockSram, MIXInitChannel, OSCancelAlarm, OSCancelThread, OSCheckActiveThreads, OSCreateThread, OSDetachThread, OSDisableScheduler, OSDumpContext, OSEnableScheduler, OSExitThread, OSGetResetSwitchState, OSJamMessage, OSJoinThread, OSLockMutex, OSReceiveMessage, OSResetSystem, OSResumeThread, OSSendMessage, OSSetAbsAlarm, OSSetAlarm, OSSetPeriodicAlarm, OSSetResetCallback, OSSetThreadPriority, OSSleepThread, OSStartTimer, OSStopTimer, OSSuspendThread, OSTryLockMutex, OSUnlockMutex, OSWaitCond, OSWakeupThread, OSYieldThread, PADControlAllMotors, PADControlMotor, PADDisable, PADRead, PADRecalibrate, PADReset, PADSetAnalogMode, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartFrame, PERFStopAutoSampling, PopWaitingQueuePrio, SEQSetState, SIDisablePolling, SIEnablePolling, SISetXY, SISync, SITransfer, SYNQuitSynth, UnlockSram, VIConfigure, VIConfigurePan, VIFlush, VIGetCurrentLine, VIGetDTVStatus, VIGetNextField, VISet3D, VISetBlack, VISetNextFrameBuffer, VISetNextRightFrameBuffer, VISetPostRetraceCallback, VISetPreRetraceCallback, VIWaitForRetrace.
u32 OSGetSoundMode(void)
References __OSLockSram, __OSUnlockSram, FALSE, OSSram::flags.
void OSSetSoundMode(u32 mode)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, FALSE, OSSram::flags, OS_SOUND_MODE_MONO, OS_SOUND_MODE_STEREO, TRUE.
void OSReport(char *,...)
References CARD_MAX_MOUNT_STEP.
Referenced by __ARChecksize, __AXAllocInit, __AXAllocQuit, __AXAuxInit, __AXAuxQuit, __AXClInit, __AXClQuit, __AXOutInit, __AXOutQuit, __AXSPBInit, __AXSPBQuit, __AXVPBInit, __AXVPBQuit, __BypassDoneRender, __DBExceptionDestinationAux, __fstLoad, __OSDispatchInterrupt, __OSUnhandledException, __VIRetraceHandler, AIInit, AISetStreamSampleRate, ARInit, ARSetSize, AXInit, AXQuit, DEMODumpROMFont, DEMOPrintStats, DMAErrorHandler, DVDDumpWaitingQueue, DVDInit, DVDOpen, fioErrorReport, fioPacketResultRead, fioPacketResultWrite, GXOverflowHandler, GXSetMisc, GXUnderflowHandler, LoadMemInfo, MPDWaiting, OSAllocFixed, OSAllocFromHeap, OSCheckActiveThreads, OSCreateHeap, OSDestroyHeap, OSDumpContext, OSDumpHeap, OSDumpStopwatch, OSInit, OSInitTimer, OSPanic, PERFEventEnd, PERFEventStart, PERFTimerCallback, Relocate, ShowChannelInfo, ShowChannelInfo, Undo.
void OSPanic(char *file, int line, char *msg,...)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSGetStackPointer, OSReport, PPCHalt.
Referenced by __DEMOInitRenderMode, DEMOInitROMFont, DEMOWriteStats, DVDConvertPathToEntrynum, DVDPrepareStream, DVDPrepareStreamAsync, DVDReadAsyncPrio, DVDReadPrio, DVDSeekAsyncPrio, GXCompressZ16, GXDecompressZ16, GXEnd, LoadMemInfo, OSCheckActiveThreads, OSInitTimer, OSStartTimer, OSStopTimer, PADSetSamplingRate, UnpackTexPalette.
void * OSPhysicalToCached(u32 paddr)
References CARD_MAX_MOUNT_STEP.
void * OSPhysicalToUncached(u32 paddr)
References CARD_MAX_MOUNT_STEP.
u32 OSCachedToPhysical(void *caddr)
References CARD_MAX_MOUNT_STEP.
u32 OSUncachedToPhysical(void *ucaddr)
References CARD_MAX_MOUNT_STEP.
void * OSCachedToUncached(void *caddr)
References CARD_MAX_MOUNT_STEP.
void * OSUncachedToCached(void *ucaddr)
References CARD_MAX_MOUNT_STEP.