pad.h
PAD_SPEC_0
PAD_SPEC_1
PAD_SPEC_2
PAD_SPEC_3
PAD_SPEC_4
PAD_SPEC_5
PAD_MOTOR_STOP
PAD_MOTOR_RUMBLE
PAD_MOTOR_STOP_HARD
PAD_CHAN0_BIT
PAD_MAX_CONTROLLERS
PAD_BUTTON_LEFT
PAD_BUTTON_RIGHT
PAD_BUTTON_DOWN
PAD_BUTTON_UP
PAD_TRIGGER_Z
PAD_TRIGGER_R
PAD_TRIGGER_L
PAD_BUTTON_A
PAD_BUTTON_B
PAD_BUTTON_X
PAD_BUTTON_Y
PAD_BUTTON_MENU
PAD_BUTTON_START
PAD_ERR_NONE
PAD_ERR_NO_CONTROLLER
PAD_ERR_NOT_READY
PAD_ERR_TRANSFER
RES_WIRELESS_LITE
typedef struct PADStatus PADStatus
int PADReset(u32 mask)
References CARD_MAX_MOUNT_STEP, CheckingBits, DoReset, EnabledBits, OSDisableInterrupts, OSRestoreInterrupts, ProbingBits, RecalibrateBits, ResettingBits, ResettingChan, SIDisablePolling, Spec, WaitingBits.
Referenced by DEMOPadRead.
BOOL PADRecalibrate(u32 mask)
References CARD_MAX_MOUNT_STEP, CheckingBits, DoReset, EnabledBits, FALSE, OSDisableInterrupts, OSRestoreInterrupts, ProbingBits, RecalibrateBits, ResettingBits, ResettingChan, SIDisablePolling, WaitingBits.
BOOL PADInit()
References __OSWirelessPadFixMode, __PADFixBits, __PADSpec, cmdProbeDevice, Initialized, OSGetTime, OSRegisterResetFunction, PAD_CHAN0_BIT, PAD_CHAN1_BIT, PAD_CHAN2_BIT, PAD_CHAN3_BIT, PADReset, PADSetSamplingRate, PADSetSpec, ResetFunctionInfo, SI_MAX_CHAN, TRUE.
Referenced by DEMOPadInit.
u32 PADRead(PADStatus *status)
References CARD_MAX_MOUNT_STEP, CheckingBits, cmdReadOrigin, cmdTypeAndStatus, EnabledBits, MakeStatus, offsetof, Origin, OSDisableInterrupts, OSRestoreInterrupts, PADDisable, PADOriginUpdateCallback, PADReceiveCheckCallback, ProbingBits, ResettingBits, ResettingChan, SI_MAX_CHAN, SIGetResponse, SIGetStatus, SITransfer, status, Type, WaitingBits.
Referenced by DEMOPadRead, DEMOWinPadRead.
void PADSetSamplingRate(u32 msec)
References CARD_MAX_MOUNT_STEP, EnabledBits, OSPanic, SIEnablePolling, SISetXY, VI_MPAL, VI_NTSC, VI_PAL, VIGetTvFormat, XYNTSC, XYPAL.
void __PADTestSamplingRate(u32 tvmode)
void PADControlAllMotors(const u32 *commandArray)
References AnalogMode, CARD_MAX_MOUNT_STEP, EnabledBits, FALSE, OSDisableInterrupts, OSRestoreInterrupts, PAD_CHAN0_BIT, PAD_MOTOR_STOP, PAD_MOTOR_STOP_HARD, PAD_SPEC_2, ProbingBits, SI_MAX_CHAN, SISetCommand, SITransferCommands, Spec, TRUE, Type.
void PADControlMotor(s32 chan, u32 command)
References AnalogMode, CARD_MAX_MOUNT_STEP, EnabledBits, OSDisableInterrupts, OSRestoreInterrupts, PAD_CHAN0_BIT, PAD_MOTOR_STOP, PAD_MOTOR_STOP_HARD, PAD_SPEC_2, ProbingBits, SISetCommand, SITransferCommands, Spec, Type.
void PADSetSpec(u32 spec)
References __PADSpec, CARD_MAX_MOUNT_STEP, Initialized, MakeStatus, PAD_SPEC_0, PAD_SPEC_1, PAD_SPEC_2, PAD_SPEC_3, PAD_SPEC_4, PAD_SPEC_5, Spec, SPEC0_MakeStatus, SPEC1_MakeStatus, SPEC2_MakeStatus.
u32 PADGetSpec()
References Spec.
int PADGetType(s32 chan, u32 *type)
References CARD_MAX_MOUNT_STEP, EnabledBits, ResettingBits, ResettingChan, Type.
BOOL PADSync(void)
References ResettingBits, ResettingChan, SIBusy.
void PADSetAnalogMode(u32 mode)
References AnalogMode, CARD_MAX_MOUNT_STEP, CheckingBits, EnabledBits, OSDisableInterrupts, OSRestoreInterrupts, SIDisablePolling, WaitingBits.
void PADClamp(PADStatus *status)
References CARD_MAX_MOUNT_STEP, ClampRegion, ClampStick, ClampTrigger, PADClampRegion::maxStick, PADClampRegion::maxSubstick, PADClampRegion::minStick, PADClampRegion::minSubstick, PAD_ERR_NONE, status, PADClampRegion::xyStick, PADClampRegion::xySubstick.
Referenced by DEMOPadRead.