perfdraw.c
DRAW_RECT
GXColor DrawFrameColor
Referenced by PERFDumpScreen.
GXColor DrawCPUColor
GXColor DrawFullColor
Referenced by PERFDumpScreen.
GXColor DrawGPColor
Referenced by PERFDumpScreen.
GXColor DrawCPUCacheColor
Referenced by DrawBWBar, PERFDumpScreen.
GXColor DrawConnectColor
Referenced by PERFDumpScreen.
GXColor DrawBWBarColor
Referenced by PERFDumpScreen.
GXColor DrawIPCBarColor
Referenced by PERFDumpScreen.
GXColor DrawGPUBarColor
Referenced by PERFDumpScreen.
GXColor DrawIPCColor
Referenced by DrawBWBar.
GXColor DrawCPColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawTCColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawCPURDColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawCPUWRColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawDSPColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawIOColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawVIColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawPEColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawRFColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawFIColor
Referenced by DrawBWBar, DrawKey.
GXColor DrawGPXFIColor
Referenced by DrawBWBar.
GXColor DrawGPXFOColor
GXColor DrawGPRASIDLEColor
Referenced by DrawBWBar.
int bDrawBWBar
Referenced by DrawBWBar, PERFDumpScreen, PERFSetDrawBWBar, PERFToggleDrawBWBar.
int bDrawCPUBar
Referenced by DrawBWBar, PERFDumpScreen, PERFSetDrawCPUBar, PERFToggleDrawCPUBar.
int bDrawXFBars
Referenced by DrawBWBar, PERFDumpScreen, PERFSetDrawXFBars, PERFToggleDrawXFBars.
int bDrawRASBar
Referenced by DrawBWBar, PERFDumpScreen, PERFSetDrawRASBar, PERFToggleDrawRASBar.
int bDrawBWBarKey
Referenced by PERFDumpScreen, PERFSetDrawBWBarKey, PERFToggleDrawBWBarKey.
float lastx
Referenced by DrawBWBar.
float FramePts[28][28]
Referenced by __PERFDrawInit, PERFDumpScreen.
float CPUPts[4][4]
float GPPts[4][4]
void(* GameDrawInit) ())()
Referenced by __PERFDrawInit, PERFDumpScreen, PERFPostDraw.
u32 PERFNumEvents
Referenced by __PERFDrawInit, PERFEndFrame, PERFInit.
Mtx mID
Referenced by __PERFDrawInit, PERFDumpScreen.
Mtx44 mProj
Referenced by PERFPostDraw, PERFPreDraw.
float pSave[7][7]
Referenced by PERFPostDraw, PERFPreDraw.
__declspec(weak)
float HEIGHT(u32 a, float f)
References CARD_MAX_MOUNT_STEP.
Referenced by DrawBWBar, DrawKey.
float COORD(u32 a)
References CARD_MAX_MOUNT_STEP.
Referenced by DrawBWBar, PERFDumpScreen.
void __PERFDrawInit(void(*id)())
References C_MTXIdentity, CARD_MAX_MOUNT_STEP, FramePts, GameDrawInit, mID, OS_BUS_CLOCK, OS_CORE_CLOCK, PERFNumEvents, PSMTXIdentity.
Referenced by PERFInit.
void PERFPreDraw()
References CARD_MAX_MOUNT_STEP, GX_AF_NONE, GX_ALWAYS, GX_BL_INVSRCALPHA, GX_BL_SRCALPHA, GX_BM_BLEND, GX_COLOR0A0, GX_DF_NONE, GX_DIRECT, GX_LO_CLEAR, GX_ORTHOGRAPHIC, GX_PASSCLR, GX_RGBA6, GX_SRC_REG, GX_TEVSTAGE0, GX_TEX_ST, GX_TEXCOORD_NULL, GX_TEXMAP_NULL, GX_VA_POS, GX_VTXFMT0, GXClearVtxDesc, GXGetProjectionv, GXInvalidateVtxCache, GXSetBlendMode, GXSetChanCtrl, GXSetNumChans, GXSetNumTevStages, GXSetNumTexGens, GXSetProjection, GXSetTevOp, GXSetTevOrder, GXSetVtxAttrFmt, GXSetVtxDesc, GXSetZCompLoc, GXSetZMode, mProj, pSave.
static void DrawBWBar(struct PerfSample *s)
References bDrawBWBar, bDrawCPUBar, bDrawRASBar, bDrawXFBars, PerfSample::cacheMisses, CARD_MAX_MOUNT_STEP, COORD, PerfSample::cpReq, PerfSample::cpuRdReq, PerfSample::cpuWrReq, DRAW_RECT, DrawCPColor, DrawCPUCacheColor, DrawCPURDColor, DrawCPUWRColor, DrawDSPColor, DrawFIColor, DrawGPRASIDLEColor, DrawGPXFIColor, DrawIOColor, DrawIPCColor, DrawPEColor, DrawRFColor, DrawTCColor, DrawVIColor, PerfSample::dspReq, PerfSample::fiReq, PerfSample::gpTimeStampEnd, PerfSample::gpTimeStampStart, HEIGHT, PerfSample::instructions, PerfSample::ioReq, lastx, OS_CORE_CLOCK, PerfSample::peReq, PerfSample::rasBusy, PerfSample::rasClocks, PerfSample::rfReq, PerfSample::tcReq, PerfSample::viReq, PerfSample::xfWaitIn, PerfSample::xfWaitOut.
Referenced by PERFDumpScreen.
static void DrawKey()
References CARD_MAX_MOUNT_STEP, DRAW_RECT, DrawCPColor, DrawCPURDColor, DrawCPUWRColor, DrawDSPColor, DrawFIColor, DrawIOColor, DrawPEColor, DrawRFColor, DrawTCColor, DrawVIColor, HEIGHT.
Referenced by PERFDumpScreen.
void PERFDumpScreen()
References bDrawBWBar, bDrawBWBarKey, bDrawCPUBar, bDrawRASBar, bDrawXFBars, PerfSample::cacheMisses, CARD_MAX_MOUNT_STEP, COORD, PerfSample::cpuTimeStampEnd, PerfSample::cpuTimeStampStart, DRAW_RECT, DrawBWBar, DrawBWBarColor, DrawConnectColor, DrawCPUCacheColor, DrawFrameColor, DrawFullColor, DrawGPColor, DrawGPUBarColor, DrawIPCBarColor, DrawKey, Frame::end, FramePts, GameDrawInit, PerfSample::gpTimeStampEnd, PerfSample::gpTimeStampStart, GX_COLOR0A0, GX_LINES, GX_QUADS, GX_TO_ZERO, GX_VTXFMT0, GXBegin, GXEnd, GXLoadPosMtxImm, GXSetChanMatColor, GXSetLineWidth, PerfSample::id, PerfSample::interrupted, Frame::lastSample, mID, PerfSample::origcpuStart, PerfSample::origgpStart, OS_CORE_CLOCK, PERF_CPU_EVENT, PERF_CPU_GP_EVENT, PERF_GP_EVENT, PERFCurrFrame, PERFEvents, PERFFrames, Frame::samples.
void PERFPostDraw()
References CARD_MAX_MOUNT_STEP, GameDrawInit, GX_PERSPECTIVE, GXSetProjection, mProj, pSave.
void PERFSetDrawBWBarKey(int tf)
References bDrawBWBarKey, CARD_MAX_MOUNT_STEP.
void PERFSetDrawBWBar(int tf)
References bDrawBWBar, CARD_MAX_MOUNT_STEP.
void PERFSetDrawCPUBar(int tf)
References bDrawCPUBar, CARD_MAX_MOUNT_STEP.
void PERFSetDrawXFBars(int tf)
References bDrawXFBars, CARD_MAX_MOUNT_STEP.
void PERFSetDrawRASBar(int tf)
References bDrawRASBar, CARD_MAX_MOUNT_STEP.
void PERFToggleDrawBWBarKey()
References bDrawBWBarKey.
void PERFToggleDrawBWBar()
References bDrawBWBar.
void PERFToggleDrawCPUBar()
References bDrawCPUBar.
void PERFToggleDrawXFBars()
References bDrawXFBars.
void PERFToggleDrawRASBar()
References bDrawRASBar.