perf.c
TOKEN_MAX
struct OSAlarm PERFAlarm
Referenced by PERFStartAutoSampling, PERFStopAutoSampling.
volatile s32 CurrAutoSample
Referenced by PERFEndAutoSample, PERFStartAutoSample, PERFStopAutoSampling, PERFTimerCallback, PERFTokenCallback.
volatile u32 CurrToken
Referenced by PERFStartFrame, PERFTimerCallback, PERFTokenCallback.
volatile u16 magic
Referenced by PERFEndFrame, PERFEventEnd, PERFEventStart, PERFTimerCallback, PERFTokenCallback.
void *(* PerfAlloc) (u32))(u32)
Referenced by PERFInit.
void(* PerfFree) (void *))(void *)
Referenced by PERFInit.
void(* DSCB) (u16))(u16)
Referenced by PERFEndFrame, PERFSetDrawSyncCallback, PERFTokenCallback.
u32 PERFNumFrames
Referenced by PERFEndFrame, PERFInit.
u32 PERFNumEvents
Referenced by __PERFDrawInit, PERFEndFrame, PERFInit.
u32 PERFNumSamples
Referenced by PERFInit.
struct Frame* PERFFrames
Referenced by PERFDumpScreen, PERFEndAutoSample, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFInit, PERFStartAutoSample, PERFStartFrame, PERFStopAutoSampling, PERFTimerCallback, PERFTokenCallback.
struct PerfEvent* PERFEvents
Referenced by PERFDumpScreen, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFInit, PERFSetEvent, PERFSetEventColor.
u32 PERFCurrFrame
Referenced by PERFDumpScreen, PERFEndAutoSample, PERFEndFrame, PERFEventEnd, PERFEventStart, PERFStartAutoSample, PERFStartFrame, PERFStopAutoSampling, PERFTimerCallback, PERFTokenCallback.
volatile s32 PERFCurrSample
Referenced by PERFEndFrame, PERFStartFrame, PERFTimerCallback, PERFTokenCallback.
static void PERFResetAllMemMetrics()
References __memReg.
Referenced by PERFStartFrame.
static void PERFGetAllMemMetrics(struct PerfSample *s, u32 i)
References __memReg, CARD_MAX_MOUNT_STEP, PerfSample::cpReq, PerfSample::cpuRdReq, PerfSample::cpuWrReq, PerfSample::dspReq, PerfSample::fiReq, GXReadXfRasMetric, PerfSample::ioReq, PerfSample::peReq, PerfSample::rasBusy, PerfSample::rasClocks, PerfSample::rfReq, PerfSample::tcReq, PerfSample::viReq, PerfSample::xfWaitIn, PerfSample::xfWaitOut.
Referenced by PERFEndAutoSample, PERFStartAutoSample, PERFStopAutoSampling, PERFTimerCallback, PERFTokenCallback.
void PERFSetDrawSyncCallback(void(*cb)(u16))
References cb, DSCB.
static void PERFTokenCallback(u16 token)
References PerfSample::cacheMisses, CARD_MAX_MOUNT_STEP, CurrAutoSample, CurrToken, DSCB, PerfSample::gpTimeStampEnd, PerfSample::gpTimeStampStart, PerfSample::instructions, magic, PerfSample::origgpStart, PERFCurrFrame, PERFCurrSample, PERFEndAutoSample, PERFFrames, PERFGetAllMemMetrics, PERFStartAutoSample, PPCMfpmc1, PPCMfpmc3, PPCMfpmc4, Frame::samples, TOKEN_MAX.
Referenced by PERFInit, PERFStartFrame.
u32 PERFInit(u32 numSamples, u32 numFramesHistory, unsigned long numTypes, void *(*allocator)(u32), void(*deallocator)(void *), void(*initDraw)())
References __PERFDrawInit, CARD_MAX_MOUNT_STEP, PerfEvent::currSample, GXInitXfRasMetric, GXSetDrawSyncCallback, Frame::lastSample, PerfEvent::name, OSInitAlarm, PerfAlloc, PERFEvents, PERFFrames, PerfFree, PERFNumEvents, PERFNumFrames, PERFNumSamples, PERFTokenCallback, Frame::samples, size.
void PERFSetEvent(u16 id, char *name, PerfType type)
References CARD_MAX_MOUNT_STEP, PerfEvent::color, PerfEvent::currSample, PerfEvent::name, PERFEvents, PerfEvent::type.
void PERFSetEventColor(u16 id, GXColor color)
References PerfEvent::color, PERFEvents.
void PERFStartFrame()
References CurrToken, GXClearGPMetric, GXSetDrawSyncCallback, Frame::lastSample, OSDisableInterrupts, OSRestoreInterrupts, PERFCurrFrame, PERFCurrSample, PERFFrames, PERFResetAllMemMetrics, PERFStartAutoSample, PERFTokenCallback, PPCMtmmcr0, PPCMtmmcr1, PPCMtpmc1, PPCMtpmc2, PPCMtpmc3, PPCMtpmc4.
void PERFEndFrame()
References Frame::cachemisscycles, CARD_MAX_MOUNT_STEP, PerfEvent::currSample, DSCB, Frame::end, GXSetDrawSyncCallback, Frame::lastSample, magic, OSDisableInterrupts, OSRestoreInterrupts, PERFCurrFrame, PERFCurrSample, PERFEndAutoSample, PERFEvents, PERFFrames, PERFNumEvents, PERFNumFrames, PPCMfpmc3, PPCMfpmc4.
void PERFEventStart(u16 id)
References PerfSample::cacheMisses, CARD_MAX_MOUNT_STEP, PerfSample::cpuTimeStampEnd, PerfSample::cpuTimeStampStart, PerfEvent::currSample, PerfSample::gpTimeStampEnd, PerfSample::gpTimeStampStart, GXSetDrawSync, PerfSample::id, PerfSample::instructions, PerfSample::interrupted, magic, PerfSample::origcpuStart, OSDisableInterrupts, OSReport, OSRestoreInterrupts, PERF_CPU_EVENT, PERF_CPU_GP_EVENT, PERF_GP_EVENT, PERFCurrFrame, PERFEvents, PERFFrames, PPCMfpmc1, PPCMfpmc3, PPCMfpmc4, Frame::samples, PerfEvent::type.
__declspec(weak)
void PERFEventEnd(u16 id)
References PerfSample::cacheMisses, PerfSample::cpuTimeStampEnd, PerfEvent::currSample, GXSetDrawSync, PerfSample::instructions, magic, OSDisableInterrupts, OSReport, OSRestoreInterrupts, PERF_CPU_EVENT, PERF_CPU_GP_EVENT, PERF_GP_EVENT, PERFCurrFrame, PERFEvents, PERFFrames, PPCMfpmc1, PPCMfpmc3, PPCMfpmc4, Frame::samples, PerfEvent::type.
static void PERFStartAutoSample()
References PerfSample::cacheMisses, CARD_MAX_MOUNT_STEP, CurrAutoSample, PerfSample::gpTimeStampEnd, PerfSample::gpTimeStampStart, PerfSample::id, PerfSample::instructions, PerfSample::interrupted, PERFCurrFrame, PERFFrames, PERFGetAllMemMetrics, PPCMfpmc1, PPCMfpmc3, PPCMfpmc4, Frame::samples.
Referenced by PERFStartFrame, PERFTimerCallback, PERFTokenCallback.
static void PERFEndAutoSample()
References PerfSample::cacheMisses, CurrAutoSample, PerfSample::gpTimeStampEnd, PerfSample::instructions, PERFCurrFrame, PERFFrames, PERFGetAllMemMetrics, PPCMfpmc1, PPCMfpmc3, PPCMfpmc4, Frame::samples.
Referenced by PERFEndFrame, PERFTimerCallback, PERFTokenCallback.
static void PERFTimerCallback(OSAlarm *alarm, OSContext *context)
References PerfSample::cacheMisses, CARD_MAX_MOUNT_STEP, CurrAutoSample, CurrToken, PerfSample::gpTimeStampEnd, PerfSample::gpTimeStampStart, PerfSample::id, PerfSample::instructions, PerfSample::interrupted, magic, OSReport, PERFCurrFrame, PERFCurrSample, PERFEndAutoSample, PERFFrames, PERFGetAllMemMetrics, PERFStartAutoSample, PPCMfpmc1, PPCMfpmc3, PPCMfpmc4, Frame::samples.
Referenced by PERFStartAutoSampling.
void PERFStartAutoSampling(float msInterval)
References CARD_MAX_MOUNT_STEP, OSGetTime, OSMillisecondsToTicks, OSSetPeriodicAlarm, PERFAlarm, PERFTimerCallback.
void PERFStopAutoSampling()
References CurrAutoSample, PerfSample::gpTimeStampEnd, OSCancelAlarm, OSDisableInterrupts, OSRestoreInterrupts, PERFAlarm, PERFCurrFrame, PERFFrames, PERFGetAllMemMetrics, PPCMfpmc4, Frame::samples.