reverb_hi.c
const double i2fMagic
Referenced by DoCrossTalk, HandleReverb.
const float value0_6
Referenced by DoCrossTalk, HandleReverb.
const float value0_3
Referenced by HandleReverb.
static void DLsetdelay(struct AXFX_REVHI_DELAYLINE *dl, s32 lag)
References AXFX_REVHI_DELAYLINE::inPoint, AXFX_REVHI_DELAYLINE::length, AXFX_REVHI_DELAYLINE::outPoint.
Referenced by DLcreate, ReverbHICreate.
static void DLcreate(struct AXFX_REVHI_DELAYLINE *dl, s32 max_length)
References __OSCurrHeap, DLsetdelay, AXFX_REVHI_DELAYLINE::inPoint, AXFX_REVHI_DELAYLINE::inputs, AXFX_REVHI_DELAYLINE::lastOutput, AXFX_REVHI_DELAYLINE::length, OSAllocFromHeap, AXFX_REVHI_DELAYLINE::outPoint.
Referenced by ReverbHICreate.
static void DLdelete(struct AXFX_REVHI_DELAYLINE *dl)
References __OSCurrHeap, AXFX_REVHI_DELAYLINE::inputs, OSFreeToHeap.
Referenced by ReverbHIFree, ReverbHIModify.
static int ReverbHICreate(struct AXFX_REVHI_WORK *rv, float coloration, float time, float mix, float damping, float preDelay, float crosstalk)
References __OSCurrHeap, AXFX_REVHI_WORK::allPassCoeff, AXFX_REVHI_WORK::AP, AXFX_REVHI_WORK::C, AXFX_REVHI_WORK::combCoef, AXFX_REVHI_WORK::crosstalk, AXFX_REVHI_WORK::damping, DLcreate, DLsetdelay, AXFX_REVHI_WORK::level, AXFX_REVHI_WORK::lpLastout, OSAllocFromHeap, AXFX_REVHI_WORK::preDelayLine, AXFX_REVHI_WORK::preDelayPtr, AXFX_REVHI_WORK::preDelayTime.
Referenced by AXFXReverbHiInit, ReverbHIModify.
static int ReverbHIModify(struct AXFX_REVHI_WORK *rv, float coloration, float time, float mix, float damping, float preDelay, float crosstalk)
References __OSCurrHeap, AXFX_REVHI_WORK::allPassCoeff, AXFX_REVHI_WORK::AP, AXFX_REVHI_WORK::C, AXFX_REVHI_WORK::crosstalk, AXFX_REVHI_WORK::damping, DLdelete, AXFX_REVHI_WORK::level, OSFreeToHeap, AXFX_REVHI_WORK::preDelayLine, AXFX_REVHI_WORK::preDelayTime, ReverbHICreate.
Referenced by AXFXReverbHiSettings.
static void HandleReverb(s32 *sptr, struct AXFX_REVHI_WORK *rv, long k)
Referenced by ReverbHICallback.
static void ReverbHICallback(s32 *left, long *right, long *surround, struct AXFX_REVHI_WORK *rv)
References AXFX_REVHI_WORK::crosstalk, DoCrossTalk, HandleReverb.
Referenced by AXFXReverbHiCallback.
static void ReverbHIFree(struct AXFX_REVHI_WORK *rv)
References __OSCurrHeap, AXFX_REVHI_WORK::AP, AXFX_REVHI_WORK::C, DLdelete, OSFreeToHeap, AXFX_REVHI_WORK::preDelayLine, AXFX_REVHI_WORK::preDelayTime.
Referenced by AXFXReverbHiShutdown.
static asm void DoCrossTalk(register s32 *l, register long *r, register float cross, register float invcross)
References blr, i2fMagic, r5, value0_6.
Referenced by ReverbHICallback.
static asm void HandleReverb(register s32 *sptr, register struct AXFX_REVHI_WORK *rv, register long k)
References AXFX_REVHI_WORK::allPassCoeff, AXFX_REVHI_WORK::AP, blr, AXFX_REVHI_WORK::C, AXFX_REVHI_WORK::combCoef, AXFX_REVHI_WORK::damping, i2fMagic, AXFX_REVHI_DELAYLINE::inPoint, AXFX_REVHI_DELAYLINE::inputs, AXFX_REVHI_DELAYLINE::lastOutput, AXFX_REVHI_DELAYLINE::length, AXFX_REVHI_WORK::level, AXFX_REVHI_WORK::lpLastout, AXFX_REVHI_DELAYLINE::outPoint, AXFX_REVHI_WORK::preDelayLine, AXFX_REVHI_WORK::preDelayPtr, AXFX_REVHI_WORK::preDelayTime, r3, r4, r5, value0_3, value0_6.
int AXFXReverbHiInit(struct AXFX_REVERBHI *rev)
References AXFX_REVERBHI::coloration, AXFX_REVERBHI::crosstalk, AXFX_REVERBHI::damping, AXFX_REVERBHI::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBHI::preDelay, ReverbHICreate, AXFX_REVERBHI::rv, AXFX_REVERBHI::tempDisableFX, AXFX_REVERBHI::time.
int AXFXReverbHiShutdown(struct AXFX_REVERBHI *rev)
References OSDisableInterrupts, OSRestoreInterrupts, ReverbHIFree, AXFX_REVERBHI::rv.
int AXFXReverbHiSettings(struct AXFX_REVERBHI *rev)
References AXFX_REVERBHI::coloration, AXFX_REVERBHI::crosstalk, AXFX_REVERBHI::damping, AXFX_REVERBHI::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBHI::preDelay, ReverbHIModify, AXFX_REVERBHI::rv, AXFX_REVERBHI::tempDisableFX, AXFX_REVERBHI::time.
void AXFXReverbHiCallback(struct AXFX_BUFFERUPDATE *bufferUpdate, struct AXFX_REVERBHI *reverb)
References AXFX_BUFFERUPDATE::left, ReverbHICallback, AXFX_BUFFERUPDATE::right, AXFX_REVERBHI::rv, AXFX_BUFFERUPDATE::surround, AXFX_REVERBHI::tempDisableFX.