reverb_std.c
const float value0_3
Referenced by HandleReverb.
const float value0_6
Referenced by HandleReverb.
const double i2fMagic
Referenced by HandleReverb.
static void DLsetdelay(struct AXFX_REVSTD_DELAYLINE *dl, s32 lag)
References AXFX_REVSTD_DELAYLINE::inPoint, AXFX_REVSTD_DELAYLINE::length, AXFX_REVSTD_DELAYLINE::outPoint.
Referenced by DLcreate, ReverbSTDCreate.
static void DLcreate(struct AXFX_REVSTD_DELAYLINE *dl, s32 max_length)
References __OSCurrHeap, DLsetdelay, AXFX_REVSTD_DELAYLINE::inPoint, AXFX_REVSTD_DELAYLINE::inputs, AXFX_REVSTD_DELAYLINE::lastOutput, AXFX_REVSTD_DELAYLINE::length, OSAllocFromHeap, AXFX_REVSTD_DELAYLINE::outPoint.
Referenced by ReverbSTDCreate.
static void DLdelete(struct AXFX_REVSTD_DELAYLINE *dl)
References __OSCurrHeap, AXFX_REVSTD_DELAYLINE::inputs, OSFreeToHeap.
Referenced by ReverbSTDFree, ReverbSTDModify.
static int ReverbSTDCreate(struct AXFX_REVSTD_WORK *rv, float coloration, float time, float mix, float damping, float predelay)
References __OSCurrHeap, AXFX_REVSTD_WORK::allPassCoeff, AXFX_REVSTD_WORK::AP, AXFX_REVSTD_WORK::C, AXFX_REVSTD_WORK::combCoef, AXFX_REVSTD_WORK::damping, DLcreate, DLsetdelay, AXFX_REVSTD_WORK::level, AXFX_REVSTD_WORK::lpLastout, OSAllocFromHeap, AXFX_REVSTD_WORK::preDelayLine, AXFX_REVSTD_WORK::preDelayPtr, AXFX_REVSTD_WORK::preDelayTime.
Referenced by AXFXReverbStdInit, ReverbSTDModify.
static int ReverbSTDModify(struct AXFX_REVSTD_WORK *rv, float coloration, float time, float mix, float damping, float predelay)
References __OSCurrHeap, AXFX_REVSTD_WORK::allPassCoeff, AXFX_REVSTD_WORK::AP, AXFX_REVSTD_WORK::C, AXFX_REVSTD_WORK::damping, DLdelete, AXFX_REVSTD_WORK::level, OSFreeToHeap, AXFX_REVSTD_WORK::preDelayLine, AXFX_REVSTD_WORK::preDelayTime, ReverbSTDCreate.
Referenced by AXFXReverbStdSettings.
static void HandleReverb(s32 *sptr, struct AXFX_REVSTD_WORK *rv)
Referenced by ReverbSTDCallback.
static void ReverbSTDCallback(s32 *left, long *right, long *surround, struct AXFX_REVSTD_WORK *rv)
References HandleReverb.
Referenced by AXFXReverbStdCallback.
static void ReverbSTDFree(struct AXFX_REVSTD_WORK *rv)
References __OSCurrHeap, AXFX_REVSTD_WORK::AP, AXFX_REVSTD_WORK::C, DLdelete, OSFreeToHeap, AXFX_REVSTD_WORK::preDelayLine, AXFX_REVSTD_WORK::preDelayTime.
Referenced by AXFXReverbStdShutdown.
static asm void HandleReverb(register s32 *sptr, register struct AXFX_REVSTD_WORK *rv)
References AXFX_REVSTD_WORK::allPassCoeff, AXFX_REVSTD_WORK::AP, blr, AXFX_REVSTD_WORK::C, AXFX_REVSTD_WORK::combCoef, AXFX_REVSTD_WORK::damping, i2fMagic, AXFX_REVSTD_DELAYLINE::inPoint, AXFX_REVSTD_DELAYLINE::inputs, AXFX_REVSTD_DELAYLINE::lastOutput, AXFX_REVSTD_DELAYLINE::length, AXFX_REVSTD_WORK::level, AXFX_REVSTD_WORK::lpLastout, AXFX_REVSTD_DELAYLINE::outPoint, AXFX_REVSTD_WORK::preDelayLine, AXFX_REVSTD_WORK::preDelayPtr, AXFX_REVSTD_WORK::preDelayTime, r5, value0_3, value0_6.
int AXFXReverbStdInit(struct AXFX_REVERBSTD *rev)
References AXFX_REVERBSTD::coloration, AXFX_REVERBSTD::damping, AXFX_REVERBSTD::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBSTD::preDelay, ReverbSTDCreate, AXFX_REVERBSTD::rv, AXFX_REVERBSTD::tempDisableFX, AXFX_REVERBSTD::time.
int AXFXReverbStdShutdown(struct AXFX_REVERBSTD *rev)
References OSDisableInterrupts, OSRestoreInterrupts, ReverbSTDFree, AXFX_REVERBSTD::rv.
int AXFXReverbStdSettings(struct AXFX_REVERBSTD *rev)
References AXFX_REVERBSTD::coloration, AXFX_REVERBSTD::damping, AXFX_REVERBSTD::mix, OSDisableInterrupts, OSRestoreInterrupts, AXFX_REVERBSTD::preDelay, ReverbSTDModify, AXFX_REVERBSTD::rv, AXFX_REVERBSTD::tempDisableFX, AXFX_REVERBSTD::time.
void AXFXReverbStdCallback(struct AXFX_BUFFERUPDATE *bufferUpdate, struct AXFX_REVERBSTD *reverb)
References AXFX_BUFFERUPDATE::left, ReverbSTDCallback, AXFX_BUFFERUPDATE::right, AXFX_REVERBSTD::rv, AXFX_BUFFERUPDATE::surround, AXFX_REVERBSTD::tempDisableFX.