seq.c
u8 __SEQMidiEventLength[128][128]
Referenced by __SEQHandleSynthEvent.
SEQSEQUENCE* __SEQSequenceList
Referenced by __SEQPushSequenceList, __SEQRemoveSequenceFromList, SEQInit, SEQQuit, SEQRunAudioFrame.
static void __SEQPushSequenceList(SEQSEQUENCE *sequence)
References __SEQSequenceList, _SEQSEQUENCE::next, NULL, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by __SEQRemoveSequenceFromList, SEQAddSequence.
static void __SEQRemoveSequenceFromList(SEQSEQUENCE *sequence)
References __SEQPushSequenceList, __SEQSequenceList, CARD_MAX_MOUNT_STEP, DVDCommandBlock::next, next, NULL, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by SEQRemoveSequence.
static u32 __SEQGetIntTrack(SEQTRACK *track)
References CARD_MAX_MOUNT_STEP, _SEQTRACK::current.
Referenced by __SEQHandleMetaEvent, __SEQHandleSysExEvent, SEQRunAudioFrame, SEQSetState.
static void __SEQHandleSysExEvent(SEQTRACK *track)
References __SEQGetIntTrack, CARD_MAX_MOUNT_STEP, _SEQTRACK::current.
Referenced by __SEQRunEvent.
static void __SEQSetTicksPerFrame(SEQTRACK *track, float bps)
References _SEQTRACK::beatsPerSec, CARD_MAX_MOUNT_STEP, _SEQTRACK::sequence, _SEQTRACK::ticksPerFrame, _SEQSEQUENCE::timeFormat.
Referenced by __SEQTempoMetaEvent, SEQSetTempo.
static void __SEQTempoMetaEvent(SEQTRACK *track)
References __SEQSetTicksPerFrame, _SEQTRACK::current.
Referenced by __SEQHandleMetaEvent.
static void __SEQTrackEnd(SEQTRACK *track)
References CARD_MAX_MOUNT_STEP, _SEQSEQUENCE::end, _SEQTRACK::sequence, _SEQTRACK::state, _SEQSEQUENCE::tracksRunning.
Referenced by __SEQHandleMetaEvent, __SEQRunEvent.
static void __SEQHandleMetaEvent(SEQTRACK *track)
References __SEQGetIntTrack, __SEQTempoMetaEvent, __SEQTrackEnd, CARD_MAX_MOUNT_STEP, _SEQTRACK::current.
Referenced by __SEQRunEvent.
static void __SEQHandleSynthEvent(struct SYNSYNTH *synth, SEQTRACK *track)
References __SEQMidiEventLength, CARD_MAX_MOUNT_STEP, _SEQTRACK::current, _SEQTRACK::sequence, _SEQTRACK::status, SYNMidiInput.
Referenced by __SEQRunEvent.
static void __SEQRunEvent(struct SYNSYNTH *synth, SEQTRACK *track)
References __SEQHandleMetaEvent, __SEQHandleSynthEvent, __SEQHandleSysExEvent, __SEQTrackEnd, CARD_MAX_MOUNT_STEP, _SEQTRACK::current, _SEQTRACK::end, _SEQTRACK::status.
Referenced by SEQRunAudioFrame.
static void __SEQInitTracks(SEQSEQUENCE *sequence, u8 *read, int tracks)
References CARD_MAX_MOUNT_STEP, _SEQTRACK::current, _SEQTRACK::defaultTicksPerFrame, _SEQTRACK::end, _SEQTRACK::sequence, _SEQTRACK::start, _SEQTRACK::state, _SEQSEQUENCE::timeFormat, _SEQSEQUENCE::track.
Referenced by __SEQReadHeader.
static void __SEQReadHeader(SEQSEQUENCE *sequence, u8 *midiStream)
References __SEQInitTracks, CARD_MAX_MOUNT_STEP, _SEQSEQUENCE::nTracks, _SEQSEQUENCE::timeFormat, _SEQSEQUENCE::tracksRunning.
Referenced by SEQAddSequence.
void SEQInit(void)
References __SEQSequenceList, NULL.
void SEQQuit(void)
References __SEQSequenceList, NULL.
void SEQRunAudioFrame(void)
References __SEQGetIntTrack, __SEQRunEvent, __SEQSequenceList, CARD_MAX_MOUNT_STEP, _SEQTRACK::delay, _SEQSEQUENCE::end, _SEQSEQUENCE::next, _SEQSEQUENCE::nTracks, SEQSetState, _SEQTRACK::state, _SEQSEQUENCE::state, _SEQSEQUENCE::synth, _SEQTRACK::ticksPerFrame, _SEQSEQUENCE::track.
void SEQAddSequence(SEQSEQUENCE *sequence, u32 *midiStream, void *wt, u32 aramBase, u32 priorityVoiceAlloc, u32 priorityNoteOn, u32 priorityNoteRelease)
References __SEQPushSequenceList, __SEQReadHeader, _SEQSEQUENCE::callback, CARD_MAX_MOUNT_STEP, _SEQSEQUENCE::state, SYNInitSynth, _SEQSEQUENCE::synth.
void SEQRemoveSequence(SEQSEQUENCE *sequence)
References __SEQRemoveSequenceFromList, CARD_MAX_MOUNT_STEP, SYNQuitSynth, _SEQSEQUENCE::synth.
void SEQRegisterControllerCallback(SEQSEQUENCE *sequence, u8 controller, void(*callback)(void *, u16))
References _SEQSEQUENCE::callback, CARD_MAX_MOUNT_STEP.
void SEQSetState(SEQSEQUENCE *sequence, u32 state)
References __SEQGetIntTrack, CARD_MAX_MOUNT_STEP, _SEQTRACK::current, _SEQTRACK::defaultTicksPerFrame, _SEQTRACK::delay, _SEQSEQUENCE::end, _SEQSEQUENCE::nTracks, OSDisableInterrupts, OSRestoreInterrupts, _SEQTRACK::start, _SEQTRACK::state, _SEQSEQUENCE::state, SYNMidiInput, _SEQSEQUENCE::synth, _SEQTRACK::ticksPerFrame, _SEQSEQUENCE::track, _SEQSEQUENCE::tracksRunning.
Referenced by SEQRunAudioFrame.
u32 SEQGetState(SEQSEQUENCE *sequence)
References CARD_MAX_MOUNT_STEP, _SEQSEQUENCE::state.
void SEQSetTempo(SEQSEQUENCE *sequence, u32 trackIndex, float bpm)
References __SEQSetTicksPerFrame, CARD_MAX_MOUNT_STEP, _SEQSEQUENCE::nTracks, SEQ_ALL_TRACKS, _SEQSEQUENCE::track.
f32 SEQGetTempo(SEQSEQUENCE *sequence, u32 trackIndex)
References _SEQTRACK::beatsPerSec, CARD_MAX_MOUNT_STEP, _SEQSEQUENCE::track.
void SEQSetVolume(SEQSEQUENCE *sequence, s32 dB)
References CARD_MAX_MOUNT_STEP, SYNSetMasterVolume, _SEQSEQUENCE::synth.
s32 SEQGetVolume(SEQSEQUENCE *sequence)
References CARD_MAX_MOUNT_STEP, SYNGetMasterVolume, _SEQSEQUENCE::synth.