syn.c
struct SYNSYNTH* __SYNSynthList
Referenced by __SYNAddSynthToList, __SYNRemoveSynthFromList, SYNInit, SYNRunAudioFrame.
static void __SYNAddSynthToList(struct SYNSYNTH *synth)
References __SYNSynthList, SYNSYNTH::next, NULL, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by SYNInitSynth.
static void __SYNRemoveSynthFromList(struct SYNSYNTH *synth)
References __SYNSynthList, CARD_MAX_MOUNT_STEP, SYNSYNTH::next, NULL, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by SYNQuitSynth.
void SYNInit()
References __SYNSynthList, __SYNVoice, CARD_MAX_MOUNT_STEP, NULL, SYNVOICE::synth.
Referenced by SYNQuit.
void SYNQuit()
References SYNInit.
void SYNRunAudioFrame()
References __SYNRunInputBufferEvents, __SYNServiceVoice, __SYNSynthList, CARD_MAX_MOUNT_STEP, SYNSYNTH::next.
void SYNInitSynth(struct SYNSYNTH *synth, void *wavetable, u32 aramBase, u32 priorityVoiceAlloc, u32 priorityNoteOn, u32 priorityNoteRelease)
References __SYNAddSynthToList, __SYNResetAllControllers, SYNSYNTH::adpcm, SYNSYNTH::aramBaseByte, SYNSYNTH::aramBaseNibble, SYNSYNTH::aramBaseWord, SYNSYNTH::art, CARD_MAX_MOUNT_STEP, SYNSYNTH::input, SYNSYNTH::inputCounter, SYNSYNTH::inputPosition, SYNSYNTH::keyGroup, SYNSYNTH::masterVolume, SYNSYNTH::melodicInst, SYNSYNTH::notes, SYNSYNTH::percussiveInst, SYNSYNTH::priorityNoteOn, SYNSYNTH::priorityNoteRelease, SYNSYNTH::priorityVoiceAlloc, SYNSYNTH::region, SYNSYNTH::sample, SYNSYNTH::voice.
Referenced by SEQAddSequence.
void SYNQuitSynth(struct SYNSYNTH *synth)
References __SYNRemoveSynthFromList, __SYNVoice, AXFreeVoice, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, MIXReleaseChannel, SYNSYNTH::notes, OSDisableInterrupts, OSRestoreInterrupts, SYNVOICE::synth.
Referenced by SEQRemoveSequence.
void SYNMidiInput(struct SYNSYNTH *synth, u8 *input)
References CARD_MAX_MOUNT_STEP, FALSE, SYNSYNTH::inputCounter, SYNSYNTH::inputPosition, src, SYN_INPUT_BUFFER_SIZE, SYNVOICE::synth.
Referenced by __SEQHandleSynthEvent, SEQSetState.
void SYNSetMasterVolume(struct SYNSYNTH *synth, s32 dB)
References CARD_MAX_MOUNT_STEP, SYNSYNTH::masterVolume, SYNVOICE::synth.
Referenced by SEQSetVolume.
s32 SYNGetMasterVolume(struct SYNSYNTH *synth)
References CARD_MAX_MOUNT_STEP, SYNSYNTH::masterVolume, SYNVOICE::synth.
Referenced by SEQGetVolume.
u32 SYNGetActiveNotes(struct SYNSYNTH *synth)
References CARD_MAX_MOUNT_STEP, SYNSYNTH::notes, SYNVOICE::synth.