synctrl.c
float __SYNn128[128][128]
Referenced by __SYNGetEnvelopeTime, __SYNRunLfo.
static void __SYNSetData(struct SYNSYNTH *synth, u8 midiChannel)
References CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, FALSE, SYNSYNTH::pwMaxCents, SYNSYNTH::rpn.
Referenced by __SYNSetController.
static void __SYNSetSustainPedal(struct SYNSYNTH *synth, u8 midiChannel, u8 data)
References __SYNSetVoiceToRelease, CARD_MAX_MOUNT_STEP, SYNVOICE::hold, SYNVOICE::keyNum, SYNVOICE::midiChannel, SYNSYNTH::priorityNoteRelease, SYNVOICE::synth, SYNSYNTH::voice.
Referenced by __SYNSetController.
static void __SYNProgramChange(struct SYNSYNTH *synth, u8 midiChannel, u8 program)
References CARD_MAX_MOUNT_STEP, SYNSYNTH::inst, SYNSYNTH::melodicInst, SYNVOICE::midiChannel, SYNSYNTH::percussiveInst, SYNVOICE::synth.
Referenced by __SYNMidiIn, __SYNResetAllControllers.
static void __SYNReleaseChannelNotes(struct SYNSYNTH *synth, u8 midiChannel)
References __SYNSetVoiceToRelease, CARD_MAX_MOUNT_STEP, SYNVOICE::midiChannel, SYNSYNTH::priorityNoteRelease, SYNVOICE::synth, SYNSYNTH::voice.
Referenced by __SYNClearAllNotes, __SYNSetController.
static void __SYNNoteOff(struct SYNSYNTH *synth, u8 midiChannel, u8 keyNum)
References __SYNSetVoiceToRelease, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::hold, SYNVOICE::keyNum, SYNVOICE::midiChannel, SYNSYNTH::priorityNoteRelease, SYNVOICE::synth, SYNSYNTH::voice.
Referenced by __SYNMidiIn, __SYNNoteOn.
static void __SYNNoteOn(struct SYNSYNTH *synth, u8 midiChannel, u8 keyNum, u8 keyVel)
References __SYNClearVoiceReferences, __SYNGetVoiceFader, __SYNGetVoiceInput, __SYNGetWavetableData, __SYNNoteOff, __SYNSetupLfo, __SYNSetupPan, __SYNSetupPitch, __SYNSetupPitchEnvelope, __SYNSetupSample, __SYNSetupSrc, __SYNSetupVolume, __SYNSetupVolumeEnvelope, __SYNSetVoiceToRelease, __SYNVoice, SYNSYNTH::auxAAttn, SYNSYNTH::auxBAttn, AXAcquireVoice, AXFreeVoice, AXSetVoicePriority, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::hold, _AXVPB::index, WTREGION::keyGroup, SYNSYNTH::keyGroup, SYNVOICE::keyGroup, SYNVOICE::keyNum, SYNVOICE::keyVel, SYNVOICE::midiChannel, MIXInitChannel, MIXReleaseChannel, SYNSYNTH::notes, NULL, SYNVOICE::pan, _AXVPB::pb, SYNSYNTH::priorityNoteOn, SYNSYNTH::priorityNoteRelease, SYNSYNTH::priorityVoiceAlloc, SYNVOICE::region, _AXPB::state, _AXVPB::sync, SYNVOICE::synth, SYNSYNTH::voice.
Referenced by __SYNMidiIn.
static void __SYNPitchWheel(struct SYNSYNTH *synth, u8 midiChannel, u8 lsb, u8 msb)
References CARD_MAX_MOUNT_STEP, SYNVOICE::midiChannel, SYNSYNTH::pwCents, SYNSYNTH::pwMaxCents, SYNVOICE::synth.
Referenced by __SYNMidiIn.
static void __SYNMidiIn(struct SYNSYNTH *synth, u8 *input)
References __SYNNoteOff, __SYNNoteOn, __SYNPitchWheel, __SYNProgramChange, __SYNSetController, CARD_MAX_MOUNT_STEP, SYNVOICE::midiChannel, SYNVOICE::synth.
Referenced by __SYNRunInputBufferEvents.
void __SYNClearAllNotes(struct SYNSYNTH *synth)
References __SYNReleaseChannelNotes, CARD_MAX_MOUNT_STEP, SYNVOICE::synth.
void __SYNSetController(struct SYNSYNTH *synth, u8 midiChannel, u8 function, u8 value)
References __SYNReleaseChannelNotes, __SYNResetController, __SYNResetController0, __SYNSetData, __SYNSetSustainPedal, __SYNVolumeAttenuation, SYNSYNTH::auxAAttn, SYNSYNTH::auxBAttn, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNSYNTH::expAttn, SYNVOICE::midiChannel, SYNSYNTH::rpn, SYNVOICE::synth, SYNSYNTH::volAttn.
Referenced by __SYNMidiIn, __SYNResetController, __SYNResetController0.
void __SYNResetController0(struct SYNSYNTH *synth, u8 midiChannel)
References __SYNSetController, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::midiChannel, SYNVOICE::pan, SYNSYNTH::pwCents, SYNSYNTH::pwMaxCents, SYNVOICE::synth.
Referenced by __SYNSetController.
void __SYNResetController(struct SYNSYNTH *synth, u8 midiChannel)
References __SYNSetController, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::midiChannel, SYNSYNTH::pwCents, SYNSYNTH::pwMaxCents, SYNVOICE::synth.
Referenced by __SYNResetAllControllers, __SYNSetController.
void __SYNResetAllControllers(struct SYNSYNTH *synth)
References __SYNProgramChange, __SYNResetController, CARD_MAX_MOUNT_STEP, SYNVOICE::midiChannel, SYNVOICE::synth.
Referenced by SYNInitSynth.
void __SYNRunInputBufferEvents(struct SYNSYNTH *synth)
References __SYNMidiIn, SYNSYNTH::input, SYNSYNTH::inputCounter, SYNSYNTH::inputPosition, SYNVOICE::synth.
Referenced by SYNRunAudioFrame.
u8 SYNGetMidiController(struct SYNSYNTH *synth, u8 midiChannel, u8 function)
References CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::midiChannel, SYNVOICE::synth.