synenv.c
s32 __SYNGetEnvelopeTime(s32 scale, s32 mod, u8 key)
References __SYNn128, CARD_MAX_MOUNT_STEP.
Referenced by __SYNSetupPitchEnvelope, __SYNSetupVolumeEnvelope.
void __SYNSetupVolumeEnvelope(struct SYNVOICE *voice)
References __SYNGetEnvelopeTime, SYNVOICE::art, CARD_MAX_MOUNT_STEP, WTART::eg1Attack, WTART::eg1Decay, WTART::eg1Key2Decay, WTART::eg1Release, WTART::eg1Sustain, WTART::eg1Vel2Attack, SYNVOICE::keyNum, SYNVOICE::keyVel, SYNVOICE::veAttack, SYNVOICE::veAttackDelta, SYNVOICE::veAttn, SYNVOICE::veDecay, SYNVOICE::veRelease, SYNVOICE::veState, SYNVOICE::veSustain.
Referenced by __SYNNoteOn.
void __SYNSetupPitchEnvelope(struct SYNVOICE *voice)
References __SYNGetEnvelopeTime, SYNVOICE::art, CARD_MAX_MOUNT_STEP, WTART::eg2Attack, WTART::eg2Decay, WTART::eg2Key2Decay, WTART::eg2Pitch, WTART::eg2Release, WTART::eg2Sustain, WTART::eg2Vel2Attack, SYNVOICE::keyNum, SYNVOICE::keyVel, SYNVOICE::peAttack, SYNVOICE::peCents, SYNVOICE::peDecay, SYNVOICE::pePitch, SYNVOICE::peRelease, SYNVOICE::peState, SYNVOICE::peSustain.
Referenced by __SYNNoteOn.
void __SYNRunVolumeEnvelope(struct SYNVOICE *voice)
References __SYNAttackAttnTable, CARD_MAX_MOUNT_STEP, SYNVOICE::keyNum, SYNVOICE::midiChannel, SYNVOICE::synth, SYNVOICE::veAttack, SYNVOICE::veAttackDelta, SYNVOICE::veAttn, SYNVOICE::veDecay, SYNVOICE::veRelease, SYNVOICE::veState, SYNVOICE::veSustain, SYNSYNTH::voice.
Referenced by __SYNServiceVoice.
void __SYNRunPitchEnvelope(struct SYNVOICE *voice)
References CARD_MAX_MOUNT_STEP, SYNVOICE::peAttack, SYNVOICE::peCents, SYNVOICE::peDecay, SYNVOICE::pePitch, SYNVOICE::peRelease, SYNVOICE::peState, SYNVOICE::peSustain.
Referenced by __SYNServiceVoice.