synmix.c
s32 __SYNVolumeAttenuation[128][128]
Referenced by __SYNSetController, __SYNSetupVolume.
s32 __SYNAttackAttnTable[100][100]
Referenced by __SYNRunVolumeEnvelope.
void __SYNSetupVolume(struct SYNVOICE *voice)
References __SYNVolumeAttenuation, WTREGION::attn, SYNVOICE::attn, CARD_MAX_MOUNT_STEP, SYNVOICE::keyVel, SYNVOICE::region.
Referenced by __SYNNoteOn.
void __SYNSetupPan(struct SYNVOICE *voice)
References SYNVOICE::art, CARD_MAX_MOUNT_STEP, SYNSYNTH::controller, SYNVOICE::midiChannel, WTART::pan, SYNVOICE::pan, SYNVOICE::synth.
Referenced by __SYNNoteOn.
s32 __SYNGetVoiceInput(struct SYNVOICE *voice)
References SYNVOICE::attn, SYNVOICE::lfoAttn, SYNVOICE::veAttn.
Referenced by __SYNNoteOn, __SYNUpdateMix.
s32 __SYNGetVoiceFader(struct SYNVOICE *voice)
References SYNSYNTH::expAttn, SYNSYNTH::masterVolume, SYNVOICE::midiChannel, SYNVOICE::synth, SYNSYNTH::volAttn.
Referenced by __SYNNoteOn, __SYNUpdateMix.
void __SYNUpdateMix(struct SYNVOICE *voice)
References __SYNGetVoiceFader, __SYNGetVoiceInput, SYNSYNTH::auxAAttn, SYNSYNTH::auxBAttn, SYNVOICE::axvpb, SYNSYNTH::controller, SYNVOICE::midiChannel, MIXSetAuxA, MIXSetAuxB, MIXSetFader, MIXSetInput, MIXSetPan, SYNVOICE::synth.
Referenced by __SYNServiceVoice.