synpitch.c
float __SYNCentsTable[100][100]
Referenced by __SYNGetRelativePitch.
float __SYNOctavesTableUp[12][12]
Referenced by __SYNGetRelativePitch.
float __SYNSemitonesTableUp[12][12]
Referenced by __SYNGetRelativePitch.
float __SYNSemitonesTableDown[128][128]
Referenced by __SYNGetRelativePitch.
float __SYNGetRelativePitch(struct SYNVOICE *voice)
References __SYNCentsTable, __SYNOctavesTableUp, __SYNSemitonesTableDown, __SYNSemitonesTableUp, CARD_MAX_MOUNT_STEP, SYNVOICE::cents, SYNVOICE::lfoCents, SYNVOICE::midiChannel, SYNVOICE::peCents, SYNSYNTH::pwCents, SYNVOICE::synth.
Referenced by __SYNSetupSrc, __SYNUpdateSrc.
void __SYNSetupPitch(struct SYNVOICE *voice)
References SYNVOICE::cents, WTREGION::fineTune, SYNVOICE::keyNum, SYNVOICE::region, SYNVOICE::sample, WTSAMPLE::sampleRate, SYNVOICE::srcRatio, WTREGION::unityNote.
Referenced by __SYNNoteOn.
void __SYNSetupSrc(struct SYNVOICE *voice)
References __SYNGetRelativePitch, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, _AXVPB::pb, _AXPB::src, SYNVOICE::srcRatio, _AXPB::srcSelect, _AXVPB::sync.
Referenced by __SYNNoteOn.
void __SYNUpdateSrc(struct SYNVOICE *voice)
References __SYNGetRelativePitch, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, _AXVPB::pb, _AXPBSRC::ratioHi, _AXPB::src, SYNVOICE::srcRatio, _AXVPB::sync.
Referenced by __SYNServiceVoice.