synsample.c
static u32 __SYNGetNibbleAddress(u32 count)
References CARD_MAX_MOUNT_STEP.
Referenced by __SYNSetupAdpcm.
static void __SYNSetupAdpcm(struct SYNVOICE *voice)
References __SYNGetNibbleAddress, WTADPCM::a, _AXPB::addr, SYNVOICE::adpcm, _AXPB::adpcmLoop, SYNSYNTH::aramBaseNibble, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, WTSAMPLE::length, _AXPBADPCMLOOP::loop_pred_scale, _AXPBADPCMLOOP::loop_yn1, _AXPBADPCMLOOP::loop_yn2, WTREGION::loopLength, WTREGION::loopStart, WTSAMPLE::offset, _AXVPB::pb, SYNVOICE::region, SYNVOICE::sample, _AXVPB::sync, SYNVOICE::synth, SYNVOICE::type.
Referenced by __SYNSetupSample.
static void __SYNSetupPcm16(struct SYNVOICE *voice)
References _AXPB::addr, SYNSYNTH::aramBaseWord, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, WTSAMPLE::length, WTREGION::loopLength, WTREGION::loopStart, WTSAMPLE::offset, _AXVPB::pb, SYNVOICE::region, SYNVOICE::sample, _AXVPB::sync, SYNVOICE::synth, SYNVOICE::type.
Referenced by __SYNSetupSample.
static void __SYNSetupPcm8(struct SYNVOICE *voice)
References _AXPB::addr, SYNSYNTH::aramBaseByte, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, WTSAMPLE::length, WTREGION::loopLength, WTREGION::loopStart, WTSAMPLE::offset, _AXVPB::pb, SYNVOICE::region, SYNVOICE::sample, _AXVPB::sync, SYNVOICE::synth, SYNVOICE::type.
Referenced by __SYNSetupSample.
void __SYNSetupSample(struct SYNVOICE *voice)
References __SYNSetupAdpcm, __SYNSetupPcm16, __SYNSetupPcm8, CARD_MAX_MOUNT_STEP, FALSE, WTSAMPLE::format, SYNVOICE::sample, SYN_SAMPLE_FORMAT_ADPCM, SYN_SAMPLE_FORMAT_PCM16, SYN_SAMPLE_FORMAT_PCM8.
Referenced by __SYNNoteOn.