synvoice.c
AX_MAX_VOICES
struct SYNVOICE __SYNVoice[64][64]
Referenced by __SYNClearVoiceReferences, __SYNNoteOn, __SYNServiceVoice, SYNInit, SYNQuitSynth.
void __SYNClearVoiceReferences(void *p)
References __SYNVoice, AX_MAX_VOICES, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, _AXVPB::index, SYNSYNTH::keyGroup, SYNVOICE::keyGroup, SYNVOICE::keyNum, SYNVOICE::midiChannel, MIXReleaseChannel, SYNSYNTH::notes, SYNVOICE::synth, _AXVPB::userContext, SYNSYNTH::voice.
Referenced by __SYNNoteOn.
void __SYNSetVoiceToRelease(struct SYNVOICE *voice, u32 priority)
References AXSetVoicePriority, SYNVOICE::axvpb, CARD_MAX_MOUNT_STEP, SYNVOICE::peState, SYNVOICE::veState.
Referenced by __SYNNoteOff, __SYNNoteOn, __SYNReleaseChannelNotes, __SYNSetSustainPedal.
void __SYNServiceVoice(int i)
References __SYNRunLfo, __SYNRunPitchEnvelope, __SYNRunVolumeEnvelope, __SYNUpdateMix, __SYNUpdateSrc, __SYNVoice, AXFreeVoice, CARD_MAX_MOUNT_STEP, SYNSYNTH::keyGroup, MIXReleaseChannel, SYNSYNTH::notes, NULL, SYNSYNTH::voice.
Referenced by SYNRunAudioFrame.