texPalette.c
PALETTE_VERSION
static void LoadTexPalette(TEXPalettePtr *pal, char *name)
References CARD_MAX_MOUNT_STEP, DVDClose, DVDOpen, DVDReadPrio, OSAlloc, OSRoundUp32B, UnpackTexPalette.
Referenced by TEXGetPalette.
static void UnpackTexPalette(TEXPalettePtr pal)
References CARD_MAX_MOUNT_STEP, OSPanic, PALETTE_VERSION, TRUE.
Referenced by LoadTexPalette.
static void TexFreeFunc(TEXPalettePtr pal)
References CARD_MAX_MOUNT_STEP, OSFree.
Referenced by TEXGetPalette.
void TEXGetPalette(TEXPalettePtr *pal, char *name)
References CARD_MAX_MOUNT_STEP, DOCacheInitialized, DODisplayCache, DSAddCacheNode, DSGetCacheObj, LoadTexPalette, TexFreeFunc.
TEXDescriptorPtr TEXGet(TEXPalettePtr pal, u32 id)
References CARD_MAX_MOUNT_STEP.
Referenced by TEXGetGXTexObjFromPalette, TEXGetGXTexObjFromPaletteCI.
void TEXReleasePalette(TEXPalettePtr *pal)
References CARD_MAX_MOUNT_STEP, DOCacheInitialized, DODisplayCache, DSReleaseCacheObj, NULL, OSFree.
void TEXGetGXTexObjFromPalette(TEXPalettePtr pal, GXTexObj *to, u32 id)
References CARD_MAX_MOUNT_STEP, GX_ANISO_1, GX_DISABLE, GX_FALSE, GX_TRUE, GXInitTexObj, GXInitTexObjLOD, TEXGet.
void TEXGetGXTexObjFromPaletteCI(TEXPalettePtr pal, GXTexObj *to, GXTlutObj *tlo, GXTlut tluts, u32 id)
References CARD_MAX_MOUNT_STEP, GX_ANISO_1, GX_DISABLE, GX_FALSE, GX_TRUE, GXInitTexObjCI, GXInitTexObjLOD, GXInitTlutObj, TEXGet.