tty.c
volatile u8 gBuf[8192][8192]
Referenced by TTYPrintf.
u32 gOldEvent
Referenced by TTYExit, TTYInit.
volatile enum MCC_CHANNEL gChID
Referenced by ttyClearProperty, TTYExit, ttyFlush, ttyIsInitialized, ttyMccChannelEvent, TTYQuery, ttyWrite.
volatile int gQuery
Referenced by ttyClearProperty, ttyMccChannelEvent, TTYQuery.
volatile u32 gReadDone
Referenced by ttyClearProperty, ttyFlush, ttyMccChannelEvent.
volatile u32 gPrintfID
Referenced by ttyClearProperty, TTYFlush, TTYPrintf.
volatile u32 gBufHead
Referenced by ttyClearProperty, ttyFlush, ttyMccChannelEvent, TTYPrintf.
volatile u32 gBufTail
Referenced by ttyClearProperty, ttyFlush, ttyMccChannelEvent, TTYPrintf.
static int ttyIsInitialized()
References CARD_MAX_MOUNT_STEP, gChID.
Referenced by TTYExit, TTYFlush, TTYInit, TTYPrintf, TTYQuery.
static void ShowChannelInfo(enum MCC_CHANNEL chID)
References MCC_Info::blockLength, CARD_MAX_MOUNT_STEP, MCC_Info::connect, MCC_Info::firstBlock, MCC_Info::isLocked, MCCGetChannelInfo, OSReport.
static void ttyMccChannelEvent(enum MCC_CHANNEL chID, u32 event, u32 value)
References CARD_MAX_MOUNT_STEP, gBufHead, gBufTail, gChID, gQuery, gReadDone, size.
Referenced by TTYInit.
int TTYInit(enum MCC_EXI exiChannel, enum MCC_CHANNEL chID)
References CARD_MAX_MOUNT_STEP, gOldEvent, MCCInit, MCCOpen, MCCSetChannelEventMask, ttyClearProperty, ttyIsInitialized, ttyMccChannelEvent.
void TTYExit(void)
References gChID, gOldEvent, MCCClose, MCCSetChannelEventMask, ttyClearProperty, ttyIsInitialized.
int TTYQuery(void)
References CARD_MAX_MOUNT_STEP, gChID, gQuery, MCCNotify, OSGetTick, OSTicksToSeconds, ttyIsInitialized, ttyWaiting.
int TTYPrintf(const char *format,...)
References CARD_MAX_MOUNT_STEP, gBuf, gBufHead, gBufTail, gPrintfID, NULL, OSRoundUp32B, ttyFlush, ttyIsInitialized, ttyWrite.
int TTYFlush(void)
References gPrintfID, ttyFlush, ttyIsInitialized.
static void ttyClearProperty(enum MCC_CHANNEL chID)
References CARD_MAX_MOUNT_STEP, gBufHead, gBufTail, gChID, gPrintfID, gQuery, gReadDone.
Referenced by TTYExit, TTYInit.
static int ttyWaiting(int timeout, volatile int *flag)
References CARD_MAX_MOUNT_STEP, OSGetTick, OSSecondsToTicks, OSTicksToSeconds.
Referenced by TTYQuery.
static int ttyWrite(u32 offset, void *data, s32 size)
References gChID, MCCWrite, size.
Referenced by TTYPrintf.
static int ttyFlush(u32 msgID, int waitResult)
References CARD_MAX_MOUNT_STEP, gBufHead, gBufTail, gChID, gReadDone, MCCNotify.
Referenced by TTYFlush, TTYPrintf.