vi.c
CLAMP
MAX
MIN
static u32 getEncoderType(void)
Referenced by __VIInit, VIInit.
static s32 cntlzd(u64 bit)
References CARD_MAX_MOUNT_STEP.
Referenced by VIFlush, VISetRegs.
static BOOL VISetRegs(void)
References CARD_MAX_MOUNT_STEP, changeMode, cntlzd, FALSE, getCurrentFieldEvenOdd, shdwChanged, shdwRegs, TRUE.
Referenced by __VIRetraceHandler.
static void __VIRetraceHandler(__OSInterrupt interrupt, OSContext *context)
References CARD_MAX_MOUNT_STEP, changed, FALSE, flushFlag, OSClearContext, OSReport, OSSetCurrentContext, OSWakeupThread, PostCB, PreCB, retraceCount, retraceQueue, VISetRegs.
Referenced by VIInit.
VIRetraceCallback VISetPreRetraceCallback(VIRetraceCallback cb)
References CARD_MAX_MOUNT_STEP, cb, OSDisableInterrupts, OSRestoreInterrupts, PreCB.
Referenced by DEMOEnableBypassWorkaround.
VIRetraceCallback VISetPostRetraceCallback(VIRetraceCallback cb)
References CARD_MAX_MOUNT_STEP, cb, OSDisableInterrupts, OSRestoreInterrupts, PostCB.
static VITiming * getTiming(VITVMode mode)
References NULL, timing, VI_TVMODE_MPAL_DS, VI_TVMODE_MPAL_INT, VI_TVMODE_NTSC_DS, VI_TVMODE_NTSC_INT, VI_TVMODE_NTSC_PROG, VI_TVMODE_PAL_DS, VI_TVMODE_PAL_INT.
Referenced by __VIInit, getCurrentFieldEvenOdd, VIConfigure, VIInit.
void __VIInit(VITVMode mode)
References __VIInitPhilips, CARD_MAX_MOUNT_STEP, encoderType, getEncoderType, getTiming, OSPhysicalToCached, VI_TVMODE_NTSC_PROG.
Referenced by VIInit.
static void AdjustPosition(u16 acv)
References SomeVIStruct::AdjustedDispPosX, SomeVIStruct::AdjustedDispPosY, SomeVIStruct::AdjustedDispSizeY, SomeVIStruct::AdjustedPanPosY, SomeVIStruct::AdjustedPanSizeY, CARD_MAX_MOUNT_STEP, CLAMP, displayOffsetH, displayOffsetV, SomeVIStruct::DispPosX, SomeVIStruct::DispPosY, SomeVIStruct::DispSizeX, SomeVIStruct::DispSizeY, SomeVIStruct::FBMode, HorVer, MAX, MIN, SomeVIStruct::PanPosY, SomeVIStruct::PanSizeY, VI_XFB_MODE_SF.
Referenced by __VISetAdjustingValues, VIConfigure, VIConfigurePan, VIInit.
static void ImportAdjustingValues(void)
References __OSLockSram, __OSUnlockSram, CARD_MAX_MOUNT_STEP, OSSram::displayOffsetH, displayOffsetH, displayOffsetV.
Referenced by VIInit.
void VIInit(void)
References __OSSetInterruptHandler, __OSUnmaskInterrupts, __VIInit, __VIRetraceHandler, AdjustPosition, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, changed, changeMode, SomeVIStruct::DispPosX, SomeVIStruct::DispPosY, SomeVIStruct::DispSizeX, SomeVIStruct::DispSizeY, encoderType, SomeVIStruct::FBMode, SomeVIStruct::FBSizeX, SomeVIStruct::FBSizeY, flushFlag, getEncoderType, getTiming, HorVer, ImportAdjustingValues, SomeVIStruct::nonInter, NULL, OSInitThreadQueue, SomeVIStruct::PanPosX, SomeVIStruct::PanPosY, SomeVIStruct::PanSizeX, SomeVIStruct::PanSizeY, PostCB, PreCB, regs, retraceCount, retraceQueue, shdwChanged, SomeVIStruct::std, taps, SomeVIStruct::threeD, SomeVIStruct::timing, SomeVIStruct::tv, VI_TVMODE_NTSC_INT, VI_XFB_MODE_SF, SomeVIStruct::wordPerLine, SomeVIStruct::wpl, SomeVIStruct::xof.
Referenced by DEMOInit.
void VIWaitForRetrace(void)
References OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, retraceCount, retraceQueue.
Referenced by __DEMOInitVI, DEMOSwapBuffers, DEMOWinMenuChild.
static void setInterruptRegs(VITiming *tm)
References CARD_MAX_MOUNT_STEP, MARK_CHANGED, regs.
Referenced by VIConfigure.
static void setPicConfig(u16 fbSizeX, VIXFBMode xfbMode, u16 panPosX, u16 panSizeX, u8 *wordPerLine, u8 *std, u8 *wpl, u8 *xof)
References CARD_MAX_MOUNT_STEP, changed, regs, VI_XFB_MODE_SF.
Referenced by VIConfigure, VIConfigurePan.
static void setBBIntervalRegs(VITiming *tm)
References CARD_MAX_MOUNT_STEP, changed, regs.
Referenced by VIConfigure.
static void setScalingRegs(u16 panSizeX, u16 dispSizeX, BOOL threeD)
References CARD_MAX_MOUNT_STEP, changed, regs.
Referenced by VIConfigure, VIConfigurePan, VISet3D.
static void calcFbbs(u32 bufAddr, u16 panPosX, u16 panPosY, u8 wordPerLine, VIXFBMode xfbMode, u16 dispPosY, u32 *tfbb, u32 *bfbb)
References CARD_MAX_MOUNT_STEP, tmp, VI_XFB_MODE_SF.
Referenced by setFbbRegs.
static void setFbbRegs(SomeVIStruct *HorVer, u32 *tfbb, u32 *bfbb, u32 *rtfbb, u32 *rbfbb)
References SomeVIStruct::AdjustedDispPosY, SomeVIStruct::AdjustedPanPosY, SomeVIStruct::bufAddr, calcFbbs, CARD_MAX_MOUNT_STEP, SomeVIStruct::FBMode, HorVer, MARK_CHANGED, SomeVIStruct::PanPosX, SomeVIStruct::rbufAddr, regs, SomeVIStruct::threeD, SomeVIStruct::wordPerLine, SomeVIStruct::xof.
Referenced by __VISetAdjustingValues, VIConfigure, VIConfigurePan, VISetNextFrameBuffer, VISetNextRightFrameBuffer.
static void setHorizontalRegs(VITiming *tm, u16 dispPosX, u16 dispSizeX)
References CARD_MAX_MOUNT_STEP, MARK_CHANGED, regs.
Referenced by __VISetAdjustingValues, VIConfigure.
static void setVerticalRegs(u16 dispPosY, u16 dispSizeY, u8 equ, u16 acv, u16 prbOdd, u16 prbEven, u16 psbOdd, u16 psbEven, int black)
References CARD_MAX_MOUNT_STEP, MARK_CHANGED, regs.
Referenced by __VISetAdjustingValues, VIConfigure, VIConfigurePan, VISetBlack.
void VIConfigure(GXRenderModeObj *rm)
References SomeVIStruct::AdjustedDispPosX, SomeVIStruct::AdjustedDispPosY, SomeVIStruct::AdjustedDispSizeY, AdjustPosition, SomeVIStruct::bfbb, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, changed, changeMode, SomeVIStruct::DispPosX, SomeVIStruct::DispPosY, SomeVIStruct::DispSizeX, SomeVIStruct::DispSizeY, encoderType, SomeVIStruct::FBMode, FBSet, SomeVIStruct::FBSizeX, SomeVIStruct::FBSizeY, getTiming, HorVer, SomeVIStruct::nonInter, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::PanPosX, SomeVIStruct::PanPosY, SomeVIStruct::PanSizeX, SomeVIStruct::PanSizeY, SomeVIStruct::rbfbb, regs, SomeVIStruct::rtfbb, setBBIntervalRegs, setFbbRegs, setHorizontalRegs, setInterruptRegs, setPicConfig, setScalingRegs, setVerticalRegs, SomeVIStruct::std, SomeVIStruct::tfbb, SomeVIStruct::threeD, SomeVIStruct::timing, SomeVIStruct::tv, VI_BITMASK, VI_CLOCK_SEL, VI_DEBUG, VI_DISP_CONFIG, VI_NON_INTERLACE, VI_PROGRESSIVE, VI_TVMODE_NTSC_PROG, VI_XFB_MODE_DF, VI_XFB_MODE_SF, VIGetTvFormat, SomeVIStruct::wordPerLine, SomeVIStruct::wpl, SomeVIStruct::xof.
Referenced by DEMOInit, DEMOReInit.
void VIConfigurePan(u16 xOrg, u16 yOrg, u16 width, u16 height)
References SomeVIStruct::AdjustedDispPosY, AdjustPosition, SomeVIStruct::bfbb, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, SomeVIStruct::DispSizeX, SomeVIStruct::DispSizeY, SomeVIStruct::FBMode, FBSet, SomeVIStruct::FBSizeX, HorVer, SomeVIStruct::nonInter, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::PanPosX, SomeVIStruct::PanPosY, SomeVIStruct::PanSizeX, SomeVIStruct::PanSizeY, SomeVIStruct::rbfbb, SomeVIStruct::rtfbb, setFbbRegs, setPicConfig, setScalingRegs, setVerticalRegs, SomeVIStruct::std, SomeVIStruct::tfbb, SomeVIStruct::threeD, SomeVIStruct::timing, VI_XFB_MODE_DF, VI_XFB_MODE_SF, SomeVIStruct::wordPerLine, SomeVIStruct::wpl, SomeVIStruct::xof.
void VIFlush(void)
References CARD_MAX_MOUNT_STEP, changed, cntlzd, flushFlag, OSDisableInterrupts, OSRestoreInterrupts, regs, shdwChanged, shdwRegs.
Referenced by __DEMOInitVI, DEMOSwapBuffers.
void VISetNextFrameBuffer(void *fb)
References SomeVIStruct::bfbb, SomeVIStruct::bufAddr, CARD_MAX_MOUNT_STEP, FBSet, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::rbfbb, SomeVIStruct::rtfbb, setFbbRegs, SomeVIStruct::tfbb.
Referenced by __DEMOInitVI, DEMOSwapBuffers.
void VISetNextRightFrameBuffer(void *fb)
References SomeVIStruct::bfbb, CARD_MAX_MOUNT_STEP, FBSet, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::rbfbb, SomeVIStruct::rbufAddr, SomeVIStruct::rtfbb, setFbbRegs, SomeVIStruct::tfbb.
void VISetBlack(BOOL black)
References SomeVIStruct::AdjustedDispPosY, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, SomeVIStruct::DispSizeY, HorVer, OSDisableInterrupts, OSRestoreInterrupts, setVerticalRegs, SomeVIStruct::timing.
Referenced by DEMOSwapBuffers.
void VISet3D(BOOL threeD)
References CARD_MAX_MOUNT_STEP, SomeVIStruct::DispSizeX, HorVer, MARK_CHANGED, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::PanSizeX, regs, SET_REG_FIELD, setScalingRegs, SomeVIStruct::threeD.
u32 VIGetRetraceCount(void)
References retraceCount.
static u32 getCurrentHalfLine(void)
References CARD_MAX_MOUNT_STEP, HorVer, SomeVIStruct::timing.
Referenced by getCurrentFieldEvenOdd, VIGetCurrentLine.
static u32 getCurrentFieldEvenOdd(void)
References CARD_MAX_MOUNT_STEP, getCurrentHalfLine, getTiming, VI_TVMODE_NTSC_PROG.
Referenced by VIGetNextField, VISetRegs.
u32 VIGetNextField(void)
References SomeVIStruct::AdjustedDispPosY, CARD_MAX_MOUNT_STEP, getCurrentFieldEvenOdd, HorVer, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by DEMOBeforeRender.
u32 VIGetCurrentLine(void)
References CARD_MAX_MOUNT_STEP, getCurrentHalfLine, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::timing.
u32 VIGetTvFormat(void)
References CARD_MAX_MOUNT_STEP, OSPhysicalToCached.
Referenced by __DEMOInitRenderMode, GXInit, PADSetSamplingRate, VIConfigure.
u16 VIGetDTVStatus(void)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, VI_DTV_STAT.
void __VISetAdjustingValues(s16 x, s16 y)
References SomeVIStruct::AdjustedDispPosX, SomeVIStruct::AdjustedDispPosY, SomeVIStruct::AdjustedDispSizeY, AdjustPosition, SomeVIStruct::bfbb, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, displayOffsetH, displayOffsetV, SomeVIStruct::DispSizeX, FBSet, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::rbfbb, SomeVIStruct::rtfbb, setFbbRegs, setHorizontalRegs, setVerticalRegs, SomeVIStruct::tfbb, SomeVIStruct::timing.
void __VIGetAdjustingValues(s16 *x, s16 *y)
References displayOffsetH, displayOffsetV, OSDisableInterrupts, OSRestoreInterrupts.