vi_private.h
MARK_CHANGED
VI_BITMASK
volatile u32 retraceCount
Referenced by __VIRetraceHandler, VIGetRetraceCount, VIInit, VIWaitForRetrace.
u32 changeMode
Referenced by VIConfigure, VIInit, VISetRegs.
volatile u32 flushFlag
Referenced by __VIRetraceHandler, VIFlush, VIInit.
OSThreadQueue retraceQueue
Referenced by __VIRetraceHandler, VIInit, VIWaitForRetrace.
void(* PreCB) (u32))(u32)
Referenced by __VIRetraceHandler, VIInit, VISetPreRetraceCallback.
void(* PostCB) (u32))(u32)
Referenced by __VIRetraceHandler, VIInit, VISetPostRetraceCallback.
u32 encoderType
Referenced by __VIInit, VIConfigure, VIInit.
s16 displayOffsetH
Referenced by __VIGetAdjustingValues, __VISetAdjustingValues, AdjustPosition, ImportAdjustingValues.
s16 displayOffsetV
Referenced by __VIGetAdjustingValues, __VISetAdjustingValues, AdjustPosition, ImportAdjustingValues.
volatile u64 changed
Referenced by __VIRetraceHandler, setBBIntervalRegs, setPicConfig, setScalingRegs, VIConfigure, VIFlush, VIInit.
u16 regs[59][59]
Referenced by DBGEXISelect, setBBIntervalRegs, setFbbRegs, setHorizontalRegs, setInterruptRegs, setPicConfig, setScalingRegs, setVerticalRegs, VIConfigure, VIFlush, VIInit, VISet3D.
volatile u64 shdwChanged
Referenced by VIFlush, VIInit, VISetRegs.
u16 shdwRegs[59][59]
Referenced by VIFlush, VISetRegs.
VITiming timing[7][7]
Referenced by getTiming.
u16 taps[25][25]
Referenced by VIInit.
SomeVIStruct HorVer
Referenced by __VISetAdjustingValues, AdjustPosition, getCurrentHalfLine, setFbbRegs, VIConfigure, VIConfigurePan, VIGetCurrentLine, VIGetNextField, VIInit, VISet3D, VISetBlack, VISetNextFrameBuffer, VISetNextRightFrameBuffer.
u32 FBSet
Referenced by __VISetAdjustingValues, VIConfigure, VIConfigurePan, VISetNextFrameBuffer, VISetNextRightFrameBuffer.
static u32 getCurrentFieldEvenOdd(void)
void __VIInitI2C(void)
References initGpioExi, OS_USEC_TO_TICKS, OSGetTime, setI2CEnable, setVideoReset.
Referenced by __VIInitPhilips.
void __VISetSCL(int value)
References CARD_MAX_MOUNT_STEP, gpioOE, shadowGPIOOE.
Referenced by __VISendI2CData, sendSlaveAddr.
int __VIGetSCL(void)
References CARD_MAX_MOUNT_STEP, gpioInput.
Referenced by wait4ClkHigh.
void __VISetSDA(int value)
References CARD_MAX_MOUNT_STEP, gpioOE, shadowGPIOOE.
Referenced by __VISendI2CData, sendSlaveAddr.
int __VIGetSDA(void)
References CARD_MAX_MOUNT_STEP, gpioInput.
Referenced by __VISendI2CData, sendSlaveAddr.
int __VISendI2CData(u8 slaveAddr, u8 *pData, int nBytes)
References __VIGetSDA, __VISetSCL, __VISetSDA, CARD_MAX_MOUNT_STEP, lastError, sendSlaveAddr, wait4ClkHigh.
Referenced by send7120Data.
void __VIInitPhilips(void)
References __VIInitI2C, ntscRange0, ntscRange1, send7120Data.
Referenced by __VIInit.
void __VIInit(VITVMode mode)
References __VIInitPhilips, CARD_MAX_MOUNT_STEP, encoderType, getEncoderType, getTiming, OSPhysicalToCached, VI_TVMODE_NTSC_PROG.
Referenced by VIInit.
void __VISetAdjustingValues(s16 x, s16 y)
References SomeVIStruct::AdjustedDispPosX, SomeVIStruct::AdjustedDispPosY, SomeVIStruct::AdjustedDispSizeY, AdjustPosition, SomeVIStruct::bfbb, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, displayOffsetH, displayOffsetV, SomeVIStruct::DispSizeX, FBSet, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::rbfbb, SomeVIStruct::rtfbb, setFbbRegs, setHorizontalRegs, setVerticalRegs, SomeVIStruct::tfbb, SomeVIStruct::timing.
void __VIGetAdjustingValues(s16 *x, s16 *y)
References displayOffsetH, displayOffsetV, OSDisableInterrupts, OSRestoreInterrupts.