vifuncs.h
VIRetraceCallback VISetPreRetraceCallback(VIRetraceCallback cb)
References CARD_MAX_MOUNT_STEP, cb, OSDisableInterrupts, OSRestoreInterrupts, PreCB.
Referenced by DEMOEnableBypassWorkaround.
VIRetraceCallback VISetPostRetraceCallback(VIRetraceCallback cb)
References CARD_MAX_MOUNT_STEP, cb, OSDisableInterrupts, OSRestoreInterrupts, PostCB.
void VIInit(void)
References __OSSetInterruptHandler, __OSUnmaskInterrupts, __VIInit, __VIRetraceHandler, AdjustPosition, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, changed, changeMode, SomeVIStruct::DispPosX, SomeVIStruct::DispPosY, SomeVIStruct::DispSizeX, SomeVIStruct::DispSizeY, encoderType, SomeVIStruct::FBMode, SomeVIStruct::FBSizeX, SomeVIStruct::FBSizeY, flushFlag, getEncoderType, getTiming, HorVer, ImportAdjustingValues, SomeVIStruct::nonInter, NULL, OSInitThreadQueue, SomeVIStruct::PanPosX, SomeVIStruct::PanPosY, SomeVIStruct::PanSizeX, SomeVIStruct::PanSizeY, PostCB, PreCB, regs, retraceCount, retraceQueue, shdwChanged, SomeVIStruct::std, taps, SomeVIStruct::threeD, SomeVIStruct::timing, SomeVIStruct::tv, VI_TVMODE_NTSC_INT, VI_XFB_MODE_SF, SomeVIStruct::wordPerLine, SomeVIStruct::wpl, SomeVIStruct::xof.
Referenced by DEMOInit.
void VIWaitForRetrace(void)
References OSDisableInterrupts, OSRestoreInterrupts, OSSleepThread, retraceCount, retraceQueue.
Referenced by __DEMOInitVI, DEMOSwapBuffers, DEMOWinMenuChild.
void VIConfigure(GXRenderModeObj *rm)
References SomeVIStruct::AdjustedDispPosX, SomeVIStruct::AdjustedDispPosY, SomeVIStruct::AdjustedDispSizeY, AdjustPosition, SomeVIStruct::bfbb, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, changed, changeMode, SomeVIStruct::DispPosX, SomeVIStruct::DispPosY, SomeVIStruct::DispSizeX, SomeVIStruct::DispSizeY, encoderType, SomeVIStruct::FBMode, FBSet, SomeVIStruct::FBSizeX, SomeVIStruct::FBSizeY, getTiming, HorVer, SomeVIStruct::nonInter, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::PanPosX, SomeVIStruct::PanPosY, SomeVIStruct::PanSizeX, SomeVIStruct::PanSizeY, SomeVIStruct::rbfbb, regs, SomeVIStruct::rtfbb, setBBIntervalRegs, setFbbRegs, setHorizontalRegs, setInterruptRegs, setPicConfig, setScalingRegs, setVerticalRegs, SomeVIStruct::std, SomeVIStruct::tfbb, SomeVIStruct::threeD, SomeVIStruct::timing, SomeVIStruct::tv, VI_BITMASK, VI_CLOCK_SEL, VI_DEBUG, VI_DISP_CONFIG, VI_NON_INTERLACE, VI_PROGRESSIVE, VI_TVMODE_NTSC_PROG, VI_XFB_MODE_DF, VI_XFB_MODE_SF, VIGetTvFormat, SomeVIStruct::wordPerLine, SomeVIStruct::wpl, SomeVIStruct::xof.
Referenced by DEMOInit, DEMOReInit.
void VIConfigurePan(u16 xOrg, u16 yOrg, u16 width, u16 height)
References SomeVIStruct::AdjustedDispPosY, AdjustPosition, SomeVIStruct::bfbb, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, SomeVIStruct::DispSizeX, SomeVIStruct::DispSizeY, SomeVIStruct::FBMode, FBSet, SomeVIStruct::FBSizeX, HorVer, SomeVIStruct::nonInter, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::PanPosX, SomeVIStruct::PanPosY, SomeVIStruct::PanSizeX, SomeVIStruct::PanSizeY, SomeVIStruct::rbfbb, SomeVIStruct::rtfbb, setFbbRegs, setPicConfig, setScalingRegs, setVerticalRegs, SomeVIStruct::std, SomeVIStruct::tfbb, SomeVIStruct::threeD, SomeVIStruct::timing, VI_XFB_MODE_DF, VI_XFB_MODE_SF, SomeVIStruct::wordPerLine, SomeVIStruct::wpl, SomeVIStruct::xof.
void VIFlush(void)
References CARD_MAX_MOUNT_STEP, changed, cntlzd, flushFlag, OSDisableInterrupts, OSRestoreInterrupts, regs, shdwChanged, shdwRegs.
Referenced by __DEMOInitVI, DEMOSwapBuffers.
void VISetNextFrameBuffer(void *fb)
References SomeVIStruct::bfbb, SomeVIStruct::bufAddr, CARD_MAX_MOUNT_STEP, FBSet, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::rbfbb, SomeVIStruct::rtfbb, setFbbRegs, SomeVIStruct::tfbb.
Referenced by __DEMOInitVI, DEMOSwapBuffers.
void VISetNextRightFrameBuffer(void *fb)
References SomeVIStruct::bfbb, CARD_MAX_MOUNT_STEP, FBSet, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::rbfbb, SomeVIStruct::rbufAddr, SomeVIStruct::rtfbb, setFbbRegs, SomeVIStruct::tfbb.
void VISetBlack(BOOL black)
References SomeVIStruct::AdjustedDispPosY, SomeVIStruct::black, CARD_MAX_MOUNT_STEP, SomeVIStruct::DispSizeY, HorVer, OSDisableInterrupts, OSRestoreInterrupts, setVerticalRegs, SomeVIStruct::timing.
Referenced by DEMOSwapBuffers.
void VISet3D(BOOL threeD)
References CARD_MAX_MOUNT_STEP, SomeVIStruct::DispSizeX, HorVer, MARK_CHANGED, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::PanSizeX, regs, SET_REG_FIELD, setScalingRegs, SomeVIStruct::threeD.
u32 VIGetRetraceCount(void)
References retraceCount.
u32 VIGetNextField(void)
References SomeVIStruct::AdjustedDispPosY, CARD_MAX_MOUNT_STEP, getCurrentFieldEvenOdd, HorVer, OSDisableInterrupts, OSRestoreInterrupts.
Referenced by DEMOBeforeRender.
u32 VIGetCurrentLine(void)
References CARD_MAX_MOUNT_STEP, getCurrentHalfLine, HorVer, OSDisableInterrupts, OSRestoreInterrupts, SomeVIStruct::timing.
u32 VIGetTvFormat(void)
References CARD_MAX_MOUNT_STEP, OSPhysicalToCached.
Referenced by __DEMOInitRenderMode, GXInit, PADSetSamplingRate, VIConfigure.
u16 VIGetDTVStatus(void)
References CARD_MAX_MOUNT_STEP, OSDisableInterrupts, OSRestoreInterrupts, VI_DTV_STAT.