EnemyStrategy.h
typedef unsigned long size_t
typedef void *(* enemyStrategyInitFunc) (void *buf, int bufSize))(void *buf, int bufSize)
enemyStrategyInitFunc * getEnemyStrategyInitFunc(int i_entityIdx)
References gEnemyStrategyInitFuncs.
Referenced by EnCondStrategies::createCondStrategy, EnStrategyContainer::createStrategy, IncludeStrategy::setStrategy.