EnemyStrategy.cpp
float dummy[][]
enemyStrategyInitFunc gEnemyStrategyInitFuncs[187][187]
Referenced by getEnemyStrategyInitFunc.
enemyStrategyInitFunc * getEnemyStrategyInitFunc(int i_entityIdx)
References gEnemyStrategyInitFuncs.
Referenced by EnCondStrategies::createCondStrategy, EnStrategyContainer::createStrategy, IncludeStrategy::setStrategy.