IncludeStrategy
u8 IncludeStrategy::mStrategyMemory[0x800][0x800]
Referenced by getBuffer.
EnemyStrategy* IncludeStrategy::mpStrategy
Referenced by destroyStrategy, setStrategy.
IncludeStrategy::IncludeStrategy()
References destroyStrategy.
IncludeStrategy::~IncludeStrategy()
References destroyStrategy.
virtual void IncludeStrategy::unknownVirtualFunc()=0
void IncludeStrategy::setStrategy(int i_entityIdx)
References destroyStrategy, getBuffer, getEnemyStrategyInitFunc, mpStrategy.
void IncludeStrategy::destroyStrategy()
References mpStrategy, EnemyStrategy::~EnemyStrategy.
Referenced by IncludeStrategy, setStrategy, ~IncludeStrategy.
void * IncludeStrategy::getBuffer()
References mStrategyMemory.
Referenced by setStrategy.