EnCondStrategies
u8 EnCondStrategies::mBuffer[0x40][0x40]
Referenced by getBuffer.
EnemyStrategy* EnCondStrategies::mpCondStrategy
Referenced by createCondStrategy, destroyCondStrategy.
EnCondStrategies::~EnCondStrategies()
References destroyCondStrategy.
void EnCondStrategies::destroyCondStrategy()
References mpCondStrategy, EnemyStrategy::~EnemyStrategy.
Referenced by createCondStrategy, ~EnCondStrategies.
EnemyStrategy * EnCondStrategies::createCondStrategy(int i_condType)
References destroyCondStrategy, getBuffer, getCondStrategyId, getEnemyStrategyInitFunc, mpCondStrategy.
s32 EnCondStrategies::getCondStrategyId(int i_entityIdx)
Referenced by createCondStrategy.
void * EnCondStrategies::getBuffer()
References mBuffer.
Referenced by createCondStrategy.
int EnCondStrategies::getBufferSize()