EnemyStrategy
void* EnemyStrategy::mpZako
0x04
Referenced by EnemyStrategy, EnemyTypicalStrategy::onFishingBegin.
void* EnemyStrategy::mpUserData
0x08
Referenced by EnemyStrategy, EnemyTypicalStrategy::onFishingBegin.
u16 EnemyStrategy::mNextState
0x0C
Referenced by changeState, EnemyStrategy, setNextState, update.
u16 EnemyStrategy::mCurState
0x0E
Referenced by changeState, AITurara::doBehaviorInit, EnemyStrategy, EnemyStrategyDecorator::update.
s32 EnemyStrategy::mTimer
0x10
Referenced by changeState, EnemyStrategy, update.
EnemyStrategy::EnemyStrategy()
References mCurState, mNextState, mpUserData, mpZako, mTimer.
EnemyStrategy::~EnemyStrategy()
Referenced by EnCondStrategies::destroyCondStrategy, IncludeStrategy::destroyStrategy, EnStrategyContainer::destroyStrategy.
void EnemyStrategy::init()
void EnemyStrategy::update()
References changeState, doBehavior, mNextState, mTimer.
Referenced by EnemyStrategyDecorator::update.
s32 EnemyStrategy::unkEnemyStrategyFunc01()
void EnemyStrategy::unkEnemyStrategyFunc02()
void EnemyStrategy::doBehavior()
Referenced by update.
void EnemyStrategy::doBehaviorInit()
Referenced by changeState.
void EnemyStrategy::setNextState(s16 i_nextState)
References mNextState.
Referenced by EnemyTypicalStrategy::onFishingBegin, AITurara::procInit_init.
void EnemyStrategy::changeState()
References doBehaviorInit, mCurState, mNextState, mTimer.
Referenced by update.
void * EnemyStrategy::operator new(size_t size, void *mem)
void EnemyStrategy::operator delete(void *mem)