EnStrategyContainer
u8 EnStrategyContainer::mBuffer[0x180][0x180]
Referenced by getBuffer.
EnemyStrategy* EnStrategyContainer::mpStrategy
Referenced by createStrategy, destroyStrategy.
EnStrategyContainer::EnStrategyContainer()
EnStrategyContainer::~EnStrategyContainer()
References destroyStrategy.
virtual s32 EnStrategyContainer::getStrategyId(int i_entityIdx)=0
Referenced by createStrategy.
void EnStrategyContainer::destroyStrategy()
References mpStrategy, EnemyStrategy::~EnemyStrategy.
Referenced by createStrategy, ~EnStrategyContainer.
EnemyStrategy * EnStrategyContainer::createStrategy(int i_entityIdx)
References destroyStrategy, getBuffer, getEnemyStrategyInitFunc, getStrategyId, mpStrategy.
Referenced by EnemyTypicalStrategy::onFishingBegin.
void * EnStrategyContainer::getBuffer()
References mBuffer.
Referenced by createStrategy.
int EnStrategyContainer::getBufferSize()