JKRHeap.h
USE_MYHEAP
USE_SYSTEMHEAP
USE_CURRENTHEAP
USE_ROOTHEAP
typedef void(* JKRErrorRoutine) (JKRHeap *heap, size_t size, int align))(JKRHeap *heap, size_t size, int align)
void JKRDefaultMemoryErrorRoutine(JKRHeap *heao, size_t size, int align)
Referenced by JKRHeap::JKRHeap.
static void * JKRAllocFromHeap(JKRHeap *heap, size_t size, int align)
References JKRHeap::alloc.
Referenced by JKRExpHeap::create, JKRThread::setCommon_heapSpecified, JKRThread::setCommon_mesgQueue.
static JKRHeap * JKRGetSystemHeap()
References JKRHeap::sSystemHeap.
static JKRHeap * JKRGetCurrentHeap()
References JKRHeap::sCurrentHeap.
Referenced by JKRExpHeap::joinTwoBlocks.
static JKRHeap * JKRGetRootHeap()
References JKRHeap::sRootHeap.
static void JKRFree(void *obj)
References JKRHeap::free, Nil.
Referenced by JKRThread::~JKRThread.
static void JKRFreeToHeap(JKRHeap *heap, void *obj)
References JKRHeap::free.
Referenced by JKRExpHeap::destroy, JKRThread::~JKRThread.
void * operator new(size_t size)
References JKRHeap::alloc, Nil.
void * operator new(size_t size, int align)
References JKRHeap::alloc, Nil.
void * operator new(size_t size, JKRHeap *heap, int align)
References JKRHeap::alloc.
void * operator new[](size_t size)
void * operator new[](size_t size, int align)
void * operator new[](size_t size, JKRHeap *heap, int align)
void operator delete(void *data)
References JKRHeap::free, Nil.
void operator delete[](void *data)