JSUPtrList
JSUPtrLink* JSUPtrList::pFirst
0x00 // head link of list
Referenced by getFirstLink, initiate, insert, remove, setFirst, setNext, ~JSUPtrList.
JSUPtrLink* JSUPtrList::pLast
0x04 // tail link of list
Referenced by getLastLink, initiate, remove, setFirst, setLast.
u32 JSUPtrList::mNumLinks
0x08 // number of links in list
Referenced by append, getNumLinks, initiate, insert, prepend, remove, setFirst, setLast, setNext, ~JSUPtrList.
JSUPtrList::JSUPtrList()
References initiate.
JSUPtrList::JSUPtrList(BOOL do_init)
References initiate.
JSUPtrList::~JSUPtrList()
References mNumLinks, Nil, pFirst, JSUPtrLink::pPrev, JSUPtrLink::pSupervisor.
void JSUPtrList::initiate()
References mNumLinks, Nil, pFirst, pLast.
Referenced by JSUList< T >::initiate, JSUPtrList, JSUPtrList.
void JSUPtrList::setFirst(JSUPtrLink *link)
References mNumLinks, Nil, pFirst, pLast, JSUPtrLink::pNext, JSUPtrLink::pPrev, JSUPtrLink::pSupervisor.
Referenced by append, prepend.
void JSUPtrList::setLast(JSUPtrLink *link)
References mNumLinks, Nil, pLast, JSUPtrLink::pNext, JSUPtrLink::pPrev, JSUPtrLink::pSupervisor.
Referenced by append.
void JSUPtrList::setNext(JSUPtrLink *link)
References mNumLinks, Nil, pFirst, JSUPtrLink::pNext, JSUPtrLink::pPrev, JSUPtrLink::pSupervisor.
Referenced by prepend.
BOOL JSUPtrList::append(JSUPtrLink *link)
References BOOL, mNumLinks, Nil, JSUPtrLink::pSupervisor, remove, setFirst, setLast.
Referenced by JSUList< T >::append, insert.
BOOL JSUPtrList::prepend(JSUPtrLink *link)
References BOOL, mNumLinks, Nil, JSUPtrLink::pSupervisor, remove, setFirst, setNext.
Referenced by insert, JSUList< T >::prepend.
BOOL JSUPtrList::insert(JSUPtrLink *last, JSUPtrLink *next)
References append, BOOL, mNumLinks, Nil, pFirst, JSUPtrLink::pNext, JSUPtrLink::pPrev, prepend, JSUPtrLink::pSupervisor, remove.
Referenced by JSUList< T >::insert.
BOOL JSUPtrList::remove(JSUPtrLink *link)
References BOOL, mNumLinks, Nil, pFirst, pLast, JSUPtrLink::pNext, JSUPtrLink::pPrev, JSUPtrLink::pSupervisor.
Referenced by append, insert, prepend, JSUList< T >::remove, JSUPtrLink::~JSUPtrLink.
JSUPtrLink * JSUPtrList::getNthLink(u32 n) const
JSUPtrLink * JSUPtrList::getFirstLink() const
References pFirst.
Referenced by JSUList< T >::getFirst, JSUTree< T >::getFirstChild.
JSUPtrLink * JSUPtrList::getLastLink() const
References pLast.
Referenced by JSUList< T >::getLast, JSUTree< T >::getLastChild.
u32 JSUPtrList::getNumLinks() const
References mNumLinks.
Referenced by JSUList< T >::getNumLinks.