JSUTree
JSUTree< T >::JSUTree(T *owner)
JSUTree< T >::~JSUTree()
BOOL JSUTree< T >::appendChild(JSUTree< T > *child)
References JSUList< T >::append.
Referenced by JKRHeap::JKRHeap.
BOOL JSUTree< T >::prependChild(JSUTree< T > *child)
References JSUList< T >::prepend.
BOOL JSUTree< T >::removeChild(JSUTree< T > *child)
References JSUList< T >::remove.
Referenced by JKRHeap::~JKRHeap.
BOOL JSUTree< T >::insertChild(JSUTree< T > *before, JSUTree< T > *child)
References JSUList< T >::insert.
JSUTree< T > * JSUTree< T >::getEndChild() const
References Nil.
Referenced by JKRHeap::find.
JSUTree< T > * JSUTree< T >::getFirstChild() const
References JSUPtrList::getFirstLink.
Referenced by JKRHeap::find, JKRHeap::~JKRHeap.
JSUTree< T > * JSUTree< T >::getLastChild() const
References JSUPtrList::getLastLink.
JSUTree< T > * JSUTree< T >::getNextChild() const
References JSUPtrLink::pNext.
JSUTree< T > * JSUTree< T >::getPrevChild() const
References JSUPtrLink::pPrev.
u32 JSUTree< T >::getNumChildren() const
References JSUList< T >::getNumLinks.
Referenced by JKRHeap::find.
T * JSUTree< T >::getObject() const
References JSUPtrLink::pObject.
Referenced by JKRExpHeap::destroy, JKRHeap::getParent, JKRHeap::~JKRHeap.
JSUTree< T > * JSUTree< T >::getParent() const
References JSUPtrLink::pSupervisor.
Referenced by JKRExpHeap::destroy, JKRHeap::getParent, JKRHeap::~JKRHeap.