JKRExpHeap::CMemBlock
friend class JKRExpHeap
u16 JKRExpHeap::CMemBlock::mMagic
0x0
Referenced by JKRExpHeap::appendUsedList, initiate, isValid, JKRExpHeap::recycleFreeBlock, JKRExpHeap::setFreeBlock.
u8 JKRExpHeap::CMemBlock::mFlags
0x2 // a|bbbbbbb a=temporary b=align
Referenced by _isTempMemBlock, allocBack, allocFore, getAlignment, initiate, JKRExpHeap::joinTwoBlocks, JKRExpHeap::recycleFreeBlock, JKRExpHeap::resize.
u8 JKRExpHeap::CMemBlock::mGroupID
0x3
Referenced by allocBack, allocFore, JKRExpHeap::freeGroup, getGroupId, initiate, newGroupId, JKRExpHeap::recycleFreeBlock, JKRExpHeap::resize.
size_t JKRExpHeap::CMemBlock::mSize
0x4
Referenced by allocBack, allocFore, JKRExpHeap::allocFromHead, JKRExpHeap::allocFromHead, JKRExpHeap::freeGroup, getSize, JKRExpHeap::getSize, initiate, JKRExpHeap::joinTwoBlocks, JKRExpHeap::recycleFreeBlock, JKRExpHeap::resize.
CMemBlock* JKRExpHeap::CMemBlock::mPrev
0x8
Referenced by JKRExpHeap::allocFromHead, JKRExpHeap::allocFromHead, JKRExpHeap::appendUsedList, JKRExpHeap::dump_sort, getPrevBlock, initiate, JKRExpHeap::joinTwoBlocks, JKRExpHeap::recycleFreeBlock, JKRExpHeap::removeFreeBlock, JKRExpHeap::removeUsedBlock, JKRExpHeap::setFreeBlock.
CMemBlock* JKRExpHeap::CMemBlock::mNext
0xC
Referenced by JKRExpHeap::allocFromHead, JKRExpHeap::allocFromHead, JKRExpHeap::appendUsedList, JKRExpHeap::check, JKRExpHeap::dump, JKRExpHeap::dump_sort, JKRExpHeap::freeGroup, JKRExpHeap::freeTail, JKRExpHeap::getFreeSize, getNextBlock, JKRExpHeap::getTotalFreeSize, JKRExpHeap::getUsedSize, initiate, JKRExpHeap::joinTwoBlocks, JKRExpHeap::recycleFreeBlock, JKRExpHeap::removeFreeBlock, JKRExpHeap::removeUsedBlock, JKRExpHeap::resize, JKRExpHeap::setFreeBlock.
JKRExpHeap::CMemBlock * JKRExpHeap::CMemBlock::getHeapBlock(void *obj)
References Nil.
Referenced by JKRExpHeap::free, JKRExpHeap::getSize, JKRExpHeap::resize.
static CMemBlock * JKRExpHeap::CMemBlock::getBlock(void *data)
void JKRExpHeap::CMemBlock::initiate(CMemBlock *prev, CMemBlock *next, size_t size, u8 groupId, u8 align)
References mFlags, mGroupID, mMagic, mNext, mPrev, mSize.
Referenced by JKRExpHeap::freeAll, JKRExpHeap::JKRExpHeap, JKRExpHeap::recycleFreeBlock.
JKRExpHeap::CMemBlock * JKRExpHeap::CMemBlock::allocFore(size_t size, u8 group_id, u8 align_1, u8 group_id_2, u8 align_2)
References mFlags, mGroupID, JKRExpHeap::mGroupID, mSize, JKRHeap::mSize, Nil.
Referenced by JKRExpHeap::allocFromHead, JKRExpHeap::allocFromHead, JKRExpHeap::resize.
JKRExpHeap::CMemBlock * JKRExpHeap::CMemBlock::allocBack(size_t size, u8 group_id_1, u8 align_1, u8 group_id_2, u8 align_2)
References mFlags, mGroupID, JKRExpHeap::mGroupID, mSize, JKRHeap::mSize, Nil.
void * JKRExpHeap::CMemBlock::free(JKRExpHeap *heap)
References Nil, JKRExpHeap::recycleFreeBlock, JKRExpHeap::removeUsedBlock.
Referenced by JKRExpHeap::free, JKRExpHeap::freeGroup, JKRExpHeap::freeTail.
void JKRExpHeap::CMemBlock::newGroupId(u8 group_id)
References mGroupID.
bool JKRExpHeap::CMemBlock::isValid() const
References mMagic.
bool JKRExpHeap::CMemBlock::_isTempMemBlock() const
References mFlags.
int JKRExpHeap::CMemBlock::getAlignment() const
References mFlags.
void * JKRExpHeap::CMemBlock::getContent() const
Referenced by JKRExpHeap::allocFromHead, JKRExpHeap::allocFromHead.
CMemBlock * JKRExpHeap::CMemBlock::getPrevBlock() const
References mPrev.
CMemBlock * JKRExpHeap::CMemBlock::getNextBlock() const
References mNext.
u32 JKRExpHeap::CMemBlock::getSize() const
References mSize.
u8 JKRExpHeap::CMemBlock::getGroupId() const
References mGroupID.