JKRHeap
friend class JKRSolidHeap
friend class JKRExpHeap
JKRHeap * JKRHeap::sSystemHeap
Referenced by becomeSystemHeap, getSystemHeap, JKRGetSystemHeap, JKRHeap, ~JKRHeap.
JKRHeap * JKRHeap::sCurrentHeap
Referenced by alloc, becomeCurrentHeap, getCurrentHeap, JKRGetCurrentHeap, JKRHeap, ~JKRHeap.
JKRHeap * JKRHeap::sRootHeap
Referenced by JKRExpHeap::create, JKRSolidHeap::create, JKRExpHeap::createRoot, getRootHeap, JKRGetRootHeap, JKRHeap, ~JKRHeap.
JKRErrorRoutine JKRHeap::mErrorHandler
Referenced by JKRSolidHeap::allocFromHead, JKRSolidHeap::allocFromTail, callErrorHandler, JKRHeap.
OSMutex JKRHeap::mMutex
0x18
Referenced by JKRHeap, lock, unlock.
void* JKRHeap::mStart
0x30
Referenced by JKRSolidHeap::adjustSize, JKRSolidHeap::check, find, JKRExpHeap::free, JKRExpHeap::freeAll, JKRSolidHeap::freeAll, JKRExpHeap::getSize, JKRHeap, JKRExpHeap::resize.
void* JKRHeap::mEnd
0x34
Referenced by JKRSolidHeap::adjustSize, JKRSolidHeap::check, find, JKRExpHeap::free, JKRSolidHeap::freeAll, JKRSolidHeap::freeTail, JKRExpHeap::getSize, JKRHeap, JKRExpHeap::resize.
size_t JKRHeap::mSize
0x38
Referenced by JKRSolidHeap::adjustSize, JKRExpHeap::CMemBlock::allocBack, JKRExpHeap::CMemBlock::allocFore, JKRExpHeap::allocFromHead, JKRExpHeap::allocFromHead, JKRExpHeap::check, JKRSolidHeap::check, JKRExpHeap::dump, JKRExpHeap::freeAll, JKRSolidHeap::freeAll, JKRHeap.
JSUTree<JKRHeap> JKRHeap::mHeapTree
0x3C
Referenced by JKRExpHeap::destroy, find, getHeapTree, getParent, JKRHeap, ~JKRHeap.
JSUList<JKRDisposer> JKRHeap::mDisposerList
0x58
Referenced by appendDisposer, dispose, dispose_subroutine, freeAll, removeDisposer.
BOOL JKRHeap::mErrorFlag
0x64
Referenced by JKRSolidHeap::allocFromHead, JKRSolidHeap::allocFromTail, getErrorFlag, JKRHeap.
BOOL JKRHeap::initArena(char **ramStart, u32 *ramSize, int maxHeaps)
References FALSE, TRUE.
Referenced by JKRExpHeap::createRoot.
void * JKRHeap::alloc(size_t size, int align, JKRHeap *heap)
References alloc, Nil, sCurrentHeap.
Referenced by alloc, JKRSolidHeap::create, JKRAllocFromHeap, operator new, operator new, operator new.
void JKRHeap::free(void *ptr, JKRHeap *heap)
References findFromRoot, free, Nil.
Referenced by JKRSolidHeap::destroy, free, JKRFree, JKRFreeToHeap, operator delete.
JKRHeap * JKRHeap::findFromRoot(void *)
References find, getRootHeap, Nil.
Referenced by free, JKRDisposer::JKRDisposer, JKRThread::JKRThread.
void JKRHeap::copyMemory(void *, void *, u32)
References __copyMemory.
static JKRHeap * JKRHeap::getSystemHeap()
References sSystemHeap.
Referenced by JKRThread::JKRThread.
static JKRHeap * JKRHeap::getCurrentHeap()
References sCurrentHeap.
static JKRHeap * JKRHeap::getRootHeap()
References sRootHeap.
Referenced by findFromRoot.
void JKRHeap::appendDisposer(JKRDisposer *disposer)
References JSUList< T >::append, mDisposerList, JKRDisposer::mHeapLink.
Referenced by JKRDisposer::JKRDisposer.
void JKRHeap::removeDisposer(JKRDisposer *disposer)
References mDisposerList, JKRDisposer::mHeapLink, JSUList< T >::remove.
Referenced by JKRDisposer::~JKRDisposer.
BOOL JKRHeap::getErrorFlag()
References mErrorFlag.
Referenced by JKRExpHeap::alloc.
void JKRHeap::callErrorHandler(JKRHeap *heap, size_t size, int align)
References mErrorHandler, Nil.
Referenced by JKRExpHeap::alloc.
JKRHeap::JKRHeap(void *obj, size_t size, JKRHeap *parent, bool is_error)
References JSUTree< T >::appendChild, becomeCurrentHeap, becomeSystemHeap, JKRDefaultMemoryErrorRoutine, mEnd, mErrorFlag, mErrorHandler, mHeapTree, mMutex, mSize, mStart, Nil, sCurrentHeap, sRootHeap, sSystemHeap.
JKRHeap::~JKRHeap()
0x08v
References JSUTree< T >::getFirstChild, JSUTree< T >::getObject, JSUTree< T >::getParent, mHeapTree, Nil, JSUTree< T >::removeChild, sCurrentHeap, sRootHeap, sSystemHeap.
JKRHeap * JKRHeap::becomeSystemHeap(void)
References sSystemHeap, USE_SYSTEMHEAP.
Referenced by JKRHeap.
JKRHeap * JKRHeap::becomeCurrentHeap(void)
References sCurrentHeap, USE_CURRENTHEAP.
Referenced by JKRHeap.
JKRHeap * JKRHeap::find(void *obj) const
References find, JSUTree< T >::getEndChild, JSUTree< T >::getFirstChild, JSUTree< T >::getNumChildren, mEnd, mHeapTree, mStart, Nil.
Referenced by find, findFromRoot.
void JKRHeap::dispose_subroutine(size_t start, size_t end)
References JSUList< T >::getEnd, JSUList< T >::getFirst, JSUListIterator< T >::getObject, mDisposerList, Nil.
Referenced by dispose, dispose.
int JKRHeap::dispose(void *, u32)
References dispose_subroutine.
void JKRHeap::dispose(void *, void *)
References dispose_subroutine.
void JKRHeap::dispose(void)
References JSUList< T >::getEnd, JSUList< T >::getFirst, mDisposerList.
Referenced by JKRExpHeap::freeGroup, JKRExpHeap::freeTail, JKRSolidHeap::freeTail, JKRExpHeap::~JKRExpHeap, JKRSolidHeap::~JKRSolidHeap.
virtual void * JKRHeap::alloc(size_t size, int align)=0
0x0Cv
virtual void JKRHeap::free(void *ptr)=0
0x10v
void JKRHeap::freeAll(void)
0x14v
References JSUList< T >::getEnd, JSUList< T >::getFirst, JSUListIterator< T >::getObject, mDisposerList.
Referenced by JKRExpHeap::freeAll, JKRSolidHeap::freeAll.
virtual void JKRHeap::freeTail(void)=0
0x18v
virtual size_t JKRHeap::resize(void *, size_t)=0
0x1Cv
Referenced by JKRSolidHeap::adjustSize.
virtual size_t JKRHeap::getSize(void *)=0
0x20v
virtual size_t JKRHeap::getFreeSize(void)=0
0x24v
virtual size_t JKRHeap::getTotalFreeSize(void)=0
0x28v
virtual u32 JKRHeap::getHeapType(void)=0
0x2Cv
virtual BOOL JKRHeap::check(void)=0
0x30v
virtual BOOL JKRHeap::dump(void)=0
0x34v
Referenced by JKRExpHeap::joinTwoBlocks.
u32 JKRHeap::getUNK(void)
0x38v
u32 JKRHeap::getCurrentGroupId(void)
0x3Cv
void JKRHeap::unlock()
References mMutex.
Referenced by JKRSolidHeap::adjustSize, JKRExpHeap::alloc, JKRSolidHeap::alloc, JKRExpHeap::changeGroupID, JKRExpHeap::check, JKRSolidHeap::check, JKRExpHeap::dump, JKRSolidHeap::dump, JKRExpHeap::dump_sort, JKRExpHeap::free, JKRExpHeap::freeAll, JKRSolidHeap::freeAll, JKRExpHeap::freeGroup, JKRExpHeap::freeTail, JKRSolidHeap::freeTail, JKRExpHeap::getFreeSize, JKRExpHeap::getSize, JKRExpHeap::getTotalFreeSize, JKRExpHeap::getUsedSize, JKRExpHeap::resize.
void JKRHeap::lock()
References mMutex.
Referenced by JKRSolidHeap::adjustSize, JKRExpHeap::alloc, JKRSolidHeap::alloc, JKRExpHeap::changeGroupID, JKRExpHeap::check, JKRSolidHeap::check, JKRExpHeap::dump, JKRSolidHeap::dump, JKRExpHeap::dump_sort, JKRExpHeap::free, JKRExpHeap::freeAll, JKRSolidHeap::freeAll, JKRExpHeap::freeGroup, JKRExpHeap::freeTail, JKRSolidHeap::freeTail, JKRExpHeap::getFreeSize, JKRExpHeap::getSize, JKRExpHeap::getTotalFreeSize, JKRExpHeap::getUsedSize, JKRExpHeap::resize.
JSUTree< JKRHeap > & JKRHeap::getHeapTree()
References mHeapTree.
JKRHeap * JKRHeap::getParent() const
References JSUTree< T >::getObject, JSUTree< T >::getParent, mHeapTree.
Referenced by JKRSolidHeap::adjustSize, JKRSolidHeap::destroy.