JSUList
JSUList< T >::JSUList(BOOL init)
JSUList< T >::JSUList()
void JSUList< T >::initiate()
References JSUPtrList::initiate.
BOOL JSUList< T >::append(JSULink< T > *link)
References JSUPtrList::append.
Referenced by JSUTree< T >::appendChild, JKRHeap::appendDisposer.
BOOL JSUList< T >::prepend(JSULink< T > *link)
References JSUPtrList::prepend.
Referenced by JSUTree< T >::prependChild.
BOOL JSUList< T >::insert(JSULink< T > *prev, JSULink< T > *next)
References JSUPtrList::insert.
Referenced by JSUTree< T >::insertChild.
BOOL JSUList< T >::remove(JSULink< T > *link)
References JSUPtrList::remove.
Referenced by JSUTree< T >::removeChild, JKRHeap::removeDisposer.
JSULink< T > * JSUList< T >::getFirst() const
References JSUPtrList::getFirstLink.
Referenced by JKRHeap::dispose, JKRHeap::dispose_subroutine, JKRHeap::freeAll.
JSULink< T > * JSUList< T >::getLast() const
References JSUPtrList::getLastLink.
JSULink< T > * JSUList< T >::getEnd() const
References Nil.
Referenced by JKRHeap::dispose, JKRHeap::dispose_subroutine, JKRHeap::freeAll.
u32 JSUList< T >::getNumLinks() const
References JSUPtrList::getNumLinks.
Referenced by JSUTree< T >::getNumChildren.