JKRExpHeap
EAllocMode
friend class CMemBlock
u8 JKRExpHeap::mAllocMode
0x6C
Referenced by allocFromHead, allocFromHead, JKRExpHeap, setAllocationMode.
u8 JKRExpHeap::mGroupID
0x6D
Referenced by JKRExpHeap::CMemBlock::allocBack, JKRExpHeap::CMemBlock::allocFore, allocFromHead, allocFromHead, changeGroupID, getCurrentGroupId, JKRExpHeap.
bool JKRExpHeap::mIsRoot
0x6E
Referenced by create, createRoot, destroy.
void* JKRExpHeap::_68
0x68
u32 JKRExpHeap::_6C
0x6C
CMemBlock* JKRExpHeap::mFreeHeadList
0x70
Referenced by allocFromHead, allocFromHead, check, dump, dump_sort, freeAll, getFreeSize, getTotalFreeSize, JKRExpHeap, recycleFreeBlock, removeFreeBlock, resize, setFreeBlock.
CMemBlock* JKRExpHeap::mFreeTailList
0x74
Referenced by check, dump_sort, freeAll, JKRExpHeap, recycleFreeBlock, removeFreeBlock, setFreeBlock.
CMemBlock* JKRExpHeap::mUsedHeadList
0x78
Referenced by appendUsedList, check, dump, dump_sort, freeAll, freeGroup, freeTail, getHeadUsedList, getUsedSize, JKRExpHeap, removeUsedBlock.
CMemBlock* JKRExpHeap::mUsedTailList
0x7C
Referenced by appendUsedList, check, dump_sort, freeAll, JKRExpHeap, removeUsedBlock.
JKRExpHeap * JKRExpHeap::createRoot(int maxHeaps, bool errorFlag)
References JKRHeap::initArena, mIsRoot, Nil, JKRHeap::sRootHeap, TRUE.
JKRExpHeap * JKRExpHeap::create(size_t size, JKRHeap *parent, bool errorFlag)
References FALSE, JKRAllocFromHeap, mIsRoot, Nil, JKRHeap::sRootHeap.
static JKRExpHeap * JKRExpHeap::create(void *obj, size_t size, JKRHeap *parent, bool errorFlag)
void JKRExpHeap::destroy(void)
References JSUTree< T >::getObject, JSUTree< T >::getParent, JKRFreeToHeap, JKRHeap::mHeapTree, mIsRoot, Nil, ~JKRExpHeap.
u8 JKRExpHeap::changeGroupID(u8 group_id)
References JKRHeap::lock, mGroupID, JKRHeap::unlock.
void * JKRExpHeap::alloc(size_t size, int align)
0x0Cv
References allocFromHead, allocFromTail, JKRHeap::callErrorHandler, dump, dump_sort, JKRHeap::getErrorFlag, JKRHeap::lock, Nil, JKRHeap::unlock, whatdo, whatdo2.
void JKRExpHeap::free(void *obj)
0x10v
References JKRExpHeap::CMemBlock::free, JKRExpHeap::CMemBlock::getHeapBlock, JKRHeap::lock, JKRHeap::mEnd, JKRHeap::mStart, Nil, JKRHeap::unlock.
void JKRExpHeap::freeAll(void)
0x14v
References JKRHeap::freeAll, JKRExpHeap::CMemBlock::initiate, JKRHeap::lock, mFreeHeadList, mFreeTailList, JKRHeap::mSize, JKRHeap::mStart, mUsedHeadList, mUsedTailList, Nil, JKRHeap::unlock.
void JKRExpHeap::freeTail(void)
0x18v
References JKRHeap::dispose, JKRExpHeap::CMemBlock::free, JKRHeap::lock, JKRExpHeap::CMemBlock::mNext, mUsedHeadList, Nil, JKRHeap::unlock.
s32 JKRExpHeap::freeGroup(u8 groupID)
References JKRHeap::dispose, JKRExpHeap::CMemBlock::free, JKRHeap::lock, JKRExpHeap::CMemBlock::mGroupID, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mSize, mUsedHeadList, Nil, JKRHeap::unlock.
size_t JKRExpHeap::resize(void *obj, size_t size)
0x1Cv
References JKRExpHeap::CMemBlock::allocFore, JKRExpHeap::CMemBlock::getHeapBlock, JKRHeap::lock, JKRHeap::mEnd, JKRExpHeap::CMemBlock::mFlags, mFreeHeadList, JKRExpHeap::CMemBlock::mGroupID, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mSize, JKRHeap::mStart, Nil, recycleFreeBlock, removeFreeBlock, JKRHeap::unlock.
size_t JKRExpHeap::getSize(void *obj)
0x20v
References JKRExpHeap::CMemBlock::getHeapBlock, JKRHeap::lock, JKRHeap::mEnd, JKRExpHeap::CMemBlock::mSize, JKRHeap::mStart, Nil, JKRHeap::unlock.
size_t JKRExpHeap::getFreeSize(void)
0x24v
References JKRHeap::lock, mFreeHeadList, JKRExpHeap::CMemBlock::mNext, Nil, JKRHeap::unlock.
size_t JKRExpHeap::getTotalFreeSize(void)
0x28v
References JKRHeap::lock, mFreeHeadList, JKRExpHeap::CMemBlock::mNext, Nil, JKRHeap::unlock.
size_t JKRExpHeap::getUsedSize(u8 group_id) const
References JKRHeap::lock, JKRExpHeap::CMemBlock::mNext, mUsedHeadList, JKRHeap::unlock.
size_t JKRExpHeap::getTotalUsedSize(void) const
u32 JKRExpHeap::getHeapType(void)
0x2Cv
bool JKRExpHeap::check(void)
0x30v
References JKRHeap::lock, mFreeHeadList, mFreeTailList, JKRExpHeap::CMemBlock::mNext, JKRHeap::mSize, mUsedHeadList, mUsedTailList, JKRHeap::unlock.
Referenced by dump.
bool JKRExpHeap::dump(void)
0x34v
References check, JUTReportConsole, JUTReportConsole_f, JKRHeap::lock, mFreeHeadList, JKRExpHeap::CMemBlock::mNext, JKRHeap::mSize, mUsedHeadList, JKRHeap::unlock.
Referenced by alloc.
BOOL JKRExpHeap::dump_sort(void)
References JKRHeap::lock, mFreeHeadList, mFreeTailList, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, mUsedHeadList, mUsedTailList, JKRHeap::unlock.
Referenced by alloc.
u32 JKRExpHeap::getUNK(void)
0x38v
u32 JKRExpHeap::getCurrentGroupId(void)
0x3Cv
References mGroupID.
CMemBlock * JKRExpHeap::getHeadUsedList() const
References mUsedHeadList.
void JKRExpHeap::setAllocationMode(EAllocMode mode)
References mAllocMode.
JKRExpHeap::JKRExpHeap(void *data, size_t size, JKRHeap *parent, bool error)
References ALLOC_HEAD, JKRExpHeap::CMemBlock::initiate, mAllocMode, mFreeHeadList, mFreeTailList, mGroupID, mUsedHeadList, mUsedTailList, Nil.
JKRExpHeap::~JKRExpHeap()
References JKRHeap::dispose.
Referenced by destroy.
void * JKRExpHeap::allocFromHead(size_t size, int align)
References ALLOC_HEAD, JKRExpHeap::CMemBlock::allocFore, appendUsedList, DBfoundBlock, DBfoundOffset, DBfoundSize, DBnewFreeBlock, DBnewUsedBlock, JKRExpHeap::CMemBlock::getContent, mAllocMode, mFreeHeadList, mGroupID, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, JKRExpHeap::CMemBlock::mSize, JKRHeap::mSize, Nil, removeFreeBlock, setFreeBlock, whatdo2.
Referenced by alloc.
void * JKRExpHeap::allocFromHead(size_t size)
References ALLOC_HEAD, JKRExpHeap::CMemBlock::allocFore, appendUsedList, JKRExpHeap::CMemBlock::getContent, mAllocMode, mFreeHeadList, mGroupID, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, JKRExpHeap::CMemBlock::mSize, JKRHeap::mSize, Nil, removeFreeBlock, setFreeBlock, whatdo2.
void * JKRExpHeap::allocFromTail(size_t size, int align)
Referenced by alloc.
void * JKRExpHeap::allocFromTail(size_t size)
void JKRExpHeap::appendUsedList(CMemBlock *block)
References JKRExpHeap::CMemBlock::mMagic, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, mUsedHeadList, mUsedTailList, Nil.
Referenced by allocFromHead, allocFromHead.
void JKRExpHeap::setFreeBlock(CMemBlock *block, CMemBlock *prev, CMemBlock *next)
References mFreeHeadList, mFreeTailList, JKRExpHeap::CMemBlock::mMagic, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, Nil.
Referenced by allocFromHead, allocFromHead, joinTwoBlocks, recycleFreeBlock.
void JKRExpHeap::removeFreeBlock(CMemBlock *block)
References mFreeHeadList, mFreeTailList, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, Nil.
Referenced by allocFromHead, allocFromHead, resize.
void JKRExpHeap::removeUsedBlock(CMemBlock *block)
References JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, mUsedHeadList, mUsedTailList, Nil.
Referenced by JKRExpHeap::CMemBlock::free.
void JKRExpHeap::recycleFreeBlock(CMemBlock *block)
References JKRExpHeap::CMemBlock::initiate, joinTwoBlocks, JKRExpHeap::CMemBlock::mFlags, mFreeHeadList, mFreeTailList, JKRExpHeap::CMemBlock::mGroupID, JKRExpHeap::CMemBlock::mMagic, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, JKRExpHeap::CMemBlock::mSize, Nil, setFreeBlock.
Referenced by JKRExpHeap::CMemBlock::free, resize.
void JKRExpHeap::joinTwoBlocks(CMemBlock *block)
References JKRHeap::dump, JKRGetCurrentHeap, JKRExpHeap::CMemBlock::mFlags, JKRExpHeap::CMemBlock::mNext, JKRExpHeap::CMemBlock::mPrev, JKRExpHeap::CMemBlock::mSize, setFreeBlock.
Referenced by recycleFreeBlock.