JKRSolidHeap
typedef struct Iter JKRSolidHeap::Iter
size_t JKRSolidHeap::mFreeSize
Referenced by adjustSize, allocFromHead, allocFromTail, check, freeAll, freeTail, getFreeSize.
void* JKRSolidHeap::mHead
Referenced by adjustSize, allocFromHead, check, freeAll.
void* JKRSolidHeap::mTail
Referenced by adjustSize, allocFromTail, check, freeAll, freeTail.
Iter* JKRSolidHeap::mIter
Referenced by freeAll, freeTail.
JKRSolidHeap * JKRSolidHeap::create(size_t size, JKRHeap *parent, BOOL isError)
References JKRHeap::alloc, Nil, JKRHeap::sRootHeap.
void JKRSolidHeap::destroy(void)
References JKRHeap::free, JKRHeap::getParent, Nil, ~JKRSolidHeap.
void * JKRSolidHeap::alloc(size_t size, int align)
0x0Cv
References allocFromHead, allocFromTail, JKRHeap::lock, JKRHeap::unlock.
void * JKRSolidHeap::allocFromHead(size_t size, int align)
References JKRHeap::mErrorFlag, JKRHeap::mErrorHandler, mFreeSize, mHead, Nil.
Referenced by alloc.
void * JKRSolidHeap::allocFromTail(size_t size, int align)
References JKRHeap::mErrorFlag, JKRHeap::mErrorHandler, mFreeSize, mTail, Nil.
Referenced by alloc.
void JKRSolidHeap::free(void *ptr)
0x10v
void JKRSolidHeap::freeAll(void)
0x14v
References JKRHeap::freeAll, JKRHeap::lock, JKRHeap::mEnd, mFreeSize, mHead, mIter, JKRHeap::mSize, JKRHeap::mStart, mTail, Nil, JKRHeap::unlock.
void JKRSolidHeap::freeTail(void)
0x18v
References JKRHeap::dispose, JKRHeap::lock, JKRHeap::mEnd, mFreeSize, JKRSolidHeap::Iter::mHead, mIter, mTail, Nil, JKRHeap::unlock.
size_t JKRSolidHeap::resize(void *obj, size_t size)
0x1Cv
s32 JKRSolidHeap::adjustSize(void)
References JKRHeap::getParent, JKRHeap::lock, JKRHeap::mEnd, mFreeSize, mHead, JKRHeap::mSize, JKRHeap::mStart, mTail, Nil, JKRHeap::resize, JKRHeap::unlock.
size_t JKRSolidHeap::getSize(void *obj)
0x20v
override size_t JKRSolidHeap::getFreeSize(void)
0x24v
References mFreeSize.
size_t JKRSolidHeap::getTotalFreeSize(void)
0x28v
References getTotalFreeSize.
Referenced by getTotalFreeSize.
u32 JKRSolidHeap::getHeapType(void)
0x2Cv
BOOL JKRSolidHeap::check(void)
0x30v
References BOOL, check, JKRHeap::lock, JKRHeap::mEnd, mFreeSize, mHead, JKRHeap::mSize, JKRHeap::mStart, mTail, JKRHeap::unlock.
Referenced by check.
BOOL JKRSolidHeap::dump(void)
0x34v
References BOOL, dump, JKRHeap::lock, JKRHeap::unlock.
Referenced by dump.
JKRSolidHeap::JKRSolidHeap(void *obj, size_t size, JKRHeap *parent, bool is_error)
JKRSolidHeap::~JKRSolidHeap()
References JKRHeap::dispose.
Referenced by destroy.