JKRThread
JSULink<JKRThread> JKRThread::mLink
0x18
Referenced by setCommon_mesgQueue, ~JKRThread.
JKRHeap* JKRThread::mCurrHeap
0x28
Referenced by JKRThread, setCommon_heapSpecified, setCommon_mesgQueue, ~JKRThread.
OSThread* JKRThread::mThreadRecord
0x2C
Referenced by setCommon_heapSpecified, ~JKRThread.
OSMessageQueue JKRThread::mMesgQueue
0x30
Referenced by setCommon_mesgQueue.
void* JKRThread::mMesgArray
0x50
Referenced by setCommon_mesgQueue, ~JKRThread.
int JKRThread::mMesgCount
0x54
Referenced by setCommon_mesgQueue.
void* JKRThread::mStack
0x58
Referenced by setCommon_heapSpecified, ~JKRThread.
size_t JKRThread::mStackSize
0x5C
Referenced by setCommon_heapSpecified.
constructor JKRThread::JKRThread(OSThread *thread, int i)
JKRThread::JKRThread(size_t size, int mesg_count, int priority)
References JKRHeap::findFromRoot, JKRHeap::getSystemHeap, mCurrHeap, Nil, setCommon_heapSpecified, setCommon_mesgQueue.
JKRThread::~JKRThread()
References JKRFree, JKRFreeToHeap, mCurrHeap, mLink, mMesgArray, mStack, mThreadRecord, Nil, sThreadList.
virtual void * JKRThread::run()
References Nil.
void JKRThread::setCommon_mesgQueue(int mesg_count)
References JKRAllocFromHeap, mCurrHeap, mLink, mMesgArray, mMesgCount, mMesgQueue, sThreadList.
Referenced by JKRThread.
void JKRThread::setCommon_heapSpecified(size_t size, int priority)
References ALIGN_VAL, JKRAllocFromHeap, mCurrHeap, mStack, mStackSize, mThreadRecord, start.
Referenced by JKRThread.
void * JKRThread::start(void *)
Referenced by setCommon_heapSpecified.